### ISSUE TITLE
위젯 출력시 컨테이너에 넣지 않고 출력하는 기능

### ISSUE THREAD

**Issue by LI-NA** [xpressengine/xe-core#1000]
위젯을 보다 다양한 용도로 사용할 수 있게끔 원래 들어가는 xe-widget-wrapper div가 없이 위젯 코드만 출력할 수 있는 기능이 있었으면 합니다.
(예를들면 위젯을 이용해 게시판 한가운데 tr 로 항목을 집어넣을때 유용하더군요)

적용 가능성 고려해보시고, 괜찮다 싶으면 의견 남겨주세요.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
