### ISSUE TITLE
숫자아이디지원

### ISSUE THREAD

**Issue by jinsan09** [xpressengine/xe-core#1020]
처음 이곳에 글을 남깁니다.
사정상 숫자로만된 아이디를 사용하게 되는데요...
회원설정에서 아이디를 모두 숫자를 사용할 수 있도록 하면 좋을것 같습니다.
현재는 영문자를 포함하고 있어야 한다고 튕기는데요..
xe.min.js를 수정하여 사용하면 된다고 하시는데
코어에서 옵션이나, 체크형태를 기능을 넣어주면 좋을것 같아
이슈에 올려봅니다.
이곳에 이렇게 올리는게 적절한지도 잘 모르겠네요! ^^

**Comment by ned3y2k** [comment]
저도 비슷한 경우가 있어서 숫자아이디로 된 경우는 앞에 prefix 를 미리 붙여 넣고 로그인시 모듈 처리를 하여 아이디를 두번 검사도록 하게 만들어두었습니다.
