### ISSUE TITLE
게시물 열람시 포인트  부족 할 경우 부족하다는 메세지 출력 이상태에서 이전 페이지 갔다가 다시 해당 게시물 들어가면 열람가능 버그 

### ISSUE THREAD

**Issue by chm1974** [xpressengine/xe-core#1038]
게시물 열람시 포인트 차감 설정 후 해당 게시판의 게시물을 열람 할 경우 포인트 차감 후 포인트가
없을 경우 포인트가 부족하다는 메세지가 출력되며 게시물이 보이지 않음.  <-- 여기 까지는 정상

여기까지는 정상인데 이 상태에서 뒤로 가기 하거나 다른 페이지 이동 후 다시 게시물을 열람하면 포인트가 부족한데도 그냥 열람이 가능합니다.
확인 부탁 드립니다.

**Comment by sejin7940** [comment]
https://github.com/xpressengine/xe-core/pull/1197
