### ISSUE TITLE
게시판에서 url 링크 작동 안됨

### ISSUE THREAD

**Issue by fromhere** [xpressengine/xe-core#1052]
게시판에서 글 작성후, 혹은 이미지 삽입후에 해당 text나 이미지를 링크시키는 것이
정상작동안됩니다.

 이미지를 선택하고 편집기 상단의 url을 눌러 링크주소를 입력하면
링크주소가 이미지 밖으로 빠져나와 쓰여지고, 정작 이미지는 링크가 안됩니다.

 텍스트를 하이라이크 한 다음에 url을 눌러서 링크를 시켜도 마찬가지입니다.

텍스트 창에 있는 url 버튼을 클릭하는 순간 
선택된 text나 image의 하이라이트가 풀려 버리기 때문에 발생하는 현상입니다.

Xe 1.7.7.2  board 1.7.2에서 발생하는 문제입니다.
(다시 확인하니 Xe 1.7.5.7. board 1.4.8에서도 동일합니다.)
php버전은 5.2.17 과 5.3에서 동일하게 발생하고 있습니다

IE 11버전에서 발생합니다.  크롬에서는 정상작동됨

![link_test1](https://cloud.githubusercontent.com/assets/5973095/5100038/cc46dab0-6fe3-11e4-8344-3c373eb26e39.gif)

**Comment by bnu** [comment]
XpressEditor를 CKEditor로 대체 사용함으로 이슈 종료합니다.
