### ISSUE TITLE
위젯페이지에서 문서 작성시 제목 입력 못하는 문제

### ISSUE THREAD

**Issue by fromhere** [xpressengine/xe-core#1061]
위젯페이지에서 페이지수정>내용직접추가>를 통해 작성하는 문서의 경우
현재 제목을 입력할 수 있는 창이 없습니다.
(위젯페이지가 아닌  단독 문서페이지에서는 제목 입력 가능합니다)

 이 때문에 관리자 페이지 대시보드> 최근글에서 보면 
"제목이 없는 문서입니다"란 글들이 표시됩니다.
보기가 좋지 않고, 관리자가 한눈에 문서들이 어떤 문서인지 파악하기 힘듭니다.

 게시판이 아닌 위젯에서 만들어지는 문서들에서도 제목입력창을 만들어 주면 간단히 해결될 문제인듯

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
