### ISSUE TITLE
IE11 환경에서 XE 기본 에디터 (xpresseditor) 사용 시 형식 (제목/h 태그) 지정 불가능

### ISSUE THREAD

**Issue by snows96** [xpressengine/xe-core#1068]
process: 에디터에서 '형식' 콤보박스 (제목/h 태그) 선택
expected: 선택한 텍스트 혹은 문단이 해당하는 h태그로 지정 됨
instead: 반응 없음

**Comment by bnu** [comment]
XpressEditor를 CKEditor로 대체 사용함으로 이슈 종료합니다.
