### ISSUE TITLE
파일 업로더 교체

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#1086]

**Comment by misol** [comment]
Html5 도 같이 지원하는 업로더였으면 좋겠어요! 구글링 해보면 꽤 나와요 :)

**Comment by bnu** [comment]
@misol 고르기가 어렵네요.
plup가 좋은데 GPL이네요^^;

**Comment by misol** [comment]
@bnu https://github.com/blueimp/jQuery-File-Upload/wiki 이 업로더 어떤가요? MIT
라이선스라 큰 무리 없을 것 같아요.
검색하다가 업로더 모아놓은 페이지
http://designscrazed.org/html5-jquery-file-upload-scripts/ 발견했는데 여기도 한번 보세요.

그리고! AXISJ 업로더도 나름 괜찮아요.

2015년 1월 1일 목요일, bnu<notifications@github.com>님이 작성한 메시지:

**Comment by misol** [comment]
위에 제가 추천한 업로더 적용은 https://github.com/blueimp/jQuery-File-Upload/wiki/Setup#using-jquery-file-upload-ui-version-with-a-custom-server-side-upload-handler 참고

**Comment by ppleo** [comment]
뭐든 전..썸네일지정이 가능한 쪽으로...ㅋㅋㅋ

**Comment by anizen** [comment]
제가 사용하고 있는 업로더 입니다.(에디터컴포넌트에서 사용)

https://github.com/hayageek/jquery-upload-file

MIT 라이센스이며, 사용에는 크게 문제가 없을 듯 합니다.

**Comment by kijin** [comment]
PLUpload가 가장 좋은 것 같은데 (써봤습니다^^) 라이선스가 호환되지 않아서 ㅠ

차선책으로 @misol 님이 링크걸어주신 jQuery File Upload도 좋아 보입니다.

그러나 특정 라이브러리를 논의하기보다는 XE에 꼭 필요한 기능이 어떤 것인지 결정하고, 그 기능을 가장 잘 구현한 라이브러리를 찾는 것이 올바른 순서가 아닐까요? 예를 들면:

- 브라우저 지원은 어디까지? (IE10? IE8? IE6? 안드로이드와 iOS 버전은?)
- HTML5 업로더를 사용할 경우, HTML5 File API가 지원되지 않는 브라우저에서는 기존의 `<input type="file">` 또는 swfupload 등을 사용해서라도 최소한의 기능을 제공해야 하지 않는가?
- chunking 기능 지원이 있으면 좋은가? (이거 제대로 구현하면 새로운 세상이 열립니다. 서버측 설정 하나도 안 바꾸고 10G짜리 대용량 업로드 가능 ㅎㄷㄷ)
- 썸네일 생성/편집 기능과 연동이 필요한가?

그 밖에도 업로더에 필요한 기능에는 어떤 것이 있을까요?

**Comment by misol** [comment]
@kijin GPL이면 이를 이용해서 업로드 기본 기능을 구현한 것이기 때문에, XE의 라이선스도 GPL로 변경되어야 합니다.(에디터 '스킨이다'. 라고 주장하면 어떻게 될진 모르겠습니다.)

jQuery File Upload 에서 말씀 하신 기능을 찾아봤습니다.

- Chunk upload: 지원 https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads
- 브라우저 지원: 모바일 브라우저에서 다중 업로드 지원이 빈약 https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support
- 썸네일: XE 자체 서버 스크립트에서도 지원하지만 클라이언트 단에서도 지원하는 스크립트.

**Comment by ajkj** [comment]
GPL의 패키징 부분에는 논란이 있어 LGPL이 나왔고, 그래서 XE도 GPL에서 LGPL로 변경한걸로 알고있습니다.

legacy 브라우져를 위한 HTML5 File API/xmlhttprequest2 의 polyfill 인 moxie가있습니다..
plupload에서 만든 회사에서 배포중이고 LGPLv2 기반입니다. jQuery File Upload랑 잘만 합치면 ie8 이상은 지원이 가능하지 않을까요?

추가적으로 
- GitHub처럼 이미지를 Ctrl-V 만으로 업로드가 되는 기능이 있었으면 좋을것 같습니다. 이미지 업로드의 난이도가 매우 쉬워지는 장점이 있습니다.
- Chunking은 있으면 정말 좋을것 같습니다. 10MB 파일을 저속망(무선)상에서 올릴경우에 상당한 도움이 될것 같습니다. PC상에서 대용량 파일을 올리기에도 좋을 것 같고요.

**Comment by ajkj** [comment]
GPL의 패키징 부분에는 논란이 있어 LGPL이 나왔고, 그래서 XE도 GPL에서 LGPL로 변경한걸로 알고있습니다.

<del>
legacy 브라우져를 위한 HTML5 File API/xmlhttprequest2 의 polyfill 인 moxie가 있다고 들었습니다.
plupload에서 만든 회사에서 배포중이고 LGPLv2 기반입니다. jQuery File Upload랑 잘만 합치면 ie8 이상은 지원이 가능하지 않을까요?
https://github.com/moxiecode/moxie
</del>
GPL인데 LGPL로 잘못 보았네요.

추가적으로
- GitHub처럼 이미지를 Ctrl-V 만으로 업로드가 되는 기능이 있었으면 좋을것 같습니다. 이미지 업로드의 난이도가 매우 쉬워지는 장점이 있습니다.
- Chunking은 있으면 정말 좋을것 같습니다. 10MB 파일을 저속망(무선)상에서 올릴경우에 상당한 도움이 될것 같습니다. PC상에서 대용량 파일을 올리기에도 좋을 것 같고요.

**Comment by bnu** [comment]
@ajkj  CKEditor에 클립보드 이미지 업로드는 업로더 API와 맞추면 에디터에 어렵지 않게 넣을 수 있을 것 같습니다.

@misol 님이 추천해주신 라이브러리를 고려하고 있었으나 IE8에서 정상 동작하지 않는 문제가 있었습니다.

@anizen 추천해주신 라이브러리 괜찮네요. IE8에서 동작도 확인했습니다.

모바일이라 우선 간단히 남깁니다.

**Comment by misol** [comment]
@bnu 명세엔 6.0+ 지원이라고 써있었는데.. http://jquery.com/browser-support/ jQuery 2.x 라 그럴 수도 있을 것 같습니다.
어떤 걸로 선택되든 잘 정착되길! ㅋㅋ

**Comment by bnu** [comment]
@misol Plup 다음으로 가장 적당한 것 같아서 저도 1순위로 두고 있었는데, 혹시나 확인해보니 그렇네요. demo에 적용된 jQuery 는 1.11.1이었고, 1.8까지 낮춰서 확인해봤지만 마찬가지였습니다.

**Comment by bnu** [comment]
@kijin 고려해야 할 사항은 정리해서 본문에 업데이트 해두도록 하겠습니다.
이슈 작성 시 기재해놨어야 했는데, 정리가 덜 되어 제목만 덜렁 있었네요 ^^;

**Comment by dokdo2005** [comment]
http://www.xpressengine.com/index.php?mid=download&package_id=22450636

공홈 자료실에도 올라와 있기도 하고 실제 저희 사이트에도 사용중인데 괜찮더라구요.
Ajax 기반에다 HTML5 지원됩니다.

**Comment by misol** [comment]
@bnu 님 고생하셨어요!!
