### ISSUE TITLE
위지윅 에디터 교체

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#1087]
* [ ] 쪽지 보내기에서 팝업 창 크기 조절 문제
* [ ] 어두운 배경의 컬러셋 추가

**Comment by ioz2014** [comment]
다음에디터나 스마트에디터2는 논외가 되려나요?  사용자 입장에서는 외산 에디터보다 훨씬 친숙하고 편리할듯합니다

**Comment by YJSoft** [comment]
@ioz2014 현재 코어에 포함되어 배포중인 XpressEditor가 스마트 에디터의 변형판입니다.

**Comment by ioz2014** [comment]
스마트에디터2는 스마트에디터의 판올림버전입니다.

다음에디터도 판올림을 했습니다

모두 웹표준

**Comment by ioz2014** [comment]
이나 호환성문제에 대해서 타 외산에디터에 뒤지지는 않습니다

**Comment by izuzero** [comment]
네이버 스마트에디터2를 포팅해보고 있습니다. 잘 될지는 모르겠네요.

**Comment by ajkj** [comment]
스마트 에디터2가 2014년 4월 이후로 추가적인 유지보수가 없는것 처럼 보입니다. 차후에 XE에디터처럼 버그가 발생할경우 자체적으로 처리해야 할 일이 있을지도 모른다는 생각이 드네요.
http://dev.naver.com/projects/smarteditor/download

다음 에디터는 지금 상대적으로 활발하게 유지보수가 잘 되고 있는것 
https://github.com/daumcorp/DaumEditor/releases

추후 유지보수를 고려하면, 에디터 전문 기업에서 오픈소스(LGPL) 및 상용 Dual License가 적용중인 제품을 이용하는게 좋지 않을까요?

**Comment by YJSoft** [comment]
@ioz2014 @izuzero 스마트 에디터 2는 진도 프레임워크 기반으로, 그대로 포팅작업만 거쳐 사용한다 해도 XE에 불러와지는 라이브러리가 jQuery와 진도 프레임워크 2개가 되는 문제점이 있습니다.(현재의 XpressEditor는 스마트 에디터를 jQuery 기반으로 수정한 것입니다).

**Comment by lansi951** [comment]
스마트 에디터나 다음 에디터는 한국웹에 맞춤이긴 하지만 그것 말고는 tiny나 cke보다 많이 떨어집니다.
유저 참여도도 적고, 충돌도 많이 나고, 확장성이 많이 떨어집니다. 메뉴얼도 제대로 없을 뿐더러 사용하기도 어렵습니다.
글로벌 사용자를 고려해서라도 tiny나 cke로 갔으면 좋겠습니다.

**Comment by bnu** [comment]
교체 대상 에디터는 CKEditor로 선택했습니다.
TinyMCE, CKEditor 모두 활성화된 프로젝트이고, 특성 차이는 있지만 브라우저 지원, 기본 기능은 큰 차이는 없어 보입니다.
의견 주신 DaumEditor 및 SmartEditor은 프로젝트 활성화 정도를 고려하여 대상에서 제외하였습니다.

이미 [적용 사례](https://www.xpressengine.com/index.php?act=&mid=download&vid=&category=&keyword=ckeditor)가 있으나, CKEditor 최신 버전으로 업그레이드 시 일부 대응이 필요합니다.

**Comment by reebit1990** [comment]
CKEditor 반응 속도가 떨어지는데 ㅜㅜ

**Comment by bnu** [comment]
컬러셋 추가(CKEditor의 스킨) 및 content style 추가 중

**Comment by bnu** [comment]
TODO : 쪽지 보내기에서 팝업 창 크기 조절 문제 있음

**Comment by ajkj** [comment]
이미 많이 늦은것 같긴 하지만, TinyMCE가 아닌 CKEditor를 선택하신 이유를 알 수 있을까요?

xe-core 차원에서 CSP 적용이 가능한지 찾아보고 테스트해 보았는데, CKEditor가 인해 CSP를 적용하는데에 있어서 가장 큰 걸림돌인것으로 보였습니다.
```
layout/skin.html element의 onclick attribute는 자동화 변환이 가능해 보였고,
<img id="xe_uniq_id" onerror="do1;()do2();">
<script>
var dom = document.getElementById('xe_uniq_id');
var a = function(event){
do1();do2();
}
a = a.bind(dom);
dom.onerror= a;
</script>
dynamic js는
<script src="https://example.com/?act=getJS&position=header&token=abcdef0123456789"></script> 
형태로 처리가 가능해 보였습니다.
```

CSP를 적용 하면 수많은 XSS 공격을 브라우져 단에서 원천적으로 차단 할 수 있을 것이라 생각합니다. 그러나 core의 기본 에디터를 CKEditor로 채택한다면 차후라도 CSP 지원이 매우 힘들어 질것 같았습니다. 다만 나중에라도 CSP를 지원 하기 힘들것 같다고 생각 하신다면 CKEditor도 괜찮을것 같습니다.

tinymce는 현재 사용시 에러가 나지만, 에러가 나는 부분도 간단하게 수정이 가능한것 같습니다.
https://github.com/tinymce/tinymce/pull/441
https://github.com/tinymce/tinymce-dist/blob/master/tinymce.js#L29356
https://github.com/tinymce/tinymce-dist/blob/master/tinymce.js#L29389

http://dev.ckeditor.com/ticket/8584

**Comment by kijin** [comment]
@ajkj Content-Security-Policy를 말씀하시는 거죠? 그거 적용하려면 건드려야 할 부분이 한두 군데가 아닐 텐데요...

해외 개발자들도 CSP 관련해서는 대부분 포기 상태이거나, 예외정책을 하도 많이 선언해서 헤더가 누더기가 되어버리곤 합니다 ㅠㅠ 에디터 외에도 구글 애널리틱스라든지, CSP 정책 하에서는 어림도 없는 것들이 현실적으로 너무나 많기 때문에... 만약 저라도 에디터를 선택하는 입장에 있다면 CSP 호환성은 한 0.01% 정도 고려하다 말겠습니다.

아무튼 XSS 방어 관련해서는 저도 다른 방법의 개선안을 제안해 본 적이 있는데 (#1267) ajkj님은 어떻게 생각하시는지요?

**Comment by ajkj** [comment]
저는 아예 불가능 에 가깝다는 생각이 들지 않았습니다. 수많은 inline script는 nonce를 이용하면 어렵지 않게 처리하면 가능해 보였고, 템플릿(HTML)상의 inline event handler는 템플릿을 처리하는 과정에서 자동분리가 가능해 보였습니다. 문제가 되는 부분 및 자동화 처리가 불가능해 보였던 부분은 CKEditor에 대대적으로 사용된 JS를 이용하여 브라우져에서 동적으로 삽입한 html event handler ``` var a = '<img onclick="do(); return false">' ``` 인데 이러한 부분을 사용한 건 현재 XE-core 내부에 많지 않아 보였습니다.

unsafe-inline 선언금지 + script src 제한 + x-content-options 만 걸어두어도 대부분의 XSS 방어는 되지 않을까 싶어요. 어떠한 방법 보다도 원천적인 차단이 가능해 보였습니다.

다만 CKEditor를 채택한다면, 앞으로 CSP는 불가능해 보였습니다.

**Comment by kijin** [comment]
코어에서 사용하는 스크립트는 어떻게든 고쳐볼 수 있을지 몰라도, 현존하는 XE 1.x의 써드파티 스킨/레이아웃/모듈/애드온 생태계를 생각하면 불가능에 가깝습니다. 사실상 `<script>` 태그와 `on_____` 이벤트 사용을 금지하는 꼴이 되어버리니까요.

XE3이라면 가능할지도? ㅎㅎ 아마 XE3에서는 에디터를 다시 선택하게 될지도 모르죠.

**Comment by ajkj** [comment]
저도 3rd party의 문제는 동의합니다, 그래도 core 차원에서 지원 할 수 있는 여지를 남겨두는것과 앞으로 적용 할 수 없음을 못 박고 가는 것에는 큰 차이가 있을 것 같습니다. CSP 가 여러모로 까다롭고 적용하는데에 넘어야 할 산이 많긴 하지만, 그 어떠한 방법보다도 XSS에 강력하게 대처가 가능할것이라 생각되어서 그렇습니다.

그리고 별개의 이야기이긴 하지만, XE를 이용한 HybridApp (Adobe phonegap/Apache Cordova)을 안전하게 지원하기 위해서는 CSP가 필수적이라고 생각합니다. 폰갭이나 Cordova에서 XSS가 뚫리면 웹과는 비교도 할 수 없을 정도로 위험하다고 생각해서 그렇습니다.

**Comment by reebit1990** [comment]
2015-04-13 14:01 GMT+09:00 bnu <notifications@github.com>:

**Comment by reebit1990** [comment]
메일 입니다!

2015-04-13 22:11 GMT+09:00 이승철 <reebit1990@gmail.com>:

**Comment by reebit1990** [comment]
2015-04-13 22:18 GMT+09:00 이승철 <reebit1990@gmail.com>:

**Comment by reebit1990** [comment]
잘못 보냈습니다. 죄송합니다..

2015-04-13 14:01 GMT+09:00 bnu <notifications@github.com>:
