### ISSUE TITLE
1.7.8 통합검색 첨부파일 mp3 일경우 문제점

### ISSUE THREAD

**Issue by botserv** [xpressengine/xe-core#1113]
기존에 XE 1.4.X 에서 1.7.8 로 업데이트 하면서

통합검색기능 이용시

mp3/wav 파일을 동영상으로 인식하여 다운로드를 실행해버린다는 문제점이 있습니다.

mp3/wav 오디오 재생 확장명일경우에는 이미지/동영상으로 분류 할 것이아니라

파일 목록으로 이동되어야 될 것 같습니다.

또는 

혹은 이미지 동영상의 프리뷰 기능 때문에 강제 다운로드가 되어버리는 현상을 막기 위해
오디오 확장명은 프리뷰 옵션이 적용안되면 될 것같습니다.

**Comment by Xvezda** [comment]
mp3파일뿐만 아니라 swf파일등도 똑같은 문제점이 있네요.
preview에서 미디어의 URL이 아니라 다운로드 URL을 사용해서 발생한 문제인것으로 보입니다.

**Comment by botserv** [comment]
@Xvezda 해당 수정으로 문제점은 해결되었습니다.
다만 IE버전에서는 동영상이 AutoPlay되지 않으나

구글 크롬브라우저에서는 동영상이 자동 시작되어버리는데, 만약 첨부파일이 비슷하여
검색결과가 많을경우 동시에 여러 음악파일이 재생되는 문제점이 있습니다.autoplay 값이
false 하도록 넣어주면 더 좋을 것같습니다.

**Comment by bnu** [comment]
@Xvezda @botserv 오늘 중 autoplay=false까지 처리되면 1.7.9에 포함하여 배포하도록 하겠습니다.

**Comment by Xvezda** [comment]
크롬에서 autostart="false"가 있음에도 자동재생이 되는문제가 있는것 같은데, 해결방법이 있나요?
@botserv 님 께서 알려주신 autoplay="false" 를 사용해도 같은 문제가 있는것 같습니다.

**Comment by bnu** [comment]
`autostart="0"`으로 해보면 어떨까요?

**Comment by botserv** [comment]
@bnu 1.7.9 업데이트 이후에도 구글 크롬브라우저에서 지속적인 여러개의 파일이 자동 재생되는 문제와

모바일환경 안드로이드 기본 인터넷에서 통합검색시 영상의 첨부파일을 모두 다 다운로드 해버리는 문제점이 있습니다.

**Comment by bnu** [comment]
@botserv 1.7.9에서는 이 문제가 수정되지 않았습니다. 진행 중인 이슈이며 차기 버전에 처리 예정입니다.

**Comment by botserv** [comment]
@bnu 이 문제가 언제쯤 해결될까요?? 패치를 애타게 기다리고 있습니다 ㅠ_ㅠ

**Comment by bnu** [comment]
fixed #1126
