### ISSUE TITLE
XE 최초 설치시 LGPL 한글 번역본 링크 오류

### ISSUE THREAD

**Issue by misol** [xpressengine/xe-core#1119]
최초 설치시 ./index.php?act=dispInstallLicenseAgreement 에 나오는 

* 한국어 번역문 (비공식) : GNU Lesser General Public License, version 2.1

항목의 링크가 [영문 페이지](http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html)로 되어 있습니다. 의도와 다른 링크 같아 이슈를 등록합니다.

**Comment by dorami** [comment]
http://korea.gnu.org/people/chsong/copyleft/lgpl.ko.html

**Comment by misol** [comment]
적용 방법 마지막 부분이 충격적이네요..

--------------
만약, 라이브러리의 저작자가 학교나 기업과 같은 단체나 기관에 프로그래머로 고용되어 있다면 라이브러리의 자유로운 배포를 위해서 고용주나 해당 기관장으로부터 라이브러리에 대한 저작권 포기 각서를 받아야 합니다. 예를 들면 다음과 같은 형식이 될 수 있다. (아래의 문구를 실제로 사용할 경우에는 예로 사용된 이름들을 실제 이름으로 대체하면 됩니다.)
