### ISSUE TITLE
모바일 회원가입에서 생일 작동안함

### ISSUE THREAD

**Issue by dorami** [xpressengine/xe-core#1122]
모바일 회원가입에서 생일 부분을 클릭하면 아무런 반응이 없습니다.

**Comment by KissT0XE** [comment]
PC버전에서 보기를 이용하니 모바일에서도 사용이 가능하네요.
모바일 기본 브라우저에서도 사용할 수 있도록 대체 방안을 찾는 것이 좋을 것 같습니다.

**Comment by wookho** [comment]
왜 이 이슈는 다뤄지지 않는걸까요.,..?
