### ISSUE TITLE
anti-access 모듈페이지가 하얀색으로 열리지 않습니다.

### ISSUE THREAD

**Issue by jazzheart** [xpressengine/xe-core#1123]
http://www.jazzheart.com

늘 쉬운 업데이트로 코어를 최신상태로 유지해왔습니다.
오늘 혹시나 들러봤는데,
anti-access 모듈페이지가 하얗게 열리질 않고 있네요...

전문 지식이 없어서 늘 Xpressengine.com 에서 시키는 대로 클릭만 하는 사람입니다.
혹시 이에 대해 잘 아시거나 해결책을 아시는 분이 계시다면
답글 남겨주시면 감사하겠습니다.

**Comment by KissT0XE** [comment]
해당 모듈 개발자에게 먼저 연락해보시고, 공홈의 묻고답하기 란을 이용해주세요.
XE팀이 Github 활동과 관련된 세부 규칙 등을 따로 알리지는 않았지만, 서드 파티의 모듈일 경우에는 (코어에 문제가 없는 이상) 해당 개발자나 묻고 답하기에 질문을 올리는 것이 올바르다고 사료됩니다.

**Comment by fromthere** [comment]
서드파티 모듈은 서드파티 모듈 제작자에게 문의해주세요
이곳은 XE 코어 관련해서만 올리는 공간입니다.

**Comment by jazzheart** [comment]
앗 네 제가 잘 몰라서 여기에 글을 남겼습니다.
알려주셔서 감사합니다.
