### ISSUE TITLE
제로보드 게시판 분류 설정 문제 해결책 없나요?

### ISSUE THREAD

**Issue by hijino0507** [xpressengine/xe-core#1124]
제로보드 버젼 : 1.7.7.2 

서버환경...

패키지를 호스트하는 중    20-1000
서버 이름   s1
cPanel Version  11.46.1 (build 4)
테마  paper_lantern
Apache 버전   2.2.29
PHP 버전  5.4.35
MySQL 버전    5.5.40-cll
아키텍처    x86_64
운영 체제   linux
Sendmail 경로 /usr/sbin/sendmail
PERL 경로 /usr/bin/perl
Perl 버전 5.10.1
커널 버전   2.6.32-504.1.3.el6.x86_64

문제점...

제로보드 게시 - 설정 - 분류 에서 분류 항목이 나오질 않습니다.
분류 항목 추가 아이콘 + 는 표시됩니다.

해결해보려 했던 나름의 방법들...
1. 레이아웃 적용 없이 게시판만 설정해봤음. - 안됨.
2. 게시판의 스킨을 제로보드 기본 스킨으로 해봤음 - 안됨.
3. 게시판 - 설정 - 분류 - 캐쉬파일 재설정 해봤음 - 안됨.
4. FTP /public_html/files/cache/document_category 폴더 권한 설정해봤음 - 안됨
5. FTP /public_html/files/cache/document_category 폴더 내 파일 삭제해봤음 - 안됨
6. 제로보드 관리자 메인페이지 하단 - 캐쉬파일 재생성 해봤음 - 안됨.

서버정보 출력.........

[XE Server Environment 2015-01-02]

location : ko
package : XE
app : Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
xe_version : 1.7.7.2
php : 5.4.35
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, calendar, curl, ftp, gd, iconv, mbstring, mcrypt, mysql, mysqli, mysqlnd, phar, imap, simplexml, soap, sockets, exif, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, pdo_sqlite, pdo_mysql, ioncube loader
module : adminlogging(1.7), attendance(5.0.5), board(1.7.2), contact(1.7.0.2), krzip(1.0), syndication(4.0)
addon : adminlogging(1.7), cameron_mobile_nav(2.0), cameron_plugin(1.1), captcha_member(1.7), oembed(1.0)
layout : neat(1.4.7), xe_official(1.7), user_layout(1.7)
widget : cameronCategory(1.0), cameronListOne(1.0), cameronSlider(1.0.1), cameronWebzineTop(1.0), counter_status(1.7), treasurej_popular(1.0.5)
widgetstyle : neat_more(1.0), neat_side(0.1), neat_slider_ws(1.0), simple(1.7)
max_file_uploads : 20
post_max_size : 8M
memory_limit : 512M

해결책을 아시는분은 좀 알려주세요. ㅠ.ㅠ
저와 같은 문제를 안고있는분들이 좀 있네요.

hijino0507@gmail.com

**Comment by lansi951** [comment]
서버 보안 설정 때문에 분류가 안 나오는 경우가 있습니다
이 경우 PHP 설정 고치면 해결 될 겁니다

그리고 제로보드가 아니라 XE입니다...

**Comment by hijino0507** [comment]
랜시님 안녕하세요.
php 설정이라 함은 xe 관리자 페이지의 설정 - ftp 설정을 말씀하시는건가요?

**Comment by lansi951** [comment]
랑시입니다;

서버에서 php.ini 설정 얘기입니다
일반 호스팅 사용자시면 호스팅 업체에 연락해보세요

**Comment by hijino0507** [comment]
랜시님~
이 문제를 해결하기 위해서는 php.ini 내에서 어떤걸 설정해야하는지요.
구체적으로 알려주실순 없을까요...

**Comment by hijino0507** [comment]
안녕하세요. 랑시님.
서버에서 php.ini 의 어떤 부분을 설정하면 분류 활성화가 정상적으로 작동되는지도 좀 알려주실순 없나요?

2015년 1월 2일 오후 1:45, Lansi <notifications@github.com>님이 작성:

**Comment by misol** [comment]
분류 설정이 게시판 글쓰기 페이지나 목록 페이지에서 나타나지 않는단 말씀이신가요?
관라자 설정 페이지에 조작이 불가능 하단 말씀이신가요?

**Comment by lansi951** [comment]
@hijino0507 죄송하지만 어떤 설정이었는지는 기억이 나지 않습니다.
오래전 일이라서요. 호스팅사에서 세팅해준 건 기억납니다. 그리고 보안 설정 문제였단 것두요.
그 설정 때문에 XE에서 만들어둔 카테고리 캐시 php 파일을 못 읽어들이더라구요.

@misol 분류 목록이 트리 메뉴에 출력이 안 된다는 말씀이신 듯 하네요.

**Comment by misol** [comment]
설정은 되는데, 목록이나 글쓰기 페이지에서 안나오는 문제라면 게시판 기본 설정 부분에서 "분류 사용" 체크도 해주셔야 합니다.

**Comment by hijino0507** [comment]
@misol 게시판에서는 정상적으로 출력이 됩니다. @lansi951 님이 언급하신대로 분류 목록이 트리메뉴에 출력이 안된다는 문제점입니다.

**Comment by gerox2n** [comment]
저도 같은 증상이 발생합니다. 다른 부분에선 잘 작동하는데 분류 관리 페이지에서 xml로 받아오는 데에서만 오류가 발생하네요.. 캐시파일을 재생성해도 같은 문제가 발생합니다.

/files/cache/document_category/205005.xml.php
![catxml](https://cloud.githubusercontent.com/assets/7563270/6433206/16f4263a-c0ac-11e4-9d9b-487a6b9abc82.png)

**Comment by misol** [comment]
text 부분이 비어있군요?!

**Comment by gerox2n** [comment]
@misol 네. DB상에도 있고 게시판 스킨에서도 잘 뜨는데 관리 화면에서 xml로 받아올 때만 비어 있습니다.

**Comment by eondcom** [comment]
아래 서버에서도 동일한 증상이 있어서 찾아왔습니다. ㅠㅠ

[XE Server Environment 2017-02-24]

app : nginx/1.11.10
xe_version : 1.8.21
php : 7.0.16-3+deb.sury.org~xenial+1
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, libxml, openssl, zlib, cgi-fcgi, mysqlnd, xml, calendar, curl, mbstring, fileinfo, ftp, gd, gettext, iconv, exif, mysqli, pdo_mysql, phar, readline, shmop, simplexml, sockets, sysvmsg, sysvsem, sysvshm, wddx, xmlreader, xmlwriter, xsl, zend opcache
