### ISSUE TITLE
통합검색 역인글

### ISSUE THREAD

**Issue by conory** [xpressengine/xe-core#1128]
http://www.conory.com/index.php?act=IS&is_keyword=%EC%BD%94%EB%85%B8%EB%A6%AC&mid=home&where=trackback

core에서 역인글(트랙백)모듈이 빠지면서... 필요가 없어진 트랙백 검색기능입니다. 

제거해야 되지않을까요?

**Comment by bnu** [comment]
트랙백 모듈 존재여부에 따라 실제 검색은 처리되지 않습니다. 다만, 트랙백 검색 링크가 나타나는 부분도 트랙백 모듈 여부에 따라 감춰야하겠네요.
