### ISSUE TITLE
POST GET에 대하여 null byte 체크를 하면 어떨까요?

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#1129]
null byte(U+0000, "\0")는 일반 이용자는 특별한 방법을 사용하지 않는 이상 작성할 수 없고, 클라이언트단 js에서도 매우 특별한 일이 있지 않는 한 사용할 일이 없는 문자열 입니다.

php상의 변수나 file 입출력에서 null byte는 문제를 만들면 만들지, 그 이외에는 전혀 도움이 되지 않는 문자열 이라는 생각이 들었습니다.

Context가 생성되는 시점에 null byte가 post get에 존재하는지 확인후 해당 문자열이 들어가면 무조건적으로 요청을 차단시키는건 어떨까요? null byte로 인한 모든 문제를 사전에 차단 시킬 수 있는 장점이 있을것 같습니다.

한편 그렇게 할 경우 발생할 수 있는 문제가 있을까요?

**Comment by izuzero** [comment]
[관련 글](https://www.xpressengine.com/forum/22909975)

**Comment by KissT0XE** [comment]
일반적인 경우에 있어서 null byte가 생기지 않는다는 보장이 없을 뿐더러 (타 사이트의 글을 복사-붙여넣기 등)
XE로 사이트를 운영하는 사람들 중에는 null byte를 이용한, 혹은 응용하는 사람들이 있을 가능성이 있으므로 조심스래 접근해야 할 것 같습니다.

**Comment by Canto** [comment]
@KissT0XE php 에서 null byte 입력은 security check를 피해서 공격하는 공격방법의 중 하나입니다.
또한 일부 php함수에서 오작동을 할 가능성이 있기 때문에 필터링이 필요하다고 생각됩니다.

**Comment by ajkj** [comment]
사실 php 5.3.4 이상에서는 파일경로상에 null byte가 들어가면, 에러를 뿜어서 안전하다고 하는데, 그래도 혹시나 하는 부분이 있어서 이슈를 올려보았어요.

XE와 연동되는 외부 프로그램에서 보안 취약점이 나올 우려가 있기도 하고요.
ex) XE---파일경로with \0--->DB---->연동프로그램 취약점 노출..
