### ISSUE TITLE
input size over than config in php.ini

### ISSUE THREAD

**Issue by hijino0507** [xpressengine/xe-core#1133]
안녕하세요.

게시판 설정 - 문서 첨부 용량을 2메가에서 10메가로 올렸는데요...

input size over than config in php.ini

메세지가 출력이 됩니다.

또한, 관리자는 제외라고 나오는데 관리자도 30메가 정도가 넘으니 나머지 첨부 목록에서 나머지 파일은 짤리고

30메가 이하로만 표시가 되는데요.

뭐가 문제일까요?

**Comment by KissT0XE** [comment]
php.ini에서 설정된 최대 파일 첨부 제한보다 높게 설정을 하셨네요. 영어를 읽어보시면 답이 나옵니다..
서버의 운영자시면 php.ini에서 해결하시면 됩니다.

만약 서버 운영자가 아니거나 php.ini를 수정할 수 없는 상황이라면 .htaccess 파일을 여시고 아래 구문을 추가해 보시길 바랍니다.

#server setting
php_value max_execution_time 3600
php_value upload_max_filesize 100M
php_value post_max_size 100M
php_value session.gc_maxlifetime 3600


더불어 이곳은 코어에 관한 이슈를 등록하는 곳이지 개인 또는 집단이 사이트를 운영하면서 생기는 단순한 설정상의 오류를 올리는 곳이 아님을 유념해주셨으면 합니다..
감사합니다.

**Comment by hijino0507** [comment]
아. 제가 검색이 부족해서인가요.
왜 이런곳을 통해야만 알짜 답변을 얻을수 있는걸까요.
정말 감사합니다. ㅠ.ㅠ
