### ISSUE TITLE
글 조회시 크롤러 조회수 관련

### ISSUE THREAD

**Issue by 3600s** [xpressengine/xe-core#1134]
최근 게시판에 글을 전체공개로 공개해 두었는데
새로 올린 게시물이 하루에 100건이 넘게 조회수가 증가하길래
무슨일인가 했더니 Googlebot이 신나게 크롤링 하고 있더라구요.
그래서 찾아보니 `isCrawler()`라는 함수가 있는데 
`documentItem::updateReadedCount()`함수에는 적용이 안되어 있더라구요.
그래서 일단은 제 사이트에만 `isCrawler()`함수를 `if`문에 추가해 아래와 같이 수정해 둔 상태입니다.
```php
function updateReadedCount()
{
	$oDocumentController = getController('document');
	if($oDocumentController->updateReadedCount($this) && !isCrawler())
	{
		$readed_count = $this->get('readed_count');
		$this->add('readed_count', $readed_count+1);
	}
}
```
[document.item.php:623](https://github.com/xpressengine/xe-core/blob/791149f02940b4ab2868b5193a5faeb91801fb8e/modules/document/document.item.php#L623)

향후 버전에는 위와 같이 적용할 계획이 있는지요? 적용이 되었으면 좋겠습니다.
아니면 위 사항을 확인 해 주시면 `develop`브랜치에 Commit해 두겠습니다.

**Comment by YJSoft** [comment]
@3600s #975 PR로 수정되어 있고 1.7.9에서 반영 예정입니다.

**Comment by 3600s** [comment]
Document Controller에 적용 되었군요!
방금 확인 했습니다 :)
고맙습니다!
