### ISSUE TITLE
IIS에서 URL 재작성 체크가 안되는 문제

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1135]
소켓 쿼리문이 C:/******/xe179//JUST/CHECK/REWRITE/files/config/tmpRewriteCheck.txt 과 같이 잘못 작성되어 URL 재작성 규칙을 등록해도 제대로 확인이 안됩니다.

**Comment by YJSoft** [comment]
## 문제 원인
IIS에서는 $_SERVER['document_root']가 C:\경로 와 같이 역슬래시를 경로 구분자로 사용하는 반면,_XE_PATH_에서는 슬래시를 경로 구분자로 사용하기에 오류가 발생할 수 있습니다.

## 해결책
윈도우 서버에서는 역슬래시를 슬래시로 치환해서 문제를 해결할 수 있습니다.

**Comment by bnu** [comment]
fixed f55f193
