### ISSUE TITLE
modules 스키마 pk 버그

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xe-core#1138]
modules 스키마에 `module` 필드가 pk로 지정되어있습니다.

버그인지 제가 사용을 잘못한건지 모르겠지만

이때문에 가상 사이트에서 설정이 필요한경우 

$oModuleController->insertModuleConfig 나 updateModuleconfig 함수를 실행했을때

duplicate 에러가뜨면서 저장이 되지않지요.

modules + site_srl 을 pk로 변경했더니 문제없이 잘 동작합니다.

**Comment by bnu** [comment]
module_config 말씀이시죠?

**Comment by XisoDev** [comment]
네 맞아요 ㅎ
