### ISSUE TITLE
회원 포인트 수정후 리스트로 이동되는 현상

### ISSUE THREAD

**Issue by botserv** [xpressengine/xe-core#1139]
XE 1.4.X 사용시에는 회원 포인트 목록에서 특정 회원을 검색한 뒤, 
포인트를 조정하여도 변경 된 후의 해당 회원의 URL위치에서 refresh 되었지만

최신코어에서는 회원 포인트 목록에서 특정 회원을 검색한 뒤, 
포인트를 조정해버리면 회원 포인트 목록 리스트로 넘어가버리는 문제가 있습니다.

그렇기 때문에 해당 회원의 포인트를 수정한 뒤 수정이 이상 없는지 확인하기 위해서는
페이지를 되돌아가거나 해당 회원을 다시 검색해야하는 불편함이 있습니다.

**Comment by botserv** [comment]
마찬가지로 첨부파일도, 검색해서 삭제/수정했을 때 리스트로 넘어가버리는 현상이 있네요.

**Comment by bnu** [comment]
duplicated #1056

**Comment by bnu** [comment]
@botserv 댓글로 작성해주신 내용을 별도 이슈로 작성 부탁드려요 :)
