### ISSUE TITLE
[Core 1.7.8] 게시판 확장변수 정렬문제

### ISSUE THREAD

**Issue by dmzvillager** [xpressengine/xe-core#1141]
1. 게시판에서 확장변수 검색후 확장변수를 정렬하면, 검색결과가 모두 사라(지워진다는 의미는 아님)집니다.
2. 게시판 설정->게시판 정보->고급->정렬방법에서 확장변수가 선택은 되지만, 저장버튼을 누르고 나면 문서번호로 설정 되어 있습니다. 즉, 확장변수가 선택이 안됩니다.

**Comment by sejin7940** [comment]
1. https://github.com/xpressengine/xe-core/pull/1142
2. https://github.com/xpressengine/xe-core/pull/1143

**Comment by ngleader** [comment]
@sejin7940 +1
