### ISSUE TITLE
1014 이슈 코드 적용 안되어있는데.. 패치내역엔 들어가있네요..

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xe-core#1151]
누락된 코드 확인이 많이 되네요 ㅠ..

확인 부탁드려효~ https://github.com/xpressengine/xe-core/pull/1014

https://github.com/xpressengine/xe-core/blob/release/1.7.9/modules/document/document.controller.php#L446

**Comment by qw5414** [comment]
저 코드에서
`$bUseHistory`
항목은 완전히 삭제 된 상태에서 올려져야 정상작동할 것으로 보여지네요.

저 항목을 안쓰는 경우에는 아무런 설정을 안햇을 경우  권한이 넘어가는 오류가 발생되는걸 확인했습니다.

어차피 지금은 코어 반영도 안되어있으니.. 저 끝에 $bUseHistory 만 지우면 될 것 같아요

**Comment by bnu** [comment]
fixed #1201
