### ISSUE TITLE
XML Request에서 0값을 전달 할 수 없음

### ISSUE THREAD

**Issue by CONORY** [xpressengine/xe-core#1154]
#1074 XML Request에서 object 및 array child argument를 전송할 수 없는 문제 고침

위 사항을 적용하니, 제가 제작한 모듈에서 문제가 발생했네요. 원인은 XML Request할때 0값을 받지못해서입니다.

Context.class.php 

	function _filterXmlVars($key, $val)
	{
		if(is_array($val))
		{
		.....
		$body = $this->_filterRequestVar($key, trim($val->body ? $val->body : ''), 0);
		if($body)
		{
			return $body;
		}
문제가 발생한 코드입니다. 저의 모듈에서 $val->body 이 값은 결국 0이기에 무시됩니다..

해결하기위해서는  isset() 요놈을 쓰면 되죠..

	function _filterXmlVars($key, $val)
	{
		if(is_array($val))
		{
		.....
		$body = $this->_filterRequestVar($key, trim(isset($val->body) ? $val->body : ''), 0);
		if(isset($body))
		{
			return $body;
		}

이렇게...

**Comment by misol** [comment]
@bnu merged 된 문제입니다.
