### ISSUE TITLE
1.7.9 이미지 본문삽입시 p태그 강제 삽입.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1158]
이로 인해 이미지 간격이 발생하여 해당 간격만큼 조정하기 어려워 졌습니다. 이전에 만들어 놓은 위젯 페이지의 이미지와 다른출력물의 조합으로 만들어 놓은 페이지에서 이미지 부분들이 p태그 만큼 틀어져 동일한 배열이 어려워져 이미지가 아닌 다른 출력물의 내부여백을 p태그 만큼 주어서 임시 해결했습니다.

**Comment by wookho** [comment]
![p](https://cloud.githubusercontent.com/assets/6590236/5735541/061184a4-9c0b-11e4-9b3e-5ee2e1a331bc.png)


에디터를 이용해 작성한 경우 위와 같이 공간이 발생해서 기존에 만들어 놓은  페이지가 대부분 저렇게 틀어졌습니다 . 

물론 에디터를 이용하지 않고 코드를 넣은 곳은 저렇게 공간이 발생하지 않구요. 같은 코드라도 결과물이 다르게 나옵니다.

에디터 작성중에 editor_component="image_link" 위 내용을 지우면 공간이 사라지지만 다시 등록을 하고 나면 위 코드가 되살아나서 다시 되풀이 됩니다. 저 공간을 없애려면 어떻게 해야 하는겁니까 ?

**Comment by qw5414** [comment]
xe/modules/editor/uploader.js
에서 insertUploadedFile 항목에 보면
426번째줄이 있습니다. 그 아래428번째 줄의 `\r\n<p><br /></p>\r\n` 문자를 지워보시는게 어떠신지요 ㅎ

/테스트는 안해봤어요./
