### ISSUE TITLE
파일 사이즈 관련 오류

### ISSUE THREAD

**Issue by hletrd** [xpressengine/xe-core#1164]
에디터에서, php.ini에서 upload_max_filesize를 MB가 아닌 다른 단위로 설정해도 무조건 MB단위로 인식하는 버그가 있습니다.

예를 들어 php.ini에서 upload_max_filesize가 8192M으로 설정되어 있으면 에디터에서 첨부파일 용량 제한이 8192MB로 정상적으로 표시되지만, upload_max_filesize를 8G로 설정하면 에디터에서 첨부파일 용량 제한이 8MB로 표시되어 정상적으로 첨부를 할 수 없는 버그가 있습니다.

**Comment by YJSoft** [comment]
관리자의 경우 설정을 무시하고 php.ini에서 최대 첨부 크기를 구해와서 적용하는데, 이때 단위에 대한 처리가 빠져 있어 생기는 문제입니다.

**Comment by misol** [comment]
#1182 에서 해결된 문제 같습니다. @bnu
