### ISSUE TITLE
1.7.9 현지 표준시 작동안함

### ISSUE THREAD

**Issue by issujun** [xpressengine/xe-core#1167]
어드민-설정-일반 에 현지 표준시 작동을 안합니다(어떤나라를 선택하던) 1.7.9 올리고 시간이 안맞아 서버문제인줄알았는데 1.7.8로 다운그레이드하니 현지표준시 +9로하면 한국시간으로 표기됩니다

**Comment by YJSoft** [comment]
http://yjsoft.zz.mu/xe/freeboard (테스트용 XE 사이트)

뭔가 이번버전이 여러모로 문제가 생기는 부분이 많네요...

**Comment by YJSoft** [comment]
@bnu #830 이 PR이후 발생하는 문제입니다.
표준시를 지원하도록 수정할 수 있으나 이경우 코드가 더 지저분해지는 관계로 #830 PR을 revert 하는게 나을것 같습니다.

**Comment by bnu** [comment]
fixed #1220
