### ISSUE TITLE
포인트에 따른 회원그룹 연동이 되지 않습니다.

### ISSUE THREAD

**Issue by eunjeung** [xpressengine/xe-core#1171]
포인트에 따른 회원그룹 연동이 되지 않습니다.
예전에는 되었던 것 같은데 요즘에는 되지 않네요.
특정 포인트 이상이 되면 자동으로 그룹이 바뀌었던 것 같은데
ㅠㅠ혹 오류인건가요 확인 부탁드립니다.

**Comment by YJSoft** [comment]
포인트를 입력하시는게 아니라 레벨을 입력하셔야 합니다
해당 레벨이 되었을때 그룹이 변경됩니다.

설정을 다시한번 확인해주세요.
