### ISSUE TITLE
파일첨부 허용확장자 대소문자구별

### ISSUE THREAD

**Issue by DooSanBaik** [xpressengine/xe-core#1176]
허용확장자를 소문자로 등록시 대문자로된 확장자는 업로드가 불가
https://github.com/xpressengine/xe-core/commit/c9961fa9266b5df96cb4b0ba166830eb6d700b49
위 링크의 패치가 적용되면서부터 문제가 발생하며 해당 패치를 이전으로 롤백하면
지정한 확장자의 대소문자 구별없이 잘 업로드가 되며
지정하지않은 확장자 차단도 정상으로 이루어짐

**Comment by izuzero** [comment]
설정의 확장자와 업로드할 확장자에 strtolower 또는 strtoupper 함수를 적용해야 함.

**Comment by akasima** [comment]
#1104 문제 해결
