### ISSUE TITLE
1.7.9 업데이트 후 모바일 이미지 조절 애드온 문제요

### ISSUE THREAD

**Issue by silhwang** [xpressengine/xe-core#1178]
sejin7940_mobile_resize
모바일 이미지 조절 애드온입니다.

기존 1.7.5 버전에서 안되길래 포기하고 있다가

1.7.8 버전 업데이트 하니 정상작동 하더라구요.

그 이후 최근 1.7.9 업데이트로 또 작동을 안합니다.

혹시 원인이 있을까요?

**Comment by izuzero** [comment]
여기는 서드파티 상품에 대한 질문을 올리는 곳이 아니에요. 세진님 홈페이지를 방문하셔서 물어보세요.
