### ISSUE TITLE
1.7.9 업데이트후 접속통계 자세히 보기가 오류가 나타납니다

### ISSUE THREAD

**Issue by sin007xx** [xpressengine/xe-core#1179]
1.7.9 업데이트 이후 데시보드 화면에서 

순방문자 페이지뷰 나오는 곳에서 자세히를 클릭하면 오류가 나옵니다

DateTime::__construct() [datetime.--construct]: Failed to parse time string (Ymd) at position 0 (Y): The timezone could not be found in the database

오류는 이렇게 나오는데 DB가 꼬여 버렸나요 머가 문제인가요 제가 초보라 잘 해결할줄 몰라서 문의 드립니다 
답변부탁드릴께요 
감사합니다 ㅎㅎ

**Comment by izuzero** [comment]
https://github.com/xpressengine/xe-core/commit/c068d6295d6d186857967b84a233594697c6d223
이 커밋에 의한 오류인 건 아닌지 확인 바랍니다. @bnu

**Comment by qw5414** [comment]
해결이 안되셧나요?
https://github.com/swhite523/xe-core/commit/ce8423c9153605a5df57330b79f666c0d8ba3519

이거대로 한번 수정해보시겟어요?

**Comment by sin007xx** [comment]
위에 두가지 방법중에 1번째 방법은 1.7.9 업데이트 후에 확인해보니 1번재 처럼 변경되어 있습니다 
그래서 안되고 2번째 처럼 해도 또다른 오류가 나오네요 ㅜㅜ 
1.7.8에서는 되었는데 1.7.9에서 갑자기 안되네요 
답변주신 두분다 감사합니다 아직 해결이 안되었습니다 
많은 답변 부탁드릴께요 ㅜㅜ

**Comment by izuzero** [comment]
@sin007xx 또 다른 오류가 나왔다면 그 오류까지 올려주셔야 해결할 수 있는 방법이 생깁니다.

**Comment by sin007xx** [comment]
@izuzero 또다른 오류는 이렇게 나오네요 ㅜㅜ

Parse error: syntax error, unexpected '&' in /home1/nkorea/public_html/zbxe/classes/template/TemplateHandler.class.php(373) : eval()'d code on line 11

**Comment by sin007xx** [comment]
@izuzero 두번째 주신분 방법대로 수정하니까 저렇게 오류가 나오게 되네요

**Comment by qw5414** [comment]
@sin007xx 1.7.9 버전 코어재대로 업데이트 안된 것 같은데요?

기본적으로 XE1.7.9 버전은 @izuzero 님이 올려주신 코드와 제 코드가 둘다 정상적으로 반영이 되어있는 코드인데, 직접 코드를 수정 하여서 다시 오류 생겼다는 부분은 어떤 부분이 수정이 이루어지지 않앗다는 것으로 보여집니다.

1.7.9 버전의 최신코어를 부분설치가 아닌 전체 설치를 통해서 다시 설치해보세요.

**Comment by sin007xx** [comment]
@qw5414 답변주신 방법대로 변경을 하니 이렇게 새로운 에러가 나타나네요

Parse error: syntax error, unexpected '&' in /home1/nkorea/public_html/zbxe/classes/template/TemplateHandler.class.php(373) : eval()'d code on line 11

**Comment by qw5414** [comment]
@sin007xx 전체코어를 받아서 파일질라 덮어쓰기 방법으로 업데이트 해보세요.

**Comment by sin007xx** [comment]
@qw5414 님이 답변주신 코드는 1.7.9 버전에서 수정이 안되있어서 알려주신대로 수정하니 위에처럼
에러가 떴습니다 
그럼 코어를 전체를 다시 설치 하면 레이어아웃 이라던가 게시판 등 홈페이지가 전체 설치 한다고 해서 변경되지는 않을까요 제가 홈페이지 만들면서 수정한 부분이 조금 있어서 변경이 되면 ㅜㅜ
또 힘들어 질것 같아서요 ㅎㅎ 제가 좀 많이 초보라 그렇습니다 ㅜㅜ 죄송합니다 
많이 가르쳐주시면 감사히 배우겠습니다 ^^

**Comment by qw5414** [comment]
@sin007xx 그러니 말씀드리는겁니다.

공홈 기준으로 1.7.9버전에서 해당 제가 말씀드린 코드와 @izuzero 님이 올리신 커밋 내용이 둘다 적용되어있는 코드가 들어가 있습니다. 근데 그 코드가 반영이 안되있다는 말씀은 업데이트시 문제가 있엇다고 보여지는 것이지요. 그래서 재 업데이트 시도 해보라고 말씀드린 것입니다.

**Comment by sin007xx** [comment]
@qw5414 방금 체인지 부분다시 파일질라로 덮어쓰기 해서 재업데이트 했는데 똑같은 증상이네요 
코어전체를 새로 업데이트 해야하나요 그럼 괜찮아 질려나요

**Comment by qw5414** [comment]
@sin007xx 직업 코드가 수정된 부분이 있다면. 그 수정을 햇던 부분은 항상 메모를 통해서 기억하시고, 업데이트 진행을 하시는것이 좋습니다.

해당 코어 업데이트가 보안 업데이트와 같은 중요업데이트도 항상 들어가 있기 때문에, 자주자주 하는편이 좋기 때문이지요.

그리고, 초보자의 경우(무시하는것 아니에요..ㅠ 저도 경험을 통한..) 직업 코어코드를 수정하는 경우 잘못된 부분을 재대로 인지 못하기 때문에 왼만하면 자기가 직접 수정을 통한 코어 업데이트를 권고하지 않는 편입니다.

혹시 만일 전체 업데이트이후 문제가 발생된다면 서버의 간단한 사양을 기제해서 알려주세요
(PHP버전, 코어버전, 디비방식, 업데이트시 사용한 FTP프로그램등)

**Comment by sin007xx** [comment]
@qw5414 감사합니다 ^^ 제가 크게 수정한건 아니고 간단하게 수정한거라 크게 문제는 되지 않을것 같습니다 서버 사양은 제가 개인 nas(큐냅)로 현재 돌리고 있습니다 
이런말하면 답답하시겠지만 ㅎㅎㅎ 부끄럽네요 
php버전 mysql  이건 잘모르겠어요ㅜㅜ 어떻게 확인하는지 잘몰라서 
코어버전은? 1.7.9 이거 말씀인가요 ㅎㅎ 바보같아서 죄송합니다 
디비방식은 phpmyadmin 이건가요 버전이 4.1.13 이렇게 되어있네요 
ftp는 파일질라 쓰고 있습니다 ㅜㅜ

**Comment by qw5414** [comment]
@sin007xx 
업데이트시 1.7.7이하 버전에서 사용하시다가 업데이트 하신건가요?

@izuzero 님이 링크하신 커밋내용은 1.7.9버전에서 패치되었고, 제가 링크한 코드는 1.7.8버전에서 패치되었네요

만일 1.7,7이하 버전에서 `xe.1.7.9.changed`와 같은 파일으로 업데이트 하면 당연히 문제 생기게 됩니다.
xe.1.7.9.changed 파일은 매 버전마다 업데이트 할 경우에만 생기지 않습니다.

## 예
1.7.8->1.7.9 업데이트시 1.7.8.1 버전이 있을 경우 1.7.8.1 버전을 업데이트 한 뒤 1.7.9버전을 업데이트 해야함...


만일 이렇게 하지 않을 경우에는 전체 코어를 덮어 씌우는 방법으로 한번만 진행하셔도 무방합니다.

아무튼, 코어 업데이트시 반영이 되지 않는 파일로 인한 문제로 보여집니다.

**Comment by sin007xx** [comment]
@qw5414 정확한 지적이십니다 제가 1.7.7에서 바로 1.7.9버전으로 체인지만 업데이트 했습니다 
그래서그런가 봅니다 전체 업데이트 해보겠습니다 대단히 감사합니다 ^^

**Comment by sin007xx** [comment]
@qw5414 감사합니다 해결되었습니다 지적해주신대로 업데이트를 건너 뛰어서 그렇게 되었습니다
전체를 새로 업데이트 하니 정상적으로 해결되었습니다 늦은밤 정말정말 감사합니다
