### ISSUE TITLE
(#1120) 미솔님의 한글도메인 해결 방안에 대한 개선안.

### ISSUE THREAD

**Issue by andjfrrk** [xpressengine/xe-core#1181]
https://github.com/xpressengine/xe-core/pull/1120 의 방법대로 하면 IE11만 해결되고 IE789는 여전히 안됩니다.
포럼에 개선한 내용을 올렸고, 미솔님도 해당 글을 보셨기에 여기에 옮깁니다.

git을 쓸 줄 몰라 해당 코드를 이 곳에 직접 씁니다.(죄송합니다.)
line 번호는 수정하지 않은 XE 원본 1.7.9를 기준으로 합니다.

- 문제 : 한글도메인과 IE에서 글쓰기 뿐만 아니라, 회원가입, 관리자 페이지 등 ajax가 쓰이는 기능 모두에서 TypeError 및 기타 에러를 냅니다.

- 원인 : html 소스 head에 삽입되는 js 변수인 current_url, request_uri, default_url 에 퓨니코드로 도메인이 등록되기 때문입니다. 또한 Context.class.php의 이와 관련한 함수인 getDefaultUrl(), getUrl(), getRequestUri()도 관계합니다.

- 해결 : IE이면서 한글도메인(IDN : xn--)일 때는 미솔님의 idna lib를 이용해서 퓨니코드를 한글로 decoding하면 됩니다.

참고) 미솔님의 idna 라이브러리가 필요하며, 올리신 방법 가운데, func.inc.php 는 수정하지 않습니다.
1. default_url은 미솔님 방법대로 퓨니코드로 해야 FF나 모바일에서 에러나지 않습니다.
/modules/install.admin.controller.php - line : 73 다음에 추가
```
		if($default_url && substr($default_url, -1) !== '/') $default_url = $default_url.'/';

		/* convert NON Alphabet URL to punycode URL - Alphabet URL will not be changed */
		require_once(_XE_PATH_ . 'libs/idna_convert/idna_convert.class.php');
		$IDN = new idna_convert(array('idn_version' => 2008));
		$default_url = $IDN->encode($default_url);
```

2. Context.class.php에서 getDefaultUrl(), getUrl(), getRequestUri() 함수를, 한글도메인이면서 IE일 때는 퓨니코드를 한글로 decoding하도록 수정합니다.

/classes/context/Context.class.php - getDefaultUrl() line : 550 return $db_info->default_url; 을 아래 코드로 교체
```
		if( strpos($db_info->default_url, 'xn--') !== FALSE && ( strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== FALSE || strpos($_SERVER['HTTP_USER_AGENT'], 'Trident') !== FALSE ) )
		{
			require_once(_XE_PATH_ . 'libs/idna_convert/idna_convert.class.php');
			$IDN = new idna_convert(array('idn_version' => 2008));
			$IDN_Domain = $IDN->decode($db_info->default_url);
		}
		else
		{
			$IDN_Domain = $db_info->default_url;
		}
		return $IDN_Domain;
```

/classes/context/Context.class.php - getUrl() line : 1515에 추가
```
		// IE이면서 IDN일 때 한글로 domain decoding
		if( strpos($_SERVER['HTTP_HOST'], 'xn--') !== FALSE && ( strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== FALSE || strpos($_SERVER['HTTP_USER_AGENT'], 'Trident') !== FALSE ) )
		{
			require_once(_XE_PATH_ . 'libs/idna_convert/idna_convert.class.php');
			$IDN = new idna_convert(array('idn_version' => 2008));
			$IDN_Domain = $IDN->decode($_SERVER['HTTP_HOST']);
		}
		else
		{
			$IDN_Domain = $_SERVER['HTTP_HOST'];
		}
```

/classes/context/Context.class.php - getRequestUri() line : 1775 $target_url = $_SERVER['HTTP_HOST'] . getScriptPath();를 아래 코드로 교체
```
			if( strpos($_SERVER['HTTP_HOST'], 'xn--') !== FALSE && ( strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== FALSE || strpos($_SERVER['HTTP_USER_AGENT'], 'Trident') !== FALSE ) )
			{
				require_once(_XE_PATH_ . 'libs/idna_convert/idna_convert.class.php');
				$IDN = new idna_convert(array('idn_version' => 2008));
				$IDN_Domain = $IDN->decode($_SERVER['HTTP_HOST']);
			}
			else
			{
				$IDN_Domain = $_SERVER['HTTP_HOST'];
			}
			$target_url = $IDN_Domain . getScriptPath();
```

3. ajax 실행 후 redirect 할 때 한글도메인이 인코딩되어 엉뚱하게 바뀌니, String.prototype.setQuery 선언부를 아래와 같이 수정.
/common/js/common.js - line 261 : uri = uri+(query_string?'?'+query_string:''); 를 아래로 수정
```
			uri = uri+(query_string?'?'+encodeURI(query_string):'');
```

/common/js/common.js - line 263 : if (String(val).trim()) uri = uri+'?'+key+'='+val; 를 아래로 수정
```
			if (String(val).trim()) {
				query_string = '?'+key+'='+val;
				uri = uri+encodeURI(query_string);
			}
```

/common/js/common.js - line 293 : return encodeURI(uri); 를 아래로 수정
```
		return uri;
```

- 결과 : IE 버전에 상관 없이 영문도메인 상태와 똑같아 집니다. 모든 문제가 해결됩니다.
단, 영문 도메인에서 나타나던 에러는 이 상태에서도 같이 나타납니다. 예) IE7에서 관리자 페이지 게시판 설정의 분류 관리에서 카테고리가 뜨지 않는 문제 같은 것.

- 결론 : IE는 punycode로 바꿀게 아니라, 그냥 한글로 돌아댕기에 하면 문제가 해결됩니다.

- 미해결1 : swfupload.swf 를 이용한 파일 업로드. 여전히 이 부분은 에러가 나는데, 에러 나는 브라우저의 공통은 location.host에서 punycode가 아니라 한글로 나타나는 브라우저들입니다.
HTML5 업로드 기능으로 대체 가능하나, IE9 이하에서는 지원되지 않는 기능이므로, jquery 멀티 업로드 플러그인과 iframe을 이용한 꼼수를 쓰면 가능할 듯도 합니다. 어차피 XE는 자동 저장을 사용할 때 서버에 파일 첨부한 것들도 임시로 저장하니까요.

- 미해결2 : SSL 환경은 테스트 못했습니다. SSL 구입해서 테스트 완료 후 따로 올리겠습니다.

- 테스트 환경
XE : 1.7.9
도메인 : 한글
브라우저:
Windows XP IE7
Windows XP IE8
Windows 7 IE9
Windows 7 IE11
Windows 7 FF 34.0
Windows 7 Chrome 39.0.2171.95 m
Windows 7 Safari 5.1.7
Windows 7 Opera 26.0.1656.60
Mobile : 5~6년 된  Vega X+, model: IM-A725L, Android: 2.2.1

**Comment by andjfrrk** [comment]
테스트 해 보실 분은 아래 url에서 하시면 됩니다.
당분간 열어 두겠습니다.
http://www.무얼까.com

다른 것 손 댄 것 없이 XE 1.7.9에 위 코드만 적용했으며, IE7에서 접속시 네비게이션 메뉴가 나타나지 않는 문제 때문에 default.layout.css의 51번 줄에서 opacity 부분만 삭제했습니다.
계정초기화를 해서 기존에 테스트 했던 내용은 없습니다.
에디터 스킨이 기본 xe editor이기 때문에 파일첨부는 여전히 에러 납니다.

**Comment by bnu** [comment]
@andjfrrk punycode로 변환하지 않고 IDNA 그대로 저장하는 방식으로 변경하고 있습니다.
'common.js' 파일은 제시해주신 코드를 변경하여 IE8 및 모던 브라우저에서 정상 동작을 확인했습니다. :)

몇 가지 테스트를 더 거친 후 푸시하도록 하겠습니다.
이후에도 테스트 부탁드립니다. :+1:

**Comment by bnu** [comment]
punycode 로 저장하는 것으로 유지했습니다. ^^;

PHP Redirection 문제로 punycode로 유지하고 아래와 같이 처리했습니다.
- default URL을 IDN으로 지정 시 punycode로 변환하여 저장
- request_uri 및 current_url를 punycode로 변환하지 않은 IDN으로 출력하도록 변경
- String.prototype.setQuery()에서 IDN을 인코딩하지 않도록 변경

**Comment by bnu** [comment]
fixed d6a898a
