### ISSUE TITLE
file.controller.php 에서 ogg파일도 미디어 파일로 처리함이 어떨지

### ISSUE THREAD

**Issue by gorhkd0612** [xpressengine/xe-core#1183]
현재 ogg파일은 첨부 후 본문삽입시 일반 파일로 처리되어 파일 링크만 나타나는데
audio태그에서 많이 사용되는 파일중 하나이므로 ogg파일도 file.controller.php 파일을

file.controller.php line 643:
if(preg_match("/\.(jpe?g|gif|png|wm[va]|mpe?g|avi|swf|flv|mp[1-4]|as[fx]|ogg|wav|midi?|moo?v|qt|r[am]{1,2}|m4v)$/i", $file_info['name']))

로 수정하여 처리함이 좋겠습니다.

**Comment by misol** [comment]
@bnu 처리된 이슈
