### ISSUE TITLE
[1.7.9]버전 사이트의 URL주소 변경시 문제점.

### ISSUE THREAD

**Issue by dmzvillager** [xpressengine/xe-core#1184]
게시판에 파일을 첨부하고 그파일을 본문에 추가하여  링크나, 이미지를 표시 하면 현재의 도메인 주소로 고정이 되어, 사이트의 URL를 변경 할 경우 링크가 변경된 URL로 표시 되지 않는 문제가 있습니다.

**Comment by dmzvillager** [comment]
과거에는 게시판에 첨부된 파일을 본문에 삽입하면, 
/files/attach/images/*/*/aaa.jpg 형태로 DB에 기록이 되었는데
현재 [1.7.9]버전에서는
http://domain.*//files/attach/images/*/*/aaa.jpg 형태로 DB에 기록되어 도메인 주소가 바뀌면 대응을 하지 못함.

**Comment by sejin7940** [comment]
저도 처음엔 이게 불편하다고 생각했는데..
외부 다른 API 를 이용하는 경우에는, 오히려 이렇게 도메인이 파일명에 같이 들어있어야하는 더 편한 경우도 있더군요.  예를들어 카카오링크 등으로 퍼가는 애드온 등에서는 이렇게 되어있어야하더군요 (물론 애드온 자체 설정에서 도메인을 받아 조합해도 되지만)
의외로 나름의 장단점이 있기에.. XE 개발진들이 고민을 이래저래 해봤으면 합니다.
