### ISSUE TITLE
[1.7.9]버전 Welcome_menu 사라짐

### ISSUE THREAD

**Issue by seobi** [xpressengine/xe-core#1185]
사이트 메뉴 편집 클릭하면 Welcome_menu가 나타나지 않습니다.
서버사양은 
mysql  Ver 14.14 Distrib 5.5.40, for Linux (x86_64) using readline 6.2
PHP 5.3.29-pl0-gentoo
입니다.
서버에 한글 locale이 설정되어 있지 않아 xpressengine을 영문으로 설정해도 마찬가지 입니다.
![welcome_menu](https://cloud.githubusercontent.com/assets/10512454/5717974/d2a08bca-9b4b-11e4-8117-9b82c6b09b52.png)

**Comment by qw5414** [comment]
xe/files/ 의 권한을 확인해보세요.
707(?)권한으로 바꿔주는게 좋다고 들었습니다.

**Comment by seobi** [comment]
files 권한 바꿔도 마찬가지 입니다.
제 계정권한으로 수정할 수 없어서 php 스크립트로 수정했는데 마찬가지 입니다. 
다른 해결책없을까요? 이거 때문에 몇번을 DB삭제하고 xpreessengine 삭제해서 다시해보고 하는데 안되는 군요.

-----------------------------------------------------------------------------
total 88
drwx---rwx 14 joseph member  4096 Jan 13 17:52 .
drwx-----x  7 joseph member  4096 Jan 13 17:49 ..
drwxr-xr-x 15 joseph member  4096 Jan  7 14:06 addons
drwxr-xr-x  3 joseph member    45 Jan  7 14:06 admin
-rw-r--r--  1 joseph member    45 Jan 13 17:52 chmod.php
-rw-------  1 joseph member 12288 Jan 13 17:52 .chmod.php.swp
drwxr-xr-x 22 joseph member  4096 Jan  7 14:06 classes
drwxr-xr-x  7 joseph member    80 Jan  7 14:06 common
drwxr-xr-x  2 joseph member    84 Jan  7 14:06 config
-rw-r--r--  1 joseph member  1419 Jan  7 14:06 CONTRIBUTING.md
-rw-r--r--  1 joseph member    46 Jan  7 14:06 COPYRIGHT
drwx---rwx 10 apache apache  4096 Jan 13 17:51 files
-rw-r--r--  1 joseph member  2358 Jan  7 14:06 .htaccess
-rw-r--r--  1 joseph member  2185 Jan  7 14:06 index.php
drwxr-xr-x  5 joseph member    72 Jan  7 14:06 layouts
drwxr-xr-x  6 joseph member   134 Jan  7 14:06 libs
-rw-r--r--  1 joseph member 25396 Jan  7 14:06 LICENSE
drwxr-xr-x  5 joseph member    69 Jan  7 14:06 m.layouts
drwxr-xr-x 32 joseph member  4096 Jan  7 14:06 modules
-rw-r--r--  1 joseph member  1667 Jan  7 14:06 README.md
drwxr-xr-x  7 joseph member   119 Jan  7 14:06 widgets
drwxr-xr-x  3 joseph member    27 Jan  7 14:06 widgetstyles

**Comment by YJSoft** [comment]
@seobi files/cache/menu 폴더에 php 파일이 있는지 확인해주세요

**Comment by seobi** [comment]
파일이 있어요.
---------------------------------------------------------------
joseph@linuxstudy ~/xe/files/cache/menu $ ls -la
total 168
drwxr-xr-x  3 apache apache   105 Jan 17 17:40 .
drwxr-xr-x 17 apache apache  4096 Jan 17 17:40 ..
-rw-r--r--  1 apache apache  1777 Jan 17 17:40 64.php
-rw-r--r--  1 apache apache  1859 Jan 17 17:40 64.xml.php
-rw-r--r--  1 apache apache 62588 Jan 17 17:40 71.php
-rw-r--r--  1 apache apache 89475 Jan 17 17:40 71.xml.php
drwxr-xr-x  2 apache apache     6 Jan 17 17:40 admin_lang
-rw-r--r--  1 apache apache    54 Jan 17 17:40 homeSitemap.php
joseph@linuxstudy ~/xe/files/cache/menu $

**Comment by seobi** [comment]
파일 있습니다.
joseph@linuxstudy ~/xe/files/cache/menu $ ls -la
total 168
drwxr-xr-x  3 apache apache   105 Jan 17 17:40 .
drwxr-xr-x 17 apache apache  4096 Jan 17 17:40 ..
-rw-r--r--  1 apache apache  1777 Jan 17 17:40 64.php
-rw-r--r--  1 apache apache  1859 Jan 17 17:40 64.xml.php
-rw-r--r--  1 apache apache 62588 Jan 17 17:40 71.php
-rw-r--r--  1 apache apache 89475 Jan 17 17:40 71.xml.php
drwxr-xr-x  2 apache apache     6 Jan 17 17:40 admin_lang
-rw-r--r--  1 apache apache    54 Jan 17 17:40 homeSitemap.php
joseph@linuxstudy ~/xe/files/cache/menu $

**Comment by jungbaksacom** [comment]
사이트메뉴가 안나오는 현상의 원인을 찾던중

Context.class.php 204 line

if(simplexml_load_string(file_get_contents("php://input")) !== false) $GLOBALS['HTTP_RAW_POST_DATA'] = file_get_contents("php://input");

이것에서 아래와 같은 경고가 나오면 더이상 진행이 안됩니다.(경고출력이 안되어도 진행이 안됩니다.)

Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<'

그래서 
			if(substr(file_get_contents("php://input"), 0, 1) == "<") {
				if(simplexml_load_string(file_get_contents("php://input")) !== false) $GLOBALS['HTTP_RAW_POST_DATA'] = file_get_contents("php://input");
			}
			else {
				$GLOBALS['HTTP_RAW_POST_DATA'] = file_get_contents("php://input");
			}

와같이 첫글자가 "<" 인지를 먼저 검사한후에 원래검사를 하는것으로 수정하니 정상동작 하였네요
