### ISSUE TITLE
metaweblog 사용시 한글 파일 등록 안되는 문제

### ISSUE THREAD

**Issue by zfanta** [xpressengine/xe-core#1187]
windows live writer를 이용하여 글을 등록할 시 파일 이름에 비영어권 문자가 있을 경우 등록이 되지 않습니다.

**Comment by fromthere** [comment]
http://saddev.tistory.com/71 여기 참고하시고 windows live writer 자체에서 한글 파일을 지원하지 않는다고 합니다.

**Comment by zfanta** [comment]
xmlrpc를 이용하여 직접 보내도 cache/blogapi 에 파일이 생기지가 않네요.
