### ISSUE TITLE
스팸 단어를 스패머에게 알려줄 필요 없음

### ISSUE THREAD

**Issue by fromthere** [xpressengine/xe-core#1189]
https://www.xpressengine.com/tip/22920141

스팸 단어를 변형하여서 등록할 수 있게 만들수 있으므로 해당 부분은 빠지거나, 관리자 한정으로 알 수 있게 변경되어야 한다고 봅니다.

**Comment by lansi951** [comment]
가끔 긴 글을 쓰는 유저들 중에 스팸이 아닌 평범한 글인 경우에도 스팸 단어가 들어가서
등록을 못 하고 고생하는 경우가 있습니다. 이럴 경우 문제가 되겠죠.

**Comment by izuzero** [comment]
@lansi951 그럴 경우 운영자에게 문의하라고 하면 됩니다. 무슨 단어 때문에 스팸 처리됐는지 스패머가 알 수 있는 걸 막는 게 급선무인 것 같습니다.

**Comment by anizen** [comment]
@izuzero 그럼 해당 작성자는 글을 작성하지 못하고 해당 글을 복사해서 운영자에 문의 하는 과정이 솔직히 불편할 것 같습니다.

**Comment by lansi951** [comment]
@izuzero anizen님 말씀대로 작성을 포기하는 사람이 더 많을 것 같습니다. 또, 관리자에게 문의해도 직접 글을 복사해서 작성하지 않는 한 어떤 게 스팸 단어인지 알아보기 힘든 어려움이 있습니다.

스팸 단어를 사람만 알아볼 수 있게 하는 건 어떤가요? 적어도 봇은 걸러지니까요.

**Comment by cglink** [comment]
**스팸**필터링과 (욕설 등) **금지단어**필터링 모듈이 분리되어야할지도...
XX가 욕설이라면 X.X , X_X , X*X 같은 것도 같이 금지단어로 차단되면 좋겠지만 처리속도가 너무 느릴거서 같기도하네요.
