### ISSUE TITLE
삭제된 게시글의 srl로만 접속시 메인으로 이동되며 팝업이 표시되지않음

### ISSUE THREAD

**Issue by DooSanBaik** [xpressengine/xe-core#1191]
free라는 게시판의 12345의 srl을 가진 게시글이 삭제되었을때
/free/12345로 접속시 게시글이 없다는 팝업창이 표시되지만
/12345로 접속시 홈페이지로 설정한 사이트 메인으로 이동되며 삭제되 게시글이라는 팝업창이 표시되지않음

**Comment by YJSoft** [comment]
게시판 모듈 뿐만이 아니라 위키 모듈이나 문서 페이지 등에서도 document 모듈을 사용하기에, document_srl만 입력한 경우 document_srl로 모듈 정보를 가져와서 처리하는데요,
mid를 입력한 경우에는 게시글이 없더라도 mid를 사용해서 모듈 정보를 불러올 수 있지만, mid가 없는 경우 어느 모듈의 srl인지 알 수 없기에 현재 구조상 적절한 처리가 불가능합니다.

**Comment by Lastorder-DC** [comment]
적어도 `주소/23423`나 `주소/mid/324324` 형태 주소는 존재하지 않을시 HTTP 404 처리가 필요하다고 봅니다. @bnu
