### ISSUE TITLE
exec_json으로 권한 없이 notice_list, category_list, file_list, comment_list를 가져 올 수 있는 문제

### ISSUE THREAD

**Issue by andjfrrk** [xpressengine/xe-core#1192]
접근 권한 있을 때 콘솔창에서 jQuery.exec_json으로 권한 없는 것들을 볼 수 있는 문제

XE Version : 1.7.9

1.. 문제
- dispBoardNoticeList : 목록 권한 없이 공지 사항 불러 올 수 있음.
- dispBoardCategoryList : 목록 권한 없이 카테고리 목록 불러 올 수 있음.(board.api.php, module.xml에 함수명 오타도 있음)
- dispBoardContentFileList : 문서 열람 권한이 없어도, 해당 문서 document_srl만 알면 file_list를 불러 올 수 있고, 이 file_list에는 첨부파일의 절대 경로 정보가 있기 때문에 다운로드 받을 수 있음. document_srl은 단순 시리얼이기 때문에 얼마든지 대입 가능.
- dispBoardContentCommentList : 문서 열람 권한 없이 댓글 목록 불러 올 수 있음.

2.. 해결
- dispBoardNoticeList : $this->grant->list 적용
- dispBoardCategoryList : $this->grant->list 적용
- dispBoardContentFileList : $this->grant->access 적용. 문서 열람 권한 적용. 파일 다운로드 가능 그룹 체크 적용(이 부분은 그냥 하드코딩 했으며, 권한만 알면 되기 때문에 getModulePartConfig에서 불러 왔습니다. file.controller.php와 겹치는 부분이 있으니 유지 보수를 위해 권한 체크만 따로 함수를 마련하는게 낫다고 봅니다.)
- dispBoardContentCommentList : 문서 열람 권한 적용.

https://github.com/andjfrrk/xe-core/commit/15189482cf68aac844b2a4bfd971bff8ce744f2b

**Comment by bnu** [comment]
fixed #1195
