### ISSUE TITLE
XE 1.7.9에서 임시저장글이 노출되는 현상이 있는 것 같습니다.

### ISSUE THREAD

**Issue by LI-NA** [xpressengine/xe-core#1198]
임시저장글도 srl을 가지게 되고 완성된 게시글로 취급되는데, 일반 목록에서는 나오지 않으나 document_srl로 직접 접근 혹은 태그 검색을 하면 임시저장글까지 같이 노출되고 있습니다.

이에 임시저장글에는 아예 접근을 못하도록 하거나, 태그검색시에도 노출이 안되게끔 수정해야한다고 생각합니다.

**Comment by sejin7940** [comment]
태그검색시 노출되는 건 =>  https://github.com/xpressengine/xe-core/pull/1207

**Comment by bnu** [comment]
fixed #1270
