### ISSUE TITLE
위젯페이지를 저장해도 act가 그대로 남아 다시 수정버튼을 눌러도 반응이 없습니다.

### ISSUE THREAD

**Issue by Darkhost** [xpressengine/xe-core#1199]
주소 끝에 수정하고 나서 저장을 해도 &act=dispPageAdminContentModify가 계속 남아있어서 수정이 안됩니다.. 다시 게시판을 누르거나 새로고침을 해야만 하네요..

**Comment by izuzero** [comment]
본인의 사이트에서 자바스크립트 오류에 의해 리다이렉트가 되지 않는 것 같습니다.
레이아웃이나 위젯 등에 포함된 자바스크립트에서 오류가 발생하고 있는 건 아닌지 확인하세요.
