### ISSUE TITLE
기본url 끝에 슬래시를 붙히지않는경우 이미지경로에 문제가생김

### ISSUE THREAD

**Issue by DooSanBaik** [xpressengine/xe-core#1200]
http://www.xpressengine.com 으로 설정시에 파비콘경로에 /에 삽입이되지않아
https://www.xpressengine.comfiles/attach/xeicon/favicon.ico
위와같은 형태가됨
http://www.xpressengine.com/ 으로 설정해야만
https://www.xpressengine.com/files/attach/xeicon/favicon.ico
위와같은 형태가됨

**Comment by qw5414** [comment]
어떤이미지 경로를 말씀하시는건지 모르겠지만.

제 사이트 대부분이 끝부분 슬래시를 쓰지 않습니다.

만일 SSL 사용중이시라면,

http://기본URL을 `https://` 으로 수정하셔서 사용해보세요..

**Comment by DooSanBaik** [comment]
qw5414
파비콘 이미지의 경로가 http://URL 로 지정하게되면
files와 url이 붙어버린다는 이야기입니다

**Comment by andjfrrk** [comment]
/modules/admin/admin.admin.model.php - line 965
```
			if(substr_compare($default_url, '/', -1) !== 0)
			{
				$icon_url = $default_url . '/files/attach/xeicon/' . $virtual_site . $iconname;
			}
			else
			{
				$icon_url = $default_url . 'files/attach/xeicon/' . $virtual_site . $iconname;
			}
```

혹시나 default_url 관련해서 같은 문제가 생길만한 곳을 찾아 봤지만 더는 없네요.

**Comment by misol** [comment]
https://github.com/xpressengine/xe-core/pull/1120 가 받아들여진다면, 이 문제도 저절로 해결될겁니다 :)

**Comment by andjfrrk** [comment]
@misol 

네. 그렇게 되면 저 코드는 불필요하죠. 기존에 있던 관련 코드도 모두. ^^

**Comment by bnu** [comment]
fixed #1120
