### ISSUE TITLE
Hostinger에서 프록시로 접속해야 제대로 접속되는 문제

### ISSUE THREAD

**Issue by Activity60** [xpressengine/xe-core#1210]
Hostinger을 사용시 프록시 웹사이트를 통해 접속해야만 제대로 되고 그냥 접속할시 알 수 없는 문자열이 나오는 문제가 있습니다. [1.7.9]

**Comment by YJSoft** [comment]
https://www.xpressengine.com/tip/22915887 참고해주세요.
호스팅어 서버 gzip 세팅 문제입니다.

**Comment by Activity60** [comment]
똑같은데요.오히려 더 긴 외계어가 나옵니다. 주소: mogun68-2014.esy.es/xe
2015. 1. 25. 오전 12:53에 "YJSoft" <notifications@github.com>님이 작성:

**Comment by YJSoft** [comment]
@Activity60 인코딩이 깨져 나오는 문제는 서버 문제로 XE에서 해결할 수 있는 방법이 없습니다.
호스팅어 고객센터로 문의해보세요.
