### ISSUE TITLE
editor\components중에서 

### ISSUE THREAD

**Issue by gsurae** [xpressengine/xe-core#122]
modules\editor\components중에서 

"preg_match_all('/(width|height)([^[:digit:]]+)([0-9]+)/i',$style,$matches);"
위 문장이 들어간 components들이 ie에서만 width와 height값을 인식못하네요.

크롬에서 mp4 파일을 본문 삽입하면 player로 연결을 못하며
등록 버튼을 누르면 다운로드가 되는 문제가 있네요.

이부분은 xe.min.js 파일에서 25라인에 mp4 확장자를 추가해서 jwplayer로 연결하여 해결.

테스트 브라우저는 ie10, 크롬 31.0.1650.57

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
