### ISSUE TITLE
파일/이미지 아이콘 중복 노출

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1232]
이미지를 첨부한 경우
게시글 목록에서 파일 디스켓 아이콘 과 이미지 아이콘이 동시에 나옵니다.
이미지 파일만 있는 경우에는 이미지 아이콘만 나와야 할듯 합니다.

**Comment by bnu** [comment]
각각 파일이 업로드되었거나 본문에 `<img>`태그가 있음을 나타내는 아이콘으로서 표시 목적이 다릅니다.
