### ISSUE TITLE
widget page 수정시 권한 문제

### ISSUE THREAD

**Issue by delphixe4** [xpressengine/xe-core#1234]
1) 임의의 회원이 소속된 그룹을 관리자 권한이 있는 그룹으로 지정하거나 or 2) 해당 모듈의 관리자로 지정된 유저는 widget page에서 widget 추가는 가능할지는 모르겠으나 "dispWidgetAdminAddContent"(Insert Content by Yourself) 에서는 msg_is_not_administrator 출력되는 문제가 있습니다.

해당 모듈의 관리자 혹은 관리하는 그룹에 소속되어 있음에도 내용 수정,추가가 불가능한 것은 확실히 버그같아 이슈 작성합니다.

**Comment by geusgod** [comment]
저도 같은 증상이 있습니다. 페이지 > 위젯페이지 형식인데
그룹 권한을 준 사용자가 "페이지수정" 버튼 누른후 톱니바퀴모양 편집을 누르면 "msg_is_not_administrator"라는 메세지만 출력됩니다.
xe 1.8.3버전 Linux, php 5.3.22 입니다.
