### ISSUE TITLE
비밀번호 검사를 통과하지 못합니다.

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1238]
https://www.xpressengine.com/qna/22933723
https://www.xpressengine.com/qna/22929372
https://www.xpressengine.com/qna/22919148

모두 같은 증상입니다. 

아. 링크에 다 나와 있어 제가 급한 마음에 내용을 적지 않았네요.
요약 하자면, 회원정보 수정을 하기 위하여 비밀 번호를 재입력해야 하는데 비밀번호 검사를 통과하지 못합니다.
모두 틀린 비밀번호라고 나옵니다. 이번에 발견하여 언제부터 이런 증상인지 정확히 판단은 안되는데 1.7.9 부터 인것 같습니다.

**Comment by YJSoft** [comment]
## Issue 작성
Issue 작성 시 참고해주세요.

* 작성하려는 이슈가 이미 있는지 검색 후 등록해주세요. 비슷한 이슈가 있다면 댓글로 추가 내용을 덧붙일 수 있습니다.
* 이슈에는 하나의 문제 또는 제안을 작성해주세요. 절대 하나의 이슈에 2개 이상의 내용을 적지마세요.
* 이슈는 가능한 상세하고 간결하게 작성해주세요
	* 필요하다면 화면을 캡쳐하여 이미지를 업로드할 수 있습니다

```CONTRIBUTING.md``` 파일을 참고해주세요. 링크만 적기보다는 상세히 문제 내용을 적는 것이 도움이 됩니다 :smile:

**Comment by mactopia** [comment]
아. 링크에 다 나와 있어 제가 급한 마음에 내용을 적지 않았네요.
요약 하자면, 회원정보 수정을 하기 위하여 비밀 번호를 재입력해야 하는데 비밀번호 검사를 통과하지 못합니다.
모두 틀린 비밀번호라고 나옵니다. 이번에 발견하여 언제부터 이런 증상인지 정확히 판단은 안되는데 1.7.9 부터 인것 같습니다.

**Comment by allcalc** [comment]
혹시 비밀번호 DB 저장방식을 변경하진 않으셨나요?

**Comment by YJSoft** [comment]
@mactopia #1244 참고해서 수정해주세요.

**Comment by mactopia** [comment]
@allcalc 님 아니요...그런거 제가 할줄 몰라서...혹시 db 저장 방식을 변경되었는지 어디를 확인하면 될까요?

@yjsoft 님 정말 감사드립니다. 그런데 테스트를 해보니

어드민은 수정이 잘되는데요..
진입 / 수정완료 모두 성공

일반회원은 
진입 성공 / 수정(등록) 버튼 이후 백지화

가 되며, 다시 들어가면 수정이 되어 있질 않습니다.

**Comment by YJSoft** [comment]
@mactopia 사용중이신 애드온 또는 모듈과의 충돌로 보입니다.
XE 관리자 화면 하단 서버정보출력의 내용 중 module:~~ addon:~~ 부분 올려 주시면 확인해 보겠습니다.
(코어 코드 자체에는 문제가 없는 것으로 보입니다)

**Comment by mactopia** [comment]
이렇게 올리면 될까요?
module : adminlogging(1.7), anniversary(0.8 beta), apporix(1.0), attendance(5.0.5), board(1.7.2), board_extend(1.1), bulkmsg(1.0), checkip(0.2.2), contact(1.7.0.2), easyxe(1.41), exam(0.6), gdata(0.5), iconshop(0.4), imageprocess(1.4.0.1), isx(1.7.4.1), krzip(1.0), loginlog(0.5.1), loginxeclient(1.03), loginxeserver(1.02), lottery(0.1), maps(1.1.1), marketplace(1.2), material(1.1), money(0.1), moneyhistory(1.0), msg_admin(0.1), naverlogin(1.0), ncenterlite(2.1.2), pado_ajax_newsModule(1.5), pointhistory(0.1.4), popup(1.5.2), portalpoint(1.2), profiler(0.1.1), quizgame(0.1), resource(1.7.0), rockgame(0.4), rssboard(0.3), sejin7940_copy(1.2), sejin7940_nick(1.0.2), sejin7940_vote(1.3), seo(0.2.0), sitemap(1.2), smith(1.0), stats(1.1.1), syndication(4.0), timeline(1.0.0), vicemanager(0.2.0)
addon : AntiProxy(1.0.0), aa_add_vote_list(1.0.1), aa_insert_ad(1.0.0), add_document(0.1.1), addon_insert_sticker(0.1), addon_insert_video(0.1), addon_write_insert_media(0.1), addon_xenara_sns(0.1), addvote(1.0), adminlogging(1.7), adult_keyword(1.0), age_restrictions(1.0), alway_stalker(0.2), anonymous_classify(0.2), appoint_view_user(1.0), apporix(1.1), apporix_native_alert(0.1), auth_email(0.1), autoDel(1.0), auto_image(0.5.6), auto_multimedia(1.0), auto_nick(1.0), auto_outimage(0.4.7), auto_reply(0.1a), bbCode(1.0), beforecheckwrite(0.1), block_control(1.0), block_country(0.2), block_document(0.1), block_insert(0.3), block_ip(2.1a), blockact(1.0), board_admin_secret(1.0), cameron_plugin(1.2), captbha(0.5), captcha2(0.1), captcha_member(1.7), category_none(0.1), change_nickname(2.0), changealt(0.2.1), check_ness(1.1), checkkorean(1.1), checklen(1.3), confirm_declare(1.1a), counter_ex(1.1.0), declared_document_move(0.1), declared_message(0.1), denied_word(1.001), denyauto(0.7), document_adbox(0.3), document_caution_blind(1.0), document_content_change(1.0), document_modete_limit(0.1.1), document_secret(0.2), double_click(0.1), download_ad(0.1), download_wanna_reply(1.0), dyform_no_spam(0.3.3), elkha_simple_spam(0.1), elkha_www(0.11), emailFilter(1.0), event_board(0.1), ex_notice(0.2), exclude_my_document(0.4), exif(0.9.2.2), ezmember(0.7 RC1), fa_fileicon(1.1.2), fa_loader(4.2.0), facebook_social(0.2), favicon(1.1), fileicon(1.1), fileuploadcount(0.1), font_awesome_new(1.0), font_nanum_gothic(1.0), geoip_block(0.1), ggstopspam(0.1), give_download_permission(0.1), guest_name(1.1.2), hello_member(1.0.0.0), hidden_module(0.3), hide_mid(0.1.0), hot_document(1.2.1), howlogin(0.2), iframe_resize(0.2), image_lazyload(0.3.1), image_preview(1.0), interpreter_addon(0.00001), ip_ban(1.0), ipguard_post(1.7.3.4), jqueryuicdn(2.0), keyword_link(0.1), kru_sslhelper(3.0.1), langfilter(0.7), layerpopup(1.10), lazyload(0.1.1.1), level_permission(0.1), lightboxplus(0.4.0), limit_message(0.2), login_2sisstore(1.0.1), login_defencer(1.0), login_method(0.2), manage_member(0.2), member_activity_check(0.4), member_ajaxboard(2.1.1), member_block_addon(0.4), member_control(0.1), member_extra_check(2.0), member_extra_vars_check(1.0), member_icon_print(0.3), member_join_ex(0.2.3), member_layer_config(1.1), memberinfo(1.10), messageTalk(2.0.1), message_btn(1.0.2), meta_add(0.2.2), mobile_extend(0.5.1), mobile_redirect(1.0), msg_point(1.0), multimedia_thumbnail(2.0.0), my_comment_addon(1.1.2), my_reading(1.1), naver_analytics(1.2), naver_syndication(0.1), new_document_notify(2.0), new_document_notify2(1.0.12), noclick(1.3), nprogress(0.1.1), oembed(1.0), opengraph(0.11), people_like(1.1), php_exif(1.0), placeHolders(1.0), planet_bookmark(0.1.1), planet_todo(0.1.1), pnbsp(0.2), point_pang_pang(1.0), point_pangpang_plus(0.1a), popup_opener(1.5.2), prettyphoto(1.1.3.0), prohibit_monologue(0.1), push_doc(0.1), radarURL(1.2), rainbow_link(0.3), recommend(1.0), recycled(1.0), refhide(0.1.1), remove_id_search(1.0), report_addon(0.2), resize_signature(0.1), robotcontrol(1.1.0), scmlock_board(1.5), searchhighlight(0.2), sejin7940_addvote(1.2), sejin7940_align(1.0), sejin7940_all_notice(1.4), sejin7940_autotrash(1.1.1), sejin7940_kakao_link(0.5.3), sejin7940_mobile_resize(1.0), sejin7940_mustlogin(0.2), sejin7940_readed_count(1.6), sejin7940_write_limit(1.5.2), setitle2(2.1.0), settitle(1.3), shortcut(0.9.9.3), show_document_voter(0.1.1), show_minfo_point(0.1), show_mobile_write(0.1.2), sns_card(1.1), sns_linker_lite(1.1), socialxe_helper(1.0.6), socialxe_mid_forwarder(1.0.3), soo_add_content(0.5), soo_add_ssl(0.1), soo_feed_delay(0.1), soo_googleplus(0.2.1), soo_jquery_unload(2012.1.23), soo_mcrblog_link(1.2.14), soo_parking(0.3a), ssl_support(0.1), stalk(0.1), stats(1.1), stop_spambot_xe(0.6), sxe_bbcode_lite(0.1), sxe_block_write(0.2), sxe_ncenter_plus(0.2), sxe_now_connected(0.2), sxe_writing_format(0.2), syncNick(1.0), tag_relation(1.4.1), tag_relation_add(1.4.1), thumbnailer(0.1), to_sns(0.2.1), today_fortune(1.0.1), updatecategory(1.0), vegas_background(0.2), voteNmove(1.1), write_limit(1.2.1), xdt_google_analytics(1.1), xss_session_protector(0.1), youtube_control(1.2)
layout : ASXE_FLAT(1.1), awake(1.0.4), Civilrevo original(1.2.2), Civilrevo(1.2.2), doorweb_basic(1.7.4), elkha_graystyle(2.0.1), Express999(2.1), flat_series(1.0.22), hestia(2.1.4), Imagemonster(2.1), kbfree(1.2), PXE_clio(1.0.3.1), Rebirth_A(1.1.2), sketchbook_search(1.0), sketchbook_search -ORIGINAL(1.0), sketchbook5(1.6.3.6), TM_Tiva(0.1), UXFACTORY_CHRONOS(1.0), verti(0.1.0), websitebuilder(1.0 beta), xdt_pure(1.4), style_a_lite(2.1.4), xe_official(1.7), xet_onecolor(1.0.2), material_xe(1.0.0), kso_faddist(1.6.1), store_style25(2.5), xecenter(1.3.7), classical(1.7), user_layout(1.7)
widget : Alldocument(1.6), attendance_check(1.6.2), birthday(0.1), browserWidget(0.2), calendar(0.2), cameronSlider(1.0.2), category(0.1), clcontents(1.0), content_specificdoc(0.2), contentextended(2.43), counter_status(1.7), ddayWidget(0.4), ding_loginWidget(0.1), doorweb_content(1.7.2), dp_counter(2.0), eh_whcarousel(0.4), flatContent(0.1), forum(0.1), gagachat(3.7), gallery_layout_widget(1.0.0), ggboardinsert_widget(0.6), ggboardmailing_widget(0.2), gsi_sitemap(0.1), gyAccordion(0.1), gyBlindBanner(0.1), gyContent(0.1.3), gyLinkTreeMenu(0.1), gySlider(0.1), gySliderBot(0.1), hb_bank(0.1), hindole_again(0.1), hitsearch(0.2), ideationBanner(0.1), ideationPopular(0.1), im_content(0.1), level_point(1.0), logged_members(0.1), maps_widget(1.1.2), member_group(0.1), member_state(4.0), navigation(0.4), navigator(1.7.0), newest_comment(0.1), newest_document(1.0), newest_images(0.1), notice(1.0.4), opageWidget(1.0), pado_ajax_newsWidget(1.9), pado_board_rankingWidget(0.6), picasa_recent_images(0.1), planet_document(0.2), plusadWidget(0.6), point_status(1.0), popular_planet_document(0.1), randomchat(1.2), rank_attendance(0.8.1), rank_count(1.5), rank_download(1.5), rank_point(1.0), rss_reader(#7), sejin7940_navermap(0.2.1), site_info(1.7.0), sitemap(0.1.0), sitemap_selectbox(0.1.0), slideimg(1.1.2), socialxe_comment(1.0.8), socialxe_info(1.0.6), srchat(219.461), tag_list(0.1), tocplus(0.3), towc_new_docu(1.9), treasurej_popular(1.0.5), uchat(1.1.7), user_finder(0.1), webcon_content(1.0), webcon_effectSlider(1.0), webcon_mosaicContents(1.0), webcon_verticalTab(1.0.1), webcon_wslider(1.0), webzine(0.1), (), xehoverdir(0.1), xelayout_weather(0.2), xet_content(1.1.4), xet_slider_nivo(1.0.1), xet_slider_parallax(1.0.1)
widgetstyle : LimitwidgetStyle(1.0), doorweb_v4_widgetstyle(1.7), eond_doubleline(0.1), gray_style(1.2.1), intermission(0.1), lineBox(0.1), m_cronos_ws(1.1), mo_colorline(0.3), nico(1.2), sctb(6.0), simple(1.7), simple-style(1.0), sketchbook5_wincomi(3.0), sorrent_simplebox(0.1), sweetMobileWidgetStyle(1.7), tiva(0.1), tiva_big(0.1), xdt_windless(1.0), xe_official(1.0), yoorim_m_v1(1.0.0)
max_file_uploads : 20
post_max_size : 100M
memory_limit : 128M

**Comment by mactopia** [comment]
module : adminlogging(1.7), attendance(5.0.5), board(1.7.2), board_extend(1.1), checkip(0.2.2), contact(1.7.0.2), exam(0.6), iconshop(0.4), imageprocess(1.4.0.1), krzip(1.0), loginlog(0.5.1), lottery(0.1), marketplace(1.2), material(1.1), msg_admin(0.1), ncenterlite(2.1.2), pointhistory(0.1.4), popup(1.5.2), portalpoint(1.2), profiler(0.1.1), quizgame(0.1), rockgame(0.4), rssboard(0.3), sejin7940_copy(1.2), sejin7940_nick(1.0.2), sejin7940_vote(1.3), seo(0.2.0), sitemap(1.2), syndication(4.0), timeline(1.0.0)
addon : AntiProxy(1.0.0), aa_add_vote_list(1.0.1), aa_insert_ad(1.0.0), add_document(0.1.1), addon_insert_sticker(0.1), addon_insert_video(0.1), addon_write_insert_media(0.1), addon_xenara_sns(0.1), addvote(1.0), adminlogging(1.7), adult_keyword(1.0), age_restrictions(1.0), alway_stalker(0.2), anonymous_classify(0.2), appoint_view_user(1.0), apporix(1.1), apporix_native_alert(0.1), auth_email(0.1), autoDel(1.0), auto_image(0.5.6), auto_multimedia(1.0), auto_nick(1.0), auto_outimage(0.4.7), auto_reply(0.1a), bbCode(1.0), beforecheckwrite(0.1), block_control(1.0), block_country(0.2), block_document(0.1), block_insert(0.3), block_ip(2.1a), blockact(1.0), board_admin_secret(1.0), cameron_plugin(1.2), captbha(0.5), captcha2(0.1), captcha_member(1.7), category_none(0.1), change_nickname(2.0), changealt(0.2.1), check_ness(1.1), checkkorean(1.1), checklen(1.3), confirm_declare(1.1a), counter_ex(1.1.0), declared_document_move(0.1), declared_message(0.1), denied_word(1.001), denyauto(0.7), document_adbox(0.3), document_caution_blind(1.0), document_content_change(1.0), document_modete_limit(0.1.1), document_secret(0.2), double_click(0.1), download_ad(0.1), download_wanna_reply(1.0), dyform_no_spam(0.3.3), elkha_simple_spam(0.1), elkha_www(0.11), emailFilter(1.0), event_board(0.1), ex_notice(0.2), exclude_my_document(0.4), exif(0.9.2.2), ezmember(0.7 RC1), fa_fileicon(1.1.2), fa_loader(4.2.0), facebook_social(0.2), favicon(1.1), fileicon(1.1), fileuploadcount(0.1), font_awesome_new(1.0), font_nanum_gothic(1.0), geoip_block(0.1), ggstopspam(0.1), give_download_permission(0.1), guest_name(1.1.2), hello_member(1.0.0.0), hidden_module(0.3), hide_mid(0.1.0), hot_document(1.2.1), howlogin(0.2), iframe_resize(0.2), image_lazyload(0.3.1), image_preview(1.0), interpreter_addon(0.00001), ip_ban(1.0), ipguard_post(1.7.3.4), jqueryuicdn(2.0), keyword_link(0.1), kru_sslhelper(3.0.1), langfilter(0.7), layerpopup(1.10), lazyload(0.1.1.1), level_permission(0.1), lightboxplus(0.4.0), limit_message(0.2), login_2sisstore(1.0.1), login_defencer(1.0), login_method(0.2), manage_member(0.2), member_activity_check(0.4), member_ajaxboard(2.1.1), member_block_addon(0.4), member_control(0.1), member_extra_check(2.0), member_extra_vars_check(1.0), member_icon_print(0.3), member_join_ex(0.2.3), member_layer_config(1.1), memberinfo(1.10), messageTalk(2.0.1), message_btn(1.0.2), meta_add(0.2.2), mobile_extend(0.5.1), mobile_redirect(1.0), msg_point(1.0), multimedia_thumbnail(2.0.0), my_comment_addon(1.1.2), my_reading(1.1), naver_analytics(1.2), naver_syndication(0.1), new_document_notify(2.0), new_document_notify2(1.0.12), noclick(1.3), nprogress(0.1.1), oembed(1.0), opengraph(0.11), people_like(1.1), php_exif(1.0), placeHolders(1.0), planet_bookmark(0.1.1), planet_todo(0.1.1), pnbsp(0.2), point_pang_pang(1.0), point_pangpang_plus(0.1a), popup_opener(1.5.2), prettyphoto(1.1.3.0), prohibit_monologue(0.1), push_doc(0.1), radarURL(1.2), rainbow_link(0.3), recommend(1.0), recycled(1.0), refhide(0.1.1), remove_id_search(1.0), report_addon(0.2), resize_signature(0.1), robotcontrol(1.1.0), scmlock_board(1.5), searchhighlight(0.2), sejin7940_addvote(1.2), sejin7940_align(1.0), sejin7940_all_notice(1.4), sejin7940_autotrash(1.1.1), sejin7940_kakao_link(0.5.3), sejin7940_mobile_resize(1.0), sejin7940_mustlogin(0.2), sejin7940_readed_count(1.6), sejin7940_write_limit(1.5.2), setitle2(2.1.0), settitle(1.3), shortcut(0.9.9.3), show_document_voter(0.1.1), show_minfo_point(0.1), show_mobile_write(0.1.2), sns_card(1.1), sns_linker_lite(1.1), socialxe_helper(1.0.6), socialxe_mid_forwarder(1.0.3), soo_add_content(0.5), soo_add_ssl(0.1), soo_feed_delay(0.1), soo_googleplus(0.2.1), soo_jquery_unload(2012.1.23), soo_mcrblog_link(1.2.14), soo_parking(0.3a), ssl_support(0.1), stalk(0.1), stats(1.1), stop_spambot_xe(0.6), sxe_bbcode_lite(0.1), sxe_block_write(0.2), sxe_ncenter_plus(0.2), sxe_now_connected(0.2), sxe_writing_format(0.2), syncNick(1.0), tag_relation(1.4.1), tag_relation_add(1.4.1), thumbnailer(0.1), to_sns(0.2.1), today_fortune(1.0.1), updatecategory(1.0), vegas_background(0.2), voteNmove(1.1), write_limit(1.2.1), xdt_google_analytics(1.1), xss_session_protector(0.1), youtube_control(1.2)

지울건 지워보고 요렇게 되었습니다.

**Comment by mactopia** [comment]
아..성공했습니다. 회원 정보 관리 애드온 문제 였습니다....이제 일반 회원까지 통과됩니다.
다시한번 정말 정말 감사드립니다.

**Comment by mactopia** [comment]
@bnu  님 혹시나 하여 적습니다.

제말은 @YJSoft  님 방법대로 수정하고 위 애드온을 끄면 통과 가능합니다. @YJSoft 님 방법 대로 하지 않으면 뭘 해도 방법이 없었습니다.

**Comment by qw5414** [comment]
@mactopia 애드온의 따라 문제점이 발생되는점이 있다면 그 해답을 바로 찾아드리긴 어렵습니다.

애드온중에서 display부분이나 회원부분을 제어하는 애드온의 영향을 받을 수 있습니다.

각 애드온의 문제이니..어떤애드온인지 파악하시고 그 애드온의 제작자에게 문의 하시는것이 좋습니다.

**Comment by mactopia** [comment]
@qw5414 애드온 문제가 아니라 코어를 위 소스대로 수정하고 나니 해결이 되었습니다. @YJSoft 님 방법 대로 하지 않으면 뭘 해도 방법이 없습니다.

**Comment by qw5414** [comment]
@mactopia https://github.com/xpressengine/xe-core/pull/1244/files 이걸 수정하고 애드온을 끄거나 키면 문제점이 해결되는데 이걸 수정하지 않으면 애드온이고 뭐고 안된다는 말씀이신가요?

**Comment by hhgyu** [comment]
#1244로 해결된 문제 입니다. 그래서 Closed 된거 같습니다.
