### ISSUE TITLE
쉬운 설치에서 installed 선택 후 일부 페이지에 목록이 나타나지 않습니다. 

### ISSUE THREAD

**Issue by bell5kim** [xpressengine/xe-core#1241]
쉬운 설치에서 installed 선택 후 일부 페이지에 목록이 나타나지 않습니다. 
일부 페이지는 목록이 보이지만 일부는 보이지 않습니다. 
버젼 1.7.8 부터 생긴 현상입니다.

**Comment by allcalc** [comment]
저는 3페이지가 빈페이지입니다.
![k-43](https://cloud.githubusercontent.com/assets/10527959/6091590/96975cbc-aef6-11e4-8615-a43058a31cf5.png)

**Comment by khongchi** [comment]
쉬운설치의 installed 목록에서 특정 페이지가 출력되지 않는 이유는
특정 페이지에 출력될 자료 중에 자료실에서 차단된 자료가 있을 경우, 자료실 서버에서 오류가 발생하여 제대로 자료목록을 전달해주지 못하는 문제 때문이였습니다.

오류가 발생되지 않도록 조치했습니다.

다만, 차단된 자료를 숨김처리만 했기 때문에, 차단된 자료가 installed 자료의 개수에 여전히 포함되고, 페이지에서 차단된 자료는 보여지지 않습니다. installed 자료에서 차단된 자료를 제외하기 위해서는 구조적으로 큰 작업이 필요하므로 차후 자료실/쉬운설치 개편시 처리할 예정입니다.

감사합니다.
