### ISSUE TITLE
포인트를 -로 진행되지 않게 한 이유가 있을까요?

### ISSUE THREAD

**Issue by anizen** [xpressengine/xe-core#1242]
포인트 모듈에서 포인트가 0이하면 0으로 고정하도록 처리가 되어 있습니다.

따라서 포인트가 마이너스로 진행이 되지 않는데,

이럴 경우 필요한 포인트를 위해 글을 작성한 후 필요한 포인트를 사용한 후 글을 삭제하게 되면,

0포인트가 그대로 유지되어 악용할 소지가 있다고 생각합니다.

따라서

/modules/point/point.controller.php

513
        //if($args->point < 0) $args->point = 0;

을 주석처리 하거나, 삭제해야 할 것 같습니다.
아니면 옵션으로 제공하는 것도 나쁘진 않을 듯 합니다.

**Comment by mog422** [comment]
개인적으로 저도 해당 부분을 주석처리 하고 사용하고 있습니다.

옵션으로 제공하거나 해당 부분이 삭제되었으면 좋겠습니다.

**Comment by Web-Engine** [comment]
선택적으로 사용하도록 수정해서 Pull Request 넣었습니당.

**Comment by anizen** [comment]
@Web-Engine 감사합니다.
