### ISSUE TITLE
1.7.10 이후 로그인 위젯으로 로그인시 페이지 갱신이 안되는 문제.

### ISSUE THREAD

**Issue by anizen** [xpressengine/xe-core#1246]
SSL 사용을 '선택적'으로 사용시 해당 문제가 발생.

로그인 자체는 되나, 페이지 갱신이 없이 현재 페이지에 머물게 됩니다.

SSL 사용을 항상/사용안함시에는 문제가 발생하지 않습니다.

**Comment by anizen** [comment]
https://www.xpressengine.com/index.php?mid=forum&document_srl=22937309&comment_srl=22937805&rnd=22937805#comment_22937805

이글을 참고해주세요.

이렇게 수정하면 일단은 응급조치로 해결이 됩니다.

parent에 대한 권한이 없다고 하는데 정확히 무슨 문제인지는 모르겠네요...

**Comment by dorami** [comment]
#1230 으로 인한 문제 입니다.

**Comment by dorami** [comment]
@anizen @bnu #1230 으로 인한 문제 입니다.
