### ISSUE TITLE
구글 크롬브라우저에서 첨부파일 미리보기 문제

### ISSUE THREAD

**Issue by botserv** [xpressengine/xe-core#1251]
구글 크롬브라우저에서 스트리밍 파일의 경우 (mp3등)

통합검색기능을 이용하여 검색된 결과값의 미리보기가
IE의 경우 Play버튼을 클릭해야 재생을 하지만

크롬브라우저에서는 여러파일이 노출 되었을경우, 동시에 재생해 버리는 문제가 있습니다.

**Comment by izuzero** [comment]
#1113

두 번이나 올리셨는데 해결이 안 돼서 올리신 건가요?

**Comment by botserv** [comment]
@izuzero 해당 이슈가 수정되어서 닫힌줄 알고 다시 올렸습니다.

**Comment by anizen** [comment]
autoplay가 표준일걸요

**Comment by bnu** [comment]
autoplay로 변경해봤지만 크롬이 내부적으로 video태그로 변환하면서 속성을 반영하지 못했습니다.
