### ISSUE TITLE
lang.xml에 선택권을 주었으면 좋겠습니다.

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1253]
lang.xml 만 한국어로만 다이어트 시켜줘도 엄청 빨라지거든요

국내 유저를 위해 lang.xml 중에서 한국어로만 이루어진 부분이 기본이 되면 좋겠으며

다국어 유저를 위한 lang.xml을 선택 할수 있게 해줬으면 합니다. 해외 유저가 국내 유저보다 더 많다면 
반대로 되고 뭐 좋고요.

**Comment by qw5414** [comment]
lang-kr.xml
lang-en.xml
이런 형태로 파일갯수를 늘리는건가요?

글쎄요..

그게 더 복잡해지지 않나요? 관리도 그렇고....

악사리 클라이언트를 분리 하는거면 더 싫고...

**Comment by mactopia** [comment]
관리자 입장에서는 지원 언어에서 한국어 만을 선택한경우 한국어로 이루어진 xml 을 이용하는게 속도도 그렇고 말이 된다고 생각합니다.

**Comment by qw5414** [comment]
배포해야 하는 입장에서 전체적인 관리를 따졌을때는 어느편이 더 효율적인것인지 따져야하는 부분이라고 생각되요.

기존에 xe1.5일때 님이 말씀해주신 부분처럼 php파일을 따로 세분화 하여 사용했지만, 결론적으로 여러 언어를 사용하는 사이트에서는 비효율적인면을 보이기도 하다고 판단되어서 1.7에서 xml방식으로 바뀐것 같은데.. 사실 결론적으로 정해진 부분은 없습니다만.. 전체 코어 배포를 따졌을때는 지금이 오히려 낫다는 판단이...

**Comment by YJSoft** [comment]
@mactopia 현재도 xml 파일에서 언어별로 따로 php 캐시를 생성 후 사용하고 있습니다.
files/cache/lang 폴더에 php 파일로 쌓이며 활성화되고 사용이 한번이라도 된 언어의 캐시만이 생성됩니다.

**Comment by dorami** [comment]
@qw5414 XE 1.4 까지 ko.lang.php en.lang.php로 분리되어 있었습니다. 저도 람보님 의견에 동의합니다.

**Comment by anizen** [comment]
나중에 추가할 때 오히려 현재 방식이 문제가 됩니다.

예를 들면 저는 한글과 영문만 되어 있고, 일본어를 추가하고 싶습니다.

그런데 다른 사람이 일본어를 추가한 파일이 있네요. 근데 이분은 한글과 일본어만 있어요.

그럼... 일일이 찾아서 추가해야합니다..

**Comment by ngleader** [comment]
lang.xml 를 변경할 필요는 없다고 생각됩니다. 다만 성능상 문제가 확인되면 해당부분에 대해서는 논의가 필요할 것 같습니다.
