### ISSUE TITLE
관리자 페이지 디버그 모드

### ISSUE THREAD

**Issue by botserv** [xpressengine/xe-core#1259]
PHP 5.2.17 환경에서

debug 값을 출력하기 위해 
config.inc.php 에서 해당 부분을 주석하고 관리자 페이지로 접속하면,
PHP Warning:  Invalid argument supplied for foreach() in /home/html/modules/module/module.model.php on line 665

위 에러를 뿜어내고, 모듈 및 관리자 메인 페이지 접근이 안됩니다.

foreach($triggers as $item)

해당 	function getTrigger($trigger_name, $module, $type, $called_method, $called_position)을

(Xe1.5)구버전 소스로 변경하면 또 정상 출력이 됩니다.

**Comment by YJSoft** [comment]
...?
주석하고 가 어떤것을 말씀하시는건지 모르겠습니다만 디버그 활성화는 `config.user.inc.php` 파일에
```php
<?php
define('__DEBUG__',1);
define('__DEBUG_PROTECT_IP__','본인 아이피');
```
이렇게 설정하는 것입니다.

어느 부분을 주석처리했는지 자세히 써주세요.

**Comment by botserv** [comment]
XE에서 PHP에러 출력을 막고 있어서 
아래 부분을 주석하고 이용했습니다.

if(version_compare(PHP_VERSION, '5.4.0', '<'))
{
        @error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING);
}
else
{
        @error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING ^ E_STRICT);
}

**Comment by izuzero** [comment]
제가 커밋한 이슈입니다.
getTrigger 함수 안의 foreach 문을 감싸는 if 문이 필요할 것 같습니다.

if (is_object($triggers)) ...

**Comment by bnu** [comment]
fixed #1265
