### ISSUE TITLE
capcha 애드온 심각한 오류가 있습니다.

### ISSUE THREAD

**Issue by botserv** [xpressengine/xe-core#1261]
그 동안 사이트의 알 수 없는 이유로 500에러 출력으로 많은 고생을 해왔습니다.

정상작동하다가 며칠마다 한번씩 500에러 문제가 발생하더군요..

해당 문제가 발생 할 때 신기한점은, PC버전에서는 500에러를 뿌리고,

모바일 버전에서는 정상적으로 사이트가 동작되는 현상이 이상했습니다.
(아마도 캡챠애드온 디폴트가 PC에만 체크되어있어서 그런듯 합니다.)

그 동안은 모듈쪽 문제라 생각하고, 모듈쪽 문제를 봤는데 모듈쪽 문제가 아니고
사이트 500에러 이상현상이 생겼을 떄 애드온에 캡챠 애드온을 빼니까
정상적으로 사이트가 출력되더군요..

config 의 디버그나, php.ini의 display_error 을 설정해놔도 에러코드를 출력하지 않아서
그 동안 해결에 어려움이 있었습니다.

다만 신기한점은 해당 문제가 발생해서, 500에러를 뿌릴 때

service httpd restart 명령어를 통해 아파치를 다시 실행하면 웹페이지가 정상적으로
돌아온다는 점이었습니다.

캡챠 애드온은 XE이용자들 대부분 사용하기 때문에 저 같은 극소수 이용자들만 
문제가 발생하는 것 같습니다.

웹서버 환경은 Server version: Apache/2.2.23 (Unix)
PHP 환경 PHP 5.2.17 with Suhosin-Patch 0.9.7 (cli) (build) 
XE1.7.10

현재는 캡챠 애드온을 끄고 운영중입니다.
왜 이런 현상이 발생하는 걸까요?

**Comment by delphixe4** [comment]
그렇다면 서버측 php 문제 아닐까요?

**Comment by botserv** [comment]
php 는 1.4.X 버전대부터 5.2.17을 사용해왔는데

1.7 업그레이드후 발생하는 문제에요

XE에서 php 5.2.8 이상버전 부터는 지원한다고 되어있으니 코어에서 수정되었으면 좋겠습니다.

**Comment by YJSoft** [comment]
@botserv 오류 메세지를 켜도 오류가 뜨지 않는다면 XE 문제가 아닌 php 자체 문제일 가능성이 큽니다.(메모리 부족, php 다운 등)
캡차 애드온 특성상 이미지 파일을 생성하기 위해 메모리를 사용하기에, 문제가 발생할 수 있습니다.

**Comment by delphixe4** [comment]
서버의 php 버전 문제가 아니고 php 프로세스 문제라는 의미였습니다

**Comment by BJPain** [comment]
요즘은 뚫기 어려운 ReCapcha 2.0(맞는지는 모르지만..) 모듈이 나왔더라고요..(XE 홈페이지나 간편설치 미지원) 따른 페이지에서 받아서 수동설치해야 되기는 하지만.. 그래도 리캡챠 2.0을 쓸 수 있으니 ㅎㅎ
