### ISSUE TITLE
정확하지 않습니다만.. php5.5.10에서 오류 (?)

### ISSUE THREAD

**Issue by reebit1990** [xpressengine/xe-core#1263]
확실하지 않은 이유가 ampsetup로 돌려본거라.. 그래도 보고 할게요. php 5.5.10에서 글 작성시 [공지]글로 자동으로 설정되는 현상(해제되있어도 자동으로 공지가..)이 있습니다. 검토 부탁드립니다.

**Comment by YJSoft** [comment]
php 5.5.10에서 증상이 재현되지 않습니다.
http://php5510.yjsoft.info/board

사용중이신 애드온/모듈을 다시한번 확인해 보세요. 충돌이 있을수 있습니다.

**Comment by reebit1990** [comment]
@YJSoft 그럴 가능성도 있겠네요. 그것도 확인했어야 했는데..
이렇게 검토해주셔서 감사합니다 :) (꾸벅)
