### ISSUE TITLE
install.css 와 admin.bootstrap.min.css 가없습니다. 지금 설치 버전 제대로 안나옵니다.

### ISSUE THREAD

**Issue by hancoma** [xpressengine/xe-core#1277]
지금 배포중이신 설치버전을 보시면 두 css가 없습니다. 그래서 화면이 제대로 나오지 않습니다. 확인해 보세요.

**Comment by YJSoft** [comment]
![image](https://cloud.githubusercontent.com/assets/5893514/6242199/af203130-b76d-11e4-8129-a0755a10bb98.png)

IIS8.5 + php 5.6에서 버전 1.7.11 설치 화면 정상적으로 잘 나옵니다.
사용중인 서버 소프트웨어(IIS,Apache) 설정을 확인해 보세요.
또한 mod_security 같은 보안 모듈 때문일 수도 있습니다.
