### ISSUE TITLE
session_set_save_handler 문제

### ISSUE THREAD

**Issue by churow** [xpressengine/xe-core#1281]
특정 환경에서 XE의 세션이 files/config/db.config.php에서 use_db_session 값이 Y임에도 불구하고 DB에 저장되지 않는 문제가 있어서 살펴봤더니, Context.class.php의 init() 메서드에서 사용하는 session_set_save_handler() 함수에서 false가 나왔습니다.

이 함수에서 false가 나오는 원인을 찾아보니, PHP의 설정값 중에서 session.auto_start가 on일 경우 이 함수에서는 무조건 false가 나옵니다.

PHP 설정값을 바꿀 수 있는 환경이라면, 예를 들어 .htaccess에 php_flag session.auto_start off 하는 식으로 이 문제를 해결할 수 있습니다.

PHP 설정값을 바꿀 수 없는 환경이라면, session.auto_start on일 경우 use_db_session 값을 Y로 해도 세션이 DB에 저장되지 않는다는 사실을 알려줄 필요가 있습니다.

**Comment by YJSoft** [comment]
@churow 
![image](https://cloud.githubusercontent.com/assets/5893514/6245890/6f64e1ec-b7a6-11e4-890c-38df0ed7ef71.png)
해당 설정은 설치 필수 조건중 하나로 설치시 이 값을 체크하도록 되어 있으나 현재는 코드가 잘못되어 있습니다.

**Comment by churow** [comment]
히스토리를 보니 참 오래 된 버그였네요.. session.auto_start on인 환경도 많지 않고, DB가 아니어도 파일로도 잘 동작하니 쉽게 눈에 안 띈 모양입니다.
