### ISSUE TITLE
Faceoff 레이아웃 제거해야 하지 않나요?

### ISSUE THREAD

**Issue by Web-Engine** [xpressengine/xe-core#1285]
FaceOff 레이아웃이 전에 지원 중단된거로 알고 있고, 생성하려고 하면 not support 하는 오류 메세지도 출력하고 있는데 제거해야 맞지 않나요?

**Comment by dorami** [comment]
XE 1.5에서 'FaceOff 레이아웃은 지원이 중단될 예정입니다. 반드시 안내에 따라 FaceOff 레이아웃을 일반 레이아웃으로 변경하여 주시기 바랍니다.' 라고 공지가 되어 있었는데.. 더이상 필요가 없으니, 제거하는게 맞다고 봅니다. 없을꺼라고 예상하지만, 기존 사용자에 대해 문제가 생기는 부분이 있을까요?

**Comment by misol** [comment]
사용자가 관리자 페이지에서 HTML/CSS 편집하는 부분이 FaceOFF 를 일부 이용합니다. 잘 걷어내면 가능할지도요..
