### ISSUE TITLE
이거 대체 무슨 문제인가요? 백지현상?

### ISSUE THREAD

**Issue by wkaak105** [xpressengine/xe-core#1286]
간헐적??으로가 아니라 페이지 새로고침 또는 페이지 이동마다 해당 현상이 나타납니다
백지현상이 나타나서 기존코어버전으로 재설치도 해보고 코어버전도 1.7.6에서 가장 최근의 최신버전으로도 업데이트해봤는데 똑같은현상이 나타납니다. 

<img src="http://atomicpark.co.kr/imgs/fa.jpg" alt="img" />

**Comment by YJSoft** [comment]
서버 사양, php 오류 로그나 사용중인 모듈/애드온 확인해주세요.

**Comment by wkaak105** [comment]
서버사양: 
델 파워엣지 r520
cpu 인텔 제논 붜드코어 e5-2407 
ram ddr3 pc3-10600 8gb
hdd ssd 360gb
bay 8bay 2u


php 5.1.45

xe에서 따로 설치한 모듈, 애드온, 위젯 없습니다. (해당 레이아웃 위젯 제외)

**Comment by YJSoft** [comment]
@wkaak105 XE가 지원하는 PHP 버전은 5.2.4 이상부터입니다.
https://www.xpressengine.com/about

**Comment by wkaak105** [comment]
@YJSoft 감사합니다 잘못적었네요 . PHP는 5.3 이고, SQL이 5.1.45 입니다
지금 DB 백업하고 다시 설치합니다. 문제가 또다시 나타나는경우 일부 DB 데이터만 백업하고
날려버려야겠지요;

**Comment by misol** [comment]
http://atomicpark.co.kr/ 새로고침도 해보고, 페이지 이동도 해보았는데, 문제가 나타나지 않습니다.
문제가 해결 되셨는지요?
