### ISSUE TITLE
procBoardInsertDocument와 첨부파일 존재 게시글 관련

### ISSUE THREAD

**Issue by KissT0XE** [xpressengine/xe-core#1287]
procBoardInsertDocument act가 감지될때 특정 작업을 수행하게 하려는데,
첨부파일 존재시 작동이 안되는 현상이 재현되고 있습니다.

의심되는 바로는 첨부파일을 업로드 하면 srl값이 부여되서 그런 것 같은데, 정확한 원인을 모르겠습니다.
(만일 이 경우라면 임시저장된 게시물에도 작동이 되지 않아야 하겠지요)

관련 글 : https://www.xpressengine.com/qna/22945994

이즈야님이 댓글 주셨지만 이건 코어상의 버그인 것 같아서 이슈를 등록해봅니다.

**Comment by izuzero** [comment]
documentModel::getDocument 함수는 전역변수와 캐시에서 게시글 정보를 가져오도록 설계되어 있지만 게시글에 변동이 생길 때 전역변수와 캐시를 초기화해주지 않아서 생기는 문제입니다.
