### ISSUE TITLE
php 5.5.9 사용 중 입니다. 글쓰기시 Access denied 표현됩니다.

### ISSUE THREAD

**Issue by ac3000** [xpressengine/xe-core#1288]
얼마전까지 php 5.3을 사용하다.
php5.5.9로 넘어왔습니다.
코어버전은 1.7.11 사용중이며 게시판은 코어상 기본게시판 스케치북게시판으로 테스트 하였습니다.
증상은 게시판에서 글쓰기를 누르면 게시글에 미리 내용 입력을 해 논것 처럼
"Access denied."가 작성된 채로.. 글쓰기를 해야합니다.
 해당 스크린샷은
https://www.xpressengine.com/forum/22947156
지금까지 에디터보다가 아무것도 모르겠어서 이슈를 남겨봄니다.
꼭 고쳐주셨으면 좋겠습니다. ㅠㅠ
혹시나해서 예전 에디터 xeed를 적용해 봤는데 증상은 사라졌습니다..
어떤게 문제인지 모르겠습니다 ㅠㅠ 관심을 가지고 한번 봐 주셨으면 좋겠습니다.

**Comment by ac3000** [comment]
익스 플로러에서는..
https://www.xpressengine.com/index.php?mid=forum&document_srl=22947803
아래 링크와 같이 표현됩니다..

**Comment by kijin** [comment]
그 부분에 들어가는 파일은 에디터 설정에 따라 다르기 때문에, 문제를 해결하려면 힌트가 조금 더 필요합니다. (HTTP 403 오류이며, XE에서 생성하는 오류메시지는 아닌 것 같습니다.)

개발자도구(F12)를 열고 에디터의 빈 부분(또는 에러 표시되는 부분)을 선택한 후, 아래에 나타나는 소스에서 `<iframe>` 태그의 `src` 속성을 확인해 보세요.

스크린샷 참조 (Firefox 기준)

![screenshot](https://cloud.githubusercontent.com/assets/164058/6365273/b87057d0-bcf7-11e4-8198-410846e8064e.png)

이 주소에 직접 접속하면 어떻게 나오나요? 여전히 Access denied 또는 HTTP 403 오류인가요? 그렇다면 서버측에서 해당 파일이 존재하는지, 퍼미션은 맞는지, 혹시 .htaccess에서 막혀있지는 않은지 확인해 보세요.

**Comment by ac3000** [comment]
일단 현재 서버상태는 nginx입니다. 그래서 htaccess는 사용하지 않습니다.
제가 주소를 적어놓질 않았네요 죄송합니다.
cigdiy.com 입니다 ㅠㅠ 한번더 관심 갖어주시면 정말 감사하겠습니다.
모바일에서는 정상으로 표현됩니다 ㅠㅠ
에디터는 퍼미션을 777까지도 줘 봤는데 ㅠ
서버 php업그레이드 후 이런 현상이 나타나 아마 호환문제 인듯 해서 이렇게 질문 하여봤습니다.
한번만 더 확인 부탁드리겠습니다 고수님
스크린샷까지너무 감사합니다.

**Comment by kijin** [comment]
http://cigdiy.com/modules/editor/styles/default/editor.html

위의 경로에서 `403 Forbidden` 오류가 발생하고, "Access denied." 라고 나옵니다.

또한 `X-Powered-By` 헤더를 보면 PHP 구동이 필요하지 않은 파일인데도 PHP 인터프리터를 거쳐서 실행하도록 되어 있고, "Access Denied." 메시지는 PHP-FPM 프로세스에서 해당 파일에 접근하지 못하기 때문에 발생하는 에러로 보입니다.

아래의 두 가지를 확인해 보시면 되겠네요.

- 왜 확장자가 `html`인 파일을 nginx가 직접 전송하지 않고 PHP를 거치도록 설정되어 있는지
- 왜 PHP-FPM 프로세스가 해당 폴더에 접근하지 못하는지

결론: XE와는 전혀 무관하고, 서버 설정에 따른 문제입니다.

**Comment by ac3000** [comment]
해결하였습니다 감사합니다^^
location ~ \.php$ { 이부분이
location ~ \.(php|html|htm)$ {
이렇게 되어있었네요 ㅡ.ㅡ;;
왜 이런지 모르겠지만 덕분에 문제점 찾아서 풀었습니다. 감사합니다.
복받으실거에요!! xe문제아니였네요 괜히 죄송스럽고 그러네요 ㅠㅠ
