### ISSUE TITLE
그룹연동 포인트에 오류가 있는 듯 합니다.

### ISSUE THREAD

**Issue by ijex** [xpressengine/xe-core#1291]
XE Core 1.7.11에서 발견된 문제입니다.
관리페이지>회원>포인트 에서 최고레벨, 포인트이름,포인트부여 등을 수정했을 때 그룹연동 항목에 있는 그룹들의 레벨이 1로 설정되고 해당 그룹을 삭제 후 다시 생성해야 그룹연동이 해제됩니다.

**Comment by YJSoft** [comment]
#1247 #1248

**Comment by bnu** [comment]
fixed #1248
