### ISSUE TITLE
1.8 beta 사이트 메뉴 편집 (메뉴를 추가해도 표시가 안보임)

### ISSUE THREAD

**Issue by braak0405** [xpressengine/xe-core#1294]
<img src="http://i.imgur.com/eRqoNSG.png?1">

크롬,익플 둘다 보이지않습니다. 
HOME이라는 모듈을 등록했구요, 
현제 XE공홈에서 
"Download XpressEngine 1.7.11 (2015. 2. 17) 을 누르면 1.7.11버전이 아닌 1.8버전을 다운받도록 이동됩니다 수정부탁드립니다.

**Comment by YJSoft** [comment]
@braak0405 메뉴 옆 폴더를 눌러 메뉴를 펼쳐 보세요.

**Comment by izuzero** [comment]
메뉴 이름 옆에 폴더 아이콘을 클릭해보세요.
그리고 이슈 하나에는 하나의 내용만 적어주세요 :)

**Comment by braak0405** [comment]
폴더눌러도 같습니다. 이미 봐볼만큼 다 봐보고 문의 드리는겁니다.
내용 두개인것은 정말 죄송합니다.
