### ISSUE TITLE
확장컴포넌트 작동 안됨(Code Highlighter)

### ISSUE THREAD

**Issue by anizen** [xpressengine/xe-core#1296]
공홈에서 Code Highlighter를 사용하여 답변을 달려고 하니...

아예 먹통입니다. 본문에 추가가 안되네요 아마도 삽입하는 방법이 바꼈나 봅니다.

**Comment by DingGGu** [comment]
Code Highlighter가 더 정확한 표현이 맞는 것 같아요.

**Comment by anizen** [comment]
@DingGGu 수정했습니다

**Comment by bnu** [comment]
베타2에서 수정되었습니다.
