### ISSUE TITLE
user_id 하이픈 들어갈 경우 ldap trigger 배제 되는 현상.

### ISSUE THREAD

**Issue by oltre** [xpressengine/xe-core#1298]
login widget을 수정하여 로그인시 procMemberLogin 을 호출하도록 하였습니다.

다른 ID들은 문제가 없었지만.
ID 중간에 하이픈(-) 이 들어가 있을 경우 ldap 통신을 하지 않고 아이디/비밀번호 체크를 하는 부분으로 들어가게 되어 문제가 발생하는 것 같습니다.

정확하게 trigger가 어떤식으로 동작하는지 몰라 스스로 해결하지 못하여 이슈사항 등록을 하게 되었습니다.
trigger 관련 함수 호출시 하이픈(-)을 사용하게 되어서 그렇게 되는 거 같긴 합니다만.;;
추측일 뿐이고 어디 부분에서 처리하는지 알 수 없는 것 같습니다

**Comment by 1Sam** [comment]
그거...
http://1sam.kr/index.php?mid=xe_tips&page=2&document_srl=69533

이것 때문이 아닌가요?

**Comment by oltre** [comment]
classes/xml/xmlquery/argument/Argument.class.php

파일의 정규 표현식인 '/^[a-zA-Z]+([_0-9a-zA-Z]+)*$/is'
부분이 false로 떨어져서 발생했던 문제였습니다.

**Comment by oltre** [comment]
음.... 저기까지는 이유파악은 못했습니다.

금일 debugPrint로 ldap에서 insert 부분에서 실패하는 것을 확인하여 로그 출력 결과.

user_id 정규식 표현이 잘못 되는 것으로 파악이 되었고.

grep으로 insertMember 호출 하는 부분을 확인했더니 checkFilter 함수 호출하는 것으로 파악하여서

해당 부분 들어가봤더니 정규표현식으로 처리하는데.

그 부분만 따로 php파일 만들어봤더니 false 처리 되면서 에러 내고 있었습니다.

그래서 해당 정규표현식 수정하는 것으로 해결하였습니다.



2015-03-04 1:47 GMT+09:00 1Sam Online <notifications@github.com>:
