### ISSUE TITLE
ck에디터에서 있는 메뉴중에서.

### ISSUE THREAD

**Issue by ToFinders** [xpressengine/xe-core#1318]
이미지랑 플레쉬가 있더군요. 이것이 추가기능과 중첩되어진 내용이 아닌가요?
ck로 간다면 이 기능이 없어도 될듯하여서 글 하나 남겨봅니다. 

이렇게 남기는것 맞나요? ^^

**Comment by bnu** [comment]
툴바의 버튼은 http://ckeditor.com/demo#full 이 페이지의 데모와 같은 구성에서 배치를 변경하고 일부 버튼은 제거한 상태입니다.

주신 의견과 공식사이트에서 의견 주신 내용을 바탕으로 툴바를 한 번 더 정리 할 계획입니다.

**Comment by bnu** [comment]
일부 버튼을 제거하고 정리했습니다.
![2015-03-25 4 48 20](https://cloud.githubusercontent.com/assets/53764/6820236/f9b95a4c-d30f-11e4-8ab9-9b8f0fad4eca.png)
