### ISSUE TITLE
local 에서 phpinfo 나 등등을 위한 php파일 생성시. [1.8-beta이슈]

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xe-core#1320]
지금 적용된 Router 기능에 문제점이 있습니다.

이경우는 조금 드문 경우이긴 하나, local 에 바로 올린 php 파일을 전혀 못가져오는 문제점이 있습니다.

phpinfo 나 등등을 위해서 로컬에 적용한채로
도메인/phpinfo.php
이나

도메인/sosi.php 을 할경우 php 의 파일을 못가져오는 것 같습니다.

베타 php 에서

.htaccess
파일만 원상복구 하면 다시 가능해지긴 합니다.

이부분의 개선이 필요할 것 같긴합니다.
(이렇게 사용하는 사용자도 몇있고.. instagram의 api정보를 위한 계정의 키를 가져올때 루트의 php파일을 이용하기도 해서요..

**Comment by YJSoft** [comment]
```
# router
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteRule ^(.*)$ ./index.php [L]
```
이렇게 되어 있어서, 요청한 파일이 파일이나 경로일 경우 제외하도록 되어 있습니다.
apmsetup으로 테스트 결과 루트의 php 파일을 잘 불러오고, 가상 디렉토리(phpmyadmin)또한 정상 작동했습니다.

다만 간혹 서버 설정 문제인지 파일이 있음에도 조건문에 걸리지 않는 경우가 있는것 같긴 합니다.(php 4.4 구동 서버에서 Textcube 1.7.8로 확인 - 텍스트큐브는 rewrite.php 방식을 사용합니다)

**Comment by qw5414** [comment]
@YJSoft C패널 사용, (Luatic.co.kr 에서 가상클라우드 세팅) php5.4 환경에서 사용이 안되어서요 ..

(C패널자체도 제가 직접 깐게 아니라.. 루아틱님이 직접 지원해주신거라..)

**Comment by YJSoft** [comment]
@qw5414 서버 세팅문제 같습니다.
w01 서버인데 정상 동작합니다. http://yjsoft.ga/phpinfo.php?key=qlqpqkrtk

**Comment by qw5414** [comment]
@YJSoft 특정 서버 세팅의 영향으로 인한 라우터의 기능의 의해 사용을 못하는 부분이겠군요..

그렇다면 이걸 해결 하고 싶으면.. 1,8에 이 기능이탑제된 상황에서는 해결이 불가능할까요..

이게 저번에도 develop 에 라우터 기능이 들어갔을때 생겼던 문제이라서요.
