### ISSUE TITLE
1.8.0 Beta 적용이후 회원가입 설정 - 약관 설정이 되지 않습니다. 

### ISSUE THREAD

**Issue by animiner** [xpressengine/xe-core#1322]
아예 페이지에 뜨지를 않네요.

중복이면 삭제하겠습니다.

**Comment by YJSoft** [comment]
에디터가 정상적으로 떴는지, 에디터 동작은 정상인지, 브라우저 콘솔창에 오류는 없는지 확인 부탁드립니다. IIS+php 5.6 Win8+크롬 테스트 정상입니다.

**Comment by dmzvillager** [comment]
ck 에디터에 컴퍼넌트 "미솔's 비디오 검색 글쓰기 도구 ver. 0.5.1(https://www.xpressengine.com/index.php?mid=download&package_id=21014822)"를 사용에 체크하면 에디터 스킨이 비활성화되고, 관리자 페이지>회원>회원설정>회원가입에서 회원가입 약관이 뜨질 않습니다.

**Comment by yyj9411** [comment]
@dmzvillager 해당 서드파티 컴포넌트 제작자분께 문의해주세요.

**Comment by misol** [comment]
@dmzvillager 해당 서드파티 컴포넌트 개발자입니다. 베타3 이후에 고쳐보겠습니다. 그때쯤 XE포럼에 글 한번 더 남겨주세요!

**Comment by klee4413** [comment]
xe Beta 182
It happened as the below right after installation using php 5.3.1

Fatal error: Call to undefined method Object::executeQuery() in C:\xampp\htdocs\clock8\config\func.inc.php on line 222
