### ISSUE TITLE
1.8 (XE공홈) 파일 첨부 본문 삽입 및 코멘트 파일 삭제 문제.

### ISSUE THREAD

**Issue by anizen** [xpressengine/xe-core#1325]
1. 글쓰기 & 코멘트 공통
   
   > 파일 첨부한 항목을 본문 삽입 시 먹통.(첨부한 파일 .zip)
2. 코멘드 해당
   
   > 첨부한 파일을 삭제시 file_srl을 찾을 수 없다며 에러

**Comment by YJSoft** [comment]
@anizen 해당 문제점들은 d72a4d07a46efa6b041b71ec202f39d525dfe2e3 로 수정되었습니다.
다만 공식 사이트에는 아직 적용되어 있지 않은것 같네요.

**Comment by anizen** [comment]
@YJSoft 코멘트에 첨부한 파일 삭제시 file_srl을 못찾는 것도 해결된 건가요?

**Comment by YJSoft** [comment]
@anizen 우선 업로드 이슈는, 선택된 파일을 가져올 때 페이지의 모든 selectbox의 선택된 것을 가져와서 발생하는 문제입니다. 댓글이 문제인건 아니구요, 글쓰기 화면에는 selectbox가 파일 업로더를 제외하면 없는데, 코멘트 화면에는 있어서 발생하는 문제였습니다.
