### ISSUE TITLE
마이그레이션툴 업데이트좀 해주세요!

### ISSUE THREAD

**Issue by Leehojun7777** [xpressengine/xe-core#1328]
안녕하세요!
그누보드5 자료 옮겨 올 수 있게 마이그레이션툴 업데이트 해주세요
누가 그러는데 4까지만 옮겨 올 수 있다고 하더라구요~
이슈?등록이 처음이라 번지수를 잘못 찾아 등록 하였더라도 이해 부탁 드립니다
죄송합니다 ㅠㅠ

**Comment by bnu** [comment]
마이그레이션 툴 이슈는 https://github.com/xpressengine/xe-migration-tool 에서 관리하고 있습니다.
xpressengine/xe-migration-tool/issues/5 에서 처리 될 예정이나, 일정은 정해지지 않았습니다.
