### ISSUE TITLE
애드온 인스턴스 개념 도입

### ISSUE THREAD

**Issue by Eundong** [xpressengine/xe-core#1336]
애드온을 지금 설치된 애드온당 한개의 설정만 사용할수 있는게 아닌, 
레이아웃처럼 인스턴스를 생성해서 설정을 다양화한 애드온을 여러곳에서 사용할수 있도록 개선되면 좋을꺼같습니다.

**Comment by wookho** [comment]
인스턴트가 어떤 것인지 모르겠는데요. 레이아웃 복사처럼 애드온 복사 기능을 지원하면 어떨까 합니다. 각 모듈에 다른 출력을 원하는경우 같은 애드온을 여러게 복사해서 FTP로 업로드해서 사용해야 하는데요. 이것을 관리자페이지에서 같은 애드온을 여러개 복사해서 사용할 수 있게요....

**Comment by YJSoft** [comment]
@wookho 말씀하신 개념이 인스턴스 개념입니다.

**Comment by wookho** [comment]
@YJSoft
아 그렇군요. 이거 완전히 필요한 기능입니다. 애드온 복사를 시도하다가 실패를 해서 사용을 하지 못하는 경험이 있어서요. 단순히 폴더명과 내용의 파일이름을 동일하게 변경해도 되지 않더군요.
