### ISSUE TITLE
1.8 베타 메일주소로 계정찾기시 에러

### ISSUE THREAD

**Issue by yeoreume** [xpressengine/xe-core#1340]
Nginx 1.7.9
PHP 5.6.7
?error_return_url=%2Findex.php%3F
에러페이지로 넘어가면서 찾기가 안되네요.

**Comment by qw5414** [comment]
@yeoreume 음 지금 1.8의 `.htaccess` 파일을 백업하시고 1.7.12버전의 `.htaccess`파일로 덮어 씌어서 테스트 해보시겠어요?

**Comment by yeoreume** [comment]
@qw5414 /index.php?error_return_url=%2Findex.php%3Fmid%3Dpage_NqHx08%26act%3DdispMemberFindAccount&vid=&ruleset=findAccount&mid=page_NqHx08&act=procMemberFindAccount&document_srl=&page=&xe_validator_id=modules%2Fmember%2Fskin%2Fdefault%2Ffind_member_account%2F1&email_address=

똑같이 500 내부서버 오류가 뜨네요.

**Comment by qw5414** [comment]
@yeoreume 다시 1.8 원본으로 돌리시고, 1,8부터 생긴 이슈이던가요?

**Comment by yeoreume** [comment]
@qw5414 넵 1.7.12까지는 문제가 없었는데
다 초기화하고 1.8로 새로설치해도 마찬가지네요.

**Comment by qw5414** [comment]
@yeoreume 아무래도 XE팀에서 정식적으로 확인하고 고쳐야할 부분같아요. 조금 기다려보세요~ 댓글을 기반으로 어느정도 버그부분을 유추해주실 수 있을 것 같습니다 :)
