### ISSUE TITLE
한글 도메인에서 리 디렉션 헤더에 UTF-8 문자열을 입력할 경우 발생하는 문제

### ISSUE THREAD

**Issue by misol** [xpressengine/xe-core#1345]
![2](https://cloud.githubusercontent.com/assets/3437916/6801752/1f24162a-d26e-11e4-835f-792a802c1766.PNG)
![default](https://cloud.githubusercontent.com/assets/3437916/6801755/2458246a-d26e-11e4-9b61-9aaf2882a58e.PNG)
위 이미지는 회원 설정 (http://www.김민수.한국/index.php?module=admin&act=dispMemberAdminConfig) 이후 발생하는 리디렉션에서 나타난 파이어폭스 오류 메시지 입니다.
1.8 최신 베타입니다. 기본 도메인을 베타 설치 후 재 입력했습니다.

헤더 정보는 캐릭터셋 정보가 없습니다. 당연히 ASCII 정보로 해석 되었으리라 믿습니다. 그러다보니 파이어 버그 이미지에서도 보시듯, 도메인이 깨져버립니다.

리디렉션을 위한 주소에는 모두 ASCII가 들어가도록 변경하거나 기본 도메인을 "푸니코드"로 다루는 것이 바람직해 보입니다. @bnu

**Comment by bnu** [comment]
punycode로 저장해두도록 되어 있습니다.
다만, 이미 설정한 값에 대해서는 별도로 처리하고 있지는 않습니다.

**Comment by misol** [comment]
@bnu 흐음;; 어디서 문제가 생긴건지 다시 한번 자세히 살펴보고 이 이슈에 기록하겠습니다 :)

**Comment by misol** [comment]
1.8.0 에서 재현되지 않네요! 이 이슈는 닫겠습니다! ㅎㅎㅎㅎ 고생 하셨어요!
@bnu
