### ISSUE TITLE
+ 또는 . 가 들어간 gmail 주소 중복 확인 기능이 필요합니다.

### ISSUE THREAD

**Issue by misol** [xpressengine/xe-core#1346]
@ngleader 님께서 알려주신 내용.

test.test@gmail.com 과 testtest@gmail.com은 같은 이메일 주소

test@gmail.com과 test+01@gmail.com test+a@gmail.com 등 은 같은 이메일 주소

중복 확인할 필요가 있음.
1. 첫 계정 존중
2. 관리자가 등록하는 경우 무시하고 등록

**Comment by ngleader** [comment]
thx.

**Comment by kijin** [comment]
Gmail뿐만 아니라 `+`가 포함된 모든 메일주소는 중복검사시 뒷부분을 무시하는 것이 좋겠습니다. 저는 개인소유 도메인을 FastMail에 연결해서 쓰고 있는데, 이것도 `+` 뒷부분은 임의로 생성해서 쓸 수 있거든요. 많은 오픈소스 메일서버 소프트웨어가 `+` 분류기능을 기본으로 지원하기 때문에, 해외 메일 서비스들은 상당수가 이 기능을 제공하고 있습니다.

점(`.`)을 무시하는 것은 Gmail뿐인 것으로 알고 있습니다.

그런데 아래와 같은 상황이 발생하지 않을까요?

- test+01@gmail.com으로 가입
- 가입 사실을 잊어버리고 test+02@gmail.com으로 다시 가입하려고 하니 중복이라 가입이 안됨
- ID/PW 찾기를 해보려는데 예전에 가입할 때 사용한 `+` 뒷부분이 뭔지 잊어버림
- 가입도 안되고, 예전 ID/PW도 못 찾겠고, 그야말로 난감해짐
- 메일 주소의 점(`.`)을 무시하도록 해둔 경우에도 똑같은 상황이 발생함... 이미 가입되어 있다고 하면서, 정작 ID/PW 찾기를 해보면 가입되지 않은 메일주소라고 나옴

그러면 ID/PW 찾기 할 때도 `+` 뒷부분과 점(`.`)을 무시하도록 해야 할 텐데... 이건 또 자칫하면 개인정보 유출의 위험이 있겠네요.

(한국 웹마스터들이 중복가입 방지에 지나치게 집착하는 건가 ㅠㅠ)

**Comment by misol** [comment]
기능을 넣는다면, +가 들어간 이메일로 가입했다는 사실을 알 수 있게 해야겠지요. 이메일 중복 검사 등으로요...도 마찬가지







On Tue, Mar 24, 2015 at 5:28 PM -0700, "Kijin Sung" <notifications@github.com> wrote:












Gmail뿐만 아니라 +가 포함된 모든 메일주소는 중복검사시 뒷부분을 무시하는 것이 좋겠습니다. 저는 개인소유 도메인을 FastMail에 연결해서 쓰고 있는데, 이것도 + 뒷부분은 임의로 생성해서 쓸 수 있거든요. 많은 오픈소스 메일서버 소프트웨어가 + 분류기능을 기본으로 지원하기 때문에, 해외 메일 서비스들은 상당수가 이 기능을 제공하고 있습니다.



점(.)을 무시하는 것은 Gmail뿐인 것으로 알고 있습니다.



그런데 아래와 같은 상황이 발생하지 않을까요?



test+01@gmail.com으로 가입
가입 사실을 잊어버리고 test+02@gmail.com으로 다시 가입하려고 하니 중복이라 가입이 안됨
ID/PW 찾기를 해보려는데 예전에 가입할 때 사용한 + 뒷부분이 뭔지 잊어버림
가입도 안되고, 예전 ID/PW도 못 찾겠고, 그야말로 난감해짐
메일 주소의 점(.)을 무시하도록 해둔 경우에도 똑같은 상황이 발생함... 이미 가입되어 있다고 하면서, 정작 ID/PW 찾기를 해보면 가입되지 않은 메일주소라고 나옴




그러면 ID/PW 찾기 할 때도 + 뒷부분과 점(.)을 무시하도록 해야 할 텐데... 이건 또 자칫하면 개인정보 유출의 위험이 있겠네요.



(한국 웹마스터들이 중복가입 방지에 지나치게 집착하는 건가 ㅠㅠ)

**Comment by misol** [comment]
1. id host 분리 후에 id 중 + 뒷부분을 제외한 검색 필요 (in?)
2. .이 들어간 지메일 주소일 경우 . 을 제거하여 검색 후 결과 반환.
 - 이때 문제, 이미 .이 들어간 이메일 주소로 가입이 되어 있는 경우는 걸러내지 못함
 - misol.kr@지메일 로 가입된 경우 mis.ol.kr@지메일로 가입시도 하는 경우....

**Comment by misol** [comment]
. 들어간게 정말 어렵겠군요...
어떡해야하지

**Comment by misol** [comment]
이런 경우가 대소문자 구분에서도 있을텐데.. 그건 되어있었던거 같고
