### ISSUE TITLE
CK 에디터로 설정시 백지

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1348]
1.8 BETA3 입니다. CK 에디터 + CK STYLE 로 설정 해봤는데 에디터가 로드되지 않고 백지 입니다. 

어디서 부터 뭘 봐야 할지 감이 안와 남겨 봅니다. 물론 기존 XPRESS EDITOR 는 잘 됩니다.

**Comment by qw5414** [comment]
CK에디터를 많은 유저가 사용하는 실사용 사이트에 사용하기엔 아직 적합하지 않습니다.

댓글 엔터로 인한 버그등등이 해결되지 않아 정식 사용은 힘들것으로 보여져요. 기존 에디터를 좀 더 활용하시고 사용하시길 권장드려요 ^^

**Comment by bnu** [comment]
문제를 확인할 수 있는 URL이 있으면 알려주세요.
스크립트 오류가 발생하는지도 확인 부탁드립니다.

**Comment by mactopia** [comment]
@qw5414  네 알겠습니다.
@bnu 어떻게 확인하는 줄 잘 모르나 브라우저로 점검해보니 ckeditor.js 를 못불러오는것 같네요. 해당 폴더에 ckeditor.js 500kb정도 되는 파일은 잘 있습니다. 

JQMIGRATE: Logging is active
x.js?20150325031423:1 DEPRECATED : xAddEventListener() is deprecated function.
x.js?20150325031423:1 DEPRECATED : xGetElementById() is deprecated function.
http://./common/js/plugins/ckeditor/ckeditor/ckeditor.js?20150325031415 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery.js:583 JQMIGRATE: jQuery.browser is deprecated
jquery.js:583 console.trace()jquery.js:583 migrateWarn
index.php:143 Uncaught ReferenceError: CKEDITOR is not defined
main.js:8 Uncaught TypeError: Cannot read property 'primary' of undefined

**Comment by bnu** [comment]
@mactopia 확인 감사합니다.
경로를 처리하는데 문제가 있는지 확인해보겠습니다.

**Comment by XisoDev** [comment]
아마 jquery를 두번호출하시지 않나 생각됩니다.

기본 xe에서 호출하는 jquery 외에 별도의 jquery를 호출하면 그런문제가 발생합니다.

레이아웃을 생성하시는 과정에서 jquery를 별도로 호출하진않는지 확인해보세용.
