### ISSUE TITLE
컴포넌트 아이콘

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1350]
https://www.xpressengine.com/tip/22383311

컴포넌트 아이콘이 기본 코어에서는 안불러와집니다. 불러와졌으면 좋겠습니다. xe 기본에디터가 
많이 이뻐지기도 하구요.

**Comment by YJSoft** [comment]
89fa0e9ecf96c0f3c720b9d67ab4885caa11b4c8
이미 아이콘으로 출력되게 변경되었습니다.

**Comment by bnu** [comment]
다음과 같은 형태로 툴바가 표시되고 확장컴포넌트 또한 툴바에 버튼으로 표시됩니다.
노란색 스마일 아이콘이 포함된 묶음이 확장컴포넌트 부분입니다.
![2015-03-25 4 48 20](https://cloud.githubusercontent.com/assets/53764/6820082/c6514512-d30e-11e4-826d-75b44723eed7.png)

**Comment by mactopia** [comment]
ck 말고요 xpress 에디터에서도요.

**Comment by bnu** [comment]
@mactopia XpressEditor에는 적용할 계획이 없습니다.

**Comment by mactopia** [comment]
^^. 냉정하셔라~ 코어 안에 포함되어 있는 파일을 
img src 하나 넣어주면 되는데 뭔가 이해하기 힘든 구석이 있네요.

**Comment by bnu** [comment]
@mactopia 이슈는 다시 열어두도록 하겠습니다.
