### ISSUE TITLE
스팸글이 올라온 이후 게시물이 안보입니다

### ISSUE THREAD

**Issue by bncplan** [xpressengine/xe-core#1351]
수고많습니다

버전 : version: 1.7.12 
증상 : 
          첫째 : 지난 3월 17일 스팸글이 올라온 이후 
          게시물이 안보입니다 (첨부화일 참고)
         그날이후 실제 게시물은 많습니다
         http://www.bncplan.co.kr/index.php?mid=com_b_01
      
        둘째 : 스팸글이 올라온 시간 으로부터 이전 약 10일 동안의 게시물은
       게시판 목록에 댓글숫자는 보이지만, 들어가 보면 댓글은 없습니다

![01](https://cloud.githubusercontent.com/assets/11656851/6838682/bbf69a3a-d3a0-11e4-8ec8-2b7a1ee576d9.png)

**Comment by bncplan** [comment]
[추가 설명]
즉,  관리자 > 콘텐츠 > 문서에 게시글이 노출 안됩니다
![01](https://cloud.githubusercontent.com/assets/11656851/6976881/0e544f74-d9ec-11e4-8acd-14dc4e92a011.png)
![02](https://cloud.githubusercontent.com/assets/11656851/6976882/0e596842-d9ec-11e4-975f-70e2d5264ab8.png)
![03](https://cloud.githubusercontent.com/assets/11656851/6976883/0e60e9d2-d9ec-11e4-8a4f-d81772c2ef75.png)

**Comment by bnu** [comment]
DB에서 `xe_sequence` 테이블에 `seq`컬럼 값을 4300000을 추가해보세요.
`INSERT INTO `xe_sequence` (`seq`) VALUES (4300000);`
어떤 이유에서 `xe_sequence` 테이블에 이상 또는 변조가 있었을 것으로 보입니다.

**Comment by bncplan** [comment]
www > files > config > db.config
화일 말씀인가요? 

이런내용인데 어떻게 하라는 말씀인지 잘 모르겠습니다.
![01](https://cloud.githubusercontent.com/assets/11656851/6993007/4a3561f0-db21-11e4-81d7-6be68691d68b.png)

**Comment by ForPeople** [comment]
디비 아이디 비번 노출 ㅡㅡ;;

**Comment by YJSoft** [comment]
@bncplan db.config.php 파일은 설정 파일입니다.
phpmyadmin 등으로 DB에 직접 접근하셔서, SQL 탭에 위 SQL문을 입력(만일 DB 접두어가 xe_ 가 아니면 xe_를 바꾸어 주셔야 합니다)해서 실행하세요.

**Comment by bncplan** [comment]
[답변] 감사합니다.
프로그램족에 전혀 문외한이라 추가 질문 드립니다

phpMyAdmin에 접근해보니
아래첨부와 같습니다
어디로 들어가서 어떤 수정을 해 보아야 할지 설명좀 부탁드립니다
![01](https://cloud.githubusercontent.com/assets/11656851/7099957/29a467fe-e041-11e4-92d0-92c432a203de.png)
![02](https://cloud.githubusercontent.com/assets/11656851/7099958/29a4ab2e-e041-11e4-9fd3-a17c6220db2a.png)
