### ISSUE TITLE
xe ver 1.7.12 xe_autoinstall_packages table entry has 2075 records

### ISSUE THREAD

**Issue by klee4413** [xpressengine/xe-core#1355]
ver 1712
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 32 bytes) in /home/uagala/public_html/main/classes/xml/XmlParser.class.php on line 231

Found xe_autoinstall_packages table entry has 2075 records. deleted 2000 records and this error is fixed. Thank you all.

**Comment by YJSoft** [comment]
@bnu 쉬운설치 XML 파싱 실패로 인한 오류. 서버에서 가져올 때 분할해서 가져오도록 수정이 필요해 보입니다.
https://code.google.com/p/xe-core/issues/detail?id=3220
