### ISSUE TITLE
대댓글에 대한 비밀글 권한 수준 변경 요청

### ISSUE THREAD

**Issue by socialskyo** [xpressengine/xe-core#1365]
이슈가 아닌데 이슈로 올리는 것같아 죄송합니다.

요지는 대댓글간의 비밀글인 경우 게시자 역시 볼수 있다는 것에 대한 문제 입니다.
중책안으로서

"대댓글을 쓸때 노출 허용할 아이디를 선택할 수 있게 하는게 좋을것 같습니다.
어짜피 비밀 대댓글에 대한 이슈는 원글주인과 대댓글 달고 있는 해당 댓글주인 딱 2명뿐이기 때문에
비밀글 체크할 때 해당 2명에 대해서 노출여부를 선택하게 하는것이 직관적이고 좋을것 같다는 생각입니다"

현재로서는 항의가 들어 오고 있습니다.

**Comment by haegyung** [comment]
흠... 이 부분은 글쎄요. 적어도 이 기능이 제공된다는 가정아래에서
댓글 작성자가 공개 권한을 가지는것은 정보의 공개와 소유권 상에서 불합리하다고 봅니다.
즉, 게시글 작성자가 공개 권한을 가져야 합니다. 올려주신 토론 글에 의견은 남겨 놓았습니다.

**Comment by mactopia** [comment]
@haegyung 게시자는 화두를 던지는 것이고 댓글이 아닌 대댓글은 새로운 화두에 대한 내용입니다.
즉 댓글은 파생된 새로운 글 원 댓글자에게 권한 및 소유권이 있지 않나 싶습니다. 

지금 이 댓글도 원글을 제가 작성한게 아니라고 가정하면 haegyun님에게 이야기하는 것이라 판단합니다.
즉 댓글을 작성하는 유저 관점에서 보면 충분히 불만이 들어올수 있는 상황을 야기하고 있다고 생각합니다.

**Comment by qw5414** [comment]
댓글을 적을려니깐 바로 댓글허용을 막으셧더라구요? 왜인지 모르겟으나.. 여기에서나마 의견을 내자면, 게시글 주인이 댓글을 컨트롤을 하는 과정까지 있는 상황에서, 구지 A가 적은 글을 비밀글을 못보게 할 이유가 있습니까?

그렇게 바뀌면 또 A가 의견낼꺼같은데요?..

결론적으로 제어권한까지 잇는 상황에서 비밀댓글을 못보게 할이유는 없어 보입니다.

큰 토론장에서, A는 주제를 말해줬고 그 주제에 대해서 B와 C가 의견을 냈으니, 그 의견을 들을 권한이 A에게도 존재해야한다는거죠. 실제적으로 댓글을 통해서 개인정보 교환한다는건, 관리자와 유저의 글관계에서만 성립시켜야 하는거고요.

**Comment by mactopia** [comment]
qw5414 님. 무슨 말씀 하고 싶어하는 줄 알겠는데 잘 보세요..
B와 C 가 (A 에게) 의견을 낸게 아니라 B 가 C 에게 이야기 것 입니다. A가 제시한 토론장이든 어디든
B 는 C 에게 비밀스럽게 귓솟말로 이야기를 하고 있다고요. 이러한 관점으로 보았을때 어떻냐는 겁니다. 

즉, B 가 C 에게 이야기를 할때 비밀글 이라는 버튼을 눌러 체크를 했어요.  말 그대로 XE가 제공하는 비밀글 체크를 했다고요. 근데 A가 볼수 있단 말이에요. A 에게 이야기 한것도 아닌데. 

그래서 저런 주제의 글을 적은 것은 지금것이 문제라기 보다 어떻게 유저 불만에 대응을 해야 하나, 아이디어가 있는지
사람들은 어떻게 생각하는지 코어의 도움을 받아야 하는지 등등 알고 싶어 적은겁니다.

B가 C 에게 이야기 할때 A에게 보입니다. 주의하세요. 이런 ALERT 이라던지, 아니면 정말 대댓글 작성할때는 A 에게 안보여야 한다던지.. 뭐 이런 USER 입장에서 한번이라도 돌려 보자 라는 겁니다. 

그리고 게시글 주인이 댓글 허용 여부 컨트롤 이야기가 여기서 왜 나옵니까? 
댓글과 대댓글사이에 비밀글이 이미 이루어진 다음 이후 시점의 이야기를 하는 겁니다.

마지막으로 큰 토론장에서 A 가 주제를 말해줬다고 하는데 왜 매번 토론장이어야 합니까? 
만약 B와 C 가 A가 초청한 놀이터에 놀러간거라면요? 거기서 같이 이야기를 하다가 B와 C 가 귓속말로 이야기를 나눈거라면요? 

이렇게 따지면 한도 끝도 없겠죠. 그래서 글을 닫은겁니다. 아래와 같이 적고요. 
여기서 이렇게 이야기 하면 되니까요. 
--
충본히 토론 하고, 공개 여부에 따른 장단점은 각각 존재 하는 것을 확인 하였으니 댓글은 이만 적을수 있도록 하겠습니다. 
-

**Comment by qw5414** [comment]
@mactopia 애초에 귀속말이라는 것은 비밀댓글을 통해서 하는 용도가 아닙니다. 사용에 오해가 있으신 것 같네요. XE는 전체 사이트를 기준으로 배포를 하는 CMS이라는 것을 생각해보세요. 단지, 님의 논점도 어느정도 맞다는 생각이 있지만, 다른 사이트들의 경우를 생각해볼 문제인거죠.

각각 사이트가 다 정책이 다르고, 님이 말씀하신 정책도 대체적으로 사용할 수 있는 커뮤니케이션 모듈이 있잖습니까.. 그걸 사용을 해서 쪽지를 주고 받고 의견을 내도 되는 상황인데 굳이 XE팀이 그것을 위해 지원을 해줄 필요가 있냐는 생각부터 드네요. 비밀스럽게 이야기한 공간을 회원이 "잘못"인지 하고 사용하고 있으면 그 사용에 대해서 정확하게 잡아주고, "대체방안"을 사용할 수 있도록 유도하는것이 사이트의 의무이죠. 아니면 모듈을 직접 수정하거나.. 의뢰를 통해서 하는게 맞다고 봅니다..


XE의 의견을 통합적으로 묻고 답하는과정에서 다소 해당 포럼글의 논란여지와, 기타등등을 따져보았을때, 결론은 자기 주장이 옳타는 싸움을 할 뿐이지, 전혀 개발에 도움이 되는 토론이나 그런것이 되고 있지 않아 보여서 씁쓸한 상황이라 답답합니다. 

그리고 님이 말씀해주신 답변에 또 다시 답변 해드리자면요.. 

제가 예시를 통해서 A의 토론장이라는 의견을 내드렸습니다, 하지만 결론적으로 보면요, Comment모듈의 속성을 이해하셔야 하는것이 중요하지 않나 생각됩니다. B는 A에게 답변하기 위한 답변을 달았고 C는 A가 타겟이 아닌 B에게 답변을 달고 싶엇는데 비밀로 이야기를 하고 싶어서 답변을 하는 것입니다. 문제는 이것이 실제가 아닌 사이트의 기준이 되면, 다르다고 생각합니다 A는 토론을 할 수 있는 글을 제공했으며, B는 A에게 답변을 했을꺼고요.. C는 B에게 답변을 하겠지만 결론적으로 A가 적은 글의 댓글을 적은거기 때문에 A글과 관련된 댓글을 남기기 마련이라는 것입니다. 그런데 그게 관련이 없는 글이 올라온다는건 해당 C의 회원의 잘못이 되기도 하겠지요. 연관성없이 포인트 얻기위한 목적으로 봐질수도 있는거고요.. 그건 뭐 사이트의 운영이 어떻게 되느냐가 따라다르겠지만.. 결론적으로 전체적으로 많은 사이트에 배포되는 과정에서 최적의 방법으로는 A글은 그 글에 대해서는 수정, 댓글, 읽기 권한이 정확하게 받는것이 좋다고 생각됩니다.

비밀의 이야기를 하기 위해서는 댓글보다는 쪽지모듈을 사용하기를 유도하시는 편이 더 옳은 방향성이라고 저는 일딴 생각하고 있습니다. :)

**Comment by bnu** [comment]
관련 코드
https://github.com/xpressengine/xe-core/blob/master/modules/comment/comment.item.php#L164-170

(싸우지 마세요…)

**Comment by ForPeople** [comment]
저는 이 토론을 보면서 느끼는게 개발자 입장에서 사용자 편의성에 대해서 어떻게 그렇게 간단히 무시하는 발언을 하시는지 깜짝 놀랐습니다.
UI 라던가 UX 라던가 하는건 유저 인터페이스, 유저 익스피리언스의 약자입니다.
다시말해서 우리 개발자들이 추구하는건 사용자 경험에서 유래한다고 해도 과언이 아닌데,
지금 사용자 관점에서 시스템이 오해할 만한 내용들이 있다고 하시는 것에 대해서 그건 틀렸다 라고 하시는 자신감은
개발자 입장에서 이해하기 힘드네요...

**Comment by bnu** [comment]
설정을 어디에 두어야 적당할지와 기본 설정을 어떤 것으로 두는 것이 좋을까요?

**Comment by qw5414** [comment]
@bnu 저는 기본 코어의 기능을 유지시킨다음.. 게시판의 module_info-> 을통한 수정을 할 수있도록 만드는게 좋다고 생각되요..

**Comment by mactopia** [comment]
귀솟말은 비유의 표현입니다...@.@. 소위 웹서비스에서의 귓속말을 말하는게 아니고요.. 

아무튼 오해는 마셔야 할 것이 애초 부터 xe 팀의 지원을 바라고 적은 글이 아닙니다. 
정확히 글을 적은 의도를 적어보자면 "XE 팀이 동의를 하면" 개선을 해야 하는 것이 아닌가 ? 입니다. 

제가 GITHUB 에 올린게 XE팀아 해줘라! 라고 어디에도 적혀 있지 않다고 생각합니다. 제가 포럼에 적은 글과 
본문 그리고 댓글 다시 봐주세요. 

그리고 저는 유저들이 "잘못" 인지 하고 있다고 생각 하지 않습니다. 
분명히 XE 코어의 기본은 분명 "비밀글" 로 되어 있습니다.  
B가 C 에게 비밀글 로 이야기를 할때 "비밀" 이라는 일반 단어가 주는 상식은 "너와 나만 아는" 그런 것 입니다.

하여  불친절하면 불친절 한거지 유저가 처음 부터 "잘못" 인지한게 있는게 아닙니다. 
벌어지고 나서 유저에게 교육을 시키는건 다른 문제입니다.(물론 방법론적으로 동의합니다.) 

그래서 저는 그 "비밀글" 기능과 문구가  Mis-leading 하고 있다고 말하고 싶네요. 
아니면 정확한 표현 법이고 완벽한 기능이라고 단정 지을지언정 최종  첫 바퀴는 우리가 의도한대로 안굴러 갈수도 있다는 전제가 있는거겠죠. 

일단 XE를 사랑하는 사람으로써 내가 가진 정말 좋은 시스템에 대한 교육과 자부심은 잠깐만 내려 놓고요...

 차라리 저와 저의 의견에 동의하시는 분들에게 

그럼 " "비밀" 말고 "3자 대화" 이렇게 LANG.XML 에서 바꾸시면 되겠네요. 라고 만 해도 

저는 XE 개발진들의 의도에 수긍을 하겠습니다. 허나 유저 "잘못" 운영자 유도 부족이다..는 좀..그래요...

**Comment by mactopia** [comment]
@BNU 님 저는 개발자가 아니라 잘은 모르지만...게시판 모듈의 아래 부분에 들어가야 하지 않나 싶습니다. (근데 제가 코드를 볼줄 몰라 이 이야기 하고 있는거 맞는지요??)

![2015-04-02 9 52 15](https://cloud.githubusercontent.com/assets/6075830/6964275/9257be06-d982-11e4-8e72-950cde71144a.png)

**Comment by ForPeople** [comment]
@bnu 
게시판이나 코멘트 설정으로 해주는게 아니구요.
어떤 대댓글은 글쓴이에게 노출하고 싶은것이고 어떤 대댓글은 노출하고 싶지 않은거에요.
그래서 설정의 주체가 대댓글 쓰는 사람이 되어야 됩니다.
따라서 지금 대댓글 권한을 설정하는건 의미가 없다고 생각됩니다.

**Comment by qw5414** [comment]
@ForPeople 그렇게 되면 스킨단위에서 수정을 해야하는 부분이 늘어나지 않을까요?

일반 개발자의 입장에서는 모르겠지만 개발하지 않고 스킨개발자에게 의존하는 사용자의 경우 스킨수정이 들어갈 경우 사용에 무리가 잇지 않을까 생각됩니다.

게시판 스킨갯수마다 적용해야하고 각 게시판스킨에 따라 다 다르니깐요..ㅎ

**Comment by ForPeople** [comment]
@qw5414 
제 생각이지만 스킨이 문제가 아니구요 지금 코멘트 모듈에는 댓글 개별적인 권한설정이 좀 힘들지 않을까 싶습니다.
디비를 좀 확장시켜서 모듈도 수정이 필요한 작업이지 않을까 생각됩니다.
차라리 서드파티 모듈로 지원해서 트리거 처리를 싹 다 해주는 방향으로 하는게 더 나을수도 있다는 생각이 들기도 합니다.
어쨌거나 노력이 많이 드는 방법이 될것 같습니다.
좀 쉬운 방법을 찾아보는게 나을것 같습니다.

**Comment by qw5414** [comment]
@mactopia 저도 XE팀에게 바라고 말씀하신 의견이 아니라는 것을 당연히 잘알고 있습니다. 제가 말씀드렸던 부분은, 정식적으로 적용이 되는 부분에서 그 많은 다양한 정책을 운영하는 사이트들의 경우 어떻게 변할지모르겠다는 생각을 말씀드리고 싶어서에요 ㅠㅠ.. 오해 없으시길 바래요 ~ㅎㅎ

**Comment by qw5414** [comment]
@ForPeople 음 제생각에는 필요한 사람들이 잇으면 간단하게 Before트리거에서 정보 수정을 할 수 잇는 트리거 권한만 주고, 그 부분을 서드파티 모듈에서 해결하도록 하는것이 좋을 것 같은 생각도 들기도 합니다.ㅎㅎ 어떻게 되었던 좋은 방향이 되면 좋죠! ㅎㅎ

**Comment by ForPeople** [comment]
생각해 보니 애드온으로 가능할것 같습니다 ㅡ.ㅡ;

**Comment by qw5414** [comment]
@ForPeople :+1:

**Comment by mactopia** [comment]
아..개발자 분들끼리 이야기하는데 죄송한데요...그럼 꼭 개별 설정 말고...게시자는 안보이게 고정 하는 그런 것은 없을까요? (개발 입장에서는 그게 그건가요?...)
아무튼 이런 의견도 있다는 점에서 들어주셔서 bnu님/qw5414님/for people님 모두 고맙습니다.

**Comment by qw5414** [comment]
@mactopia 가능해요. 개별설정의 경우는 오히려 더 혼란성을 가중될거같고.. 각 mid별 설정기능을 사용해서 그 게시판에는 해당기능을 이렇게 사용하겠다 하는 방식으로 사용하는것이 좋을 것같아요

**Comment by ForPeople** [comment]
@mactopia 
고정적으로 안보이게 처리하는건 애드온으로 처리할 수 있을것 같습니다.
만약 대댓글 유저가 체크 설정해서 하게 하려면 간단한 모듈 + 애드온이 될것 같습니다.

**Comment by mactopia** [comment]
아..그렇군요. 코어나 게시판 모듈에서 안되면 제작 의뢰를 해야겠군요. ^^. 늘 그렇듯 이제 bnu 님 포함 xe팀의 판단을 기달려야죠..뭐^^; 

두분 모두 속시원한 답변 감사 드립니다.

**Comment by bnu** [comment]
@ForPeople 댓글 작성자가 공개 범위(글 작성자에게 보여줄 것인가)를 지정하는 것은 개발 비용이 대폭 커질 것 같습니다. `commentItem:: isAccessible()`을 이용하지 않고 `$oComment->get('is_secret')`를 이용하는 코드나 댓글을 가져오는 query 등 처리해야 할 부분이 많아질 것 같네요.

**Comment by qw5414** [comment]
@bnu @ForPeople 제가 한 사이트를 대상으로 비밀글이 아닌 닉네임 변경 관련 쪽으로 모듈을 의뢰받고 제작한적 잇엇는데 그때도 비슷한원리엿을 겁니다. (지금은 그것은 다른 모듈으로 대처했지만요)

**Comment by haegyung** [comment]
@mactopia 그러니까 게시자가 공개한 글이니 끝까지 게시자에겐 접속 권한이 있어야 한다는 말씀을 드린겁니다...
정보의 컨텐츠 내용이 어떻건간에, 저는 "정보" 와 "권한"이라는 것으로 말씀드린겁니다.
@ForPeople 죄송하지만, 말씀하신 것 처럼 개발자가 사용자의 UI / UX 를 고려 하지 않으신다는 말씀은 과한 말씀입니다. UI / UX 를 고려하지 않는 개발자가 있을리 없어요.

**Comment by ForPeople** [comment]
@haegyung 
네... 맞습니다.
그래서 지금 당연히 원글 게시자가 비밀 대댓글에 대한 권한을 갖고 있다고 생각했었는데
댓글에 비밀 대댓글을 달았을때 원글 게시자에게 권한이 없다고 주장하는 UX 사례가 나와서 이를 무시하면 안된다고 애둘러 표현한 것입니다.

**Comment by kijin** [comment]
각자가 당연하다고 생각하는 것에도 너무 큰 차이가 있군요.

제 생각에는 A의 글에서 B가 C에게 비밀댓글을 작성한다면 그건 A와 C 모두에게 보내는 메시지라고 보입니다만... B의 입장에서는 A는 생각하지 못할 수도 있겠네요. 그래서 UX가 어렵습니다 ㅠㅠ 사람마다 다르게 해석하거든요.

상세설정 가능 여부를 떠나서 사용자의 혼란을 최소화하는 것이 가장 중요한 목적이라면, 안내 문구를 수정하는 것이 가장 간단한 방법이겠네요. 예를 들어 비밀글 체크박스를 클릭하는 순간 화면에 모달창 하나를 띄워서,

> 비밀글을 선택하시면 다음의 사용자들에게만 노출됩니다.  
> 관리자 및 (비밀글을 볼 권한이 있는 사용자들 닉네임)
> 이것을 원하지 않으신다면 개별적으로 쪽지를 이용해 주십시오.

**[사족]** 만약 제가 관리자의 입장이라면 이렇게 생각해 볼 수도 있겠습니다. "남의 글 밑에서 자기들끼리 비밀댓글을 주고받다니 예의가 없지 않나!!!" 만약 이런 입장이라면 비밀댓글 기능 자체를 없애버릴 수도 있겠죠. 그러나 이미 기능을 만들어버렸으니 이건 물건너갔고... ㅋ

**Comment by mactopia** [comment]
@haegyung 네. 의도는 알겠으나.. 접속권한 권리라는게....이해가 어렵네요. 접속? 권한에 대한 권리?
일단 게시자(A) 가 다 볼수 있는 권한이 있어야 한다는 말씀 같은데..동의 합니다. 그런데 불만은 B와 C 에서 나는 비율이 높습니다. 이 부분도 왜 그런지에 대해 이해를 하고 보자는 겁니다. 

게시자에게 댓글에 대한 모든 권한이 있다면 댓글 존재시 게시물 삭제 금지 라는 옵션에 대한 기존의 열망을 생각 해보시면 유저 입장이 조금 생각이 되실까요? 

아무튼 예를 들어 
저와 haegyung님이 지금 이렇게 @으로 지칭하며 
대화를 하는 상황에서 제가 만약 "이제 그만 게시자 A와 싸우지 맙시다" 라고  haegyung님에게 적고 싶을때  더이상 대댓글 비밀로 남기지를 못하게 됩니다. 

네. 쪽찌라는것도 있지요. 그런데 B와 이야기를 그대로 그 자리에서 
이어가지 못하고 단절된 느낌을 주는 확실하지요. 그리고 기능적으로 비밀이라는 기능이 있음에도..

유저들이 사용하지 못하는 상황이 연출 될수 있으므로 대댓글 기능이 졸지에 서자가 되어 버리는 상황이 연출 되는 겁니다. 

특히나 조금은 민감한 이야기를 나눌수 밖에 없는 비밀글 기능이니 
사용 못하는 비중이 계속 늘어날것이고,  저는 이미 컴플레인을 받아서 이렇게 github에서 조언을 구하는 겁니다. 


ps. 이제 계속해서 챗바퀴를 도는 말을 하는 것 같으니 더이상 관련하여 글은 적지 않겠습니다.^^ (기분나뻐서가 아닙니다.^^)  이후는 xe 코어 개발자 분들의 판단을 따르겠습니다.

@kijin 아이디어 좋으시네요. 만약 대댓글 "비밀" 댓글 기능이 권한 제어 수준에서 해결이 되기 전까지충분히 실 사용 사이트에도 적용할수 있겠습니다. 감사합니다.

**Comment by haegyung** [comment]
@mactopia 저 위에서, 접속 권한이라는게... "정보를 조회할 수 있는 권리"를 뜻합니다. 그리고 저는 대댓글 사용자가 본문 게시자에게 보이지 않도록 설정하도록 하는 것이 부당하다고 말하고 있는 것입니다.
말씀하신것처럼 민감한 이야기들이 포함되니까, 게시물을 쓴 작성자 본인이 그것에 대한 조회 권한(또는 자기가 조회하지 않고자 선택할 수 있는 권한)이 부여 되어야 합니다. 즉, 대댓글을 공개할 범위는 본문 게시자가 선택해야 합니다. (이 기능이 제공된다는 가장 아래에서)
- B나 C의 모든 입장을 반영해야 하는 것이 아닙니다. 그것이 타당한 의견인지 부터 검토를 하고 반영해야 하는데, 저는 그 B나 C의 입장이 타당하지 못하다는 것이죠.

**Comment by mactopia** [comment]
haegyung 님이 작성한 게시물의 의문스러운 구석이 싫다는 부분은 인정 할수 밖에 없습니다. 그런데 그거와 같은 개념으로 B와C도 같은 감정을 느낄수 있습니다. 똑같이 강요하면 안됩니다.

**Comment by bnu** [comment]
입장차에 대한 이야기가 반복되는 것 같아서 남깁니다.
글 작성자가 비밀 댓글을 볼 수 있어야 하느냐의 문제는:

1. 게시글에 관계된 댓글들이니 볼 수 있어야 타당하다
1. 사용자 입장에서는 직계 부모인 상위 댓글 작성자에게만 보이는 것으로 인식한다

두가지 의견에 대해 모두 동의하며 아래 나열한 방법 중 하나로 해결될 수 있도록 개선이 필요하다고 인식하고 있습니다.

이를 위한 해결 방법으로는 위에서 @kijin 님 등이 주신 의견을 종합하면:

1. 사용자가 인지할 수 있도록 안내문을 표시 : 상위 댓글 작성자와 글 게시자에게도 보인다
1. 3rd-party 모듈/애드온으로 해결
1. XE에서 게시판 설정에서 옵션 제공
1. 사용자가 선택할 수 있게 한다

안내문을 표시하는 것이 XE Core에서 처리하는 비용이 가장 적으며, 사용자가 선택할 수 있도록 하는 것은 많은 처리와 호환성 문제가 발생할 수 있습니다. 3rd-party 모듈/애드온으로 처리하기 위해 개선이 필요한 사항이 있는지, XE Core에서 옵션을 제공한다면 어떤 페이지에서 옵션을 제공해야 할지와 기본 값을 어떻게 두어야 할지에 대해 논의 해주시면 감사하겠습니다.

**Comment by kijin** [comment]
@bnu 댓글 클래스의 외부적인 인터페이스는 그대로 두고, `isAccessible()` 메소드 및 거기서 호출하는 `isGranted()`, `isSecret()` 등의 다른 메소드들을 수정하는 방식으로도 가능하지 않을까요?

예를 들어 `is_secret` 컬럼이 지금은 `Y` 아니면 `N` 두 가지 값밖에 들어가지 않지만, 대댓글 작성자와 부모댓글 작성자만 읽을 수 있는 `Z`라는 값을 추가한다고 가정해 봅시다.

일단 `isSecret()` 메소드에서 `is_secret` 컬럼이 `Y`인지 체크하는 것이 아니라 `N`이 아닌지 체크하는 방식으로 바꾸면 기존 방식과의 호환성은 유지할 수 있겠죠.

한편, `isAccessible()` 메소드에서는 `isSecret()`만 확인하는 것이 아니라 `is_secret` 컬럼값이 `Z`인지 다시 한 번 체크하고, 만약 `Z`인 경우에는 관리자와 부모댓글 작성자만 허용해 줍니다. (관련 로직을 별도의 메소드로 빼는 것도 괜찮겠습니다.)

문서 모듈과 달리 댓글은 확장변수도 사용할 수 없고 상태 표시 컬럼도 1글자밖에 되지 않아서 조회 권한을 가진 회원들의 `member_srl`을 직접 나열하거나 좀더 세부적으로 설정하는 것은 어렵겠지만, 부모댓글 글쓴이만 구분하면 된다면 이런 방법으로도 가능하지 않을까 합니다.

만약 위와 같은 기능을 활성화시킬 수 있는 옵션을 추가한다면 기본값은 비활성화 상태로 두는 것이 좋겠습니다. XE를 업데이트했더니 게시판에 이상한 옵션이 생겼어요! ← 이런 상황을 막기 위해...

UX 문제는 게시판 모듈을 확장하거나 스킨을 개발하는 것으로도 상당부분 커버가 가능하지만, `isAccessible()` 같은 부분은 코어의 댓글 모듈에서 직접 지원해 주어야 할 것으로 보입니다. 기본적인 권한 처리를 모듈마다 각각 엉뚱한 방식으로 하게 된다면 나중에 오히려 혼란스러워질 수도 있어요.

**Comment by bnu** [comment]
@kijin 네 `is_secret `컬럼에 타입을 하나 더 사용하고 `commentItem:: isAccessible()`을 개선하면 간단히 해결할 수 있습니다. 다만, 확장 기능들에서 직접 query를 사용할 때 `Z`를 비밀 댓글로 처리하지 못할 가능성이 있습니다. `is_secret != 'N'`이면 다행이지만 `is_secret != 'Y'`이 대부분일테니까요.

**Comment by fromthere** [comment]
@kijin 아니면 논의가 된 김에 댓글도 확장변수를 사용할수 있게 하는건 어떨까요? 추후 다른 서드파티 프로그램에서 이외에 다른 값(읽을 수 있는 회원 지정, 자동 삭제를 위한 기간 지정 등) 을 넣을수 있게 되니까요.

**Comment by kijin** [comment]
@bnu 네, 그런 문제가 있겠네요. 멀쩡한 공식 메소드를 두고 다른 방식으로 코딩하다니 에러나도 싸다!!! ... 라고 할 수 있으면 좋겠지만 현실은 시궁창.

`CommentItem` 클래스 생성자에서 `is_secret == `Z`인 경우 별도의 플래그를 설정한 후 `Y`로 되돌려버린다면 당장 호환성 문제는 해결되겠지만, 이런 꼼수를 쓰면 아무래도 기분이 더럽죠.

댓글 테이블에 필드를 추가하는 것도 무리일 테니 (큰 사이트는 `ALTER TABLE` 도중에 타임아웃 걸려버릴 듯) @fromthere 님 제안처럼 차라리 댓글 확장변수 테이블을 만들어 쓰는 것이 제일 깔끔하지 않을까 합니다. 관련 코드는 대부분 문서 모듈에서 복사해서 쓰시면 될 테고요.

겉으로 보기엔 아주 간단한 기능일 것 같은데 실제로 개발을 생각해 보면 장난이 아니죠? 위에서 개발자들이 사용자의 편의에 너무 둔감하다고 하신 분의 심정도 이해가 되네요 ㅎㅎ

**Comment by bnu** [comment]
일이 커졌네요! :scream:

**Comment by wookho** [comment]
게시글 주인의 글에대한 코멘트에 새로운 비밀댓글이 달렸다고 비밀댓글을 게시글 주인이 보지 못하게 된다는 것을 원치 않는 사이트는 기존대로 유지가 가능한가요 ?

게시글에 댓글이 달린 상황까지는 분명 게시글에 대한 의견이고 거기에 새로운 비밀스러운 댓글이 달렸는데 정작 글을 작성한 사람이 그 비밀스러운 댓글을 못본다면 글 주인은 그 글을 삭제 하는 게 낫겠지요.

지금 논의되고 있는 내용들이 지금까지 있어왔던 룰을 이어갈 수 있는지 궁금합니다.

**Comment by wookho** [comment]
케이스 하나만 들어 보겠습니다.

게시글 작성자 A
게시글 내용 : 난 XE가 좋아요.

댓글 작성자 B
댓글 내용 : 저도 XE가 좋아요.


비밀 대댓글 작성자 C
대댓글 내용 : 무슨소리에요. WP가 지금 얼마나 좋은데요. WP로 넘어 오세요.

비밀 대대댓글 작성자 B
대대댓글 내용 : 그래요 ? 그럼 XE가 많이 지금 딸리는 군요....

B가 다시 댓글로 작성
새롭게 작성된 댓글 내용 : 생각해보니 저는 XE가 별로 인거 같네요.


글 작성자는 비밀대댓글로 파생된 비밀이야기를 전혀 알지 못합니다. 하지만 대댓글의 내용이 정말 둘만 알아야 하는 비밀이어서 그런건지 어떤 건지 전혀 작성자의 의도는 파악할 수 없습니다. 

처음 시작된 비밀대댓글이 댓글에서 파생이 되었는데 전혀 관련 없는 이야기가 될 수 있을까요 ?  만약 게시글 주인이 절대 봐서는 안되는 게시글과 관련이 없는 이야기라면 더욱이 게시글에 종속된 댓글에서 다뤄지면 안된다는게 제 생각입니다.

이렇게 회원들에게 의문스러운 점을 만들수 있는 시스템으로 개편을 한다면 오히려 더 반목이 생기고 민원이 생기는게 아닌가 합니다.

**Comment by kijin** [comment]
@wookho 저도 그런 기능이 필요한 경우를 당장 상상하기는 힘들지만, 세상에는 온갖 다양한 종류의 인터넷 커뮤니티들이 있으니 뭐 누군가는 필요한가보다~ 라고 생각합니다. 필요한 사람은 해당 기능을 활성화시켜서 쓰고, 필요하지 않은 사람은 기본값 그대로 쓰면 그만이잖아요. XE의 확장성을 고려하면 문서 모듈과 댓글 모듈을 꼭 우리가 잘 아는 게시판이라는 구조로 조합하여 사용한다는 법도 없고요. 모듈을 어떻게 설계하고 스킨을 어떻게 디자인하느냐에 따라서는 `Comment` 모듈이 꼭 댓글의 형태를 띤다는 법조차 없습니다. 단지 정보를 분류하는 단위일 뿐이죠. (실제로 해외에서 많이 쓰는 포럼 형태의 공간에서는 문서와 댓글의 구분이 없는 경우가 많습니다.)

@bnu 일을 키워서 죄송합니다 ㅋㅋㅋ

생각해 보니 확장변수를 사용해서 `accessible_member_srl_list` 이런 식으로 배열을 만들어 넣고, 댓글 작성 시점에서 부모댓글의 글쓴이 정보을 저장해 준다면오히려 제가 처음 제안했던 `Z` 방식보다 서버 자원이 절약될 것 같습니다. 댓글을 화면에 뿌려줄 때는 부모댓글을 일일이 찾아서 글쓴이를 비교할 필요 없이 그냥 세션의 `member_srl`과 비교하기만 하면 되니까요.

또한 사실상 ACL을 구현하는 것이 되니까, 각 모듈에서 필요에 따라 아주 유연하게 권한관리를 할 수 있는 길도 열립니다. 예를 들어 여러 사람이 공동으로 작업하는 공간을 만든다면 글이나 댓글을 작성한 사람이 특정한 다른 회원에게 열람 또는 수정 권한을 부여할 수도 있겠죠. (열람 권한과 수정 권한을 별도의 ACL로 관리한다는 가정 하에서...)

누가 누구에게 무엇을 비밀로 할 권리가 있느냐? 라는 질문은 각 사이트와 모듈의 특성에 맞게 알아서 결정하면 될 일입니다. 그러나 그런 기능을 구현하는 데 반드시 필요한 인프라를 코어에서 제공하지 않을 이유는 없어 보입니다.

단, 그런 기능이 꼭 공식 `board` 모듈에 들어가야 하느냐는 별개의 문제이고, 원한다면 누군든지 모듈을 확장하거나 애드온을 통해 구현할 수 있습니다.

**Comment by wookho** [comment]
@kijin 네. 부디 기존에 작동했던 부분들에서 문제가 없길 기대합니다. 기본코어 동작 외에 서드파티에서 비밀글 처리하는 부분에 영향을 주지 않았으면 하는 기대를 하구요. 물론 지금 논의하시는 코드공여자 분들이 알아서 잘 해주시라 믿고 있습니다.

**Comment by anizen** [comment]
댓글이 달리면 삭제할 수 없도록 설정을 지원하는 것으로 글 게시자에게 댓글 권한은 없다라고 하셨는데, 

반대로 글쓴이가 댓글을 못달도록 막을 수 있다는 건 댓글이 글 게시자에게 볼 권한이 있다라고 볼 수 있는 거 아닐까요?

만약 글 게시자가 B-C의 비밀댓글을 볼 수 없고, 서로 많은 비밀 댓글이 오갔다면,
저는 글삭제를 하거나, 글삭제가 안된다면, 댓글을 못달게 막겠습니다.

**Comment by haegyung** [comment]
@kijin 님 말씀처럼 이 사례로 코어에서 제공해주는 기능이 많아지고, 그 활용 성이 넓어지는 방향은 좋은 것 같습니다.
다만 코어 업데이트시 공개되는 내용에서 "본문 게시자를 배제하는 댓글 공개권한"에 대한 내용은 인지 되지 않아야 할 것 같습니다. 만야 그렇지 않고, 저러한 내용이 인지되는 순간 코어에서 그기능을 순기능으로 본다고 인식할 것이기 때문입니다, "본문 게시자를 배제하는 댓글 공개권한" 은 순기능이 아닙니다.

**Comment by kijin** [comment]
@haegyung 만약 저와 @fromthere 님의 제안처럼 확장변수를 활용하는 방향으로 간다면 "본문 게시자를 배제하는 댓글 공개권한"보다 훨씬 더 광범위한 기능이 되어버리겠죠. 개인적으로는 "문서 및 댓글의 접근권한을 유연하게 조정할 수 있도록 함" 정도가 되었으면 좋겠습니다 ^^

**Comment by qw5414** [comment]
굳이 이 이슈의 대해서 또 이야기 드리자면..

코어자체에서 제공해주는건.. 그 칼럼만 제공 해주고, 그걸 처리하고 싶은 유저는 서드파티에서 해결할 수 잇는 그런 취지가 되는 방향이 좋을 것 같아요.

일딴 코어에서 제공하는 기본적인 기능이 정상적으로 다른 서드 파티모듈을 사용하는 수많은 사이트에 호환을 해야하는것도 주 목적이 되어야 합니다.

디비 칼럼의 추가로 인해서 다른 모듈에서 댓글작성이나 등등을 제공 하는 모듈을 사용하다가 오류를 내뿜을 수 잇는 부분적인 문제점도 존재하지 않을까 하는 우려때문이죠..

**Comment by mactopia** [comment]
해경님은 꾸준히 무슨 이야기를 하는 건지 알기 참 힘드네요. "본문게시자를 배제하는 댓글 공개권한" ? 
에 대한 내용은 인지되지 않아야 할것 같습니다. ??

"본문 게시자를 배제하는 댓글 공개권한"은 순기능이 아닙니다? 

순기능의 정의는 뭐고 설사 순기능이 아닌지를 어떤 근거로 일반화 시키고 본인이 단정하시는지요?
