### ISSUE TITLE
불필요한 PHP4용 코드 삭제

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1370]
`classes/mail/Mail.class.php` 파일의
```php
if(version_compare(PHP_VERSION, '5.0.0', '>='))
{
	require_once _XE_PATH_ . "libs/phpmailer/phpmailer.php";
}
else
{
	require_once _XE_PATH_ . "libs/phpmailer/class.phpmailer.php";
}
```

`classes/db/DB.class.php` 파일의
```php
if(version_compare(phpversion(), '5.0') < 0 && preg_match('/pdo/i', $db_type))
{
	continue;
}
```

이외에도 htmlpurifier쪽에도 관련 코드가 남아 있으나 코어쪽이 아니므로 제외했습니다.

XE는 이미 PHP4를 지원하지 않으니 PHP4용 코드가 XE에 여전히 남아 있습니다.
어차피 PHP4에서는 사용조차 되지 않으므로, 위 코드는 삭제되어도 괜찮을듯 싶습니다.

**Comment by qw5414** [comment]
:+1:

**Comment by YJSoft** [comment]
htmlpurifier에도 php4 코드가 있으나 htmlpurifier를 4.6.0으로 업데이트하면 해결되는 문제이므로 포함하지 않았습니다.
PR 보내겠습니다.
