### ISSUE TITLE
신고 클릭시 '신고 사유' 작성..

### ISSUE THREAD

**Issue by perzona420** [xpressengine/xe-core#1386]
신고 클릭시 '신고 사유'가 표시 되었으면 합니다.
신고를 왜 했는지 작성되어 있다면 관리자가 편하게 관리가 가능하지만..
표시가 안되있다면.. 왜 신고 했는지 확인에 불편함이 있습니다.

기본적으로 xe에 탑재 되었으면 하는거라 이슈를 남겨보아요.
감사합니다.

**Comment by mactopia** [comment]
그러네요...사적인 감정을 판단 할수 있는 좋은 아이디어 같습니다.

**Comment by kijin** [comment]
몇 가지 옵션을 관리자가 직접 지정하고, 그 중 하나를 선택할 수 있도록 하는 것도 좋겠습니다.

예:

- 광고
- 성인
- 욕설
- 게시판의 목적에 맞지 않음
- 기타 (직접 작성)

**Comment by mactopia** [comment]
@kijin 호...전문가는 역시 틀리네요...

**Comment by Himom42** [comment]
정말 필요로 하는 필수 기능이네요 ㅠㅠ
