### ISSUE TITLE
executeQuery 실행시 오류

### ISSUE THREAD

**Issue by sylee123** [xpressengine/xe-core#1387]
AWS EC2에 서버를 생성하고 AMI에 이미지를 생성해놓고 서버를 생성하여 쓰고 있습니다.

원본서버는 잘 작동되는데 새로 생성된 서버에서는 로그인이 안되는 현상이 발생하였습니다.

```php
$oMemberModel = &getModel('member');
$member = $oMemberModel->getMemberInfoByUserId($user_id); //여기서 오류
```

getMemberInfoByUserId 여기서 오류가 나길래 살펴봤더니

```php
function getMemberInfoByUserID($user_id, $columnList = array())
	{
		if(!$user_id) return;
		$args = new stdClass;
		$args->user_id = $user_id;
		$output = executeQuery('member.getMemberInfo', $args); //여기에서 오류
		if(!$output->toBool()) return $output;
		if(!$output->data) return;
		$member_info = $this->arrangeMemberInfo($output->data);
		return $member_info;
	}
```

executeQuery를 실행 하면 오류가 나더라구요.

```php
$output = executeQuery('member.getMemberInfo', $args);
```
member 모듈 query 폴더에 getMemberInfo.xml이 있는건 확인했습니다.

서버환경은 PHP Version 5.5.9-1ubuntu4.7+MariaDB 입니다.

executeQuery가 실행하면 오류가 나는 이유가 뭘까요..??

오류 메시지는 뜨지 않고 뺑뺑이 몇초 돌다가 백지현상이 나타납니다.

**Comment by bnu** [comment]
오류메시지 내용 확인이 필요합니다.

**Comment by sylee123** [comment]
/index.php?act=procMemberLogin에 백지 페이지로 나오며, 에러는 표시되지 않았습니다.

아파치쪽 에러로그도 남은것이 없으며,

아파치가 죽어서 아파치 재실행을 해야 서버 접속이 가능합니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
