### ISSUE TITLE
CK 에디터 사용시 파일 다중 선택이 안됨으로 불편 초래

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1388]
파일첨부 혹은 선택삭제를 위해 파일을 선택을 할때 1개씩 밖에 선택이 되지 않아 여러번 반복해야 하는 수고가 따르게 됩니다.

섬네일에 모두 선택할 수 있는 부분있고 사용자는 당연히 일괄로 처리할 수 있으리라 예상하지만 실제로 그렇게 동작하지 않아 처음 사용시 여러번 시도를 하게 되고 만약 이부분을 어쩔수 없는 부분으로 받아 들인다 해도 불편하다는 생각을 계속 하게 될 것입니다.

**Comment by wookho** [comment]
이부분 확인을 다시 해 보니 shift 키를 누른채 선택해야만 다중선택이 되게 되어 있습니다. 이는 널리 사용하는 체크박스에 체크를 하여 다중선택이 가능한 부분과 달라 체크박스를 체크만 하여도 체크가 모두 되게끔 개선이 필요해 보입니다.

**Comment by wookho** [comment]
모바일 환경에서 다중선택을 고려했을때 다중선택이 클릭(탭)으로만 이루어질 수 있어야 될 것 같습니다.

**Comment by bnu** [comment]
#1579 에서 처리 합니다.
