### ISSUE TITLE
파일 첨부하려 하면 

### ISSUE THREAD

**Issue by pacific20** [xpressengine/xe-core#1395]
1.8.0업데이트후 파일 첨부하려하면 에러가 뜸니다. 
이유를 아무리 찾아봐도 알수가 없어 요청드립니다. 

http://pacific20.byus.net/xe/index.php?mid=board_jtbd70

**Comment by bnu** [comment]
문제되는 오류 메시지나 상황에 대한 설명이 필요합니다.
발생한 문제가 특정 브라우저에서 나타나는 것인지 등 좀 더 상세한 내용을 확인해주세요.
