### ISSUE TITLE
1.8 버전 debugPrint() 안찍히네요

### ISSUE THREAD

**Issue by shonelee** [xpressengine/xe-core#1401]
1.8 버전 업그레이드후 debugPrint() 안찍힙니다.

**Comment by qw5414** [comment]
잘사용하고 있는데요?ㅎ 제 서버에서는 잘나와요..

**Comment by YJSoft** [comment]
@shonelee 
혹시 `config.inc.php` 파일을 직접 편집하셨나요?
`config.inc.php` 파일은 버전 업때마다 덮어 씌워집니다. 
`config.user.inc.php` 파일을 만드셔서(`config.inc.php` 파일이  있는 폴더에) 사용하시는걸 권장드립니다.

```php
<?php
define('__DEBUG__',1);
```
처럼 적으시면 됩니다.

**Comment by shonelee** [comment]
YJSoft 님 제안하신대로 했는데 역시 안찍히네요..
php 버전과 관련이 있을까요?  저는 5.3 버전인데..

**Comment by qw5414** [comment]
@shonelee 관련없습니다...

**Comment by shonelee** [comment]
@qw5414 @YJSoft 
files 폴더권한도 777로 주었고, 
define('__DEBUG__',1);
define('__DEBUG_OUTPUT__', 0);
이외에 다른 부분 볼 부분이 있나요?

**Comment by qw5414** [comment]
```PHP
<?php
define('__DEBUG__', 1);
define('__DEBUG_OUTPUT__', 0);
```

**Comment by shonelee** [comment]
@qw5414 
네 그렇게 되어 있죠.. 당연히.

**Comment by qw5414** [comment]
config.inc.php 은 다시 원본으로 되돌려 두시는게..

**Comment by shonelee** [comment]
@qw5414 
네.. 그렇게 했는데.. 상관은 없네요..

**Comment by qw5414** [comment]
`define('__DB_DEBUG__', 1);` 이거도 한번 추가해보시길..

**Comment by shonelee** [comment]
@qw5414 
감사.. 그것도 했네요..  
아무래도 1.7로 돌아가야할 것 같아요..

**Comment by qw5414** [comment]
@shonelee debugPrint를 적용시킨 함수가 빈값일경우 나타나지 않는 경우도 있습니다.

자신이 코딩한 php의 코딩상태나 등을 확인 해보셔야..할 것 같기도해요..
물론 그정도 하신다는건 어느정도 개발능력이 되신다는 것이겠지만요..

쉽게 확인하시는 방법으로는 일부러 로그인비밀번호를 틀려 오류화면을 보는 방법으로도 디버그프린트가 작동하는지 아닌지 확실하게 볼 수 있습니다.

**Comment by bnu** [comment]
./config/config.user.inc.php 파일에 다음과 같이 작성해보세요
```php
<?php
define('__DEBUG__', 1);
define('__DEBUG_OUTPUT__', 0);
define('__DEBUG_PROTECT__', 0);
```

**Comment by shonelee** [comment]
@qw5414 
감사..  다른 모듈에서도 테스트 해 봤는데 안되요.. 아무래도 환경문제인듯..
그것말고도 1.8에서 안되는 것들이 많아요.. 그냥 Back 하는 게 낳겠어요..

**Comment by misol** [comment]
@shonelee 1.8 사용하시다가 1.7로 내리면 로그인이 안될겁니다.

**Comment by qw5414** [comment]
@shonelee 제가 사용하는 서버에서는 정상적으로 작동중이에요..

@misol md5옵션 그대로 설정에서 바꾸지 않았으면 괜찮을껄요? 비밀번호 DB데이터가 md5만 유지 하고 잇다면 괜찮을겁니다
