### ISSUE TITLE
다양한 국가에서 접속하는 사이트의 경우...

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xe-core#1402]
다양한 국가에서 접속하는 사이트을 운영하고 있습니다.

기본적으로 한국인이 재일 많기는 하지만 타이완에서도 적지않게 들어올 예정으로 보여집니다.

하지만, 그들은 한글을 모르는 경우가 다반사입니다.. 아무래도 이러한 사이트들을 운영하는 사람들도 XE에서는 적지 않을 것으로 보여집니다..(특히 소녀시대팬사이트들 같은곳도 대부분 그렇습니다.)

그들에게 안내는 항상 하고 있지만, 다국어 설정이 생각보다 레이아웃에 따라 애드온에 따라 쉽지 않거나 발견하기 힘든 구간이 있다고 판단됩니다.

이럴경우 자동으로 접속하는 국가의 코드를 인식해서 우리가 설정한 언어 설정에서 포함되는 언어가 있을경우 그 국가의 코드를 따라 설정이 가능하게끔 되었으면 좋겠습니다..

EX)
접속지역 : 대만
접속지역의 사용언어 : 중국어 - 번체
사이트의 사용언어에 중국어-번체가 채크되어있는지, 확인 있으면 그 접속 코드엔 중국어로 출력.

이런 형태가 되었으면 좋겠습니다...

**Comment by kijin** [comment]
IP 주소를 바탕으로 위치를 추정할 수도 있겠지만, 이렇게 하려면 각 나라에 배정된 IP 대역을 DB로 만들어 비교하거나, 외부 API를 활용해야 하기 때문에 복잡해집니다.

브라우저의 `Accept-Language` 헤더를 활용하는 방법은 훨씬 간단하고, 미국에 사는 중국 화교나 일본에 사는 한국인처럼 IP 주소의 위치와 실제 언어가 다른 경우에도 자신의 컴퓨터는 자신이 선호하는 언어로 설정해 두고 사용하는 경우가 많으므로 정확하게 파악이 가능합니다. (저처럼 한국에서 영어판 OS를 사용하는 사람도 있긴 하지만... 그 정도는 이해해 드릴게요.)

[일단 애드온으로 구현해 봤는데](https://github.com/kijin/xe-addon-autolang), 애드온이 호출되는 시점에는 이미 `Context` 클래스에서 언어 설정을 마친 후이기 때문에 그걸 되돌리느라고 다소 비효율적인 코딩이 되어버렸네요. 그러나 신규 방문자당 한 번씩만 이 과정을 거치면 이후에는 언어 설정을 쿠키로 기억하도록 했으니 큰 문제는 없을 듯 합니다.

**Comment by qw5414** [comment]
@kijin 괜찮네요. 
꼭 해당 국가가 아니라도 해당 국가에서는 당연히 브라우저의 Accept-Language 이 다를태니 이를 이용해도 관계없겠죠 !
