### ISSUE TITLE
CKEditor 사용시 문서서식이 적용되지 않는 현상.

### ISSUE THREAD

**Issue by rarururi** [xpressengine/xe-core#1406]
기존 xpresseditor 에서 사용중이던 문서서식을 ckeditor 에서 사용하지 못하는 현상.
css는 정상적으로 로딩하나 editor.html 의 내용을 불러오지 못함.

**Comment by izuzero** [comment]
CKEditor용 문서 서식은 따로 있습니다.

**Comment by rarururi** [comment]
1.8 업데이트 내용을 살펴봐도 서식에 대한 설명이 없습니다.
그로인해 단순히 에디터만 바뀐다고 생각하였기 때문에 다른 설명이 없어서 사용하기가 힘듭니다.
따로 어디에 있는지, 어느 폴더인지, 어떻게 생성해야하되는지요.

**Comment by flowerrain** [comment]
같은 현상이네요. 문서서식없이 그냥 빈 화면만 나옵니다. 그러다가 다시 에디터를 기존의 xpresseditor로 변경하면 정상 작동이 됩니다. 문제는 똑같은 버전의 xe 로 두 개의 사이트를 운영중입니다. 레이아웃, 애드온, 모듈 등 거의 동일함에도 한쪽은 제대로 화면이 나오고, 한쪽은 빈 화면만 나옵니다.ㅠㅠ

**Comment by flowerrain** [comment]
저의 경우 1.8.2 업그레이드 후 증상이 해결되었습니다.

**Comment by jjvision** [comment]
같은 현상입니다. 도대체 왜 그러는지 알 수가 없습니다. 
에디터 안에서 서식을 갖추어서 글을 쓰면, 서식이 보입니다. 그래서 안심하고 등록을 누르면 
![image](https://user-images.githubusercontent.com/31362821/29738632-88d80a96-8a62-11e7-8ba9-747894f604bf.png)

서식이 적용되지 않은 본문만 스크린데 출력됩니다. 
![image](https://user-images.githubusercontent.com/31362821/29738638-9e7fec7e-8a62-11e7-8dbe-6bef400bb6e1.png)

도대체 왜 그럴까요? 
에디터를 다른 것으로 선택해도 마찬가지입니다. 
저는 지금 1.8.43을 쓰고 있습니다.

**Comment by vdsluser** [comment]
동일증세입니다.
글쓸때는 서식이 나타는데, 글읽기로 가면 서식이 먹히지 않습니다.
1.8.45 입니다.

**Comment by bnu** [comment]
레이아웃 및 스킨의 영향으로 보입니다.
배포본에 포함된 레이아웃과 몇 가지 주요 레이아웃/스킨을 확인하여 서식이 적용되도록 수정하겠습니다.

**Comment by yohan666** [comment]
관련 이슈 업데이트 되기전에 해결할 수 있는 방법은 없나요? 기존 에디터로는 파일 업로드가 힘들고... (플레쉬때문에)

**Comment by bnu** [comment]
릴리즈 취소. 이슈 종료.
