### ISSUE TITLE
선택적 SSL 사용시 관리자 커스텀 모듈. 에디터 내부 파일 첨부 문제

### ISSUE THREAD

**Issue by ned3y2k** [xpressengine/xe-core#1408]
서버환경
1. 선택적 SSL 사용
2. SSL 포트 변경
3. 커스텀 모듈 사용(예: 배너모듈)

재현
1. 관리자 로그인 시도
2. 관리자 화면 표시됨(이때 URL은 https 로 되어 있음)
3. 배너 모듈에 접근
4. 에디터 내부에 첨부 파일 업로드
5. http로 파일을 업로드 시도
6. 크롬은 아래 첨부 메시지가 출력.

Mixed Content: The page at 'https://localhost:8443/index.php?module=admin&act=dispBannerAdminInsertBanner' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost/index.php?module=file&act=procFileUpload'. This request has been blocked; the content must be served over HTTPS

해결책
1. 관리자로 로그인 완료후 http로 동작하게 변경(로그인 후 http로 리다이렉트)
2. 관리자에서는 에디터 첨부시 http가 아닌 https로 첨부되게끔 함.

**Comment by kijin** [comment]
커스텀 모듈을 사용하지 않더라도 아래와 같은 상태에서 문제가 재현되는 것을 확인했습니다.

1. 선택적 SSL 사용
2. 평소 http로 사용하는 게시판에 https로 접속
3. 파일 업로드 시도
4. Mixed Content 오류 발생

오류가 발생하는 이유는 `./common/js/plugins/jquery.fileupload/js/main.js` 58줄에서 업로드 타겟 URL을 http로 생성하고 있기 때문입니다.

업로드 타겟 URL이 http로 생성되는 이유는 `setQuery()` 함수가 멀쩡한 URL을 http로 바꿔서 반환하기 때문입니다. (이 함수는 `./common/js/common.js` 239줄에 선언되어 있습니다.)

#20 문제가 아직 해결되지 않은 것 같습니다. 현재 페이지가 https인 경우 무조건 https URL을 반환하도록 고쳐야 하겠습니다. (그 밖에도 https를 사용할 이유가 조금이라도 있다면 https를 반환하는 것이 좋겠습니다. http로 요청해야 할 것을 https로 요청하는 것은 웬만해선 문제가 되지 않지만, https로 요청해야 할 것을 http로 요청하면 큰일납니다.)
