### ISSUE TITLE
코어 1.8.1에서는 본문 이미지삽입시 이미지와 이미지사이 간격어떻게 주나요?

### ISSUE THREAD

**Issue by sin007xx** [xpressengine/xe-core#1411]
안녕하세요 

버전 1.8.0

스케치북 게시판 사용중입니다

1.7.13 까지는 사용되었습니다

 업데이트후 사진게시판 본문에 첨부파일삽입(이미지) 간격 자동 조절 방법이 달라진것 같은데요 어떻게 해야하나요?

사진을 본문에 첨부하다 보면 이미지가 너무 붙어 나와서 보기가 싫어서 일일이 엔터쳐서 띄우기가 너무 번거러워서

기존에는 상단내용 css 에

<style type="text/css">
.xe_content img {
margin-bottom:30px;
display:block; /* 이미지가 작을경우 옆으로 정렬되지 않고 항상 줄바꿈. (텍스트도 옆으로 정렬되지 않고 줄바뀜) */
}
</style>
 

이렇게 입력을 해서 사용했습니다

이번에 업데이트 하면서 적용이 안되는것 같은데요 어디를 수정해야 하는지 초보라 하나도 모르겠네요

고수님들 부탁드릴께요 방법좀 갈쳐주세요

부탁드립니다

https://www.xpressengine.com/qna/22981001  xe홈페이지 질문게시판 링크입니다 

위에처럼 나와서 너무 답답해보여서 아래처럼 이미지 삽입시 자동으로 저렇게 띄워주고 싶습니다

**Comment by YJSoft** [comment]
@sin007xx 코어 문제가 아닌 단순 설정 문제는 묻고 답하기 게시판에만 올려주세요.
이곳은 XE 코어의 이슈(문제)에 대해 올리는 공간입니다. :smile:

**Comment by sin007xx** [comment]
@YJSoft 죄송합니다 예전에 여기서 답변을 해주셔서 올렸습니다 ㅜㅜ ^^
