### ISSUE TITLE
선택적 SSL 사용시 관리자 화면에서 무한 로딩

### ISSUE THREAD

**Issue by devdho** [xpressengine/xe-core#1414]
선택적 SSL 사용시 관리자 화면에서 '서버에 요청 중입니다. 잠시만 기다려주세요' 메시지가 계속 나오는 문제가 있습니다.

페이지 소스를 보니 ```var request_uri``` 가 http 주소를 가르키고 있었습니다.

Context::getRequestUri() 소스를 보니 $current_use_ssl를 ```$_SERVER['HTTPS'] == 'on'```  로 확인하고 있었습니다.

$_SERVER['HTTPS'] 가 없지만 https를 사용할 수 있으므로 이에 대한 처리가 필요한 것 같습니다.

참고로 최근에 cafe24 의 경우는 HTTP_CAFE24_SSL 를 사용하도록 수정를 한 것 같습니다.

확인부탁드립니다.

사용환경: php 5.3.13, mariaDB 5.5.34, apache, XE 1.8.1

**Comment by kijin** [comment]
https 상태인데도 `$_SERVER['HTTPS']` 변수가 없다면 서버 설정 문제이지, XE의 문제는 아닙니다. 저도 카페24 리눅스호스팅에서 SSL 사용하는 사이트가 하나 있는데, HTTPS 변수가 정상적으로 들어옵니다. 만약 이 변수가 없다면 카페24 쪽에서 서버 설정을 잘못 건드렸을 수도 있으니 일단 카페24 측에 문의해 보시기 바랍니다.

반면, 다른 변수명을 사용하는 것이 호스팅 업체의 공식적인 정책이라면 XE 쪽에서도 대응이 필요하겠지요. 그러나 호스팅 업체가 멋대로 다른 변수명을 사용한다면 이것도 대책이 없습니다.

**Comment by devdho** [comment]
호스팅 서버의 일시적인 문제였었나 봅니다.
$_SERVER["HTTPS"] 변수 확인이 다시 되었습니다.

구글에서 찾아보니 $_SERVER["HTTPS"] 변수 확인이 안되서 https 작동 유무를 다른 방식으로 체크하는 사례가 있길래 혹시 XE 에서도 방어적인 코드가 필요하지 않을까 하는 생각에 이슈로 남겼었습니다.

https 사용시에는 $_SERVER["HTTPS"]가 사용되는게 표준이라고 한다면 별 문제는 없을 것 같네요.
