### ISSUE TITLE
xe 1.8.1 ckeditor 모바일에서 사용시

### ISSUE THREAD

**Issue by twocad** [xpressengine/xe-core#1416]
document.controller.php
comment.controller.php

위 파일에 있는

if(Mobile::isFromMobilePhone()) 부분 모두 주석처리를 해야 제대로 입출력이 되는데요.

ckeditor 를 사용할 때에만 위 부분을 사용하지 않도록 할 수는 없을까요.

**Comment by misol** [comment]
이 부분을 변경하게 되면, 이전에 만들어진 스킨에서 글을 쓸 경우 모두 줄바꿈이 되지 않고, 꺽쇠<>가 들어간 글을 쓰는데 문제가 생기겠지요.
하지만, 적절한 방법(변수를 하나 더 전달해서 구분한다든지..)이 있다면 저도 바랍니다. 기대중
