### ISSUE TITLE
본문 서식과 댓글 서식을 XE CKEditor 기본 서식으로 변경

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1418]
현재 XE 클린설치시 XE 기본서식이 사용되나 이경우 에디터에 여백이 없게 됩니다.
XE 기본서식은 XpressEditor 사용시 사용되던 서식이므로 기본 에디터가 CKEditor로 바뀐 1.8 이상에서는 XE CKEditor 기본 서식을 사용하는것이 좋다고 봅니다.

**Comment by qw5414** [comment]
乃乃

**Comment by wookho** [comment]
서식을 변경해야 한다는 것 조차 알기 어렵네요. 저도 이걸 모르고 소스를 고쳐서 여백을 주었다가 나중에 서식변경이 있다는걸 알고 .............
