### ISSUE TITLE
코어에 포함된 이미지 파일들 앞축해야 하면 어떨까 합니다.

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1420]
기본 코어에 포함된 여러가지 jpg/png 파이들은 한번만 앞축 해놓고 코어에 포함시켜 배포하면 되는데 저라도 해서 올리면 반영해주실까요? 코어 몸집도 줄고, 유저 반응속도도 개선 될거 같은데요.

**Comment by mactopia** [comment]
tinypng.com 이런거나 유틸리티 많습니다.

**Comment by misol** [comment]
압축 말하시는거죠? ㅋㅋ
간단하지만, 하면 좋을 것 같습니다 :)

**Comment by bnu** [comment]
PR 환영합니다. :+:

**Comment by bnu** [comment]
fixed #1436
