### ISSUE TITLE
새로운 웹에디터 404 에러파일 문제

### ISSUE THREAD

**Issue by dooglegh** [xpressengine/xe-core#1421]
/common/js/plugins/ckeditor/ckeditor/config.js?t=F0RD

추가 커스터마이징을 위한 파일인거 같은데 초기 XE 설치나 업그레이드시 나오지 파일이 없기 때문에 
404 오류가 지속적으로 뜹니다.

아무래도 기본설치시 빈파일이라도 있어야 한다고 봅니다.

**Comment by YJSoft** [comment]
해당 오류는 실제 동작과는 상관없는 부분입니다.
코어에 config.js 파일을 포함하여 배포할 경우 업데이트 시마다 config.js가 덮어씌워지게 되서, 추가로 설정을 하는 의미가 없어집니다.

**Comment by misol** [comment]
파일이 존재하지 않는 경우 스크립트를 불러오지 않는 것이 필요하겠군요.

**Comment by masque79** [comment]
저도 에러나네요..
