### ISSUE TITLE
페이스북 공유시 섬네일이 한번에 만들어지지 않습니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1423]
이게 페이스북의 일시적인 문제려니 하고 오래 지켜 봤는데 변함없이 2-3차례 공유 시도를 해서 
본문의 이미지가 페이스북 공유화면에 생겨납니다.

이게 XE가 판올림되면서 생긴문제로 추측되는데요. 언제부터인지는 저도 확인하기는 어렵네요.

이문제가 저희 XE에 문제가 있는지 검토가 필요하지 않을까요 ?

**Comment by wookho** [comment]
그런데 제가 예전에 네이버블로그 게시물도 테스트를 해 보니 동일한 현상이 나타나는데요. 이거 참 난해 하네요.

물론 다른곳에서도 동일하니 XE도 같은현상이 나타나는게 당연하다는 이야기는 아니구요.

**Comment by anizen** [comment]
썸네일 이미지가 너무 크거나, 이미지 로딩이 느릴 경우 썸네일이 뜨지 않습니다.
이건 페이스북 API 문제입니다. 여기서 로딩이란, 자신의 사이트의 로딩이 아니라, 페이스북 공유할 때 페이스북에서 공유할 페이지를 불러와 캐쉬화(?)하는 과정을 말합니다.

**Comment by wookho** [comment]
@anizen 썸네일이 작은 경우 문제 없다는 것을 확인하신건가요 ? 저는 따로 확인을 하진 않았지만 모든 문서가 동일한 현상이었습니다.

**Comment by wookho** [comment]
@anizen 
섬네일이 없는 경우 대체이미지가 나가게 되어더 대체이미지 자체가 상당히 작은 200픽셀 정도인데도 동일했고 모든 문서가 같은 현상입니다.

**Comment by anizen** [comment]
이미지가 크건 작건 상관 없습니다. 이미지가 크면 그럴 가능성이 더 높다고 말씀드리는 것 뿐입니다.
그래서 이미지가 너무 크거나, 로딩이 느릴 경우라고 말씀드렸습니다.
강제적으로 지정하는 API가 제공(SEO 모듈 사용시 반영됨 / og:image 메타태그)되기는 하나, 이것 또한 위와 같은 문제가 발생할 수 있습니다.


저 또한 이 문제 때문에 여러 방면으로 알아봤는데, 결론은 할 수 있는 게 없다였습니다.

XE 뿐만 아니라, 직접 작성한 html 문서의 경우도 위와 같이 동일한 현상이 간헐적으로 발생했습니다.

그리고, 이미지가 200픽셀이면 페이스북에서 규정(?)한 이미지보다 작을 거에요.

**Comment by wookho** [comment]
@anizen 그럼 말씀하신 조건은 논외로 하고 API측 문제로 해결 불가인지 여부에 대해 알아보는게 합리적이고 생산적일 것 같습니다. 제가 이슈로 등록한 목적이 XE의 오류이니 해결을 해야 한다가 아니고 XE에코어에서 방법이 있다면 이라는 가능성에 희망을 두고 올린 것이니까요,.

말씀 하신 현상은 예전에는 랜덤하게 발생하는 일시적인 문제였다면 지금은 100%의 확율로 이야기 할 만큼 이미지가 만들어지지 않고 있습니다. 3번 4번 5번 정도는 해야 만들어지는 정도이니까요.

예전과 다른 현상에 대해 궁금하고 이것에 대해 아시는 개발자분들의 조언과 해결책 혹은 해결불가 등의 내용을 듣고 싶은것 입니다.

**Comment by misol** [comment]
@wookho 님, @anizen 님의 말씀을 요약하면, "XE 에서는 해결 불가" 라는 내용입니다. 페이스북에서 처리해줘야 합니다.

**Comment by bnu** [comment]
페이스북이 썸네일을 생성할 때 비동기로 처리하기 때문에 발생하는 문제입니다.
