### ISSUE TITLE
사이트 아이디 사용시 문제

### ISSUE THREAD

**Issue by 2nchant** [xpressengine/xe-core#1431]
카페 모듈에서만 그런 줄 알았는데, 업글타일 모듈에서도 발생하는 걸 보니 공통 문제인 것 같아 이슈남깁니다.

XE 관리자 메뉴에서 설정 > 일반 > 고급 > 기본 URL이 www.xe.com 이고 카페 모듈이나 업글타일 모듈에서 사이트 아이디를 test로 설정하면, www.xe.com/test 로 접속해야지만 페이지가 출력되고 xe.com/test 에서는 404 에러가 뜹니다.

**Comment by 2nchant** [comment]
웹호스팅에서 저러길래 이슈 남겼는데, 혹시 직접 서버로 XE 사용하시는 분들은 또 다른가요.....?

**Comment by qw5414** [comment]
코어 버전, php버전 등의 정보를.. 남겨주시면 좋을 것 같습니다.

**Comment by bnu** [comment]
www.xe.com과 xe.com은 다른 도메인입니다.

**Comment by 2nchant** [comment]
https://www.xpressengine.com/index.php?mid=download&package_id=22753646
이 애드온을 사용하면 해당 문제를 해결할 수 있네요.

**Comment by 2nchant** [comment]
아.... 이런 저 애드온을 사용해도 해결되지 않네요.... 죄송합니다....
php 5.3.13p1, xe 1.8.1, 카페24 웹호스팅 사용하고 있습니다.

기본 URL이 kakao.me 입니다.

이게 mid가 xe이면 www.kakao.me/xe 와 kakao.me/xe 둘다 들어가도 페이지가 출력되요. www를 넣던 말던 mid이면 동일하게 페이지가 표시되는데,
사이트아이디(vid <-이게 맞는지는 모르겠습니다.)가 cafexe면 기본 URL이 kakao.me 일 떄 kakao.me/cafexe 로만 페이지가 출력되고, www.kakao.me/cafexe 로는 출력되지 않습니다.

이게 문제인지는 잘 모르겠는데 위에 애드온을 사용했을 땐 http://www.kakao.me/?mid=cafexe 로 불어와서 혹시나하는 마음에 http://www.kakao.me/?vid=cafexe 로 해봤는데 작동하지 않네요....

소소한 문제이지만 해결하고싶어 올립니다.
감사합니다~

**Comment by ForPeople** [comment]
이문제는 근본적으로 웹서버의 버추얼호스트 세팅 문제 아닌가요?

**Comment by 2nchant** [comment]
음.... 제가 잘 몰라서 그런데 버추얼호스트가 무엇인가요?
