### ISSUE TITLE
페이지 브라우저 제목 다국어 설정 안되는 문제

### ISSUE THREAD

**Issue by phiDelbak** [xpressengine/xe-core#1439]
페이지의 브라우저 제목을 다국어로 설정하면 적용이 되질 않습니다.

**Comment by YJSoft** [comment]
XE 버전을 적어주시지 않아 최신버전(1.8.1)에서 테스트하였습니다.
결과 문서/위젯/외부 페이지 모두 다국어 설정이 정상 적용됩니다.
사용중 모듈이나 애드온의 문제일 가능성이 큽니다.

**Comment by phiDelbak** [comment]
![1](https://cloud.githubusercontent.com/assets/12091900/7369673/bbe08b38-edee-11e4-85f9-848e45988a7e.PNG)
다국어 설정시 위 사진 처럼 회색으로 변하는게 맞는것인지 알았는데 저장 후 다시 돌아가는군요. 
제가 착각했습니다. 죄송합니다. 
그런대 다국어 사용 중인지 위처럼 표시해 주는게 더 좋을것 같다는 의견 남기고 갑니다.
그럼 수고해 주세요^^

**Comment by phiDelbak** [comment]
추신: 아니네요/ 저장 후에도 보존 되네요. 제가 잘못된 정보를 본거 같아요 
말씀대로 다른 게 문제네요. 착각... ㅎㅎ;;

**Comment by phiDelbak** [comment]
`xe_modules` browser_title 에는 $user_lang->userLang20150520160716059 이런식으로 들어있지만
$this->module_info->browser_title 에는 벼환되어 들어 있던게 문제네요.
