### ISSUE TITLE
신고 알림 기능이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1441]
신고를 받으면 관리자가 일일이 확인 하지 않는 이상 뭐 방법이 없습니다.

관리자 대쉬보드에 한켠에 자리를 하거나 팝업이라도 뜨면 좋겠는데요.. 

신고는 신고에 대한 빠른 대처가 생명인데...기능만 있지 실사용 까지 고려가 좀 되면 좋겠습니다.
의견입니다.

**Comment by qw5414** [comment]
써드파티 애드온이나, 모듈이 있는 것으로 알고 있습니다 :)
