### ISSUE TITLE
글/댓글 신고 갯수도 표현 할수 있게 해주셨으면 합니다.

### ISSUE THREAD

**Issue by socialskyo** [xpressengine/xe-core#1443]
https://www.xpressengine.com/qna/22988332

{$comment->get('voted_count')?$comment->get('voted_count'):0} 
추천

{$comment->get('blamed_count')?$comment->get('blamed_count'):0}
비추천

{$comment->get('declared_count')?$comment->get('declared_count'):0}
신고

에서 신고만 안됩니다. 관리자 화면에서는 보이는거 같은데..스킨에서도 활용할수 있게 
만들어 주시면 좋겠습니다. 의견 드립니다.

**Comment by Himom42** [comment]
공감 합니다. 신고 기능을 현재 XE에서 좀더 신경 쓸 필요가 ㅠㅠ
