### ISSUE TITLE
콘텐츠 위젯에서의 댓글 출력시 비밀댓글 노출

### ISSUE THREAD

**Issue by kaijess** [xpressengine/xe-core#1444]
현재 콘텐츠 위젯에서 게시글은 비밀글일때 출력이 되지 않습니다만
게시글이 아닌 댓글의 경우 비밀댓글이 그대로 노출되는 현상이 있습니다.
물론 운영자가 아닌 타인이 볼때에는 '비밀글입니다.'라고 표시됩니다.

코어 1.8.1 / 기본 콘텐츠 위젯

게시글과 댓글의 비밀글 노출여부를 다르게 설정한 이유가 있을까요?
게시글과 댓글 모두 비밀글 표시 여부를 위젯옵션을 두어야 하는게 더 효율적인듯 하여 이슈를 남깁니다.

**Comment by mactopia** [comment]
문제네요..댓글이 보통 응답..즉 답이 달리는 거라... 더 민감한 내용이 많을텐데요..
