### ISSUE TITLE
modules/admin 폴더에 아직도 admin_bar.html이 있네요.

### ISSUE THREAD

**Issue by KissT0XE** [xpressengine/xe-core#1445]
파일 정리하다가 확인하였는데 한번 확인해주세요.

**Comment by qw5414** [comment]
어디에 있나요?

해당 풀더랑.. tpl풀더봐도 없는데요..?

**Comment by YJSoft** [comment]
@KissT0XE 이미 있는 파일은 당연히 삭제되지 않습니다.
https://github.com/xpressengine/xe-core/tree/master/modules/admin/tpl
https://github.com/xpressengine/xe-core/tree/develop/modules/admin/tpl
코어에서는 이미 제거되어 있습니다.

**Comment by wa-sans-tv** [comment]
앗 이런 실수를... ㅠㅠ
