### ISSUE TITLE
전체글 선택시 공지 선택이 default가 아니었으면 좋겠습니다.

### ISSUE THREAD

**Issue by socialskyo** [xpressengine/xe-core#1446]
게시물 관리를 위해 게시글 전체 선택시 
해당 목적 특성상 이동/삭제를 위함인데....공지글이 있는 경우 전체 선택시 마다 
매번 deselect 해야 하는게 불편합니다.

공지글은 기본 적으로 전체글 선택시 선택이 안되게끔 불가능 할까요?

**Comment by YJSoft** [comment]
전체글 선택은 두가지 경우가 있다고 봅니다.

* 공지글까지 선택해야 하는 경우
* 공지글은 선택할 필요가 없는 경우

위 두 경우 중 공지글까지 선택해야 하는 경우 추가적으로 공지글을 선택하면 되는 반면, 공지글은 선택할 필요가 없는 경우 매번 공지글까지 체크된 것을 풀어 줘야 합니다.

다만 기본 동작을 바꾸는 것보다는, 기본 스킨에 옵션으로 전체 선택시 공지글 제외 기능을 추가하는것이 좋을것 같습니다.

**Comment by mactopia** [comment]
네. yjsoft 님 그게 되면 더 금상첨화 같습니다. 저는 지금 처럼 하나의 조건으로 되어 있는 상황이라면
차라리 공지글 선택이 기본이 아닌게 아무래도 총 클릭횟수도 적어지고 하여 제안 드려 봤습니다.

**Comment by bnu** [comment]
매우 귀찮은 일이죠..

**Comment by qw5414** [comment]
@bnu 히믈내요 슈퍼파워어얼~

**Comment by YJSoft** [comment]
사용중이신 스킨의
```javascript
XE.checkboxToggleAll({ doClick:true });
```
를
```javascript
XE.checkboxToggleAll({ wrap:jQuery('tr:not(.notice)'), doClick:true });
```
로 바꿔 주시면 됩니다.

기본 스킨은... @bnu
