### ISSUE TITLE
모바일 기본이모티콘 사용시 뒤에 내용 사라짐

### ISSUE THREAD

**Issue by unigo** [xpressengine/xe-core#1447]
요즘 아이폰이나 갤럭시 등에서 기본으로 제공하여 이모티콘을 많은 사람들이 이용합니다.

그런데 스마트폰에 기본적으로 제공되는 이모티콘 사용시 이모티콘이 저장이 되지 않고 사라집니다.

db에 저장되는 문자 제한이 있어서 사라지는 것은 xe랑 관계 없다 생각합니다.

다만 문제는 이모티콘 사용시 뒤에 정상적인 글자도 저장되지 않고 날아간다는 것입니다.

예 ) 안녕하세요 (웃음이모티콘)  (웃음이모티콘)  반가워요
-> "안녕하세요" 만 저장 됩니다.

짧은 글이면 큰 문제 없지만 이모티콘 뒤에 많은 내용을 적었다만 글이 없어져버려 문제가 있습니다.

이모티콘을 저장되게 할 수 없다면 미리 걸러내어 정상적인 글자들은 사라지지 않고 저장되게 되었으면 합니다.

**Comment by misol** [comment]
mysql 문자열을 utf8mb4로 한번 변경하고 테스트 해보세요 :)
문자열이 잘리는 문제는 고려해볼만 한 것 같아요.

**Comment by unigo** [comment]
사용중인 mysql 버전이 낮아 utf8mb4로 변경 테스트 하기가 어렵네요.
xe에서 utf8mb4를 지원하지 않아 정상적으로 작동된다는 보장이 없어 업데이트가 어려워요
(xe에서 utf8mb4에 맞게 쿼리를 줘야하는거 아닌가 싶기도 하고요)

나중에 가면 utf8mb4를 지원하게 되어 문제가 자연스럽게 해결 되겠지만
대부분 바로 변경할 수 없는 상황이 많은테니 미리 필터링해서 하는 방법이 지원되었으면 좋겠습니다.

**Comment by misol** [comment]
XE에서 utf8mb4를 지원하지 않는다고 한 적이 없습니다. utf8mb4는 사실 mysql에서 분류란 코드이지 UTF-8 표준에 이미 다 포함되어 있던 부분입니다.

**Comment by misol** [comment]
필터링 하는 것은 오히려 UTF-8 지원 범위를 줄이게 됩니다. UTF-8 문자열은 1바이트 문자열 부터 4바이트 문자열까지 표준으로 지정되어 있습니다.

**Comment by misol** [comment]
mysql을 지원하는 환경 중에 utf8mb4가 아닌 경우에 한정해서 문자열을 필터링 할 수는 있겠지만...

**Comment by unigo** [comment]
utf8와 utf8mb4가 작성 쿼리나 그런부분에서 달라져야 하는 별개인줄 알았습니다.
잘몰라서 .. 그부분에서 xe 지원 여부를 이야기 한것입니다.

다만 xe에서 기본 db셋팅을 3바이트 문자열 까지 지원하는 utf8_general_ci를 설정하고 있으므로,
utf8mb4 지원 하지않는 버전에 대해서는 필터링을 하는 것이 좋아 보입니다.
또 좀더 지원한다면 utf8mb4 지원 버전에는 4바이트 문자열을 많이 쓰게된 현 모바일 환경에 맞게
utf8mb4를 기본 설정으로 지원하는 것이 어떨까 합니다.
