### ISSUE TITLE
관리자 페이지에서의 로그인품

### ISSUE THREAD

**Issue by ghost** [xpressengine/xe-core#1448]
이전에는 로그인품이 있어 레이아웃에서 오류 생겨도 관리자 페이지 로그인품으로 로그인해서 처리하는데..
지금은 관리자 페이지에 접속시 '권한이 없다'는 오류만 뜨는걸로 변했네요.

로그인품은 유지하시는게 좋지 않나 싶어 의견을 남겨봅니다.
은근 유용하거든요 ㅎㅎ..

**Comment by BJPain** [comment]
그건 저도에요.. 권한이 없다는 오류 아래에 로그인메뉴가 들어가면 좋겠는데..
