### ISSUE TITLE
1.8 업데이트시 토마토 레이아웃 v1.6에서 메뉴 및 사이트맵 출력 안됨

### ISSUE THREAD

**Issue by cymakr** [xpressengine/xe-core#1449]
말그대로 1.8 업데이트시 토마토 레이아웃 v1.6에서 메뉴 및 사이트맵 출력 안됨

**Comment by qw5414** [comment]
XE코어의 문제점이 아닌 것 같습니다.

해당 레이아웃의 개발자에게 문의 하셔야 하지만.. 그분이 연락두절이라..ㅎㅎ

XE에서는 처리할 수 없을 것 같아요.

**Comment by YJSoft** [comment]
@cymakr 코어의 문제점이 아닌 서드파티 자료의 문제점은 각 서드파티 개발자에게 문의해 주세요.
