### ISSUE TITLE
exec_json 사용시 에러 메세지에 대한 건의 사항

### ISSUE THREAD

**Issue by phiDelbak** [xpressengine/xe-core#1451]
![default](https://cloud.githubusercontent.com/assets/12091900/7369783/a843902e-edef-11e4-9bdf-518ab50b9975.PNG)

제목을 적지 않았을때 위 사진 처럼 에러 정보가 넘어 옵니다.
그런대 어떤 에러인지에 대한 정보가 없어 처리를 하려면 따로 찾아야하는 불편이 있습니다.

message_type: "title", error: -99,

과 같이 에러에 대한 정보가 넘어 온다면 한결 개발이 편해질거 같다고 생각합니다.
개발자분들의 노고에 감사드리며 이런 의견 남기고 갑니다.^^

**Comment by YJSoft** [comment]
#988
