### ISSUE TITLE
동일한 이름의 파일 업로드 불가 현상

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#1453]
#### 증상
동일한 이름의 파일을 업로드후 삭제시 업로드가 진행되지 않습니다.

#### 증상 재현 과정
1. XE 공홈에 A.jpg라는 파일을 업로드 합니다.
2. 업로드가 완료되면 파일을 삭제합니다
3. 다시 A.jpg라는 파일을 업로드 시도합니다.
4. 파일의 업로드가 진행되지 않습니다.

**Comment by ajkj** [comment]
Firefox에서는 정상 작동하며, 크롬의 경우 Drag and Drop으로 업로드시에는 정상 작동합니다.

문제가 발생하는 Chrome 버젼은
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36 입니다.

**Comment by ajkj** [comment]
IE11(Win 8.1)에서도 동일합니다. 동일한 파일을 삭제후 업로드시 정상적으로 업로드 되지 않으며, 드래그 드롭으로는 정상적으로 업로드가 됩니다.

**Comment by ajkj** [comment]
간단하게  확인해 보았는데, ```<input type="file">``` 에서 onchange event를 이용하여 업로드 하는것 같네요.. 크롬이나 IE에서는 동일한 파일명일 경우 onChange event가 발동하지 않는것 같습니다.

**Comment by ajkj** [comment]
pr 넣어 보았습니다. #1454

**Comment by bnu** [comment]
jQuery file upload의 설정을 조정하여 해결했습니다.
문제가 되었던 브라우저에서 증상이 계속되는지 확인해주시면 감사하겠습니다. :)

**Comment by ajkj** [comment]
업로더에서 이미 옵션으로 지원을 하는 기능이였군요.

IE 8, 9, 10, 10, 11에서 정상작동하며, 최신버젼은 Chrome, FF에서 전부 정상작동합니다.

 #1454 PR은 내릴게요.

**Comment by bnu** [comment]
확인과 PR 감사합니다. :)
