### ISSUE TITLE
PostgreSQL, SQLite, Firebird 관련

### ISSUE THREAD

**Issue by delphixe4** [xpressengine/xe-core#1459]
https://www.xpressengine.com/devlog/20395449

PHP4 지원 중단에 관하여 비교적 명확한 설명을 해 주셨습니다만..

XE가 1.5까지 가지고 있던 가장 큰 장점이었던 DBMS 선택의 자유도가 꽤나 떨어졌습니다.
물론 MS-SQL도 불가능하고 MySQL만 지원하는 툴도 많긴 합니다만 지금 생각해도 너무 아쉽습니다.

특히 PostgreSQL 같은 RDBMS의 지원 재개를 요청드립니다..

**Comment by bnu** [comment]
지원 재개/추가 계획이 없습니다.
