### ISSUE TITLE
ckeditor config.js issue

### ISSUE THREAD

**Issue by delphixe4** [xpressengine/xe-core#1464]
common/js/plugins/ckeditor/ckeditor/config.js가 없어 404를 리턴하고 있어 속도가 저하되고 있습니다.

바로 옆에 config.sample.js가 있어 config.js로 복사하고 수정 적용하여 해당 문제는 없앴지만
해결이 필요합니다.

**Comment by delphixe4** [comment]
부연 설명이 짧았습니다. 임의의 페이지에서 해당 에디터를 불러오는 경우에 문제 발생하고 있습니다.

**Comment by fromthere** [comment]
@delphixe4 #1421

**Comment by bnu** [comment]
dup #1421
