### ISSUE TITLE
파일업로드시 제한 문제....

### ISSUE THREAD

**Issue by kimdaehee** [xpressengine/xe-core#1469]
6M까진 전부되는데

7메가정도 후부턴 업로드가안됨 100% 됬다가 사라져버림....버그인거같아요

사진들어간 파일은 업로드됨....이상함.....ㅡ;

**Comment by qw5414** [comment]
http://www.swhite523.com/index.php?mid=schedule&act=dispScheduleSchedule&schedule_srl=47939
이상이 없는데요?

**Comment by qw5414** [comment]
`php5.5.29` (한달전빌드)
에서 문제점이 없는걸로 나타나네요.. 21메가짜리 사진첨부햇을때요..

**Comment by kndol** [comment]
저도 큰 파일은 업로드 안 되네요.
@qw5414 사진은 커도 된다고 @kimdaehee 님이 쓰셨네요. ^^a

**Comment by kimdaehee** [comment]
@kndol 정말 안되는듯해요....사진 이외엔 다른 파일들은

묘한 현상인데 이걸 어떻게 설명해야하지.ㅡㅡ;

**Comment by kimdaehee** [comment]
@kndol  원인을 대충은 찾았어요~php 5.5에서 그런현상이 발생하네요5.3 으로 내린 후 정상작동하네요~

**Comment by kndol** [comment]
@kimdaehee php 설정 문제일까요? cafe24 웹 호스팅을 사용 중이라 php 버전을 제가 바꿀 수는 없고... 뭐 현재 제 사이트는 큰 파일 업로드할 일은 없을 것 같아서 괜찮긴 하지만 그래도 정확한 원인과 해결책을 찾으면 좋겠네요.

**Comment by qw5414** [comment]
cafe24사용시 php5.5 버전에서 방화벽인가..스팸필터를 사용시 문제점이 일어난다고 하네요.
(XE공홈 참고..)
