### ISSUE TITLE
CK에디터 IE 구버전에서 열리지 않는 문제

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1473]
사이트 회원중 IE9 에서 글쓰기 창이 열리지 않는다는 보고가 들어와 테스트를 이리저리 해 보다 알아낸 것이 위젯들이 포함된 경우 IE구버전에서 CK에디터가 열리지 않음을 확인했습니다.

저의 테스트 환경은 IE8 이 있어서 IE8로 테스트를 했습니다.
저희사이트에서 문제가 되는 위젯은 한줄광고와 카운터위젯 이었으나 다른 종류의 위젯도 영향을 줄수도 있어 보입니다.

더욱 특이한 점은 구글검색광고를 이용하기 위한 스크립트도 영향을 주어 구글검색의 검색어입력창을 레이아웃에 배치를 하면 역시 CK에디터가 IE구번전에서만 활성화되지 않았습니다.

IE11에서는 문제없음을 확인했습니다.
IE8,IE9, 는 문제가 있음을 확인했습니다.

IE10은 확인하지 못했습니다.

메시지: 잘못된 인수입니다.
줄: 66
문자: 353
코드: 0
URI: /common/js/plugins/ckeditor/ckeditor/ckeditor.js?20150409102127

**Comment by qw5414** [comment]
IE가.. 역시 걸림돌..

**Comment by wookho** [comment]
@qw5414 IE10에서도 에디터가 열리지 않는 현상을 다른 사이트에서 확인한 것으로 보아 이정도면 IE11을 제외한 아래버전 모두 문제가 있을 수 있는 상황입니다. 

물론 레이아웃에 어떠한 위젯들이 영향을 줄지 모르는 상황이라 사이트별로 랜덤일 것 같습니다.

**Comment by bnu** [comment]
@wookho 확인할 수 있는 URL을 알려주세요
(공개할 수 없으면 deveolpers@xpressengine.com으로 주세요)

**Comment by wookho** [comment]
@bnu 메일로 테스트하실 수 있는 url 보내드렸습니다.

**Comment by wookho** [comment]
@bnu 아약스보드모듈 에러관련 언급하신분 누군지 몰라 여기에 멘션합니다. 해당 증상과 상관없는 에러입니다. 일단 해당 에러 발생하지 않도록 아약스보드모듈 알림플러그인 해당게시판 제외시켰습니다.

**Comment by wookho** [comment]
@bnu 제가 포럼에 작성한 글도 단순 질문성 게시물로 분류하여 묻고답하기로 이동하였는데 에디터 사용에 큰 문제가 있는데 이슈가 아닌것으로 판단 하신건가요 ?

**Comment by wookho** [comment]
테스트 url 남겨놓을게요. 비회원 글쓰기 당분간 열어 놓겠습니다.
http://pomelove.com/xe/joint

**Comment by wookho** [comment]
웹 페이지 오류 세부 정보

사용자 에이전트: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; GTB7.5; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
타임스탬프: Thu, 14 May 2015 14:57:42 UTC


메시지: 사용 가능한 저장소가 부족하여 이 작업을 마칠 수 없습니다.

줄: 66
문자: 140
코드: 0
URI: http://pomelove.com/xe/common/js/plugins/ckeditor/ckeditor/ckeditor.js?20150409102127

**Comment by wookho** [comment]
레이어팝업애드온 사용이 원인이 되었음을 확인했습니다.

**Comment by wookho** [comment]
단순히 레이어팝업애드온의 문제가 아니라 다시 이슈 살렸습니다.
IE구버전에만 CK에디터 활성화가 안되는 것에 영향을 주는 것들
각종위젯,아약스보드모듈html5알림,실시간글알림애드온2,레이어팝업애드온,딩고정배너 등 너무 많네요.

**Comment by YJSoft** [comment]
@wookho IE 6~9 버전까지는 다음 제약이 존재합니다.

* 문서에서 사용할 수 있는 `<style>`태그와 `<link>` 태그는 합쳐서 31개 까지만 가능
* 파일당 CSS 선택자(.className{})는 최대 4095개까지만 가능
* 파일당 최대 31개의 `@import`문 사용 가능
* `@import`는 최대 4개 깊이 지원

해당 문제가 발생하는 시점이 CSS 등록 시점인 것으로 봤을 때, 이미 많은 CSS 파일과 style문이 있는 상태에서 추가로 불러오면서 발생하는 오류로 추정됩니다.(CKEditor가 4개의 css 파일을 추가로 불러옵니다)

http://stackoverflow.com/questions/9906794/internet-explorers-css-rules-limits

**Comment by wookho** [comment]
@YJSoft 설명 감사합니다. 이제 모든 현상이 이해가 가네요. 왜 구형 IE에서 사이트 디자인이 틀어지는 현상이 특정자료들을 추가했을때 발생하는지 이해가 갑니다. 

지금 다수의 사이트을에서 원인을 찾지 못하는 것이 아마 하나씩 제거해 보고 그게 아니다 싶으면 다시 해당자료를 다시 사용하게 하고 다른 것을 사용해제 해보고 하면서 찾을 겁니다. 이래서 원인을 찾지 못했던 사이트들이 많을 겁니다. 저는 무식하게 레이아웃을 미사용으로 하면 문제가 없길래 사용된 자료를 하나씩 제거하는 것을 반복해서 결국 말씀하시는 제약에 벗어나는 시점에서 CK에디터가 활성화가 되었던 것이군요.

지금 타 자료들은 단순히 디자인이 틀어지는 문제정도여서 아마 심각하게 받아들이지 못했고 그냥 오래된 브라우저니 그러려니 했던거 같습니다. 

하지만 에디터비활성화의 경우 글 작성 자체가 안되니 뭔가 대책이 필요한 것 같습니다.

그렇다고 현 시점에서 지원이 중단이될 구형 에디터를 사용할 수는 없는 상황이고 지금 사이트에서 이 문제 때문에 사이트에서 제거한 기능(위젯과 애드온등)이 상당한데 이것도 부담이 됩니다.


구형브라우저 사용자들에게 글쓰기가 안되니 최신브라우저를 사용하라는 고지는 한계가 있어서요.

**Comment by kijin** [comment]
1) 예전에는 여러 CSS, JS 파일들을 하나로 묶어서 전송해주는 기능이 있었던 것 같은데, 없어진 건가요? 아니면 제가 기억을 잘못하고 있는 건가요? 만약 없다면 다른 애드온에서 삽입하는 각종 CSS, JS 파일들을 하나로 묶어주는 애드온을 개발해 봐야겠네요 ㅎㅎ

2) 공홈 포럼의 관련글에서도 제안했지만, 에디터의 정상 작동을 보장할 수 없는 환경에서는 과감하게 `<textarea>`로 graceful degradation이 되었으면 좋겠네요. 최신브라우저를 사용하지 않더라도 기본적인 글쓰기에는 지장이 없지만, 색깔도 넣고 글꼴도 바꾸고 이미지도 편집하고 다중파일업로드 기능을 사용하고 싶다면 최신브라우저를 사용하라고 당근을 던져주는 거죠.

**Comment by wookho** [comment]
@kijin  네. 글쓰기만 이라도 최소한으로 제공하는 것으로 에디터에서 해결해 줬으면 합니다. 최신브라우저 쓰면 되잖아. 이건 너무 한 거 같아요.

기존에디터는 어떠한 방식인지 몰라도 에디터가 잘 열리니 말입니다. 구형 브라우저에게 많은 것을 지원하는 것을 바라는게 아니고 최소한 글자라도 입력할 수 있는 제한적인 기능을 제공만 한다면 나머지 최신 브라우저들에게는 사이트에 보다 많은 자료들을 이용할 수 있게 할 수 있지 않나 합니다. 

지금으로서는 IE9이하를 무시할 수 없는 사이트에서는 CK에디터를 포기하거나 혹은 많은 자료를 내려야 하는 상황이네요. 

어찌 되었던 저와 같은 생각을 뭐 그리 오래된 브라우저 사용자들까지 고려하려고 하냐 ? 라고 하시는 분도 계시리라 생각되지만 그건 관점의 차이이니 누가 옳다고 하기는 어려운 문제이고 어떤 방식으로든 해결을 보아야 할 문제라고 보네요.

**Comment by wookho** [comment]
@YJSoft 몇몇 필요한 자료(애드온 등)의 CSS를 레이아웃에 직접 적용하여 사용하면 새로운 CSS가 추가되는 것이 아니라 언급된 제약에서 벗어나게 되는건가요 ? 이게 맞다면 일단 해결점이 보이기 전 까지 일부 자료들이라도 이렇게 해서라도 사용하는건 어떨지 해서요.

**Comment by kijin** [comment]
@wookho 각 페이지의 `<head>` 부분에 들어가는 CSS 및 JS 레퍼런스들을 각각 하나의 파일로 모아주는 애드온을 만들어 보았습니다. 이미지 및 `@import` 등의 상대경로도 자동으로 변환됩니다. 개인적인 테스트 결과 일단 큰 문제는 없어보이지만, 급조된 애드온이라 어느 모듈이나 위젯과 충돌을 일으킬지 모르니 주의하세요. 좀 안정화시키고 나서 공홈 자료실을 통해 배포하겠습니다.

https://github.com/kijin/xe-zipperupper

설치 경로는 `./addons/zipperupper` 입니다.

**Comment by qw5414** [comment]
기진님 대.다.나.다

**Comment by wookho** [comment]
@kijin 오..  만들어주신 애드온이 해결책이 될수 있겠군요. 그런데 혹시 !important 와 같은 것을 사용해서 다른쪽의 선언된 것을 무력화 하는 등의 이런 내용이 발목을 잡거나 하지는 않을까요 ? 한군데로 합쳤을때  말이죠....

**Comment by kijin** [comment]
@wookho 페이지 소스에 등장하는 순서 그대로 붙였기 때문에, 적용되는 순서도 똑같을 거예요.

**Comment by bnu** [comment]
@wookho 최근 첨부파일 관련 라이브러리로 인해 IE8에서 에디터 활성화에 영향을 주는 문제를 1.8.7에서 해결 했습니다. 확인가능하시면 1.8.7에서 확인부탁드립니다.
최신 패치가 적용된 윈도우7, IE8 환경에서 확인해 본 것으로는 해당 문제가 더 이상 나타나지 않았습니다.

**Comment by kijin** [comment]
@bnu 코어와 일부 애드온만의 조합으로는 정상 작동하더라도, 애드온 갯수가 늘어나면 IE 구버전의 스타일시트 갯수 제한 때문에 언제든지 다시 문제가 발생할 수 있을 것 같습니다. 에디터에서 사용하는 스타일시트의 갯수를 정말 획기적으로 줄였다면 몰라도...
