### ISSUE TITLE
live.jp 에서 이메일이 안받아진다고합니다.

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1476]
![kakaotalk_20150518_223645925](https://cloud.githubusercontent.com/assets/1341628/7683718/df86cfb6-fdbb-11e4-8aab-2321dbcbf72b.png)

가입자가 보내온 사진입니다. 확인 부탁드려요 (내용이 빈칸으로 뜬다고하네요)

**Comment by kijin** [comment]
#1367 #1372 한메일 텅 빈 메일 발송 문제와 관련이 있는 것 같네요.

일단 관리모듈 일반설정에서 Qmail 호환 옵션을 한번 건드려 보세요.
