### ISSUE TITLE
1.8 이후 css/js의 외부 로드가 불가능한 문제

### ISSUE THREAD

**Issue by cherrype** [xpressengine/xe-core#1477]
A. 개요

XE의 1.8 버전 업그레이드 이후, jQuery 관련 CSS, JS 파일들의 외부 로드가 제대로 이루어지지 않습니다.

B. 문제점

- 트래픽과 부하 분산을 위해 jQuery의 외부로드 애드온(jQuery UI 외부로드 애드온 ver. 1.0, jQuery CDN for XE 1.7 ver. 1.0.3)을 사용하고 있습니다.

- XE를 1.8로 업그레이드한 이후에는 해당 애드온 사용시 외부에 있는 css와 js 파일을 제대로 불러오지 못하고 있습니다.

- 이러한 문제로 에디터(xpresseditor)의 로드가 불가능하거나, 회원가입시 생일 입력같은 기능 등.. 다수의 기능이 제대로 작동하지 않습니다.

C. 문제점 파악

- 처음에는 1.8 업그레이드 이후 jQuery css, js의 버전에 변경이 있었는지 확인하였으나 동일한 버전이었으므로 외부 로드 자체만으로 기능들이 오작동할 이유가 없는 것으로 보입니다.

- 동일한 XE 버전(1.8.1)의 다른 서버에서 같은 내용의 jss, cs를 외부 호출하는 경우에도 문제점은 계속 발생합니다.

- 1.7.13에서는 외부 호출이 정상적으로 작동함을 확인하였습니다.

**Comment by misol** [comment]
안녕하세요 해당 애드온 제작자 미솔입니다.
해당 애드온은 1.8 이후 업데이트가 필요하나 업데이트가 안된 상황입니다. 도라미님께서 애드온을 잘 관리해주실 것 같아서 배포권을 넘겨드렸는데, 아직 관리가 안되고 있습니다. 당분간 애드온 사용은 중단해주시면 감사하겠습니다.
불편을 드려서 죄송합니다.
