### ISSUE TITLE
관리자 페이지에서 회원 포인트 추가(+)가 안됩니다. 크롬만 (IE10 잘 됨)

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1479]
https://www.xpressengine.com/qna/22165405

찾아보니 예전에도 발생했고 아직도 고쳐지지 않은거같은데

고쳐주세요...

**Comment by BJPain** [comment]
이것은 IE10 및 크롬 환경에서 되는 것을 보아 IE 9 이하의 엔진에서는 제대로 작동이 되지 않는 구문이 있는 듯 합니다. Chrome 또는 IE10 또는 상위버젼에서 회원 포인트 추가를 하시는 임시방편을 쓰시는게 좋을 듯 하네요..

**Comment by hjhj3686** [comment]
크롬이 안되는건데요?

익스는 잘됩니다

**Comment by BJPain** [comment]
아.. 크롬이 되지 않는거군요.. 그냥 익스쓰시거나 혹시 https 보안접속이면 크롬이 위험하다고 막았을 수도 있습니다.. 그런 것 있는지 확인해보시고요..

**Comment by YJSoft** [comment]
@BJPain 크롬에서 number type에 + 기호 사용을 허용하지 않아 발생하는 문제로 https와 관련 없습니다.
@hjhj3686 임시로 링크하신 글 댓글처럼 수정해서 사용해 주세요.

**Comment by YJSoft** [comment]
#1223
