### ISSUE TITLE
1.8.2 업그레이드 후 레이아웃 이미지 첨부 에러

### ISSUE THREAD

**Issue by anizen** [xpressengine/xe-core#1480]
레이아웃 설정에서 이미지를 등록할 때 

Upload Failed 에러 뜹니다.

1.8.1로 다운시키니 정상적으로 업로드 되네요.

레이아웃 외 <var type="image"/> 설정은 공통적으로 위와 같은 에러가 날 것으로 예상합니다...

그래서 1.8.1로 내렸네요..

에러 확인한 php 버전은 php : 5.5.17p1 입니다. (카페24이용, 각종 필터 다 끈 상태.)

**Comment by qkrcjfgus33** [comment]
+1
저도 마찬가지 입니다.
(localhost상에서 오류. 남은 용량 충분, 2MB 이하의 파일.)

**Comment by kimtajo** [comment]
저도 같은 증상입니다!

**Comment by bnu** [comment]
@kimtajo https://www.xpressengine.com/index.php?mid=download&package_id=18325662&release_id=22755020 에서 알려진 문제 항목을 참고하세요.
