### ISSUE TITLE
사이트 잠금 때에 https 보안접속시 관리자페이지 접속불가문제

### ISSUE THREAD

**Issue by trustypeople** [xpressengine/xe-core#1482]
사이트 잠금 때에 https 보안접속시에 관리자페이지도 접속이 불가능한 문제가 있습니다.

https 에서는 아마 ip조회가 불가능한 듯 한데.. 차라리 암호로 사이트잠금된 사이트를 들어가는 방법이 필요한 듯 합니다.(제발 모듈이라도 만들어 주셨으면.. ㅠㅠ)

**Comment by kijin** [comment]
HTTPS 상태에서도 IP는 변경되지 않습니다. 만약 변경된다면 HTTP, HTTPS 둘 중 하나만 로드밸런서를 경유하도록 설정되어 있거나, 그 밖에 특이한 서버 설정 탓일 가능성이 높습니다.

아래의 내용을 파일에 넣어 적당한 경로에 올려두고 HTTP에서 한 번, HTTPS에서 한 번 방문해 보세요. 화면에 표시되는 내용이 다르다면 IP가 바뀌는 것입니다.

    <?php echo $_SERVER['REMOTE_ADDR']; ?>

**Comment by BJPain** [comment]
저는 왜인지는 모르지만 http와 https 상태의 IP가 다르더라고요;;

저는 차라리 암호로 들어가는 방법이 필요한 듯 합니다..

**Comment by bnu** [comment]
@BJPain cafe24 계정이죠?

**Comment by BJPain** [comment]
hostinger 프리미엄 계정입니다.

**Comment by bnu** [comment]
@BJPain cafe24의 경우 일부 환경에서 SSL 서버를 별도로 두는 경우가 있는 것으로 보입니다. hostinger도 그러한지 모르겠지만 유사한 문제로 보이네요.

**Comment by BJPain** [comment]
아마 cloudflare 를 사용중이라 그런 듯 하기도 합니다..
