### ISSUE TITLE
템플릿에서 load로 filename.min.js나 filename.min.css 파일을 불러올 때 같은 디렉토리 안에 filename.js나 filename.css 파일이 존재하면 min 파일을 불러오지 않는 문제

### ISSUE THREAD

**Issue by jdssem** [xpressengine/xe-core#1483]
예를 들어 템플릿에서
```
<load target="css/bootstrap.min.css" />
```
를 하면 당연히 ```bootstrap.min.css``` 파일을 불러올 것이라 생각했는데 css 디렉토리 안에 ```bootstrap.css``` 파일이 존재하면 컴파일 된 이후의 결과값은 ```bootstrap.css```이 되어 있습니다. 임시 방편으로 ```bootstrap.css``` 파일 명을 변경해서 사용중인데 이것이 의도된 것인지 오류인지 잘 모르겠습니다.

CSS나 JS 파일 모두 동일한 현상이고 파일명 가운데에 min 이외의 값을 넣을 때는 이 같은 현상이 발생하지 않더라고요.

**Comment by YJSoft** [comment]
@jdssem __DEBUG__ 값이 1이 아닌지 확인해주세요.
__DEBUG__ 값이 1이면 min 파일 대신 원본 파일을 불러옵니다.

**Comment by jdssem** [comment]
@YJSoft 아 그런 것이군요. 감사합니다^^
