### ISSUE TITLE
루아틱 Cpanel 호스팅기준일까요..?

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xe-core#1484]
세션을 불러오는
`SessionController::write`중 $val 값이 암호화 되어서 전송되는 문제점이 있네요..

무슨이유인지는 모르겠습니다만.. 저희 서버에서 문제점이 생기는 경향이 있네요..ㅠ

확인 해봐야할 것 같아요.

**Comment by qw5414** [comment]
bnu@xpressengine.com 으로 debug로 나타난 $val값을 보내드릴께요.. 혹시나 확인부탁드려요.

**Comment by kijin** [comment]
혹시 서버에 `suhosin` 모듈이 설치되어 있다면 `suhosin.session.encrypt` 설정을 확인해 보세요.

참고: https://www.suhosin.org/stories/howtos.html#session-encryption

**Comment by qw5414** [comment]
@kijin 해당 부분이 ON 되어있습니다..

**Comment by kijin** [comment]
OFF로 바꿀 수 있으면 한번 해보세요.

**Comment by qw5414** [comment]
@kijin 서버 세팅해준 곳에서 C패널 정상적으로 아직 결제가 안되어 설정이 차단되어있는데, 완료되면 해보도록 하겠습니다.

**Comment by qw5414** [comment]
@kijin c패널 자체에서 하는건 수호신을 지우는 방법뿐이네요. 일딴 지워봤더니 해결됬네요.

**Comment by kijin** [comment]
그렇다면 수호신에서 암호화하는 것이므로 XE와는 무관합니다. 세션 핸들러를 호출하기도 전에 이미 암호화되어 버리기 때문에 딱히 XE에서 할 수 있는 것도 없고요.

오픈소스계에서 거의 유일하게 우리말로 이름을 붙인 프로그램인데... 의도는 좋았지만 여기저기 문제를 일으키는 게 너무 많아요 ㅠㅠ

**Comment by qw5414** [comment]
@kijin 그러네요.. 뭐 따지고보면 DB세션의 방식도 그렇게 보안에 좋은 방법은 아니긴 하지만.. XE를 사용하는 자체적은 문제점은 크게 없지만.. 수호신으로 어느정도 웹방화벽에 대해서는 처리가 가능하긴 했으니깐 쓰긴 했던건데요..ㅎ 

조금 대처할 수 잇는 방법이 없나 싶기도 하네요 ㅎ
