### ISSUE TITLE
자동 로그인 풀림

### ISSUE THREAD

**Issue by myclements** [xpressengine/xe-core#1485]
코어 1.8.2 최신버전 업데이트 이후 자동 로그인이 풀리는 현상이 있습니다.
메인 사이트와 카페를 동시에 사용할때..
메인사이트의 자동로그인을 사용하면 카페의 자동 로그인이 풀립니다.
그 반대로 카페에서 자동로그인을 사용하면 메인사이트의 자동로그인이 풀립니다.

**Comment by kijin** [comment]
자동 로그인에 사용되는 쿠키값을 예측하기가 너무 쉬운 문제가 있어서, 1.8.2부터 쿠키값에 난수를 포함하도록 바뀌었습니다. 참고: #1359

서로 다른 두 사이트에서 지금까지 자동로그인 공유가 가능했다면 방금 말씀드린 보안 취약점 때문에 쿠키값이 동일하게 생성되었기 때문이 아닐까 합니다. 같은 브라우저에서 같은 ID와 같은 비번을 사용하기만 하면 전혀 엉뚱한 사이트에서도 마구마구 자동로그인이 되곤 했습니다 ㅠㅠ

1.8.2부터는 자동로그인 공유 조건이 더 까다로워졌기 때문에, 두 사이트의 XE 버전이 모두 1.8.2 이상이고 회원 테이블과 자동로그인 테이블까지 공유해야만 자동로그인 공유가 가능합니다.

반면, 같은 사이트인데도 카페 모듈만 들어가면 로그인이 풀린다면 그건 코어나 카페 모듈의 버그일 수도 있겠습니다.

**Comment by qw5414** [comment]
임시로 해당 모듈을 사용할 수 잇습니다.

https://www.xpressengine.com/index.php?mid=download&package_id=22753636
