### ISSUE TITLE
Module의 Controller에서 getUrl()을 호출하면 & 문자가 $amp;로 변경됩니다.

### ISSUE THREAD

**Issue by maesiltea** [xpressengine/xe-core#1486]
개인적으로 만들어 사용하는 모듈 프로그램이 있습니다만, 해당 모듈에서 Controller 멤버 함수 호출 후 아래와 같이 getUrl()을 사용하여 복귀할 페이지 주소를 세팅해 주고 있습니다.
$return_url = getUrl('','act', 'dispGmpSentenceInsertForm', 'selected_date', $obj->selected_date);
return $this->setRedirectUrl($return_url);
실제 위 코드 적용 후 Controller 내 함수를 동작시키면 url에 두번째 변수인 selected_date 앞 & 문자가 $amp;로 표시되는 바람에 selected_date변수값을 View 클래스 내 함수에서 읽어오지 못하고 있습니다.

아래 수정사항으로 인해 &문자가 &amp;로 변경되는 것 같은데요, 의도된 수정인지 확인 부탁드립니다.
https://github.com/xpressengine/xe-core/commit/681a9b2d07521131e67352a1d7e5f610f7c8b1f2#diff-de5b23b21a68b91d2437b1294f22ea1cR1598

**Comment by YJSoft** [comment]
& 등 문자가 &amp;로 이스케이프 되는 것은 의도된 동작으로, 이스케이프 되지 않은 주소는 `getNotEncodedUrl` 함수를 사용하시면 됩니다. 
```php
/**
 * Get a not encoded(html entity) url
 *
 * @see getUrl()
 * @return string
 */
function getNotEncodedUrl()
{
	$num_args = func_num_args();
	$args_list = func_get_args();
	if($num_args)
	{
		$url = Context::getUrl($num_args, $args_list, NULL, FALSE);
	}
	else
	{
		$url = Context::getRequestUri();
	}
	return preg_replace('@\berror_return_url=[^&]*|\w+=(?:&|$)@', '', $url);
}
```

**Comment by bnu** [comment]
API 문서 : http://xpressengine.github.io/xe-manual-api/html/func_8inc_8php.html#aa73dbeb07c5bcac26c24fe4c6b05d8d2

**Comment by maesiltea** [comment]
자세한 설명 감사합니다^^
