### ISSUE TITLE
링크된 이미지 출력이 되지 않습니다...

### ISSUE THREAD

**Issue by moki35** [xpressengine/xe-core#1487]
코어를 1.8.1 버젼으로 업데이트 이후에 링크된 이미지가 나오질 않습니다. 
그리고 플래쉬로 만든 메뉴의 링크도 작동하지 않네요..

페이지는 
http://rexking.cafe24.com/community2/31018
입니다. 

이미지는 html태그로 작성했으며, 
&lt;img src="http://cfile223.uf.daum.net/image/2371F94054F688890AD2CA" editor_component="image_link" /&gt;

이렇게 작성했습니다. 
아마도 확장자가 없는 이미지를 못 불러오는 게 아닌가 싶습니다. 

이미지 크기나 걸려있는 스크립트의 문제인가 싶어 리사이즈 애드온도 꺼봤지만, 
효과가 없네요..ㅋ

해결책을 알려주시면 정말 정말 감사하겠습니다.

**Comment by hhgyu** [comment]
![Image](cfile223.uf.daum.net/image/2371F94054F688890AD2CA)

해당문제는 xe문제가 아닌 다음 쪽에서 외부 리퍼러를 차단한 것으로 확인 됩니다.

**Comment by hhgyu** [comment]
해당문제는 xe문제가 아닌 다음 쪽에서 외부 리퍼러를 차단한 것으로 확인 됩니다.

Remote Address:180.70.134.229:80
Request URL:http://cfile223.uf.daum.net/image/2371F94054F688890AD2CA
Request Method:GET
Status Code:403 Forbidden

**Comment by moki35** [comment]
답변 대단히 감사합니다. 
저는 다음의 문제라고는 생각하지 않는데.. 이유가 다른 사이트에서도 같은 방식으로 링크이미지를 걸었는데 잘 나옵니다. 
http://www.3oneshot.com/default/03/01.php?com_board_basic=read_form&com_board_idx=2&topmenu=3&left=1&&com_board_search_code=&com_board_search_value1=&com_board_search_value2=&com_board_page=&
위 페이지에서는 이미지가 잘 뜨는데.. 그래서 XE의 문제가 아닌가 했는데...ㅋ

**Comment by bnu** [comment]
#1417 에서 수정 되었습니다.
