### ISSUE TITLE
1.8.2 파일 팍스 업로드 오류

### ISSUE THREAD

**Issue by fy5914** [xpressengine/xe-core#1492]
(1) 카페24 + 1.8.2 에서 파일 팍스 업로드 오류 있습니다.

(2) 사이트 메뉴 편집 -> 바로가기 -> 메뉴 링크 이미지 에서 이미지 등록시에

정상적으로 등록되지 않는 오류 있습니다.

**Comment by hjhj3686** [comment]
(1) 은 모르겠으나 저같은 경우에는 잘됩니다. (동일 서버 동일 버젼)

(2)는 .. #1480 이거 같은데

**Comment by fy5914** [comment]
hjhj3686 네 1.81 로 다시 되돌리고 나니 (1) (2) 2가지 문제 모두 정상입니다.

**Comment by bnu** [comment]
fixed #1480
