### ISSUE TITLE
.gitignore에 .idea를 추가하는건 어떨까요?

### ISSUE THREAD

**Issue by wan2land** [xpressengine/xe-core#1498]
PHP Editor계의 De facto, PHPStorm을 쓰는데 자꾸 .idea를 추가하라는 메시지가 눈에 거슬리네요.

![shot 2015-05-26 3 05 00](https://cloud.githubusercontent.com/assets/4086535/7806172/99108290-03b8-11e5-8adc-87bea1f1415f.png)

PHPStorm을 사용하는 사람이 얼마나 있을지는 모르겠지만.. 그냥 조심스럽게 의견을 던져봅니다.

**Comment by YJSoft** [comment]
:+1:

**Comment by bnu** [comment]
추가할 것이 더 있을까요?

**Comment by wan2land** [comment]
요즘 PHP패키지에서는 composer.phar, composer.lock 두개를 제외하곤 합니다.
XE에서는 composer.lock 파일이 포함되어 있는데, 개발단계와 정확히 같은 버전을 깔아야 할 의도가 있다면 남겨놓아도 상관은 없습니다. :-)
