### ISSUE TITLE
XE 1.8.2 업로드 이상 문제 임시 패치 방법

### ISSUE THREAD

**Issue by wesias7** [xpressengine/xe-core#1499]
위치

/www/classes/context/Context.class.php - _setUploadedArgument 메소드 (1420 Line 부근)

<1.8.2 Codes>

		if($_SERVER['REQUEST_METHOD'] != 'POST' || !$_FILES || stripos($_SERVER['CONTENT_TYPE'], 'multipart/form-data') === FALSE || stripos($_SERVER['HTTP_CONTENT_TYPE'], 'multipart/form-data') === FALSE)
		{
			return;
		}

수정

		if($_SERVER['REQUEST_METHOD'] != 'POST' || !$_FILES || stripos($_SERVER['CONTENT_TYPE'], 'multipart/form-data') === FALSE)
		{
			return;
		}

**Comment by YJSoft** [comment]
@wesias7 
91497fd77bfaa05d9d1e76b187e512a534b647e0
적용후에도 문제가 발생하는 것인가요?

**Comment by bum3144** [comment]
감사합니다. 적용하고 로고파일 업로드 해보니 정상 업로드 됩니다^^

**Comment by bnu** [comment]
fixed #1480
