### ISSUE TITLE
회원 탈퇴시 포인트 DB가 안날아가네요.

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1504]
확인 부탁드립니다.

**Comment by hjhj3686** [comment]
@YJSoft 님이 해결해 주신거 같네요 close 처리합니다.

**Comment by hjhj3686** [comment]
해당 파일에 문제가 있는거 같습니다...

![1](https://cloud.githubusercontent.com/assets/1341628/7838341/487fe72a-04c7-11e5-9291-3c0165951b31.PNG)
![2](https://cloud.githubusercontent.com/assets/1341628/7838342/4b49f43c-04c7-11e5-84bd-9ffce5d0d1b5.PNG)

**Comment by YJSoft** [comment]
@hjhj3686 961d752e883f988a23a186309b66b7d26321f6da 도 수정해주세요

**Comment by hjhj3686** [comment]
@YJSoft 해보았는데요.
탈퇴시에 크롬은 흰 화면이 되고, IE는 프로그래밍 오류가 있다고 하더군요

탈퇴는 되는데 포인트는 안날아가고 그대로 있고요..

**Comment by YJSoft** [comment]
@hjhj3686 하나더 적용해주세요.
자꾸 실수를 하네요 ㅠㅠ

**Comment by hjhj3686** [comment]
@YJSoft 잘됩니다. 감사합니다.
