### ISSUE TITLE
1.8 이상의 버전대에서 관리자화면에 '모듈 업데이트' 안 됨. 

### ISSUE THREAD

**Issue by bexoss** [xpressengine/xe-core#1506]
1.8 이상의 버전대에서 관리자화면에 '모듈 업데이트' 안 됨. 
member, modules, 등의 '모듈 업데이트 하기' 가 관리자 대시보드 화면에서 
클릭해도 계속 떠 있는 현상, 세션 정리, 캐시파일 재생성, 초기화 등을 눌러봐도 
반응이 없습니다. 

1.8.2 버전에서 설치해 보고 테스트 해봤는데 안 되어서 
1.8.1 버전에서도 테스트 해봤습니다만 똑같은 문제가 발생 했습니다. 
브라우저는 Chrome 이며 , 홈페이지에서 xe-core 다운로드 후 로컬에서 압축푼 후 
filezila 로 업로드 했습니다.

**Comment by YJSoft** [comment]
@bexoss `modules/module/module.model.php` 파일의 `getTrigger` 함수중
```php
if($triggers && is_object($triggers))
```
를
```php
if($triggers && is_array($triggers))
```
로 변경해 보시고 없어지는지 확인 부탁드립니다.
