### ISSUE TITLE
1.8.1 이미지 상대경로 에러

### ISSUE THREAD

**Issue by phiDelbak** [xpressengine/xe-core#1510]
[img cond="$module_info->title" src="../img/common/blank.gif" /] 경로 에러

[img src="../img/common/blank.gif" cond="$module_info->title"  /] 에러 없음

이렇게 img src 태그 앞에 비교 조건을 쓰면 에러가 발생합니다.
(단, 문자에 > 이게 들어가는 오브젝트 변수여야합니다.)

**Comment by izuzero** [comment]
```html
<block cond="$module_info->title">
<img src="../img/common/blank.gif" />
</block>
```

이렇게 사용해보세요.

**Comment by phiDelbak** [comment]
답변 감사합니다.
그런대 굳이 그렇게 안해도 위에 말했듯 src 뒤에 cond(조건문)을 쓰면 됩니다. :)

저는 버그를 말씀드린건데 ㅎㅎ;;
이거 xe1.4~5 때즘이였나? 그때도 있던적이 있던 오래된 버그였는데 
예전에 이슈 등록해 고쳐진적이 있던거 같은데... 기분탓인가...

아무튼... 모르고 쓰면 문제가 있을것 같아 제보했습니다.
항상 수고해 주셔서 감사합니다.

**Comment by bnu** [comment]
`>`로 이미지 태그의 종료점을 찾기 때문입니다.
고쳐야지~ 했다가 잊고 있었던 버그네요..^^;

**Comment by bnu** [comment]
@phiDelbak f6a538a 의 변경사항을 적용하여 확인해주시면 감사하겠습니다. :)

**Comment by phiDelbak** [comment]
일단 앞, 뒤는 고쳐졌어요.  :)
하지만 다음 2가지 경우에 src 에러가 발생합니다.

1. [img class="tmp_class" cond="!$module_info->title" src="../img/common/blank.gif" /]
2. [img cond="$mi->title" class="tmp_class"|cond="$mi->use" src="../img/common/blank.gif" /]

1. cond 가 중간에 있는경우
2. |cond= 하나더 사용한 경우 (1. cond 가 중간에 있는경우 때문인거 같음)

**Comment by bnu** [comment]
@phiDelbak 추가 보완해봤습니다. :)

**Comment by bnu** [comment]
추가 보완해야 할 사항이 없으면 이슈 닫겠습니다.

**Comment by phiDelbak** [comment]
다 잘 되는거 같습니다.
닫으셔도될거 같아요. 수고하셨습니다^^
