### ISSUE TITLE
포인트에 따른 그룹연동 문제

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1511]
저는 코어의 아래 기능을 통해
![2015-05-30 6 58 20](https://cloud.githubusercontent.com/assets/6075830/7896711/dda3eea4-06fd-11e5-83ea-535d00a7a0d5.png)

특정 포인트에 그룹을 연동 시켜놓았습니다. 
근데 제가 이해를 잘못하고 있는건지 이해를 구하고자 글타래를 열어봅니다.

예를 들어 가입직후의 회원의 group name 이 "default" 라면
10 포인트 이후 group name은 "new group" 으로 설정 해놓은 상태입니다.

저는 10포인트 이상 득한 회원들은 그룹명이 new group 될줄 알았으나

default, newgroup 이렇게 두가지 그룹에 속하여 있습니다.

그냥 new group이 되어야 하는게 맞지 않나요?
--

**Comment by mactopia** [comment]
혹시 오른쪽에 설정된 그룹 초기화 후 새 그룹 부여 라는 설정으로 바꾸면 될까요?
괜히 섣불리 건드렸다가 회원 그룹 다 틀어질까봐 건들지 못하고 있습니다...덜덜..

**Comment by hjhj3686** [comment]
그룹 초기화 후 새 그룹 부여가 맞을 겁니다.

그러면 default 없어진 다음에 new group 으로 지정이 되겠죠

그리고 질문은 XE 포럼 문답에다가 올려주세요
