### ISSUE TITLE
자동설치후 upload failed 에러

### ISSUE THREAD

**Issue by missol** [xpressengine/xe-core#1512]
xe 1.8.2 자동설치후 각 레이아웃의 이미지 업로드가 에러납니다.

contact us 자동 설치시 xe 버전이 자동 1.8.2로 되며 여전히 upload failed구요..

**Comment by YJSoft** [comment]
https://www.xpressengine.com/index.php?mid=download&package_id=18325662&release_id=22755020

# 알려진 문제
#1480 레이아웃 설정 기능 등에서 파일을 업로드할 수 없는 문제
https://github.com/xpressengine/xe-core/issues/1480
위 주소를 참고하여 ./classes/context.class.php 파일을 수정하여 해결할 수 있습니다.

**Comment by bnu** [comment]
dup fixed #1480
