### ISSUE TITLE
관리자의 비밀번호 변경시 비밀번호 보안수준에 상관없이 무조건 통과하는 문제

### ISSUE THREAD

**Issue by jdssem** [xpressengine/xe-core#1517]
오류는 아니지만 ```member.model.php```를 보면

```
function checkPasswordStrength($password, $strength)
	{
		$logged_info = Context::get('logged_info');
		if($logged_info->is_admin == 'Y') return true;
```

위와 같이 사이트 관리자일 경우 비밀번호 보안수준을 무조건 통과하도록 하고 있습니다. 이것이 관리자를 위한 편의인지는 모르겠으나 관리자가 파일 업로드 용량 제한이나 기타 제한을 뛰어넘는 것과는 별개로 비밀번호만큼은 오히려 보안 수준을 지키는 것이 더 바람직하지 않을까 생각합니다.

물론 ruleset에서 4~20자로 제한하고 있기는 하지만 임의의 POST 요청으로 전송하니 1자리 비밀번호도 가능하더라고요.

**Comment by kijin** [comment]
관리자 자신의 비밀번호를 지정하는 경우보다는, 관리자가 관리 모듈을 통해 다른 회원의 비밀번호를 변경해 주는 경우를 고려한 기능인 것 같습니다. 예를 들어 특수문자가 포함된 비번 사용을 어려워하는 노인 회원이 있다면 관리자가 그 회원만 특별히 쉬운 비번으로 바꿔줄 수 있는 거죠.

만약 관리자 자신에게 보안수준이 적용되도록 조치한다 해도, 관리모듈에 가서 보안수준 설정을 잠깐 바꿨다가 원래대로 돌려놓으면 그만입니다. 관리자는 클릭 몇 번만으로 사이트 전체를 폭파해 버릴 수도 있는 막강한 권한의 소유자이니까, 비번 보안수준 정도는 스스로 지켜주기를 기대하는 수밖에요. 게다가 룰셋조차 우회할 정도의 정성이면 차라리 DB를 직접 수정하고 말죠 ㅋㅋ

그러나 저 조건이 저 메소드 내에 붙어있는 것이 좀 이상하긴 하네요. 특별히 어떤 경우에 예외를 부여하고 싶다면 `MemberController` 클래스의 `insertMember()`, `updateMember()` 등에서 처리하는 것이 더 자연스러울 것 같습니다. 예외조건을 충족한다면 아예 `checkPasswordStrength()` 메소드를 호출할 필요도 없을 테니까요.

**Comment by jdssem** [comment]
@kijin 그런 경우라면 이해가 되는군요ㅎ 그럼 이 이슈는 일단 닫아두도록 하겠습니다!
