### ISSUE TITLE
그룹 아이콘은 한번 등록했다가 취소를 못합니다.

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1518]
그룹에 연동시킨 그룹 아이콘을 삭제할려면 해당 그룹을 삭제하고 처음 부터 다시 생성해야 합니다.

**Comment by qw5414** [comment]
https://github.com/xpressengine/xe-core/issues/574

**Comment by YJSoft** [comment]
#1520

**Comment by mactopia** [comment]
@YJSoft 님 감사합니다. 잘 적용 하였습니다.
