### ISSUE TITLE
잘못된 다국어 조합

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1523]
![image](https://cloud.githubusercontent.com/assets/5893514/7988466/9081d4c2-0b1e-11e5-93f1-6639865094ac.png)
`{$lang->cmd_document_do} {$lang->confirm_delete}`

위 구문이 한국어 상태에서는 `이 게시물을 삭제하시겠습니까?`로 정상적으로 조합되지만 영어 상태에서는 `I want to Are you sure you want to delete?` 라고, 굉장히 어색하게 조합됩니다.
이는 cmd_document_do가 게시물 메뉴에도 사용되기 때문으로, 한국어 번역이 `이 게시물을` 인 반면 영어는 `I want to` 라는, document가 전혀 들어가지 않은 string이기 때문에 발생합니다. 

https://www.xpressengine.com/qna/23013169

**Comment by kijin** [comment]
저도 모듈을 개발하다 보니 언어마다 어순이 다른 경우가 상당히 불편하더군요. 한국어와 영어만 사용해도 이렇게 되는데, 다른 언어들은 어떨지 상상이 가지 않습니다 ㅠㅠ

간단한 것은 별도의 문자열로 분리해 내는 방식으로 해결할 수 있겠지만, 좀더 유연하게 사용할 수 있도록 번역문에 `%s` 이렇게 빈 칸을 남겨둔 후 `this document`, `this comment` 등으로 치환할 수 있으면 좋겠습니다. 널리 사용되는 `sprintf()` 구문을 활용한다면 못할 것도 없지요.

**Comment by YJSoft** [comment]
@kijin 그냥 `%s`만 써서는 단어 순서 변경시 곤란해질 수 있습니다.
예를 들어 문서 삭제 string의 경우 한국어는 이 __문서__를 _삭제_하시겠습니까?` 인 반면 영어로는 Are you sure to _delete_ this __document__ 로 반대가 될 수 있죠.

다행히도 sprintf에서 `%1$s` 나 `%2$s` 처럼 순서 변경을 지원하니 이왕 sprintf로 바꾼다면 이렇게 지정해서 바꾸는 것도 좋을 것 같습니다.

**Comment by kijin** [comment]
@YJSoft 확인해 보니 이미 일부 모듈에서는 `%s` 형태로 변수를 삽입하여 쓰고 있네요. 직접 `sprintf`해줘야 한다는 단점이 있지만... (예: `member.controller.php`에서 `sprint`를 검색해 보세요.)

**Comment by bnu** [comment]
fixed #1571
