### ISSUE TITLE
도움말에서 APMSETUP 제거

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1524]
다음은 APMSETUP의 최신 버전인 7 버전의 사양입니다.

```
Apache 2.2.14 (openssl 0.9.8k) [ http://httpd.apache.org ]
    - Server\Apache
    - mod_log_rotate 1.00a
    - mod_security 2.5.10

PHP 5.2.12 [ http://kr.php.net / http://windows.php.net/ ]
    - Server\PHP5

Zend Optimizer v3.3.3 [ http://www.zend.com ]
    - Server\ZendOptimizer

MySQL 5.1.39 [ http://www.mysql.com ]
    - Server\MySQL5

phpMyAdmin 3.2.3 [ http://www.phpmyadmin.net ]
    - Server\phpMyAdmin

CUBRID  [ http://www.cubrid.com ] , JRE  [ http://java.sun.com ]
```

XE 1.8을 설치하기에는 PHP 버전이 낮습니다. APMSETUP은 지난 2010년 1월  버전 7 릴리즈 이후 업데이트가 되지 않는 프로그램으로, 추후 업데이트를 기대하는 것은 힘들기에 삭제하는 것이 좋다고 봅니다.

**Comment by kijin** [comment]
APMSETUP을 설치한 후 PHP만 별도로 업그레이드하는 꼼수가 있긴 하죠.

그러나 2015년 현재는 [XAMPP](https://www.apachefriends.org/)나 [오토셋](http://autoset.net/xe/)을 추천하는 것이 낫겠습니다. 특히 오토셋은 한글화도 잘 되어 있고 공식 홈페이지도 XE로 운영하고 있네요. (XE 버전이 상당히 오래되긴 했지만 ㅠ)
