### ISSUE TITLE
xe코어1.8.2 설치 후 썸네일 등록/수정이 되지 않습니다.

### ISSUE THREAD

**Issue by choi6157** [xpressengine/xe-core#1527]
수고하십니다. 누리고 쇼핑몰 사용하던중..
코어 1.82 최신버전 업데이트를 하면 상품 썸네일 저장/수정이 되지않고 있습니다. 

누리고에 문제는 아닌듯하여 이곳에 이슈등록합니다.
다시 1.82 이하로 다운그레이드 하고 나니 다시 정상 작동됩니다.
몇번씩 반복 테스트 후 1.8.2만 설치 후 나타나는 현상인듯합니다.
코어 최신버전에서 사용할 수 있게 검토를 부탁드립니다.  감사합니다. 

※ 상품관리 > 디지털콘텐츠 / 쇼핑몰 일반상품 2곳 모두 같은 현상입니다. 캐시파일 재생성 등 기본 조치는 취했습니다.

**Comment by YJSoft** [comment]
https://www.xpressengine.com/index.php?mid=download&package_id=18325662&release_id=22755020

# 알려진 문제
#1480 레이아웃 설정 기능 등에서 파일을 업로드할 수 없는 문제
https://github.com/xpressengine/xe-core/commit/91497fd77bfaa05d9d1e76b187e512a534b647e0
위 주소를 참고하여 ./classes/context.class.php 파일을 수정하여 해결할 수 있습니다.

**Comment by choi6157** [comment]
감사합니다. ^^

**Comment by bnu** [comment]
dup #1480
