### ISSUE TITLE
1.8.3 업데이트중 TemplateHandler.class 관련 에러

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1531]
changes만 받아서 업데이트 하고 있는데 classes 의 TemplateHandler.class 만 replace하면 메인 위젯 페이지가 백지가 됩니다..흠... 혹시 더 증상이 필요하시면 말씀 주시면 해보겠습니다. 조언좀 주시면 고맙겠습니다.

**Comment by mactopia** [comment]
메인 페이지 만이 아니라 사이트 헤더 풋터 제외하고 모두 백지가 되네요.

**Comment by bnu** [comment]
증상을 확인할 수 있는 사이트 URL, PHP 버전을 알려주세요.

**Comment by mactopia** [comment]
증상 확인할려면...다시 백지로 만들어야 하는디.... 시간대를 맞출수가 있을까요.... 어떻게해 해야 할지..
일단 닷홈에서 php 5.5로 업데이트 해준다고 하니 해보고 다시 말씀 드려볼게요

**Comment by mactopia** [comment]
bnu 님 5.5 로 업데이트 하니 증상이 사라졌습니다. 감사합니다.
