### ISSUE TITLE
CK Editor 메뉴부분

### ISSUE THREAD

**Issue by yeoreume** [xpressengine/xe-core#1532]
http://i.imgur.com/gQpl1Km.jpg
사이트 언어를 영어로해도 한글로 나와요.

소스 본문 글꼴 크기

+

첨부파일 부분도..

**Comment by YJSoft** [comment]
@yeoreume 첨부파일 부분은 #1494 에서 진행중입니다.

CKEditor의 언어는 `/common/js/plugins/ckeditor/ckeditor/ckeditor.js` 파일을 다음 내용으로 생성하여 변경하실 수 있습니다.
```javascript
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	config.language = 'en';
};
```
