### ISSUE TITLE
XE 1.8.3  회원가입폼에서 "사용자 정의 항목 추가" 버튼 클릭시 팝업창 활성화 안됨

### ISSUE THREAD

**Issue by sswan7** [xpressengine/xe-core#1538]
XE 1.8.3 신규설치후 관리자모드 회원>회원설정>회원가입폼에 들어가서 
사용자 정의 항목을 추가하려고 해당 버튼을 클릭하면 
모달창 캍은 것이 팝업으로 뜨는것 같은데 반투명 상태, 비활성 상태로  떠서 
추가작업을 할 수가 없는 현상이 발생합니다.

**Comment by YJSoft** [comment]
@sswan7 사용중이신 운영체제 버전과 브라우저 버전을 알려주세요.

**Comment by sswan7** [comment]
리눅스 / php 5.6.9 / mysqli / 아이네임즈 웹호스팅 / IE 11, 구글크롬에서도 동일한 현상입니다.
전체화면이 반투명상태로 바뀌면서 모달창이 뜬거 같긴 한대 (창닫기 X표시는 보임)
설정할수 있는 input 박스 같은 건 전혀 안보여요.
질답게시판에 이미지를 올려놓을께요.
감사합니다.

**Comment by sswan7** [comment]
XE 설치후 기능 작동여부를 점검하다 보니 
먼저 언급한 현상 말고도 안되는 부분들이 몇군데 발견되었습니다.

MessageXE 개발자이신 누리고님께서 디버깅을 통해 오류원인을 알려주셔서 
유추해 본 바로는 PHP5.6.* 버전과 관련 있는 것 같습니다.

PHP5.5.* 에서 PHP5.6.* 로 오면서 
$HTTP_RAW_POST_DATA  변수 제거와 관련하여 
php.net 에 버그리포트와 php.ini 를 수정하여 fix하는 방법도 올라와 있습니다.

https://bugs.php.net/bug.php?id=66763
https://github.com/piwik/piwik/issues/6465

호스팅사에 php.ini 수정을 요청해 놓은 상태이며 오류가 잡히면 
그때 게시판에 정보를 공유하도록 하겠습니다.

**Comment by YJSoft** [comment]
@sswan7 해당 문제는 2579042e4c7bb89505dbf8ff115851355275b172 , 80ab9dffcd4269d56582fe2e8b80e758c994af9d , f4d4c3218d286cae95f35cf73c7c46b8b2406823 3개 커밋으로 수정된 상태입니다. [이 링크](https://github.com/xpressengine/xe-core/compare/91f1396f127384993d569acc730b1ff19c31a66b...f4d4c3218d286cae95f35cf73c7c46b8b2406823) 에서 변경 사항을 한번에 볼 수 있습니다.

`$GLOBALS['HTTP_RAW_POST_DATA']` 가 설정되어 있지 않고 PHP 버전이 5.6 이상이라면 `file_get_contents('php://input');`으로 대신 내용을 채웁니다.

php.ini를 수정하는 방법은 웹 호스팅 환경에서는 곤란하기에(변경을 해주지 않을 수도 있죠) 다른 해결책도 찾아야 할 것 같습니다.

**Comment by sswan7** [comment]
아! 우회해결책을 사용하지 않도록 정공법으로 코어에 이미 반영하셨군요.
그런데 페이지 곳곳에서 다음과 같은 오류메세지를 내뿜는 것은 다른 원인이 있을까요?
XE1.8.3 신규설치 순정판인데도 그러네요.

The result is not valid JSON : (JSON뿐만 아니라 XML도 동일)
-------------------------------------------------------------------------------------
Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
Warning:  Cannot modify header information - headers already sent in Unknown on line 0

아무래도 PHP5.5.* 버전대로 낮추어야 할지 고민되네요. 그렇게 해줄지도 모르겠고요.
감사합니다.

**Comment by YJSoft** [comment]
@sswan7 XE는 이미 `php://input`를 사용하도록 패치되었으나 호스팅사 php.ini 설정에서 하위 호환을 위해 설정해둔 것이 원인입니다. 해당 부분만 변경해 주시면 됩니다.

**Comment by sswan7** [comment]
정말 감사합니다.
덕분에 해결하였습니다.
다행히 호스팅사에서 php.ini  / always_populate_raw_post_data 값을 -1 로 변경해 주었습니다.
다시 한번 진심으로 감사를 드립니다.
