### ISSUE TITLE
모바일 스킨에 확장변수 url형식 사용시 a tag 가 계속 붙는 형상

### ISSUE THREAD

**Issue by phiDelbak** [xpressengine/xe-core#1540]
기본 게시판으로 설명드릴게요.
![003](https://cloud.githubusercontent.com/assets/12091900/8123387/49cd8054-1103-11e5-916b-d076a05eee41.PNG)

modules/board/m.skins/default/_list.html
파일을 열어 확장변수 출력 코드를 넣습니다.
![002](https://cloud.githubusercontent.com/assets/12091900/8123239/bfc8a9da-1100-11e5-927e-fc8d9c96a5c5.PNG)

그려면 아래 그림 처럼 a tag 가 붙습니다.
![001](https://cloud.githubusercontent.com/assets/12091900/8123237/ba4a4644-1100-11e5-9392-c7615a700822.PNG)

**Comment by misol** [comment]
getValue"HTML" 이니까요..

**Comment by phiDelbak** [comment]
아 죄송해요.
착각했어요.
a tag안에 a tag가 들어가서 그렇군요
