### ISSUE TITLE
XE위키 모듈로 글을 썼을때 코어부분에서 오류를 뿜습니다.

### ISSUE THREAD

**Issue by owlo11** [xpressengine/xe-core#1548]
Fatal error: Cannot redeclare class HTMLPurifier_Bootstrap in /host/home2/계정명/html/classes/security/htmlpurifier/library/HTMLPurifier/Bootstrap.php on line 31

오류를 뿜는 부분은 전혀 모듈 부분이 아닌데 왜 이럴까요?

**Comment by YJSoft** [comment]
@owlo11 위키 모듈 저장소는 따로 있습니다. https://github.com/xpressengine/xe-module-wiki 이곳에 올려 주세요. 해당 부분은 코어에 HTMLPurifier가 이미 포함되어 있음에도 위키 모듈에서 따로 불러와서 발생하는 문제입니다.
