### ISSUE TITLE
1.8.3 oops! 통합검색을 사용할수 없습니다.

### ISSUE THREAD

**Issue by missol** [xpressengine/xe-core#1552]
1.8.3에서 통합검색시 통합검색을 할수 없습니다라는 메세지와 함께 로그인화면이 뜹니다.

**Comment by YJSoft** [comment]
#1551 
통합검색 모듈의 설정에서 에서 검색 대상 모듈을 선택하셔야 합니다.
해당 메세지는 검색 대상을 선택하지 않았을 때 표시하는 의도된 메시지 입니다.

@missol

**Comment by hjhj3686** [comment]
이부분은 좀더 명확하게 오류메세지에 모듈에서 검색대상을 지정하라는 안내 메세지가 필요하지 않을까요?

**Comment by YJSoft** [comment]
@hjhj3686 829c1c20ddf33cb566471face1b8b014974648d3 원래는 관리자에게는 `통합 검색을 사용할 수 없습니다. 통합검색 설정에서 대상 모듈을 선택하세요.` 라고 표시했으나 2b8954cb96473155614f085a1adb96f4e05d087d 에서 제거되었습니다. @bnu

**Comment by missol** [comment]
@YJSoft 
네 그렇군요. 감사합니다.

**Comment by misol** [comment]
밋솔님이라고 읽어야 하나요?-? 반가워요!

**Comment by missol** [comment]
@misol 안녕하세요. misol님을 의식해서 s을 하나 더 넣었습니다. ^^ 
미쏠이라고 지인들이 제 닉을 쎄게 부를때입니다.
