### ISSUE TITLE
HHVM 환경에서 XE 구동 시의 문제

### ISSUE THREAD

**Issue by Shavakan** [xpressengine/xe-core#1556]
안녕하세요.

HHVM 환경에서 XE를 구동해 Install을 시도하면 다음 에러가 발생합니다:
\nFatal error: $this is null in /home/ubuntu/xe-core/classes/db/DB.class.php on line 247
이것은 XE에서 non-static method들을 static하게 reference하고 있기 때문으로 보입니다.

(HHVM 환경은 HHVM Documentation에 나와있는대로 nginx를 사용하지 않았고,
Apache2를 사용하여 설정하였으며 그 방법은 https://gist.github.com/Shavakan/53f34dbfa3d53f994328 에 남겨두었습니다.)

"\nFatal error: $this is null" 에러 메시지를 해결하는 방법은 다소 지저분하지만 간단한데,
함수의 인자로 함수가 실행되는 scope의 $this를 넘겨주면 됩니다.

제가 파악한 바로는 Install module에서 getEnableList(), getDisableList() 두 함수를 사용하는데,
예시로 이 함수들에 대한 대응을 적용해보았습니다.
이대로 코드를 수정하면 HHVM에서 XE Installation 페이지가 나타나도록은 할 수 있습니다.
(https://github.com/Shavakan/xe-core/commit/de1b5b3c8aa6da91564176eface49043a5f3ae68)

해결하지 못한 문제로 설치를 진행하다 DB 설정을 시도하려 submit 버튼을 클릭하면 HHVM 환경에서는 Page Not Found 에러가 발생하는 경우가 남아있는데, 아직까지 원인을 파악하지 못하였습니다.

또 모든 $this 용법이 비슷한 문제를 발생시키지는 않겠지만 적어도 검토는 되어야할 것으로 생각하는데,
xe-core 프로젝트 경로 전체에 대하여 $this의 사용례를 검색해보면 (grep -r '$this->' xe-core/ >> grep_result) 약 24,800여 건에 달해 실질적으로 HHVM 환경에서 XE를 구동시킬 수 있을지 의문이 듭니다.

메인테이너 분들은 어떻게 생각하시는지 의견을 여쭙고 싶습니다.

**Comment by kijin** [comment]
그냥 `$oDB->_getSupportedList()`를 직접 사용하도록 변경하면 훨씬 간단할 것 같습니다.

안 그래도 PHP 4.x 시절에 작성된 클래스들은 static으로 호출하는 메소드와 그렇지 않은 메소드의 구분이 애매한 경우가 많은데, #1260 덕분에 일부 개선될 것 같긴 합니다.
