### ISSUE TITLE
php7에서 오류

### ISSUE THREAD

**Issue by delphixe4** [xpressengine/xe-core#1558]
코어 1.8.2, 1.8.3입니다.

php7 alpha 1을 사용해봤는데, 사이트 메뉴 편집이 작동하지 않는 문제가 있고
1.8.2에서 1.8.3으로 쉬운설치 업데이트가 불가했습니다.

혹시 php7 개발버전에 대해서 대응하지 않으신다면 닫아주시면 감사하겠습니다.

**Comment by YJSoft** [comment]
#1556 함수 static 호출 관련 문제 같습니다.
아무래도 PHP7에서 검사를 strict하게 하면서 문제가 생기는것 같네요.
