### ISSUE TITLE
CKEditor - Code Highlighter bug?

### ISSUE THREAD

**Issue by usna-ansu1** [xpressengine/xe-core#1560]
![341d7f162aaa94f5e4da6372bd757199](https://cloud.githubusercontent.com/assets/13005704/8290303/22174e70-195d-11e5-93e7-1ffffcc83059.png)
의미없는 스크롤이 발생

![b4a682e585708c61611bce7888e6c611](https://cloud.githubusercontent.com/assets/13005704/8290317/40d7e2de-195d-11e5-9fa3-dcb25c086f45.png)
하단 하이퍼링크.. & 등록 부분이 버튼 처리되지 않음

**Comment by YJSoft** [comment]
@usna-ansu1 코드 하이라이터 저장소는 따로 있습니다. 이곳 말고 https://github.com/xe-public/code_highlighter 에 올려주세요.
