### ISSUE TITLE
타사이트에서 /favicon.ico 를 무조건 파비콘으로 긁어갈때 생기는 문제

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1563]
타 사이트 리피러 (구글, 티스토리 등) 파비콘을 무조건 xe설치 경로 최상단에 있는

favicon.ico 로 받아가서 파비콘을 정상적으로 받아가지 못합니다.

해당파일을 수동으로 따로 추가하지 않으면 뜨지 않고 수동으로 파일을 넣어주면 타사이트에서도 보여지지만 개선이 필요합니다.

**Comment by YJSoft** [comment]
파비콘은 보통 자주 바꾸지 않는 것으로, 직접 루트에도 파비콘을 업로드하시는것을 추천드립니다.
XE에서 루트에 업로드할 수도 있으나, 루트 폴더에 쓰기 권한이 없을수 있으므로 기본 적용은 힘듭니다.

**Comment by hjhj3686** [comment]
혹시 모르니 이슈만 열어둘께요 근데 그렇게 심각한건 아니긴해요 ㅎㅎ;

일부사이트들이 외부사이트의 파비콘을 표시할때 무조건 저걸 긁어가서 일어나는 현상이거든요 -.-

**Comment by upgle** [comment]
이건 XE에서도 파비콘 업로드할때 같이 치환해주는게 좋지 않을까요?
권한문제가 걸리긴 하네요 ㅎㅎ..
