### ISSUE TITLE
템플릿 문법내 {@ ... }에서 $_SESSION, $globals 변수를 사용 할 수 없음

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#1564]
템플릿 문법 내에서 $_SESSION, $GLOBALS, $_POST, $_GET 변수 등을 사용 할 수 없는 버가 있습니다...

{@ var_dump(is_null($_SESSION)); } => true로 출력하네요.

현재로는 아래 형태로 사용하면 우회(?)해서 사용 가능하긴 합니다.

```
<?php
Context::set('temp_session_var_name', $_SESSION['something']);
?>
<div>
{$temp_session_var_name}
</div>
```

**Comment by YJSoft** [comment]
```
{@ echo $_SESSION['something']; }
```
혹은
```
{@ $something =  $_SESSION['something']; }
{$something}
```
{} 안에 들어가는 모든 변수는 컴파일시 $__Context->변수 로 바뀝니다. 그냥 사용하면 $__Context->_SESSION이 될테니 null로 뜨겠죠.

그리고 `$_POST['변수']`나 `$_GET['변수']`처럼 Context::get으로 가져올 수 있는 변수는 별도의 작업 없이 모두 {$변수} 처럼 사용 가능합니다.(정확히는 `$_REQUEST`의 모든 변수입니다)

**Comment by ForPeople** [comment]
보안 이슈때문에 일부러 막은것 아닌가요? 사용할 수 있는 방법이 있는것 자체가 잘못된덧 아닌가요?

**Comment by YJSoft** [comment]
@ForPeople 글쎄요. 세션변수나 GLOBAL 변수를 사용 가능하다 해서 보안 취약점이라는 생각이 들지는 않습니다.
해당 부분 편집이 가능하려면 관리자 권한이 있거나, FTP 권한 등이 노출된 경우인데, 마음만 먹으면
```
{@
print_r(Context::getDBInfo());
}
```
로 DB 정보를 출력해 버릴수도 있습니다. 즉, 세션변수 사용을 막는다고 보안이 강화된다던가 하는 것은 아니라는 것이죠. 물론 $_SESSION[사용자입력아이디]; 이런 것을 출력하는 거라면 문제가 있겠지만요.
