### ISSUE TITLE
XEDITION 레이아웃 반응형화

### ISSUE THREAD

**Issue by dlehdanakf** [xpressengine/xe-core#1567]
반응형

**Comment by bnnu** [comment]
이미 XEDITION 레이아웃은 배포된 레이아웃입니다. 이를 변경하는 것보다는 XEDITION_responsive 등으로 변경해서 배포했어야 한다고 생각합니다. https://www.xpressengine.com/qna/23055769 등 HTML 편집을 사용해 XEDITION 레이아웃을 변경하여 사용한 경우 업데이트 이후 오류가 발생합니다. 이에 대한 안내가 있었나요? 동일 이름으로 구조를 그냥 바꾸는 것은 무책임한 일이라 생각합니다.

요즘들어 XE 배포판의 품질이 많이 떨어지고 있는데, 이러한 세세한 점이라 해도 무시하여서는 안되겠습니다.

**Comment by bnu** [comment]
@bnnu 해당 내용은 릴리즈 노트에 포함되어 있습니다.
