### ISSUE TITLE
xe 1.8.3 위젯페이지 "내용직접추가하기"기능 에러

### ISSUE THREAD

**Issue by fotolife** [xpressengine/xe-core#1569]
위젯 페이지에 "내용직접 추가하기" 기능을 사용하여 문서를 작성할 경우 저장되지 않습니다. 
빠른시일내에 에러가 수정 되었으면 좋겠네요.

**Comment by YJSoft** [comment]
![image](https://www.xpressengine.com/files/attach/images/19778968/479/029/023/cd3796d63e869aa9b07491058142b844.gif)
1.8.3 기준 정상 동작합니다. 서드파티 자료와의 충돌일 수 있습니다. 관리자 페이지-서버정보보기의 정보를 올려 주세요.

**Comment by fotolife** [comment]
빠른 답변 감사합니다.  서버정보 올립니다 

[XE Server Environment 2015-06-25]

realpath : /home/xe_fotolife/www
location : ko
package : XE
host : http://www.fotolife.co.kr/
app : Apache/2.2.20 (Unix) mod_ssl/2.2.20 OpenSSL/0.9.8e-fips-rhel5 DAV/2 PHP/5.6.7
xe_version : 1.8.3
php : 5.6.7
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, curl, dba, fileinfo, ftp, gd, gettext, iconv, mbstring, mcrypt, mysql, mysqli, pdo_sqlite, phar, simplexml, soap, sockets, exif, xml, xmlreader, xmlwriter
module : ad(0.5.2), adminlogging(1.7), analytics(1.0.0), androidpushapp(1.5), apporix(1.0), attendance(5.0.5), authentication(3.1.2), automail(0.1), bannermgm(0.1), blogshop(1.1), board(1.7.2), board_extend(1.1), boardauction(0.1.1), bulkmsg(1.0), cashpay(1.0), contact(1.7.0.2), coupon(1.0), currency(1.0), cympusadmin(1.3), epay(2.2), exam(0.8), faq(1.7.0.1), forum(1.7.0.1), gdata(0.5), ggmailing(0.3.9), guestbook(1.7.0.1), homepage(1.7.0.1), iconshop(0.4), imageprocess(1.3.0.3), inipay(1.2), inipaymobile(1.0), isx(1.7.3.1), join_extend(0.5.3.4), kcp(1.1), keywordstatistics(0.3), kin(1.7.0), krzip(1.8.0), license(1.2.1), lisense(0.1), loginlog(0.5.1), lottery(0.1), lunar(0.1.1), mail_m9(0.1), mailing_free(0.2.1), maps(1.1.1), marketplace(1.3), material(1.0), minishop(1.3), money(0.1), moneyhistory(1.0), ncart(1.7), ncenterlite(2.1.3), newposts(2.2.1), nmileage(1.5.4), nproduct(1.7), nstore(2.2), nstore_digital(1.9), nstore_digital_contents(1.1), pado_ajax_newsModule(1.5), paynoty(1.1), paypal(1.0), plusad(0.5), pointhistory(0.1.4), pointsend(1.2.5.1), popup(1.5.4.3), portalpoint(1.2), profiler(1.0), quizgame(0.1), realnotice(0.5), referer(3.8.2), referer2(2.1.1), resource(1.7.0), rockgame(0.4), sejin7940_comment(1.5), sejin7940_vote(1.3), sitemap(1.2), sms(1.3.10), smsontextyle(1.0.1), socialxe(0.1.4), socialxeserver(1.0.11), stats(1.1.1), store_review(0.2), store_search(0.9), syndication(4.0), tccommentnotify(1.1.0), textmessage(2.3), textyle(1.7.0), upgletyle(0.1.4), user_finder(0.1), wiki(1.7.0.1), zzz_menu_new(1.7.0)
addon : aa_add_vote_list(1.0.1), aa_insert_ad(1.0.0), add_document(0.1.1), addon_insert_video(0.1), adminlogging(1.7), apporix(1.1), apporix_native_alert(0.1), bootstrap_icon(1.1), captcha_member(1.7), counter_ex(1.1.0), division(1.0), exif(0.9.2.2), facebook_social(0.1), font_nanum_gothic(1.0), iframe_resize(0.2), keywordstatistics(0.1), langfilter(0.7), level_permit(0.1), login_2sisstore(1.0.1), lua_hashtag(0.0.1), member_icon_print(0.3), member_join_ex(0.2.3), member_pointsend(0.2.1), meta_add(0.2.2), multimedia_thumbnail(2.0.0), naver_analytics(1.2), new_document_notify(2.0), noclick(1.3), oembed(1.0), point_pang_pang(1.1), point_pangpang_plus(0.2b), poll_point(0.2), popup_opener(1.5.4.3), pushwing(0.5), pushwing_comment(0.5), radarURL(1.2), referer2(2.1.1), scmplayer(1.5), sejin7940_mobile_resize(1.0), sejin7940_mustlogin(0.2), showindow(0.4), socialxe_helper(1.0.6), soo_add_content(0.5), soo_mcrblog_link(1.2.14), soo_parking(0.3a), stats(1.1), stoptrackback(0.3), sxe_now_connected(0.2), sxe_writing_format(0.2), to_sns(0.2.1), today_fortune(1.0.1), trolley(0.3), xdt_google_analytics(1.1), youtube_control(1.3)
layout : flat_series(1.0.22), phizRWDThemes(1.2), simplestrap(1.4.2), sketchbook5(1.6.3.6), the_bootstrap(3.5.1.2), Treasurej_Lifestyle(1.1), xe_cafe_site(1.7.0), cafeXE(1.7.0), xe_cafe_hub(1.7.0), xe_cafe(1.7.0), xe_official(1.7), xedition(1.8), xe_kimtajo_layout(1.20), daerew_v4_layout(1.2), webbuilder_layout(1.0.3), qookrabbit(1.9.8), user_layout(1.7), hankooktown2(1.2.2)
widget : analytics_flash_counter(0.1), attendance_check(1.6.2), bannermgm_widget(0.2), browserWidget(0.2), calendar_plannerXE123(4.3.0), cameronImage(1.0), cameronIntro(1.0), cameronListOne(1.0), cameronNewsTicker(1.0), cameronSlider(1.0.2), cameronWebzine(1.0.1), category(0.1), category_menu(1.2), content_specificdoc(0.2), contentextended(2.43), contentsmedia(0.7), counter_status(1.7), cute_clock(1.0), ddayWidget(0.4), eh_whcarousel(0.4), facebook(0.1), fixedNotice(0.6), flowing_pictures(1.1.7), frontdisplay(1.0), gallery_layout_widget(1.0.0), ggboardmailing_widget(0.2), hb_bank(0.1), hitsearch(0.2), ideationBanner(0.1), ideationPopular(0.1), lineadWidget(0.8), logged_members(0.1), maps_widget(1.1.2), member_group(0.1), module_point(0.1), navigator(1.7.0), newest_document(1.0), newest_document_tab(0.2), opageWidget(1.0), padoLittleBanner(0.1), pado_ajax_newsWidget(1.9), pado_board_rankingWidget(1.1), pado_image_news(0.3), picasa_recent_images(0.1), plusadWidget(0.6), (), rank_attendance(0.8.1), rank_count(1.5), sejin7940_calendar(1.0), site_info(1.7.0), sitemap(0.1.0), socialxe_comment(1.0.8), socialxe_info(1.0.6), splanner(0.3.0), (), tag_list(0.1), talkbox(0.2), talkshow(3.1), treasurej_popular(1.0.5), twitter(0.2), twitter_follow(1.0), webzine(0.1), xeBanner(0.1), xegallery(0.3), xestream(0.1)
widgetstyle : CN_No_series(1.1), admin_ws(0.2), eond_doubleline(0.1), eond_webzine(0.1), garden_islide(1.0), nico(1.2), sctb(6.0), simple(1.7), sketchbook5_wincomi(3.0), xe_official(1.0)
max_file_uploads : 20
post_max_size : 20M
memory_limit : 128M

**Comment by qw5414** [comment]
혹시 document.controller.php 파일을 수정한 기억이 잇으신지요?
