### ISSUE TITLE
xe 1.8.3 에디터 기능 보완

### ISSUE THREAD

**Issue by fotolife** [xpressengine/xe-core#1570]
XE 1.8.3 에디터에서  문서를 작성할 경우 "등록"버턴을 누른 후 "돌아가기" 버턴을 눌러야 저장되는데 이를 이전 버전처럼 하나로 통합 해 주면 안 되나요? 너무 불편해 졌어요..

**Comment by YJSoft** [comment]
사용중이신 서드파티 자료의 문제로 보입니다. XE 기본설치에는 등록 버튼 하나만 있습니다.

**Comment by fotolife** [comment]
Editor  컴포넌트를 체크해야 하나요?
