### ISSUE TITLE
RSS 통합 피드 비활성화

### ISSUE THREAD

**Issue by perzona420** [xpressengine/xe-core#1573]
RSS 통합 피드는 기본적으로 [사용]상태로 되어있는데요.
이걸 [미사용]으로 설정하기 위해서는 피트 정보를 적어야 합니다.
피드(Feed) 제목 값은 필수입니다. 이렇게 뜨지요.

미사용을 하면 입력되지 않고도 설정이 가능하도록 개선되야 할것 같네요.

**Comment by misol** [comment]
이 이슈에 대한 PR이 제출되었습니다. https://github.com/xpressengine/xe-core/pull/1660
