### ISSUE TITLE
SSL 적용시 관련 페이지 문제

### ISSUE THREAD

**Issue by reebit1990** [xpressengine/xe-core#1575]
SSL선택 적용 및 항상 적용시 관련 페이지가 오작동 합니다.

1. 관리자 페이지의 [사이트 메뉴 편집]이 오작동 합니다. (메뉴가 출력되지 않음)
[ps. SSL적용하지 않아도 사이트 메뉴 편집 페이지 접속한 상태에서 재접속시 메뉴 출력 되지 않음]
2. 에디터가 정상 작동되지 않습니다. (CK Editor경우 빈 페이지 출력 xe에디터는 출력되지만 에러)
3. 쉬운 설치 가면 안전하지 않는 리소스로..(이건 오류가 아니지만..그래도 작성)

확인 부탁드립니다. CloudFlare이용한 SSL테스트였습니다.
감사합니다.

**Comment by kijin** [comment]
CloudFlare의 Flexible SSL 옵션을 사용할 경우 HTTPS 사용 여부를 실서버에서 정확하게 파악할 수 없기 때문에 발생하는 문제입니다.

이 문제는 아파치 서버에 CloudFlare 모듈을 설치해서 해결하는 것이 정답입니다. 그러나 웹호스팅 환경이라서 서버 설정을 건드리기 곤란하다면 `config` 폴더에 `config.user.inc.php`라는 파일을 생성하여 아래의 내용을 넣어보세요.

    <?php
    if (strpos($_SERVER['HTTP_CF_VISITOR'], 'https') !== false) {
        $_SERVER['HTTPS'] = 'on';
    }

**Comment by misol** [comment]
@kijin 님 댓글의 방법대로 하면 해결되는 이슈입니다.
3번은 XE Core 이슈는 아닌 것 같습니다.

이 이슈는 닫아도 될 것 같습니다.

**Comment by reebit1990** [comment]
@misol 닫는 방법을 몰라서.. 그냥 내비둔 1ㅅ..잌ㅋㅋ
방법 좀 가르쳐줘요..
