### ISSUE TITLE
언어가 영어일때 getRegdateDT() 에서 올바르지않은 값이 반환됨

### ISSUE THREAD

**Issue by conory** [xpressengine/xe-core#1577]
언어가 영어일때 $oDocument->getUpdateDT() 에서 2013-06-06T23:04:13+09:00 이란 YYYY-MM-DDThh:mmTZD형식이 아닌 영어 표기대로 Jul 02, 2015T17:54:11+09:00 이란 값이 반환됩니다.

때문에 프로그램에서 오류가 났습니다.

**Comment by kijin** [comment]
#1656
