### ISSUE TITLE
jQuery.exec_json으로 코멘트 추천, 비추천시 리턴값에 문제가 있습니다.

### ISSUE THREAD

**Issue by zfanta** [xpressengine/xe-core#1580]
![image](https://cloud.githubusercontent.com/assets/6619332/8508095/667a97d6-229d-11e5-88f7-fa80c61708a7.png)
공홈에서도 확인한 결과 글을 추천한 경우 추천 갯수가 리턴되는데 코멘트의 경우에는 추천 갯수가 리턴되지 않습니다.
```
// Return the result
$output = new Object(0, $success_message);
if($point > 0)
{
	$output->add('voted_count', $obj->after_point);
}
else
{
	$output->add('blamed_count', $obj->after_point);
}
$output->add('point', $point);

return $output;
```
comment.controller.php의 updateVotedCount에 저 코드가 있고 실행도 되는데 이상하네요.

**Comment by misol** [comment]
최신 버전에서 해결된 이슈니 닫아도 될 것 같습니다. @bnu 님 고생하셨습니다. @YJSoft 님도 고생하셨습니다.
