### ISSUE TITLE
작업하다 알아낸 작은 버그가 있습니다.

### ISSUE THREAD

**Issue by perzona420** [xpressengine/xe-core#1581]
설치된 레이아웃에서 레이아웃을 복사하는 기능이 있지요?
새 제목 클릭하고나서 저장하면 복사되겠죠?

하지만.. 새 제목에서 '추가' 버튼 누르면.. 그때부터 문제가 발생합니다.
입력을 이미 완료했는데도 또 입력하라는 메시지가 뜹니다.
제목 작성후 절대로 '추가'버튼을 누르면 안된다는거죠. 그대로 저장 버튼 클릭해야만 작동하지요.

이거를 수정할 필요가 있지 않나 싶어서 보고 합니다.

**Comment by YJSoft** [comment]
@reebit1990 해당 추가버튼은 레이아웃을 한번에 여러번 복사할 때 사용하는 것으로, 추가 버튼을 누른 뒤 두 입력란을 모두 채우면 문제 없이 복사가 됩니다.

**Comment by reebit1990** [comment]
@YJSoft 추가 버튼을 누른뒤 2번째 역시 추가 버튼을 누르면 복사가 이뤄져야 하는것 같은데
현재는 1번째는 추가 버튼 누르고 2번째는 '입력칸'에다가 위치 해야만 정상 복사가 됩니다.
뭔가 좀 이상한것 같은데요? 흠..
