### ISSUE TITLE
15-263

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#1583]

**Comment by kijin** [comment]
수많은 레이아웃들이 다 따라오려면 상당한 시간이 소요될 것 같습니다. XE로 만들어진 모든 사이트가 각자의 레이아웃을 갖고 있는 것이나 마찬가지니까요. 레이아웃 마크업에 `htmlspecialchars()`가 들어가는 것도 상당히 지저분해 보입니다. `$is_keyword` 변수를 레이아웃에 넘기기 전에 미리 escape 처리해 주는 방법은 없나요?

**Comment by hjhj3686** [comment]
아 레이아웃 소스를 변경해야 하나 했는데 1.8.5에서 반영이 됬군요.
