### ISSUE TITLE
메뉴 노출 대상 그룹이 1개 이상일 경우 메뉴명 수정이 안되는것 같습니다.

### ISSUE THREAD

**Issue by geusgod** [xpressengine/xe-core#1586]
풀리퀘를 드려야 되는데 버그 보고만 하게 되었습니다T.T

우선 3개 서버에서 테스트 했습니다. 아래는 해당 서버의 환경 입니다.
app : Apache
xe_version : 1.8.3
php : 5.5.9-1ubuntu4.4
db_type : mysql_innodb
use_rewrite : Y

메뉴 노출 권한에 그룹을 2개 이상 체크하고
메뉴 이름을 수정하면 메뉴 명칭이 수정이 안되는것 같습니다. (1개만 체크하면 수정됩니다.)

![20150707_002](https://cloud.githubusercontent.com/assets/3859253/8537171/eceff366-2495-11e5-9adc-9646ba4b2bc3.jpg)

접근, 관리 권한은 그룹을 2개 이상 체크하여도 문제가 없습니다.
제가 가지고 있는 서버가 모두 환경이 비슷해서 다양한 환경에서는 테스트를 못했습니다.
양해바랍니다~

**Comment by geusgod** [comment]
원래는 다국어 적용을 위해서 테스트 하다가 원인 몰라서 계속 그냥 썼었는데...
오늘 오전에서야 재현이 가능한 부분을 발견해서 보고 드린것입니다.
피드백 이렇게 빨리 주셔서 놀랐습니다^^; 감사합니다~ 수고하세요~

**Comment by bnu** [comment]
fixed #1587
