### ISSUE TITLE
1.8.4 CK에디터 섬네일 대표 지정 오류

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1589]
업데이트 후 파일 첨부를 테스트 해보려고 첨부를 하니 섬네일의 오른쪽 위 귀퉁이에 V표시가 생긴것을 확인했습니다. 아마 이 부분이 대표섬네일로 사용할 이미지를 선택하는 것 같은데

선택을 하면 대상을 찾을수 없다고 메시지가 발생합니다.

**Comment by hjhj3686** [comment]
해당 현상은 글 작성 전에 일어나는걸로 확인했습니다. 저는

글 수정시에는 문제가 되진 않습니다만.. 글 작성시에는 이러한 메세지가 출력되네요

**Comment by wookho** [comment]
기술적으로 게시글 등록 이후 다시 섬네일을 변경할 수밖에 없는 구조라면 메시지를 바꿔야 사이트 이용회원들이 혼돈이 없을 것 같습니다.

대상을 찾을 수 없다   ->  게시글 등록 후 수정을 통해 대표 이미지를 변경할 수 있습니다.

**Comment by wookho** [comment]
@bnu 궁금합니다. 오류인가요 ? 아니면 문구를 바꿔야 하는 상황인가요 ?

**Comment by hjhj3686** [comment]
이거 제가 보기에는 빠른 조치가 필요할거 같네요

무턱대고 대상을 찾을수 없습니다만 띄우니..
