### ISSUE TITLE
$matches[0] 로 닉네임을 불러올경우 생기는 문제

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1603]
비회원에게는 닉네임이 그대로 표시되지만

로그인 이용자에게는 닉네임이 보이지 않고 공란으로 표시됩니다.

**Comment by ioz2014** [comment]
$member_srl = $matches[3];
	if($member_srl < 1 || !$member_srl)
	{
		return $matches[0];
	}

그냥 처음 부분에서 한꺼번에 하면 될텐데 따로 하실 필요가...

**Comment by hjhj3686** [comment]
@ioz2014 그렇게 하도록 하겠습니다.
