### ISSUE TITLE
config 파일을 일반 유저가 쓸 수 없는 문제

### ISSUE THREAD

**Issue by wkpark** [xpressengine/xe-core#1605]
현재 `files` 아래에 생성되는 모든 파일의 퍼미션은 그 파일의 소유자/그룹이 모드 `www-data` 혹은 그에 준하는 사용자입니다.
따라서 이 아래의 파일을 수정해주려면 https://www.xpressengine.com/qna/21638521 에 언급되어있는 것처럼 간단한 php 스크립트를 만들어서 해결해야 합니다.

https://www.xpressengine.com/devlog/22674444 같은 공식 문서는 아예 호스팅 업체에 문의하라는 일반 사용자 입장에서 조금 황당한 설명이 있기도 합니다.

이러한 문제를 해결하려면 유닉스에 익숙하신 사용자라면 `files` 디렉토리 퍼미션에 `sgid` 퍼미션을 주면 된다는 사실을 알고계실것입니다. 즉, `files` 디렉토리 아래에 생성되는 모든 파일의 그룹소유주가, 자신의 그룹 소유주와 같게 됩니다.

즉 자신의 유저/그룹에 각각 `foobar:hello`이고 `files/` 디렉토리에 `sgid` 퍼미션 비트가 설정되어 있으면, `files/` 아래에 `www-data`아파치 유저에 의해서 생성되는 `files/cache/page/foobar.php` 파일의 `소유주:그룹`은 `www-data:www-data`가 아닌 `www-data:hello`가 됩니다.

따라서 소유주는 `files` 아래의 모든 파일을 손쉽게 삭제하여 관리할 수 있으며, 특정 템플리트 캐시를 고쳐서 간단히 테스트해볼 수 있는 방법을 써먹을 수도 있습니다.

모니위키는 이미 기본으로 `sgid` 퍼미션을 설정하도록 되어있으며,

디렉토리에 `SGID` 비트를 설정하려면 `chmod 2777 files`라고 하면 됩니다.
최초 XE를 설치할 때에 XE 최상위 디렉토리의 퍼미션을 `777`이 아닌 `2777`라고 해야 합니다.

또한 XE가 이미 설치되어 있는 경우에는 다음과 같은 명령으로 모든 디렉토리에 대해 `sgid` 비트를 세팅할 수 있습니다. (`files` 포함. 파일 소유주의 그룹이 `mygroup`인 경우)

```
$ sudo find files -type d |xargs chmod 2777
$ sudo find files -type d |xargs chgrp mygroup
```

도쿠위키에서 설정하는 방법
https://www.dokuwiki.org/install:permissions#tipusing_the_setgid_bit

---

현재 XE 메뉴얼 페이지에서는 `files` 디렉토리를 만든 후에 `707` 퍼미션으로 만들라고 되어있는데,
- 현재 `files` 디렉토리는 자동 생성 가능함. 메뉴얼 고쳐야 함.
- 자동 생성될 경우에 퍼미션은 `777`임 메뉴얼의 설명 `707`과 다름  (디렉토리에 그룹 퍼미션에 `0`을 주는 것은 별 의미 없음. 다른 사용자가 `7`이므로 디렉토리 리스팅이 가능.)
- 관리자 레벨인 경우에는 `777` 권장

그리고
- 일반 유저인 경우에는 `2777` 권장.
  이런 식으로 추가 설명을 넣거나 해야 할것입니다.

(수정됨)

**Comment by wkpark** [comment]
살펴보니 FileHandler에서 chmod를 사용하고 있어서 새로 생성되는 디렉토리가 sgid 비트를 제대로 보존하지 못하고 있었습니다. 이에 chmod()를 쓸것이 아니라 umask()를 사용하여 이 문제점을 수정하였으며, 또한 umask()를 관리자/사용자가 직접 제어할 수 있도록 하여 보안강화도 가능하도록 하였습니다.

**Comment by qw5414** [comment]
혹시, 이거.. 여러 웹호스팅을 대상으로 한 PR이 맞는지 궁금합니다.

서버 관련 권한은 전체적인 서버영향을 받기 때문입니다.

애초에 755권한만 필요로로 하는 서버도 있고 웹호스팅마다 너무 다른 서버세팅이 존재하기 때문입니다.
가상 서버도 자기마음대로 설정하는것도 있고요..

**Comment by wkpark** [comment]
@qw5414 // 일반 사용자 레벨에서도 `chmod()` 대신에 `umask()`를 쓰는 것이 편리하고, 호스팅 업체 입장에서도 편리합니다.

이 패치의 기본 목적은 `2777`과 같은 세팅을 하였을 경우에 `sgid` 비트를 건드리지 않는 것입니다.
즉, `chmod(755)`때문에 `sgid` 비트가 clear 되어버리는 문제를 해결

뿐만아니라
`chmod(755)`로 하드코딩 되어있는데, `umask` 값을 조절해서 `700` 값으로 조정하는 것도 소스를 고치지 않고 보다 chmod값을 조정할 수 있으며, 보안을 강화할 수도 있습니다.

**Comment by qw5414** [comment]
@wkpark 근데요 제가 서버에서 설정되어있는 서버는 `2777`이나 `777`으로 files풀더를 설정하면 아에 서버에서 웹을 차단되게 되어있어요. 이부분은 어떻게 해결해야하죠? 이러한 환경이나 기타등등의 웹환경의 고려부분은요? 이부분을 질문드리고 싶어서요..

**Comment by wkpark** [comment]
@qw5414 // 음.. selinux 설정때문이 아닐까 합니다. selinux 설정때문에 아파치 설정을 한참을 헤멨던 기억이 나네요. 보안에 강력하지만.. selinux를 결국 잘 안쓰게 되더라는..

**Comment by qw5414** [comment]
@wkpark 글쎄요 저희서버는 그걸 설정한 적이없어서요 ;;
자체 패널의 보안을 사용하고. 패널에서도 권한이 유저에게 나눠지는 형태입니다.
