### ISSUE TITLE
통합검색이 1.8.1 이후 업그레이드 하고 나서 안된다

### ISSUE THREAD

**Issue by youshine** [xpressengine/xe-core#1606]
오늘 1.8.5 로 업그레이드 해도 통합검색이 1,8,1 이후에 안되고 있다.

http://www.sfmasterchorale.com/xe/내가 운영하는 다른 XE웹들은 1.8.1으로 다운 그레이드 하니 통합검색이 여전 잘 되고 있다.

1.8.3 release note 에다 상세한 보고했었다.

**Comment by hjhj3686** [comment]
검색 대상을 지정 안하셔서 그런거 아닌가요

관련 변경이 있던걸로 기억하는데..

**Comment by youshine** [comment]
검색대상을 어이 지정하는 지 좀 가르쳐 주실 수 있나요...

1.8.1에서는 그런 거 안해도 검색잘 되고 있는 데 업그레이드 하면 안 됩니다.

**Comment by YJSoft** [comment]
@youshine 관리자 페이지-고급-설치된 모듈-통합검색에서,
* 검색 대상 모듈을 선택(선택한 대상만 검색 선택후에서 모듈 추가)혹은
* 검색에서 제외할 모듈을 __하나 이상__ 선택(선택할 대상을 검색에서 제외 선택후 모듈 추가) 후 저장하시면 됩니다.

**Comment by youshine** [comment]
감사합니다. 덕분에 문제 해결 했내요.

Richard Yim (also known as 유샤인 YouShine@youshine.com )
510-583-1161 cell
http://www.youshine.com 
http://www.newlifeforum.us
http://www.youshineblog.com
http://www.kb34.com
http://www.rokaf50.com/
http://www.snulaw17.org
http://cafe.chosun.com/youshine 
http://www.sfmasterchorale.com
http://thecrossing.cfcchayward.org
