### ISSUE TITLE
changed 파일 배포와 관련한 건의사항입니다.

### ISSUE THREAD

**Issue by devdho** [xpressengine/xe-core#1610]
XE의 새로운 버전이 배포되면 changed 파일만 업데이트하고 있습니다.

git 정보를 보면 사용하지 않아 삭제되는 파일이 존재하는데
changed 파일에는 삭제 파일 정보는 포함되지 않아
불필요한 파일이 계속 누적되고 있습니다.

changed 파일 혹은 릴리즈 정보에 삭제되는 파일에 대한 정보도 함께 제공해주시면 좋을 것 같습니다.

감사합니다.

**Comment by bnu** [comment]
`git diff --stat=200 --diff-filter D 1.8.0..1.8.5` 이러한 명령을 통해 확인할 수 있습니다.

**Comment by ioz2014** [comment]
@bnu git을 사용할 줄 모르는 사람은 어떻게 되지요? 삭제되는 파일은 README 파일이나 CHANGELOG 등에 기재해서 압축파일에 첨부하거나 다운페이지에서 따로 기재해주면 좋을 것 같습니다.

**Comment by bnu** [comment]
`CHANGES.버전명.txt` 으로 별도로 파일을 추가했습니다.
https://github.com/xpressengine/xe-core/releases/tag/1.8.7

**Comment by qw5414** [comment]
@bnu 발견이 되어서..
해당 텍스트 파일이 맥OS에서 진행이 되어서 그런지 엔터의 스타일이 윈도우와 맞지 않아 메모장에서 잘못되게 표기되고 있습니다.
![_072015_102620_pm](https://cloud.githubusercontent.com/assets/4381756/8776746/5d13490c-2f2e-11e5-9ea0-87bcafee2ec0.jpg)
물론 다른 에디터로 열거나 하면되지만, 저파일을 보는 일반 유저의 경우 메모장을 사용하는것으로 판단되어서요.

1. 윈도우기반에서도 쉽게 열 수 있는 `txt`파일인점.
2. 윈도우 기반의 `txt`파일이 보통 `메모장`프로그램에서 실행된다는점.


을 예시로 들엇을 때를 생각해서 엔터가 정상적으로 먹혀보이도록해주시는게 좋을 것 같아요.
