### ISSUE TITLE
ck에디터에서 에디터 시퀀스가 전달되지 않음.

### ISSUE THREAD

**Issue by ioz2014** [xpressengine/xe-core#1618]
var editorSequence = '{$editor_sequence}';

editor.html에 누락되어있어서 컴포넌트가 동작하지 않는 경우가 있었습니다.

**Comment by misol** [comment]
오호! 눈 좋으십니다.

**Comment by bnu** [comment]
이슈에 대한 좀 더 상세한 설명 바랍니다.

**Comment by ioz2014** [comment]
에디터 시퀀스를 전달하는 코드가 누락되어있었습니다. 그것 뿐입니다.
서드파티 컴포넌트나 수정 에디터 스킨(axisj uploader, imgur upload) 등과의 호환성을 해결할 수 있습니다.

**Comment by YJSoft** [comment]
@ioz2014 ```html
<div id="ckeditor_instance_{$editor_sequence}" data-editor-sequence="{$editor_sequence}" data-editor-primary-key-name="{$editor_primary_key_name}" data-editor-content-key-name="{$editor_content_key_name}" style="min-height:{$editor_height}px;"></div>
```

```js
ckeconfig: {
	height: '{$editor_height}',
	skin: '{$colorset}',
	contentsCss: '{$content_style_path}/editor.css',
	xe_editor_sequence: {$editor_sequence},
	toolbarCanCollapse: true,
	language: "{str_replace('jp','ja',$lang_type)}"
},
```

위와 같이 전달하고 있습니다.

**Comment by ioz2014** [comment]
@bnu 
editorSequence 라는 자바스크립트 변수로 $editor_sequence를 전달하는 것을 말한겁니다....

**Comment by YJSoft** [comment]
@ioz2014 기존 XpressEditor에서도 전달하지 않았던 것을 추가로 전달할 필요성이 없어 보입니다.
게다가 한 화면에 에디터가 여러개 올 경우 변수가 덮어 씌워지게 되어 의미가 없어집니다.

**Comment by misol** [comment]
수정된 에디터 예시로 AXISJ 에디터를 드셔서 https://www.xpressengine.com/index.php?mid=download&package_id=22450636 를 테스트 해봤으나 호환성 문제가 발생하지 않았습니다. 그리고 CK 에디터도 하나의 에디터 스킨이고 AXISJ 업로더를 사용하는 위 에디터 스킨도 하나의 스킨이기 때문에 CK에디터와 무관한 것으로 보입니다.
