### ISSUE TITLE
1.8.5 업데이트 후 문제

### ISSUE THREAD

**Issue by Altberta** [xpressengine/xe-core#1626]
게시물이나 댓글을 등록하려고 할 시, '내용 값은 필수입니다'라는 메시지가 뜨면서 등록이 되지 않습니다. 에디터는 'XE 기본 에디터'입니다.

**Comment by misol** [comment]
문제가 일어나는 페이지 주소를 남겨주시겠어요? 저도 한번 보고 싶습니다.

**Comment by Altberta** [comment]
현재 1.8.3으로 롤백한 상태이기 한데, 내일 중으로 재업데이트 해서 확인 후 여전히 문제 있으면 주소 남겨드리겠습니다.

**Comment by misol** [comment]
감사합니다 :)

**Comment by Altberta** [comment]
1.8.7로 재업데이트하였습니다. 여전히 문제가 있으며 게시판 스킨 등을 건드려보았는데도 문제는 여전하네요.
http://velona.xyz/Free_Board
확인을 하실 수 있도록 특정 게시판 권한만 잠시 풀어두었습니다.

추가로 덧붙이자면 어떤 에디터를 사용하느냐에 따라 각각 다른 현상들이 나타납니다.
CK에디터를 쓸 때는 아예 내용 작성 란이 보이질 않고, 'simple'이라는 에디터가 있는데 이것의 경우 그야말로 텍스트란만 있는 에디터라 그런지 잘 작동하네요. 아무래도 에디터쪽 문제가 아닌가 싶기도 합니다.

**Comment by bnu** [comment]
@Altberta  스크립트 오류가 있을 것으로 보이네요. 폰으로 보는 중이라 1~2시간 내에 pc로 확인해보겠습니다.

**Comment by misol** [comment]
자바스크립트 오류는 XEdition 레이아웃에서 나는 것 같습니다.

**Comment by misol** [comment]
@Altberta SCM 음악 재생기 잠깐 비활성화 해주실 수 있나요?

**Comment by Altberta** [comment]
네 비활성화했습니다.

**Comment by misol** [comment]
xedition 레이아웃에서
```html
<load target="./js/jquery.parallax-scroll.min.js" />
```
구문이 삭제되어 일어나는 문제입니다.

**Comment by YJSoft** [comment]
HTML 편집 기능 등으로 레이아웃을 편집하셨다면 초기화해 주세요.(변경 사항은 백업해 두셔야 합니다)
1.8.5부터 XEDITION 레이아웃이 반응형화 되면서 HTML 코드가 변경되었습니다.

**Comment by Altberta** [comment]
삭제된 구문을 다시 추가할 필요는 없는 것 같고, HTML 코드 초기화를 하니 잘 되네요.

**Comment by misol** [comment]
HTML 코드 초기화를 하면 삭제된(이전에 없었던) 구문이 살아납니다 :)
문제 없는 이슈로 보입니다. 닫아도 될 것 같습니다.

**Comment by Altberta** [comment]
네. 감사합니다.
