### ISSUE TITLE
CK Editor 로 설정시 본문 입력 화면이 안나옵니다.

### ISSUE THREAD

**Issue by socialskyo** [xpressengine/xe-core#1627]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/js/plugins/ckeditor/ckeditor/ckeditor.js?20150710232135
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
editor.app.min.js:1 Uncaught ReferenceError: CKEDITOR is not defined

요소 검사시 이렇게 관련 js를 못불러 오는거 같은데 짚어 볼게 있을까요?

1.8.5 이며 호스팅 유저 입니다.

app : Microsoft-IIS/5.0
xe_version : 1.8.5
php : 5.5.26
db_type : mysql
use_rewrite : Y
use_db_session : N
use_ssl : none

**Comment by bnu** [comment]
modules/editor/tpl/js/editor.app.min.js 파일이 제대로 업로드 되었는지 확인해보세요.

**Comment by mactopia** [comment]
@bnu 님 네 해당 파일이 있습니다. 약 2.6KB 2.7KB 즈음 되는것 같습니다.

**Comment by bnu** [comment]
@mactopia 해당 파일의 퍼미션을 확인해보세요.

**Comment by mactopia** [comment]
adfrw -0644 로 나옵니다.
