### ISSUE TITLE
암호에 특수문자 삽입시 로그인이 안되는 문제

### ISSUE THREAD

**Issue by solsol0609** [xpressengine/xe-core#1628]
1.5버전 부터 암호에 특수문자를 넣어 만들면 로그인이 안됩니다. 특히 관리자 로그인시 로그인이 안 되어 db 수정로 문제를 해결하고 있는데요. 다음버전에는 이 오류를 수정해 주시면 감사하겠습니다.

**Comment by bnu** [comment]
비밀번호에 특수문자 사용을 제한하지 않습니다.
사용 중인 별도의 확장 기능을 점검해보시기 바랍니다.

**Comment by qw5414** [comment]
1.4버전부터 지금 릴리즈까지 이상이 없습니다...

**Comment by ioz2014** [comment]
어떤 특수문자인가요?

**Comment by kijin** [comment]
웹방화벽 등 다른 프로그램과 상호작용일 가능성도 있습니다.

**Comment by solsol0609** [comment]
!, @ 등 모든 특수문자 사용 시 발생합니다.올바른 이메일 주소를 입력해도, 로그인시 " 아이디의 값은 올바른 메일주소가 아닙니다."라는 오류가 발생합니다.

**Comment by misol** [comment]
저는 XE로 만든 여러 사이트에 모두 특수문자를 입력해서 비밀번호를 만들어두었는데 현재 아무 문제가 없습니다.
아이디로 로그인, 이메일로 로그인 모두 동일합니다.

로그인이 일어나는 레이아웃이나 로그인 위젯 스킨 문제일 수도 있습니다.
