### ISSUE TITLE
XE 1.8.6 업데이트 하고 하니 스케치북 faq 게시판과 레이아웃 깨어집니다..

### ISSUE THREAD

**Issue by hsmin75** [xpressengine/xe-core#1630]
안녕하세요..
아까전에 XE 1.8.6 업데이트 무사히 마쳤는데요 스케치북 faq 게시판이 통채로 깨어지는 현상이 일어나고 있습니다..
일반 게시판과 갤러리는 괜찮은데요..

XE 1.8.5 로 마이그레이션 했습니다..

**Comment by YJSoft** [comment]
#1634 를 참고하셔서 직접 수정하시거나, 스케치북 스킨 파일 `_list_faq.html` 중
`<span cond="$document->getExtraEidValue('rating')" class="starRating" title="{$document->getExtraEidValue('rating')}점"><span style="width:{$document->getExtraEidValue('rating')*10}%">{$document->getExtraEidValue('rating')}점</span></span>`를 지우시면 됩니다.
