### ISSUE TITLE
1.8.6 업데이트 후 본문 읽기 에러

### ISSUE THREAD

**Issue by mactopia** [xpressengine/xe-core#1632]
186		return $extra_eid[$eid]->getValue();

이 부분 에러가 납니다. 그런데 스케치북 게시판 갤러리 형태에서만 본문 읽기시 에러가 납니다.
일반 리스트 형식에서 본문 읽기는 괜찮습니다.

Fatal error: Call to a member function getValue() on a non-object in /host/home2/socialskyo/html/modules/document/document.item.php on line 682

**Comment by mactopia** [comment]
일단 임시로 해당 부분만 아래와 같이 기존 버전 그대로 처리하여 사용중입니다.

return $extra_eid[$eid]->value;

**Comment by YJSoft** [comment]
`Extravar.class.php` 파일에 getValue 함수가 있는지 확인(`function getValue()~`)해주세요.
함수가 없다면 업데이트가 제대로 되지 않은 것입니다.

**Comment by YJSoft** [comment]
#1634 를 참고하셔서 직접 수정하시거나 다음 업데이트를 기다려주세요.

**Comment by devwit** [comment]
이슈 등록되어있네요 같은 문제로 깃에 들렸는데 ㅇㅅㅇ;

**Comment by YJSoft** [comment]
https://github.com/xpressengine/xe-core/pull/1634 를 참고하여 수정해서 사용하시거나 https://raw.githubusercontent.com/YJSoft/xe-core/bugfix/nonexistextravar/modules/document/document.item.php (접속후 오른쪽 클릭-다른이름으로저장) 를 받아 modules/document.item.php 파일을 덮어 씌우시면 됩니다.

**Comment by bnu** [comment]
fixed #1634
