### ISSUE TITLE
1.8.6 업그레이드후 초기화면이 안나옴.

### ISSUE THREAD

**Issue by ldonghun** [xpressengine/xe-core#1635]
한글도메인인 이레산업기계.한국을 사용하고 있습니다.
관리자페이지는 들어가지는데, 홈페이지를 들어가면 첫화면에 아무것도 나오지 않는 상황입니다.

**Comment by hjhj3686** [comment]
#1634 체크해보세요

**Comment by YJSoft** [comment]
https://github.com/xpressengine/xe-core/pull/1634 를 참고하여 수정해서 사용하시거나 https://raw.githubusercontent.com/YJSoft/xe-core/bugfix/nonexistextravar/modules/document/document.item.php (접속후 오른쪽 클릭-다른이름으로저장) 를 받아 modules/document.item.php 파일을 덮어 씌우시면 됩니다.

**Comment by bnu** [comment]
fixed #1634
