### ISSUE TITLE
1.8.6 업그레이드 이후 초기화면이 안 나와요ㅠㅠ

### ISSUE THREAD

**Issue by ghost** [xpressengine/xe-core#1637]
업그레이드 이후 초기 화면이 안 나오네요ㅠㅠ

방법 좀 알려주세요ㅠㅠ

**Comment by hjhj3686** [comment]
#1634 체크해보세요

**Comment by kkangtae97** [comment]
어떤 걸 체크하면 되는 거죠?

**Comment by YJSoft** [comment]
https://github.com/xpressengine/xe-core/pull/1634 를 참고하여 수정해서 사용하시거나 https://raw.githubusercontent.com/YJSoft/xe-core/bugfix/nonexistextravar/modules/document/document.item.php (접속후 오른쪽 클릭-다른이름으로저장) 를 받아 modules/document.item.php 파일을 덮어 씌우시면 됩니다.

**Comment by bnu** [comment]
fixed #1634
