### ISSUE TITLE
document.item.php 파일의 getExtraValue 함수 에러

### ISSUE THREAD

**Issue by twocad** [xpressengine/xe-core#1638]
document.item.php 파일의 651라인의 getExtraValue($idx) 함수 내에 있는
return $extra_vars[$idx]->getValue(); 로 바뀐 이유가 따로 있나요..
원래는 return $extra_vars[$idx]->value; 이었는데..
바뀐 문장 때문에 getExtraValue를 사용한 부분이 모두 에러가 뜨네요.

변경된 파일만 적용해서 바꿨습니다만..

별것 아닌것 같은데 게시판 절반이 안 열려서 급 당황.
저 부분만 다시 바꿔서 사용중에 있습니다.

**Comment by YJSoft** [comment]
XSS 취약점으로 패치된 부분입니다
오류가 나는 부분은 #1634 를 참고해서 수정하여 사용하실수 있습니다.

**Comment by bnu** [comment]
fixed #1634
