### ISSUE TITLE
getModel Controller, 등등을 사용할 경우 

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xe-core#1640]
모듈의 설치에 따라 각모듈간의 호환성이 있는경우가 있는데
`getModel->메소드`의 함수에 대해서 문제점이 있는것 같습니다.

각 모듈을 사용하는경우 코어의 경우는 괜찮지만, 연관되는 모듈을 묶어버리는 경우가 있을 수 있습니다.

(퀴즈게임모듈 <--> 메뉴새글표시모듈)
이렇게 되는경우 문제점이 발생되는데.. 보통, php구문애러가 뜨더군요..
새글표시 모듈에서 퀴즈게임모듈이 존재 하지 않는경우 퀴즈게임의 메소드가 불러와졌을때, 생기는 문제점 같았습니다... 

이럴때, 무조건 
`if(!$oQuizgameModel) return;`
구문으로 처리를 해야하는것이 현명한건가요?
아니면, 모듈이 존재하지 않을때 메소드를 읽게 하더라도 구문을 넘길 수 있는 방법을 만들 수 있는지 궁금해서요..

(구문이 넘길 수 있으면 코어쪽수정일 것 같아서.. 여기에 남겨 봅니다..)

**Comment by YJSoft** [comment]
get~~류의 함수는 모두 `ModuleHandler::getModuleInstance` 함수를 호출하고, 이 함수에서 이미 해당 모듈이 없는 경우 NULL을 반환하도록 처리되어 있습니다.

**Comment by qw5414** [comment]
@YJSoft 리턴을 처리하는것도 좋을것 같긴한데.. 사실 것도 뭐 ㅎ 모듈간의 호환성이 문제점이 될 수 있겠군요. 얼마전 알수 없는 오류때문에 캐시파일 재생성이 안디는 문제점때문에 error로그를 통해서 봤더니 이와 같은 비슷한현상이라 ㅎㅎ

답변 땡큐요 ^,~
