### ISSUE TITLE
사이트메뉴편집-메뉴설명 작성 후 한글깨짐현상

### ISSUE THREAD

**Issue by jominhyun** [xpressengine/xe-core#1644]
사이트메뉴편집-메뉴설명 작성 후 한글깨짐현상 (SEO 모듈 Meta description 최적화 기능 사용)

저만그런건가요?

예)

meta property="description" content="&amp;ecirc;&amp;para;�&amp;ecirc;&amp;cedil;�&amp;iacute;��&amp;ecirc;&amp;sup2;�&amp;igrave;�� &amp;igrave;�&amp;not;&amp;igrave;�&amp;copy;&amp;igrave;��&amp;euml;�&amp;frac14;&amp;euml;&amp;brvbar;&amp;not; &amp;igrave;��&amp;euml;&amp;iexcl;� &amp;euml;��&amp;igrave;��&amp;igrave;&amp;pound;&amp;frac14;&amp;euml;�� &amp;igrave;&amp;sect;�&amp;igrave;��&amp;ecirc;&amp;sup3;&amp;micro;&amp;ecirc;&amp;deg;�&amp;igrave;��&amp;euml;��&amp;euml;�&amp;curren;">

**Comment by kijin** [comment]
기본 문자셋이 ISO-8859-1(미국표준)인 서버에서 UTF-8(XE 기본값)으로 인코딩된 한글을 `htmlentities()` 함수에 통과시키면 저런 결과가 나옵니다.

서버의 기본 문자셋(`default_charset`)이 UTF-8이 아닌 것 같으니 확인해 보세요.

**Comment by YJSoft** [comment]
@jominhyun 해당문제는 SEO 모듈의 문제입니다. https://github.com/YJSoft/xe-module-seo/issues 에 새로 이슈로 남겨 주세요.

**Comment by jominhyun** [comment]
@YJSoft 어느분의 이야기가 맞는것인지 모르겠네요.

**Comment by jominhyun** [comment]
@kijin 서버는 UTF-8로 맞춰져있습니다. 혹시 제가 실수하는것일지 모르니 
비슷한 증상이 있는분들이 있는지 포럼쪽에도 문의를 해봐야겠네요.

**Comment by YJSoft** [comment]
@jominhyun SEO 모듈 자체가 제가 수정한 모듈입니다. 그리고 이슈 링크 달아 드렸으니 관련 내용은 위 이슈에서 진행해주세요.

**Comment by YJSoft** [comment]
@jominhyun 
https://github.com/YJSoft/xe-module-seo/releases/tag/0.3.2
추가로 문제가 있다면 https://github.com/YJSoft/xe-module-seo/issues/new 로 남겨 주세요.

@bnu 이 이슈는 닫아 주세요.
