### ISSUE TITLE
Ck에디터에 자동 저장 기능이 없습니다.

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1648]
xpresseditor 와 달리 자동 저장 기능이 없습니다..

먼가 허전하다 했더니..

해당 기능이 없어 글이 다 날아갈수도 있는 불편함을 초래합니다.

**Comment by wkpark** [comment]
궁금해서 찾아보니 이런게 있네요. http://ckeditor.com/addon/autosave

**Comment by YJSoft** [comment]
https://github.com/YJSoft/xe-core/tree/feature/ckautosave 에서 진행중이나 아직 자동 저장된 문서를 불러올 때 첨부파일이 갱신되지 않는 문제가 있습니다.

**Comment by YJSoft** [comment]
#1651

**Comment by largeden** [comment]
@YJSoft https://github.com/xpressengine/xe-core/commit/f7fea869f5f9bc2f032eeb6ac9fb0b410b7f4dab

혹시나 하고... document_srl도 추가해야합니다.
