### ISSUE TITLE
게시물 검색시 해당 키워드로 검색하면 글에서 에디터가 보이지 않음.

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1653]
검색시 앞에 ($ 가 들어가면 에디터가 보이지 않습니다.

($docu 로 검색을 돌려서 게시글에 들어갔는데 해당 게시글에서 에디터가 보이지 않네요

그래서 실험을 해봤더니 저 문구가 들어가면 그런걸 보아서 필터링을 해야 될거 같네요.

**Comment by hjhj3686** [comment]
공홈의 2차메뉴도 마우스 오버시에 2차 메뉴가 뜨지않는걸 보아 이거 그 제이쿼리 충돌이라고 하나요..

**Comment by YJSoft** [comment]
해당 부분은 알림센터 Lite의 스크립트 문제로, 코어 문제가 아닙니다.
알림센터 문제는 알림센터 저장소에 올려 주세요. https://github.com/xe-public/xe-module-ncenterlite

**Comment by hjhj3686** [comment]
@YJSoft 원인을 알지못해 일단 코어쪽 문제인줄 알았는데 그쪽이군요 그쪽으로 이동할게요!
