### ISSUE TITLE
1.8.5 이후 1.8.6 와 1.8.7 모두 쉬운설치하면 성공적으로 설치되었습니다고 말하지만 실상은 업그레이드 되지 않은 것 같네요.

### ISSUE THREAD

**Issue by youshine** [xpressengine/xe-core#1658]
1.8.5 이후 1.8.6 왈 1.8.7 모두 쉬운설치하면 성공적으로 설치되었습니다고 말하지만 실상은 업그레이드 되지 않은 것 같네요.

왜냐면 관리자 제어판 맨밑에는 여전히 버젼이 1.8.5 로 남아 있으며 쉬운설치도 계속 업그레이드 하라고 나와 있으니까요...

**Comment by youshine** [comment]
새버젼을 다운하여 FTP로 올린후 압축을 풀으니 그제서야 업그레이된 표시를 보입니다.  
쉬운설치는 안되나보네요..

**Comment by YJSoft** [comment]
@youshine 코어 업데이트는 변경되는 파일이 많습니다. 쉬운 설치로 업그레이드할 경우 서버 사양에 따라 업데이트가 중간에 중단되어 사이트가 열리지 않게 될 수 있습니다. 또한 간혹 일부 서버의 경우 쉬운설치로는 코어 업데이트가 불가능하기도 합니다(자세한 원인은 알 수 없으나 권한 문제 등일 가능성이 큽니다)

코어 업그레이드는 쉬운설치보다는 FTP 등으로 덮어 씌우는것을 추천드립니다.

**Comment by wkpark** [comment]
음... 변경된 파일을 자동으로 보관하고 덮어씌워주는 업그레이드 스크립트를 지원하는 것도 나쁘지 않을것 같네요.

**Comment by misol** [comment]
@wkpark 그러려면 자료실 서버에서 changed 만 보관하고 있어야겠군요.
좋은 PR 기대합니다 ( 으응 )

**Comment by wkpark** [comment]
@misol 제가 다른 프로젝트 용도로 만들어둔 스크립크가 있기는 합니다~ diff를 이용해서 자동으로 바뀐 파일 리스트를 생성하지요ㅎ 시간내어 이걸 XE에 맞춰보고 개선해야겠습니다. 쉘스크립트로 만든건데 PHP로 바꿔볼 수도 있겠네요.
