### ISSUE TITLE
1.8.6 의 확장변수 패치(?)로 포인트 경매모듈 사용이안되네요

### ISSUE THREAD

**Issue by Syangki** [xpressengine/xe-core#1659]
https://www.xpressengine.com/index.php?mid=download&package_id=20279228
이러한 모듈인데 잘쓰고있다가 안되길래 다운그레이드 했습니다. 무슨 문제로 안되는건가요

**Comment by misol** [comment]
분류: 질문 또는 버그 또는 하위호환성 문제

**Comment by misol** [comment]
어떻게 안되는지 자세히 적어주시면 더 도움이 될 것 같습니다.

**Comment by Syangki** [comment]
제가 개발자가 아니라 자세한건 모르지만
업데이트 하자마자 진행중이던 경매가 진행이 안됩니다
ex)88:24:01 남음 <- 이것이 없어져버림
더불어 입찰내역 조회도안되고, 이미 당첨자가 나온것도 표시가 되지않네요

전부다 확장변수를 통한것인것 같아서 제목을 저렇게 해놓았습니다...
이해가 되실런지 모르겠네요 ㅠㅠ

**Comment by YJSoft** [comment]
#1661 참고해주세요.

**Comment by Syangki** [comment]
그럼 스킨에있는 getValue()  함수를 getValueHTML() 함수로 고치면 이용이 가능한 부분인가요?
@YJSoft

**Comment by YJSoft** [comment]
@Syangki https://github.com/xpressengine/xe-core/pull/1661/files 를 참고해서 수정해주세요.

**Comment by Syangki** [comment]
@YJSoft 감사합니다 덕분에 해결됬네요
