### ISSUE TITLE
MCRYPT_DEV_URANDOM 문제

### ISSUE THREAD

**Issue by bnnu** [xpressengine/xe-core#1665]
https://www.xpressengine.com/qna/23051986
일부 환경에서 `MCRYPT_DEV_URANDOM` 사용시 설치가 안되는 문제점이 있습니다.
특정 상수를 그대로 사용하는 것보다는, 해당 상수의 존재 여부 및 값 유효성 여부를 검사후 사용하도록 해야 할 것입니다.

**Comment by kijin** [comment]
해당 사용자는 PHP 5.6을 사용하고 계십니다. 정상적으로 컴파일된 PHP 5.6에서 `mcrypt_create_iv()` 함수는 존재하는데 `MCRYPT_DEV_URANDOM` 상수가 존재하지 않는 경우는 있을 수 없으며, 설사 상수가 존재하지 않는다 해도 `MCRYPT_DEV_URANDOM`이 기본값이기 때문에 효과는 동일합니다. 따라서 상수의 존재여부를 확인하는 것만으로는 해결이 되지 않습니다.

타임아웃에 걸린다는 것으로 보아서는 `MCRYPT_DEV_RANDOM`으로 잘못 들어가고 있는 게 아닌가 하는 생각이 듭니다. 만약 `URANDOM`이 아닌 `RANDOM`으로 들어간다면 시간이 아주 오래 걸릴 수도 있습니다.

**Comment by kijin** [comment]
Changelog를 보니 PHP 5.6.10에서 `mcrypt_create_iv()` 함수가 `/dev/urandom`에 접근하는 방식에 [변화가 있었습니다](http://permalink.gmane.org/gmane.comp.php.cvs.general/74916). 만약 이것 때문에 발생하는 문제라면 버그가 존재하는 버전에서는 `mcrypt_create_iv()` 함수를 사용하지 않도록 조치해야 할 거예요. 의심되는 버전에서 좀더 테스트해 보겠습니다.

**Comment by kijin** [comment]
최초 버그 신고자의 업데이트에 따르면

- 리눅스, 직접 컴파일한 PHP 5.6.11
- `MCRYPT_DEV_URANDOM` 상수는 정상적으로 `1`로 선언되어 있음
- 일반 유저 권한으로 `/dev/urandom` 접근에 이상 없음
- PHP 스크립트 내에서도 `/dev/urandom` 접근에 이상 없음

제가 추가 테스트를 해보니

- 리눅스, dotdeb 패키지로 설치한 PHP 5.6.11
- `MCRYPT_DEV_URANDOM`을 사용하여 `mcrypt_create_iv()` 실행시 아주 빠르게 결과가 나옴
- 여러 번 반복하거나 `MCRYPT_DEV_RANDOM`과 번갈아 사용해도 문제 없음
- 일반 유저에게 `/dev/urandom` 접근 권한을 주지 않을 경우, 오래 걸리는 것이 아니라 즉시 에러 메시지를 출력한 후 종료됨
- `open_basedir` 설정으로 PHP 스크립트 내에서 `/dev/urandom` 접근을 막더라도 영향 없음

즉, 재현이 불가능합니다.

일단 worksforme 태그를 달아 놓고, 만약 다른 환경에서도 문제가 재발한다면 `Password` 클래스에서 `mcrypt_create_iv()` 함수에 의존하는 부분을 지워버릴 것을 추천드립니다. 이 함수를 사용하지 않더라도 다른 옵션들이 충분히 주어져 있습니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
