### ISSUE TITLE
모바일에서 회원가입 또는 로그인 버튼을 눌렀을때, 아무것도 나오지 않는 오류

### ISSUE THREAD

**Issue by solsol0609** [xpressengine/xe-core#1666]
컴퓨터로 xe 설정을 완료하고 모바일에서 테스트를 하던 중에 발생한 오류입니다. 모든 모바일 레이아웃에서 로그인과회원가입 버튼을 누르면 아무것도 없는 창으로 넘어가기만 합니다. 도와주세요.

**Comment by YJSoft** [comment]
@solsol0609 증상이 재현되지 않습니다. 클릭시 어떤 링크로 이동하는지 적어 주세요.

**Comment by solsol0609** [comment]
로그인 버튼: http://자신의 도메인/index.php?mid=index&act=dispMemberLoginForm
회원가입 버튼: http://자신의 도메인/index.php?mid=index&act=dispMemberSignUpForm

**Comment by MoonWooJohn** [comment]
저도같은 것 같은데요 도움바랍니다.
