### ISSUE TITLE
한국 정보통신망법 개정에 따른 회원 관리체계의 개선 필요성

### ISSUE THREAD

**Issue by cherrype** [xpressengine/xe-core#1667]
misol님께서 XE 공식 웹사이트 포럼에 남겨주신 글과 같이, 

대한민국에 적용되는 정보통신망 이용촉진 및 정보보호등에 관한 법률 제29조2항, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 시행령 제16조에 따라 정보통신서비스 제공자는 1년 이상 이용하지 않는 이용자의 개인정보를 해당 기간 경과 후 즉시 파기하거나 다른 이용자의 개인정보와 분리하여 별도로 저장ㆍ관리하여야 합니다.

XE 기반 웹사이트의 대부분이 대한민국 법의 적용을 받는 만큼, 이 내용은 서드파티 앱이나 퍼블리셔들의 개별적인 선택에 맡기는 것이 아니라 이용약관을 기본 지원하는 것과 마찬가지로 코어의 member 모듈에 기본적으로 포함되어야할 사항이 아닌가 생각됩니다. (당장 XE 공식 웹사이트에도 필요할 수 있습니다.)

동 법 시행령에는 정보통신서비스 제공자등은 이용자가 정보통신서비스를 제1항의 기간(=1년) 동안 이용하지 아니하는 경우에는 이용자의 개인정보를 해당 기간 경과 후 즉시 파기하거나 다른 이용자의 개인정보와 분리하여 별도로 저장ㆍ관리하여야 한다.고 명시하고 있습니다.

그리고 정보통신서비스 제공자등은 제1항의 기간 만료 30일 전까지 개인정보가 파기되거나 분리되어 저장ㆍ관리되는 사실과 기간 만료일 및 해당 개인정보의 항목을 전자우편ㆍ서면ㆍ모사전송ㆍ전화 또는 이와 유사한 방법 중 어느 하나의 방법으로 이용자에게 알려야 한다.는 조항도 있습니다.

따라서 아래와 같은 기능이 필요할 것으로 생각됩니다.

1) 365일 이상 미접속자를 분류하여,

2) 퍼블리셔(사이트 운영자)의 판단에 따라 개인정보를 파기(=회원 탈퇴)하거나 별도의 공간에 저장하여 관리될 수 있는 기능

3) 이 중 별도의 공간에 저장하여 관리한다의 경우 물리적 분리를 명시하지는 않았으므로, DB의 별도 테이블에 '휴면 계정' 형태로 저장하고 로그인시 등록된 이메일 주소로 다시 한번 인증을 거치는 식으로 적법하게 분리가 가능하지 않을까 판단됩니다.

4) 회원정보 파기 또는 휴면계정으로의 별도 분리를 선택한 이후, 회원에게 이메일로 관련 법률에 따라 개인정보가 별도로 처리되었음을 고지할 수 있는 메일링 기능도 함께 필요할 것으로 생각되어집니다.

감사합니다.

**Comment by cherrype** [comment]
그리고 이건 제 생각인데, 법의 적용을 떠나서 사용자 권리 보호를 위해서 이런 기능이 유용하지 않을까 생각합니다. 실제로 사이트를 이용하다 보면 휴면 계정이 해킹되어 스팸을 등록하는 사례도 간혹 있기도 하구요. 

어쨌든 서비스 제공자의 입장에서도 이런 식으로 사용자 정보를 보호할 수 있는 장치가 마련된다는 것은 XE의 바람직한 개선 방향이 아닐까 생각합니다. 뭐 한국에서는 무조건 해야하는 것이니 선택의 여지가 없겠습니다만..

**Comment by bnu** [comment]
코어에서 직접 지원해야할 범위 외의 것인 듯 합니다.
별도의 확장 기능으로 가능하며, 그 어떤이가 이러한 기능의 제작, 배포를 위해 코어의 변경이 반드시 필요하다면 그를 수용할 수는 있습니다.

**Comment by kijin** [comment]
휴면회원을 삭제하는 것은 쉽습니다. 이미 자료실에 관련 모듈이 있는 것으로 알고 있습니다.

별도의 테이블로 옮기는 것은 좀더 까다롭습니다. 서드파티 모듈에서 별도의 테이블을 만들어 회원정보를 옮긴 후 기존의 회원정보를 삭제하는 것까지는 구현이 가능한데, 로그인시 원상복구하는 부분에서 애매한 버그가 발생할 가능성이 많습니다.

예를 들어 `member.doLogin` `before` 트리거를 사용해서 현재 로그인을 시도하고 있는 계정이 휴면계정인지 확인하고, 휴면계정인 경우 회원정보를 원래 위치로 옮겨놓아서 정상적인 로그인이 가능하도록 해줄 수 있습니다. 그런데 만약 로그인에 실패한다면? 누가 해킹을 시도하고 있는 거라면? 원래 위치로 옮겨놓았던 회원정보를 다시 휴면계정으로 원위치시켜야겠죠. 그런데 로그인 실패시에는 `member.doLogin` `after` 트리거가 호출되지 않고 곧바로 종료됩니다. 그럼 회원정보를 원위치시키는 코드는 어디에 넣어야 할까요?

회원들의 편의를 위해서는 로그인뿐 아니라 아이디/비번찾기도 지원해야 하는데, 현재 `procMemberFindAccountByQuestion()`, `procMemberResendAuthMail()`, `procMemberAuthAccount()` 액션에는 트리거가 끼어들 여지가 없습니다. 따라서 별도의 테이블로 옮겨진 휴면계정 주인이 아이디/비번찾기를 시도하면 아예 존재하지 않는 계정으로 취급됩니다.

휴면계정 주인이 같은 아이디나 메일 주소로 다시 가입을 시도하는 것도 막아야 합니다. 안 그러면 휴면계정을 복원할 경우 중복이 일어나니까요. 다행히 이건 `procMemberInsert` `before` 트리거를 통해 구현할 수 있는데, 위에서 말했듯이 아이디/비번찾기에서는 존재하지 않는 계정이라고 하면서 회원가입을 시도하면 중복이라고 한다면 사용자가 혼란을 겪겠죠.

따라서 코어에서 로그인, 아이디/비번찾기, 인증메일 클릭 등 "인증"과 관련된 모든 작업 전후에, 성공 여부와 관계없이 항상 호출되는 트리거 (예: `member.authAttempt`) 를 제공해 주거나...

아니면 휴면계정 저장을 위한 테이블을 아예 코어에서 지정하고 (예: `member_expired`), 인증 시도시 항상 양쪽 테이블을 모두 확인하도록 해주면 좋겠습니다.

그것도 아니면 다른 테이블 이동은 포기하고, 최종 로그인 날짜를 기준으로 일괄 삭제하는 기능만 만들어 쓰면 됩니다.

한편, 잠깐 실행되고 마는 PHP 언어의 특성상 단체메일링 기능을 코어에서 구현하는 것은 불가능에 가깝습니다. 수십 건만 보내도 time limit에 걸려버립니다. 여러 번 나눠 보내더라도 일반 웹호스팅 환경에서는 휴면계정이 수백 개만 되어도 모두에게 안내메일을 보내는 것이 불가능합니다. 단독서버에서 쉘 스크립트를 사용하더라도 각 포털의 스팸정책 때문에 하루 수만 건 이상은 어렵습니다. 수년간 회원 계정을 엄청나게 쌓아 놓았지만 실제 방문자는 별로 없는 사이트의 경우, 결국 대량메일 발송 모듈과 유료 API에 의존할 수밖에 없게 되지요.

마지막으로, 돈 거래가 있었던 회원은 5년간 로그인하지 않아도 회원정보를 보존할 수 있고, 심지어 보존할 의무가 있을 수도 있습니다. 휴면계정 처리를 할 때 이런 회원은 제외해야 하는데, 쇼핑몰 모듈마다 거래내역 저장 형태가 다르기 때문에 파악이 어렵습니다.

**Comment by ForPeople** [comment]
xe_member 테이블에서 last_login 과 denied 컬럼만으로 제어할 수 있지 않을까요?
그냥 최근 로그인 날짜 받아서 매일 한번씩 체크하고 업데이트하는 함수를 호출한다 치고 denied 를 Y 로 업데이트 하면 다음 로그인시 메일인증을 해야한다거나 하는 부분만 수정해주면 되지 않을까 합니다.
문제는 주기적으로 호출해주는 crontab같은 것인데 웹 호스팅 유저들은 웹기반 크론탭 서비스를 별도로 사용할 수밖에 없을듯 합니다.

**Comment by kijin** [comment]
@ForPeople 그냥 `denied`만 변경하면 안되고, 회원정보를 아예 삭제하거나 별도의 공간으로 옮겨야 합니다. 별도의 공간이라는 조항은 대부분 별도의 테이블이라는 의미로 해석하는 것 같습니다. 인젝션 공격으로 `member` 테이블을 다 퍼가더라도 노출되지 않도록 말이죠.

**Comment by wkpark** [comment]
제가 다른 곳에서 밝혔던 것처럼 개인정보를 모두 날려버리는 방식은, 임의의 사용자에 의한 동일 ID로 재가입을 통한 사칭 문제를 막을 방법이 없습니다. (위키위키의 경우에는 더욱 중요한 문제)

따라서 가입한 후에 단 한차례도 글을 쓰지 않은 사용자의 경우에는 삭제를 해도 전혀 문제될 것이 없지만,
한번이라도 글을 남겼던 사용자는 중복가입을 막을 방식을 생각해봐야 합니다.

중복가입을 막으려면 적어도 사용자의 ID 및 이메일 정보는 보존해야 하는데, 이것도 개인정보에 들어가기때문에 raw값을 저장하면 안되고 변환된 값으로 저장하거나 하는 방식을 써야 할것입니다. 예를 들어서

1. 사용자 ID를 변환해서 저장 : 서버 설정값으로 `$db_info->seed='blahblah';`를 두고, seed + 사용자 ID 값을 md5sum으로 저장.
2. 사용자 email 주소 역시 같은 방식으로 저장.
3. 새로 가입을 하는 사용자에 대해서 ID값 및 seed+ID의 md5sum이 user_id컬럼이 있으면 이미 존재하는 ID로 판별. / email 주소에대해서 동일한 방식으로 중복 검사.

**Comment by kijin** [comment]
@wkpark XE는 동일한 아이디 및 메일주소로 재가입하더라도 `member_srl` 값이 다르기 때문에, 예전 회원이 쓴 글에서 "회원정보 보기"를 클릭하더라도 재가입한 회원의 정보가 나오지는 않습니다. 즉, 관리자나 다른 회원들이 쉽게 식별할 수 있습니다.

탈퇴 후 재가입 방지는 각 사이트의 필요에 따라 별도의 정책으로 관리해야 할 문제로 보입니다. 문제를 일으키는 회원을 강퇴시키면서 자동으로 금지아이디로 지정하는 애드온도 있었던 것으로 기억합니다. 코어에 메일주소를 금지시키는 기능이 없어서 반쪽짜리긴 하지만...

**Comment by wkpark** [comment]
@kijin 아하 그렇군요! 알려주셔서 감사합니다~

원칙적으로는 raw값으로 이메일을 저장한다면, 사용자의 이메일 정보를 수집한것이 되고 이를 이용해서 운영자/관리자가 홍보질을 한다거나 등등의 가능성도 있기때문에 이메일 및 사용자 ID는 파기하는 것이 맞을 것 같습니다. 제가 제시한 방식으로 md5 체크섬만 저장할 경우에는 문제가 없을 것으로 보이고요.

**Comment by kijin** [comment]
https://github.com/kijin/xe-member-expire 에서 작업 중입니다.

**Comment by kijin** [comment]
로그인 및 아이디/비번찾기를 할 때 휴면계정을 복원하거나 휴면상태임을 안내하는 기능은 `moduleObject.proc` `before` 및 `after` 트리거를 사용하여 구현하는 데 성공했습니다. 그러나 이 트리거는 인증관련 액션이 아니어도 무조건적으로 호출되기 때문에 모든 페이지의 로딩 속도에 영향을 미칠 수밖에 없습니다. 코어에서 추가적인 지원이 없다면 다른 방법은 없는 것 같고요...

금전거래 내역을 1년 이상 보존해야 하는 경우의 처리는 각 사이트 및 쇼핑몰 모듈에 맡겨야겠습니다. 아마 지금도 대부분은 회원정보와 별도로 보관되고 있지 않을까 합니다.

**Comment by kijin** [comment]
휴면계정 정리 모듈이 배포되었습니다.

공홈 자료실: https://www.xpressengine.com/index.php?mid=download&package_id=22753717

GitHub: https://github.com/kijin/xe-member-expire

이 이슈는 닫으셔도 될 것 같습니다.
