### ISSUE TITLE
업로더 다국어 지원 필요성

### ISSUE THREAD

**Issue by dorami** [xpressengine/xe-core#1668]
common/js/plugins/query.fileupload/js/main.js 에서

선택, 커버이미지로 선택

위와 같이 한국어로 코딩 되어 있습니다. 기본 방법 외 별다른 방법이 없나요?
이 부분도 다국어가 지원됐으면 좋겠습니다.

**Comment by YJSoft** [comment]
#1624

**Comment by dorami** [comment]
@YJSoft PR이 있었네요. 이슈 닫습니다.

**Comment by misol** [comment]
[라이믹스 브랜치](https://github.com/xetown/xe-core)에 집중하기 위해서 [이 이슈에 대한 PR](https://github.com/xpressengine/xe-core/pull/1624)을 제출하였으나 닫습니다.
