### ISSUE TITLE
데이터베이스 마이그레이션 기능 개선 필요성

### ISSUE THREAD

**Issue by upgle** [xpressengine/xe-core#1671]
현재는 컬럼에 대한 drop, create 를 지원하고 있지만 타입 혹은 이름을 변경하거나 속성을 추가하는 메소드가 존재하지 않습니다.
서드파티 개발자가 한번 배포한 모듈의 DB구조를 변경하기가 쉽지 않습니다.

**Comment by ForPeople** [comment]
모듈의 클래스 파일에서 제어가 가능하지 않나요?

**Comment by upgle** [comment]
column에 대해서는 아래 두 메소드만 지원되고 있는거 아니가요?
지금 XE는 modifyColumn 메소드가 없어 한번 생성된 컬럼은 설정을 바꿀수가 없습니다.

	function addColumn($table_name, $column_name, $type = 'number', $size = '', $default = null, $notnull = false)

	function dropColumn($table_name, $column_name)

**Comment by YJSoft** [comment]
#901

**Comment by upgle** [comment]
@kijin 꼭 있어야할 기능이라고 생각이 되는데 혹시 이슈(#901)를 닫으신 이유가 있으신가요?

**Comment by kijin** [comment]
@upgle 비번 암호화 패치를 작성할 때 일부 알고리듬이 60자를 넘어가기에 `member` 테이블의 `password` 필드 길이를 늘릴 목적으로 만들어 보았는데, 데이터 양이 많은 테이블에서는 시간이 너무 오래 걸려서 PHP 실행시간 제한에 걸리더군요. 자칫하면 데이터를 날려먹을 것 같아서, 결과 길이가 60자를 넘는 암호화 알고리듬은 모두 빼버렸습니다.

데이터는 전혀 건드리지 않고 `varchar` 길이 제한만 바꿔도 테이블을 새로 생성하는 멍청한 RDBMS가 있어요. 이름이 My 뭐라고는 말할 수 없습니다 ㅠㅠ 게다가 XE에서 공식적으로 지원하는 큐브리드 일부 버전은 컬럼 속성 변경이 아예 불가능합니다. 이래저래 안정적으로 구현하기는 힘들다고 판단했습니다.
