### ISSUE TITLE
[버그] 허용확장자 에러

### ISSUE THREAD

**Issue by phin1000** [xpressengine/xe-core#1673]
1.8.7 다른 버전은 테스트 못해봄.

관리자 > 설정 > 파일 업로드에서 허용확장자 입력 후 저장시 "invalid_extension" 에러 메시지
게시판 관리 > 추가설정 > 파일에서 허용확장자 입력시 "invalid_extension" 에러 메시지

**Comment by YJSoft** [comment]
`invalid_extension` 메세지는 코어에서 발생하는 것이 아닙니다.
사용중이신 서드파티 자료의 문제일 가능성이 큽니다.

**Comment by phin1000** [comment]
제 실수였습니다.
확장명을 여러개 입력하다보니 오타가 있었군요.

**Comment by hjhj3686** [comment]
확장자들을 입력할때 알맞은 형식으로 입력하지 않으면 invalid_extension 이란 문구를 띄워 버리는거 같습니다. 알림 메세지를 다국어 지원하는게 좋을거 같네요.
