### ISSUE TITLE
관리자 페이지의 푸터에서 Latest Version 이 표시되지 않습니다.

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1674]
보니 아예 받아오지 못해서 템플릿 조건문으로 표시가 되지 않는거 같습니다.
현재 Powered by XE. | Your version: 1.8.7 | 만 표시되고 있습니다.

**Comment by kijin** [comment]
XE 코어 쪽의 문제는 아니고, 최신버전 체크에 사용되는 API 서버에 일시적으로 장애가 발생한 듯 합니다. 해당 URL을 직접 요청해 보아도 `500 Internal Server Error` 에러만 나오네요.
