### ISSUE TITLE
모바일 글쓰기 개선

### ISSUE THREAD

**Issue by andjfrrk** [xpressengine/xe-core#1675]
ck 에디터로 바뀌면서, 조금 불편하긴 해도 모바일에서 위지윅 및 파일 업로드가 가능해졌습니다.

한 가지 문제가 있는데, 모바일에서 위지윅 에디터로 글(댓글) 수정(작성)시 nl2br 때문에 의미 없는 &lt;br&gt; 태그가 들어 갑니다.

nl2br 을 스킨 제작자나 사용자가 선택해서 쓸 수 있도록 아래와 같이 개선했으면 합니다.

xe 1.8.7
/modules/document/document.controller.php - line : 289
/modules/document/document.controller.php - line : 487
/modules/comment/comment.controller.php - line : 331
/modules/comment/comment.controller.php - line : 740

원래 코드 : $obj->content = nl2br($obj->content);
개선 코드
			if($obj->use_wysiwyg != 'Y')
			{
				$obj->content = nl2br($obj->content);
			}

'use_wysiwyg' 은 스킨에서 처리하면 되겠죠.

**Comment by izuzero** [comment]
#1490 #1495

**Comment by andjfrrk** [comment]
아. 진작 있었군요.
검색을 해보고 올렸어야 했는데.

이 이슈는 닫겠습니다.

**Comment by misol** [comment]
[라이믹스 브랜치](https://github.com/xetown/xe-core)에 집중하기 위해서 [이 이슈에 대한 PR](https://github.com/xpressengine/xe-core/pull/1495)을 제출하였으나 닫습니다.
