### ISSUE TITLE
POST 요청을 content-type json으로 보낼경우 일부 서버에서 오류

### ISSUE THREAD

**Issue by fromthere** [xpressengine/xe-core#1684]
http://stackoverflow.com/questions/19004783/reading-json-post-using-php
일부 서버에서 POST 요청을 content-type json으로 보낼경우, $_POST 값이 비어 버려서, 정상적으로 요청이 처리되지 않고 대신 메인 페이지가 JSON 포맷으로 반환됩니다. 아마 사이트 메뉴가 안 뜨신다는 분들도 이 문제 때문에 정상적으로 요청이 처리되지 않는 것 같습니다. JSON으로 요청할 때에는 GET을 사용하는 것이 호환성 측면에서 좋을 것 같습니다.

이하는 제 서버 정보입니다. nginx + php-fpm 으로 동작하고 있습니다.

[XE Server Environment 2015-07-30]

realpath : /var/www/public_html
location : ko
package : XE
host : https://******.**/
app : nginx/1.6.3
xe_version : 1.8.7
php : 5.6.11
db_type : mysqli_innodb
use_rewrite : Y
use_db_session : N
use_ssl : always
phpext : core, ereg, libxml, openssl, zlib, bcmath, bz2, calendar, curl, fileinfo, mbstring, mcrypt, pcntl, mysqlnd, pdo_mysql, phar, readline, mysqli, shmop, simplexml, sockets, mysql, sysvmsg, sysvsem, sysvshm, xml, xmlreader, xmlwriter, xsl, zip, cgi-fcgi, gd, iconv, memcache, mhash, zend opcache
(이하 생략)

**Comment by fromthere** [comment]
[php.net의 $_POST 정의](http://php.net/manual/kr/reserved.variables.post.php) 에 따르면, $_POST 값은
HTTP POST 요청이 `application/x-www-form-urlencoded`나 `multipart/form-data` 컨텐츠 타입으로 전성될 때 전달되는 변수라고 명시되어 있습니다. 따라서, POST 요청을 보내면서 `content-type`를 json으로 지정하는 것은 잘못된 동작을 유발시킬 수 있습니다. 다행히도, XE의 모든 json ajax 요청은 exec_json을 통해 이루어지므로 이 부분만 손보면 될 것 같네요. @bnu 

이하는 원문입니다.
```
An associative array of variables passed to the current script via the HTTP POST method when using application/x-www-form-urlencoded or multipart/form-data as the HTTP Content-Type in the request.
```

**Comment by fromthere** [comment]
다음 내용의 post.php 파일과
```php
<?php
$vars = new stdClass();
$vars->content_type = $_SERVER['CONTENT_TYPE'];
$vars->raw_data = var_export(file_get_contents('php://input'),TRUE);
$vars->post = var_export($_POST,TRUE);

echo json_encode($vars);
```
```js
request_uri = 'http://(주소)/post.php';var $ = jQuery;var params = {};var response_tags = new Array('menuList');params['menu_srl'] = 0;$.exec_json("menu.getMenuAdminSiteMap", params, function(data){console.log(data);}); 
```
위 자바스크립트 코드로 테스트 결과

```
Object {content_type: "application/json", raw_data: "'menu_srl=0&module=menu&act=getMenuAdminSiteMap'", post: "array (↵)"}
```
위 값이 반환됩니다.

**Comment by YJSoft** [comment]
XE는 이미
```php
	/**
	 * Handle request arguments for JSON
	 *
	 * @return void
	 */
	function _setJSONRequestArgument()
	{
		if($this->getRequestMethod() != 'JSON')
		{
			return;
		}
		$params = array();
		parse_str($GLOBALS['HTTP_RAW_POST_DATA'], $params);
		foreach($params as $key => $val)
		{
			$this->set($key, $this->_filterRequestVar($key, $val, 1), TRUE);
		}
	}
```
와 같이 json post값을 처리하고 있습니다.

**Comment by YJSoft** [comment]
#1686
