### ISSUE TITLE
file_get_contents("php://input")가 XML이 아니면 $GLOBALS['HTTP_RAW_POST_DATA']가 설정되지 않음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1686]
``` php
if(!isset($GLOBALS['HTTP_RAW_POST_DATA']) && version_compare(PHP_VERSION, '5.6.0', '>=') === true) {
    if(simplexml_load_string(file_get_contents("php://input")) !== false) $GLOBALS['HTTP_RAW_POST_DATA'] = file_get_contents("php://input");
}
```

simplexml_load_string(file_get_contents("php://input")) 이 false가 아닐때만, 즉 post body가 XML이 아닐 때에만 `$GLOBALS['HTTP_RAW_POST_DATA']` 변수 값이 설정됩니다.
이 때문에, `$GLOBALS['HTTP_RAW_POST_DATA']` 값을 설정하지 않는 php 5.6 이상 버전에서 exec_json으로 실행되는 액션이 전부 오동작하는 문제점이 있습니다.
json post body값은 당연히 XML이 아니고(`key1=value1&key2=value2` 형식입니다), 따라서 `$GLOBALS['HTTP_RAW_POST_DATA']` 값이 설정되지 않으므로 JSON 값을 불러오지 못하게 되는 것이죠.(덕분에 몇시간이나 삽질했습니다)

이는 #1684 같은 문제를 일으킬 수 있습니다. 왜 조건문이 있는지는 모르겠지만, XML일 때에만 `$GLOBALS['HTTP_RAW_POST_DATA']` 값을 사용하는 것이 아니므로 위 조건문은 없애야 맞는 것 같습니다. 조건문을 추가하신 것에 이유가 있나요?

**Comment by YJSoft** [comment]
@bnu 확인 부탁드립니다.

**Comment by YJSoft** [comment]
`$GLOBALS['HTTP_RAW_POST_DATA']` 변수를 항상 세팅하면 상황에 따라 HTTP 400 오류가 발생합니다.
현재 해결책으로는

* `file_get_contents("php://input")` 변수를 `parse_str` 함수로 처리하여 최소 한개의 변수가 배열에 지정될 경우에만 설정
* Request type이 `JSON`일때만 변수 설정(이외 요청은 `simplexml_load_string`로 확인하는 현재 방식 그대로도 문제가 없음)

두가지 정도를 생각하고 있습니다.

**Comment by misol** [comment]
XE 가 JSON을 지원하지 않던 시절에 들어간 조건문일거에요.

**Comment by YJSoft** [comment]
@misol 최근에 php 5.6을 대응하면서 추가된 부분입니다. 
https://github.com/xpressengine/xe-core/blame/master/classes/context/Context.class.php

**Comment by misol** [comment]
그렇군요

**Comment by qkrcjfgus33** [comment]
if(simplexml_load_string(file_get_contents("php://input")) !== false)
를 빼버리면 안되나요?

php://input의 경우 $GLOBALS['HTTP_RAW_POST_DATA'] 와 다른점이
ReadOnly 의 차이라고 하더라구요.

**Comment by YJSoft** [comment]
@qkrcjfgus33 그렇게 하면 로그인시 문제가 됩니다.(로그인이 안됩니다)

**Comment by qkrcjfgus33** [comment]
아, 그렇네요. 배우고 갑니다 :+1:

**Comment by YJSoft** [comment]
#1763 으로 fix됨
