### ISSUE TITLE
png 파비콘 지원 관련

### ISSUE THREAD

**Issue by bnnu** [xpressengine/xe-core#1687]
최근 출시된 대부분의 브라우저는 png 파비콘을 지원하며, 기본 파비콘 파일도 png인데 정작 파비콘 업로드는 ico만 가능한 것은 어색합니다.
다른 포맷은 몰라도 png 파일은 업로드가 가능해야 하지 않을까요?

**Comment by oasis123** [comment]
동의합니다 일반적인 브라우저에서 (IE 9.0 이상) 는 다 지원하는 것 같더군요
