### ISSUE TITLE
XE core  1.7.4 게시판에서 수정기능 

### ISSUE THREAD

**Issue by kyungheedo** [xpressengine/xe-core#1688]
XE core  1.7.4 게시판 생성해서 쓰고 있는데요 
작성된 글 수정이 안됩니다. (읽기와 목록에서 글 수정 버튼이 안나옴) 
해결 방법 부탁합니다

**Comment by bnu** [comment]
공식사이트 묻고답하기에 남겨주세요.

**Comment by misol** [comment]
묻고답하기에 올리시더라도, 조금 더 상황을 자세하게 남겨주세요.
자세하게 뭘 적어야 할지 모르겠다면 적어도 현상을 확인할 수 있는 사이트 주소라도 적어주셔야 답변이 가능할 것 같습니다.
