### ISSUE TITLE
날짜로 검색 에러 (regdate 불러오기 먹통)

### ISSUE THREAD

**Issue by oasis123** [xpressengine/xe-core#1691]
XE 기본 달력 위젯에서 날짜를 클릭하면 해당 날짜에 쓴 글만 보이는 기능이 예전엔 분명 되었는데 요즘은 잘 되지 않더군요. 이게 통합검색의 문제인지 아니면 SQL의 regdate값으로 검색하는 기능이 없어진건지..

일반적으로 달력 위젯에서 굵게 표시된 날짜를 누르면 http://도메인/xe/index.php?mid=어쩌구&search_target=regdate&search_keyword=날짜 이런 식으로 이동하게 되어 있는데 날짜로 검색하는 게 없어진 건지 어떤 사이트에서도 거의 제대로 동작을 않네요. 누르면 그냥 그 게시판(mid에 해당하는)으로 이동할 뿐 검색이 되질 않아요. 

여러 사이트에서 시도해보았는데 다 그렇더군요. 이게 단순 오류인지 아니면 뭔지 모르겠어요 ;;

**Comment by YJSoft** [comment]
원래 게시판에 등록일 기준 검색 자체가 없는 기능입니다.
그동안 작동하던 것이 오작동인 셈입니다.

**Comment by oasis123** [comment]
그렇군요.. 그러면 board_class.php 를 수정하는 수밖에 없겠네요 감사합니다
