### ISSUE TITLE
회원 정보 조회/수정폼 오타로 인한 폼 깨짐 현상 해결

### ISSUE THREAD

**Issue by treasurej** [xpressengine/xe-core#1692]
회원 정보 조회/수정폼 오타로 인한 폼 깨짐 현상 해결

**Comment by treasurej** [comment]
https://github.com/xpressengine/xe-core/compare/master...treasurej:patch-1

**Comment by qw5414** [comment]
해당 링크를 직접 Pull넣으시면됩니다.

pull생성하시고, XpressEngine의 Xe-core `develop`브랜치로 전송하시면 됩니다.
