### ISSUE TITLE
허용확장자 에러

### ISSUE THREAD

**Issue by phin1000** [xpressengine/xe-core#1696]
관리자페이지>설정>파일업로드와
게시판설정 > 추가설정>파일에서
확장자 지정해도 적용되지 않습니다.(모든 확장자 업로드됨)

**Comment by YJSoft** [comment]
관리자는 설정과 상관없이 모든 확장자를 업로드할 수 있으며, 용량 제한 또한 무시하고 php.ini에 지정된 최대 용량까지 업로드할 수 있습니다. 일반 사용자 계정으로 테스트해 보시면 정상 적용됩니다.

**Comment by phin1000** [comment]
아!
아무래도 내가 더위먹은 것 같군요.ㅠㅠ
이런 걸 착각하다니...
감사합니다.
