### ISSUE TITLE
profiler 에서의 함수가 실행되지 않아 디버깅 결과..

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#1701]
`ProfilerAdminModel::getTriggersToBeDeleted()`
함수내에서 사용되는
`moduleModel::getTriggers()` 함수에 문제점이 있음.
각각의 정보가 너무 불규칙적으로 Array값으로 저장햇다 빠져나갓다 하는 현상이 발생됨.

즉, 여기서 원하는 방향은 각 트리거1개당 그 속에 있는것들을 각각 가져오는 방식이였더라면
이건 모듈 1개속에 들어있는 트리거를 또 가져오는 방식이됨.
(자세한 규칙을 모르겠어요 이렇게 추정됨..)

이게 문제점이 있는게 보통은

```
$oModuleModel = getModel('module');
$trigger_list = $oModuleModel->getTriggers();

debugPrint($trigger_list);
```

이렇게 사용해보면, 실제 debugPrint에서 보여주는 내용은
`NULL`으로 표시됨.

즉, array으로 보여주는 형태가 아니고 각각 또 array이 또 불규칙적으로 2개, 3개 씩 더 불러오고 그러다보니 전체적인 데이터를 얘가 가져올수 없는것으로 보여짐.

이건 직접적으로 현재사용한것에서 debug해봐야 증상을 확인이 가능함..

그래서, 기존 profiler모듈 내에서 없는 트리거 목록을 가져오지 못하는 문제점이 발생됨.

https://github.com/xpressengine/xe-core/commit/a38d7703fdf337c09515d30e93ae75f535970923
여기 코드에서 적용됬던듯..

실제 영상을 녹화하다가.. 이 부분에 문제점을 발견해서 디버그 과정도 채크해서 영상 업로드 하겠음..;ㅁ;

으헝.. 모듈 탐방 방송 망했서..;ㅁ;

**Comment by qw5414** [comment]
https://www.youtube.com/watch?v=zFO13cJak3s
영상에서 프로파일러의 목록을 못가져왔던 부분
20분부터 보시면될듯합니다. 기존의 풀더를 지우고 나서 반응을 살펴보던 과정이였습니다.
그래서 여러가지 반응을 찾다가.. 29분 15초쯤 DB에 접속해서 봤을땐 DB에 트리거 목록이 있엇던 것을 발견.

36분 45초부터 profiler 설치및 디버그하는 부분이 시작됩니다.
