### ISSUE TITLE
게시판 생성 안 됩니다

### ISSUE THREAD

**Issue by simsimhae** [xpressengine/xe-core#1703]
업데이트 전 잘 되었는데 업데이트 이후 안됩니다.
시정 하세요

**Comment by izuzero** [comment]
이건 무슨?

**Comment by simsimhae** [comment]
![image](https://cloud.githubusercontent.com/assets/13744920/9241292/833d6438-41ac-11e5-9461-ce47e135c1c8.png)
생성 버턴이 없읍니다.
빨리 시정 하세요

**Comment by YJSoft** [comment]
![image](https://cloud.githubusercontent.com/assets/5893514/9241365/81343044-41ad-11e5-864f-0c449836a94d.png)
1.7 이후 게시판 생성은 사이트 메뉴 관리에서 가능합니다.
