### ISSUE TITLE
제가 db에서 뭘 삭제한 이후로 ㅠㅠ

### ISSUE THREAD

**Issue by hicongnet** [xpressengine/xe-core#1705]
레이아웃이 안나타나요..
게시판에 글을 쓰면 젤 위에 써지는게 아니라
젤 첫페이지에 써져요..ㅠㅠㅠㅠ 1번페이지에 ...최신글이 10페이에 있으면 10페이지에 생겨야하는데..
뭘 어떻게 해야할까요

**Comment by YJSoft** [comment]
[공식사이트 묻고 답하기 게시판](https://www.xpressengine.com/qna) 에 올려 주세요.
