### ISSUE TITLE
[다국어] 회원가입시 메시지가 다국어로 나오지 않고, 한글로 나오는 문제

### ISSUE THREAD

**Issue by treasurej** [xpressengine/xe-core#1737]
![signup_en](https://cloud.githubusercontent.com/assets/4101147/9622670/49d2ecb6-5171-11e5-93ab-753cd784197f.png)

[다국어] 회원가입시 메시지가 다국어로 나오지 않고, 한글로 나오는 문제

**Comment by YJSoft** [comment]
@treasurej 해당 부분은 브라우저에서 출력하는 부분으로 XE와 무관합니다.
브라우저 설정을 영어로 바꾸면 해당 부분도 바뀝니다.

**Comment by treasurej** [comment]
@YJSoft 앗! Close.. 감사합니다^^
