### ISSUE TITLE
사이트 메뉴 편집과 사이트 디자인 설정만 오류가 납니다.

### ISSUE THREAD

**Issue by waydodo** [xpressengine/xe-core#1739]
XE 1.8.9를 새로 설치했고요.

작동은 모두 정상적으로 돌아갑니다.

그런데 유독 "사이트 제작/편집"에 있는 '사이트 메뉴 편집과 사이트 디자인 설정' 메뉴만 누르면 

아래의 에러 메시지가 나옵니다.

모든 페이지가 정상입니다. 관리자 페이지도 정상적으로 작동하고요.
도와주세요.

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

[참고로]
이곳 저곳 서치해서 아래 내요은 해 보았습니다.
use_rewrite : Y =>을 'N'으로도 바꾸어 보았고요.
XE의 퍼미션을 755로
index.pgp를 644로 수정했습니다.

수십번도 넘게 XE를 설치해 보았지만 이런 경우는 처음이네요.
도와주세요.
# 

아래는 서버에 관한 정보입니다.
[XE Server Environment 2015-09-05]

realpath : /home/linweb09/w/wimbledonkoreanbaptist.org.uk/user/htdocs/xe
location : ko
package : XE
host : http://wimbledonkoreanbaptist.org.uk/xe/
app : Apache
xe_version : 1.8.9
php : 5.4.44
db_type : mysql
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bz2, calendar, curl, fileinfo, ftp, gettext, gmp, iconv, pcntl, readline, phar, shmop, simplexml, sockets, mbstring, sysvmsg, sysvsem, sysvshm, wddx, xml, cgi-fcgi, bcmath, dba, gd, imap, ldap, exif, mcrypt, mssql, mysql, mysqli, odbc, pdo_dblib, pdo_mysql, pdo_odbc, pdo_pgsql, pdo_sqlite, pgsql, pspell, snmp, soap, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, mhash, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.2), krzip(1.8.0), syndication(4.0)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0)
layout : xe_official(1.7), xedition(1.9), user_layout(1.7)
widget : counter_status(1.7), newest_document(1.0)
widgetstyle : lineBox(0.1), simple(1.7), xdt_windless(1.0)
max_file_uploads : 20
post_max_size : 20M
memory_limit : 64M

**Comment by devflow** [comment]
제 예전 경험으론 use_rewrite 사용 유무에 상관없이  아파치에 rewrite mod가 설치되어있지않아서 발생했습니다. 확인부탁드립니다.

**Comment by totofox** [comment]
1. 이상 현상
   
1). "사이트 메뉴 편집"의 내용에 아무 것도 나타나지 않으며 "찾기"버튼을 눌러도 동작하지 않습니다.
하단에 있는 "사이트맵 추가" 버튼을 누르면 추가할 수 있는 박스가 우측에 나타납니다. "사이트맵 이름"의 필드에
 입력하고 "확인"버튼을 눌러도 동작하지 않습니다.

2). "사이트 디자인 설정"에는 "PC"탭에 "XEDITION" 레이아웃 하나와 바로 밑에는 "레이아웃[레이아웃 사용 안 함]"이 나타납니다.
"레이아웃[레이아웃 사용 안 함]"을 클릭하면 우측에 "레이아웃" 박스가 나타나며 그 내용에는 "레이아웃 사용 안 함"과 "다른 레이아웃 설치"중 하나를 선택(라디오 버튼)하도록 되어 있군요.
"다른 레이아웃 설치"를 선택하면 우측에 "다른 레이아웃 설치"가 나타나고 그 내용에는 "다운로드 가능한 항목이 없습니다."로 되어 있습니다.
 

2. XE 1.8.9 설치의 과정


1) Windows 8.1과 아래와 같이 APM를 새로 설치했습니다.
     1) Apache24 : httpd-2.4.16-win64-VC11.zip
     2) Mysql5 : mysql-5.6.26-winx64.zip
     3) PHP5 : php-5.6.13-Win32-VC11-x64.zip 
   

2) XE 1.8.9의 설치를 위해 xe/index.php로 들어가자 바로
"Internal Server Error"의 메시지가 나타납습니다.
그래서 apache의 "httpd.conf" 파일에서 
"LoadModule rewrite_module modules/mod_rewrite.so"부분을 주석제거한 후 
XE를 설치할 수 있었습니다.

3) 그러나 XE가 제1항과 같은 "이상 현상"이 나타나므로
이를 해결하기 위해서 홈(xpressengine.com)를 서핑한 결과 
많은 분이 동일한 이상 현상이 있음을 알게 되었고, 몇 분이 해결책으로서 
다음과 같이 "php.ini" 파일을 수정하도록 제시하였습니다.
그대로 조치하였으나 저의 경우에는 마찬가지의 현상입니다.

        (1) always_populate_raw_post_data = -1     *.주석제거
        (2) display_errors = Off                        *. On에서 Off으로
        (3) display_startup_errors = Off           *. On에서 Off으로

**Comment by waydodo** [comment]
"devflow"님께서 제시해 주신 "아파치에 rewrite mod가 설치되어있지않아서 발생했습니다."를 수정해도 이상현상이 고쳐지지 않네요.

**Comment by devflow** [comment]
@waydodo Apache 에러 로그를 살펴보시는것이 좋을 것같습니다..
