### ISSUE TITLE
ie11에서 jquery 오류가 납니다. 

### ISSUE THREAD

**Issue by garnecia** [xpressengine/xe-core#1740]
![k-005](https://cloud.githubusercontent.com/assets/12852912/9710818/1ffc3e18-5579-11e5-939b-88c72516cfb6.png)

이렇게 ie11에서 분류가 제대로 표현이 안됩니다. 

이와같은 오류가 전반적으로 나오는데, 개발자도구를 봐도 바로 표현이 안나와서 

스크린샷만 남깁니다.

**Comment by YJSoft** [comment]
![works](https://cloud.githubusercontent.com/assets/5893514/9711416/71d3e52e-557e-11e5-9ce1-75cf26b0aeca.PNG)
제 환경에서는 잘 되는데요, 어느 스크립트에서 오류가 나는지 콘솔창을 캡쳐해서 올려주시면 확인해 보겠습니다.
