### ISSUE TITLE
메뉴에 i태그로 아이콘 사용

### ISSUE THREAD

**Issue by samswnlee** [xpressengine/xe-core#1751]
이번 패치로 메뉴에 태그사용이 제한된걸로 알고 있습니다.

그전까지는 

\<i class=' '>\</i>메뉴이름 

형태로 사용하였습니다만.. 
앞으로는 사용이 불가능한건가요?  

XEIcon도 위의 방식을 사용하고 있는줄로압니다만
개선이 되었으면 좋겠습니다.

현재는 db에서 직접 수정하여 사용중입니다.

**Comment by YJSoft** [comment]
1.8.11을 적용하시면 태그 사용이 가능해집니다
