### ISSUE TITLE
XE Core 1.8.10 이후 메뉴 다국어 기능을 사용할 수 없음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#1752]
1.8.10이후 메뉴 아이템의 태그를 제거하면서, 다국어 기능을 사용할 수 없습니다.
`$user_lang->userLang20150916162252057` 형태가 `$user_lang-&gt;userLang20150916162252057` 와 같이 escape되면서 다국어로 인식되지 않는 부분으로, 다국어 문자열이 변경된 이후 필터링을 해야 합니다.

**Comment by choongki** [comment]
다국어 문자열이 변경된 이후 필터링을 해야 한다는 말씀은 저렇게하면 해결이 되는것인지요?
저도 다국어 페이지 제작중인데 업데이트 이후로 엉망이 되어 버렸습니다. http://ahreuk.cafe24.com

**Comment by YJSoft** [comment]
@choongki DB에서 해당 메뉴를 찾으셔서 이름의 `&gt;` 를 `>` 로 바꾸시면 됩니다.

**Comment by kijin** [comment]
임시 해결책: https://www.xetown.com/lakepark/11336

**Comment by wookho** [comment]
@YJSoft 저희도 지금 메뉴수정은 하지 않고 페이지 자체를 수정하다가 이경우를 당했습니다. 조금 자세히... 메뉴를 찾는것도 어렵네요.

**Comment by YJSoft** [comment]
@wookho 위 @kijin 님이 올리신 링크 참고해주세요.

**Comment by wookho** [comment]
@YJSoft 저희는 db에서 찾아보아도 그렇게 변한메뉴는 없구요. 예상되는 메뉴가 메뉴명이 그냥 한글로 되어 있습니다.

**Comment by wookho** [comment]
아.. 바로가기메뉴가 따로 있어서 혼돈했네요. 임시조치했습니다. 감사합니다.
