### ISSUE TITLE
기존에 존재하는 모듈의 메뉴 연결 

### ISSUE THREAD

**Issue by snowall** [xpressengine/xe-core#1755]
업데이트 하면서 기존에 존재하는 모듈을 메뉴에 다시 연결할 필요가 생겼는데 방법이 없네요.
일단 사용 버전은 XE 1.8.11 입니다. 

상황은 다음과 같은데요,
기존에 axon이라는 mid를 가지는 게시판이 있었는데, 사용하지 않아서 메뉴에서 뺐습니다. 그리고 업데이트를 했고요. 이제 이걸 다시 사용하기 위해서 추가하려고 보니, 사이트 메뉴 편집에서 기존에 존재하는 모듈이지만 메뉴에 없던 것들은 연결할 수가 없게 되어 있네요. 검색해보니 temporary_menu라는게 생겨서 거기서 갖고 오면 된다고 하는데, 어떻게 된건지 모르겠지만 안보입니다. (업데이트를 제가 직접 한게 아니라 저 말고 다른 관리자가 해서 어떻게 된건지 모르겠습니다. 그 관리자는 컴맹인지라.....)

또한, home 모듈이 존재했는데, 이 모듈이 메뉴에는 존재하지 않지만 사이트 첫 페이지로 기능하고 있었습니다. 실수인지 뭔지 모르겠으나 home 모듈이 더이상 첫 페이지로 기능하지 못하게 되어서, 첫 페이지로 다시 지정하기 위해서 '사이트 메뉴 편집'에 갔더니 거기서는 위의 문제와 같은 이유로 추가할 수가 없고, '일반'의 '홈페이지'에서 지정하려고 보니 메뉴에 없어서 고를 수가 없습니다. 
1. 기존에 존재하는 모듈을 메뉴에 추가할 방법이 필요합니다.
2. 기존에 존재하는 모듈을 홈페이지로 지정할 방법이 필요합니다. 

https://www.xpressengine.com/forum/21788106
위의 페이지에 있는 글을 참고해서 시도해 보았으나 실패했습니다.

**Comment by RapidWorkers** [comment]
스크린샷 등을 첨부해주시면 오류 확인에 도움이 됩니다.
