### ISSUE TITLE
XEDITION 레이아웃 메뉴 반응형 버그

### ISSUE THREAD

**Issue by cococob** [xpressengine/xe-core#1769]
xedition 메뉴관련 버그가 있습니다~~~!

**Comment by cococob** [comment]
(xedition 수정레이아웃이 아닌, xe순정 레이아웃입니다)

1

메인형 메뉴타입: 매거진형 header with bottom menu

서브형 메뉴타입: 매거진형 regular header

으로 설정(다른 설정에서도 마찬가지였던 것 같습니다)

2

사이트메뉴편집>디자인>모바일뷰사용 체크안함 (xedition을 모바일에서도 사용하기 위해서)

이렇게 설정한 경우입니다.

 

즉, 화면을 모바일 사이즈로 줄여서 메뉴를 클릭해서 잘 펴지는지? 확인 후 다시 풀스크린으로 펴보면, 

(추정하기에 아래부분이 문제를 일으키는듯)

<nav class="gnb pc-gnb" id="gnb"> 

            </nav>

으로 적혀있는 부분이 아에 표시되지 않습니다.

구글에서 요소보기해도 오류라고 적혀져있진 않네요 해결해보려 노력은 하려 하는데 이미 파악하신 분이나 혹시 아시는 분 도움좀 주시면 좋겠습니다!

**Comment by cococob** [comment]
여기 위에 제목 주소로 가면 원문글이 있어요~~!

**Comment by YJSoft** [comment]
이슈 제목은 이슈를 한번에 알 수 있도록 적어주세요. ex. XEDITION 레이아웃 메뉴 버그
링크 등을 달으시면 이슈 목록에서 어떤 이슈인지 파악하기 힘듭니다.
