### ISSUE TITLE
xe 1.8.11 에서 "회원 가입 후 이동할 페이지" 동작 문제

### ISSUE THREAD

**Issue by paulryu03** [xpressengine/xe-core#1771]
안녕하세요. xe 1.8.11 에서(이전 버전부터 문제가 있었던 것 같은데 어떤 버전부터인지는 모르겠습니다), 아래와 같이 했을 때 문제가 발생합니다.
1. "사이트 제작/편집" 에서 외부페이지로 메뉴를 하나 만듦니다( 예로, Greeting 이라고 만들었다고 가정).
2. 페이지 모듈에서 Greeting 에 외부페이지를 링크 걸어줍니다.
3. "회원 설정/회원가입"에서 "회원 가입 후 이동할 페이지"를 통해서 위에서 만든 메뉴를 "찾아서 지정"해 줍니다.
4. 이제 마지막으로 회원가입을 시도하면, 회원가입 후에 위에서 지정된 모듈을 통해서 해당 외부페이지가 나타나야 정상인데 "페이지를 찾을 수 없다"고 404 에러가 나옵니다. 그래서 주소창에서 주소를 확인해 보니...

예상되는 정상적으로 표시되어야 할 주소:
http://www.address.com/xe/index.php?mid=Greeting

현재는 아래와 같이 표시:
http://www.address.com/xe/Greeting
그러면서 404 에러가 납니다.

회원 가입 후 이동할 페이지를 직접 입력할 수 없기 때문에 수정도 할 수 없는 상황입니다. 전에는 분명 정상 작동했던 기능이었는데 언제부터인지 최신 버전으로 오면서 위와 같이 오동작하는 것 같습니다. 확인 부탁드립니다. 감사합니다!!!

**Comment by YJSoft** [comment]
#1657 을 참고하셔서 수정하시거나 다음 릴리즈를 기다려주세요.

**Comment by paulryu03** [comment]
아... 이미 두 달 전에 논의가 됐던 것이군요. ㅠ 답변 감사드립니다!
