### ISSUE TITLE
SSO 처리 부분 버그

### ISSUE THREAD

**Issue by hkkiw0823** [xpressengine/xe-core#1773]
xe/classes/context/Context.class.php

 662번 라인부터의 SSO 처리 소스입니다.
		
// for sites recieving SSO valdiation
		if($default_url == self::getRequestUri())
		{
			if(self::get('default_url'))
			{
				$url = base64_decode(self::get('default_url'));
				$url_info = parse_url($url);

				$oModuleModel = getModel('module');
				$site_info = $oModuleModel->getSiteInfoByDomain($url_info['host']);
				if(!$site_info->site_srl) {
					$oModuleObject = new ModuleObject();
					$oModuleObject->stop('msg_invalid_request');

					return false;
				}

				$url_info['query'].= ($url_info['query'] ? '&' : '') . 'SSOID=' . session_id();
				$redirect_url = sprintf('%s://%s%s%s?%s', $url_info['scheme'], $url_info['host'], $url_info['port'] ? ':' . $url_info['port'] : '', $url_info['path'], $url_info['query']);
				header('location:' . $redirect_url);

				return FALSE;
			}
			// for sites requesting SSO validation
		}

getSiteInfoByDomain 를 통해 가져오는 값이 DB에는 http://아이피/xe 이렇게 저장되있고
				$url = base64_decode(self::get('default_url'));
				$url_info = parse_url($url);
이렇게 parse_url 을 통해 가져오는 값( $url_info['host'] ) 은 아이피(host)만 담겨있는데 
아무리 봐도 버그 같은데 의도하신건가요???

저렇게 검증하면 절대로 참값이 안나올텐데...

이건 쿼리문을 담은 xml 파일 내용 일부분이구요 저 소스가 맞다면 최소한 like 문이여야하는데 equal 로 처리하네요 흠..
condition notnull="notnull" var="domain" column="sites.domain" operation="equal"

**Comment by qw5414** [comment]
최신버전에서부터 생긴 문제점인가요..?

@kijin 님께서 SSO관련 새션관련 취약점을 보안하는 방법으로 최근 코드가 수정되었는데 해당 부분과 연관이 될련지요?

**Comment by kijin** [comment]
@qw5414 저는 버그 제보만 했고 직접 패치를 작성하지 않았기 때문에 잘 모르겠네요. 코드를 훑어보니 도메인과 host의 구분이 애매하긴 합니다만... 실제로 테스트를 해봐야겠어요.

**Comment by qw5414** [comment]
@kijin 앗! 그런거였군요 ㅎ 실례를 범했네요 죄송합니다.ㅠ 해결방법도 같이 제공 해주신 것으로 알고 있었어요. 관련 부분의 해결방법을 패치전에 알려드리면서 주신것 같아서요 ㅎ

**Comment by hkkiw0823** [comment]
당연히 최신버전에서 새로 설치하고 테스트했어요~

DB에 저장할때는 http://아이피/xe 이런식의 url 형태구요

메소드 명은 getSiteInfoByDomain 이와 같이 By Domain 인데 DB엔 URL 형식입니다.

**Comment by kijin** [comment]
테스트해 보니 정말 문제가 있네요.

    $site_info = $oModuleModel->getSiteInfoByDomain($url_info['host']);

이 줄을

    $site_info = $oModuleModel->getSiteInfoByDomain(rtrim($url, '/')); 

이렇게 바꾸면 되는 것 같은데, 다른 분들도 테스트 부탁드립니다.

**Comment by hkkiw0823** [comment]
XE 소스를 다 안봐서 모르겠지만 메소드 명이 By Domain 인걸로 보아 XE 개발자가 의도한대로라면 domain 명이 들어가는게 맞고  DB에서 xe_sites 테이블 -> domain 컬럼에 URL 말고 domain명을 저장해야 하지 않을지요

이부분은 개발자분이 판단하시는게 좋을듯합니다.

**Comment by kijin** [comment]
`domain`에 도메인이 아닌 주소 전체가 들어간 지는 꽤 오래 되었습니다. 이름이 맞지 않는 건 사실이지만, 이제 와서 고치기는 힘들 것 같고요...

이름과 실제 용도가 다른 부분은 그것 뿐이 아니예요. 예를 들어 `$default_url` 변수에는 기본 URL이 들어가지만, 실제로 주고받는 `default_url` 파라미터에는 기본 URL이 아니라 SSO 세션정보를 돌려받을 URL이 들어가요. 소스를 읽는 입장에서는 혼란스럽기 짝이 없죠 ㅠㅠ

또 하나... SSO 체크에 실패했을 때 실행하는 아래의 코드는

    $oModuleObject = new ModuleObject();
    $oModuleObject->stop('msg_invalid_request');

아무 효과가 없어요. 잘못된 요청이라는 메시지를 생성하지만 정작 `DisplayHandler`를 호출하지 않기 때문에 그 메시지는 표시되지 않고 그냥 백지화면만 뜹니다.

이래저래 문제가 많은 함수입니다.

**Comment by kijin** [comment]
#1775
