### ISSUE TITLE
1.8.11 업그레이드 후 이미지 갤러리 작동 안되는 현상

### ISSUE THREAD

**Issue by djclamo** [xpressengine/xe-core#1776]
[재현 환경]
LAMP
XE 1.8.11
XE Official Skin 을 이용한 게시판을 생성

[재현 스텝]
1. 1.8.9 에서 XE Official Skin 을 이용한 게시판을 생성
2. 게시판 -> 스킨관리 -> 기본형태: 갤러리
3. 게시물 작성 -> 이미지 업로드 -> 확장 컴포넌트 -> 이미지 갤러리 사용
4. 게시물 등록 -> 이미지 갤러리 작동 확인
5. 1.8.11를 다운로드 한 후에 파일들을 덮어 씌우는 방식으로 업그레이드
6. 이미지 갤러리가 정상적으로 보이지 않는 오류 확인

[Expected Result]
1.8.9 에서 1.8.11로 업그레이드 후, 이미지 갤러리 컴포넌트가 정상적으로 작동해야 함.

**Comment by YJSoft** [comment]
증상이 재현되지 않습니다. 정확히 어떤 오류인지, 자바스크립트 오류라면 어떠한 오류인지 적어 주시면 재현에 도움이 됩니다.

**Comment by djclamo** [comment]
![xebug](https://cloud.githubusercontent.com/assets/13039529/10731911/d40ad9f8-7bb4-11e5-9d71-24f6da5d79a7.PNG)

브라우저에서 에러를 뱉어내지는 않습니다. .13 에서도 같은 버그가 나네요.
위 캡쳐같이 Loading images 에서 사진들이 로딩되지 않습니다.
