### ISSUE TITLE
외부 페이지 내 위젯 캐시파일 재생성 되지 않는 문제

### ISSUE THREAD

**Issue by tuna0611** [xpressengine/xe-core#1779]
외부 페이지를 메인으로 사용하고 거기에 위젯을 붙여다가 사용하고 있습니다.
모듈 설정에서 캐시시간은 0분이고, 위젯 캐시는 10분으로 했는데, 캐시파일 재생성을해도 적용되지 않습니다.

관리자 페이지 하단에 있는 캐시파일 재생성을 눌러야 적용되네요.
ㅡ XE 최신 순정버전 설치해서 테스트해봐도 동일한 증상입니다.

**Comment by YJSoft** [comment]
외부페이지 하단의 캐시파일 재생성은 외부페이지 자체의 캐시파일을 재생성하는 것으로, 외부페이지 안에 삽입한 위젯 코드의 캐시는 재생성되지 않습니다. 이는 정상으로, 이슈가 아닙니다.

각 페이지별 캐시파일 재생성이 꼭 필요하시다면, 외부 페이지 대신 위젯 페이지를 사용하되, 외부 페이지 부분은 https://www.xpressengine.com/index.php?mid=download&package_id=22753403 외부 페이지 위젯 자료로 출력하시는 것을 권장드립니다.

**Comment by tuna0611** [comment]
임시 해결책입니다. 필요하신분 참고하세요.
http://lab.hv-l.net/173241
