### ISSUE TITLE
1.8.11 버전 사용중. 권한 없는 게시물에 메타정보 콘텐츠 및 제목이 노출됨.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#1784]
![_101915_013520_am](https://github-cloud.s3.amazonaws.com/assets/4381756/10565013/f11df0ce-7601-11e5-91ed-f9cfe00026d8.jpg)
분명 권한이 없는 상태에서 메타 정보의 글제목 및 글 내용이 노출됩니다.

검색봇이 충분히 document_srl 만 파악하면, 글 내용이나 글의 내용을 알 수 있을 것 으로 보여집니다.

**Comment by misol** [comment]
SEO 모듈이나 메타태그 자동입력 애드온 사용중이신가요?

**Comment by qw5414** [comment]
SEO모듈이 설치되어있지만, 애널리틱스 기능만 현재 사용중인듯 합니다.

**Comment by smaker** [comment]
SEO 모듈에서 해결해야할 이슈가 아닐까요?
