### ISSUE TITLE
CKEditor 업데이트 이후 문제점..

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xe-core#1785]
php스톰에서 코드를 복사한뒤 CKEditor에 붙여넣기 할경우 pre태그를 통한 해당 색깔을 그대로 가져오게 됩니다.

이번 업데이트가 있고 난다음 Pre태그만 먹히고, 해당 배경색이나 등등의 스타일리스트가 붙여넣기가 불가능해졌습니다.

제가 원하는 결과값은 
![_101915_063331_am](https://cloud.githubusercontent.com/assets/4381756/10566775/51dd3f54-762b-11e5-8f72-104a8bc2aaa7.jpg)
이렇게 보여지기를 원하고 있지만, 해당 결과물은 실제로 코드 엔터부분도 재대로 적용되지 않은체 흰색 바탕에 검은색 글자만 덩그러니 있습니다..
해당 부분을 확인 부탁드리겠습니다.
(이번 업데이트와 함께 CKEditor가 업데이트 되었길래..)

기존의 사용하는 공간에서는 문제 없이 사용되었습니다.

**Comment by qw5414** [comment]
사용해보니.. 윈도우 크롬에서의 문제점이네요. 최신버전에서 해당 문제점이 발생되고 익스는 모르겟지만 파폭에서의 정상적 동작은 확인했습니다.

**Comment by bnu** [comment]
위 이미지의 HTML 원본 코드를 알려주세요.

**Comment by qw5414** [comment]
@bnu 해당 코드가 문제가 아니라
복사 이후 붙여넣기 하면 단순히
```html 
<pre>내용 내용 내용</pre>```
형태로만 바뀌게 됩니다. (즉 스타일CSS가 하나도 붙지 않아요..)

**Comment by bnu** [comment]
@qw5414 
붙여넣기 시 필터에 의해 콘텐츠를 변경하는 것으로 보입니다.
http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-pasteFilter

common/js/plugins/ckeditor/ckeditor/config.js 파일을 생성하여 이 설정을 변경할 수 있습니다
```
CKEDITOR.editorConfig = function( config ) {
	config.pasteFilter = null;
};
```

**Comment by qw5414** [comment]
@bnu 해당 말씀해주신 부분 확인 했습니다.
하지만, 확인과정에서, `common/js/plugins/ckeditor/ckeditor/config.js `을 생성해도 자동적으로 불러오지 않는 부분이 있더군요..

이부분은 어떻게 처리를 해야하는건지..
해당 부분을 자동으로 인식하여 Load해주는 부분이 없더군요.
만일 추가해야한다면..

```html
<!--@if(!FileHandler::exists('common/js/plugins/ckeditor/ckeditor/config.js'))-->
<load target="../../../../common/js/plugins/ckeditor/ckeditor/config.js" />
<!--@end-->
```

으로 처리를 해야하지 않을까 생각됩니다.

**Comment by YJSoft** [comment]
@qw5414 따로 지정하지 않을시 ckeditor 설치 경로의 config.js를 불러오도록 되어 있습니다. 다만 config.js 파일이 없다면 불러오지 않도록 `<!--@if(!FileHandler::exists('common/js/plugins/ckeditor/ckeditor/config.js'))-->CKEDITOR.config.customConfig = '';<!--@endif-->` 로 파일 지정을 비우고 있습니다.

**Comment by qw5414** [comment]
@YJSoft 직접 파일을 해당 경로에 그대로 생성이 되어있지만, 실제로는 불러오지 않아 문제점이 발생되어서요.
따로 파일을 지정하거나, 해당 부분의 메뉴얼이 많이 없어 사용자입장에서 혼돈을 할 수 잇다는 생각이 들기도 하네요.

**Comment by bnu** [comment]
config.js 파일은 CKEditor에서 자동으로 로드합니다.

**Comment by qw5414** [comment]
@bnu 혹시 자동로드 되는 부분의 코드가 어디쯤 잇는지 확인가능한가요?
최신버전 기준에서요~~

**Comment by bnu** [comment]
@qw5414 
https://github.com/ckeditor/ckeditor-dev/blob/a122cdbfcdf7e4bf2aa04794bc147b6dbf286242/core/editor.js#L249-L289

**Comment by qw5414** [comment]
@bnu 신기하네요..
자동적으로 Config.js파일을 해당 경로에 있으니깐.. 겉으로 config.js파일을 불러오는 부분이 전혀 존재하지 않아도 해당 코드가 적용이 되네요..저는 브라우저 소스코드보기시 해당 부분을 불러오지 않는것으로 보여, 해당 부분을 불러오지 못하도록 하고 있는것인줄 알고 있었습니다.

혹시, 기본 코어내에서 `config.pasteFilter = null;` 이 옵션을 사용하실 계획은 없으신지요?

**Comment by bnu** [comment]
@qw5414 
config.js 파일은 CKEditor 자체에서(에디터 스킨을 가리키는 것이 아님) 로드합니다.
반영 요구가 많다면 검토하겠습니다.

**Comment by qw5414** [comment]
아 넵.

**Comment by totofox** [comment]
bjrambo 님, 제가 Chrome을 사용해 왔고 지금 최신버전(49.0.2623.87m)인데 XE 1.8.17에서는 pre태그의 속성이 적용되에 제대로 표현되고 있습니다. XE 1.8.18에서만 속성이 사라집니다.
