### ISSUE TITLE
1.8.12 이후 xpresseditor의 파일 첨부 오류

### ISSUE THREAD

**Issue by cherrype** [xpressengine/xe-core#1787]
XE Core 1.8.12 패치 이후,

에디터 스킨으로 Xpresseditor를 사용할 때 파일 첨부가 이뤄지지 않는 문제가 발생합니다. (업로드 100% 완료 후 파일 증발)

당황스러운건 크롬으로는 업로드가 잘되는데, IE에서는 업로드가 제대로 되질 않네요.

복수의 환경에서 테스트를 진행했고, XE 체험하기를 통해 테스트시에도 동일 문제가 확인되어 이슈 등록합니다.

**Comment by pxheart** [comment]
저도 업데이트 이후 100% 동일 증상이 발생했습니다.
온갖 방법으로 시도를 해보았으나 계속 실패네요.

**Comment by bnu** [comment]
fixed #1788
