### ISSUE TITLE
가상사이트에서 파일 업/다운로드의 이상한 점 두 가지

### ISSUE THREAD

**Issue by churow** [xpressengine/xe-core#1789]
작년에 이 문제에 대해 이슈를 제기한 적이 있는데, 그 때는 재현 불가로 이슈가 종결됐죠.
https://github.com/xpressengine/xe-core/issues/770

매번 XE 업데이트할 때마다 file.controller.php를 고치는 게 짜증나서
어떻게 된 일인가 따져보다가 이상한 점을 발견했습니다.

XE 새 버전에서는 가상사이트에 파일을 업로드할 때 module_srl 값이 0으로 저장됩니다.
그래서 다운로드할 때는 권한 검사할 모듈이 지정되지 않으니 무조건 다운로드가 됩니다.
게다가 이 권한 검사도 다운로드 URL의 module_srl 값에만 의존하는 것으로 보입니다..
XE 새 버전에서 가상사이트에 업로드된 파일은
모듈의 권한과 상관없이 다운로드 URL만 알면 누구나 내려받을 수 있습니다..
(사실 이건 가상사이트의 문제만은 아닙니다.)

**가상사이트에 파일 업로드시 module_srl 값이 0으로 저장되는 것이 첫번째 이상한 점입니다.**

그런데 예전 버전에서 가상사이트에 업로드된 파일은 module_srl 값이 들어가 있으므로
그 모듈에 대해 권한 검사를 하게 되고, 그 결과 권한이 없는 것으로 판정됩니다.

가상사이트의 모듈에서 파일 다운로드할 때 권한 검사를 통과하지 못하는 이유는
fileController에서 $logged_info->group_list가
가상사이트의 회원그룹이 아닌 메인사이트의 회원그룹 값을 갖기 때문에
fileController->grant(즉, moduleModel->getGrant()의 반환값)에도
그 회원그룹을 기준으로 잘못된 권한 판정 결과가 들어가기 때문입니다.
다른 모듈에서는 당연히 가상사이트라도 $logged_info->group_list가 제대로 된 값을 갖습니다.

**file 모듈에서 $logged_info->group_list가 가상사이트를 반영하지 못하는 것이 두번째 이상한 점입니다.**

그리고 파일 다운로드는 access 권한이 있으면 가능하게 되어 있는데
이것보다는 view 권한이 있을 때 가능하게 하는 것이 타당해 보입니다.
보통 access 권한은 줘도 view 권한은 안 주는 경우가 그 반대보다 많을 텐데,
본문은 읽을 수 없는데 본문에 첨부된 파일은 받을 수 있다는 것은 이상해 보입니다.

file 모듈의 전체적인 점검이 필요해 보입니다.

**Comment by bnu** [comment]
우선, module_srl 값은 정상적으로 기록되는 것으로 확인했습니다.
기존 운영 중인 사이트 외에 새로 설치해서 현상이 재현되는지 확인해주시면 좋겠습니다.

이외 다른 부분은 추가 확인해보겠습니다.

**Comment by bnu** [comment]
module_srl이 0으로 기록이 문제 상황이 아니라면 파일 다운로드 권한 체크에 문제가 없는 것으로 보입니다.
module_srl이 잘못 기록되는 상황은 운영하시는 사이트에서만 발생하는 상황일 수 있으므로 사용중인 확장기능의 영향일 수 있습니다. 새로 설치된 환경에서 확인해주시거나 demo.xpressengine.com 에서 문제가 재현되는지 확인해주시면 감사하겠습니다.

**Comment by churow** [comment]
테스트해 보신 가상사이트 게시판의 module_srl 값과 해당 파일 다운로드 URL 뒤에 붙은 module_srl 값이 같은지 확인해 보세요.

새로 가상사이트를 만들어서 테스트해 본 결과 메인사이트와 가상사이트의 mid가 같을 때(예를 들어 freeboard) 메인사이트의 mid를 검색해서 메인사이트의 module_srl을 찾는 것으로 보입니다. 저희 가상사이트에서 module_srl이 0이 된 것은 메인사이트에 같은 mid가 없기 때문일 겁니다.

그리고 가상사이트 게시판에 access 불가 권한을 설정해 놓은 상태에서 파일 다운로드 URL의 module_srl을 0으로 고쳐서 다운로드 해 보세요. 아마도 다운로드가 될 것입니다. 이건 보안 문제입니다.

**Comment by churow** [comment]
위의 경우는 맨처음 제기한 **첫번째** 문제에 대한 것이고, **두번째** 문제도 여전히 남아 있습니다. file 모듈에 가상사이트의 회원그룹이 반영되지 않습니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
