### ISSUE TITLE
IE에서 에디터가 보이지 않음.

### ISSUE THREAD

**Issue by ftft1** [xpressengine/xe-core#1790]
기본에디터(ckeditor ??)가 보이지않습니다.

참고글 및 동일현상 : https://www.xpressengine.com/qna/23094817

다른설정을 건들인것없고

SSL 환경입니다.
포인트 : 잘사용하다 업데이트 즉시 안보여졌습니다. (다른변수 제로)

피해가이만저만이아님 ㅠ 아예 업데이트를 하기싫어질듯 앞으로..

**Comment by qw5414** [comment]
문답게시판에 댓글을 남겼던 유저입니다.
XE최신버전 사용하고, 익스 10에서도 잘 작동하는것을 확인했습니다.
너무 이슈를 남기시는데 정보가 없습니다.

**Comment by bnu** [comment]
IE 버전 및 문제를 확인할 수 있는 URL 등의 상세정보가 없으면 확인이 어렵습니다.

**Comment by haendel7** [comment]
이 문제 확인 되었나요? 저도 같은 증상이 있어서요.
IE 11.306.10586.0 이구요.
Edge 25.10586.0.0 에서도 마찬가지입니다.
zipperupper를 적용해봐도 똑같고..(IE의 css 31개 참조제한은 없어졌겠지만요)

증상이 있는 사이트는 http://cglink.com/freeboard 입니다.

**Comment by bjrambo** [comment]
@haendel7 크롬에서도 문제가 되는걸 보면 단순 로드쪽 문제는 아닌것 같네요. 파일의 유무여부나 파일이 정상적으로 올라갔는지 점검해보세요.

**Comment by haendel7** [comment]
크롬, 파이어폭스에서는 문제가 없이 잘 잘동하고있습니다.
제가 IE를 잘 안써서 몰랐는데... 최근에 알았어요. 어떤분이 제보해주셔서...

**Comment by bjrambo** [comment]
@haendel7 님사이트의 경우 저한테는 크롬에서도 에디터 실행에 오류가 있어 크롬 개발자 콘솔에서 문제있다고 뜨고 있습니다. 잘 한번 살펴보세요.

**Comment by haendel7** [comment]
아~~ 1시간전까지만 해도 크롬에선 잘 되던게...귀신이 곡할노릇... test게시판 따로 만들고 다른 게시판을 모두 옛날 에디터로 되돌렸네요.ㅠㅠ 위 '여기'링크도 수정했습니다.
찬찬히 원인을 찾아봐야겠네요.ㅠㅠ

**Comment by haendel7** [comment]
원인 찾았습니다.
도메인/common/js/plugins/ckeditor/ckeditor/ckeditor.js 로 직접 접근해보니
**500 Internal Server Error** 가뜨고 있었습니다.

원인은 **.htaccess**에 이었는데
`RewriteRule ^(.*\.(css|js))$ /min/index.php?f=$1 [L]`
제가 .htaccess 마지막에 위 코드를 추가해서 Google minify를 쓰고있었습니다.
그걸 없애주니 정상적으로 접근이 되고 ckeditor도 작동할 수 있었습니다. ㅡ.ㅡ
부끄럽습니다.
