### ISSUE TITLE
1.8.13 글등록 삭제 댓글 등록 삭제시 문제가 생깁니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1792]
https://www.xetown.com/lakepark/40892

해당액션이 있을때 마다 알럿창이 발생을 해서 확인을 요청을 하고 확인을 누르면 컨텐츠영역 상단에 해당액션에 대한 완료 메시지가 나타납니다.

사용하는 스킨은 스케치북5 스킨입니다.

![regi](https://cloud.githubusercontent.com/assets/6590236/10709162/0a1e2116-7a5d-11e5-9ff2-bfa4a49b78da.png)

**Comment by wookho** [comment]
@bnu 저 메시지와 알럿 발생하는 것들이 아약스보드와 같은 사용유저에게 큰 문제를 일으키는 듯 합니다. 또한 댓글 삭제도 안되고 많은 문제가 있어요.

**Comment by bnu** [comment]
fixed #1795
