### ISSUE TITLE
1.8.13 에서 게시판 관리/추가 설정/위지윅 에디터의 '문서 폰트' 설정이 변경되지 않습니다.

### ISSUE THREAD

**Issue by paulryu03** [xpressengine/xe-core#1793]
XE 1.8.13 에서 게시판 관리/추가 설정/위지윅 에디터 섹션에서 "문서 폰트"의 설정이 변경되지 않습니다. 특이 사항은, SSL 을 항상 사용하는 웹사이트에서는 변경이 되는데, SSL 을 사용하지 않는 웹사이트에서는 변경 사항이 저장되지 않는다는 것입니다. 그리고 다른 것들은 다 변경이 잘 되는데, 오직 "문서 폰트" 설정만 변경이 안되네요. 확인 부탁드립니다.

**Comment by qw5414** [comment]
증상이 재현되고 있지 않아요,1.8.13 버전인데...

**Comment by paulryu03** [comment]
그런가요?? 쩝,,, 제가 관리하는 사이트들 중에 SSL 사용 안하는 4개의 사이트들 모두가 같은 증상인데요...ㅠ 암튼 확인해 주셔서 감사합니다. ^^ 또 열심히 원인을 찾아봐야겠네요. ^^

**Comment by qw5414** [comment]
@paulryu03 문서 폰트 설정은 제 사이트에서도 1.8.13버전 업데이트 이후 충분히 테스트 해봤지만..증상이 나타나지 않아서용 ㅠ.ㅠ

**Comment by paulryu03** [comment]
@qw5414 네. 다른 분들이 위의 문제 없이 잘된다는 것을 아는 것만으로도 도음이 됐습니다. 테스트 해주셔서 다시 한번 감사드립니다!!  ^^
