### ISSUE TITLE
선택적 SSL 사용시 게시글을 삭제후에도 이에 따른 리다이렉트가 되지 않음.

### ISSUE THREAD

**Issue by hjhj3686** [xpressengine/xe-core#1794]
일단 해결방법은 이 commit을 롤백 후 테스트 하니 정상 작동합니다...
https://github.com/xpressengine/xe-core/commit/dcf8a95ada9282905d3e0a12338413843531e984

증상 재현 방법은 이렇습니다.
1. 선택적 SSL 사용된 사이트 게시판에서 테스트 게시글 작성 (계정이 관리자든 뭐든 상관X)
2. 관리자 아이디로 해당 글 삭제
3. 주소 확인 (삭제 후에도 act 가 남아 있는 현상이 발견됨 EX1 : /index.php?document_srl=SRL_NUM&mid=MID_NUM&act=dispBoardDelete)
4. 게시글은 삭제 처리되었으나 게시글은 없으니 mid로 리다이렉트는 되나 주소는 EX1과 같은 포맷 형태입니다.
추후 여기에서 타게시물을 누를경우 해당 게시물의 dispBoardDelete 로 자동 연결되는 등 현상이 일어날 수 있습니다.

**Comment by bnu** [comment]
fixed #1795

**Comment by hjhj3686** [comment]
.. 이거 안고쳐졌네요 그대롭니다.

**Comment by qw5414** [comment]
@hjhj3686 전 정상작동 확인햇는데.
어떤 현상이 있는건지..?
