### ISSUE TITLE
cache에서 object 타입 저장시 \ 가 들어가면 발생되는 오류

### ISSUE THREAD

**Issue by qkrcjfgus33** [xpressengine/xe-core#1801]
$oCacheHandler->getGroupKey
$oCacheHandler->get
$oCacheHandler->put

위 3개 함수를 이용 값을 캐슁하는 모듈을 작성중인데
windows에서의 경로문자 즉 \ 가 들어가면
만료안된 캐쉬파일이 있는데도 $oCacheHandler->get 가 false를 반환하는 버그가 있습니다.

저장되는값에서 \ 를 빼니 제대로 동작하네요.

이게 본래 의도되서 개발된 구조인지 아니면 버그인지 잘 구분이 안가서
조심스럽게 이슈 남겨봅니다.
- 테스트환경은 windows8.1  , file cache를 이용, XE버전 1.8.13

**Comment by ridikim** [comment]
안녕하세요. 관리자 모두에서 메뉴 만들시 무작위로 \ (원표시로) 나오는데 구체적으로 어떤 파일을 고쳐야 하는 지요?

**Comment by qkrcjfgus33** [comment]
@ridikim 그건 이 문제와는 별개의 문제인것같고.. 알려주신 정보가 부족해서 해결방법도 알수가 없네요.
XE 공홈 게시판에 문제발생시의 조건과 발생문제를 자세히 적으시면 도움을 받을수도 있습니다. https://www.xpressengine.com

**Comment by YJSoft** [comment]
@ridikim 별도의 이슈로 올려주세요.
