### ISSUE TITLE
이미지맵태그를 기본으로 허용했으면 합니다.

### ISSUE THREAD

**Issue by anizen** [xpressengine/xe-core#1811]
<map><area> 엘레멘트를 허용했으면 합니다.

비록 크게 활용하진 않는 것 같지만.. 기본적으로 허용하는 방향으로 했으면 하네요..

아니면 혹시 보안에 관련된 이슈가 있어서 막은 건지 궁금합니다..

**Comment by lansi951** [comment]
#1804 이 이슈하고 비슷한 이슈같네요

**Comment by anizen** [comment]
이미지맵 태그는 ie5.5부터 있던 태그인데......
