### ISSUE TITLE
대시보드에서 1.8.15 설치를 누른 순간 fatal error가 뜬 후 홈페이지에 아무 것도 뜨지 않아 접속이 되지 않아요

### ISSUE THREAD

**Issue by nungureum** [xpressengine/xe-core#1815]
1.8.15 core update 안내가 떠서 대시보드에서 설치를 눌렀는데 그 때 fatal error가 뜨고 나더니 홈페이지에 접속하면 빈 화면만 떠서 뭘 어디서부터 손을 봐야할지도 모르겠네요. 초짜라서 백업 같은 거도 잘 모르고 ssh는 접속이 안 되서.. 글이 많았던 곳인데 처음부터 다시 다 해야되나 생각하니 막막합니다. 처음 본 거라서 fatal error 다음 글귀가 뭐였는지 기억도 안 나고.. 이거 다시 살릴 방도가 있나요?

**Comment by kijin** [comment]
[같은 질문을 두 군데 올리는 것은 피해 주시기 바랍니다.](https://www.xpressengine.com/qna/23110066)

**Comment by YJSoft** [comment]
코어 이슈가 아닌 것은 공식 사이트 묻고 답하기에 올려주세요.
