### ISSUE TITLE
사이트 관리자가아닌 다른그룹의 회원이 글 작성시 첨부이미지가 본문에 삽입이 않됩니다.

### ISSUE THREAD

**Issue by zhao9110** [xpressengine/xe-core#1818]
xe1.8.15버전으로 사이트를 제작중 인데요,관리자가 글 작성시 이미지를 첨부하여 본문에 삽입시 정상적으로 보입니다.문제는 관리자가 아닌 다른 그룹의 회원이 글 작성하면 첨부이미지를 본문에 삽입해서 미리보기에서도 이미지가 보이는데 확인버턴을 누르면 본문에 삽입했던 이미지가 다 없어집니다.  글 작성시 이미지 관련 권한문제 같기도 한데 어디서 어떻게 설정해야 하는지 모르겠고 해서 이슈로 글을 올립니다.

**Comment by qw5414** [comment]
문제가 없어보입니다..(정상적인 첨부가가능해서요..)
첨부 하고 본문삽입이라하면 게시판 에서 일어나는 문제라고 판단하고 테스트 했습니다.

**Comment by zhao9110** [comment]
그러면 게시판 설정이 잘못된 문제인가요? 제가 windows server 1012R2에다 IIS,PHP7 Mariadb이렇게 서버와 DB환경을 만들어 XE를 깔았습니다. 게시판설정은 별로 한게 없구요. 현상은 사이트 관리자가 이미지를 첨부해서 본문에 삽입하면 잘 나오는데,관리자가아닌 다른 그룹의 회원이 똑같은 동작을 하면 미리보기 까지도 잘 보여지는데 글을 다 쓰고 발표를 하면 문자는 제데로 나오는데 그림만 나타나지 않네요. 제가 다른곳에있는 여러명의 회원에게 테스트를 의뢰했는데 똑같은 현상이 나타났습니다. IE,크롬 등 여러개 브라우저로 교체해서 테스트해도 마찬가지구요. 답답해서 xe홈페이지에 가서 xe를 다운해서 로컬환경에서 테스트 해봤는데 똑같은 현상입니다. 아무리 봐도 권한 설정관련 문제 같은데 어떤소스를 고쳐야 하는지,아니면 어떻세 설정을 해야 하는지 모르겠네요.

**Comment by qw5414** [comment]
`PHP7`이 주원인일수도 있습니다. php7은 아직 XE를 사용하기엔 어렵습니다. https://www.xetown.com/index.php?mid=lakepark&category=11323&document_srl=109198 여기에서 호환성 관련 작업을 진행중이기도 합니다.

**Comment by qw5414** [comment]
php5.6.15 ( XAMPP ) 순정으로 설치 이후 확인 결과,정상적으로 업로드 가능.. ( 본문삽입 + 내용 ) 이상이 없네요.
