### ISSUE TITLE
메뉴관련 건의사항

### ISSUE THREAD

**Issue by zhao9110** [xpressengine/xe-core#1819]
다국어 사이트 제작시,메뉴를 따로따로 보이게 하는 기능을 증가했으면 좋겠습니다. 예를 들어 영어를 누르면 메뉴1,메뉴2,메뉴3이 나타나고 한국어 누르면 메뉴4,메뉴5,메뉴6,중국어를 누르면 메뉴1,메뉴2,메뉴5이런식으로요. 드루팔과 비슷한 기능을 증가했으면 합니다.

**Comment by qw5414** [comment]
XE는 하나의 사이트맵을 연결해서 쓰는 형태를 취하하고 있습니다.
말씀주신 방법으로 하게 될경우, 메뉴 연동이나 다른 부분에 커스터마이징도 엉청나게 들어가야할 것 같습니다.( 레이아웃에 메뉴를 연결하는 방식이라..)
그래서 메뉴 생성시, 메뉴를 잡히는 형태로 취하고 있는거입니다.
