### ISSUE TITLE
xe 설치화면이 빈 화면으로 나와요.

### ISSUE THREAD

**Issue by waydodo** [xpressengine/xe-core#1823]
xe 1.8.15와 1.813 등을 설치하려고 시도했는데

전혀 작동하지 않고 있습니다.

그래서 호스팅 업체에 문의를 했더니

아래의 에러 메시지가 뜬다고 하네요.

PHP Fatal error: require(): Failed opening required '/home/createyo/public_html/xe/classes/module/ModuleObject.class.php'

(include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/createyo/public_html/xe/config/config.inc.php on line 400

어떻게 조치를 취야할지 전혀 모르겠습니다.

도움을 부탁 드립니다.

PHP 버전은 5.5입니다.
아래는 셋팅입니다. 수정해야할 사항이 있는지요?

![01](https://cloud.githubusercontent.com/assets/14140717/12054148/6ab7df22-af18-11e5-8fa1-8a58a5512cf4.jpg)

**Comment by misol** [comment]
XE 코어 전체 파일을 재 업로드(덮어쓰기) 하세요 :)
파일이 일부 누락된 것 같습니다.

**Comment by waydodo** [comment]
전체 파일 재 업로드는 여러번 해보았습니다.
심지어 다른 버전으로도 테스트 해보았고요.
서버가 '영국에 있는 회사'라 무슨 셋팅이 맞지 않아서 setup이 작동하지 않아 보이네요.
코어 파일에 필요한 아래의 사항을 요청해서 모두 설치 했는데도 여전히 작동하 않습니다.

PHP version 5.3.0 or greater (But recommend PHP >= 5.5.0)
MYSQL version 4.1 or greater (But recommend MYSQL >= 5.x) , MS-SQL, CUBRID
XML Library
GD Library
ICONV
session.auto_start = Off (php.ini)

**Comment by kijin** [comment]
우선 `'/home/createyo/public_html/xe/classes/module/ModuleObject.class.php` 파일이 있는지 확인해 보시고요... 있다면 퍼미션이 정상(644)인지도 확인해 보시기 바랍니다.

모든 파일이 정상인데도 작동하지 않는다면 퍼미션 문제일 가능성이 있습니다. 특히 해외 호스팅은 퍼미션 구조가 독특한 경우가 종종 보여요.

**Comment by waydodo** [comment]
답변 감사합니다.
살펴보니.. 파일도 있고요. 퍼미션도 (0644)로 되어 있네요.
그렇지 않아도 호스팅 업체측에서도 그 파일을 따로 달라고 했었어요.
이 문제로 업체와 10일 넘도록 씨름하고 있어요.
업체가 친절해서 그쪽도 이것 저것 해보고 있는데 성과가 없네요...ㅠ.ㅠ;
아무리해도 다른 업체를 찾아야 할까봐요.
