### ISSUE TITLE
[XE 1.8.15] 댓글 등록시 alert창 출력 관련 문제

### ISSUE THREAD

**Issue by krnis** [xpressengine/xe-core#1825]
[조건사항]

XE 버전 : 1.8.15

SSL 관련 : SSL을 선택적으로 사용

Ps. SSL을 항상 사용시 alert창 출력 안합니다. 

board.class.php 파일을 1.8.12 버전의 board.class.php 으로 변경시 alert창 출력 안함

**Comment by hjhj3686** [comment]
#1792
