### ISSUE TITLE
게시판에 이상한 글이 자꾸 올라 옵니다?

### ISSUE THREAD

**Issue by kjo9958** [xpressengine/xe-core#1838]
![_2016_02_04_14_02_29_647](https://cloud.githubusercontent.com/assets/17059157/12806288/f3009d7e-cb47-11e5-88b7-78ca7eb1cc5f.png)

지워도 지워도 자꾸 광고글이 게시판에 올라 오고 잇습니다

**Comment by qw5414** [comment]
게시글 등록을 막는 캡처 기능을 사용하시거나
비회원의 작성을 막으시기 바랍니다.
또한 회원의 경우에도 가입시 캡차를 입력하게 하여 회원가입에 사용자인지 아닌지를 가려내서 받으시기 바랍니다..

**Comment by anizen** [comment]
광고 봇입니다. 라이믹스와는 무관한 이슈입니다.

**Comment by bjrambo** [comment]
@anizen 고객님 여긴 XE입니다. ~~~ ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by anizen** [comment]
@bjrambo 히익 -_-;; 메일 타고 와서 착각했네요.......
