### ISSUE TITLE
[중요] 1.8.16 업데이트 후 회원가입이 불가능합니다. 

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1861]
사용자정의 선택이나 입력이 불가능해서 가입이 되지 않고 있습니다.

빠른 처리가 필요합니다.

**Comment by bjrambo** [comment]
func.inc.php 파일내에
1203
번째줄에

`$val = preg_replace_callback('/&#(?:x([a-fA-F0-9]+)|0*(\d+));/', function($n) {return chr($n[1] ? ('0x00' . $n[1]) : ($n[2] + 0)); }, $m[3][$idx] . $m[4][$idx]);`
내용이 있는데 이를
`$val = preg_replace('/&#(?:x([a-fA-F0-9]+)|0*(\d+));/e', 'chr("\\1"?0x00\\1:\\2+0)', $m[3][$idx] . $m[4][$idx]);`
으로 일딴 수정해놓고 회원가입 받으세요

**Comment by wookho** [comment]
@bjrambo 
고쳤는데 동일한데요. 캐시파일 재생성 해야 할까요?
아니면 회원가입설정을 한번 저장해봐야 하나요?

**Comment by bjrambo** [comment]
@wookho XE는 다를수도 있겟네요..ㅠㅠ

라이믹스는 저것만 수정해두면 가입은 됬거든요 ㅎ

**Comment by wookho** [comment]
@bjrambo 저는 라이믹스 사용자가 아니라서요....

**Comment by bjrambo** [comment]
@wookho 이부분에 대해서는 제가 BNU님에게 개인적으로 잘 전달 드린 상태에요..ㅠㅠ

해결 해주실것 같아요 :)

**Comment by bjrambo** [comment]
@wookho 몽실아빠님
member.admin.view.php 파일에서
634번째줄 근처 언저리에 보시면,
`$inputTag = preg_replace_callback('@%(\w+)%@', function($n) { return $replace[$n[1]]; }, $template);`
가 있는데, 이를

`$inputTag = preg_replace_callback('@%(\w+)%@', function($n) use($replace) { return $replace[$n[1]]; }, $template);`
으로 수정해주세요
기진곰님이 알려주셧어요 @kijin 乃

**Comment by wookho** [comment]
@bjrambo 감사합니다. 말씀하신대로 처리해서 회원정보수정을 통해 확인했습니다. 잘 되네요. 감사합니다.

**Comment by kijin** [comment]
결자해지... 죄송 ㅠ

#1814 는 PHP 7 관련 패치를 좀 모으다가 그만둔 거라서 설마 이렇게 빨리 merge될 거라고는 생각하지 못했어요. 그래서 충분히 테스트해 보지 못한 것 같네요.

**Comment by conory** [comment]
두달이 넘도록 발견 못한 버그가!!

**Comment by bjrambo** [comment]
@kijin @conory 죄송.. 제가 회원가입에 확장변수만 있엇어도 가능햇을텐데 ㅠ.ㅠ 쓰질 않았어요 ㅠㅠ..
