### ISSUE TITLE
추천,비추천,신고의 취소기능

### ISSUE THREAD

**Issue by sonyeonghwa** [xpressengine/xe-core#1865]
XE로 만들어진 대부분의 커뮤니티 사이트들에 보면

"앗 죄송합니다. 잘못 OO 눌렀네요."라는 댓글이 항상 있습니다.

이런 댓글이 만연하다는 것 자체가 추천,비추천,신고 기능이

근본적으로 잘못 누르는 경우가 생길 수 밖에 없는 구조이며,

따라서 단순히 경고창을 출력하는 애드온으로 해결하는 것을 넘어서서

취소기능도 필요하다고 생각합니다.

페이스북과 같은 유명SNS부터 유명 커뮤니티에서는 이미 도입되어

일반적인 기능이 되어가는 추세입니다.

**Comment by bnu** [comment]
변경 계획이 없습니다.

**Comment by bjrambo** [comment]
@bnu 모바일이 대중화되가고 있는 시대에 당연히 모바일에서 지원하는 추천 버튼이 확인을 하지 않고 작동합니다.

이러한 작동에 있으면 알럿 창을 띄우도록 게시판에서 지원하거나, 아니면 취소를 해야하는 기능이 있어야 한다고 생각해요.

지원하지 않을 계획이라는건.. 결국은 코어에서 지원하지 않는다는 의미인데.. 이런 기초적인 부분까지 서드파티에게 넘기는건.. 좀 아닌것 같아요.

물론 XE1이 오래된 프로젝트이고 좀 유지보수 힘든 프로젝트이긴하지만.. 지원해줘야할 부분은 해줘야 한다 생각해요.

XE1유저가 날로가면 갈수록 늘어나는 사람들도 많다고 생각해요.

**Comment by bjrambo** [comment]
XE는 회사형태의 1인 블로그식의 사이트보단 모두가 어울리며 게시글을 공유하며 지내는 공간으로 사용되는 경우가 많기때문에 필수적으로 취소가 안되면 최소한 추천하겠습니까? 라는 안내가 필요하다고 봐요.

**Comment by eondcom** [comment]
@bnu 추천 취소 기능도 넣어주세요! ㅠㅠ

**Comment by eondcom** [comment]
https://xetown.com/questions/1115448#comment_1115598

람보님이 라이믹스에는 개발했다고 하는데 한번 소스 보고 비슷하게 해주시면 안되나요 ㅠ
