### ISSUE TITLE
#1857 기본카운터 애드온 적용시 관리페이지 대쉬보드 접근 404 에러발생

### ISSUE THREAD

**Issue by kanielu** [xpressengine/xe-core#1870]
금일 윈도우 재설치한후 IIS 재설정하였을때
대시보드 접근시 페이지가 로딩이 됬습니다.

다만 하단에 아래와 같은 오류가 표시됩니다.
`Fatal error: Uncaught Error: Call to undefined method stdClass::getTitle() in C:\inetpub\public_html\files\cache\template_compiled\702fc0c70362ea85e18d26f3c77d6a7e.compiled.php:32 Stack trace: #0 C:\inetpub\public_html\classes\template\TemplateHandler.class.php(384): include() #1C:\inetpub\public_html\classes\template\TemplateHandler.class.php(175): TemplateHandler->_fetch('file://C:/inetp...') #2C:\inetpub\public_html\files\cache\template_compiled\6e90905c2fc05923e8ed3eee1df62c4c.compiled.php(67): TemplateHandler->compile('modules/admin/t...', '_dashboard_coun...') #3C:\inetpub\public_html\classes\template\TemplateHandler.class.php(384): include('C:\inetpub\publ...') #4C:\inetpub\public_html\classes\template\TemplateHandler.class.php(175): TemplateHandler->_fetch('file://C:/inetp...') #5C:\inetpub\public_html\classes\display\HTMLDisplayHandler.php(61): TemplateHandler->compile('./modules/admin...', 'index.html') #6C:\inetpub\public_html\classes\display\DisplayHandler.class.php(65): HTMLDisplayHandler->toDoc(Objec in C:\inetpub\public_html\files\cache\template_compiled\702fc0c70362ea85e18d26f3c77d6a7e.compiled.php on line 32 Fatal error: Uncaught Error: Call to undefined method stdClass::getTitle() in C:\inetpub\public_html\files\cache\template_compiled\702fc0c70362ea85e18d26f3c77d6a7e.compiled.php:32 Stack trace: #0 C:\inetpub\public_html\classes\template\TemplateHandler.class.php(384): include() #1C:\inetpub\public_html\classes\template\TemplateHandler.class.php(175): TemplateHandler->_fetch('file://C:/inetp...') #2C:\inetpub\public_html\files\cache\template_compiled\6e90905c2fc05923e8ed3eee1df62c4c.compiled.php(67): TemplateHandler->compile('modules/admin/t...', '_dashboard_coun...') #3C:\inetpub\public_html\classes\template\TemplateHandler.class.php(384): include('C:\inetpub\publ...') #4C:\inetpub\public_html\classes\template\TemplateHandler.class.php(175): TemplateHandler->_fetch('file://C:/inetp...') #5C:\inetpub\public_html\classes\display\HTMLDisplayHandler.php(61): TemplateHandler->compile('./modules/admin...', 'index.html') #6C:\inetpub\public_html\classes\display\DisplayHandler.class.php(65): HTMLDisplayHandler->toDoc(Objec in C:\inetpub\public_html\files\cache\template_compiled\702fc0c70362ea85e18d26f3c77d6a7e.compiled.php on line 32 `

**Comment by YJSoft** [comment]
코드 등을 붙여넣으실 때에는 ```를 사용하시는 것이 좋습니다.

ex)
![image](https://cloud.githubusercontent.com/assets/5893514/13424608/345494ea-dfe5-11e5-9cd4-d5bb433c30a3.png)
이렇게 쓰면 아래와 같이 보입니다.

```
<?php
echo 'Hello XE!';
```

**Comment by kanielu** [comment]
YJsoft님, 정보 감사합니다. 깃허브는 처음이라 실수했네요.
폰으로 수정한다고 고생했습니다 하하..

**Comment by YJSoft** [comment]
@kanielu 크게 중요한건 아니고... 그냥 적으면 `#숫자` 같은게 나왔을때 이슈로 불필요하게 링크가 걸려서 그렇습니다. 또 읽기에도 좋지 않고요.

**Comment by kanielu** [comment]
PHP 7.0 이상 사용시 #1884 에서 해결방법 있습니다.
