### ISSUE TITLE
SEO 1.8.18 로 업데이트 후에 "Analytics"와 "기타" 설정들이 화면에 나타나지 않습니다.

### ISSUE THREAD

**Issue by paulryu03** [xpressengine/xe-core#1873]
SEO 1.8.0 에서 1.8.18 로 업데이트 후에, "Analytics" 와 "기타" 설정들이 화면에 나타나지 않고, 저장 버튼만 보입니다. 확인 부탁드립니다.

**Comment by bjrambo** [comment]
https://github.com/xpressengine/xe-module-seo/issues

SEO모듈의 이슈는 여기에서 받을 것 같아요

코어에는 합쳐서 배포가되었지만, 실제 깃허브는 완전히 분리되어 운영되요~

**Comment by paulryu03** [comment]
아... 그렇군요. ^^;; 감사합니다. ^^
