### ISSUE TITLE
1.8.18에서 익명으로 작성한 글을 수정하면 원래 회원정보가 노출됩니다.

### ISSUE THREAD

**Issue by kijin** [xpressengine/xe-core#1874]
### 재현 방법

1. 익명 게시판에 글을 씁니다.
2. 이름이 anonymous로 나오고, 이름을 클릭해도 회원정보 메뉴가 뜨지 않습니다. (여기까지 정상)
3. 글을 수정합니다.
4. 이름은 여전히 anonymous이지만, 클릭하면 회원정보 메뉴가 뜹니다.
5. 다시 수정합니다.
6. 이제는 회원정보 메뉴가 뜨지 않습니다.
7. 또다시 수정합니다.
8. 또 회원정보 메뉴가 뜹니다.

즉, 수정할 때마다 회원정보가 노출되었다가 숨겨졌다가를 번갈아 반복합니다.

### 해결 방법

board.controller.php에서 이번에 수정된

    $obj->member_srl = $oDocument->get('member_srl') * -1;

이 코드를 아래와 같이 변경합니다.

    $obj->member_srl = abs($oDocument->get('member_srl')) * -1;

**Comment by YJSoft** [comment]
:+1:
