### ISSUE TITLE
XE 1.8.18에서는 <pre>태그 속성 사용불가, video태그와 audio태그 사용 불가, editor에 가로스크롤바 생김

### ISSUE THREAD

**Issue by totofox** [xpressengine/xe-core#1876]
XE를 오래 전부터 사용해 오면서 upgrade해 왔습니다.

이번 APM, browser(Chrome) 그리고 XE를 update했습니다(아래 '저의 PC 재원'을 참고해 주세요)
이런 PC의 환경에서 문제가 발생하고 있습니다.

이번 XE 1.8.18 에서 다음과 같은 이상한 점이 발생하고 있습니다.
그런데 XE 1.8.17이나 XE 1.8.16으로 down date를 하면 1항의 가로 스크롤바만 생기는 문제만 있습니다.

1. 이미 upload된 페이지를 editor(Ckeditor)에서 '소스'버튼을 누르고 수정하려고 하면
   내용에 긴 문단이 있는 경우 editor에 가로 스크롤바가 생겨 수정작업이 매우 불편합니다.

2. 아래의 소스는 최초 입력시 적용되어 browser(Chrome)에서 제대로 보입니다.
    &lt;pre style="display:block;white-space:pre-line;word-wrap:break-word;word-break:break-all;text-align:justify;"&gt;

    그렇지만, 소스를 수정하려고 editor에 들어가서 보면 
    &lt;pre&gt;태그만 남고 속성은 사라져 있습니다.

    이후부터는 wrap이 적용되는 위의 소스로의 수정이 불가능하게 됩니다.
    오직 삭제하고 새로 입력하는 수 밖에 없습니다.

3. &lt;video&gt; 태그나 &lt;audio&gt;태그를 사용할 수 없습니다.
   태그가 흔적도 없이 사라지고 
   'Your browser does not support the video element.'만 남겨 있습니다.

  &lt;video autoplay="true" controls="true" height="360" preload="none" width="640"&gt;
   &lt;source src="*.mp4" type="video/mp4" /&gt;
            Your browser does not support the video element.
   &lt;/video&gt;

   &lt;audio autoplay="true" controls="true" height="30" preload="none" width="300"&gt;
   &lt;source src="*.mp3" type="audio/mpeg" /&gt;
            Your browser does not support the audio element.
   &lt;/audio&gt;

[참고]  저의 PC 재원

        Windows 10
        Chrome v.49.0.2623.87 m
        XE 1.8.17 (XE 1.8.18로 높였다가 down date했습니다)

        Apache 2.4.18
        PHP 7.0.4
        MySQL 5.7.11

**Comment by bjrambo** [comment]
2번 항목은..
#1785 이슈를 참고해보시길 바래요.

**Comment by totofox** [comment]
bjrambo 님, 제가 Chrome을 사용해 왔고 지금 최신버전(49.0.2623.87m)인데 XE 1.8.17에서는 pre태그의 속성이 적용되어 제대로 표현되고 있습니다. XE 1.8.18에서만 속성이 사라집니다.

**Comment by bjrambo** [comment]
@totofox 현재 1.8.18버전올라오면서 ckedior에 관한 패치가 없엇습니다.

해당 부분에 대해서는 https://www.xetown.com/index.php?mid=lakepark&category=11323&document_srl=220908 댓글에서도 잘 알려주듯이
에디터에 사용되는 라이브러리의 버전에 따라 문제점이 있을 수 있고 혹은 위에 #1785 이슈와 비슷하게 config.js 으로 선언해줘서 해결할 수 잇는 방법일 수 있기에 제안 드리는겁니다.

문제점을 대충인지하고 해당 문제를 어느정도 도움을 드리기위해 해당 이슈를 확인해보라고 한거고.. 만약 해당 이슈에 댓글과 비슷하게 세팅하고 해결이 될 수 잇기 때문에 제의드리는거에요.

한번 해보시기 바래요. 

아니면 바로위의 댓글처럼 버전이 업데이트 될때까지 기다려야 할지도요.

**Comment by totofox** [comment]
bjrambo님, 제가 이해를 못했군요. 업데이트될 때까지 XE1.8.17를 사용하겠습니다.
항상 건강하시고, 행복하시길 빕니다. 감사합니다.

**Comment by kijin** [comment]
word-wrap, word-break, <audio>, <video> 등이 삭제되는 것은 XE에서 사용하는 HTMLPurifier라는 라이브러리의 특성으로, 최근 이 라이브러리를 업데이트한 적이 없기 때문에 1.8.17에서도 마찬가지로 삭제될 것 같습니다. 만약 1.8.18에서는 삭제되는데 1.8.17에서 멀쩡하다면 오히려 전혀 필터링이 되지 않고 있다는 뜻이니 1.8.17의 버그일 것입니다.

위와 같은 태그나 속성이 삭제되지 않도록 하려면 관리자로 로그인한 후에 글을 쓰거나 수정하시면 됩니다.

#1875 는 중복이니 이슈를 Close 해주셔도 될 것 같습니다.

**Comment by totofox** [comment]
#1875 는 중복된 이슈를 Close 해도 되겠습니다.

xe1.8.17에서는 관리자로 로그인한 후 글을 쓰거나 수정하면 제대로 됩니다.
그러나 일반회원이 로그인한 후 글을 쓰면 <pre>태그는 wrap관한 속성을 날려버리고 정렬에관한 속성만 남습니다. 그리고 <audio>, <video>태그는 사라지고 안내글'Your browser does not support the video element.'만 남겨 있습니다.

**Comment by bjrambo** [comment]
@totofox #1875 본인이 직접 해주세요. 기진님은 권한이 없으셔서 불가능하십니다.

**Comment by kijin** [comment]
@totofox 네, 말씀하신 현상은 의도적인 동작입니다. XE 모든 버전에서 관리자 외에는 `<audio>`, `<video>`, wrap 속성 등을 사용할 수 없습니다. 이것은 1.8.18이나 1.8.17이나 마찬가지입니다.

만약 1.8.18에서 관리자가 글을 썼는데도 태그나 속성이 삭제되는 문제가 있다면 버그가 되겠습니다.

**Comment by oldkids** [comment]
1.8.18에서 관리자가 글을 썼음에도 태그나 속성이 사라지거나 소스가 그대로 노출이 되니 버그겠군요.
최초 글 작성시에는 제대로 보여지다가 수정하면 이러한 증상이 나타납니다.

**Comment by totofox** [comment]
bjrambo님, kijin님, oldkids님, 세분 모두 친절하고 자세히 알려주셔서 고맙습니다.

XE 1.8.18에서 나타나는 bug가 없는 version으로 update할 때까지 XE 1.8.17을 사용하겠습니다.

항상 건강하시고 뜻하시는 일들이 이루어지기를 빕니다.

**Comment by kijin** [comment]
관리자가 입력했는데도 태그가 삭제되는 버그의 원인을 찾았습니다.

#1882 에 제가 작성한 댓글을 참고하세요.

**Comment by totofox** [comment]
기진님, 안녕하세요. 

알려주신대로 파일을 수정하였더니 제가 제기한 4개중 3개는 문제없이 잘 실행됩니다.

나머지 1개는 editor에 관한 문제 입니다.
기존 페이지를 수정하기 위해 editor의 "소스"버튼을 누르면 editor에 가로 스크롤바가 생깁니다.
소스를 수정하기 불편하므로 복사해서 editplus에서 작업한 후 다시 editor에 붙여넣기를 하고 있습니다.
언젠가는 개선되어야 할 것 같습니다.

감사합니다.

**Comment by bnu** [comment]
fixed #1882
