### ISSUE TITLE
board 글작성시 첨부파일 본문삽입 링크 <a> 속성 날아가는 문제

### ISSUE THREAD

**Issue by delphixe4** [xpressengine/xe-core#1877]
본인의 환경 : nginx / PHP 7 / mariadb 10.1 / Chrome & IE11 그리고 XE 1.8.18은 물론 XE 공식사이트에서도 확인되고 있는 문제점으로, 문제점 확인방법은 아래와 같습니다.

1. 글 제목은 아무렇게나, 내용도 아무렇게나 하고, 첨부파일에 이미지가 아닌 것을 올린다.
2. 올린 첨부파일은 "본문 삽입"한다.
3. 글을 등록한다. [[여기서 바로 문제가 나타나는 경우도 있음]]
4. 글 수정을 들어간다.
5. <a> 태그의 속성이 사라진다. 다시 "본문 삽입"후 글을 수정하여도 해당 속성이 사라진 상태로 등록된다.

위 문제는 ckeditor 외의 또다른 에디터로도 확인한 바 있습니다. 다만 이상하게도 직접 작성한 다른 링크들은 살아있는 경우가 대다수입니다. 현재 XE 공식사이트에서는 txt, pdf 등의 파일로 실험해 본 결과 3번에서 바로 문제가 생기고 있습니다.

**Comment by onepang** [comment]
이거 정말 심각합니다.
오늘에서야 저도 발견했네요
zip 첨부파일을 본문삽입하면 링크 URL 다날라가 버립니다.

XE 1.8.18에서 발생하였습니다.

**Comment by delphixe4** [comment]
1875, 1876도 원인은 비슷할 것으로 보인다만 문제는 나름 대형버그임에도 일주일 가까이 반응이 없다는 것이겠죠. 음.. 일단 전 17로 내려갑니다..

**Comment by kijin** [comment]
`config/func.inc.php` 1270번째 줄을

    if(preg_match('@(\?|&|;)(act=)@i', $attr_value))

아래와 같이 고쳐주면 해결됩니다.

    if(preg_match('@(\?|&|;)(act=(\w+))@i', $attr_value, $m) && $m[3] !== 'procFileDownload')

**Comment by vastnet** [comment]
감사합니다~~^^
위와 같이 수정하니 잘 됩니다.
1.8.18 에서 수정해서 잘되었는데요..
1.8.19로 업데이트 하니 다시 안되더군요.
그래서 다시 위와 같이 수정했습니다.
저는 1227번째 줄 이었습니다.
감사합니다.^^
