### ISSUE TITLE
'in' operation 사용시 notnull 적용 문제

### ISSUE THREAD

**Issue by devflow** [xpressengine/xe-core#1879]
원래부터 Xml Query의 Condition 노드에서 in operation 사용시, 빈 array를 전송하면 notnull 조건에 맞지않나요?

문제가 빈 array를 보내면 condition이 적용되지않는것같아 모든 데이터가 검색됩니다.

일단 더미값을 넣어서 모든검색은 피하고있습니다.

**Comment by kijin** [comment]
`array() !== NULL`

빈 배열과 NULL은 다릅니다.

**Comment by devflow** [comment]
감사합니다. 본래부터 빈 array도 null로 인식하여 작동했던 잘못된 기억이 났나봅니다.
