### ISSUE TITLE
HTML 편집기에서 작성한 코드가 저장되지 않습니다.

### ISSUE THREAD

**Issue by seobi** [xpressengine/xe-core#1882]
아래코드를 게시판 HTML편집기에서 작성후

```
<!-- Place this tag in your head or just before your close body tag. -->
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<!-- Place this tag where you want the widget to render. -->
<div class="g-post" data-href="https://plus.google.com/107207613435608729601/posts/PXiesTRStuX"></div>
```
 저장하면
저장되지 않고 코드가 사라집니다.
사용버전은 1.8.18 버전이고 이전 버전에서는 잘 작동되었었습니다.

**Comment by kijin** [comment]
저런 스크립트를 아무나 입력한다면 보안상 문제가 될 수 있으니 막히는 것이 당연한 것 아닌가요?

단, 관리자가 입력해도 안 된다면 버그일 수도 있습니다.

**Comment by seobi** [comment]
관리자 계정에서 입력한 코드입니다.

**Comment by fy5914** [comment]
ckeditor 사용 + 1.8.18 최근버전 업데이트 이후에 저또한 마찬가지 버그가 있는것으로 보입니다.

글수정후, 관련 코드가 삭제되거나 변형됩니다. 조치가 필요해보입니다.

**Comment by seobi** [comment]
에디터 스킨을 ckeditor 가 아니라 xpresseditor 로 선택해도 마찬가지 입니다.
1.8.18버전되면서 그런 것 같습니다.
처음 저장시에는 제대로 저장되는 데 수정하면 사라집니다.

**Comment by kijin** [comment]
1.8.18에서 새로 생긴 버그가 맞네요.

해결책: modules/document/document.controller.php 455~458줄

```
		if(Context::get('is_logged') && !$manual_updated)
		{
			$logged_info = Context::get('logged_info');
			if($source_obj->get('member_srl')==$logged_info->member_srl)
			{
				... 후략 ...
```

이 코드의 3번째 줄을 잘라내어 앞으로 옮기면 됩니다.

```
		$logged_info = Context::get('logged_info');
		if(Context::get('is_logged') && !$manual_updated)
		{
			if($source_obj->get('member_srl')==$logged_info->member_srl)
			{
				... 후략 ...
```

**Comment by seobi** [comment]
kijin 님이 알려주신데로 수정하니 잘 되네요.
감사합니다.

**Comment by kijin** [comment]
XE 개발팀이 봐야 하니 이슈 열어두세요!

**Comment by oldkids** [comment]
정말 감사합니다.
덕분에 이제는 글을 수정해도 소스가 삭제되거나 사라지는 버그가 없습니다.
1.8.18로 업데이트 하고 나서 지금까지 이 문제 때문에 머리가 아팠는데 
덕분에 해결되니 너무 좋습니다.

**Comment by SangrakLee** [comment]
감사 같은 버그로 한참 검색했는데,,,감사합니다.
