### ISSUE TITLE
php 버전 7.0.0 이상에서 기본카운터 애드온 사용 시 관리자 페이지 깨짐 버그

### ISSUE THREAD

**Issue by kanxion** [xpressengine/xe-core#1884]
![29e41013dc802befa325cc596a5bc82d](https://cloud.githubusercontent.com/assets/18184209/14167898/47e44ac4-f759-11e5-99b5-5def8d2601f5.png)

위와 같이 php 버전 7.0.0 에서 기본 카운터 애드온을 사용하면

관리자 첫 페이지의 레이아웃이 깨집니다.

코어 버전은 1.8.18 입니다.

**Comment by kijin** [comment]
재미있는 현상을 발견했습니다.

문제가 생기는 파일이 `modules/admin/tpl/_dashboard_counter.html`인데요... 이 파일 맨 아래에 자바스크립트 코드가 있습니다. 자바스트립트 중간쯤에 `//`로 시작하는 주석이 두 줄 있는데, 이걸 지워주면 정상적으로 관리자 화면이 나오더군요 ㅡ.ㅡ;;

주석을 지우지 않더라도 자바스크립트의 분량만 어느 정도 줄여주면 또 괜찮더군요. PHP 7에서는 템플릿 파일에 다량의 자바스크립트가 포함되어 있을 경우 XE 템플릿 문법 변환이 잘 안 되나 봅니다.

**Comment by kanxion** [comment]
@kijin 맞네요. 주석 두줄을 지워주니 깨졌던 관리자 메인 페이지와 페이지뷰 그래프도 정상적으로 나오는군요. 감사합니다 ^^

**Comment by kanielu** [comment]
덕분에 #1870 문제 해결하였습니다.
다음 버전에서는 해당 이슈가 수정되었으면 좋겠네요 ^^;

**Comment by bnu** [comment]
템플릿 파서에서 어떤 문제가 있을 것으로 보이네요.
우선 스크립트 파일을 분리하는 것으로 조치하였으나, 근본 문제는 다른 이슈에서 다루도록 하겠습니다.
