### ISSUE TITLE
1.8.15 에서 1.8.18 업데이트후 video 태그 이상 발생

### ISSUE THREAD

**Issue by WanbinLim** [xpressengine/xe-core#1885]
xe 기본 게시판에 모바일 스트리밍 동영상 mp4를 video 태그로 작성하여 스마트폰에서 볼 수 있게 
하였음..    1.8.15 까지는 게시물 작성과 스마트폰으로 보기가 잘 작동하였으나 1.8.18 업데이트후 
video 태그가 안되고 html 내용이 다 사라짐..

**Comment by kijin** [comment]
#1876 #1882 참고하세요.

**Comment by bnu** [comment]
fixed in #1882
