### ISSUE TITLE
RSS 통합피드 문제 도저히 제 선에서 해결이되지않습니다.

### ISSUE THREAD

**Issue by bacaptain** [xpressengine/xe-core#1886]
bestaid.kr 을 운영하고 있습니다. RSS에 문제가 있습니다!

https://bestaid.kr/index.php?mid=notice&act=rss

이런식으로 RSS피드는 정삭 출력되지만,

https://bestaid.kr/index.php?mid=notice&act=rss 이렇게 통합피드는 잠겨있다고 나옵니다.

RSS 모듈에서도 통합피드 사용, 각 게시판에서도 추가설정에서 통합피드에 포함에 사용을 시켰고,

phpmyadmin에서 xe_module_config > rss 에서 "use_total_feed";s:1:"Y";  인것도 확인했습니다.

이유를 정말 알수가 없네요! 현재 코어는 1.8.13 버전을 사용하고 있습니다,

**Comment by bnu** [comment]
fix #1920
