### ISSUE TITLE
제목 따옴표 입력시 

### ISSUE THREAD

**Issue by madnomad1101** [xpressengine/xe-core#1893]
\&quot; 로 바뀝니다.

1.8.19버전

**Comment by kijin** [comment]
게시판 스킨에 따라 차이가 있을 수 있습니다. 기본 스킨(XEDITION)에서는 제목에 따옴표를 입력해도 따옴표 그대로 잘 나오네요.

**Comment by madnomad1101** [comment]
음 저는 XEDITION으로도 안 되네요...

**Comment by madnomad1101** [comment]
php 버전 차이때문일 수도 있을까요?
