### ISSUE TITLE
#1011 md5(rand(111111,999999) 관련

### ISSUE THREAD

**Issue by dorami** [xpressengine/xe-core#1901]
#1011 md5(rand(111111,999999) 대신 $random->createSecureSalt(32, 'hex') 쓰면 파일 엔트로피가 향상되지 않을까요?

**Comment by kijin** [comment]
외부에 노출되는 파일명이 아니라 잠깐 임시파일로 사용했다가 삭제할 뿐이므로 큰 상관은 없다고 생각됩니다만, 제대로 된 랜덤 문자열을 사용하면 동접자가 아주 많은 사이트에서 중복이 발생할 가능성을 낮출 수는 있겠네요.

**Comment by dorami** [comment]
네, 임시파일이라 상관은 없겠지만, 머... 우연이 있을 수도 있죠.

**Comment by bnu** [comment]
@dorami 그렇지 않아도 변경했었는데 정리하면서 빼먹었나 봅니다.

**Comment by bnu** [comment]
아.. 뭔가 이상하네요. 의도했던 몇가지 코드가 빠져있네요.
다른 로컬 브랜치에 커밋했던지 stash에 들어있던지 할 것 같네요 ㅠ

**Comment by bjrambo** [comment]
@bnu 머지를 마스터로 한것들도 몇가지있어서 develop에서는 적용안된것들도 ..처리해야할듯요

**Comment by bnu** [comment]
헷갈렸네요; 폰으로 보다보니 이력 보기가 힘들어서..
https://github.com/xpressengine/xe-core/blob/master/modules/document/document.item.php#L886-920 적용되어 있습니다.

**Comment by dorami** [comment]
@bnu 커밋을 전부 확인을 안 했었네요. 다음부터는 다 확인하고 이슈 올릴게요.
이슈 닫습니다.

**Comment by bnu** [comment]
@dorami 제가 커밋에 이슈 번호를 붙이지 않아서 그렇죠 뭐 ^^;
