### ISSUE TITLE
XEIcon 업데이트

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#1904]
2.2.0 버전 적용

**Comment by kijin** [comment]
아이콘 누락 문제는 모두 해결되었나요?

**Comment by bnu** [comment]
@kijin 사용성이 떨어지는 아이콘은 삭제하고 클래스 이름이 다소 변경되어 메이저 버전으로 업데이트 되었습니다.

**Comment by kijin** [comment]
서드파티 자료에서 xeicon을 끌어다 쓰는 경우가 상당히 많습니다. 코어에 포함되어 있으니 당연히 의존할 수 있을 거라고 생각했겠지요. 그런데 마이너버전(1.9)도 아닌 패치버전(1.8.21)에서 갑자기 일부 아이콘이 사라지거나 클래스명이 변경되면 어떻게 하죠?

**Comment by Lastorder-DC** [comment]
갑자기 이슈가 생기고 얼마 안되서 커밋이 되고... 점점 XE 개발이 밀실에서 진행되는 것처럼 느껴집니다. 여기 저장소는 그냥 공개용 저장소인가요?

**Comment by bjrambo** [comment]
https://www.xetown.com/qna/285726
실제로 이런질문도 올라올만큼. 사용되는 아이콘이 사라지는 경우가 있으면 사람들이 쓰기가 난감할듯요.
물론 이미지가 바뀔수는 있다는건 맞지만, 이미지가 바뀌더라도 그 이미지가 사라지는 경우는 없어야해요.

**Comment by bnu** [comment]
넵. 사용상에 문제가 발생하니, 되돌리고 1.9 버전에서 적용하도록 하겠습니다.

**Comment by kijin** [comment]
자세히 확인해 보니 XEIcon 1.0.4에서 정의된 클래스 680개 중 367개가 XEIcon 2.2.0에 존재하지 않습니다. 무려 54%가 바뀌었네요. alias 처리를 해주지 않는다면 1.9에서도 무리일 것 같습니다.

**Comment by kijin** [comment]
XEIcon 1.0.4 클래스 680개
XEIcon 2.3.3 클래스 914개
양쪽 모두 지원하는 클래스 400개
XEIcon 1.0.4에만 있는 (XE 1.10에서 지원 종료되는) 클래스 280개
XEIcon 2.3.3에만 있는 (XE 1.10에서 신규 지원하는) 클래스 514개

서드파티 자료에서는 XEIcon에 의존하지 말라고 시그널을 보내시는 것 같군요. 마음놓고 쓰지도 못할 거 뭐하러 업데이트하시는지 모르겠습니다.

**Comment by Lastorder-DC** [comment]
@bnu 그대로 적용시 당장 코어의 XEIcon에 의존하던 수많은 자료들이 깨지게 됩니다. 설마 또 릴리즈 노트에 ~~했으니 아이콘 코드를 찾아서 바꿔주세요 하고 올리시고 말건가요?

**Comment by bnu** [comment]
릴리즈 취소. 이슈 종료.
