### ISSUE TITLE
favicon 과 mobicon의 경로에서 '/'가 빠지는 오류

### ISSUE THREAD

**Issue by haendel7** [xpressengine/xe-core#1911]
```
<link rel="shortcut icon" href="http://domain.comfiles/attach/xeicon/favicon.ico" />
<link rel="apple-touch-icon" href="http://domain.comfiles/attach/xeicon/mobicon.png" />
```

이렇게 출력됩니다.

어쩐지 아주 오래간만에 최신버전 업데이트 후 잘 안되더라구요.

**Comment by kijin** [comment]
기본 URL에서 `/`를 빠뜨리신 것 아닌가요?

**Comment by cglink** [comment]
아 그거 꼭 넣어야하는거였나요? 몇 년째  그거 없이 써왔었는데...ㅎㅎㅎㅎ
그렇게 하니 되네요. ^^;;; 뻘쭘..

**Comment by dorami** [comment]
#1827 에서도 말했던 문제이긴합니다. 기본 URL을 관리자 패널에서 입력하면 /가 자동으로 붙지만, db.config.php에서 수정하면 위와같은 현상이 발생될 수 있죠.
