### ISSUE TITLE
관리자 [사이트 메뉴 편집] 기능 오류가 있습니다. 

### ISSUE THREAD

**Issue by msgbox486** [xpressengine/xe-core#1912]
늘 수고가 많습니다. 
 
다른 사이트맵으로 여러 개의 하위메뉴가 달려 있는 메뉴폴더를 이동시키려고 할 때,    
하나의 메뉴만 이동되고, 다른 메뉴들은 공중으로 사라집니다. 
메뉴와 연결되어 있던 "게시판이나 페이지" 모들들은 
아예 삭제된 것 같기도하고, 어디에 마치 유령처럼 숨어 있는 것 같기도 하고,,,
기존 바로가기 타입의 메뉴와 연결되어 있던 링크메뉴들도 막 바뀌어지는 것 같습니다. 
Update 빨리 되었으면 좋겠네요..
 
여러개의 사이트맵과 방대한 메뉴를 가지고 있는 웹사이트의 경우, 
[사이트 메뉴 편집]  기능의 작동이 너무 느리고,  매우 힘듭니다. 
특히 가장 많이 쓰여지는 메뉴의 이동에 대한 
좀 더 손쉽고 직관적인 방법도 강구해 주었으면 좋겠네요..
매뉴수정 창 "붙여넣기" 밑에 [이동메뉴]를 두고, 
하위 [이동메뉴] 창에서는 
"바로가기 메뉴"의 "URL 링크"나 "메뉴링크"를 거는 방식처럼
직접 이동하고자 하는 곳의 메뉴를 선택 지정하는 방식이 조금은 덜 힘들 것 같습니다.. 
 
XE Core가 대단히 무겁고 동작이 아주 굼뜬 상태에서 
마우스로 하나하나 정확하게 메뉴를 드래그하여 이동시키는 현재의 방식은 
너무 정교한 손기술을 요구하고 있네요.  ㅠㅠ
 
MS 윈도우의 파일 탐색기 방식을 최고로 알고 XE가 꼭 고집해야 할 이유도 없을 것 같은데,,,
아마도 이러한 방식을 계속 따라하여 구사하다보니 
XE 관리자 시스템이 쓸데없이 커지고. 동작이 더뎌진 것에 일조를 한 것 같기도 하네요..
 
사용자는 항상 단순하고 직관적인 것을 제일 좋아합니다. 
물론 개발자도 윈도우 이전 도스시대가 그립겠지만, 
그리해서는 아니되겠지요.. ^^
그럼 수고 많이 하세요..

**Comment by bnu** [comment]
UI를 대거 교체하기는 어려운 점이 있습니다.

속도 개선은 메뉴 출력을 위해 사용하는 파일 재생성이 너무 많이 이루어지는 부분이 있어 개선하려 했으나 좀 더 정리가 필요하여 다음 마일스톤(다음 배포)에서 잡아보도록 할 예정입니다.

**Comment by eondcom** [comment]
1.8.21로 업데이트해도 사라진 메뉴가 안 나타납니다. ㅠㅠ 다시 오픈해주세요;;;
