### ISSUE TITLE
업데이트하라고 계속뜸

### ISSUE THREAD

**Issue by djdisodo** [xpressengine/xe-core#1913]
이 사진이면 설명이 될것같네요

![image](https://cloud.githubusercontent.com/assets/17721656/15709923/661a9ea2-2842-11e6-8381-73bdba6f0c96.png)

http://njmcpe.kro.kr/d.jpg

![image](http://113.131.18.55:8000/list/HDD1/a5004ns_plugin/d.JPG)

**Comment by smaker** [comment]
FTP로 직접 업데이트하는 경우, 버전 업데이트가 되었다는 것을 제대로 인지하지 못합니다.
이걸 관리자 페이지에 접속할 때마다 매 번 확인하는 게 아니라, 캐시 파일로 저장해놓기 때문에 생기는 문제입니다.

대부분의 경우에는 캐시파일 재생성을 하게 되면 해결되는데, 그래도 업데이트하라고 나오는 경우라면 XE 자료실 서버 문제입니다.

**Comment by kang154123** [comment]
그냥 ftp로 업데이트 파일을 덮어씌우시고 캐시 재생성 하시면 됩니다.
