### ISSUE TITLE
업데이트 후 알림센터가 올바르게 동작하지 않음

### ISSUE THREAD

**Issue by kang154123** [xpressengine/xe-core#1916]
업데이트 후 알림센터가 올바르게 동작하지 않음, 관리자가 선택한 게시판의 댓글을을 무조건 알림에 뜨게 설정하였으나 이게 동작하지 않음.

**Comment by bjrambo** [comment]
곧 알림센터 업데이트할예정이에요.
XE이슈는 아닌것 같네요.,
