### ISSUE TITLE
xe1.8.21버전으로 업데이트해도 사라진 사이트맵 하위메뉴가 다시 나타나지 않습니다.

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#1918]
xe1.8.21버전으로 업데이트해도 사라진 사이트맵 하위메뉴가 다시 나타나지 않습니다.

1.8.15 버전에서 사이트맵 이동 중 하위메뉴가 사라지는 버그가 있어
1.8.21 버전으로 업데이트했는데 어떤 것은 다시 나타나는데
어떤 메뉴는 다시 나타나지 않습니다.
'phpmyadmin에서 해당 메뉴 이름을 검색해보면 나오지만'
사이트맵에서는 실제 캐시파일을 삭제하고 캐시파일 재생성해봐도 나타나지 않습니다.
제 위치에 나타나달라는 말은 못해도 unlinked에도 나타났으면 좋겠습니다. ㅠㅠ
페이지관리에 보면 해당 페이지가 있습니다만 사이트맵에서는 안 나타나네요;

**Comment by eondcom** [comment]
추가
같은 메뉴명을 가진 메뉴
예를 들어, 

도움말(동일A)
도움말(동일B)
-도움말1
-도움말2

동일한 메뉴명을 가진 메뉴 중, 하위메뉴가 달린 메뉴(B)를 전체 삭제했을 시,
사이트맵에서 A도 사라지는 현상이 있습니다. (실제 게시판이 사라지는 건 아닙니다.)

**Comment by bnu** [comment]
(기존 버그에 의해) 하위 메뉴를 잃은 상태에서 상위 메뉴를 이동 시 고스트 한 마리를 발견했습니다…
예로 66번 메뉴가 버그 및 어떤 이유로 인해 다른 사이트 맵으로 이동 됐으나 하위 메뉴를 데려오지 못한 경우 66번 메뉴가 양쪽에 존재(cache 파일에서만)하는 현상이 있습니다.
DB 상 실제 위치한 메뉴를 기존 사이트맵으로 이동하면 중복 문제가 해결되는 것으로 확인했습니다.

꼬인 DB를 정리할 수 있는 기능을 어딘가에 넣기는 해야할 것으로 보이긴 합니다. 고민해봐야겠어요.
