### ISSUE TITLE
1.8.21 업데이트 이후 문제

### ISSUE THREAD

**Issue by fy5914** [xpressengine/xe-core#1919]
업데이트 이후에 아래와 같이, 외부파일 불러오기로 구성해서 정상적으로 보여지던 부분들이
하나도 보여지지 않고 있는 문제가 발견됐습니다.

< img class="zbxe_widget_output" path="http://....중략..../001.html" skin="default" widget="opageWidget" / >

버그라면 어서 패치되길 바래봅니다 (__)

**Comment by bnu** [comment]
해당 위젯을 직접 확인해봤으나 특별한 문제를 발견하지는 못했습니다.
생략한 실제 사용하신 주소를 알려주시면 문제를 찾는데 도움이 될 것 같습니다.
bnu@xpressengine.com 으로 주셔도 좋습니다.

**Comment by bnu** [comment]
#1922 에서 해결 됨
