### ISSUE TITLE
1.8.21 업데이트 후 SSL 환경에서 댓글 작성 후 갱신 문제

### ISSUE THREAD

**Issue by gigglehd** [xpressengine/xe-core#1922]
개인적으로 수정을 한 스케치북 스킨을 사용 중 1.8.20에서 1.8.21로 업데이트를 했습니다. 수정을 했다고는 하나 스킨 위치나 디자인 정도가 고작이며, 큰 부분은 아니지만 일단 설명은 해야되지 싶어서 씁니다. 

업데이트 이후엔 댓글을 작성해도 페이지가 리프레시 되지 않네요. 수동으로 갱신하면 댓글은 등록 돼 있습니다. 

수차례 삭제/재설치/테스트를 거듭한 결과, SSL 보안을 사용 중인 경우 해당 증상이 나타나는 것으로 확인됐습니다.

그리고 1.8.21에서 수정된 .htaccess 파일만 1.8.20으로 롤백했을 경우, 이 증상이 사라집니다.

해당 파일이 1.8.20에서 1.8.21로 오면서 달라진 점이라면 4번째 줄이
RewriteRule ^(layouts|m.layouts)/(.+)\.html$ - [L,F]
에서
RewriteRule ^(common|layouts|m.layouts)/(.+)\.html$ - [L,F]
로 바뀐 것이 전부입니다. 한 쯤 확인이 필요하지 않나 싶습니다.

**Comment by bnu** [comment]
#1887 에서 변경했던 코드의 영향으로 인한 문제로, 해당 변경 내역을 되돌렸습니다.
