### ISSUE TITLE
업데이트 이후 아래와 같은 에러가 납니다.

### ISSUE THREAD

**Issue by tenyears10** [xpressengine/xe-core#1926]
아래와 같은 에러가 왜 생기나요?
게시판 등에서 첨부파일이 올라가지 않습니다. 

Fatal error: Call to a member function getAction() on a non-object in /host/home2/edutown/html/classes/db/DB.class.php on line 633

**Comment by bnu** [comment]
관리페이지 하단의 캐시파일을 재생성을 해보시거나 'files/cache/queries' 폴더를 삭제해보세요.
