### ISSUE TITLE
안드로이드 기기 다운로드 문제

### ISSUE THREAD

**Issue by dorami** [xpressengine/xe-core#1927]
안드로이드 기기(문제 확인 : 갤럭시 S2 KT 안드로이드 4.1.2 펌웨어)에서 다운로드 문제가 발생합니다.
Play 스토어의 크롬에서는 발생하진 않고, 기본내장된 브라우저에서 발생합니다.
파일이 다운로드 되지 않고, index.php가 다운됩니다.

**Comment by bjrambo** [comment]
일부 안드로이드 브라우저에 따라 그런것 같아요.

노트3, 최신펌웨어 5.0 업글한 것에서도 동일한 문제가 있음요.

크롬에서 받으면 문제가 없어요.(안드로이드 크롬요)

**Comment by dorami** [comment]
@bjrambo 그렇긴 한데.. 사용자가 브라우저를 바꿀 가능성이 낮죠.

**Comment by bjrambo** [comment]
라이믹스쪽에도 이슈는 일딴 올려뒀어요.

**Comment by kijin** [comment]
안드로이드 기본 브라우저의 User-Agent 문자열이 크롬과 유사하여 XE에서 크롬으로 인식하기 때문에 발생하는 문제입니다. (안드로이드 기본 브라우저는 아주 오래된 버전의 사파리로 취급해야 합니다. IE로 취급할 수도 없을 만큼 바보입니다 ㅠ)

원인: #1897

해결책: rhymix/rhymix#535

요약: User-Agent 문자열에 `Android`와 `Chrome`이 포함되어 있는 경우

- `#(Version|Browser)/[0-9]+#` 또는 `#\bwv\b#` 정규식이 매칭되면 기본 브라우저, 삼성 브라우저, 웹뷰 등 기능 제약이 많은 환경으로 취급하면 됩니다.
- 그 밖의 경우는 진짜 크롬입니다.
