### ISSUE TITLE
업데이트 이후 자료를 올리고 다음과 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by bery97** [xpressengine/xe-core#1932]
![106](https://cloud.githubusercontent.com/assets/5966495/16545928/d43a3420-4173-11e6-8490-6a835d477326.png)

고생이 많으십니다.
글쓰기로 자료를 첨부한 후 https로 바뀌는데 나의 글에서도 https 상태입니다.
그 상태로 첨부한 파일을 다운 받으려 하면 위와 같은 에러가 발생합니다. 
다른 글을 읽고 다시 첨부한 파일을 다운 받으면 http로 바뀌어 가능합니다. 
버그 패치 부탁드립니다. 감사합니다~ ^^

**Comment by jdssem** [comment]
보충 설명을 드립니다. 현재 1.8.22 사용중입니다. 사이트에서 선택적 SSL을 사용중인데 게시판 글 작성 전에는 http였다가 글작성을 누르면 https로 변경됩니다. 그리고 파일을 첨부한 후 저장을 하면 글의 본문으로 리다이렉트가 되는데 이때 https가 유지되면서 문제가 발생합니다. 첨부파일의 링크는 http로 연결이 되어 있어서 파일을 누르면 외부링크에서 다운로드 할 수 없다는 메시지가 표시됩니다. 본인이 글을 작성한 직후에만 나타나는 문제이고 다른 사용자가 게시물을 확인하거나 본인도 다른 게시판 이동 후 다시 글을 읽을 때는 정상적으로 http로 접근하기 때문에 문제가 되지 않습니다.

**Comment by bnu** [comment]
fixed #1939
