### ISSUE TITLE
$dbinfo 정보를 한가지으로 통일 해야할 필요성이있음.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#1933]
서버를 이전한다거나 도메인이 바뀌는 경우 $dbinfo 를 설정할 경우 보통은
files/config/db.config.php 파일을 수정하게됩니다.
근데 이 부분에서 문제가 있는것이,
files/config/db.config.php 파일에 있는 정보와는 따로 site 의 url을 정하는 기본적인 디비 정보도 파일이 아닌 DB에 저장되는 현상같아요.

예를 들어서,
a.com 도메인을 b.com 으로 옮겼을 경우,
보통 하는 방법으로
files/config/db.config.php 파일만 수정하는경우가 대다수이지만,일부 관리자 페이지의 mid링크에서 쓰이는 기본 url은 a.com 으로 연결되기도 합니다.

이경우에는 관리자 도메인을 설정하는 구간에서 한번더 적용을 해야 비로소 모든 url이 재대로 맞춰지죠.

결국 하나의 default_url을 재대로 처리안하고 있는 상황이라 유저의 입장에서는 혼란이 좀 있을 것 같아요.

파일이 기본적으로 db_info설정하는 페이지에서 가져오고 있다면 default_url 정보도 모두 한곳에서 처리하는것이 어떤가요?

**Comment by bnu** [comment]
`xe_site` 테이블(DB)과 files/config/db.config.php 파일의 도메인 두 곳에 설정되어 있어서 양쪽을 모두 바꾸지 않으면 문제가 된다는 내용이죠?

이건 좀 고민을 해봐야 할 부분인 것 같네요.
SSO 등을 처리하기 위한 메인 도메인을 지정하기 위한 것이라, db.config.php의 'default_url'을 폐기하고 xe_site 테이블의 site_srl이 0인 도메인을 사용하는 것으로 다른 문제가 발생할지 확인해봐야 할 듯 하네요.

**Comment by kijin** [comment]
현재 Context.class.php 270줄 전후에서 site_srl이 0인 사이트(기본 사이트)의 domain을 기본 URL로 강제 지정해 주고 있습니다. 0번 사이트는 항상 기본 URL이 되는 셈이지요.

개인적으로 DB보다는 설정파일에 이 내용이 들어 있는 것이 사용자 입장에서 편리하다고 생각됩니다. 기본 URL에 해당하는 정보를 DB에 저장하는 워드프레스의 경우, 이것을 변경하려면 phpmyadmin에 들어가서 여러 레코드를 직접 수정해야 합니다. XE처럼 캐시 기능이 있다면 DB를 변경하더라도 즉시 적용이 안 되어서 더 많은 혼란이 발생하겠지요. site 테이블의 내용을 관리 모듈에서 쉽게 변경할 수 있는 것도 아니고, 대부분의 서드파티 자료는 site를 여러 개 추가하는 상황에 전혀 대응이 안 되어 있기도 하고요.

기본 URL을 어떤 방식으로 처리하든, 일반적인 웹호스팅 환경에서 느닷없이 기본 URL이 설정되지 않았다느니, 잘못된 요청이라느니 하는 에러는 뜨지 않았으면 합니다.

**Comment by bjrambo** [comment]
@kijin :+1: 제머리속에서 사시는분..?ㅋㅋㅋ

**Comment by bnu** [comment]
@kijin 네. db.config.php의 값을 사용하는게 편집이 쉽겠죠.
