### ISSUE TITLE
iframe 이 않됩니다

### ISSUE THREAD

**Issue by bb0404** [xpressengine/xe-core#1937]
설정->일반->embed Filter->iFrame에 해당 URL을 추가 했습니다.
일반 사용자도 iframe 동작을 하지 않아서
admin 사용자도 iframe 을 올려 보니 화면에 보여 지지 않습니다.

1.8.22 에서 그런건가요 ?

iframe src는 http://www.test.kr/order/_skin_MO_t/prodm.php?idx=124&p_gubun=m 이런 식 입니다.

다른 사항을 봐야 할까요 ?

**Comment by YJSoft** [comment]
해당 사이트의 설정이 프레임 금지인 경우 화이트리스트와 상관없이 화면에 보이지 않을 수 있습니다. iframe 코드가 있음에도 빈 화면만 보인다면 이경우입니다. 이외 iframe 태그 자체가 삭제되는 경우 필터 입력을 잘못 하신 경우입니다.

**Comment by bb0404** [comment]
admin 계정으로 글쓰기를 할경우에는 src 가 보입니다.
제가 사용하는 다른 버전 1.8.17에서는 admin계정으로 글쓰기를 하면 잘 보입니다.
로그를 확인할 방법은 없을까요 ?
