### ISSUE TITLE
ck에디터 맥 이모티콘

### ISSUE THREAD

**Issue by madnomad1101** [xpressengine/xe-core#1944]
맥 사파리
xe 1.8.22
ck에디터

맥에서 첨부한 이미지의 맥 이모티콘을 포함하면 이모티콘 뒷 부분의 내용은 저장이 안되고 사라집니다.

![2016-08-15 7 29 23](https://cloud.githubusercontent.com/assets/16433450/17670850/d10dcff8-634e-11e6-8d0c-9daf5bedac11.jpg)

**Comment by kijin** [comment]
이건 XE 문제가 아니라 MySQL에서 UTF-8 이모티콘을 제대로 처리해 주지 못해서 생기는 현상입니다.

아래의 애드온을 설치하면 해결됩니다.
https://www.xpressengine.com/index.php?mid=download&package_id=22753796

**Comment by madnomad1101** [comment]
감사합니다 적용하니 되네요.
