### ISSUE TITLE
파일 제한 크기 및 문서 첨부 제한 1M설정됨

### ISSUE THREAD

**Issue by Micalgenus** [xpressengine/xe-core#1948]
1.8.18을 사용하다 버전업을 하였는데, 1.8.23이후 버전부터는 파일첨부의 크기제한이 1M로 강제설정됨을 발견하였습니다. DB에는 기존에 사용하던 값이 정상적으로 들어가있는데, 아마 불러오는 부분에서 1M로 불러오는게 아닌가 싶습니다.

+ 새로운 설치로 하는 경우에는 정상적으로 이루어 지는데, 덮어쓰기를 통한 업데이트할 경우 이러한 문제가 생깁니다.

**Comment by bnu** [comment]
문제가 재현되지 않습니다.
php.ini의 upload_max_filesize 값을 확인해보세요.

upload_max_filesize 설정 값 이하로만 사용할 수 있습니다.

**Comment by Micalgenus** [comment]
확인을 해보았는데 1G로 설정할 경우 1M로 강제적용됨을 보았습니다. 1024M로 설정하니까 문제가 발생하지 않는데, 1G로 설정할 경우 문제가 발생하게 되네요.
