### ISSUE TITLE
page 모듈과 board 모듈에서 브라우저 제목 다국어 풀림 현상

### ISSUE THREAD

**Issue by cydemo** [xpressengine/xe-core#1955]
page 모듈이나 board 모듈 등에서 브라우저 제목(browser_title)을 다국어로 입력하고 등록하면 다국어 기능이 처음에는 잘 작동합니다.
그렇지만, 게시판 목록수를 변경하는 등 설정 내용을 수정하고 다시 등록 버튼을 눌러보면, 브라우저 제목의 다국어가 풀립니다.
등록 버튼을 눌렀을 당시의 언어 모드로 고정돼 버리는 거죠.

디비에서 모듈 테이블을 보면 browser_title에서 $user_Lang이 사라지고 '블로그' 같은 식으로 내용이 변경된 걸 확인할 수 있었습니다.

애드온을 모두 끄고 테스트를 해봐도 마찬가지였습니다.
언제부터였는지는 모르겠지만 1.8.24 버전에서 관련 문제를 확인했습니다.

**Comment by YJSoft** [comment]
모듈 설정 페이지에서 다국어가 정상적으로 불러와지지 않아, 저장 시점에서 다국어 변수 대신 현 언어 기준 문자열이 전달되어 발생하는 현상입니다.
