### ISSUE TITLE
글쓰기 때 "\0..." 으로 시작하는 특수문자가 입력되면 글이 저장되지 않고 메인으로 튕기는 현상.

### ISSUE THREAD

**Issue by kimhangook** [xpressengine/xe-core#1965]
맥에서 작업을 주로 하는 편인데...
가끔씩 글을 복사해서 붙여넣기 할 때가 있습니다.
이때 간혹 글이 등록되지 않고 메인으로 튕겨버리는 문제가 있어서 확인을 해봤더니 \0~으로 시작하는 문자가 있는 경우 이런 문제가 발생하더군요.

http://www.biz-gis.com/test.zip

위 파일에 문제가 있는 특수문자가 들어있습니다.
|(파이프) 와 |(파이프) 사이에 특수문자가 있는데 일반 메모장에서는 보이지 않고,
노트패드++에서 확인 가능합니다.

해당 문제 개선 부탁드립니다.

**Comment by kijin** [comment]
첨부하신 파일에는 `VERTICAL TAB (\0b)` 문자가 포함되어 있는 것으로 보입니다.
(총 3바이트, `\7c\0b\7c`)

이 파일을 Notepad++에서 열어 Ctrl+A로 모두 선택한 후 Ctrl+C로 복사하고 글쓰기 창에 Ctrl+V로 붙여놓어 보았으나 말씀하신 것과 같은 증상은 발생하지 않았습니다. 글쓰기 후 그냥 공백으로 표시됩니다. 최고관리자 권한으로 글을 쓸 때와 일반 회원 권한으로 쓸 때 마찬가지인 것으로 보아 HTML 필터링에 차이가 있는 것 같지도 않고요.

테스트해본 환경은 XE 최신버전(1.8.24), PHP 7.0, 에디터는 CKEditor, 브라우저는 Firefox였습니다. 만약 다른 환경에서 에러가 발생한다면 버전과 에디터 종류, 브라우저 종류를 알려주시기 바랍니다.

**Comment by kimhangook** [comment]
XE Core ver. 1.8.24
에디터: CKEditor
브라우저: 크롬
서버 환경: UTF-8 (PHP5.5, MySQL5.x)

혹시 몰라 최신 XE Core ver 전체를 FTP로 업로드하였는데도 마찬가지 입니다.
