### ISSUE TITLE
#1978 보안패치가 이상합니다.

### ISSUE THREAD

**Issue by kijin** [xpressengine/xe-core#1979]
1. member.controller.php에서는 바로 위에서 `removeHackTag()`를 했는데 또 하고 있습니다.
2. member.model.php에서는 서명을 불러올 때마다 일일이 `removeHackTag()`를 해주고 있습니다.

`removeHackTag()` 함수는 HTML Purifier를 사용하기 때문에 성능에 미치는 영향이 매우 큽니다. 불필요하게 반복 호출하는 일이 없어야 하겠습니다.

**Comment by bnu** [comment]
....... (  '')

**Comment by bjrambo** [comment]
....... ('' )..b

**Comment by kijin** [comment]
1.8.28에서 처리되었으므로 닫습니다.
