### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by npmine** [xpressengine/xe-core#1986]
Catchable fatal error: Object of class stdClass could not be converted to string in /host/home3/adminnp/html/files/cache/template_compiled/78ef82787e4093282c6a44fb444efcb2.compiled.php on line 803

무슨오류 인지.....

**Comment by kijin** [comment]
사용하시는 레이아웃이나 모듈 스킨에 오류가 있는 것 같습니다. 특정 모듈에서만 오류가 나온다면 그 모듈에 현재 적용된 스킨을 의심해 보셔야 하고, 모든 화면에서 오류가 나온다면 공통으로 적용된 레이아웃을 의심해 보셔야 합니다. 예전에 만들어진 모듈이나 스킨은 최근 버전의 PHP와 호환되지 않는 것이 많습니다.
