### ISSUE TITLE
php-7.1.0 환경입니다.

### ISSUE THREAD

**Issue by dmzvillager** [xpressengine/xe-core#1995]
xe-1.8.27 설치를 시도하니 "Fatal error"가 나네요.

**Comment by paulryu03** [comment]
XE 1.8.29 에서도 아직 고쳐지지 않았는데 PHP 7.1 에서 설치가 안되는 문제는 굉장히 빨리 고쳐져야 할 이슈인 것 같습니다.

**Comment by dmzvillager** [comment]
1.8.29에서 인증 세션 DB 사용시 로그인 안되는 버그도 있습니다.

**Comment by bnu** [comment]
@dmzvillager 확인했습니다. #2033 이슈에서 처리하겠습니다.
