### ISSUE TITLE
file모듈 webm파일에 대한 처리

### ISSUE THREAD

**Issue by huhani** [xpressengine/xe-core#1997]
https://github.com/xpressengine/xe-core/blob/master/modules/file/file.controller.php#L932

html5환경이 빠르게 조성되면서 webm파일 사용도도 점점 높아지는데
webm 파일도 멀티미디어로 동작하게 하면 어떨까 싶습니다.

**Comment by bnu** [comment]
webm과 함께 webp, ogg, m4a, m4v 파일 확장자도 추가했습니다.
