### ISSUE TITLE
wincache 설정후 일반설정에서 저장을 하면 사라져버리는 문제

### ISSUE THREAD

**Issue by kekeke00** [xpressengine/xe-core#2002]
관리자메뉴의 설정->일반에서 저장을 하면 

$db_info->use_object_cache = 'wincache';
$db_info->use_template_cache = 'wincache';

db.config.php에 이렇게 저장해둔 wincache 설정이 사라져버리네요.
물론 설정을 끝마치고 해두면 상관없어 보이긴합니다.

**Comment by bnu** [comment]
최신버전 기준으로 해당 문제가 확인이 안 됩니다.
