### ISSUE TITLE
통합검색에서 검색된 키워드중 mp3 파일이 여러개 일경우,

### ISSUE THREAD

**Issue by botserv** [xpressengine/xe-core#2007]
현재 최신버전에서 미디어 파일 mp3파일의 경우 크롬에선 미리 듣기가 지원이 되는데

이게 기본값이 바로 실행이라서

첨부 결과값이 여러개 일경우 모든 음악파일이 동시에 재생되는 경우가 있습니다.

**Comment by bnu** [comment]
통합검색에서 미리 듣기 기능 등을 제거 할 예정입니다.
