### ISSUE TITLE
XE Admin 관리자 레이아웃 편집모드 사용시 소스코드가 노출될 수 있는 취약점 존재

### ISSUE THREAD

**Issue by Xvezda** [xpressengine/xe-core#2010]
사이트 디자인의 레이아웃 HTML/CSS 설정에서 편집시 레이아웃 템플릿 경로가 `files/faceOff` 로 바뀌게 되는데
`.htaccess` 의 `RewriteRule` 중 위의 경우에 대한 reserve 처리가 되어있지 않아, 노출이 되는 문제가 있습니다.

아무래도 XE 사용경험이 풍부하신 웹마스터 분들에 비해 해당 메뉴를 사용하시는 분들은 XE를 접한지 얼마 안되신
분들이 비중이 크기 때문에, 인지없이 레이아웃에 직접 취약한 코드를 추가 할 경우 위 취약점은 치명적일 수 있습니다.

또한 오픈 라이선스가 아닌 레이아웃의 경우에도 위 취약점으로 코드가 전부 공개 되어버리는 것과 같아,
불이익을 받을 수 있습니다. 레이아웃이 include 방식으로 분할되어있는 구조가 아닐경우 더 심각합니다.

**Comment by Xvezda** [comment]
PR #2011 
+) Nginx User분들 께서는 

```
# reserve XE Layout Template Source File (*.html)
rewrite ^/(layouts|m.layouts|files/faceOff)/(.+)/(.+)\.html$ /index.php last;
```
를 `xe_rewrite.conf` 에 있는 내용과 교체하여 주시면 됩니다.

**Comment by kijin** [comment]
nginx에서 저런 용도로 rewrite를 쓰는 것은 좋지 않습니다. 접근을 금지하고 싶은 파일이 있다면 location 블럭 안에서 return 403; 해주는 것이 정석입니다.

참고: https://github.com/rhymix/rhymix/blob/master/common/manual/server_config/rhymix-nginx.conf

**Comment by Xvezda** [comment]
커밋PR 후에 생각이 나 [xpressengine/xe-core/wiki/Nginx-rewite-설정하기](../wiki/Nginx-rewite-설정하기) 페이지 에서 참조하여 
추가한 코멘트 인데, @kijin 님이 제시한 방향이 더 웹 표준에 맞는것 같네요. 동의합니다.
