### ISSUE TITLE
1.8.9 에서 업그레이드 시 .JPG 대문자 확장자 썸네일 생성 fail

### ISSUE THREAD

**Issue by djclamo** [xpressengine/xe-core#2012]
1.8.9 에서 업그레이드 시, 이미지 갤러리가 제대로 생성되지 못하는 버그가 있습니다.

디버깅결과 1.8.9 에서 업그레이드를 하면, JPG 확장자가 대문자인 경우에는 갤러리를 생성하지 못합니다. (확장 콤포넌트 -> 이미지 갤러리 사용)

갤러리는 썸네일 방식으로 만들어지는걸로 알고 있는데, getThumbnail 코드 자체내에서도 대문자/소문자를 구분 못하는 버그는 없는 것 같습니다. ($/i) 아마 1.8.9 에서 업그레이드 시 썸네일 코드 자체에는 문제가 없지만 게시판이나 쿼리 방식에서 어딘가 연결이 제대로 되지 않고 있는 것 같습니다.

제 클라이언트의 xe보드는 전부터 꾸준히 업데이트 되어왔기 때문에 upgrading path 중에 생긴 버그일지도 모르겠습니다. 여건이 되는대로 최신버전 clean install 경우에도 같은 버그가 있는지, 1.8.9 clean install 에서 최신으로 업그레이드해도 버그가 재현되는지 테스트 해보고 결과를 공유하겠습니다.

**Comment by clamo** [comment]
확인결과 최신 버전에서도 같은 버그가 있습니다.
1.8.9 이후에서만 jpg 파일확장자가 대문자일 경우 썸네일 갤러리에 보여지지 않습니다.

**Comment by clamo** [comment]
공식 게시판들에서만 재현 가능한 이슈 같습니다. 커뮤니티가 제작한 스킨에서는 (JB) JPG 대문자 확장자 파일들도 잘 보입니다.

기본 게시판에서 이런 버그나 나타난다니 아쉽네요

**Comment by bnu** [comment]
`getThumbnail()` 등 썸네일과는 별개이며 해당 컴포넌트에서 이미지 목록을 가져올 때 소문자 확장자만 인식하는 문제를 고쳤습니다. 감사합니다 :)
