### ISSUE TITLE
1.8.27에서 그 이상 버전(1.8.28, 1.8.29)으로 업데이트시 메세지 출력되지 않음

### ISSUE THREAD

**Issue by Arepin** [xpressengine/xe-core#2014]
1.8.27에서 그 이상 버전(1.8.28, 1.8.29)으로 업데이트하면 로그인 실패("존재하지 않는 회원 아이디입니다.", "잘못된 비밀번호입니다.") 등 각종 오류 메세지가 출력되지 않습니다.

버전을 다운그레이드하니 다시 정상 출력되고요.

문제 확인 부탁드립니다.

**Comment by paulryu03** [comment]
저도 같은 증상입니다.

**Comment by kijin** [comment]
패치 방법을 #2020 에 올렸습니다.
