### ISSUE TITLE
1.8.29 업데이트 후 font awesome....

### ISSUE THREAD

**Issue by kekeke00** [xpressengine/xe-core#2015]
1.8.29 업데이트 후 메뉴에서 사용하던 font awesome 아이콘이 삭제되었고 다시 재작성해도 태그가 빠집니다.

**Comment by kimjangsuk** [comment]
저만 그런게 아니였군요 ^^;

**Comment by paulryu03** [comment]
YJSoft 님께서 XE 공홈에 다음과 같이 댓글을 남기셨네요.
https://www.xpressengine.com/devlog/23203715
(이번 보안패치 이후 메뉴에 태그 사용시 캐시파일 재생성/메뉴 수정 시점에서 태그가 전부 지워지게 됩니다. 의도한 변화라면 이를 안내해야 할 것이고 의도치 않은 변화라면 수정이 되어야 할 것입니다.)

**Comment by YJSoft** [comment]
메뉴는 관리자만 편집할 수 있는 영역이므로 태그를 필터링할 필요 없습니다. 만일 이부분 필터링이 필요하다면 당장 관리자로 글을 썼을때 필터링이 적용되지 않는 점(스크립트 자유롭게 입력가능)부터 수정되어야 할것입니다. 관리자 메뉴가 깨지는 1.8.28도 그렇고 태그를 입력못하는 1.8.29도 그렇고 최근 릴리즈시 최소한의 확인은 하는건지 의문이네요.

**Comment by bnu** [comment]
특정 보안취약점으로 인해 제한이 적용되었습니다.

**Comment by YJSoft** [comment]
@bnu 보안 취약점이 있다면야 어쩔수 없겠죠. 하지만 태그가 전부 지워지는 중대한 변화면 최소한 공지정도는 해야 하는게 맞지 않을까 싶습니다.

**Comment by kijin** [comment]
strip_tags 대신 removeHackTag를 적용한다면 보안상 문제가 없는 아이콘 폰트 같은 것들은 남길 수도 있지 않을까요?

**Comment by samswnlee** [comment]
그럼 앞으로 메뉴에 태그 사용불가인가요?
