### ISSUE TITLE
글수정시 첨부파일이 에디터에서 사라집니다. 

### ISSUE THREAD

**Issue by dmzvillager** [xpressengine/xe-core#2017]
app : Apache/2.4.25 (Unix)
xe_version : 1.8.29
php : 7.0.15
db_type : mysqli_innodb
use_rewrite : Y
use_db_session : N
use_ssl : always
phpext : core, libxml, openssl, sqlite3, zlib, bcmath, bz2, calendar, curl, dba, fileinfo, ftp, gd, gettext, gmp, iconv, intl, mbstring, mcrypt, mysqlnd, mysqli, pdo_mysql, pdo_sqlite, phar, imap, shmop, simplexml, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, xml, xmlreader, xmlrpc, xmlwriter, zip, igbinary, ssh2, zend opcache

위의 환경에서  php확장모듈 igbinary-2.0.1 or memcache 설치이후
 igbinary 설치 이전의 글 수정시 첨부파일이 에디터 상에 사라지고, 글수정 및 첨부파일 추가 후 저장하면 새글로 등록되며 첨부파일은 첨부되지 않는 버그가 있습니다. 

임시 방편으로 "인증 세션 DB 사용" 을 해제 하시면 위의 증상들이 사라집니다.

**Comment by bnu** [comment]
- DB 세션 사용 중
- igbinary OR memcache 설치 후
- 서버 환경 변경 전의 게시물 수정 시

에디터는 CKeditor인가요? 플래시 업로더가 사용된 xpress Editor인가요?

**Comment by dmzvillager** [comment]
CKeditor, xpress Editor둘다 같은 증상입니다.
