### ISSUE TITLE
게시물 밀림 현상

### ISSUE THREAD

**Issue by n0207** [xpressengine/xe-core#2018]
app : nginx/1.11.9
xe_version : 1.8.27
php : 5.6.29
db_type : mysqli_innodb
use_rewrite : Y
use_db_session : N
use_ssl : none

게시판 > 설정 > 고급설정에 있는 정렬방법을 문서번호로 정렬 시
아래 사진처럼 게시글이 밀리는 현상이 생깁니다.
(파일첨부 할 때만 밀림 현상이 있습니다.)

![dmq](https://cloud.githubusercontent.com/assets/25482285/22508877/3eba366c-e8cf-11e6-91cb-2e92ec678e05.PNG)

파일첨부를 28분에 하고 최종 글 등록 시간이 30분
2분 사이에 다른 사용자가 게시물을 작성하게 되면 저런 식으로 밀림 현상이 생깁니다.
사이트 특성상 사진을 올리는 사용자가 많은데
밀림현상때문에 불편함이 발생하는데 제 힘으로 고칠 수 없어
개발자 분들에게 도움을 요청드립니다.

**Comment by howtoxe** [comment]
파일 첨부를 하면서 문서번호가 할당되기 때문에 발생하는 문제입니다. XE는 임시저장된 게시글도 공개된 게시글과 같은 테이블, 같은 시리얼번호를 쓰고 있기에 해결이 불가능합니다.

등록일 순으로 정렬하시면 이런 문제가 없습니다.

**Comment by kijin** [comment]
@howtoxe 문서번호순으로 정렬하더라도 실제로 사용되는 필드는 list_order이니, 이것만 새로 발급해서 넣어 주면 해결할 수 있지 않을까요? (updateDocument에서 update_order를 갱신해 주는 과정 참고)

**Comment by howtoxe** [comment]
@kijin 좋은 아이디어같습니다 👍

**Comment by n0207** [comment]
@howtoxe 등록일로 정렬 시 
https://주소/문서번호 형태로 이동 하게되면 뷰 페이지 하단에 나오는
게시글 목록이 무조건 1페이지만 나오는 현상이 있습니다.
실제 게시물은 12페이지에 있어도 말입니다.

**Comment by howtoxe** [comment]
@n0207 등록일 순으로는 getDocumentPage에서 페이지를 안구하기 때문에 그렇습니다. 이 부분은 제가 풀리퀘를 넣겠습니다.

**Comment by n0207** [comment]
@howtoxe 아이고! 이렇게 귀한 자료를 공개 해주셔서 감사합니다!
늦었지만 복 많이 받으세요 ^_^.
