### ISSUE TITLE
모바일 관리자모드에서 레이아웃 교체 불가

### ISSUE THREAD

**Issue by kohry** [xpressengine/xe-core#2019]
모바일 관리자모드에서 레아아웃 저장버튼이 보이는데, 세부 레이아웃 고르는 곳에 한단계 더 들어가면 버튼이 사라져버림. 결과적으로 레이아웃을 모바일에서 바꾸고 저장 불가

**Comment by bnu** [comment]
'PC 설정 저장' 버튼이 첫번째 패널에만 나타나기 때문에 모바일에서는 세부 설정/레이아웃 선택 패널을 닫아야(X 아이콘) 가려졌던 'PC 설정 저장' 버튼을 볼 수 있습니다.

모바일에서는 각 패널을 하나씩만 나타내는 방식 때문인데요.
어떻게 개선해야 할 지는 고민해봐야 할 것 같네요.
