### ISSUE TITLE
XE 1.8.29에서 로그인 실패 등의 에러메시지가 나오지 않음

### ISSUE THREAD

**Issue by kijin** [xpressengine/xe-core#2020]
XE 1.8.29 업데이트 후 로그인 화면에서 비번을 잘못 입력하는 등의 에러를 발생시켜도 에러메시지가 출력되지 않습니다. 공홈에서도 같은 증상이 있습니다.

원인: #2006 보안패치에서 `XE_VALIDATOR`(대소문자 구분 안함)으로 시작하는 GET/POST/COOKIE 변수를 모두 제거해 버리기 때문에, 로그인 폼 등에서 `xe_validator_id`를 전송해도 무시해 버립니다.

해결책: 폼에서 넘어온 변수명이 `xe_validator_id`인 경우 `htmlspecialchars()` 또는 `strip_tags()` 처리 후 통과시켜야 합니다.

참고 링크: https://www.xetown.com/qna/491042

**Comment by kijin** [comment]
[이렇게 패치하면 됩니다.](https://github.com/rhymix/rhymix/commit/bef2e35f8488fc30aee4982dc1de034654562d88)

**Comment by Arepin** [comment]
정말 감사합니다. 덕분에 무사히 업데이트했습니다.
