### ISSUE TITLE
제거한 모듈에 대한 관리자 즐겨찾기를 삭제할 수 없습니다.

### ISSUE THREAD

**Issue by smaker** [xpressengine/xe-core#2024]
FTP 상에서 직접 모듈을 삭제한 경우, 모듈명이 공백이 되어서 관리자 즐겨찾기 메뉴에 삭제 버튼이 보이지 않게 됩니다.

이 경우, DB 상에서 직접 제거해야하는 불편함이 있습니다.

**Comment by bjrambo** [comment]
약간의 삭제버튼을 클릭할 수 있는 여지는 있어서 삭제는 가능하지만.. 삭제를 할 수 있긴하더라구요.

이를 예전에 http://github.com/xpressengine/xe-module-profiler 에서 기능을 추가할려고 했으나 현재는 프로젝트에 진전이 없는 상태이긴 합니다..ㅠㅠ
