### ISSUE TITLE
첨부파일 본문 삽입 후 체크 해제

### ISSUE THREAD

**Issue by andjfrrk** [xpressengine/xe-core#2028]
첨부한 파일을 선택한 후 본문 삽입을 하면, 선택했던 파일의 체크가 그대로 유지 됩니다.
습관에 따라 다르겠지만, 하나씩 삽입하는 경우 먼저 선택한 것을 일부러 체크 해제해야 합니다.
그러다보니 체크 해제하지 않고 중복 삽입하는 경우가 종종 생깁니다.
(특히, 처음 XE를 쓰는 경우)
클릭 횟수도 늘어나고요 -_-

그래서, 본문 삽입 후에는 체크 했던 것들을 자동으로 해제시키게 개선했으면 합니다.
(커버이미지로 설정한 것은 그대로 둡니다.)

적용 대상
/common/js/plugins/jquery.fileupload/js/main.js
Line 245에 추가

data.selected_files.prop('checked', false);

**Comment by mintro** [comment]
전체선택도 없어서 수십개의 이미지 일일이 다 체크하는 것도 너무 힘듭니다.
예전에 전체선택도 있었는데말이죠.

**Comment by bnu** [comment]
@mintro 첫번째 파일을 선택 후 마지막 파일을 shift 키를 누른 채 선택하면 전부 선택은 가능하지만... 어렵긴 하네요^^;
개선하겠습니다.
