### ISSUE TITLE
metaweblog API 사용 불가

### ISSUE THREAD

**Issue by zfanta** [xpressengine/xe-core#2030]
https://github.com/xpressengine/xe-core/blob/1.8.29/classes/module/ModuleHandler.class.php#L511

metaweblog API 클라이언트에서 POST를 사용하기 때문에 저 부분에서 에러가 발생합니다. #1788 과 같은 방식으로 `$this->act !== 'api' &&` 만 추가하는 방식으로 해결해도 되나요?

**Comment by bnu** [comment]
네. 우선 그렇게 추가하여 사용하셔도 됩니다.

방법을 정하여 처리하도록 하겠습니다.
