### ISSUE TITLE
사이트맵 위젯 동작 안함

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2031]
네비게이터 메뉴 출력기

https://www.xpressengine.com/index.php?mid=download&package_id=18324338

 

사이트맵 위젯

https://www.xpressengine.com/index.php?mid=download&package_id=19527787

 

사이트맵 출력 위젯

http://sejin7940.co.kr/index.php?document_srl=3972&mid=xe_data

 

 

셋다 동작을 안하네요 ㅠㅠ

혹시 왜 그런지 아시나요

1.8.14 버전에서는 위젯생성이 되었는데 최신 버전에서는 안되네요..ㅠㅠ

1.8.29 버전에서 동작 안함.

1.8.21 버전에서 동작 안함

1.8.2x 이후 버전에서 뭔가 달라진 것 같아요. 왜 그런 걸까요..

**Comment by bnu** [comment]
1.8.32 버전에서 동작 확인했습니다.
