### ISSUE TITLE
서버환경확인 누르면 에러가 발생합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2048]
Call to undefined function ibase_connect()
/home/wookho/public_html/xe/classes/db/DBFirebird.class.php : 69
62          * @brief DB Connection  
63          **/  
64         function __connect($connection) {  
65             //if(strpos($this->hostname, ':')===false && $this->port) $this->hostname .= ':'.$this->port;  
66             // attempts to connect  
67             $host = $connection["db_hostname"]."/".$connection["db_port"].":".$connection["db_database"];  
68  
69             $result = ibase_connect($host, $connection["db_userid"], $connection["db_password"]);  
70             if(ibase_errmsg()) {  
71                 $this->setError(ibase_errcode(), ibase_errmsg());  
72                 return;  
73             }

**Comment by YJSoft** [comment]
파일 `DBFirebird.class.php` `DBPostgresql.class.php` `DBSqlite3_pdo.class.php` 3개를 지우시거나 https://gist.github.com/YJSoft/dbbea73dbed61a0ba9fedc9e0f00e6a6 대로 각각 패치해주세요.
지원 중단된 DBMS의 파일이 남아 있어 발생하는 문제입니다.

**Comment by kijin** [comment]
@YJSoft 예전부터 꾸준히 XE를 업데이트해 오신 분들은 지원 중단된 DB 드라이버 파일이 남아 있을 수 있습니다. admin 모듈에서 서버 환경을 확인할 때 현재 사용중인 DB 드라이버 외에는 모두 무시하도록 해주면 간단하게 해결되겠네요.

**Comment by wookho** [comment]
@YJSoft 말씀해주신 오래된 파일 삭제하니 해당 기능 잘 동작하네요.
