### ISSUE TITLE
FileHandler::getRemoteResource()의 timeout 기본값 문의

### ISSUE THREAD

**Issue by kim135797531** [xpressengine/xe-core#2055]
* 실행 환경
  * XE: 1.8.33
  * php : 5.5.9
  * 서버 위치: 미국 서부

* 증상
  * 쉬운 설치를 이용하여 모듈 업데이트(코어 및 레이아웃 등)를 하려고 하는데, 업데이트를 눌러도 아무 변화가 없는 증상이 발생하였습니다.
* 분석
  * 업데이트 할 파일을 다운로드 받아 주는 FileHandler::_download() 메소드가 제대로 파일을 다운 받지 못 한다는 것을 알아내었습니다.
  * 다음 메소드를 실행해도 $buff가 비어 있습니다. [autoinstall.lib.php#L139](https://github.com/xpressengine/xe-core/blob/master/modules/autoinstall/autoinstall.lib.php#L139)
```php
$buff = FileHandler::getRemoteResource($this->base_url, NULL, 3, "POST", "application/x-www-
form-urlencoded", array(), array(), $postdata);
```
* 원인
  * getRemoteResource 메소드가 PEAR를 사용하여 파일을 다운로드 하는데, timeout 시간보다 시간이 오래 걸리면 timeout 예외가 발생합니다. 그러나 getRemoteResource 메소드에 예외처리가 적절히 되어 있지 않아 발생한 예외는 무시되고, NULL이 리턴됩니다. [FileHandler.class.php#L658](https://github.com/xpressengine/xe-core/blob/master/classes/file/FileHandler.class.php#L658)
* 제안
  * 외국의 평범한 서버에서, xe core 모듈(약 28MB)를 3초 안에 다운 받기는 어려워 보입니다.
  * 가장 간단한 해결책으로 제한 시간을 5초 정도로 늘리면 될 것 같은데, 제가 아직 지식이 부족해서 xe를 설계하실 때 3초로 정한 이유가 있는 지를 모르겠어서 조심스럽습니다. 일단 제 서버에서는 임시로 5초로 늘려서 업데이트가 되는 것을 확인하였습니다.

**Comment by kijin** [comment]
getRemoteResource 메소드는 쉬운설치뿐 아니라 외부 이미지 섬네일 생성, 외부 API 연동, 상용 모듈의 라이선스 체크 등 광범위하게 사용되는 기능입니다. 기본 타임아웃을 지나치게 길게 설정해 놓은 상태에서 이런 기능과 연동되는 외부 서비스에 장애가 발생하기라도 하면 로딩시간이 한참씩 지연될 수 있습니다. 따라서 기본 타임아웃은 짧은 것이 좋다고 생각됩니다. NULL을 돌려받았을 때 어떻게 처리할 것인지는 각 모듈에서 결정하면 되니까요.

해외에서 쉬운설치를 시도할 때 타임아웃이 걸리는 문제가 작년 이후 훨씬 심해졌습니다. 운영팀에서 자료실 서버를 이전하거나 뭔가 설정을 변경하면서 해외 접속 속도가 크게 떨어진 듯 합니다. 해외 트래픽 제한이 많은 국내의 평범한 IDC에서는 저녁 피크시간대 해외 접속 속도가 1~2MB/s 정도만 나와도 양반입니다. 일부 해외서버에서는 타임아웃을 현실적으로 설정 가능한 최고치인 30초까지 늘려도 여전히 XE core를 다운로드할 수 없는 경우를 보았습니다.

이것은 쉬운설치만의 문제가 아닙니다. 해외에서 운영되는 커뮤니티에 국내 사이트의 이미지를 링크하면 외부이미지 섬네일 생성 때문에 로딩 시간이 몇 초씩 지연되곤 합니다. 국내 API와 연동하는 서드파티 모듈도 마찬가지고요. 해외에서 국내 서버로 접속하는 액션이라면 모두 해당됩니다. 그나마 3초 제한 덕분에 사이트가 완전히 먹통이 되지는 않지만, 10초쯤 해놓으면 서버 터지는 곳 많을 거예요.

단지 타임아웃을 늘리기보다는 (같은 미국 서부라도 5초만에 되는 곳이 있고 15초씩 걸리는 곳도 있습니다) 쉬운설치 다운로드 요청을 비동기적으로 처리하거나, 자료실 서버의 네트워크 품질을 개선하는 방향으로 해결해야 할 것 같습니다.

**Comment by kim135797531** [comment]
@kijin 좋은 댓글 감사합니다. 역시 그렇게 단순한 문제는 아니었군요.

일단 저는 이 이슈를 닫지 않을 테니, repo 메인테이너님께서 유지 여부를 판단하시고 이슈를 닫아 주시기 바랍니다.
