### ISSUE TITLE
외부페이지 오류

### ISSUE THREAD

**Issue by dimorinpk** [xpressengine/xe-core#2060]
외부페이지 타입 메뉴에 오류가 발생합니다.
발생 스텝은 아래와 같습니다.

1.외부페이지 타입 'test'메뉴에
2.상세설정으로 들어가
3.외부페이지 경로를 지정(설명문에 있는 절대경로로 지정해줬습니다.)
세팅을 저장하고 'test'메뉴를 클릭하면,
xe를 세팅한 호스트주소 xxx.org 에서 요청을 지원하지 않습니다.
라는 문구가 나옵니다.

빠뜨린 설정이 있거나, 잘못 설정한 부분이 있다면 가르쳐 주세요. 부탁드립니다.

**Comment by dimorinpk** [comment]
이전 내용을 좀 더 보충합니다.

'페이지가 작동하지 않습니다.

현재 xxx.org에서 요청을 처리할 수 없습니다.
HTTP ERROR 500'

위와 같은 문구의 오류페이지가 뜹니다.

**Comment by bnu** [comment]
설정하신 내용을 좀 더 자세하게 알려주세요.
스크린샷이나 항목에 대한 값 등을 알려주시면 확인이 가능합니다.
공개하여 적기 곤란한 경우 값의 일부를 가리거나 bnu@xpressengine.com으로 이메일로 주셔도 좋습니다.

**Comment by dimorinpk** [comment]
외부페이지 오류 해결했습니다.
외부페이지내에
xe 문법에 맞지 않는 코드가 들어가 있어서, 오류가 났었습니다.
 
메일 주셔서 감사합니다.
 
-----Original Message-----
