### ISSUE TITLE
관리자에 의한 글 즉시 잠금(수정금지) 기능이 필요합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2061]
현재 글보호 기능은 댓글이 달리면 잠기게 되어 있지만 현실적인면을 무시한 잠금 기능입니다. 물론 이 기능을 사용은 사이트마다 유요하다 적절하지 않다 입장이 다르겠지만 많은 경우 운영에 애로사항이 잇습니다.

글 수정이 금지되어야 하는 보존 되어야 하는 시점을 댓글 기준으로 하다보면 글 작성자 본인도 문의를 댓글로 하게 되고 또 그 댓글에 관리자도 댓글을 달아주어야 합니다. 이경우 애로사항이 발생하죠. 글 작성에 관해 문의하는 순간 잠겨버리니까요.

조건을 글 작성자의 경우는 예외 처리 한다해도 글 작성자가 문의한 댓글에 관리자가 쪽지로 응대해야 하는 이상한 상황이 벌어지는 것이죠. 관련 증거를 연결해서 남길 수가 없습니다.

![management](https://cloud.githubusercontent.com/assets/6590236/24230097/9293204c-0fc0-11e7-9dd9-63cf4a5e82ff.jpg)

관리자 판단에 글이 보호되어야 하는 시점이 되었다는 것이 되는 순간 관리자가 직접 잠금을 할 수 있는 글보호기 능이 필수적으로 필요하다고 봅니다.

**Comment by YJSoft** [comment]
현재 글 보호 기능 자체는 글 보호 기능 사용여부와 댓글수를 비교해서 보호 기능이 사용중이면서 동시에 댓글이 한개 이상인 경우 글 수정을 막는 것으로 구현되어 있습니다. 확장성을 위해서는 다음 방향으로 수정되어야 할것입니다.

- 공개/비공개 이외 별도로 글 잠김 상태를 추가
- 글 보호기능을 사용하는 경우 해당 글에 댓글을 다는 액션 수행시 해당 글을 잠금
- 댓글이 달리지 않더라도 관리자는 글을 수동으로 잠글수 있도록 함
- 댓글이 달려 글이 잠긴 상태에서도 관리자는 수동으로 글 잠금을 해제할 수 있도록 함

**Comment by wookho** [comment]
@YJSoft 댓글이 달릴 경우 잠기는 시스템이 굉장히 어려운 상황을 만들고 있습니다. 이 경우도 옵션으로 해야 할 것 같습니다. 

중요한 신청을 받는 양식의 경우 작성 후 관리자에게 묻는 질문을 자신의 글에 댓글로 의견을 내는 경우가 많고 이에 관리자는 여기에 댓글을 달아주는 경우가 있습니다. 따라서 댓글잠금 기능때문에 오히려 문서의 완성을 지체 시키거나 하는 등의 문제가 있습니다.

댓글 달리면 즉시 잠김이 필요한 경우

댓글과 상관없이 관리자가 접수요건이 충족되면 즉시 잠금을 할 수 있는 경우(댓글 달려도 계속 수정 가능..) 

케이스가 다를겁니다. 저의 경우는 후자인데 지금까지 공개된 글보호 관련 자료로는 구현이 어려웠습니다.

**Comment by YJSoft** [comment]
@wookho 글 잠금 기능을 댓글과 분리하면 지금처럼 댓글이 달려야 잠기는 것이 아닌, 댓글과 무관하게 관리자가 수동으로 잠금 및 잠금 해제하는 것도 가능할 것입니다. 구현 자체는 크게 힘들것 같지 않으니 저녁때쯤 살펴보겠습니다.

**Comment by wookho** [comment]
@YJSoft 검토 감사합니다. 코어에서 이런건 꼭 수용해줬으면 합니다. 중요 기능을 매번 수정해서 사용하는 것도 XE개발팀에서는 사용자를 위해 생각해 줘야 한다고 생각합니다. 물론 지금 많이 그런 방향에서 멀어진 개발팀 이긴 하지만요.

**Comment by YJSoft** [comment]
@wookho 살펴 보고는 있습니다만 하위 호환성 문제 때문에 구현이 쉽지는 않네요.

**Comment by bnu** [comment]
기능의 구현이 쉽지는 않을 것 같습니다.

별도의 모듈로 구현하는 게 오히려 편할수도 있을 것 같고요.
서드파티 기능으로 만드시는 분이 있다면 트리거 추가 등의 지원이 가능할 것 같습니다.
진행하시는 분이 있다면 필요한 내용은 이슈로 남겨주세요.

이슈는 좀 더 열어뒀다가 닫겠습니다.
