### ISSUE TITLE
메뉴에 태그사용 부분적 허용해주실수 없나요??

### ISSUE THREAD

**Issue by samswnlee** [xpressengine/xe-core#2063]
https://github.com/rhymix/rhymix/pull/688

참고하셔서 보안에 문제가 없다면
허용해주시면 안될까요?

UI에서 아이콘은 중요한 요소인데
이게 막혀버리니 조금 답답합니다...

**Comment by Lastorder-DC** [comment]
중복 #2015

**Comment by bnu** [comment]
#2015 이슈에서 다루겠습니다.
