### ISSUE TITLE
<link> 태그를 head 영역으로 끌어올리는 기능이 잘못 동작하는 문제

### ISSUE THREAD

**Issue by wonsuc** [xpressengine/xe-core#2064]
일단 문제의 원인은 `<link>` 태그를 사용시 클로징 태그에서 슬래시("/")를 추가하지 않으면 발생하는 버그인 것 같습니다.

link 태그에서 /를 추가하지 않을시 XE에서 HTML 내용을 Replace 하는 과정에서 `<body>` 등의 잘못된 태그가 강제로 삽입되어 버립니다.

잘못된 태그가 삽입되는 지점은 다음의 예들입니다.
- form 사용시 error_return_url 등의 누락된 태그를 강제로 삽입할 때
`<input type="hidden" name="error_return_url" value="/" />`
- point level icon 이미지 태그를 강제로 삽입할 때
`<img src="/modules/point/icons/default/27.gif" alt="[레벨:27]" title="포인트:127475point (9%), 레벨:27/30" class="xe_point_level_icon" style="vertical-align:middle;margin-right:3px;" />`

아래 이미지는 IE11에서 잘못된 `<body>` 태그 삽입에 대한 콘솔 오류 메시지입니다.
<img width="598" alt="2017-04-02 5 13 20" src="https://cloud.githubusercontent.com/assets/9866158/24585721/4b35422a-17cc-11e7-8d4c-bd13172323cd.png">

오류 라인을 클릭해보면 아래처럼 point level icon 바로 아래 지점이라는 것을 알 수 있습니다.
<img width="671" alt="2017-04-02 5 14 36" src="https://cloud.githubusercontent.com/assets/9866158/24585723/51535110-17cc-11e7-8cc9-ad017fbfaa6f.png">

결국 이 문제는 `<link>` 태그 사용시 클로징 태그에서 슬래시("/")를 추가하면 해결됩니다.

하지만 근본적으로 HTML에서 void 요소의 경우 클로징 태그에 슬래시를 추가하지 않는 것이 표준에 가깝기 때문에 제고되어야 할 부분이라고 생각합니다.

그리고 XE에서 강제로 태그를 삽입하는 코드들을 보면 대부분 void 요소의 클로징 태그에 슬래시를 추가합니다. XHTML의 경우 void 요소에도 end tag가 삽입되는 것이 규약이지만 HTML에서는 void 요소의 경우 end tag를 가질 수 없다고 명시되어있기 때문에 이 부분이 좀 수정되었으면 합니다.

예를들면, 아래 코드에 보면 클로징 태그에 슬래시가 추가되네요.
https://github.com/xpressengine/xe-core/blob/master/addons/point_level_icon/point_level_icon.lib.php#L72

**참고링크들**
- `<link>` 태그에 슬래시가 없는 것을 권고
[https://www.w3.org/TR/html5/document-metadata.html#the-link-element](https://www.w3.org/TR/html5/document-metadata.html#the-link-element)
- void 요소는 end tag를 가질 수 없다(슬래시가 삽입되더라도 아무런 효과를 가지지 않는다)
[http://w3c.github.io/html/syntax.html#tags](http://w3c.github.io/html/syntax.html#tags)

**Comment by bnu** [comment]
우선 스크린샷 첨부하신 것의 문제는
XE에서 `<link />` 태그를 찾아 `<head>`영역으로 끌어 올려주는 기능이 있습니다.
원인을 찾으신 것과 같은 차이로 `<head>`영역에 `<link>`태그 이후부터 '/>'가  나타나는 사이의 태그가 끌어 올려진 것으로 보입니다.
이 부분은 문제를 고칠 수 있을 것 같습니다.

XHTML에 우선하여 유지되어왔고 HTML5에서 XHTML의 하위 호환 또는 말씀하신 것처럼 다르게 처리하지 않으니 당장에는 변경의 필요성이 크지는 않아 보입니다.

우선 위의 문제를 해결하고 self-closing에 대해서는 추가 검토 후 처리 여부를 결정하도록 하겠습니다.

**Comment by wonsuc** [comment]
피드백 감사합니다!
한가지 학구적인 궁금증 때문에 여쭤보는 것이지만 XE 1.8이 XHTML에 우선하고 있는 이유를 알 수 있을까요? XHTML을 벗어나고 HTML5를 우선으로 하였을 때 발생되는 크리티컬한 사항들이 많은걸까요? 저도 배우는 입장이라 간단하게라도 지식을 나눠주시면 감사하겠습니다.

**Comment by kijin** [comment]
@wonsuc XE가 XHTML 문법을 사용하는 이유는 XE가 처음 만들어질 무렵 XHTML이 최신 웹표준이었기 때문입니다. 그 이상도 이하도 아니예요. DOCTYPE만 얼마 전 HTML5로 바뀌었습니다. HTML5에서 `/>`를 사용한다고 오류가 나는 것도 아니니 그냥 두는 거지요.
