### ISSUE TITLE
저만그런지는 모르지만 멀티미디어 태그 작성이 안됨

### ISSUE THREAD

**Issue by mkjang2000** [xpressengine/xe-core#2065]
이전버전에는 없던문제입니다만은 멀티미디어 태그작성이 불안정합니다.
기존에 작성된 멀티미디어 태그는 잘 읽히지만 작성이되지 않습니다.

ex) 기존 멀티미디어 태그
`<img width="400" height="400" style="background:url(&quot;https://dongeunchurch.kr/modules/editor/components/multimedia_link/tpl/multimedia_link_component.gif&quot;) no-repeat center;border:2px dotted rgb(67,113,185);width:400px;height:400px;" src="../../../../common/img/blank.gif" auto_start="false" wmode="transparent" multimedia_src="http://dehdd.kr:25000/rec/dawn_worship/2017/4/170402.mp3" editor_component="multimedia_link" alt="blank.gif" />
`

   현재버전 멀티미디어 태그
`<img auto_start="false" editor_component="multimedia_link" height="400" multimedia_src="http://dehdd.kr/rec/dawn_worship/2017/4/170402" src="../../../../common/img/blank.gif" style="display:block;width:400px;height:400px;border:2px dotted #4371B9;background:url(https://dongeunchurch.kr/modules/editor/components/multimedia_link/tpl/multimedia_link_component.gif) no-repeat center" width="400" wmode="transparent" /></p>`

**Comment by bnu** [comment]
두 코드의 경우 style 속성이 조금 다른 것 외에는 동작에 영향을 줄만한 것은 없어 보입니다.
증상을 좀 더 자세히 설명해주실 수 있을까요?

**Comment by mkjang2000** [comment]
오류가 있는 코드의 사이트 : https://dongeunchurch.kr/admin_test/289426
정상코드 사이트 : https://dongeunchurch.kr/record/288850

오류가 있는 코드는 표시가 되지 않습니다.
소스코드만 따로 복사한다음 HTML 파일로 저장해서 단독 테스트했을때도 나오지 않습니다.

**Comment by wonsuc** [comment]
@mkjang2000 multimedia_link 코드를 살펴보진 않았지만 님이 올리신 사이트 링크로만 봤을 때 정상코드 사이트에서는 mp3 확장자가 존재하는 미디어를 불러오고 오류코드 사이트에서 불러오는 미디어는 아무런 확장자가 없네요. 아마도 확장자 이슈인 것 같습니다.
