### ISSUE TITLE
모바일에서 에디터 사용하게 해주세요.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2066]
https://github.com/xpressengine/xe-core/pull/1495/files

사용자들 그만 골탕먹게 좀 반영좀 해주시기 바립니다.

https://www.xetown.com/square/554450

**Comment by bnu** [comment]
게시판 설정에 모바일 에디터 사용 옵션을 추가하고 내장된 기본 모바일 스킨에 위지윅 에디터를 사용할 수 있도록 적용했습니다. 기본 값은 기존과 같은 textarea입니다.
