### ISSUE TITLE
board 모듈의 manage_checked_document.xml 필터가 잘못된 act를 참조

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#2068]
존재하지 않는 `procBoardAdminManageCheckedDocument` act를 참조하고 있습니다. 해당 파일은 코어에서 사용되고 있지 않으며, 존재하지 않는 act를 참조하고 있기에 동작도 하지 않습니다.

**Comment by bnu** [comment]
모듈 정리 시 잘못 딸려온 것으로 보입니다.
삭제 예정입니다.
