### ISSUE TITLE
1.8.36 버전의 .htaccess 파일 문제

### ISSUE THREAD

**Issue by gigglehd** [xpressengine/xe-core#2076]
1.8.36 버전으로 업데이트 후 500 에러가 뜹니다. 

이게 저만 그런게 아니라 같은 증상을 호소하신 분이 있네요.
https://www.xetown.com/qna/563211
https://www.xpressengine.com/qna/23223270

.htaccess 파일 외에 다른 건 업데이트해도 아무 문제가 없습니다. 

일단은 호스팅 업체에 로그를 요청하겠으나, 확인할 필요가 있어 보입니다.

1.8.36 버전에 적용된 .htaccess 파일 변경점
https://github.com/xpressengine/xe-core/commit/be3578deeaacbb5f3fae5da96d2f4b3ddb1e3a6f

**Comment by kijin** [comment]
#2077
