### ISSUE TITLE
관리자모드에서 일부 설정 수정시 HTTP ERROR 500 발생

### ISSUE THREAD

**Issue by SUCO2** [xpressengine/xe-core#2079]
Core XE 1.8.37로 버전업을 하고 난 뒤, 
관리자 모드에서 모듈 등,일부 내용 설정 수정시 HTTP ERROR 500 발생으로 수정이 안됩니다.
앞서 Core 업데이트 하기 전,  모듈 설정 수정을 하고 있다가,
Core  XE 1.8.37 업데이트 내용을 확인하고 바로 업데이트를 하고 나니, 이런 결과가 나타났습니다. 

백업을 미리 했어야 하는데, 설마라는 생각에 이런 오류가 날거라고는 생각지도 못했네요.

**Comment by bnu** [comment]
@SUCO2 '일부 내용 설정' 등에 관한 좀 더 상세한 내용이 있다면 알려주세요.
