### ISSUE TITLE
board.getBoardCommentPage 요청에서 게시판[모듈->권한]에 접근 권한은 있으나 게시글 열람권한은 없을때 게시글이 비밀글이 아니라면 댓글 훔쳐보기 가능한 취약점

### ISSUE THREAD

**Issue by huhani** [xpressengine/xe-core#2083]
비밀글이 아니고 모듈 권한 설정에서 오직 접근 권한만 있으면 다른 목록, 열람 권한이 어떻게 셋팅되어있던 간에 모든 댓글 훔쳐보기 가능.

exec_json('board.getBoardCommentPage', {document_srl: 해당 게시글}, ret_obj => {
    console.log(ret_obj);
});

**Comment by bjrambo** [comment]
getBoardCommentPage 에서 실제로 댓글 내용이 나온것이 맞나요?
테스트 해보았습니다만.. 해당 오브젝트에 html내용엔 비밀글이라는 내용을 출력하고 잇엇어요.

**Comment by bjrambo** [comment]
해당 내용 확인해서 보안취약점 해결방법을 @bnu님에게 전달 해드렸습니다. 
앞으로 보안 취약점의 경우 xe개발자 이메일을 통해서 알려주세요 ㅠㅠ..

**Comment by bnu** [comment]
#2084 PR에서 해결 됨
