### ISSUE TITLE
첨부파일 주소. 절대주소라서 도메인변경시 첨부파일 깨짐 문제.

### ISSUE THREAD

**Issue by mintro** [xpressengine/xe-core#2090]
웹호스팅사를 변경하면서 그동안 두개의 도메인을 이용하다가
이제는 기존의 도메인을 아예 접속 안되게 하고 신규도메인으로만 접속을 되게 했는데
특정기간 이후의 이미지들이 깨져서 나옵니다.

글 본문에서 소스보기를 통하여 본 결과 특정시점 이전의 글은 상대주소로 이미지가 되어있는데
특정시점 이후부터는 상대주소가 아닌 절대주소로 되어있어서
도메인 변경 이전의 모든 글들의 첨부이미지는 다 깨지는 결과가 되어버립니다.
도메인 두개를 중복으로 연결해놓은 것들은 대표주소가 변경후 주소라서 
절대주소도 변경후 주소로 처리가 되어있어서 깨지진 않는데....

기존의 도메인 하나만 이용할때의 첨부이미지들은 모두 깨집니다.
수백개의 글이 그러한 상황이라서 매우 난감한 상황인데....

노가다로 본문에 있는 이미지를 삭제하고 첨부파일에 있는 이미지를 다시 본문에 삽입하면 되지만
이렇게 하여도 현재의 주소를 절대값으로 처리가 되니까 혹시라도 추후에 도메인 변경시 또 문제가 발생됩니다.

그래서 XE측에서 절대주소가 아닌 상대주소로..
도메인을 변경해도 전혀 상관이 없도록 업데이트시에 개선을 해줘야 한다고 보여집니다.

다음번 업데이트시에 본문삽입시 절대주소가 아닌 상대주소로 처리되도록 해주시기 바랍니다.

**Comment by bnu** [comment]
예전에는 상대경로 였습니다.
어떠한 의도에 의해 절대경로로 변경이 되었는데요.
꽤 오래 된 부분이라 변경 의도를 파악해보겠습니다.
