### ISSUE TITLE
바로가기 메뉴 권한 수정하면 본메뉴 권한 전체공개

### ISSUE THREAD

**Issue by sunmikr** [xpressengine/xe-core#2093]
메뉴 타입 : 바로가기인 메뉴의 **메뉴 노출 대상**을 수정하면
그 메뉴의 링크에 해당하는 본 게시판의 **접근 권한,목록,열람,글 작성 등 권한**이
모두 **모든 사용자**로 허용됩니다.

이를 모르고 바로가기 메뉴 노출 대상을 수정하게 되면
의도치 않은 게시글 노출이 생길 수 있습니다.

**Comment by bnu** [comment]
문제 확인했습니다.
와우.
빠르게 문제 해결할 수 있도록 하겠습니다.
