### ISSUE TITLE
xxx.xxx.xxx.xx:8080일때, 주소 오류문제

### ISSUE THREAD

**Issue by masque79** [xpressengine/xe-core#2096]
1. 주소는 "xxx.xxx.xxx.xxx:8080"이다
2. 글쓰기를 한다.
3. 내용을 넣는다
4. 등록을 누른다
5. xxx.xxx.xxx.xxx로 링크된다.

**Comment by Lastorder-DC** [comment]
#1956 이슈와 중복됩니다.
