### ISSUE TITLE
회원 가입폼 설정에서 사용자정의 항목 폼이 잘못 표시되는 문제

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2098]
https://www.xetown.com/lakepark/612950
https://www.xpressengine.com/devlog/23228219

**Comment by Lastorder-DC** [comment]
6ac2c9727de771b23de7987871c2711d5c5ea3aa 에서 `&lt;` 등을 `>`로 이스케이프시키는 부분이 삭제되어 생기는 문제입니다.

**Comment by Lastorder-DC** [comment]
6ac2c9727de771b23de7987871c2711d5c5ea3aa 에서 `&lt;` 등을 `<`로 이스케이프시키는 부분이 삭제되어 생기는 문제입니다.
