### ISSUE TITLE
에디터 및 파일첨부 질문입니다.

### ISSUE THREAD

**Issue by choi-inkyung** [xpressengine/xe-core#2100]
cafe24에서 그누보드xe 설치버전으로 호스팅을 구매하였습니다.

지금 문제가

파일업로드 할때 100%까지 채워지지만 파일이 출력되지 않는 문제,

에디터는  ckeditor, xpresseditor

두개다 있지만 ckeditor를 선택하면 에디터가 아예 생기지 않고 스크립트 에러가 납니다.

스크립트 오류로 인해 ckeditor 스킨이 입혀지지 않는문제

스크립트 에러내용 : Uncaught TypeError: $(...).XeCkEditor is not a function

그리고 xpresseditor 얘를 선택해도 

마찬가지로 스크립트 에러가 나고 HTML 편집기를 아무리 클릭해도 활성화가 안되는 문제가 있습니다.

답변 부탁드립니다.

**Comment by kijin** [comment]
- 이곳은 [질문/답변 게시판](https://www.xpressengine.com/qna)이 아닙니다.
- 설치하자마자 문제가 있다면 호스팅 업체에서 설치를 잘못한 것입니다. 현재 XE 최신버전 기준으로 CKEditor에서 스크립트 오류는 발생하지 않습니다. XE 최신버전을 [자료실](https://www.xpressengine.com/index.php?mid=download&package_id=18325662&release_id=22755850)에서 직접 다운받아 현재 설치된 경로에 그대로 덮어씌운 후, 관리 화면에서 "캐시파일 재생성"을 클릭해 보세요.
- 설치 후 레이아웃이나 스킨 등을 변경한 상태에서 에러가 난다면 해당 레이아웃이나 스킨에 문제가 있는 것이니 해당 레이아웃이나 스킨을 개발한 사람에게 문의해 주시기 바랍니다.

**Comment by bnu** [comment]
최신 버전 기준으로 문제가 보이지 않으며, 저희는 그누보드xe를 배포하지 않습니다.
