### ISSUE TITLE
xe.css 등의 언로드가 가능하도록

### ISSUE THREAD

**Issue by howtoxe** [xpressengine/xe-core#2101]
바로 PR을 넣으려다가 구글 검색을 조금 해봤더니 일부러 언로드되는 걸 막아두셨다고 하더라고요. 

제가 생각하기에도 일부러 막은 이유가 있을 것 같고해서 말씀을 들어보고자 이슈로 남깁니다.

**Comment by kijin** [comment]
언로드가 가능해야 하는 이유를 좀더 자세히 설명해 주시면 도움이 될 것 같습니다.

기본으로 로드되는 CSS, JS 파일들을 특정 서드파티 자료에서 임의로 언로드해버리면 다른 자료들이 오작동할 수 있습니다. 님이 만드는 모듈이나 레이아웃 하나만 천상천하 유아독존하는 게 아니니까요.

이러한 공통 리소스를 임의로 언로드하는 모듈이나 레이아웃이 생겨나면 그걸 체크해서 또다시 로드하려는 모듈이 만들어질 수밖에 없고 (예전에 만들어진 상당수 모바일 스킨들이 jQuery를 중복으로 로딩하는 것과 비슷한 현상이죠) 그러면 결국 서드파티 자료들끼리 심각한 충돌을 일으키게 되어 여러 자료를 조합하여 사이트를 구성한다는 XE의 기본 원칙마저 흔들릴 수 있다고 생각합니다.

**Comment by howtoxe** [comment]
btn같이 많이 쓰이는 클래스명을 미리 지정해놓는다거나 폰트가 지정돼있다거나 하는게 불편해서요. 검색하면서 보니까 역시 많은 분들이 언로드하는 방법을 찾거나 요구하기도 하셨더라고요. 

오죽하면 jQuery remove 메소드로 로드 즉시 지워버리는 꼼수도 돌아다니던데 그럴바에야 역시 코어에서 지원하는게 낫지 않을까 생각했습니다.

하지만 호환성 부분을 고려했을때 님의 말도 일리가 있네요. 이 부분은 개인적으로 해결하겠습니다. @kijin 님, 답변 고맙습니다.

**Comment by kijin** [comment]
특정 클래스에 속성이 미리 지정되어 있는 것이 문제가 된다면 아마 다른 속성을 지정하고 싶으시기 때문이겠지요? 그렇다면 나중에 로딩하는 CSS 파일에서 해당 클래스에 다른 속성을 지정하면 그만입니다.

또한 클래스명은 레이아웃이나 스킨 소스에서 쓰기 나름이니, 개발하신 스킨에 `.btn`이 적용되는 것이 싫으면 아예 다른 클래스명을 쓰시는 방법도 있습니다.

물론 xe.css에서 `!important`로 선언해 버리는 바람에 덮어쓸 때도 마찬가지로 `!important`를 선언해야 하는 귀찮은 속성도 몇 가지 있는데요... 이건 코어에서 첫 단추를 잘못 꿴 거라고 생각합니다만, 이제 와서 변경하면 기존 레이아웃이나 스킨을 사용하던 사이트에서 갑자기 스타일이 바뀌어 버릴 수도 있어서 곤란합니다. `.btn`처럼 이미 굳어져 버린 클래스명도 마찬가지고요.

이래저래 호환성 때문에 바꾸기가 쉽지 않은 것이 XE죠 ㅎㅎ

**Comment by bnu** [comment]
화면이 출력되기 거의 직전에 추가되기 때문에 unload가 무시되는 셈인데요.
오래전에 관련 부분의 코드가 리팩토링 되면서 바뀌었습니다.
해당 부분을 unload가 가능한 시점으로 옮겨볼게요.

하지만 kijin님이 말씀하신 것처럼 빼기에는 다른 곳에서 문제가 발생할 수 있지만 의도에 의한 것이므로, 변경이 가능하다면 방법을 찾아보겠습니다.

**Comment by howtoxe** [comment]
@bnu 피드백 감사합니다. 사실 저도 기진 님 말씀처럼 하나의 서드파티 자료가 공통 리소스를 없애버리도록 허용하는게 바람직한 건지는 모르겠네요. 그게 XE 팀의 초기 생각이기도 할겁니다. 

특히 스킨이나 레이아웃같은 곳에서 편의에 따라 추가해버리면 나중에 어디서 언로드되었는지 디버깅하는 것도 쉽진 않을테구요. 

하지만 그걸 감안해도 xe.css 자체의 결함이 XE의 확장성을 제약할 정도로 너무 크다고 생각을 하고 있습니다. 

우선 xe.css에 들어가있는 팝업 레이어나 메시지 레이어의 스타일 속성을 각각 멤버 모듈이나 메시지 모듈로 이전하는 것부터 선행되어야 할 것 같습니다. 코어가 아닌 모듈에 집어넣을 수 있는 다른 속성들이 있다면 다 이전하는게 호환성 문제를 최소화하는 방안이라고 생각합니다. 

그리고 가칭 unloadCommonResource() 같은 메소드를 따로 Context 클래스에 둬서 기존 언로드 메소드로는 공통 리소스를 제거하지 못하도록 하는 방안도 필요할 것 같습니다.

**Comment by bnu** [comment]
서드파티 자료에서 unload하는 것을 방지(?) 하려면 config.user.inc.php 등에 별도의 옵션을 켜고 끌 수 있는 방안 등이 있을 것 같은데, 여전히 불편하기는 하네요. 음..

`unloadCommonResource()`같은 걸 두더라도 서드파티에서 사용하면 마찬가지 일 것 같고요.

xe.css에 있는 스타일은 어느 것 하나 옮기기 어려워 보이긴 하네요^^:

**Comment by howtoxe** [comment]
@bnu 마찬가지이긴 하지만 무분별한 사용은 막을 수가 있을 것 같아서요. 나중에 에디터로 찾거나 할때에도 일반 언로드와 구분되니 용이할 수 있을 것 같고요.

방지 대책은 별 뾰족한 수가 없을 것 같긴 합니다. xe.css를 언로드한다는 자체가 별도로 스타일을 입히기 위함이니 웬만한 상황에서는 문제가 발생하지 않긴 할텐데... 

이런 부분들을 고려해서 한번 PR을 넣어보려고 하는데 리뷰 부탁드려도 될까요?

**Comment by bnu** [comment]
@howtoxe 좋습니다

unload 하려면 `HTMLDisplayHandler::_loadJSCSS()`를 호출하는 시점을 상당히 앞당겨야 합니다.
현재 구현상 unload한 파일이 이후에 다시 load하면 추가될 수 있기 때문에 호출 시점을 앞 당겨야 unload할 수 있습니다.

제가 생각하는 타협점은 위에 말씀 드린 것에 좀 더 다듬어 아래와 같이 생각하고 있습니다.
- _loadJSCSS() 호출 시점을 두 곳에 두고
  - 1) 가능한 앞당긴 시점
  - 2) 현재와 동일한 곳 (`HTMLDisplayHandler::prepareToPrint()`)
- config.user.inc.php에 옵션을 두고 활성화하면 `2)`를 실행하지 않도록 함
- 그렇지 않으면 `2)`에서 한 번 더 `_loadJSCSS()`를 호출하여 혹시나 unload 했을 지 모르니 다시 덮기

**Comment by wonsuc** [comment]
prefix 없이 btn, message 같은 클래스 네이밍은 xe.css가 강제적으로 로드된다는 점을 고려하면 bad practice 라고 생각됩니다.
xe-btn, xe-message 이런 식이였다면 좀 더 나았을거 같네요. 그리고 xe.css 내의 태그 규칙 reset 이나 지정된 폰트도 매번 재지정해야되서 번거로웠던 경우가 많았습니다. 물론 기진님 말씀대로 첫 단추를 좀 잘못 꿴 측면이 있기에 unload 하는 방법이라도 간편하게 적용될 수 있다면 상당히 유용할거 같네요.
개인적인 아이디어는 XE의 각 페이지 상세설정에서 아래와 같은 옵션이 있으면 어떨까 생각해봅니다.
- [X] **XE의 기본 스타일(css) 사용하기**

**Comment by kijin** [comment]
@wonsuc 기본 스타일의 적용 범위는 단지 공통으로 적용되는 폰트나 버튼 모양뿐 아니라 서버에 요청중이라는 레이어, `alert()` 함수 사용시 나타나는 레이어, 문서와 회원 등의 컨텍스트 메뉴 등도 포함됩니다. 레이아웃이나 스킨에서 기본 스타일이 마음에 들지 않는다고 몽땅 unload해버리면 다른 모듈이나 애드온이 의존하는 기능의 디자인도 깨질 수 있어요.

만약 unload를 허용한다면 폰트나 버튼 모양과 관련된 스타일만 따로 분리하거나, `.btn()`을 `.xe_default_styles .btn`으로 바꾸고 `<body>`에 `xe_default_styles` 클래스 적용 여부를 선택할 수 있도록 하는 등 좀더 우회적인 방법이 필요하다고 생각됩니다.

**Comment by wonsuc** [comment]
@kijin 저처럼 디자이너로부터 사이트 전체의 디자인을 넘겨받아서 퍼블리싱하는 퍼블리셔에게는 써드파티 모듈이나 애드온을 사용하지 않고 사이트를 구축하기 때문에 제가 제시한 아이디어가 아니더라도 unload 하는 방법은 어떤 식으로든 제공이 되었으면 좋겠습니다. 스타일을 재정의하는 방법은 불필요한 파일을 로드하고 코드수도 늘어나기 때문에 비효율적인 것 같습니다. body에 클래스명을 붙히는 방식도 마크업상으로 깔끔해보이지 않고 hacky한 측면이 있네요.

**Comment by kijin** [comment]
@wonsuc 하위 호환성을 유지하려다 보면 당연히 hacky하게 되지요...ㅜㅜ

**Comment by bnu** [comment]
@wonsuc `.btn`은 TWBS를 관리자 모드에 적용하면서 TWBS의 버튼 스타일을 덮기 위한 의도였을 것으로 추측합니다. 의도나 결과가 어찌됐든 되돌릴 수는 없고, 적당한 방법이 제시되면 반영하도록 하겠습니다.

위에 말씀해주신 내용들을 종합해보면 가장 간단한 방법이 @wonsuc 님이 말씀해주신...
관리페이지에 설정 추가(고급 설정 부분이 적당하겠죠)하고 xe.css, mobile.css(xe.css에 있는 일부를 분리하고 싶지만 그냥 두고 통째로 빼는 게 낫겠다는 생각입니다)를 로드하지 않도록 하는 방법인 것 같습니다. 관리페이지에 체크박스가 하나 더 생긴다는 게 사실 내키지는 않습니다만, 다른 사용자분들이 혼란만 겪지 않는다면 가장 편리한 방법일 것 같긴합니다.

좀 더 이야기해보고 다음 정기 배포에서 위와 같은 방향으로 진행하는 것으로 예정하겠습니다.

@kijin 혹시 xetown에서 관련 의견이 있으면 알려주시면 감사하겠습니다 :)

**Comment by howtoxe** [comment]
요즘 제작 작업 가끔 하기도 바빠서 손을 못대고 있네요... 

관리자 페이지에서 온오프하는 것 보다는 개발자가 자료에서 직접 로드/언로드를 결정하는게 나을 것 같다는게 제 생각입니다. 

가령 레이아웃이 있고 여기에서 xe.css 언로드를 해서 커스텀 디자인을 넣으려고 하는데 사용자보고 레이아웃 설치한 다음에 설정에서 체크박스 해제해라... 이렇게 안내해야하는게 맞을까요? 

개발자가 처리해야하는 것을 가뜩이나 XE 관리자페이지 설정하기 힘들다는 사용자가 해야하는 것인지 전 잘 모르겠습니다. 나중에 그 레이아웃 지울때 대신 체크 풀어줄 수도 없는 것이구요.

**Comment by howtoxe** [comment]
저도 @wonsuc 님 말씀중에 클래스 명 고치자는 것에는 찬성이고 한발 더 나가서 아예 로딩레이어, 기본 버튼 뺀 나머지 스타일시트는 관련 모듈로 보내버리면 좋겠다는 생각이긴 합니다. 

그런데 지금와서 고민해보니까 xe.css, xe.js를 로드/언로드할 수만 있다면 레이아웃, 모듈 개발자는 별도의 코어 수정없이도 꽤 여러가지를 손 댈 수 있게 될 겁니다. 그냥 언로드하고 원하는 css를 로드하면 되는데 굳이 호환성 문제를 더 감수하면서 기존 클래스명까지 손댈 이유가 없는 것 같다는 거죠...

그런 관점에서 보면 클래스명을 바꾸거나 스타일들을 재분류하는 것은 지엽적인 문제라고 보이긴 합니다.

**Comment by bnu** [comment]
@howtoxe 원하시는 방향과는 다른 것 같지만, 저는 이 상황을 '사이트의 직접적인 개발/운영을 담당하는 사람'으로 대상을 한정하고 보고 있습니다. 배포 또는 판매되는 서드파티 레이아웃, 스킨 등에서 unload하는 것은 맞지 않은 것 같습니다.

서드파티 자료에서 unload를 허용한다면 대혼란이 있을 것 같습니다. 스타일이 빠지는 건 차치하고 각자의 스타일로 새로 정의한다면 `.btn` 버튼이 세모 모양으로 변할지도 모르니까요.

레이아웃, 스킨 등 디자인을 직접해서 사이트를 제작하여 운영하거나, 납품하는 경우로 한정해야 한다고 봅니다.

**Comment by howtoxe** [comment]
@bnu 

언로드를 하고 새로운 리소스를 로드한다는 것은 기존 스타일과 js 등에 완전히 대응한다는 것으로 저는 이해합니다. 모듈, 레이아웃 제작자치고 자기가 필요한 스타일시트만 골라서 추가해서 로드한 다음 호환성문제를 일으킨다는 것은 상상하기 힘들지 않나 생각합니다. 

물론 개발 가이드라인을 지키지 않아 bad practice가 나올 수는 있습니다만 그것은 그 자료의 문제라고 생각합니다.

설정에서 사용자가 설정창에서 로드 여부를 결정하도록 했을시 오히려 더 큰 문제를 야기할 수 있다고 봅니다. 가령 특정 모듈만이 언로드를 필요로함에도 일괄적으로 언로드를 하게 되면서 xe.css에 의존하는 다른 페이지들에서 문제가 발생하게 됩니다.

개발 방향이야 메인테이너 님이 결정하시는 것이지만 이 부분들도 고려해주셨으면 합니다.

**Comment by howtoxe** [comment]
@bnu 여러 서드파티 자료들이 언로드 로드를 반복하게 되면 그건 확실히 심각한 문제가 될 수 있습니다. 그런데 문제는 설정에서 로드/언로드를 결정하도록 한다고 해서 서드파티 자료들이 로드하는 커스텀 스타일들이 충돌하는 문제가 해결되지는 않습니다...

**Comment by xeyeyak** [comment]
@bnu
unload가 가능했으면 좋겠습니다.
커스터 마이징에 어렴움을 겪었습니다.
unload 문제로 서드파티 자료들로 인해 큰 혼란이 올 거라 생각하지 않습니다. 오히려 서드파티 모듈등의 디자인에 있어서 자유로움이 오지 않을까요.

**Comment by bnu** [comment]
@howtoxe 네. 어찌됐든 CSS는 덮을 수 있으니 마찬가지이긴 합니다. 하지만 `<unload>`로 xe.css를 제거할 수 있게되면 새로운 헬 게이트를 열어버리는 느낌입니다. 그래서 해당 옵션의 선택권을 서드파티 제작자는 제한하는 것으로 생각하는 것이고요.

**Comment by kijin** [comment]
@bnu 서드파티 개발자는 함부로 호출할 수 없고 위에 글을 쓰신 분들처럼 특별히 제작하여 납품하시는 분들에게만 주로 필요한 것이라면... 사실 xe.css를 마음대로 수정해 버릴 수도 있는 상황인데 코어 업데이트시 덮어씌워질 수 있으므로 꺼리시는 것으로 보입니다. 그렇다면 아예 관리자 화면에는 노출되지도 않지만 업데이트시 덮어씌워지지 않는 db.config.php 옵션으로 구현하는 것도 괜찮겠네요.

**Comment by bnu** [comment]
`<unload>`를 통해 허용하는 방법으로 생각했으나 서드파티에서 unload 시 원인을 알 수 없는 문제를 만들어 낼 수 있다는 의견에서 조금은 불편하고, 제한적인 방법으로 이야기하고 있는데요.

여러 의견 중 업데이트 때 마다 다시 코드를 고치지 않는 선에서 '가장 불편한' 방법으로 적용해야 할 것 같습니다.

'config/config.user.inc.php' 파일에 `__DEBUG__` 등 처럼 상수로 지정하여 서드파티에서 함부로 설정을 변경하지 못하도록 하겠습니다.

**Comment by howtoxe** [comment]
@bnu 지금보다는 나을 것 같네요. 신경써주셔서 정말 감사합니다.

**Comment by bnu** [comment]
단순하게 적용했습니다.

`__DISABLE_DEFAULT_CSS__` 값을 1/true로 설정하여 CSS 적용을 해제할 수 있습니다.
config/config.user.inc.php 파일에 `define('__DISABLE_DEFAULT_CSS__', 1);` 이와 같이 적용할 수 있겠죠.
