### ISSUE TITLE
1.8.40 위젯페이지 내용직접입력 애드센스 코드 잘림

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2108]
애드센스를 내용직접입력으로 에디터에서 작성하면 스크립트코드중 일부가 필터링되어 잘려나가 애드센스 출력이 되지 않습니다.

이전에 작성된 것 수정을 하거나 혹은 신규로 작성하거나 모두 동일합니다. 
이전에 만들어 놓은 위젯페이지에 애드센스를 함께 하나의 문서로 작성해 놓은 경우 문서 수정시 애드센스가 사라집니다.

현재 방법은 db에서 해당 문서번호 찾아서 애드센스 부분을 수정하거나 입력해야 하는 상황입니다.

**Comment by bnu** [comment]
(애드센스를 사용하지 않아서요)
문제가 발생한 코드를 주시면 확인해보겠습니다.
(공개되어서는 안 되는 코드는 임의로 대체해주세요.)

**Comment by wookho** [comment]
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-****************"
     data-ad-slot="**************"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


아래와 같이 잘립니다.


<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by wookho** [comment]
@bnu 여기 에디터에도 잘려서 적기가 어렵네요. 

원래 코드 입니다.

<--script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="******************"
     data-ad-slot="******************"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script-->

**Comment by kijin** [comment]
ins 태그가 잘려나가는 건가요?

원형 그대로 보존되어야 하는 코드는 앞뒤에 ```를 붙여주시면 도움이 됩니다.

\```
source code
source code
\```

이렇게 쓰시면

```
source code
source code
```

이렇게 나옵니다.

**Comment by wookho** [comment]
@kijin 네. 위에 보시면 코드 전체를 넣었는데 ins 태그가 잘려나간게 여기 댓글에서도 보일거에요.

**Comment by wookho** [comment]
@kijin 코드 전체는 윗 댓글의 이미지를 보시구요.
여기에 전체를 복사해서 넣어볼게요. 그럼 여기 댓글에서도 잘려나갑니다.

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-****************"
     data-ad-slot="**************"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by wookho** [comment]
`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-****************"
     data-ad-slot="**************"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`


위가 원코드



아래가 잘린 후 코드요.

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-****************"
     data-ad-slot="**************"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by bnu** [comment]
@wookho 문제 확인했습니다. CKEditor에서 `<ins>` 태그를 제거하는 것으로 확인했습니다.

**Comment by bnu** [comment]
다음 버전이 배포되기 전까지.. 아래와 같이 임시로 `<ins>` 태그에 주석을 넣어 CKEditor가 태그를 제거하지 않도록 할 수 있습니다.
```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 468 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-****************"
     data-ad-slot="**************"><!-- --></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

`... ***"><!-- --></ins>` 이처럼 `<ins>`태그에 주석 코드를 넣으시면 됩니다.

**Comment by kijin** [comment]
에디터 로딩 과정에서 아래와 같은 설정을 추가하면 `<ins>` 태그가 삭제되지 않는 것을 확인했습니다.

```
CKEDITOR.dtd.$removeEmpty['ins'] = 0;
```

modules/editor/skins/ckeditor/editor.html 에서 적당한 위치에 추가하시면 될 것 같습니다.
