### ISSUE TITLE
파일 업로드 개선

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2109]
CKEditor에 사용된 파일 업로드 UI 개선
- 첨부한 파일 목록에서 선택이 어려움
  - 범위 선택 기능이 있으나 아무도 모르는 듯
  - 전체 선택 기능 필요(이미지)
- 썸네일 지정 기능이 있는지도 모르겠음
- 추가 업로드 파일의 본문 삽입 시 이미 선택된 항목이 해제되지 않아 번거로움
- xpressEditor의 플래시 업로더 대체 (xpressEditor는 추후 배포판에서 제거 예정)

**Comment by bnu** [comment]
개선이 필요한 항목이 있으면 댓글로 남겨주세요.

**Comment by wookho** [comment]
이미지의 경우 본문에 자동 삽입 (커서의 위치에)

수정이나 글 작성시 첨부에서 제거 시 본문에서 제거(해당태그 제거..)
- 자동본문 삽입이 채용될 경우 필요한 기능 , 자동으로 삽입된 후 잘못 올린거 같아 첨부에서 삭제만 한경우 글 작성 완료시 엑박이 뜨는데 사이트 이용자들은 본문까지 수고스럽게 지워야 하는 것을 대부분 모릅니다.

위 본문 자동삽입/삭제 기능은 라이믹스에서 제공하고 있습니다.

**Comment by kijin** [comment]
- 현재 대표이미지로 지정(우측 상단 체크)하면 썸네일이 되는 것으로 알고 있습니다.
- 본문삽입 단추는 XpressEditor의 잔재(?)라고 생각됩니다. 별도의 단추를 클릭하지 않아도 업로드 직후 자동으로 삽입되거나, 더블클릭으로 삽입할 수 있게 되면 훨씬 편리하겠습니다.
- @wookho 님이 제안하신 자동 본문삽입 기능이 들어가면 이미 선택한 항목을 따로 해제해야 하는 불편도 많이 덜어질 것으로 보입니다.

**Comment by wookho** [comment]
@kijin 본문삽입 수동으로 넣는 버튼과 기능은 유지가 필요해 보입니다. 자동삽입 스크립트가 안먹는 브라우저나 단말기들이 간혹 있더라구요. 이 경우 애드온등으로 본문에 넣을 수는 있지만 원한는 위치에 넣으려는 요구도 있으니 자동으로 안들어가는 경우를 대비해 유지가 필요해 보입니다.

**Comment by wookho** [comment]
더블클릭,버튼클릭 뭐 방법의 차이겠군요.

**Comment by bnu** [comment]
네. 본문 삽입 버튼은 유지할 생각입니다.
자동 삽입 외에도 편집 중 일부 몇 개의 이미지를 선택 후 일괄로 넣는 경우도 있어서 유지할 생각입니다.

개별 본문 삽입은 XE3처럼 하나씩 넣기 편하게 변경 할 예정입니다.
<img width="453" alt="2017-06-14 3 01 21" src="https://user-images.githubusercontent.com/53764/27117654-6f94fe92-5112-11e7-97fc-87123262284f.png">

**Comment by wookho** [comment]
@bnu 좀 늦은 댓글이긴 한데 혹시 가능하다면 검토 부탁드립니다.
클라우드플레어의 경우 업로드 100M 제한이 되어 있습니다. 그렇다보니 조금 큰 용량의 업로드가 되지 않는 상황인데요. 업로드 과정에서 100M이하로 업로드 해서 다시 합쳐주는 기능이 필요합니다.
라이믹스에 적용된 기술인데 가능할지요....

**Comment by wookho** [comment]
https://github.com/rhymix/rhymix/pull/663

**Comment by bnu** [comment]
@wookho 파일 업로드 라이브러리에서 지원하는 기능이긴 합니다.
CKEditor 초기에 적용하려던 것이었는데 무한으로 밀리던 것이긴 한데요.
이번에 에디터를 정리하면서 적용을 고려하고 있지만 10월 이전까지는 어려울 것 같습니다.
이 이슈 자체의 일정이 10월 이후로 밀리고 있습니다. ㅠ

**Comment by wookho** [comment]
@bnu 일단 이번 에디터 정리할때 고려 대상이었다니 반가운 소식입니다. 함께 곡 처리되길 바랄게요.

**Comment by bnu** [comment]
새로 추가한 `xe.selectable`은 jQuery Widget으로 구성되며,
첨부한 파일의 본문 삽입, 삭제 등의 동작 시 finderSelect를 대체하여 다중 선택 기능을 제공 함.

**Comment by bnu** [comment]
- [ ] 목록에서 선택 시 버튼 등 간소화
- [ ] progressbar

**Comment by bnu** [comment]
- [ ] 디자인 정리. 버튼, 기타 파일의 목록

**Comment by bnu** [comment]
릴리즈 취소. 이슈 종료.
