### ISSUE TITLE
인증메일 24시간 제한 때문에 인증 불가

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2112]
인증메일의 유효기간이 24시간으로 굉장히 짧은 것은 처음 알았습니다. 인증에 실패하는 사람이 많아 원이이 궁금해 알아보다가 24시간 제한이 있다는 사실을 알았고 테스트로 제가 24시간을 넘긴 후 인증을 시도해 보았지만 저도 실패했습니다.

24시간이 지난 후 메일에 인증용 링크를 클릭하면 아래와 같이 메시지가 나타납니다.
![auth](https://user-images.githubusercontent.com/6590236/27475395-05b7803c-5840-11e7-8c02-702718fc28b1.png)

뭘 하라는 것인지 명확하지 않지만.... 

아이디/패스워드 찾기를 시도하라는 것으로 읽혀 집니다.
흔히들 위의 액션을 하기 전에 아마도 인증메일 재발송을 눌러 볼겁니다.
 - 잘못된 요청으로 나옵니다.

이제 다시 이이디/패스워드 찾기를 진행해 봅니다. 이메일을 입력하고 아이디/패스워드 찾기 버튼을 누르면 해당 메일로 바뀐 패스워드와 인증용 링크가 새로 도착합니다.

해당 링크를 눌러서 인증을 성공한 후 

변경된 패스워드를 가지고 로그인을 해 보면...
![stop](https://user-images.githubusercontent.com/6590236/27475524-7ba7a1e6-5840-11e7-999b-e12547434514.png)

해당 계정이 중지중이라고 뜹니다.

관리자인 제가 테스트로 인증을 성공하지 못하는데 일반인도 마찬가지 일 듯합니다.
제가 잘못 한게 있나요??

- 인증메일 유효기간이 너무도 짧습니다. 스팸함등에 숨어있거나 하여 못찾고 잠시 바빠 시간을 놓친 경우 24시간을 넘길 수 있는데 24시간 넘긴 후 인증 자체가 불가능한 듯 합니다.

- 최초 인증메일 도착 시 인증유효기간 안내가 없습니다. 이것은 분명히 필요할 듯 합니다. 시간이 지난 경우라면 어떻게 하라는 안내도 함께 있어야 할 것 같습니다.

- 인증유효기간이 지났다고 패스워드 변경과정을 거쳐야 하는 것도 이상합니다.

- 24시간 후 인증은 어떻게 하는건가요?

**Comment by wookho** [comment]
@kijin 인증유효기간을 두어야 한다고 제한하셨던 것 같은데 도움이 필요합니다. 어떻게 해야 24시간 지난 후 인증 시도하는 분들이 인증에 성공할 수 있나요?

굉장히 많은분들이 인증에 성공하지 못하고 있는 듯 합니다.

**Comment by wookho** [comment]
반복해서 테스트 해봐도 24시간 이후 스스로 로그인 할 수 있는 방법이 없네요.
일단 메일인증 사용을 중단해야 겠습니다.

**Comment by kijin** [comment]
@wookho 24시간 안에 인증을 마치지 못한 경우, 재발송을 클릭하면 인증 메일이 다시 발송되고 그 시점으로부터 다시 24시간이 주어지는 것이 정상입니다. 24시간이 지나지 않았더라도 재발송을 클릭하면 다시 발송이 될 겁니다. (단, 이 경우 처음에 발송되었던 링크는 무효가 될 수 있습니다.)

만약 이것이 제대로 작동하지 않는다면 (1) 버그이거나 (2) 메일 주소를 잘못 입력했거나, 둘 중 하나입니다. 회원가입 과정, 로그인시 나오는 에러 메시지, 인증메일 내용이 부실한 것도 사실입니다. 이런 부분은 확실히 개선이 필요하고, 버그가 있다면 고쳐야겠지요.

그러나 위의 기능이 정상적으로 작동한다고 가정할 때 24시간은 그다지 짧은 시간이 아닙니다. 흔히 휴대폰으로 전송되는 인증코드는 3~5분만에 만료됩니다. 메일은 SMS처럼 당장 확인하지 못할 수도 있기 때문에 위험을 감수하고 시간을 하루종일 더 준 것입니다.

예전에는 몇 년이 지난 인증 메일의 링크로도 계정 리셋이 가능한 문제가 있었습니다. 인증 메일에 포함된 링크는 사실상 비번과 같은 효과를 가지는 매우 민감한 정보임에도 불구하고 전혀 암호화되지 않은 상태로 전송되기 때문에, 유효기간이 길수록 보안 사고가 발생할 가능성이 높아집니다.

아무리 스팸함으로 들어가거나 바쁘다고 해도, 당장 가입하고 싶은 사이트를 이용하는 데 반드시 필요한 인증메일을 다음 날까지도 확인하지 못한다는 것은 흔치 않은 일입니다. 대부분의 사이트에 가입하는 대부분의 사람(로봇이 아님)은 몇 분 안에 인증을 마치는 것으로 알고 있습니다.

**Comment by wookho** [comment]
@kijin 제가 수차례 반복을 한 결과이라 메일주소를 잘못 넣거나 하지 않았습니다.

최초 인증메일이 온것을 확인 한 후 처음에는 24시간을 기다려 테스트 했구요.

이후에는 db에서 등록시간을 고쳐서 테스트 했습니다.

인증메일 재발송을 누르면 잘못된 요청으로 응답합니다.


그리고 24시간 지난 인증링크를 누르면 "인증메일 재발송을 하라는 메시지" 도 아니고 위에 첨부한 패스워드 찾기를 하라고 나옵니다.

패스워드찾기를 해야 잘못된 요청이 아닌 인증메일이 발송이 됩니다. 그런데 이 인증용 메일은 패스워드를 바꿔서 보냅니다.

그래서 이 메일로 인증을 하면 인증에 성공했다고 응답합니다.

하지만 로그인 하면 중지된 계정이라고 뜹니다.

저희는 메일인증 포기했습니다.

**Comment by wookho** [comment]
@kijin 그리고 비율로 따지면 10% 이내 이겠지만 그래도 많은 분들이 여러가지 시간정 상황이나 개인적 상황으로 가입 후 즉시 인증을 못하고 하루 지나서 시도하십니다. 제가 모니터링 해 본 바로는요..
인증 실패가 하루가 지나면 거의 100% 인 상황이라 제가 테스트를 해 보니 위 결과가 나왔습니다.

**Comment by wookho** [comment]
@kijin 24시간 지난 링크를 클릭하면 위와 같은 이상한 메시지를 출력하고 인증관련 db를 삭제해 버리는데 이때 인증메일 재발송을 요청하면 기존에 인증용링크정보 db가 없기 때문에 모순으로 잘못된 요청이 뜨는거 아닐까요?

설명대로라면 24시간 연장이 될 인증 자체가 사라진 이후인데요? 
그리고 24시간 지난 링크를 클릭했을때 메시 자체도 왜 메일인증 재발송을 시도하라는 메시지가 아닌지도 의문입니다.

**Comment by kijin** [comment]
@wookho 네, 저도 24시간이 지나면 가입할 수 없어야 돼!!! 라는 주장을 하는 건 아니고요, 1차적으로 24시간을 주고 그 후에는 재발송을 하도록 변경한 이유를 말씀드린 것 뿐입니다.

그런데 최초 가입시 발급된 인증코드를 사용하지 못했을 경우 진행상황이 아주 이상하게 되는군요. 사실상 무한대였던 인증메일의 유효기간을 축소하면서 생긴 부작용을 뒤늦게 발견한 것인지도 모르겠습니다.

**Comment by wookho** [comment]
@kijin 네. 24시간 자체의 문제라기 보다는 시간이 지난후 클릭했을 경우 인증정보를 없애버리는게 문제라고 봅니다. 메시지도 이상하구요.

다만 유효기간이 각자 근무환경이나 생활패턴에 따라 불가능한 시간일 수 있다고 봅니다. 가입할때 인증가지 못마쳣는데 마침 바빠서 다음 잠을 낼 수 있는 시간이 그 다음 말이나 이후인 분들이요.

제가 모니터링해본 결과 타이밍이 맞지 않아 인증을 못했다가 재시도 시 실패하는 분들이 제법 많습니다.

**Comment by wookho** [comment]
@kijin 메일에 오랜만에 로그인하려니 패스워드가 기억나지 않아 잠시 포기하고 하루가 더 걸려 시도 하는 경우도 재법 있을거구요.

**Comment by bnu** [comment]
만료된 경우 새로운 인증키를 새로 발급하고 자동으로 인증 메일을 발송하도록 했습니다.
![2018-06-18 5 31 13](https://user-images.githubusercontent.com/53764/41525894-7394913c-731d-11e8-9de5-39e793bebf5d.png)
