### ISSUE TITLE
이미지 파일 업로드시 본문 자동삽입 기능추가로 파일 삭제시 본문 이미지태그 삭제가 필요합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2113]
자동으로 본문에 들어간 사진 중 잘 못 올린 것이 있을 경우 다수의 이용자들이 파일삭제를 하면 본문에 것은 자동으로 지워지는 줄 알고 글 등록을 합니다.

이때 브라우저 캐시 때문에 엑박이 보이지 않아 본문 수정을 하지 않는 경우가 많아 첨부에서 삭제할때 해당 이미지 태그를 같이 삭제해 주는 기능이 필요합니다. 

라이믹스에서 이미 적용되어 있는 기능입니다.

**Comment by wookho** [comment]
프로그램은 잘 몰라 라이믹스에서 찾아서 적용했는데..

file_srls = file_srls.join(',');

			exec_json('file.procFileDelete', {'file_srls': file_srls, 'editor_sequence': data.editorSequence}, function() {
				file_srls = file_srls.split(',');
				$.each(file_srls, function(idx, srl){
					data.settings.fileList.find('ul').find('li[data-file-srl=' + srl + ']').remove();
				});
				var ckeditor = _getCkeInstance(data.editorSequence);
				var regexp = new RegExp('<(img) [^>]*data-file-srl="(' + file_srls.join('|') + ')"[^>]*>', 'g');
				ckeditor.setData(ckeditor.getData().replace(regexp, ''));
				self.loadFilelist($container);
			});
		 },
		/**
		 * 파일 목록 갱신
		 */


이부분을 제대로 적용했는지 모르겠습니다.

일단 지금 확인해 보니 본문의 이미지태그도 지워져 이미지가 잘 사라집니다. 문제가 없다면 반영해 주시면 좋을 것 같습니다.

**Comment by bnu** [comment]
네. 파일 업로더 부분을 정리하면서 추가 할 예정입니다.

**Comment by bnu** [comment]
#2109 이슈에서 처리 함

**Comment by bnu** [comment]
릴리즈 취소. 이슈 종료.
