### ISSUE TITLE
회원아이디 건의

### ISSUE THREAD

**Issue by dududay09** [xpressengine/xe-core#2115]
현재 회원가입 시 아이디를 영문시작만 가능합니다.
관련 제약이 제외되거나 옵션으로 선택설정하거나 모듈로 빼거나 하면 좋을 것 같습니다.

게시판이나 글에 제약이 있는건 이해가 가지만,
회원아이디에 이런 제약이 있는 이유가 어떤용도인지 이해하기 힘드네요.

마이그레이션 하다가 의문이 들어 남겨봅니다.

**Comment by bnu** [comment]
오래된 관습이 남아있습니다.
하지만 이 룰을 변경하기는 조심스럽네요.
