### ISSUE TITLE
return new Object(-1, '') 으로 리턴되었을때 value값이 고정되는 문제.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#2116]
예시 템플릿 코드입니다. 

```html
<block loop="$icon=>$key,$val>
<form action="./" method="post">
<input type="hidden" name="icon_srl" value="{$val->icon_srl}" />
<input type="submit" 어쩌구저쩌구 />
</form>
</block>
```

이와같은 코드에서 만약 리턴이 있는경우가 있습니다.

그런데 리턴되었을때 value="{$val->icon_srl}" 에 들어가는 값이 모든 반복 form 에서 오류났던 icon_srl 값이 입력되어있는 문제가 발생됩니다.

어설프게 모든 입력값을 해당 값을 넣지 않고 서로 다른 값이 필요한 구간에서는 구분할 수 있었으면 좋을 것 같습니다.

**Comment by kijin** [comment]
어느 `<input>`에 어떤 값을 넣어줘야 하는지 구분하기에 충분한 정보가 제공되었는지도 생각을 해봐야 할 것 같아요. 한 페이지에 `<form>`이 여러 개 있고 각각 다른 `XE_VALIDATOR_ID` 값으로 구분이 되지 않으면 코어에서 어느 게 어느 건지 알 길이 없습니다.

**Comment by bnu** [comment]
input를 구분하기 모호하므로 앞서 처리하신 것처럼 폼 또는 input name을 명확히 하는 것으로 해결하는 것이 맞다고 봅니다.
