### ISSUE TITLE
CK에디터 업데이트 된 후 모바일에서 롱 터치시 CK에디터의 붙여넣기 나오지 않게 하는 방법?

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2118]
기존에는 config.js 파일에..

CKEDITOR.editorConfig = function( config ) {
                config.removePlugins = 'liststyle,tabletools,contextmenu'; 
};

이런식으로 넣어 놓아서 문제없이 롱터치로 붙여넣기가 가능했습니다. 
최근 에디터 업데이트 이후 롱터치시 CK에디터의 붙여넣기 contextmenu ? 인가가 나와서 붙여넣기를 할 수 가 업습니다.

업데이트된 버전에서 추가조치해야 하거나 혹은 방법이 아예 다른건지 알려주시면 감사하겠습니다.

-- 추가 --
추가로 CK에디터에서 제공하는 모든 붙여넣기(워드붙여넣기 ? 등..) 는 브라우저에서 사용이 금지 되었다고 사용이 되지도 않습니다.

**Comment by wookho** [comment]
http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-enableContextMenu

위 내용을 참고해서

CKEDITOR.editorConfig = function( config ) {
	config.enableContextMenu = false;
};


위 내용을 적용하니 contextmenu 의 팝업이 뜨지 않게 되었습니다.

하지만 여전히 브라우저에서 작동하는 붙여넣기,복사하기 등이 뜨지 않아 키보드를 직접 조작하는 환경이 아닌 상황에서는 붙여넣기가 가능하지 않은 상황은 동일합니다.

**Comment by wookho** [comment]
https://youtu.be/6b8DyUBnMWw

관련 영상입니다.

**Comment by wookho** [comment]
답을 찾지 못해 그냥 CKEDITOR를 contextmenu를 빼고 빌드해서 js 파일들만 교체하고 마무리 지었습니다.
XE에서 배포하는 CK에디터를 그대로 사용하는 분들께는 뭔가 도움이 필요할 수 도 있는 문제 같습니다.

**Comment by bnu** [comment]
@wookho 
뭔가 불편해보여서 관련 부분을 살펴보니 기존 동작은 크게 바뀌지 않은 것으로 보입니다.
다만, 메뉴나 툴바를 통한 붙여 넣기 시 별도의 dialog를 표시하고 그곳에 붙여 넣을 수 있도록 할 수 있던 것이 단축키를 안내하는 메시지로 변경된 것으로 보입니다.
![2017-07-21 3 12 34](https://user-images.githubusercontent.com/53764/28451237-13176646-6e27-11e7-849f-a5585c282e45.png)

iOS에서는 롱터치로 메뉴를 불러와 붙여넣기 등의 동작이 가능했습니다.

터치 다비이스에서 붙여 넣기 동작이 불가능하다면.. 윈도우 태블릿 인가요?

**Comment by wookho** [comment]
@bnu 
붙여넣기가 불가능한건 모든 디바이스에서 입니다.
다만 PC의 경우 Ctrl +V 로 할 수 있어 이것으로 가능하다는 것이구요.

실제 해보셨나요?  이 단축키를 제외한 나머지로는 불가능하실텐데요?

**Comment by wookho** [comment]
@bnu 
PC에서는 오른쪽 마우스를 누르면 CK에디터의 붙여넣기 작은 아이콘이 나옵니다. 그걸 누르면 CK에디터에 붙여넣을 수 있는 창이 열리죠. 하지만 업데이트된 이후로는 브라우저에서 사용할 수 없다는 파란 메시지가 떠서 사용 불가요.
브라우저 자체의 오른쪽 마우스 붙여넣기 메뉴가 안나온다는 것입니다.

모바일에서는 동일하게 브라우저에서 사용할 수 없다고 나와 에디터의 붙여넣기는 사용하지 못하구요. 물론 이걸 사용하는 사람도 없겠지만요.
PC와 동일하게 브라우저 자체의 붙여넣기 메뉴가 노출되지 않아 붙여넣기가 불가능하다는 것 입니다.


현재 시점 XE CK에디터에서 유일하게 붙여넣기가 가능한 상황은 PC에서 Ctrl+V 를 눌러서 하는 한가지 방법 뿐 입니다.

**Comment by bnu** [comment]
@wookho 
네. 단축키를 통해서 붙여 넣기가 가능했습니다.
앞서 말씀드렸다시피, CK에디터에서 OS의 context menu를 자체 메뉴로 변경을 하는데요.
기존에도 이러한 동작이 있었습니다. 차이점이 dialog가 사라졌다는 것이었고요.

키보드로 붙여넣기 동작이 불가능한 기기(터치 기반의 모바일 기기)에서 테스트한 것은 iOS이며,
정상적으로 붙여넣기가 가능했다는 답변이었습니다.

![img_1528](https://user-images.githubusercontent.com/53764/28455788-3a878fe4-6e3b-11e7-9eb1-10854a2f8602.jpg)

PC 외에 터치 기반의 기기에서 롱터치로 붙여넣기가 불가능한...
@wookho 님이 문제를 겪은 환경을 알려주세요. 기기가 없어 정확한 테스트는 불가능 하겠지만 관련 정보를 찾는데 도움이 될 것 같습니다.

**Comment by wookho** [comment]
@bnu IOS는 제가 없어 확인하지 못했지만..
안드로이드 , PC의 모든 브라우저에서 가능하지 않았습니다.
안드로이드에서 해보시고 그리고 PC에서 마우스만으로 붙여넣기를 성공하실 수 있는지 확인 부탁드립니다.
마우스로 하는 동작이 결국 모바일에서는 롱터치이니까요..

에디터의 메뉴에 붙여넣기는 브라우저에서 금지해서 안된다고 뜹니다.

**Comment by bnu** [comment]
<img width="515" alt="2017-07-21 6 38 07" src="https://user-images.githubusercontent.com/53764/28458260-1ba7f600-6e44-11e7-826d-b43a48079bdf.png">

<img width="514" alt="2017-07-21 6 40 10" src="https://user-images.githubusercontent.com/53764/28458264-20b7cdb4-6e44-11e7-91b2-eb4a93cc439b.png">

가상머신에서 확인한 부분이긴 하지만..
파이어폭스와 (가상 머신 상의) 기본 브라우저로 테스트 해봤습니다.
시스템 붙여 넣기 메뉴가 나오고 붙여 넣기가 가능한 것으로 확인했습니다.

PC에서는 단축키를 이용 가능한 부분이고, 이 기능을 제거 시 표 편집 기능도 함께 제거되기 때문에 가능한 유지하고 싶습니다만, 불편을 초래하니 context menu를 제거하도록 하겠습니다.

**Comment by wookho** [comment]
@bnu 실제 기기에서 해보세요. 제발 부탁입니다.

**Comment by bnu** [comment]
@wookho 실제 기기가 없습니다.
저라고 테스트 따위 귀찮아서 안 하고 있는게 아닙니다....

답변에 두서가 없어서 오해를 살 수 있는 부분은 인정합니다만, 이슈 대충 닫을라고 이러고 있는 게 아닙니다.

**Comment by wookho** [comment]
가상머신이 무엇을 말하는지 모르겠습니다. 실제 안드로이드폰 여러개로 여러 사이트를 다 테스트 해봤구요.

PC에서 컨트롤 V 를 사용해야만 하는 것도 이상한 일이구요.

어찌 되었던 해결점을 찾는 부분에 가까워져 가는것 같아 다행이긴 합니다.

CK업데이트 이전에는 PC에서도 오른쪽 마우스로 브라우저의 네이티브 복사하기,붙여넣기 메뉴가 호출이 잘 되었습니다. 이제는 그거 쓰려면 키 하나를 눌러야 호출이 되는데 이건 일반인이 알수 없는 수수께끼 같은 이야기죠.

**Comment by dorami** [comment]
@bnu pastefromword 폴더는 더이상 필요없지 않나요?
