### ISSUE TITLE
위젯페이지에서 위젯박스의 위치 이동이 안 되는 문제

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2122]
위젯 페이지에서 상자위젯을 만들고 안에 위젯을 넣어놓으면 서로 위치 변경이 안됩니다.
번호를 부여하도록 해서라도 그 위치를 변경할 수 있었으면 합니다.

**Comment by eondcom** [comment]
![image](https://user-images.githubusercontent.com/3683813/29579658-67fc31fa-87ae-11e7-857d-069c7bd823f3.png)
위젯페이지를 이용하여 컨텐츠를 꾸밀 경우 다양한 상자위젯을 추가하고 그 안에 다시 위젯들을 집어넣어서 
편집을 하는데 보시다시피 메인의 경우 상자박스나 위젯갯수가 많아지고
그에 따른 위치 편집이 있을 경우 
상당히 사용성이 떨어집니다.

**Comment by azena** [comment]
최신 코어(1.9.3)에서 상자 위젯이 이동하지 않습니다.
예전에는 이동을 했는데, 지금은 아예 이동이 안 되네요.
빈 위젯 페이지를 만들고 100x100 크기의 상자 위젯을 1,2,3,4 이렇게 4개 만든 후 간단하게 컨텐츠를 넣은 후에 순서 바꾸기를 시도해보면 전혀 움직이지 않는다는 것을 알 수 있습니다.
언제부터 안 되는지 모르겠으나 기능 건의가 아니라 버그로 봐야 맞을 듯 싶네요.

**Comment by Lastorder-DC** [comment]
@azena 새로 이슈를 열어주세요.

**Comment by bnu** [comment]
@azena 다른 스크립트의 오류로 인한 영향일 수 있습니다.
확인이 가능하다면 브라우저 콘솔에서 오류가 발생하고 있는지 확인해보세요.

**Comment by azena** [comment]
@bnu xStr(), xGetElementById(), xInnerHtml() 관련한 deprecated만 발생할 뿐 에러는 없습니다.

**Comment by bnu** [comment]
@azena 상자위젯 간에 위치(순서) 변경이 안 되는 문제를 수정했습니다.
상세한 설명 감사합니다.

@eondcom 말씀하신 문제가 해결이 될지 모르겠네요.
