### ISSUE TITLE
업데이트 안됨 문제...

### ISSUE THREAD

**Issue by spc999** [xpressengine/xe-core#2123]
![_00000_22](https://user-images.githubusercontent.com/30456091/28604090-52f49eac-7203-11e7-9b11-aa5a691d1f46.png)
현재 XE core version: 1.8.22 
인데 
위 3종이 계속 업데이트가 되지 않습니다...
어느 부분을 확인 해야 하나요?
 패치 같은건 없나요.... 복잡하지않고 간단한...

**Comment by Lastorder-DC** [comment]
이곳은 XE의 버그를 신고하는 공간이지 질문을 위한 공간이 아닙니다. 질문은 [공홈 묻고답하기 게시판](https://www.xpressengine.com/qna)에 올려주세요.

1. 쉬운설치가 안된다면 FTP로 받아 수동 업로드해보세요(코어는 특히 수동 업데이트를 권장합니다)
1. 일부 자료실 개편 전 업로드된 자료는 자료 설명의 버전만 업데이트되고 실제 파일의 버전은 업데이트되어 있지 않은 경우가 종종 있는데요, 이경우 해당 자료의 conf 파일을 수정해 버전을 업데이트해 줘야 할수 있습니다.
