### ISSUE TITLE
익명일 때 관리자가 회원의 글을 수정하면 닉네임이 넘어가는 현상

### ISSUE THREAD

**Issue by itoito0710** [xpressengine/xe-core#2124]
회원 글을 수정하면 닉네임이 관리자로 넘어갑니다.
예전에도 발생했던 문제 같은데 패치하고 괜찮았다가
이번 버전에서 다시 발생하는 것 같아요.

**Comment by bnu** [comment]
문제를 확인할 수 없습니다.

추가 설치한 모듈, 애드온에서 발생하는 문제일 수 있습니다.
