### ISSUE TITLE
editor : 유튜브 동영상 주소 입력시 외부이미지로 섬네일 자동생성

### ISSUE THREAD

**Issue by haendel8** [xpressengine/xe-core#2130]
아이디어 건의입니다.

Youtube나 Vimoe 주소를 입력하고 oembed로 플레이되는 기능을 유용하게 쓰고있는데 다들 아쉬워하는게 목록에서 썸네일을 표시하기 위해서는 캡쳐 이미지를 수동으로 등록해주거나 해야한다는 것입니다.

별도의 애드온이나 트윅하는 방법들이 있는거 같긴한데 간단한 아이디어가 생각나서요.
외부이미지도 섬네일 생성이 된다는 점을 이용할 수 있겠다 싶어 올려봅니다.

글 입력시 본문에 동영상 주소가 있으면 본문내에 **숨겨진 이미지 태그**를 자동으로 넣어주는겁니다.

`<!--<img src="https://img.youtube.com/vi/nVCubhQ454c/sddefault.jpg" id="thum_nVCubhQ454c" />-->`

`<!--<img src="http://i.vimeocdn.com/video/50115370_640.jpg" id="thum_50115370" />-->`

이런식으로
URL 바로 뒤에 혹은
문서 맨 뒤에
숨겨진 주석처리된 이미지태그를 하나 넣어주면 섬네일이 자동으로 생성될 수 있을꺼 같아서요.

늘 감사합니다.

**Comment by bnu** [comment]
oEmbed는 게시물 작성 시가 아닌 게시물을 보여줄 때 사용자의 브라우저에서 동작하는 기능입니다.
물론 기능이야 만들 수 있지만 코어에서 처리하기는 어려운 부분이 있네요.

말씀하신 것과 유사한 방식의 [애드온](https://www.xpressengine.com/index.php?mid=download&package_id=22753343)이 있는데 유지보수가 중단된 것 같네요.

**Comment by haendel8** [comment]
아 비슷한 애드온이 있었군요. embed된 동영상만 처리되는 상태인거 같긴 하지만... 안내 감사합니다.
역시 이런건 애드온으로 처리하는게 맞을꺼 같긴 합니다.^^
