### ISSUE TITLE
사이트 메뉴 편집 / 사이트 디자인 설정 열 경우 내용 안보임

### ISSUE THREAD

**Issue by winstar0070** [xpressengine/xe-core#2132]
![default](https://user-images.githubusercontent.com/24579935/29488223-91152dc2-8541-11e7-823d-5fc2676e3b22.PNG)
이런식으로 나옵니다 ㅜㅜ 해결 방법이 최대한 찾아봤는데
안보여 이슈에 남겨둡니다.

**Comment by bnu** [comment]
스크립트 오류일 수 있습니다.
가능하다면 브라우저에서 콘솔에서 오류 메시지를 확인하고 알려주세요.

**Comment by winstar0070** [comment]
콘솔에선 오류 메세지는 없어보이네요.

**Comment by bnu** [comment]
메뉴명 입력 시 보이지 않는 문자열이 들어가는 경우에 발생하는 문제로 확인하고 해당 문제를 고쳐두었습니다.
기타 다른 오류메시지가 없다고 하시니, 아마 위와 같은 문제인 것 같네요.

**Comment by tychetic** [comment]
안녕하세요. 혹시 해결하셨나요..? 저도 에러가 안뜨는데 위와 같은 화면이 나옵니다..
