### ISSUE TITLE
비로그인 사용자가 게시판에 댓글 작성시에 홈페이지 입력칸의 줄 맞춤이 이상합니다.

### ISSUE THREAD

**Issue by knight2995** [xpressengine/xe-core#2133]
이유로는 
/modules/board/skins/default or xedition 내의 **comment_form.html**의 
`<input type="text" name="homepage" id="homePage" class="iText homePage" value="{htmlspecialchars($oComment->get('homepage'))}" />&nbsp;`

에서 마지막 부분의 &nbsp; 때문입니다. 혹시 의도하신 건가요 ?

**Comment by bnu** [comment]
특정한 의도는 없으므로 제거하도록 하겠습니다.
