### ISSUE TITLE
페이지 수정시에 업데이트 반영이 안되고 있습니다

### ISSUE THREAD

**Issue by fy5914** [xpressengine/xe-core#2135]
몇개 사이트에서 공통적인 문제로 확인된 사항으로,

XE 업데이트 이후의 문제로 보이고요.

페이지 수정시에 업데이트 반영이 안되고 있습니다. (크롬 및 파이어폭스에서 확인)

확인 부탁드리겠습니다.

**Comment by bnu** [comment]
페이지의 종류(문서, 위젯, 외부), 사용 중인 버전과 업데이트 이전의 버전을 알려주세요.

**Comment by fy5914** [comment]
문서페이지이며, 1.8.43 으로 업데이트한 상태입니다.

이전 사용하던 버전은 1.8.42 입니다.

참고적으로 카페24호스팅이며, 일반 게시판 글쓰기 및 댓글들은 정상입니다.

**Comment by bnu** [comment]
새로 설치하거나 1.8.24에서 사용한 문서 페이지를 1.8.43 버전으로 업데이트 후 확인해보았으나 수정 사항이 잘 반영 되는 것으로 확인했습니다.

게시판에서 정상 글 등록이 가능하니 에디터 등 관련 부분은 아닌 것 같으나,
페이지 관련해서도 영향을 줄 수 있는 변경사항은 없었습니다.

가능하시다면 문제가 발생하는 페이지와 수정 권한이 있는 계정을 알려주시면 확인이 가능할 것 같습니다.
임시로 권한이 있는 계정을 생성하여 bnu@xpressengine.com 메일로 보내주시면 확인해보겠습니다.
(서버를 들춰 보는 게 아니라서 단순한 확인만 가능하므로 문제 해결이 도움을 드리지 못할 수 있는 점 미리 양해부탁드립니다)

**Comment by fy5914** [comment]
추가적인 확인사항으로써, 모듈중에 EASY XE의 사용체크를 해제했었는데,

혹시나 이것을 다시 사용으로 하니까

정상적으로 문서페이지가 업데이트/문제 해결이 된 것으로 확인하였습니다.

상세한 확인/답변주심에 감사드립니다.

**Comment by bnu** [comment]
확인 감사합니다.
