### ISSUE TITLE
oembed : xe_content 가로폭에 딱 맞게 표시되도록 개선

### ISSUE THREAD

**Issue by haendel8** [xpressengine/xe-core#2137]
이건 제가 고쳐서 쓰고있는 부분인데 한번 반영할만한지 함 보시고 버리셔도 됩니다.^^

jquery.oembed.js 의 내용을 보니 플레이어의 크기를 정하는 부분에서 선언되지 않은? settings.maxWidth 값으로 체크를 하고있더라구요. 그래서 아래와 같이 'settings.maxWidth' 가 없을 때의 처리에 관한 } else { ... } 부분을 추가했더니 xe_content 가로폭에 꽉 차게 표시되도록 구현됬습니다.

jquery.oembed.js 의 300번째 행의 조건문

```
if(post_width < settings.maxWidth) {
    ratio = iframe_width_orig / post_width;
} else if(settings.maxWidth < iframe_width_orig) {
    ratio = iframe_width_orig / settings.maxWidth;
} else {
    ratio = iframe_width_orig / post_width;
}
```

끝에
```
else {
    ratio = iframe_width_orig / post_width;
}
```
이 부분만 추가했습니다.

**Comment by bnu** [comment]
해당 코드를 적용하고 확인했습니다.
콘텐츠 영역폭에 최대 크기로 출력이 되는 것으로 확인했습니다.

현재 상태는 콘텐츠 영역을 넘어 벗어나지 않도록 동작하고 있습니다.
최대 폭으로 항상 늘리는 것은 반영하기 적절하지 않을 것 같습니다.
영상 위주의 콘텐츠라면 유용하겠으나, 그렇지 않을 때는 영상이 너무 큰 영역을 차지하게 되어 다른 콘텐츠를 방해할 수 있을 것 같습니다.
