### ISSUE TITLE
HTML Link 앙카(anchor) 기능에 대해 문의합니다.

### ISSUE THREAD

**Issue by largeden** [xpressengine/xe-core#2138]
라이믹스에도 이슈올렸는데 이곳에도 문의드립니다. https://github.com/rhymix/rhymix/issues/903

HTML내에서 링크를 만들어 이동을 하고자할때에 Bookmark, 일명 앙카(anchor)를 이용하게 됩니다.
https://www.w3schools.com/html/html_links.asp
HTML Links - Create a Bookmark

헌데, XE는 id, name attribute를 아예 활성화하지 않고 있어서 일반 사용자가 글을 쓸때 이 기능을 만들 수 없습니다.

https://github.com/xpressengine/xe-core/blob/f482897cabdba2ce4a809b4cadc291d8ff24a6d3/classes/security/Purifier.class.php#L32

혹 문제가 없다면 다음 버전에서 아래와 같이 설정 값을 추가해주실 수 있는지 문의드립니다.

        $this->_config->set('Attr.EnableID', true);

**Comment by largeden** [comment]
앵커인데 일본식 발음 때문에 앙카라고 썼네요 ㅠㅠ

**Comment by kijin** [comment]
라이믹스에서는 보안과 호환성을 위해 `user_content_`로 시작하는 `id`만 허용하고 있습니다. `id`가 필요한 기능을 개발하시는 분들의 편의를 위해 XE에서도 동일한 prefix를 사용한다면 도움이 되겠습니다.

rhymix/rhymix#903

**Comment by bnu** [comment]
```php
return array(
    'Attr.IDPrefix' => 'user_content_',
    'Attr.EnableID' => true
);
```

이렇게 설정 파일을 만들어두면 적용되도록 하면 좋을까요?

**Comment by kijin** [comment]
@bnu 설정 파일을 또 만드시게요? 그냥 기본값으로 적용시켜도 될 것 같은데요. 관리자는 어차피 글을 쓸 때 `removeHackTag()`를 호출하지 않으니 상관없고요.

**Comment by bnu** [comment]
저도 박아버리는 게 편하긴 합니다만...

**Comment by kijin** [comment]
prefix가 설정에 따라 쉽게 바뀌지 말아야 하는 이유에 대해서는 라이믹스의 관련 이슈에서 설명을 드렸습니다. 그냥 Purifier.class.php에 박아버리시죠 ㅎㅎ

**Comment by largeden** [comment]
@bnu 
낮에 @kijin 님등과 이야기 나눴었는데요. 저도 kijin님과 같은 의견입니다. 위 제가 링크걸어논  `_setConfig()`에 선언하면 될 것 같습니다.
