### ISSUE TITLE
게시판에 상담과 익명 기능을 동시에 사용했을 때 오류

### ISSUE THREAD

**Issue by wonsuc** [xpressengine/xe-core#2140]
Fatal error: Call to undefined method documentItem::getDefaultStatus() in /www_root/xe/modules/document/document.item.php on line 1025

![kakaotalk_20170905_015055643](https://user-images.githubusercontent.com/9866158/30036946-56fb64ea-91f2-11e7-87db-395aa5d2c318.png)

익명일 경우 -(글쓴이의member_srl) 형태로 member_srl이 삽입되는데 board.view.php의 dispBoardContentView 메서드에서 음수양수를 고려안하고 로그인한 유저의 srl과 비교하다보니 발생하는 오류인거 같습니다.

발생하는 시점은 상담과 익명 기능을 동시 사용하는 게시판에서 일반 사용자가 본인의 글을 읽는 페이지에서 해당 에러가 발생합니다.

정확한 에러 발생 버전은 알 수 없으나 클라이언트에 의하면 최신 버전 패치 후에 발생했다고 합니다.

**Comment by kijin** [comment]
좀더 직접적인 원인은 `documentItem` 클래스에 `getDefaultStatus()` 메소드가 존재하지 않는데 호출하려고 하고 있군요.

**Comment by kijin** [comment]
우선 modules/document/document.item.php 1025번째 줄에서

```
if(!$this->get('status')) return $this->getDefaultStatus();
```

이것을 아래와 같이 변경해 봅니다.

```
if(!$this->get('status')) return getClass('document')->getDefaultStatus();
```

이렇게 변경했을 때 익명글+상담 기능에 어떤 영향을 주는지는 모르겠으나, 일단 백지화면에 Fatal Error만 뜨는 문제는 해결이 가능할 듯 합니다.

**Comment by bnu** [comment]
@kijin 님이 해결한 코드와 더불어 상담 기능과 익명 기능을 동시에 사용할 때 발생하는 문제를 고쳤습니다.
