### ISSUE TITLE
WYSIWYG Editor

### ISSUE THREAD

**Issue by solatoz** [xpressengine/xe-core#2150]
WYSIWYG Editor
![wysiwyg](https://user-images.githubusercontent.com/17806436/30679341-c63ed884-9e4d-11e7-9265-d7846871d582.PNG)
의 인디케이터(마크/이미지)들이 모두 Blank로 나옵니다.

무엇이 문제인지 알려 주세요.

최신 버전으로 업데이트 했더니 생긴 문제 입니다. (xe.1.8.45)

아래 캡쳐 사진 참조

**Comment by wonsuc** [comment]
XE 문제라고 보기는 좀 힘드네요.

**Comment by bnu** [comment]
CSS 영향을 받거나 버튼 이미지를 로드하지 못하는 등의 문제로 보입니다.
문제가 나타나는 주소를 주시면 확인이 가능합니다.
