### ISSUE TITLE
Your browser doesn't allow you to paste this way. Press 컨트롤+V to paste.

### ISSUE THREAD

**Issue by AraIV** [xpressengine/xe-core#2152]
해당 문구 어디에서 풀어야 하는지요?
표나 스타일 등이 제대로 붙여 넣기가 안됩니다.

**Comment by wonsuc** [comment]
전 최신버전으로 업데이트 한 뒤 해당 이슈 안뜨더라구요. 사용하시는 XE버전과 어떤 디바이스, 어떤 브라우저에서 발생하는 이슈인지를 명시해주는 것이 좋을 듯 합니다.

**Comment by AraIV** [comment]
1.8.45 최신버전이구요. 크롬에서 워드형태 붙여넣기 클릭시 발생하고 있습니다.

**Comment by bnu** [comment]
해당 플러그인 제거했습니다.
