### ISSUE TITLE
아직도 사이트 곳곳에 MID를 생략한 주소로 생성합니다. 

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2155]
이로 인해 각종 위젯들에서 MID가 빠진 주소를 제공해 사이트에 이미 체류하는 방문자들도 주소를 클릭 후 이동시 불필요한 리디렉트 과정을 거치게 됩니다. 

또 rss 발행시에도 MID가 없는 주소로 발행을해서 이런 주소가 검색엔진등에 반영되는 문제도 있습니다.

https://www.xetown.com/qna/751234

기본적인 문서주소에 대한 것을 너무 오래 방치하는 것 아닌가 하는 생각이 듭니다.

**Comment by bnu** [comment]
배포본에 포함된 위젯, 모듈이나 스킨에서 수정해보겠습니다.
RSS 모듈에서 출력하는 링크 또한 살펴보겠습니다.

**Comment by wookho** [comment]
@bnu 스킨에서도 수정이 이루어져야 하는 것은 맞지만..
처음 url 자체를 mid가 포함된 url로 생생되어야 한다고 봅니다. 

아마 문서모듈에서 생성하는 것으로 알고 있습니다.

**Comment by wookho** [comment]
@bnu 
이와 관련 해서 이야기 하다가 댓글에 
XE는 $oDocument->getPermanentUrl()을 사용해도 mid가 누락되는군요.

이런 의견을 받았습니다.

**Comment by bnu** [comment]
@wookho `getPermanentUrl()` 이거 말씀하시는 거죠?
물론 이것도 포함하고, 이것을 사용하지 않고 getUrl()로 사용되는 곳이 많아서 전체적으로 수정해야겠죠.

**Comment by wookho** [comment]
@bnu 네. 전반적으로 살펴봐주세요.
요상하게 네이버에서 XE로 된 사이트의 웹문서 수집을 1차적으로 rss로 긁어갑니다. 그리고 실제로 문서를 한번 더 크롤링 하구요.

이러한 과정에서 XE사이트들이 모두 중복문서 수집이 되고 있어요. rss를 통해 mid 없이 한번 실제 크롤링을 통해 mid 있는 것으로 한번..

XE공홈은 무슨 이유인지 rss를 못긁어 가는 것 같더군요. 그래서 rss로 수집한 것이 없어 mid 있는 주소로만 수집되고 있습니다.
 - XE공홈은 https://developers.google.com/speed/pagespeed/insights/?hl=ko

여기에 주소를 넣어보면 해석을 못하는데 이와 관련이 있어 보이기도 합니다.
