### ISSUE TITLE
관리자 사이트맵 메뉴를 편집할 때 좀 쉽게 해주세요.

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2157]
먼저 XE의 경우 메뉴 1개를 수정하려면 무조건 갯수만큼 수정저장/새로고침이 발생합니다.
워드프레스의 경우 한개의 사이트맵에서 수정과정을 한 후에 업데이트 1번으로 모두 수정작업이 됩니다.

구조는 다음과 같으면 어떨까 생각해봤습니다. 
1. 기존의 사이트맵 모음 > 2. 편집할 사이트맵 선택(추후 저장할 사이트맵) > 3. 편집 > 편집 완료 후, 2에서 저장.

[사이트메뉴편집] [편집할사이트맵선택] [편집및저장]

현재는 [사이트메뉴편집] > [사이트맵명]-하나만 나타남 > [메뉴수정]
이런 구성인데요,

제가 건의드리는 것은 사이트맵명이 하나만 나오는 것이 아니라, 편집할 사이트맵을 선택하면 폴더형의 구조가 그대로 선택이 되는 것입니다. 차후에 사이트맵끼리 이동할 경우 2개 이상이 될 수도 있고, 이건 복수의 사이트맵을 선택가능합니다. (이 부분 설명이 좀 어렵지요. 긍정적으로 논의가 필요하다면 그림으로 다시 그려보겠습니다. )

**Comment by bnu** [comment]
메뉴 수정할 때 마다 새로고침이 짜증나긴 합니다.
다만, 이 부분은 건드릴 것이 많을 것으로 보이네요.
쉽지는 않아 보입니다.

**Comment by bnu** [comment]
편의성을 위한 주요 개선이 될 수 있으나, 처리하지 않고 닫습니다.
