### ISSUE TITLE
게시판별 포인트 관리를 한번에 일괄 설정 할 수 있었으면 합니다.

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2159]
10년동안 생성해서 사용하는 게시판 갯수가 500개가 넘습니다. (__);
관리자 > 회원 > 포인트 > 포인트관리 > 모듈별 설정 화면에서 말이죠.
이 500개가 로딩되는데는 사실 많은 시간이 필요하지 않습니다만,
각각의 포인트가 7개 항목이란 말이죠.

이걸 한번에 설정한다는 건 무리가 있습니다.
게시판 종류를 선택하는 건 기본 설정값이 사이트 디자인 설정에서 있는데,

사실 불편한게 이런 디자인 설정 뿐만 아니라, 각 게시판의 권한 설정이나 스킨 설정, 포인트 설정인데요,

제가 이걸 이런 식으로 만들어봤습니다.
http://eond.com/xe_usertip/392961
tpl 관리자 페이지의 경우 <style> 부분 적용이 안되어서 그냥 style 인라인속성으로 넣었는데
이 부분도 됐으면 좋겠고 @_@;

코어반영이 되는 부분일까요

**Comment by bnu** [comment]
추가/수정하신 코드를 PR해주시면 반영할 수 있습니다.

`<style>` 태그가 포인트 모듈 부분만이 아닌 관리페이지 전체에 적용된다는 것을 말씀하시는 것이라면,
`modules/point/tpl/module_config.html` 파일에 추가하신 것이 아닌가요?
