### ISSUE TITLE
Uncaught TypeError: undefined is not a valid argument for URI

### ISSUE THREAD

**Issue by ppleo** [xpressengine/xe-core#2162]
Your version: 1.8.43 까지는 괜찮더니 Your version: 1.8.45 으로 업하니.

전체 파일을 업해서..

아래 와 같은 에러가 나면서 슬라이더가 무한로딩만 되네요..^^

같은 슬라이드을 쓰는데 다른샘플 사이트는 괜찮은데요.. 혹시 무슨 문제가 있을까요?

image
![image](https://user-images.githubusercontent.com/5974818/31420348-edf08c2c-ae7b-11e7-905f-e40d154cc1b3.png)

같은 슬라이드 문제가 생기는 것입니다.
http://www.2sisstore.com/mercury

정상인곳....하하하..^^

http://www.2sisstore.com/cronos_rx

같은 nivo-slider를 쓰고 있어서...하하하..이것참..

**Comment by bnu** [comment]
![2017-10-11 4 11 50](https://user-images.githubusercontent.com/53764/31426588-ed0b3a96-ae9e-11e7-9efc-6be1ca512825.png)

`<a>` 태그에서 target 속성이 비어있을 때 발생하는 것으로 확인했습니다.

target 속성을 제거하시면 임시로 해결되며, 다음 버전에 문제를 해결하여 배포하도록 하겠습니다.

**Comment by ppleo** [comment]
음  target 속성을 지워도 같은 경우가 생기네요 일단은 이전버전으로 돌리고 추후 버전일때 업그레이드 를 해야 할것 같네요.. 감사합니다.
