### ISSUE TITLE
ckeditor 에서 모바일에서 입력하면 이상하게 입력이 되네요

### ISSUE THREAD

**Issue by rubyon** [xpressengine/xe-core#2165]
우선 아이폰/아이패드 에서

모바일 환경에서 ckeditor 에서 종성없이

"야야야" 이런식으로 입력을 하고 엔터를 친다음 다시
"너" 라고 입력하면

"야야야야너"

이렇게 줄바꿈이 되돌아가고 중간에 글자가 하나 더 추가가 되네요

**Comment by kijin** [comment]
애플 기기에서 CKEditor를 사용할 경우 자주 나타나는 현상입니다. XE에서는 CKEditor를 그대로 가져다 쓸 뿐이기 때문에 대책이 없습니다. TinyMCE 등 다른 오픈소스 에디터들도 대부분 마찬가지입니다.

**Comment by bnu** [comment]
XE1 공홈에서 현재 해당 증상이 재현되는지 확인 부탁드립니다.
특정 항목을 변경해봤는데... 이게 어떤 다른 영향을 줄지는 확인해봐야겠네요.

우선은 본문에 말씀하신 증상 해결이 되는지 확인 부탁드려요.

**Comment by rubyon** [comment]
공홈에서 테스트해봤는데... 내용 부분은 버그가 해결된거 같은데...

제목에

테스트

라고 쓰고 내용에 "임시테스트" 라고 입력을하면

"테임시테스트" 라고 적히네요

제목의 마지막 한자가 내용에 추가가 되는현상 입니다.

**Comment by bnu** [comment]
모바일에서만 문제의 원인이 되는 CKEditor 에디터의 플러그인 비활성화로 처리 함
