### ISSUE TITLE
우편번호 모듈이 코어에서 제외되어있는데....

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2167]
krizp 모듈이 XE 코어에는 없네요?
그런데 해당 기능을 사용하는게 주로 게시판에서 사용자정의 - 우편번호인데요,
board 모듈은 코어에 탑재되어있습니다. 그러면 우편번호 기능도 동작하기 위해서는 코어에 포함되는 게 맞지 않나요?

**Comment by bjrambo** [comment]
https://github.com/xpressengine/xe-module-krzip 따로 분리되어있습니다.

코어에 포함하지 않는것이 더 낫다는 평으로 생각되고있는듯합니다.

**Comment by bnu** [comment]
우편번호 모듈은 저장소는 분리되어 있지만 배포 시 함께 묶어 배포하고 있습니다.
