### ISSUE TITLE
글 작성중 긴주소로 url이 전달되는 문제. 최근 발생한 문제

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2170]
이전에는 긴주소로 완성되지 않았던 것 같습니다. 최근 한달 이내의 기간 안에 변동이 생긴 듯 합니다.

글 작성 직후 게시글 url이 긴주소로 표시되어 신디케이션으로 네이버쪽에 긴주소로 전달되어 rss로 수집해간 짧은주소 신디케이션으로 수집된 긴주소 2개의 문서가 중복수집됩니다.

또한 현재 url을 담아 api를 통해 전달하는 애드온등의 자료에서도 긴주소로 전달되는 문제가 생겼습니다.

https://www.xetown.com/rxe_issue/776016

**Comment by bnu** [comment]
말씀하시는 "긴주소"는 'mid=board&document_srl=123'과 같은 형태를 말씀하시는 게 맞나요?

"도메인 + mid + srl" 형태로 통일해야겠네요.

#2155 이슈에서 함께 처리하도록 하겠습니다.

**Comment by wookho** [comment]
@bnu 네. 그런 긴주소로 출력되게 바뀌었는데 이게 최근에 발생된 문제입니다. 
먼저 열어드린 이슈와는 조금 다른 문제이구요. 최근에 발생한 문제 같습니다.

이문제 때문에

https://github.com/xpressengine/xe-module-syndication/issues/10

이러한 문제가 있ㅅ브니다.

**Comment by wookho** [comment]
그래도 답을 해주시는 다행이네요.
이문제는 신디케이션을 중단해야 할 만한 상황으로 긴급히 처리가 필요해 보이는 중요 문제입니다. SEO에 관한 문제는 좀 중대한 사안으로 보아주셨으면 합니다.

코드를 볼줄 몰라 어디 변경점에서 문제가 발생한지는 알 수 없으나 제가 변화된 부분을 거슬러 올라가보니 최근에 발생된 문제입니다.

공홈에서도 글 작성해 보니 동일하구요.

**Comment by wookho** [comment]
https://www.xetown.com/rxe_issue/776016#comment_776078

1.8.44 업데이트 영향으로 추정이 됩니다.

**Comment by wookho** [comment]
기진곰	2분 전
XE에서 글 작성 직후에 넘어가는 주소는 항상 긴주소입니다. 최근에 바뀐 게 아닙니다. 라이믹스에서는 1년여 전에 패치해서 짧은주소로 넘어가도록 했고요.

POST 요청 상태에서 getUrl(), getFullUrl() 등의 함수를 호출하는 경우 POST로 넘어온 개인정보가 URL에 포함되어 나오는 보안문제가 있어서 1.8.44쯤에 고쳐졌습니다. 따라서 POST 요청 상태, 즉 글쓰기 직후가 아닌 글쓰기 요청 도중에 URL을 생성하는 서드파티 자료가 있다면 여기에 영향을 받았을 수도 있습니다.
 
그러나 mid와 document_srl만 넘겨주면 짧은주소를 반환한다는 규칙은 변하지 않았으니, 예전에 불필요한 다른 파라미터 때문에 긴주소로 나오던 것이 짧은주소로 바뀌었다면 몰라도 예전에 짧은주소로 나오던 주소가 긴주소로 바뀔 가능성은 낮습니다.

**Comment by wookho** [comment]
원래부터 긴주소로 표시되었고...

글 작성중에 넘겨주는 url이 이제 긴주소로 넘겨주는 것으로 코어에서 변경점이 생겼다면 신디케이션모듈을 비롯한 서드파티에서 이를 받아주어야 하는 상황으로 보입니다.

이 사실을 아는 제작자분들 그리고 중요성을 인식하는 제작자분들의 경우는 수정할 수도 있겠지만 그렇지 않은 경우는 긴주소로 api쪽으로 넘겨주는 상황이 여전하겠네요.

**Comment by bnu** [comment]
![2017-10-25 4 01 30](https://user-images.githubusercontent.com/53764/31984814-ca16b858-b99d-11e7-8831-9fb317d9bb10.png)
해당 주소는 정상적으로 출력되는 것으로 확인했습니다.

가능하다면 해당 페이지(게시물) 주소와 신디케이션 모듈의 '신디케이션 비밀번호'를 공유해주시면 확인이 쉽습니다.
공유 가능하다면 bnu@xpressengine.com 메일 주시기 바랍니다.

**Comment by wookho** [comment]
@bnu 지금은 신디케이션을 중단했습니다. 패스워드는 따로 사용하지 않고 있습니다. 이미 등록된 게시글 주소를 알려드리면 되나요?

**Comment by bnu** [comment]
@wookho 음.. 네. 일단 게시물 주소라도 알려주시면 제한적이나마 확인해보겠습니다.

**Comment by bnu** [comment]
'domain/MID/SRL' 형태로 네이버로 보내지고 있습니다.

좀 더 확인해봐야겠으나...
코드상으로도 'domain/MID/SRL'으로 명확하고..
syndication 모듈의 문제는 확인할 수 없었습니다.

**Comment by wookho** [comment]
@bnu 글쎄요. 제가 사용하는 애드온에서도 한달 전 즈음 부터 긴주소로 구글로 보내져서 구글측에서 긴주소로 단축주소를 만들어준 것을 확인했습니다.
이 애드온은 현재 머물고 있는 곳의 주소를 그대로 그대로 구글에 전달하는 그런 애드온 이었습니다. 그런데 이렇게 긴주소로 보내지게 된게 불과 한달사이 시점입니다.

저희 게시물 제목 쪽에 짧은 주소라고 있습니다. 그것을 클릭하면 구글단축 주소가 클립보드에 담겨지는데 오늘 이전 게시글들을 보면 전부 긴주소로 되어 있는것이 확인 되실 거에요.

이 애드온은 제가 현재 머물고 있는 주소가 아닌 'domain/MID/SRL' 형태로 구글로 보내게 오늘 수정했습니다.

**Comment by wookho** [comment]
네이버서버에서 신디케이션으로 핑을 받은다음 어떻게 처리하는지 저희는 알 수 가 없으니...

XE의 게시글 소스에 보면 

<--script>
var current_url = "https://www.xpressengine.com/?mid=devlog&document_srl=23244976";
var request_uri = "https://www.xpressengine.com/";
var current_mid = "devlog";
var waiting_message = "서버에 요청 중입니다. 잠시만 기다려주세요.";
var ssl_actions = new Array();
var default_url = "https://www.xpressengine.com/";
var enforce_ssl = true;</script-->


이런 소스가 있습니다. 

혹시 네이버봇이 저희 신디케이션모듈에 의해 핑을 받은다음 즉시 크롤링하러 와서 저런 소스에 영향을 받아 저 주소로 색인하는건 아닐까 하는 그냥 추측의 댓글이라도 달아봅니다.

**Comment by wookho** [comment]
<--script>
--
  | var current_url = "https://www.xpressengine.com/?mid=qna&act=dispBoardWrite";
  | var request_uri = "https://www.xpressengine.com/";
  | var current_mid = "qna";
  | var waiting_message = "서버에 요청 중입니다. 잠시만 기다려주세요.";
  | var ssl_actions = new Array();
  | var default_url = "https://www.xpressengine.com/";
  | var enforce_ssl = true;</scrip--t>


요건 글 작성시에 보이는 소스입니다.

**Comment by bnu** [comment]
@wookho 신디케이션은 주고 받는 데이터를 최소화하기 위해 별도로 접근을 합니다.
(메일로 보내드렸습니다.)

**Comment by wookho** [comment]
@bnu 네. 그렇다면 ping 을 받을때의 전달받은 정보와 상관없이 방문해서 읽어간 주소로 색인한다고 추정할 수 밖에 없습니다. 

신디케이션의 문제가 아니라면 현재 네이버의 봇이 XE게시물의 주소를 긁어가는데 문제가 있다는 것일 수도 있겠고 아니면 XE 문서의 소스 어디에 문제가 있을 수도 있다고 봅니다. 

정확히 
https://www.xpressengine.com/?mid=devlog&document_srl=23244976

이렇게 색인을 해버리고 있으니까요.

**Comment by wookho** [comment]
https://www.xetown.com/rxe_file/776283

해결이 될지 사용해봐야 알겠지만 이를 회피해 볼수 있는 애드온이 개발되어 공개되었습니다.

**Comment by bnu** [comment]
확인된 것과 같이 코어의 변경이나 syndication 모듈의 영향으로 보이지 않아 이슈를 닫습니디ㅏ.

**Comment by wookho** [comment]
성급한 결론을 내리시네요. 네이버측에서 신디케이션으로 색인반영하려면 신디케이션 사용을 시작후 시간이 필요하고 또 신디케이션으로 반영을 시작한 사이트라도 문서가 즉시 반영되지 않습니다.

제가 모니터링 후 다시 알려드리겠습니다.

**Comment by bnu** [comment]
@wookho 네. XE에서 변경해서 해결될 수 있는 부분이면 알려주세요.

다시 말씀 드리지만 신디케이션 모듈의 변경사항이 없었고, 최근 코어의 변경으로 인해 신디케이션 모듈에 영향을 줄 수 없는 부분입니다.

**Comment by wookho** [comment]
@bnu 네. 말씀 하신대로 최근에 생긴 문제가 아닐 가능성이 있습니다. 제가 최근에 다시 신디케이션을 사용하면서 확인을 했습니다. 아마도 예전부터 발생이 되는 XE또는 네이버신디케이션 검색엔진이 가진 오류 일 것으로 추측됩니다.

**Comment by bnu** [comment]
코어 이슈로 판단할 만한 추가 증상이나 정보가 없으면 12월 중 이슈를 닫도록 하겠습니다.
