### ISSUE TITLE
컨텐츠 안에 mail to 링크가 있으면 에러가 발생합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2174]
댓글이 950개 이상 달린 게시물을 읽을 경우 // 이건 아니고 제목의 문제로 확인되었습니다.
최고관리권한을 가진 계정에게 문제가 생깁니다. 

콘솔에 아래 에러가 확인되며
xe.min.js?20171021181154:6 Uncaught Error: URNs do not have any generally defined hierarchical components 

사용자정의 부분이 보이지 않고 
스크립트 오류로 동작에 문제가 생깁니다.

댓글 페이지를 한페이지만 이전 페이지로 이동 시키면 이상이 없어집니다.

**Comment by wookho** [comment]
최고관리권한 -> 관리그룹 으로 정정합니다. 게시판 관리권한이 있는 계정으로 접근해도 동일합니다.

**Comment by wookho** [comment]
이전 댓글을 삭제해서 910여개 정도 되니 정상이 됩니다.

**Comment by wookho** [comment]
컨텐츠에 mail to 링크가 들어 있어 생기는 문제입니다.

**Comment by wookho** [comment]
https://www.xetown.com/rxe_issue/792186

**Comment by kijin** [comment]
아래와 같이 해결하면 될 것 같습니다.

- `isSameHost()` 함수에서 외부 링크 여부를 판단할 때 http: 또는 https:로 시작하지 않는 링크는 URL.js로 비교하지 않고 무조건 외부 링크로 취급하거나, 아예 `target="_blank"` 속성을 날려버림 (mailto: 또는 tel: 링크를 `target="_blank"`로 여는 것은 어차피 무의미합니다.)
- http: 또는 https:로 시작하는 링크라도 최소한의 형태가 제대로 갖춰져 있는지 확인한 후 URL.js로 넘겨주거나, 아니면 예외처리하는 코드를 작성
