### ISSUE TITLE
 배포되는 모바일 스킨에 제거하고 배포해주세요.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2176]
{@ Context::addJsFile("./common/js/jquery.min.js", true, '', -100000) }
{@ Context::addJsFile("./common/js/xe.min.js", true, '', -100000) }

ex)멤버스킨이나 커뮤니케이션 스킨....

**Comment by bnu** [comment]
어이쿠...
감사합니다.
더 있는지 찾아보고 제거하겠습니다.
