### ISSUE TITLE
문서변경이력에 글쓴이 정보도..

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2178]
게시판 모듈에서 문서 변경 이력 기능을 사용하면,
수정시간, 수정아이피는 변경이 되는데
글쓴이 정보는 처음 게시물 작성자 정보 그대로 남습니다.

이것도 수정한 사람의 정보가 반영되도록 하는게 맞지 않을까 싶습니다.

**Comment by AraIV** [comment]
이거 해결 가능 할지요?.. DB보니 수정한 사람이 전부 첫 게시글 작성자네요 ;;
