### ISSUE TITLE
모듈별설정에서 값을 입력한 후 저장하면...

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2179]
관리자 > 포인트 > 포인트관리 > 모듈별설정에서..
게시판이 약 500개 이상이라서 (500*7=3500)
약 인풋값이 3500개 정도 됩니다.
그런데 저 페이지에서 저장을 하면 첫번째 인풋에서 988번째 인풋까지는 저장이 되는데..
그 이후부터는 저장이 안됩니다. 

일괄변경하도록 수정한 건데, -_-; 
이거랑은 상관없이; 일단 게시판이 많아서 인풋에 값을 다 입력해버리고
988개까지는 인풋에 저장된 값이 저장이 되는데 나머지는 저장이 안됩니다..

람보님께서 말씀하시길,  insertModuleConfig나..  getModuleConfig 를 이용하면 데이터가 길면 길수록 뒷부분의 설정은 날라간다고 하더라고요. config테이블이 bigtext타입이 아니라 일반 text타입이라 길면 뒷부분이 짤린다고 하던데,

혹시 이게 길어도, 뒤에 값이 있으면 계속 확인해서 추가 저장하도록 하는 식은 안되나요?

**Comment by bnu** [comment]
게시판이 정말 많네요.

DB 컬럼의 제한을 넘을 수도 있을 것 같네요.
DB에 접속하여 phpmyadmin 등의 툴을 이용하여 longtext로 변경하시거나 다음과 같이 쿼리를 이용해서 해당 컬럼의 크기를 늘릴 수 있습니다.
```sql
ALTER TABLE `xe_module_config` CHANGE `config` `config` LONGTEXT;
```

**Comment by bnu** [comment]
디비보니 분할되어 저장되네요.
내일 살펴보고 확인해볼게요. 컬럼 크기 문제는 아닌 것 같네요.
post_max_size 문제일 수도 있어보이네요.

**Comment by eondcom** [comment]
아울러, 모듈별설정을 초기화하는 버튼이 추가되었으면 합니다.

**Comment by bnu** [comment]
@bjrambo 님과 얘기하다보니 타임아웃으로 인한 문제로 추정됩니다.
서버의 `max_execution_time` 값을 60, 120 이상으로 늘리고 테스트 가능할까요?
(해보고 있는데.. 게시판 복사하기가 힘드네요;;)

**Comment by eondcom** [comment]
@bnu 동일합니다. ^^; 필요하시다면 사이트 정보 드릴게요. 카카오톡 2ond 입니다.

**Comment by bjrambo** [comment]
@eondcom 아쉽게도 BNU님은 카카오톡을 쓰지 않습니다.

**Comment by eondcom** [comment]
![image](https://user-images.githubusercontent.com/3683813/33423845-548551d6-d5fd-11e7-8445-d6cf958bd732.png)
db 테이블도 longtext로 수정했습니다만 변화는 없습니다;

**Comment by bnu** [comment]
컬럼 크기의 문제가 아닌 것으로 확인되었으며(PHP max_input_vars 제한),
xe_module_config.conf의 컬럼 크기는 #2180 이슈에서 다루겠습니다.
