### ISSUE TITLE
moduleConfig를 저장하는 칼럼의 Config칼럼이 text인 문제.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#2180]
일부 모듈에서 에디터를 호출하여 HTML을 moduleConfig를 사용하여 저장하는 경우가 있습니다.

이때, module_config테이블의 config 칼럼이 text이라 정상적으로 전체길이가 저장안되는 문제가 있습니다.

~이는 1.7.4에서 communication 에서 쪽지의 내용이 짤리는 문제와 거의 동일하다고 봅니다.~

확인해보니 이슈는 일딴 모르겠고, 뭔가 요청이 안받아진거같고요..

관련 이슈는

https://www.xpressengine.com/index.php?mid=forum&search_target=nick_name&search_keyword=%EB%AA%BD%EC%8B%A4%EC%95%84%EB%B9%A0&page=1&document_srl=22960218

공홈에서 찾아볼 수 있었습니다. 

moduleConfig와 더불어 비슷한 방법으로 serialize 을 하는 설정값에 모두 text가 아닌 bigtext으로 바꿔야 하지 않을까 생각됩니다. 

한번 검토해주세요.

**Comment by bnu** [comment]
문제로 제기되었던 쪽지 내용이 잘리는 문제는 module_config.config 컬럼의 문제와 연관 없음으로 확인 되었음

**Comment by bnu** [comment]
@kijin 네. 현재 DB class에서 column 타입을 수정할 수 있는 방법을 제공하지 않아 업데이트 수행이 불가능 합니다.
필요하다면 업데이트는 제외하고 설치할 때만 적용할 수 있을 것 같습니다.
대량의 데이터는 별도로 처리해도 되겠지요.
