### ISSUE TITLE
Object 클래스의 이름 충돌로 인한 클래스 이름 변경

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2181]
PHP 7.2에서 `Object` 클래스를 사용할 수 없음.
PHP 7부터 예약어로 지정됐고, 최근 PHP 7.2에서 변경으로 인해 사용이 제한 됨.
PHP 7.2는 현재 RC6 단계이지만 이 변경 사항은 정식버전에도 반영될 것으로 보임

XE는 이러한 PHP 7.2의 변경사항에 맞춰 `Object` 클래스의 이름을 `BaseObject`로 변경합니다.
이로 인한 호환성 문제를 피하기 위해 PHP 7.2 미만에서는 여전히 `Object` 클래스를 사용할 수 있습니다
(`class_alias()`를 이용해 `Object`클래스를 유지합니다)

이는 PHP 7.2의 변경으로 인해 XE가 변경을 따라갈 수 밖에 없는 부분입니다.
`return new Object(...)`과 같은 코드를 사용한 모듈, 애드온, 위젯 등은 이 변경사항을 반영하지 못하면 PHP 7.2 이상에서 동작할 수 없습니다. 다음과 같이 변경 사항을 적용해야 PHP 7.2 미만과 이상에서도 동작할 수 있습니다.

써드파티 모듈 등에서 `return new Object(-1, 'error message')`처럼 사용하고 있다면 다음과 같이 수정해야 합니다.
```php
return new Object(-1, 'errmsg');
$output = new Object();
// 이와 같이 사용했다면 아래와 같이 변경

return class_exists('BaseObject') ? new BaseObject(-1, 'errmsg') : new Object(-1, 'errmsg');
$output = class_exists('BaseObject') ? new BaseObject() : new Object();
```
이름이 바뀐 `BaseObject`와 `Object` 클래스를 모두 지원할 수 있도록 합니다.

@kijin 님께서 제시해주신 코드이며, 동작에 문제가 없는 것 까지 확인해주셨습니다.
다만, PHP 7.2의 정식 버전이 배포되기 이전이므로 PHP 7.2 정식 버전 및 이후의 변경에 따라 이 방법이 유효하지 않을 수도 있습니다.

**Comment by bjrambo** [comment]
`return $this->stop('text');` 을 사용하는 경우도 있던데... 이부분은 어떻게 처리하실 예정인가요?

**Comment by kijin** [comment]
서드파티 자료 제작자 중 수정하실 부분이 많다면 아래와 같이 편리하게 처리할 수도 있습니다.

우선 `모듈명.class.php`에 정의된 모듈 기본 클래스에 메소드 하나를 추가합니다.

```
public function makeObject($code, $msg)
{
    return class_exists('BaseObject') ? new BaseObject($code, $msg) : new Object($code, $msg);
}
````

그리고 이 클래스를 상속받는 다른 모든 클래스(컨트롤러, 모델, 뷰 등)에서
```
return new Object(-1, 'errmsg');
```
라고 되어 있던 부분을 모두
```
return $this->makeObject(-1, 'errmsg');
```
라고 바꾸시면 그나마 깔끔하게 호환성을 유지할 수 있습니다.

서드파티 모듈 내에서 이런 함수는 얼마든지 자유롭게 만들어 쓰셔도 됩니다.

**Comment by howtoxe** [comment]
@kijin 해당 함수를 XE 코어 차원에서 지원하는 편이 나을 것 같습니다.

**Comment by bjrambo** [comment]
@howtoxe 서드파티에서 XE코어 함수라고 썻다가 이전 버전에서 실행하지 못하는 경우떄문에 모듈 클래스로 만들라고 하는겁니다..ㅡ.ㅡ;;ㅋㅋㅋ

**Comment by kijin** [comment]
@howtoxe XE 구버전과 신버전을 모두 지원해야 하는 서드파티 자료 개발자 입장에서는 이제 와서 함수를 새로 만든다 해도 도움이 되지 않습니다. XE 구버전에는 해당 함수가 없었으니까요... 여전히 `function_exists` 등을 사용해서 삼항식으로 처리해야 하겠지요.

**Comment by howtoxe** [comment]
@kijin @bjrambo 아 그렇겠네요. 이 이슈보는 순간 왠지모르게 귀차니즘이 몰려와서 아무 생각없이 달아버렸네요 ㅋㅋ

**Comment by bnu** [comment]
@kijin 님이 가이드 하신 것처럼 krzip 모듈에 적용했습니다.
단순한 치환이지만 아래 커밋을 참고해주세요.

https://github.com/xpressengine/xe-module-krzip/commit/8516c05f8b624ae7f9c5856722744aa82aa8193f

**Comment by kimsijin33** [comment]
타임라인 모듈 설치 후 디비 테이블 생성 후 같은 문제가 생겼는데요
어느파일의 Object 를 BaseObject 로 변경해주면 되나요?

**Comment by Lastorder-DC** [comment]
@kimsijin33 모든 Object를 변경하셔야 합니다. 
에디터의 일괄 치환 기능을 사용시 `new Object`를 `new BaseObject`로 변환하시면 대부분의 오류는 해결되실겁니다.
(단순 Object->BaseObject 변환시 ModuleObject 등도 ModuleBaseObject처럼 바뀌어 오류가 발생할수 있습니다)

p.s.) XE1 개발은 사실상 중단 상태입니다. 이곳보다는 XE타운에 질문하시는게 빠른 답변 받으실수 있습니다.
