### ISSUE TITLE
[1.9.0]카테고리 관리에서 목록 출력 안됩니다.

### ISSUE THREAD

**Issue by phin1000** [xpressengine/xe-core#2185]
ver.1.9.0 에서
게시판관리 > 분류관리에서 분류목록 출력이 안됩니다.
기존 등록된 분류 및 신규 분류 둥록시에도 분류관리에서 분류목록이 출력 안됩니다.

**Comment by bnu** [comment]
관련 부분에 변경이 있었습니다.
해당 게시판의 카테고리 목록을 알 수 있을까요?
글 쓰기 페이지나 목록 상단에는 나오고 있을 겁니다.
페이지 주소를 알려주시거나 주소 공개가 어려우면 카테고리 목록 캡쳐도 괜찮습니다.

**Comment by phin1000** [comment]
https://phiz.kr/tip
관리비 비번도 드려야 하나요?

**Comment by bajjak** [comment]
저도 1.9.0 업그레이드하고 출력이 안됩니다.
1.9.0 따로 새로 설치한 것도 그러네요.
게시판 자체 에서는 분류가 잘나오는데
설정 > 분류관리 > 분류에 리스트가 출려되지 않습니다.
모듈삭제 후 재설치해봤는데도 동일합니다.
