### ISSUE TITLE
"페이지가 작동하지 않습니다" - 1.9.0 업데이트 후

### ISSUE THREAD

**Issue by dcaps001** [xpressengine/xe-core#2186]
HTTP ERROR 500 에러가 발생하며 "페이지가 작동하지 않습니다."라고 뜨네요.

1.9.0 업데이트 후 발생하는 문제네요.

**Comment by bnu** [comment]
changed에 파일이 하나 누락되어 있었습니다.

https://github.com/xpressengine/xe-core/releases/tag/1.9.0
이 페이지에서 '20171201_xe.1.9.0.changed.zip' 이처럼 '20171201' 날짜를 붙인 파일이 문제를 해결하여 다시 올린 파일입니다.
이 파일로 다시 업데이트 하시거나 'BaseObject.class.php' 파일만 따로 올려두었으니 'classes/object/BaseObject.class.php' 위치에 넣으시면 됩니다.
