### ISSUE TITLE
[1.9.0] Object 클래스를 찾을 수 없는 문제

### ISSUE THREAD

**Issue by bajjak** [xpressengine/xe-core#2187]
1.9.0 업그레이드 및 새로 설치를 해도 FAQ 모듈이 동작하지 않습니다.

FAQ 게시판에 들어가면 

Fatal error: Class 'object' not found in /www/ksgm_co_kr/home/Moduels/faq/faq.item.php on line 8

에러가 뜹니다.

XE 설정페이지도 admin 쪽 파일로 에러가 출력되면서 화면이 출력되지 않습니다.

FAQ 모듈 폴더를 삭제하면 정상 동작 합니다.

# 서버 정보
[XE Server Environment 2017-12-01]

realpath : /www/ksgm_co_kr/main
location : ko
package : XE
host : http://www.ksgm.co.kr/main/
app : Apache
xe_version : 1.9.0
php : 5.3.28
db_type : mysql
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, curl, fileinfo, ftp, gd, iconv, mbstring, mcrypt, mssql, mysql, mysqli, pdo_mysql, pdo_sqlite, pgsql, phar, simplexml, soap, sockets, sqlite, exif, sysvsem, sysvshm, xml, xmlreader, xmlwriter, zip, cubrid, oci8, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.1.1), krzip(1.9.0), seo(1.9.0), syndication(6.0.0)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0)
layout : xe_official(1.7), xedition(1.9), xe_kimtajo_layout(2.03), user_layout(1.7)
widget : counter_status(1.7)
widgetstyle : simple(1.7)
max_file_uploads : 20
post_max_size : 20M
memory_limit : 128M

**Comment by bnu** [comment]
classes/config/config.inc.php 파일 하단에 아래와 같은 코드가 있는지 확인해주세요.
`class_alias('BaseObject', 'Object', true);` 이런 코드가 있어야 합니다.
아래와 같지 않으면 해당 파일을 다시 업로드 해보세요.

```php
spl_autoload_register('__xe_autoload');

if(version_compare(PHP_VERSION, '7.2', '<'))
{
	class_alias('BaseObject', 'Object', true);
}

if(file_exists(_XE_PATH_  . '/vendor/autoload.php')) {
	require _XE_PATH_  . '/vendor/autoload.php';
}
```

**Comment by keysung** [comment]
bnu님 안녕하세요, 

참고:
어떤 사이트는 괜찮고, 어떤 사이트는 위와같이 'Object' 클래스를 찾지 못하는군요...
한곳은 php : 5.5.38 이고, 한곳은 php : 5.3.29 인데 문제가 생기는 곳은 php : 5.3.29 버전이 설치된곳입니다.

class_alias() 함수는 php 5.3.0 이상에서 실행인데, php버전이 낮아서 그런가 하고,
php : 5.3.29 사이트에서 위의 class_alias() 함수를 별도로 실행 해보니 실행은 되나 에러가 계속 되는군요.
해서, 아래와 같이 위의 코드중 true를 제거하고 실행을 하니 'Object'클래스가 생성 되는지 에러가 없어지는데... 정확한 이유는 모르겠으나, 현상 파악에 참고가 되지 싶어 글을 올립니다.

수고하세요.
ksc

기존:
class_alias('BaseObject', 'Object', true);
변경:
class_alias('BaseObject', 'Object');


서버 환경은 아래와 같습니다.
[XE Server Environment 2017-12-03]

realpath : /home3/planner/html/xe
location : ko
package : XE
host : http://planner123.raonnet.com/xe/
app : Apache/2.2.17 (Unix) mod_ssl/2.2.17 OpenSSL/0.9.8e-fips-rhel5 PHP/5.3.29
xe_version : 1.9.0
php : 5.3.29
db_type : mysql
use_rewrite : Y
use_db_session : Y
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, calendar, curl, fileinfo, ftp, gd, gettext, gmp, iconv, mbstring, mcrypt, mysql, mysqli, pdo_sqlite, phar, shmop, simplexml, sockets, sqlite, exif, sysvshm, xml, xmlreader, xmlwriter, zip, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.2), bodex(0.9.3), issuetracker(1.2.0), krzip(1.8.0), resource(1.7.0), seo(1.8.20), syndication(5.0.0), wiki(1.7.0.1)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0), php_exif(1.0), stop_spambot_xe(1.0)
layout : XE_layout123_v02(0.2), xe_official(1.7), xedition(1.9), XEgrid_Free(1.0.3), user_layout(1.7)
widget : calendar_plannerXE123(5.4.0), contentextended(2.43), counter_status(1.7)
widgetstyle : simple(1.7), simpleRound(0.1)
max_file_uploads : 20
post_max_size : 80M
memory_limit : 128M

**Comment by bnu** [comment]
@keysung 동일한 5.3.29에서 실험해봤으나 변화는 없었고, (매뉴얼 상으로는) BaseObject 클래스의 autoload에만 영향을 주는 것이라하니 영향은 없을 것 같습니다.
OPcache 등의 영향일 수도 있을 것 같습니다.

@bajjak @keysung 공통적으로 ioncube loader, zend guard loader PHP 확장 모듈이 사용되고 있는데요(같은 호스팅 사 일까요?). 해당 확장이 캐시를 가질 수 있고, 이로 인한 문제일 수 있습니다,

**Comment by keysung** [comment]
bnu님 안녕하세요,

공홈에 올라온글을 보면 'Object' 클래스를 못찾는 에러메시지가 있던데 
문제가 생기는 이유가 php버전이라기 보다는 어쩌면 서버 환경 탓일 수도 있지 싶습니다. 
(묘하게도 위 사이트는 'true'를 제거 했을때는 정상 작동이 되기는 합니다.)

수고하세요.
ksc

**Comment by keysung** [comment]
bnu님 안녕하세요,

와우...!
마침내 해결하셨군요... 수고 많이 하셨습니다.
아마도 서버 사양과 관련이 있지않나 싶은...  좀 까다로운 버그였습니다.^^

ff0e244 로 수정하신 내용을 BaseObject.class.php 와 config.inc.php 파일에 반영하니,
문제가 있던 사이트가 에러메시지 발생없이 홈페이지가 잘 열립니다.  
(다른 사람이 한번 확인을 해주면 좋겠는데... 아마 별 문제 없지 싶습니다..)

년말 즐겁게 보내시고... 새해 복 많이 받으세요.

수고 하셨습니다.
ksc

**Comment by moonboogie** [comment]
같은 호스팅에 2개의 xe를 설치해 보니 현재 운영중인 것은 에러를 내고 단순하게 설치해서 테스트중인 것은 문제 없이 1.9로 업데이트가 되는 것으로 보입니다.

[문제없음]
[XE Server Environment 2017-12-04]

realpath : /home/moonhouse181/www/new
location : ko
package : XE
host : http://moonhouse.co.kr/new/
app : Apache
xe_version : 1.9.0
php : 5.3.3
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, zlib, bz2, calendar, ftp, gettext, gmp, iconv, shmop, simplexml, sockets, exif, xml, bcmath, curl, fileinfo, gd, mbstring, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, phar, soap, sqlite3, wddx, xmlreader, xmlwriter, xsl, zip, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.2), cashpay(2.5.2), currency(2.5.2), cympusadmin(2.5.2), cympuser(2.5.2), epay(2.5.2), epos(1.0), etorrent(0.1), inipaymobile(2.5.2), kcp(2.5.2), krzip(1.8.0), newposts(2.4), nmileage(2.5.2), nstore_digital_contents(2.5.2), paynoty(2.5.2), paypal(2.5.2), seo(1.8.19), sitemanagement(1.0.0), store_search(2.5.2), syndication(5.0.0), textmessage(3.2.1)
addon : adminlogging(1.7), ap_parser(0.3.6), autoattach(1.1.3), captcha_member(1.7), ext_link_new_window(0.2), extkr_signature(0.2), file_attach_button_extend(0.2), message_btn(1.1), multimedia_thumbnail(2.1.0), oembed(1.0), trolley(0.3), web_fonts(1.1)
layout : editorial_xc(0.2), fully(0.5), Mh_Site_Select(1.0), xedition_MH(1.9), xedition(), mh_Lego(1.8), mh_ahn(1.0)
widget : category_menu(1.2), counter_status(1.7), frontdisplay(1.0), ggboardinsert_widget(0.8), mh_Transformer_popup(1.3), mh_appoint(0.1), mh_comment(1.1), mh_hover(1.0), mh_multi(2.1), mh_sliding_banners(0.1.2), mh_sliding_tile(1.0), mh_windows_popup(1.2), scr_webzine_document(0.1), sitemap(0.1.0), tab_newest_document(0.1), tab_newest_image(0.1)
widgetstyle : line(0.1), simple(1.7)
max_file_uploads : 20
post_max_size : 30M
memory_limit : 64M

[문제 발생]
[XE Server Environment 2017-12-04]

realpath : /home/moonhouse181/www/xe
location : ko
package : XE
host : http://moonhouse.co.kr/xe/
app : Apache
xe_version : 1.8.46
php : 5.3.3
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, zlib, bz2, calendar, ftp, gettext, gmp, iconv, shmop, simplexml, sockets, exif, xml, bcmath, curl, fileinfo, gd, mbstring, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, phar, soap, sqlite3, wddx, xmlreader, xmlwriter, xsl, zip, ioncube loader, zend guard loader
module : adminlogging(1.7), automention(1.0), board(1.7.2), board_extend(1.1), contact(1.7.0.2), elfinderxe(0.2), gradeup(1.0.0), guestbook(0.1), imageprocess(2.1.1.1), isx(1.7.4.1), krzip(1.8.0), loginlog(1.4.0), membermemo(0.7), ncenterlite(3.0.3), parserlink(1.1.2), profiler(1.0), referer(3.9.6), seo(1.8.19), sitemanagement(1.0.1), sitemaplite(1.1.1), socialxe(2.2), supercache(1.3.5), syndication(5.0.0), timeline(1.0.2), vicemanager(0.2.0)
addon : SNS_image_submit(1.1), aa_doc_rating(1.0.4), abc_urlshortener(1.1.1), adminlogging(1.7), ap_footnote_editable(0.4), autoattach(1.1.3), bot_challenge(1.0.5), browser_title_lite(0.2), captcha_member(1.7), css3pie_js(1.1.1), ext_link_new_window(0.2), floating_video(0.6.0), hello_member(1.1.0.0), hide_mid(0.1.0), iframe_resize(0.2), jqueryuicdn(1.0), noclick(1.3), oembed(1.0), photoswipe(1.0.1), point_pangpang_plus(0.2b), pr_tooltip(0.1.0), recaptcha(0.2.1), referer(3.5.1), regdate_edit(0.1), show_ncenter_read(0.1.3), web_fonts(1.2), zipperupper(0.3)
layout : Mh_Site_Select(1.1), mh_simple(1.8), mjworks_standardV1(1.0), xe_official(1.7), xedition(1.9), xedition_MH(1.9), mh_Lego(1.8), moonhouse_V2(2.0), mh_only(0.1), user_layout(1.7)
widget : cameronSlider(1.0.2), contentextended(2.45), contentsmedia(0.7), counter_status(1.7), flowing_pictures(1.1.7), ggboardinsert_widget(0.8), ideationBanner(0.1), mh_Ext_JS_popup(0.1), mh_Transformer_popup(2.0), mh_alway_stalker(1.0), mh_appoint(0.1), mh_banner(0.1), mh_c_images(1.0), mh_comment(1.1), mh_hover(2.1), mh_multi(2.1), mh_multi_ch(1.0), mh_popular(1.0), mh_sliding_banners(0.1.2), mh_sliding_tile(1.0), newest_document_tab(0.2), nkoclock(0.1), pado_board_rankingWidget(1.1), scr_webzine_document(0.1), sitemap(0.1.0), tab_newest_document(0.1), webcon_newswidget(1.0.1), webzine(0.1), widget_lightgallery(1.8.19), widget_social_login(1.8.14)
widgetstyle : colorbox(0.1), line(0.1), memo(0.1), mhstyle(2.0), postitWire(0.1), roundFace(0.1), roundWire(0.1), simple(1.7), simpleRound(0.1), simpleSquare(0.1), simpleTitle(0.1), sketchbook5_wincomi(3.0), squareWire(0.1), sweetMobileWidgetStyle(1.7)
max_file_uploads : 20
post_max_size : 30M
memory_limit : 64M

저의 생각은 특정 프로그램의 문제인 것 같기도 합니다.

**Comment by keysung** [comment]
moonboogie 님 안녕하세요,

네, 그렇군요.
혹시 가능하시면 ff0e244 에 수정된 내용을 BaseObject.class.php 와 config.inc.php 파일에 반영하여 
한번 시험 해주실 수 있나요?  제 사이트는 해결 되었는데,  moonboogie님 사이트는 어떨지 모르겠군요.

감사합니다.
ksc

**Comment by moonboogie** [comment]
keysung님 반갑습니다.
수정된 내용 적용하고 나니 아직까지는 Object에러도 안나고 글쓰기 및 수정 삭제 파일첨부 그리고 PlannerXE123도 정상 작동합니다.

감사합니다.

**Comment by keysung** [comment]
moonboogie 님 안녕하세요,

오,,,!  기쁜 소식이군요.
정상작동 된다니 다행입니다.^^
플래너도 조만간 업그레이드를 해서, 문제소지를 아예 없애야 되려나 봅니다.

확인글 감사드리며,  
moonboogie 님도 년말 즐겁게 보내시고 새해 복 많이 받으세요. 
ksc
