### ISSUE TITLE
관리자페이지의 help버튼사용.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#2190]
관리자 페이지의 help 버튼을 사용해서 해당 설정을 할경우 어떤 실행하는 지를 설명하는 부분이 XE에 있지요? 이를 기본값이 숨겨져있습니다.

![_120517_104151_pm](https://user-images.githubusercontent.com/4381756/33610001-7e182b18-da0d-11e7-832b-3338b6dfea4b.jpg)
이런설명들이 있는다고 해서 디자인적으로 전혀 문제가 되지 않는데 굳이 숨겨져있는게 default이기 때문에  XE가 제공하는 방법대로 모듈의 설정페이지를 코딩했을 경우 유저들에게 재대로된 설명을 전달하기가 어렵습니다. (숨겨져있기 때문에..) 그걸 하나하나 눌르면서 설명을 봐야하는 것이 불편합니다.

애드온이던 어디던 기본 설명값이 노출되었으면 좋겠습니다.

**Comment by bnu** [comment]
https://github.com/xpressengine/xe-core/blob/master/modules/admin/tpl/css/admin.bootstrap.css#L537
감춰져 있나요?

**Comment by bjrambo** [comment]
그 클래스와는 상관없이 기본적으로 도움말 버튼이 있을경우 해당 도움말버튼을 클릭해야 나타나도록 되어잇습니다. 

x_help-block 클래스에 자동으로 style="display:none;" 를 자바스크립으로 불러들이도록 되어잇네요.

**Comment by Lastorder-DC** [comment]
![image](https://user-images.githubusercontent.com/18280396/36190478-f9d5b4c6-119b-11e8-9e83-4f06258ad722.png)
![image](https://user-images.githubusercontent.com/18280396/36190482-05085006-119c-11e8-8567-6792f76db1a0.png)

@bjrambo 기본값이 숨김인 도움말이 많아서 그런 것일뿐 기본값은 보여지는 것입니다.

**Comment by bnu** [comment]
설명문의 길이에 따라 나눌 수 있겠지만, 짧은 설명문이라도 반복적으로 보여져야 할 필요성이 없는 설명문도 있네요.
길이에 따라 나눠 판단하기는 모호한 것 같습니다.

메시지의 중요도에 따라 나눠서 기본 상태를 보여지게 하거나, 필요 없는 설명문은 제거하는 것도 좋을 것 같습니다.
더 나은 개선 방법도 머릿속에서 날아다니지만 진행하지는 않겠습니다.

@bjrambo 해당 모듈에서 필요에 따라 hidden 속성과 도움말 버튼을 제거하시면 될 것 같습니다.
