### ISSUE TITLE
외부의 파일을 가져오지 못하는 것 같습니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2191]
https://github.com/poesis/xe-autoattach

1.9.2 업데이트 이후 위 자료를 이용해 사이트 밖의 이미지를 서버로 가져와서 업로드해주는 기능이 동작하지 않고 있습니다. 위 자료에서는 다운로드 실패로 메시지가 남습니다.

그리고 rss로 이미지 + 텍스트를 수집해서 이미지는 저희 서버로가져와 업로드해서 게시글로 완성해 주는 자료에서도 이미지쪽을 저희쪽으로 가져와서 업로드해 주는 기능이 정상적으로 동작하지 않고 있습니다.

FileHandler::getRemoteResource()
위 함수에 문제가 있을 것이라는 이야기를 들었습니다.

**Comment by wookho** [comment]
https://xetown.com/qna/820244#comment_821189

**Comment by bnu** [comment]
fixed #2203
