### ISSUE TITLE
1.9.2 업뎃 후 500에러

### ISSUE THREAD

**Issue by kkang0308** [xpressengine/xe-core#2193]
- 관리자 페이지의 사이트 메뉴 클릭시 500에러
- 관리자 페이지의 사이트 디자인 설정 클릭시 PC/모바일 설정화면은
   나오지만 내용물(레이아웃)이 안보이는 현상
- 모바일 백지화 현상 (메인페이지는 접속 되나 메뉴클릭시 백지화)

**Comment by bnu** [comment]
@kkang0308 
https://github.com/xpressengine/xe-core/releases/tag/1.9.2
서버가 OPcache를 사용하고 있다면 'OPcache 제거 안내' 항목을 참고해주세요.
