### ISSUE TITLE
XE 대시보드 UI 변경 건의도 이슈 가능한가요?

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2201]
XE 대시보드 UI 변경 건의도 이슈 가능한가요?
1. XE 대시보드 UI 변경 
2. 서드파티자료 검색 기능
- 유무료모두 검색가능하게
- RSS 등록 등 특정모듈 상관없이 등록절차 간편해졌으면
3. 대시보드 관리자 첫화면 스킨 기능
4. 대시보드 관리자 첫화면 위젯 추가 기능
- 1.4 버전의 화면이 좋으나, 이 화면으로 돌아가자고 했을 시, 현재 상황에서 반향이 있을 수 있음.
- XE3와 같이 특정 위젯을 사용자가 개발해서 추가 가능하게끔 개발하면 좋겠음.

**Comment by bnu** [comment]
크게 두 가지 이슈로 보입니다.

1. 관리페이지 대시보드 개선 (위젯, 스킨화)
어떤 내용의 요청인지는 대략적이나마 알 것 같습니다.

일반적인 사용에서도 유용하겠지만 제작 후 납품 시 고객 요청 또는 만족도를 높일 수 있는 부분이라 생각하고, 이와 유사한 이유로 요청하신 것이라 생각합니다.

기능의 유용성은 동의하지만 위젯 편집 기능을 대시보드에 붙이기는 간단하지 않으며, 스킨화 또한 마찬가지입니다.


2. 서드파티자료 검색 기능
쉬운설치 기능을 제공하지 않고 단순 링크만 제공하는 형태이더라도 관리 이슈가 발생하는 부분입니다.

데이터를 제공하는 각 사이트 장애 시 관리페이지 접근 지연이 발생할 수 있으며, 자료 제공처를 관리(제공처 등록, 목적 외의 데이터 필터링)해야하는 이슈 등이 발생합니다.

마켓 허브에 등록된 데이터를 활용할 수 있겠으나, 이는 현재 자료실과 별도로 구성되어 있어 관리페이지에서 검색 제공이 원활하지 않을 수 있으며, 관리페이지에서 노출하더라도 자료실의 목록과 별개로 분리되어 제공할 수 밖에 없을 것으로 보입니다.

---

대시보드 개선은 유용성에는 동의하나, 우선 순위를 매우 낮음으로 판단하며,
서드파티 자료 검색 기능은 기능의 구현 외에 운영 이슈가 더 큰 부분이라 도입이 쉽지 않습니다.

두 이슈 모두 처리하기 어렵습니다.

**Comment by eondcom** [comment]
1.4 버전의 UI가 좋아서요. 납품보다는 사용성 측면에서 과거 1.5에서 1.7로 변화되었지만
단순화는 되었지만 실제 사용 측면에서 불편한게 있어서, ^^; 
1.4가 좋은데, 돌아가려면, 또 기존 익숙해진 사용자의 불만이 터져나올거 같고
XE3를 이번에 보니, 위젯을 편집할 수 있는 기능이 추가되어있더라고요.
이 아이디어가 좋을거 같아 건의드려봤습니다.

**Comment by bjrambo** [comment]
1.4 의 버전에서 나름의 불편한 방법이 있었기 때문에 발전을 시킨것으로 보여집니다.

굳이 디자인적인 부분을 건드려서까지 또한번의 변화를 주기엔 너무 어렵습니다...ㅠ

버전업하며 변화된 XE의 관리자 페이지는 이제 더 이상 바꿀필요나 바뀌면서 동작에 대한 UI동작 테스트에 더이상 에너지를 쏟기엔 무리가 있다고 보이고..

또 바뀌게 되면 서드파티 모듈도 거기에 맞게 새로 관리자 페이지의 스크립트를 다 변경해야하기 때문에 이부분까지 신경쓰기엔.. 너무 위험한 부담이 있습니다..(대부분 서드파티의 모듈은 HTML+css으로 관리자 페이지를 XE와 동일한 태그를 이용해서 제작합니다...
