### ISSUE TITLE
프로필 사진 용량 제한 및 확장자 제한하기

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2202]
커뮤니티 사이트에서 트래픽을 잡아먹는 주범으로 프로필 사진이 있습니다.
업로드 용량과 확장자 제한 기능이 없어서, 요즘 10메가 넘는 gif 파일을 올리는 회원이 있습니다. ㅠ
댓글을 달때마다 트래픽이 올라가고, 사람들이 볼 때마다 트래픽 폭탄을 맞습니다.
이 부분 빠른 업데이트 부탁 드려도 될까요? ㅠ_ㅠ
  
https://xetown.com/qna/393105

**Comment by bnu** [comment]
확장자 제한은 gif, png, jpg의 세 종류로 제한되기 때문에 용량 제한 부분만 옵션으로 추가하겠습니다.

용량 제한의 경우 이미지의 크기?사이즈?(dimension) 제한에 따라 리사이즈 과정이 있기 때문에, 리사이즈 된 용량을 기준으로 제한하도록 합니다.

**Comment by bnu** [comment]
이미지 이름, 이미지 마크의 리사이즈가 되지 않을 수 있는 문제도 함께 수정되었습니다.
