### ISSUE TITLE
admin 페이지 문제

### ISSUE THREAD

**Issue by dcaps001** [xpressengine/xe-core#2206]
변경된 파일로만 업데이트 했을 경우 발생하는 문제점입니다.
이 문제는 1.9.2에서부터 발생했습니다. 아래 그림 참고 바랍니다. "페이지가 작동하지 않습니다." 라고 표시됩니다.

![err](https://user-images.githubusercontent.com/18044197/34771914-d100f8ae-f638-11e7-86ac-4576462ca255.jpg)

**Comment by bjrambo** [comment]
500에러는 PHP에러입니다.

단순히 증상만 가지고는 XE팀에서 도움을 드리기가 어려워 보입니다.

어떤 페이지에 접속했는지, 도메인 URL및 기타 정보를 함께 남겨주시면 좋을 것 같아요.

**Comment by dcaps001** [comment]
index.php?module=admin 접속했을 때 발생하는 문제랍니다.
어드민 페이지의 php 문제 인가요?

**Comment by bjrambo** [comment]
변경된 파일이 아닌XE 1.9.2 전체를 업로드 해보시길 권장합니다...

**Comment by dcaps001** [comment]
1.9.3에서도 계속 발생하고 있는 문제구요. 
전체 파일 업로드 하기 힘들어 변경된 파일만 업데이트 하는 중입니다.  변경된 파일이 제공되어 변경된 파일만 업데이트 하는 중입니다.

**Comment by bjrambo** [comment]
변경된 파일만 업로드 하는 경우 해당 파일이 잘못되는 경우도 있어서..(특히 1.9.1->1.9.2 일때 1.9.1에필요한 내용이 누락되는 경우..등) 이런경우가 발생되는 경우가 잇는데

방법은 500에러는 대부분 PHP에러이기 떄문에 PHP에러를 확인할 수 있으면 에러를 알려주지 않으면 아무리 개발자라도 완벽하게 도움을 드릴 수 없습니다.

전체를 업로드 하시는 방법이나.. 아니면 실제 500에러를 나는 PHP에러 로그를 남겨주시면 도와드릴 수 있어요.

500에러는 겉으로는 들어나지 않지만 서버상태에서 아픈 곳이 있어서 뜨는 것이라. 단순히 증상만으로 알 수 없어요. 이유가 수천가지 일 수 있어서 그거 하나하나 다 따지기가 어렵거든요...
