### ISSUE TITLE
대용량 파일 업로드 지원

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2209]
#2109

**Comment by kijin** [comment]
jQuery File Upload를 사용해서 대용량 파일 업로드를 지원하는 브라우저가 있고, 그렇지 않은 브라우저도 있고, 서버의 업로드 용량 제한에 아예 신경을 안 쓸 수는 없고... 고려해야 할 부분이 많습니다.

rhymix/rhymix#663 을 참고하시면 도움이 될 것입니다. 해당 PR에 포함된 코드로서 제가 작성한 것은 모두 LGPL 조건으로 사용할 수 있도록 허가합니다.

**Comment by bnu** [comment]
@kijin 참고하겠습니다 :)
