### ISSUE TITLE
캐시클래스의 isValid() 메소드에서 캐시 삭제까지 하는 이유가 있나요?

### ISSUE THREAD

**Issue by howtoxe** [xpressengine/xe-core#2213]
최근 캐시가 쓰여야하는 작업들을 많이 하게 되다가 나온 이슈인데요, isValid에서 false를 반환하기 전에 캐시 삭제까지 하게 되면서 다음 상황에서 문제가 발생합니다.

보통 isValid에서 유효하면 캐시를 그대로 사용, 유효하지 않으면 ((새로 처리후)) 캐시 저장 및 이 데이터를 반환하는 식으로 개발을 하게 됩니다.

그런데 이 새로 처리하는 과정이 오래 걸리는 경우, 그리고 여러 사용자들이 이 데이터를 요청하는 경우엔, 이미 최초의 isValid에서 캐시가 삭제된 상황이기 때문에 무조건 새로 처리를 하는 문제가 발생하게 됩니다.

궁금해서 찾아보니까 여기까지가 '캐시 스탬피드'라고 하는 현상이더라구요. 그런데 lock 파일을 만들어서 처리중이라는 것을 확인하더라도, 당장 다른 사용자들에게 보여줄 캐시가 없기에 최초의 처리과정이 끝날때까지 무한정 기다려야하는 문제가 발생합니다.

따라서 get, is_readable 함수로 캐시와 lock 파일이 동시에 존재할 경우, 유효성과 상관없이 기존 캐시를 반환하는 방식으로 처리했습니다. 하지만 isValid 메소드에서 검증과 함께 캐시를 삭제하기 때문에, 삭제하는 부분만 제거한 확장 클래스를 만들어서 이를 불러와 써야 했습니다.

굳이 isValid에서 캐시 삭제를 하는 이유가 있는지 궁금하며, 굳이 필수적인 부분이 아니라면 제거해도 괜찮은지 여쭤봅니다.

**Comment by howtoxe** [comment]
@kijin 말씀대로 무의미할 수도 있지만 get 메소드에서는 지금처럼 유효기간이 지난 캐시를 지워주는게 나을 것 같습니다. 

그러나 isValid는 말그대로 유효 여부만 반환하고 그 이상은 안하는게 낫지 않나 하는 제 생각입니다. 그런 차이점이 있다면 isValid도 제가 말씀드린상황같은 경우 쓰임새가 있을 수 있지 않을까요?

파일캐시의 유효기간 지정은 어떤 방법이 있으려나요..

캐시파일명에 추가하는 방법과 캐시파일
내부에서 XE 전역상수 확인하는 다음줄에 넣어서 검사하는 정도가 떠오르긴 하지만 깔끔한 방법인지는 잘 모르겠네요.

전 여기에 더해서 캐시클래스에서 락 관리도 지원하면 좋을 것 같습니다. 파일 잠금이건 lock 파일을 생성하건 캐시 생성중이라는 표식을 하는 방법이 코어에 들어가면 편리할 듯 하네요.

**Comment by kijin** [comment]
@howtoxe 엄밀히 말하면 get에서도 지워줄 필요가 없습니다. 동일한 캐시 키를 서로 다른 $modified_time으로 불러오려고 할 경우 무조건 유효기간이 짧은 쪽을 기준으로 지워지는 부작용이 발생할 테니까요.

그러나 파일 캐시의 경우 어딘가 지워주는 루틴이 없으면 파일이 너무 많이 쌓이는 문제가 있고, 현실적으로 동일한 캐시 키를 서로 다른 $modified_time으로 불러오는 경우는 거의 없기 때문에... 어딘가에서 지워주어야 한다면 get이 가장 적합하겠네요.

아무튼 서드파티 자료 개발자 입장에서 isValid는 그냥 존재하지 않는 메소드라고 생각하시는 게 좋습니다... get이랑 똑같은데 유효한 데이터를 반환하지 않을 뿐이니까요.

파일 캐시는 어차피 serialize해서 저장하기 때문에 유효기간을 함께 넣어서 serialize하고, 불러올 때는 그 시간이 지났는지 확인하는 방식으로 하면 됩니다. ([슈퍼캐시 모듈](https://github.com/poesis/xe-supercache/blob/master/supercache.filedriver.php#L59-L71)에서 자체 구현한 파일 캐시 기능 참고)

락을 걸어놓고 제대로 풀어주지 않으면 오히려 더 큰 문제가 생길 수도 있기 때문에 조심스럽게 접근해야 한다고 생각합니다.

**Comment by howtoxe** [comment]
@kijin 어차피 파일 인클루드해서 시리얼라이즈까지 푼다면 다른 캐시들과 검사 방법이 거진 같아지네요. 유효기간 설정을 하게 된다면 말씀대로 isValid가 굳이 필요없을 것 같다는 생각이 듭니다. 사실 외주나 용역하는 입장에서는 대상 환경이 호스팅이 많아서 파일캐시가 압도적으로 중요하거든요ㅋㅋ

제가 말씀드린 상황같은 경우는 그냥 자체적으로 해결하는 것이 맞을 듯 하네요. 락도 말씀대로 코어에 들어가기는 좀 복잡할 것 같구요. 

혹시 제가 접한 이슈를 겪으신 분들은 이런 방법이 있구나 참고만 하시면 될 것 같습니다.
