### ISSUE TITLE
다국어로 글을 썼을 시 최초 언어셋이 아닌 환경에서는 포인트가 부족해도 글 내용이 열람되는 현상

### ISSUE THREAD

**Issue by howtoxe** [xpressengine/xe-core#2214]
제목이 좀 길어졌네요.. ㅋ 다국어 강의 사이트를 XE로 제작하다가 나온 이슈입니다.

1. 포인트가 부족하면 글 열람 불가하도록 설정

2. 글을 쓰고 언어를 바꾼뒤 글을 수정 (글이 다국어화됨)

3. 최초 언어셋에서는 정상적으로 글 내용이 보이지 않습니다. 그러나 이후에 추가된 다른 언어로 바꾸고 열람해보면 포인트가 부족해도 글 내용이
 보입니다.

이 밖에도 다국어로 쓴 글 내용은 게시판 검색이 안되는 문제 등이 발견되었습니다.

맘같아서는 풀리퀘를 넣고 싶은데 글 관련한 다국어 기능 전반적으로 이런 알려지지 않은 문제들이 있을 것으로 추정됩니다. 따라서 도큐멘트 모듈의 다국어 처리 구조를 바꾸는 수준의 pr이 필요할 수도 있을 듯 합니다.

**Comment by howtoxe** [comment]
관련한 이슈를 경험하신 적이 있으신 분들도 여기에 추가 말씀주시면 좋을 것 같습니다.

**Comment by bnu** [comment]
fixed 9e40434
