### ISSUE TITLE
영어 상태에서 SEO모듈의 이름 및 링크가 나타나지 않음

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2215]
- **증상**
최초 설치 시 영어로 설치한 XE에서 SEO모듈의 관리 페이지 링크 및 설명이 출력되지 않습니다.
영어
![image](https://user-images.githubusercontent.com/20029869/35884402-ed44c0f4-0bcd-11e8-99aa-33111ed047ac.png)
한국어
![image](https://user-images.githubusercontent.com/20029869/35884427-faca9bf4-0bcd-11e8-8901-c71e1d206fd6.png)

- **설치모듈**
    XE 기본 제공 외 설치 안 함

- **추가정보**
   한국어로 설치한 XE에서 act명을 따와 접속하면 되는 문제이나 외국어로 설치 시 불편을 겪을 수 있을 것으로 사료되며 현재는 직접 info를 수정하여 해결했습니다. SEO가 XE-CORE에 포함되어 있어 issue 남깁니다.

**Comment by laiglinne-ff** [comment]
p.s. Trash Module도 현재 multilingual 상태가 들쑥날쑥한 상태네요.

**Comment by bjrambo** [comment]
사실 이런거 XE에 너무많이 있어요..ㅎ

**Comment by bnu** [comment]
fixed #2216
