### ISSUE TITLE
Member Sign Up 화면에서 이름이 긴 항목의 처리

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2217]
- **증상**
![image](https://user-images.githubusercontent.com/20029869/35931647-8e4ff2de-0c78-11e8-811f-64586b6ab1f1.png)
이렇게 잘려보이곤 하는데 꼭 ...로 줄이지 않고 줄바꿈 해줘도 괜찮지 않았을까 싶습니다.

**Comment by laiglinne-ff** [comment]
https://github.com/xpressengine/xe-core/pull/2221/commits/661109b34e74612a660c43c4fe2584ef7e20af42
#2221

**Comment by bnu** [comment]
해결 됨 #2222
