### ISSUE TITLE
회원가입 비활성 시에도 Sign Up 메뉴가 보였으면 좋겠습니다.

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2218]
![image](https://user-images.githubusercontent.com/20029869/35931919-8b890bac-0c79-11e8-9af6-32494cd4df5a.png)
억지로 들어갈 수 있긴 하지만 일반적인 사용자의 경우 간혹 없다고 생각하는 경우가 더러 있어(실제로 들어본 질문) 숨기지 말고 편집 화면 위에 '현재 회원가입을 받고 있지 않습니다' 등의 경고문을 띄우는 것이 UX측면에서 더 좋지 않을까 생각해봅니다.

뭐 예를 들면 이렇게...
![image](https://user-images.githubusercontent.com/20029869/35932469-0503a810-0c7b-11e8-832b-5e00d86522b3.png)

**Comment by kijin** [comment]
가입을 일단 막아놓고 회원가입과 관련된 설정을 변경한 후 다시 가입을 허용하는 워크플로우도 은근히 흔합니다. 가입을 막아놓았다고 설정 변경조차 할 수 없다면 정말 곤란하지요.

https://github.com/xpressengine/xe-core/blob/master/modules/member/tpl/header.html#L15

여기 한 줄만 없애면 회원가입 메뉴가 항상 표시되도록 할 수 있습니다. 소스를 보니 일부러 막아놓은 것 같은데, 대체 무슨 생각이었는지 궁금하네요 ㅎㅎ

**Comment by laiglinne-ff** [comment]
@kijin XE 1.5버전까지는 가입 불가 상태에서도 보여주었던것 같은데 은근 불편하게 하는 부분이더라구요...

뭔가 이유가 있으니 막은것 같긴 한데...ㅠ 개발자야 한두줄 지우면 되는거 아니까 그렇다 쳐도 일반 사용자 단에서는 조금 불편해 보이는...

**Comment by bnu** [comment]
@laiglinne-ff 
회원가입 기능을 비활성화한 것을 잊고 가입 설정만 주구장창 바꿀까봐 감춰둔 것 같습니다.
제안하신 것 처럼 메시지를 표시하는 방법으로 개선할 수 있을 것 같습니다.

**Comment by laiglinne-ff** [comment]
#2221

**Comment by bnu** [comment]
해결 됨 #2223
