### ISSUE TITLE
XE Core 1.9.3 업데이트 후로 관리자 사이트 메뉴가 안보입니다

### ISSUE THREAD

**Issue by kaistac** [xpressengine/xe-core#2219]
XE Core 1.9.3 업데이트 후로 관리자 화면에서 사이트 메뉴가 아무것도 보이지 않습니다.
추가도 안되구요.
여기서 검색해보니 아래와 같은 글이 있어 확인해봤더니 첨부한 이미지처럼 menu_srl이 0인 데이터는 없었습니다.
어떻게 해야 할까요?
바쁘시겠지만 도움 부탁드립니다.
감사합니다.
![xe_menu-menu_srl-db_view](https://user-images.githubusercontent.com/36252960/35954361-8660626c-0ccc-11e8-9386-bb009d48cd9b.jpg)
![admin_site_menu_err](https://user-images.githubusercontent.com/36252960/35954391-b2bcf398-0ccc-11e8-8fa6-3e7ade27f703.jpg)

XE팀에게 받은 메일을 토대로
DB -> xe_menu 테이블을 확인해보니
menu_srl 이 0 인 데이터가 생성되어있어서 해당 데이터를 삭제하니 정상작동..

**Comment by bnu** [comment]
'캐시파일 재생성'을 해보세요.
확인이 가능하시다면 브라우저 콘솔에서 오류가 발생하는지 확인 부탁드립니다.

**Comment by kaistac** [comment]
bnu // 캐시파일 재생성 해봤지만 동일한 증상입니다.
바쁘시겠지만 카카오톡 kaistac@naver.com 으로 도움좀 주시겠어요?ㅠ
팀뷰어나 원격으로......

**Comment by bnu** [comment]
@kaistac 개별 메신저, 원격지원 등으로 확인하지 않습니다.
새로운 최고관리자로 계정을 추가하여 공유해주시면 사이트에서 확인해보겠습니다.
