### ISSUE TITLE
Menu Editor와 Site Design의 XE_VALIDATE_MESSAGE 의도하신 사항인가요...?

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2220]
![image](https://user-images.githubusercontent.com/20029869/36068012-58a02120-0f0e-11e8-8a20-7264762ee6fa.png)

Menu Editor와 Site Design에서 이렇게 보이는것 같은데...

https://github.com/xpressengine/xe-core/blob/81845919fcf2fce46d3b809ec8ab4782850f2a09/modules/menu/tpl/sitemap.html#L5-L7

**Comment by misol** [comment]
오류 메시지가 반환되면 값이 입력됩니다.

**Comment by laiglinne-ff** [comment]
@misol 어... 그게 아니고 그냥 저게 저렇게 출력돼요 원래대로면 cond=""는 tmpl 생성하면서 숨겨져야 하는것 아닌가요 ? ?...

**Comment by laiglinne-ff** [comment]
https://github.com/xpressengine/xe-core/pull/2221/commits/950da757126b8109ce0b99985023063f01f65532

**Comment by bnu** [comment]
템플릿 파서가 가끔 문제를 일으키는데, 관련한 문제로 보이네요.
#2224 PR로 해결될 수도 있으나 환경에 따라 문제가 다시 또는 새롭게 나타날 수 있을 것 같습니다.

**Comment by bjrambo** [comment]
@bnu 임시로 바꿔서 해결되는것 같습니다.

근본적인 템플릿 파서쪽을 확실히 원인을 잡으셔야할 것 같아요..

일부 cond 많이 사용되거나 PHP언어 환경을 많이 구축된 위젯을 사용하다 보면 위젯 생성시에도 에러 나는 경우가 있고요,스킨단에서 따로 클래스 구별을 위한 기능도 재대로 작동하지 않는 경우도 있습니다.

**Comment by laiglinne-ff** [comment]
가장 간단하게 재현하는건 그냥 <?PHP ?>로 조건문만 몇번 걸어도 cond 조건 걸어둔걸 파싱을 제대로 못하더군요. 뭐 사실 레이아웃 내에 <?PHP ?>를 안쓰는게 맞긴 하지만 . . .

**Comment by kijin** [comment]
혹시 사용하시는 서버의 php.ini에서 `pcre.recursion_limit` 설정이 어떻게 되어 있나요? 대개 10만~100만 사이로 되어 있습니다만 이 값이 낮으면 일부 템플릿이 제대로 파싱되지 않는 문제가 있더군요.

**Comment by laiglinne-ff** [comment]
@kijin 수정하고 다시 테스트 해보겠습니다.

**Comment by laiglinne-ff** [comment]
```
[XE Server Environment 2018-02-24]

realpath : 
location : ko
package : XE
host : 
app : nginx/1.10.3
xe_version : 1.9.3
php : 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
db_type : mysqli_innodb
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, libxml, openssl, zlib, sodium, cgi-fcgi, mysqlnd, xml, calendar, mbstring, fileinfo, ftp, gd, gettext, iconv, exif, mysqli, pdo_mysql, phar, readline, shmop, simplexml, sockets, sysvmsg, sysvsem, sysvshm, wddx, xmlreader, xmlwriter, xsl, zip, zend opcache
module : adminlogging(1.7), board(1.7.2), krzip(1.9.0), seo(1.9.0), syndication(6.0.0)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0)
layout : xe_official(1.7), srnxe(1.9), xedition(1.9), user_layout(1.7)
widget : counter_status(1.7)
widgetstyle : simple(1.7)
max_file_uploads : 20
post_max_size : 64M
memory_limit : 1024M
```
