### ISSUE TITLE
1.9.3 버전 설치 이후 게시판 설정의 분류 표시 문제

### ISSUE THREAD

**Issue by inf053c** [xpressengine/xe-core#2225]
![1](https://user-images.githubusercontent.com/36668535/36429740-6a9a39e4-164b-11e8-9a86-ddc109d60918.PNG)

http://infosectimes.com

ID : test PASS : test

1.9.3 설치 이후 게시판 설정의 분류 표시가 나타나지 않고 있으며 이후 다른 버전을 설치해도 문제가 지속되고 있습니다.

**Comment by laiglinne-ff** [comment]
Apache가 아닌 Nginx에서 동일 환경 테스트 결과 정상 출력되고 있습니다.

확인해보니 분류 자체를 출력을 못할 뿐 정상적으로 동작은 하고 있는것 같습니다.

` 테스트 : `
![image](https://user-images.githubusercontent.com/20029869/36459296-8f39cade-16f6-11e8-8c94-90992a75999b.png)

files 폴더의 권한을 먼저 확인해보시고 
동일한 증상 발생 시 module/document/ 및 module/board 폴더에 다시 원본을 덮어씌워보세요...

**Comment by inf053c** [comment]
알려주신바와 같이 사이트 디자인에 해당 코드를 하단에 붙여보았으나,
분류가 나오지 않습니다.

http://infosectimes.com/index.php?mid=board&act=dispBoardAdminCategoryInfo

ID : test PASS : test

![1](https://user-images.githubusercontent.com/36668535/36465997-c93afac2-16cf-11e8-8162-4e1b59a89696.PNG)


물론, files 폴더 권한을 707로 변경해보고
module/document , module/board 폴더를 원본으로 다시 덮어보았습니다만

계속적으로 안되고 있습니다.

**Comment by inf053c** [comment]
cafe24 안팅웹셀이 문제였던것 같습니다.

해결하였습니다.
