### ISSUE TITLE
갑자기 관리자에서 사이트메뉴편집 및 사이트 디자인설정 메뉴 클릭시 아무것도 안나옵니다.

### ISSUE THREAD

**Issue by sayedit** [xpressengine/xe-core#2226]
서버 정보는 다음과 같습니다. 

[XE Server Environment 2018-02-21]

realpath : /home/user/start1/public_html/www
location : ko
package : XE
host : http://start1.12345.co.kr/www/
app : Apache
xe_version : 1.8.27
php : 5.3.3
db_type : mysql
use_rewrite : N
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, zlib, bz2, calendar, ftp, gettext, gmp, iconv, shmop, simplexml, sockets, exif, xml, curl, fileinfo, gd, mbstring, mysql, mysqli, pdo_mysql, pdo_sqlite, phar, zip
module : adminlogging(1.7), analysis(0.1.2), analytics(1.0.1), board(1.7.2), krzip(1.8.0), multidomain(1.3.1), pointhistory(0.1.4), referer(3.8.2), seo(1.8.19), statistics(1.0.1 Beta), stats(1.1.1), syndication(5.0.0), umessage(0.3)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0)
layout : doorweb_v4(1.7), hestia(2.1.4), modern_line(1.0), s4us_1.0(1.0), saturn_portal(1.12), smart(1.4.6), kia(0.1), seven(1.2), xdt_offical_2(1.4), freelancer(1.0), xe_official(1.7), xedition(1.9), xe_kimtajo_layout(2.03), xet_onecolor(1.0.5), nabul2_milate_8T(2.0), eond_official(1.4.1), xecenter(1.3.7), user_layout(1.7), portal_ever(1.2.1), portal_NEO(1.1.6), miku_daisuki(1.0)
widget : GPEneo_Popularity(0.0), GPEneo_Rpoint(0.0), GPEneo_content(0.0), cameronSlider(1.0.2), counter_status(1.7), maps_widget(1.1.2), (), treasurej_popular(1.0.5)
widgetstyle : gpeNEO_ws_de(0.0), lineBox(0.1), memo(0.1), nico(1.2), simple(1.7), sweetMobileWidgetStyle(1.7), xe_official(1.0)
max_file_uploads : 20
post_max_size : 10M
memory_limit : 128M

![image](https://user-images.githubusercontent.com/13535671/36472411-16f71dda-1735-11e8-9781-b12b80499a9a.png)

![image](https://user-images.githubusercontent.com/13535671/36472419-1b8bd624-1735-11e8-8c7b-3254889cadd5.png)

갑자기 안나옵니다.

**Comment by sayedit** [comment]
bnu@xpressengine.com
으로 계정정보, 관리자 정보도 보내드렸습니다. 
부탁드리겠습니다. 도통 이유를 모르겠습니다.

**Comment by bnu** [comment]
@sayedit 설치하신 모듈/애드온에서 문제를 일으키는 것으로 확인했습니다.
