### ISSUE TITLE
일부 Cookie를 HTTP Only로 변경

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2230]

**Comment by kijin** [comment]
세션과 관련된 쿠키에 secure, httpOnly 등의 속성을 추가하면 안드로이드 푸시앱 등 일부 서드파티 자료가 오작동한다는 제보가 있으니 참고하시기 바랍니다.

**Comment by bnu** [comment]
앱에서 기술적으로 해결할 수 있는 문제일 것 같지만, 호환성 문제는 피할 수 없겠네요.
CSRF 토큰도 마찬가지일테고요.

어렵군요.
그럼에도 불구하고 진행하는 것이 맞다는 생각입니다.
옵션으로 비활성할 수 있게 해야할까요...

**Comment by kijin** [comment]
원하는 사람은 php.ini를 수정해서 쓰면 됩니다. XE 쪽에서 ini_set으로 세션 쿠키 속성을 건드리면 XE를 서브폴더에 설치하고 다른 프로그램과 세션을 공유하는 사이트에서 문제가 생길 수 있습니다. 폴더 내에서 생성한 쿠키와 루트에서 생성한 쿠키의 속성이 서로 다르면 우선순위가 꼬이는 것은 푸시앱 뿐 아니라 일부 PC용 브라우저도 마찬가지였던 것으로 기억합니다. 안정적으로 운용하려면 속성이 다른 쿠키를 찾아서 먼저 지워주고 새 쿠키를 굽는 등 복잡한 과정이 필요하더군요.

그리고 이게 그누보드도 아니고;;; setcookie 함수를 쓰는 게 그렇게 어려운 것도 아닌데 굳이 wrapper function을 경유하는 것도 개발자들에게는 오히려 혼란만 주지 않을까요.

CSRF 토큰도 exec_xml, exec_json, 그 밖에 임의로 form을 만들어 쓰거나 AJAX 요청을 보내는 모든 서드파티 자료의 정상 작동을 보장할 수 없으면 난리가 납니다. 결국 자바스크립트로 토큰을 이리저리 주고받도록 구현해야 하는데, 그러다 보니 "이렇게 토큰값에 쉽게 접근할 수 있도록 해놓으면 기존의 리퍼러 체크로도 충분히 막을 수 있는 공격 외에는 마찬가지로 다 뚫리는 거 아닌가" 하는 생각까지 들더군요. ㅜㅜ

세션 보안 강화 기능과 CSRF 토큰 두 가지 모두 제가 전에 배포했던 세션 쉴드 애드온은 물론이고, 라이믹스에도 기본 탑재되어 있는 기능입니다만... 실제 사이트 운영자분들이 겪는 여러 가지 문제들을 함께 고민하다 보니 결국 기본값이 off가 되었습니다. 이번 기회에 확실한 해결책을 마련할 수 있다면 좋겠지만, 확실하지 않다면 신중하게 진행해 주시기 바랍니다. 이론상으로는 간단한데 실제로는 전혀 그렇지 않은 대표적인 케이스입니다....

**Comment by bnu** [comment]
- 토큰은 이미 페이지에 노출되고 있으며, 이 토큰을 다루는 방법의 쉽고 어렵고는 문제가 아닙니다
- 토큰이 외부에 노출될 수 있다면 이미 공격을 받을 수 있는 상황이었겠죠. 그건 거기서 해결해야 할 문제입니다.
- 이것은 확실한 해결책이란 게 없겠죠. 이미 운영중인 상태에서 이런 변화는 호환성 문제를 야기하며, 개별 대응이 필요함은 예상하고 있습니다.
- saveCookie는 secure 옵션 적용을 위해 추가하여 사용했습니다
- 필요하다면 비활성 옵션을 사용할 수 있도록 하겠습니다.

**Comment by bnu** [comment]
릴리즈 취소. 이슈 종료.
