### ISSUE TITLE
$.xe.CKEditor is not a function

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2233]
- develop 마지막 커밋에서 CKEditor 출력 오류가 발생했습니다.

https://github.com/xpressengine/xe-core/blob/eebdf0755a949a4d10384a5510395f9c119312ab/modules/editor/skins/ckeditor/editor.html#L99

![image](https://user-images.githubusercontent.com/20029869/36879312-6c3e2144-1e06-11e8-901d-be616f0934c0.png)

![image](https://user-images.githubusercontent.com/20029869/36879319-747a4ca2-1e06-11e8-8d89-f65a5ea48816.png)

**Comment by bnu** [comment]
개발 환경으로 전환하시거나 99de18c 커밋으로 확인해주세요.
