### ISSUE TITLE
CSRF 커밋 이후 모든 POST 403

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2234]
- CSRF 커밋 이후에 POST 로 전송하는 모든 값이 403을 반환합니다.

https://github.com/xpressengine/xe-core/blob/eebdf0755a949a4d10384a5510395f9c119312ab/config/func.inc.php#L1645-L1649

![honeycam 2018-03-02 10-54-05](https://user-images.githubusercontent.com/20029869/36879747-94015de8-1e08-11e8-87b2-20165f33b37a.gif)

**Comment by bnu** [comment]
develop 브랜치는 빌드되지 않은 스크립트 환경에서 동작할 수 있습니다.
빌드되지 않은 원본의 스크립트가 적용되는 환경.. 개발 모드로 설정할 수 있습니다.

99de18c 커밋으로 확인해주세요.

config/config.user.inc.php
```php
define('__DEBUG__', 1);
```

**Comment by laiglinne-ff** [comment]
@bnu debug 모드로 전환 후 마지막 커밋에서 확인해보겠습니다.

**Comment by bnu** [comment]
확인 감사합니다.
