### ISSUE TITLE
업데이트된 문서 파일 관리 부분 UX

### ISSUE THREAD

**Issue by lalafellsleep** [xpressengine/xe-core#2235]
사용해보니 조금 불편한 감이 없잖아 있습니다.

아래처럼 개선되면 좋을 것 같습니다. 서드파티로도 충분히 개선될 수 있지만

오리지널의 UX도 높아야 한다고 생각합니다.

![image](https://user-images.githubusercontent.com/20029869/36889492-88b9df98-1e3d-11e8-9adb-464758a8bc28.png)

위 그림처럼 개별적으로 본문에 추가할 수 있도록 한다면 좋을 것 같습니다.

**Comment by bnu** [comment]
업로더는 아래 이미지와 같이 develop에 적용되어 있습니다.
![2018-03-09 10 59 54](https://user-images.githubusercontent.com/53764/37186496-26bd053a-2389-11e8-9ebf-dcdb1d14a9c9.png)

좀 더 다듬고 있습니다.

**Comment by laiglinne-ff** [comment]
오... 괜찮네요 👍

**Comment by bnu** [comment]
릴리즈 취소로 이슈 종료합니다.
