### ISSUE TITLE
일반회원이 동영상 올릴때 옵션이 제거되는 문제

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2236]
allowfullscreen="" 

mozallowfullscreen=""

webkitallowfullscreen="

이러한 것들이 제거되어 최고관리자가 아닌 회원이 등록한 영상의 경우 전체화면보기로 영상을 볼 수 없습니다.

XE사이트에 올라온 영상만 지원지하지 않는다고 하면 사이트의 평가가 좋지 않을 것 같습니다.

**Comment by kijin** [comment]
mozallowfullscreen과 webkitallowfullscreen은 웹표준이 정해지기 전에 구버전 크롬과 파폭에서 임시로 사용하던 속성이므로 더이상 필요하지 않고, 이제는 allowfullscreen만 지원하면 될 것 같습니다.

**Comment by wookho** [comment]
@kijin 네. 위 예시는 커뮤니티에서 질문글을 올리신 분이 말씀 하신 옵션이구요.
allowfullscreen 지원이 안되는게 큰 문제 같습니다. 지금 회원이 올린 영상 일일히 수정해 주고 있네요.

**Comment by kijin** [comment]
참고하세요: https://github.com/rhymix/rhymix/blob/master/common/framework/filters/htmlfilter.php#L267

**Comment by wookho** [comment]
@kijin XE의 어떤 파일에 추가해야 할지 찾기 어렵네요.
