### ISSUE TITLE
2229 이슈 처리 중 컬럼 추가 등이 잘못된 문제

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2238]

**Comment by wookho** [comment]
어제 1.9.4 업데이트 직후 관리자페이지에서 editor 업데이트가 떴는데 이것 때문인가요? 큰 지장을 주지는 않겠죠?

**Comment by bnu** [comment]
@wookho editor 모듈의 업데이트가 있는 게 정상이고, 문제를 일으키는 내용은 아닙니다.
