### ISSUE TITLE
editor 관련 수정사항이 정상적으로 진행되지 않습니다.

### ISSUE THREAD

**Issue by laiglinne-ff** [xpressengine/xe-core#2240]
![image](https://user-images.githubusercontent.com/20029869/37085836-6d90e2b6-2239-11e8-8e99-b03cdf4d6ad6.png)

editor의 테이블이 정상적으로 업데이트 되었으나 

https://github.com/xpressengine/xe-core/blob/af74fafdbb70c919fd7afad5cf7cf3f000e44b21/modules/editor/editor.class.php#L125

에서 오류가 발생하면서 계속 화면에 남아있는 문제가 있습니다...

![image](https://user-images.githubusercontent.com/20029869/37085980-ce5d5d68-2239-11e8-8343-2feb26332c0c.png)

**Comment by laiglinne-ff** [comment]
Uncaught ArgumentCountError: Too few arguments to function DBMysql::addIndex(), 2 passed in / . . . /editor.class.php on line 125 and at least 3 expected in / . . . /classes/db/DBMysql.class.php:383

**Comment by bnu** [comment]
TT

**Comment by bnu** [comment]
1e8fbef

**Comment by bnu** [comment]
@laiglinne-ff 감사합니다 👍
