### ISSUE TITLE
1.10 릴리즈 취소 및 롤백으로인한 영향 점검

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2245]

**Comment by yohan666** [comment]
허얼... 어쩌시다가 ㅠㅠ

**Comment by lalafellsleep** [comment]
엥? 왜 취소되었나요? 뭔가 이유를 설명해주지 않으면 또 유저들이 불만들 토로하지 않을까요...

**Comment by bnu** [comment]
1.10은 다소 호환성을 깨는 부분이 있었습니다.
이에 대해 지켜보시는 분들의 우려가 있어서 1.10에 포함된 이슈와 릴리즈 계획을 취소했습니다.
1.9.x는 기존과 같이 버그, 보안 취약점 위주로 업데이트 예정입니다.

호환성과 직접 관련이 없는 업로더 개선과 같은 이슈 또한 jQuery UI 업데이트가 필요한 부분이어서 함께 취소했습니다.

**Comment by lalafellsleep** [comment]
우선 실사용중인 개발용 페이지에 적용 후 문제가 발생하는지 체크해 보겠습니다
