### ISSUE TITLE
admin 페이지 접근불가

### ISSUE THREAD

**Issue by mkjang2000** [xpressengine/xe-core#2247]
관리자 로그인후 관리 페이지 접근시 다음오류를 출력하며 접속되지 않습니다

Fatal error: Call to a member function getAction() on a non-object in /home/hosting_users/dongeunchuchkr/www/classes/db/DB.class.php on line 629

https://dongeunchurch.kr/index.php?module=admin

**Comment by bnu** [comment]
업데이트 시 파일이 제대로 교체되지 않았거나 OPCache 등으로 인한 문제로 보입니다.
