### ISSUE TITLE
NginX rewrite_mod 지원여부 체크 오류

### ISSUE THREAD

**Issue by bonik21** [xpressengine/xe-core#2248]
[https://github.com/xpressengine/xe-core/wiki/Nginx-rewite-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0](url)

NginX서버를 사용중입니다. 위 내용을 보고 rewrite을 적용시켰는데 XE관리자 화면에서 '짧은 주소 사용불가'로 나옵니다.
그치만 짧은 주소 사용에 체크하면 실제로 짧은 주소 적용은 잘되고 있고 실 사용에 문제가 없습니다.
아마 XE가 서버의 환경을 제대로 읽어오질 못하는 것 같습니다.
처음에는 서버의 문제라고 파악해서 별짓 다 해봤는데도 안되서 이슈 등록하게 됐습니다.
혹시 테스트할만한 내용이 있다면 테스트 해보도록 하겠습니다.

   OS : 데비안 stretch (Chroot) (DB와의 연결은 127.0.0.1이용 불가능, Localhost로 연결해야함)

    PHPmyadmin에서 확인한 서버 내용 
    nginx/1.10.3
    데이터베이스 클라이언트 버전: libmysql - mysqlnd 5.0.12-dev - 20150407
    PHP 확장: mysqli문서 curl문서 mbstring문서
    PHP 버전: 7.0.27-0+deb9u1

**Comment by bnu** [comment]
rewrite 설정을 테스트할 때 'files/config' 폴더에 파일을 생성하는 과정이 있습니다(확인 후 삭제 됨).
이 폴더의 권한이 없거나 해당 파일이 이미 존재한채로 권한 문제가 있지 않은지 확인해보세요.
동일한 환경은 아니지만 문제를 확인할 수 없었습니다(정상 동작)
