### ISSUE TITLE
관리자 사이트맵 바로가기 메뉴를 복사 붙여넣기 했을 경우 &...

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2257]
관리자 사이트맵에서 바로가기 메뉴를 복사 후 붙여넣기 했을 경우 `&`가 포함되어있으면
`&`가 `&amp;`로 변환되어 저장이 됩니다. 바로가기 메뉴에 `&`가 있을 경우 붙여넣기 했을 때도 동일하게 적용되면 좋겠습니다.

**Comment by Lastorder-DC** [comment]
`&amp`가 `&`로 바뀐다는 건가요 아니면 `&`가 `&amp`로 바뀐다는 건가요? Github에 엔티티 문자를 그대로 넣으시면 자동변환되서 `로 감싸서 넣어주셔야 합니다.
