### ISSUE TITLE
게시판 관리 기능이 제대로 작동이 안되는 문제

### ISSUE THREAD

**Issue by E-nuri** [xpressengine/xe-core#2258]
1.7.7.2 버전이 적용된 페이지를 수정하려합니다.

게시판 관리 메뉴에서 GA(Google Analytics) 스크립트 코드를 **상단 내용**에 붙여넣기 후 **등록** 버튼을 눌렀으나 반영이 안됩니다.
하지만 `success_updated`라는 팝업은 뜹니다.

**상단 내용**, **하단 내용**뿐만 아니라 다른 메뉴(모바일 설정 등)을 변경 후 **등록**버튼을 눌러도 `success_updated` 팝업만 뜰 뿐 반영이 안됩니다.

메뉴가 약 30여개되는데 절반정도는 정상적으로 작동하고 절반정도는 비정상적으로 작동합니다.

혹시 참고할 문서가 있을까요?

**Comment by bnu** [comment]
일반 사용에 관한 질문은 https://www.xpressengine.com/qna 게시판을 이용해주세요.
