### ISSUE TITLE
글자가 없는 <a> 태그, 위지윅 에디터 모드에서 자동 삭제 문제

### ISSUE THREAD

**Issue by jun7051** [xpressengine/xe-core#2273]
등록된 문서 소스 보기를 하면 스팸 관련 소스가 보이지 않는 정상문서로 보이지만 웹브라우져 소스보기를 하면 검색사이트 연결 링크 점수를 높이기 위한 특정 페이지 링크 ( 토토 사이트 )가  보여집니다.

구글 검색을 돌려보면 많은 수의 xe 사이트에 동일 유형의 게시물이 퍼져 있는데 대부분 운영자들이 알아채지 못한 채 방치가 되고 있습니다. 운영자가 등록되는 모든 게시물을 일일이 확인 하기에는 문제가 있어보이는데  가급적 개선이 되었으면 합니다.

자세한 내용은 아래 링크를 참고 해주세요.
https://xetown.com/board/1014400 

"확인해보니, 긑자가 없는 <a> 태그는 위지윅 에디터 모드에서 자동 삭제되는 것으로 확인되었습니다.
따라서 악성코드에 의한 이상이 아닙니다. 그냥 에디터의 [소스] 모드에서 붙여넣고 등록하면 그렇게 되는 것을 확인하였습니다."

" 이건 에디터의 문제이긴 보단 코어단에서 방어해야 될 겁니다. "

**Comment by kijin** [comment]
42d5a3b 이렇게 하면 폰트어썸이나 XEIcon에서 사용되는 `<i>` 태그도 날아가지 않나요? 서드파티 자료에서 특별한 효과를 줄 위치를 지정하기 위해 중간에 끼워넣는 `<span>`이나 `<div>`도 내용이 없으면 모두 지워질 테고요. 문서를 에디터에서만 작성하는 게 아니잖아요.

스패머 하나 잡자고 집을 다 엎지는 말아요. 만약 제가 스패머라면 이 커밋이 적용된 후에도 눈에 잘 보이지 않는 유니코드 문자 하나씩 집어넣고 계속 스팸질하겠습니다.

**Comment by Lastorder-DC** [comment]
1. 현재 설정으로는 `<p>&nbsp;</p>`를 막을수 없습니다. 이는 별도 설정인 `AutoFormat.RemoveEmpty.RemoveNbsp`까지 활성화시켜야 합니다.
1. 설사 위 설정까지 활성화시킨다고 해도  `<a href="https://example.com"><img src="./1x1.gif"></a>` 와 같은 방법은 막을 수 없습니다.(1x1짜리 이미지니 잘 보이지 않겠죠)
1. @kijin 님이 언급하셨듯이 정상적인 HTML 코드까지 필터링될수 있습니다.
