### ISSUE TITLE
통합검색 DB 제한 관련 

### ISSUE THREAD

**Issue by choowolms** [xpressengine/xe-core#2274]
안녕하세요 !!

글이 500,000개쯤 되니까 원하는 검색이 바로바로 안되고 '계속 검색' 기능을 이용해야 합니다.

바로바로 검색이 되게끔 할수 있는 방법이 없을까요?

**Comment by Lastorder-DC** [comment]
검색시 발생하는 부하 때문에 나누어 검색하는것으로, 한번에 검색이 되게 하시려면 Sphinx 등 별도 검색엔진과 연동 작업을 하셔야 합니다.

**Comment by bnu** [comment]
성능 유지를 위해 검색 범위가 제한/분할되어 동작합니다.
