### ISSUE TITLE
jQuery UI의 버전 1.12.1 반영필요

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2275]
러이믹스와 차이로 인해 서드파티에서
라이믹와 XE에서 동작 불능의 경우가 생깁니다.

https://xetown.com/board/854712

**Comment by Lastorder-DC** [comment]
1.10에서 업데이트가 예정되어 있었으나 1.10 자체가 취소되면서 업데이트도 취소되었습니다.
#2197 에서 업데이트가 되었던것을 확인할수 있습니다.

**Comment by wookho** [comment]
@Lasorder-DC 그렇지 않습니다. 어떠한 이유인지 실제 배포시에는 해당 내용이 반영되지 않았습니다.
https://xetown.com/board/854712

실제로 이 문제로 서드파티에서 문제가 되고 있습니다. 라이믹스는 동작 XE는 미동작

**Comment by wookho** [comment]
@Lastorder-DC 그렇지 않습니다. 어떠한 이유인지 실제 배포시에는 해당 내용이 반영되지 않았습니다.
https://xetown.com/board/854712

실제로 이 문제로 서드파티에서 문제가 되고 있습니다. 라이믹스는 동작 XE는 미동작

**Comment by bjrambo** [comment]
@wookho 처음 업데이트가 되었다가 취소되었다는 것을 말씀하신것 같아요. (업데이트는 했었긴한거죠.)

@Lastorder-DC 님께서 말씀해주신 내용이 바로 취소되었었지만 #2197 에서 업데이트가 되었었던 것을 확인할 수 있다 라고 말씀하셨던 것입니다. (즉 코드는 반영되었엇다가 다시 코드를 되돌린 것입니다.) 

```
1.10에서 업데이트가 예정되어 있었으나 1.10 자체가 취소되면서 업데이트도 취소되었습니다.
```

**Comment by wookho** [comment]
네. 대화에 약간의 전달이 안된 부분이 있었던것 같네요.
어찌되었던 취소가 된 패치인데 1.9.3 배포시에는 이 내용이 반영되었다고 공지까지 있었으니 개발팀에서 오해가 있는듯 합니다.

다시 반영이 필요한 부분이라 이슈 등록했습니다.

**Comment by bnu** [comment]
혼란을 드려서 죄송합니다.
브랜치를 이동하면서 코드 누락이나 내역이 잘못 추가되었던 것 같습니다.
jQuery UI 1.12.1 버전을 적용하여 배포하도록 하겠습니다.
