### ISSUE TITLE
travis 검사 정리 하시는게 어떨까요?

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xe-core#2277]
이제 XE는 PHP 5.6 이상 지원을 목표이므로 불필요한 php5.3, 5.4, 5.5 유닛테스트는 지우고 

5.6, 7.0, 7.1,7.2 를 검사합시다!

**Comment by bnu** [comment]
해당 내용은 취소 되었습니다.
https://www.xpressengine.com/devlog/23254107
