### ISSUE TITLE
콘텐츠 내 링크에 대한 nofollow 적용

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#2278]
document, comment 등 불특정 다수가 작성하는 콘텐츠의 링크에 nofollow 적용

- 스팸 콘텐츠의 외부 링크로 인한 사이트의 신뢰도 개선
- 전체 게시판을 대상으로 활성화 상태를 초기 값으로 함
- admin 제외
  - 관리자만 제외하는 것 이상의 비대상 회원 및 범위를 구분 짓는 것은 기능 추가 대비 효과를 기대할 수 없음
- 이 변경이 어떠한 영향을 미치지 않으므로 사이트 신뢰 개선만 목적으로 함

related #2273

**Comment by dailyworker** [comment]
이전에 레거시한 XE기반 게시판을 1.11.2로 업그레이드하면서 

Fatal error: Call to undefined method Purifier::setConfig() in /var/www/html/zbxe/config/func.inc.php on line 1111 이러한 에러가 발생하는데 혹시 해결방법이 어떻게 되나요? 

어드민 혹은 기타 계정 로그인을 하면 메인페이지가 나오나, 로그인을 안했을 시에는 해당 에러가 출력됩니다.
