### ISSUE TITLE
다국어(영문) 확장변수로 날짜 받을때 형식에러

### ISSUE THREAD

**Issue by 1ocate** [xpressengine/xe-core#2282]
안녕하세요 처음 글을 쓰게 되어서 이렇게 작성하는 것지 모르겠습니다.

xe 1.9.6 버전 사용중이다가  1.9.8 버전 쉬운설치로 업데이트 가능하여 업데이트 하였습니다.

이후 다국어(영어)로 열린 페이지에서 게시판글 작성할때  확장변수로 년월일 일자 받는 달력을 클릭해서 받게 되면

값을 MM/DD/YYYY 형식으로 받아 저장하게 되는데  출력은 Jun 19, 10 이런식으로 표기됩니다.

<input type="hidden" name="extra_vars10" value="06/11/1994">

게시판 수정으로 해서 보면 실 데이터는 06/11/1994 이런식으로 들어갑니다.
한국어 페이지에서는 19940611로 제대로 값이 들어가고 있습니다.

현재 /xe/common/js/plugins/ui  항목을 이전 1.9.6버전으로 가져와서 사용하니 문제 없습니다.

jquery ui가 업데이트 된건지, 혹은 제가 쉬운 설치로 설치해서 그런지 확신이 안서서 일단 이슈에 올렸습니다.

확인 부탁드립니다.

늘 감사합니다.

**Comment by Lastorder-DC** [comment]
최근 jquery ui 버전이 업데이트되었는데 이로 인한 것으로 보입니다.

@bnu

**Comment by bnu** [comment]
어떤 이유에선지 날짜 포맷이 적용되지 않아 날짜 포맷 옵션을 다시 조정하도록 변경하여 해결했습니다.

**Comment by 1ocate** [comment]
반영 감사합니다.

이외에 zdate 함수로 확장변수 출력시에 다국어 페이지에서 다르게 출력되는게 정상인가요?

2018-06-08 이라는 날짜를 ExtraVar1확장변수로 입력받았고

zdate 함수결과물이 아래와 같이 언어마다 다르게 출력됩니다.
{zdate($item->getExtraVar1(),'Y-m-d')}

한국어 페이지에서는  결과물이 2018-06-08
영문 페이지에서는 Jun 00, 0 이렇게 출력됩니다.

**Comment by bnu** [comment]
@1ocate `zdate` 함수는 포맷을 지정하더라도 해당 언어에 맞게 변경되어 출력됩니다.

변경을 원하지 않으시는 경우 다음과 같이 세번째 파라메터에 false를 지정하시면 됩니다.
`zdate($val, 'Y-m-d', false)`
