### ISSUE TITLE
XpressEngine 설치 직후, 대부분의 작업에서 "잘못된 요청입니다." 발생

### ISSUE THREAD

**Issue by Hoto-Cocoa** [xpressengine/xe-core#2285]
XpressEngine 1.9.8 설치 직후, 대부분의 작업을 진행 할 수 없습니다. GIF 첨부합니다.
[GIF(GitHub 용량 제한으로 인해 외부 링크로 첨부함)](https://puu.sh/Bg9IO/fe0596eae0.gif)
PHP 7.0, MariaDB 10.1 사용중입니다. 설치 할 때 master, release/1.9.8, tag/1.9.8 브랜치들과 Release 1.9.8을 사용해보았으나 모두 같은 증상입니다.
![image](https://user-images.githubusercontent.com/21969938/44299624-ee832880-a334-11e8-96e9-82ffa384d512.png)
설치 환경입니다.

**Comment by Hoto-Cocoa** [comment]
DB 쓰는 것들은 대부분 안된다는 느낌입니다.

**Comment by Hoto-Cocoa** [comment]
![image](https://user-images.githubusercontent.com/21969938/44309877-04ade900-a408-11e8-8e41-289685b70591.png)
이 환경에서 진행 할 경우에는 잘 됩니다. DB는 MariaDB 10.2고, 앞 두 서버와 달리 Nginx->Apache2의 방식입니다.

**Comment by Hoto-Cocoa** [comment]
짧은 주소 문제인가 싶어 테섭에서 관련 설정을 지우고 진행해보았는데 그대로입니다.

**Comment by Hoto-Cocoa** [comment]
![image](https://user-images.githubusercontent.com/21969938/44310077-6885e100-a40b-11e8-995c-6c854e8dc4ad.png)
WSL+Ubuntu로 이 환경 이용해서 셋업해보았는데 동일 증상입니다. Nginx를 쓰면 안되는 느낌입니다만...

**Comment by bnu** [comment]
@Hoto-Cocoa 아래 링크의 변경 내역을 되돌리고 확인해주실 수 있을까요?
빨간색 라인에서 녹색 라인으로 변경된 것인데, 반대로 녹색 라인을 빨간색 라인의 코드로 복원하면 됩니다.
두 곳이고, config/func.inc.php 파일입니다.

https://github.com/xpressengine/xe-core/commit/124d119e0a00e2c5a67c50d78ae1e180116a07c6

**Comment by Hoto-Cocoa** [comment]
![image](https://user-images.githubusercontent.com/21969938/44320574-cce18880-a47d-11e8-8df5-541b9e7c5523.png)
변화가 없는 느낌입니다. 로그인으로 테스트 하였습니다.

**Comment by kijin** [comment]
서버 세팅에 문제가 있거나 (테스트 서버를 따로 구축하더라도 기존과 비슷한 방식을 사용하셨을 테니...) 사이트를 설치한 URL이 정상적이지 않을 가능성이 높아 보입니다. 특히 기본URL 설정이 실제 접속에 사용하는 주소와 일치하지 않으면 거의 모든 액션에서 잘못된 요청이라고 나올 수도 있습니다.

**Comment by Hoto-Cocoa** [comment]
![image](https://user-images.githubusercontent.com/21969938/44322222-40d45e80-a487-11e8-865a-848f339909cb.png)
기본 URL 설정에는 문제가 없고, Nginx 설정도 별 다른 특이점이 없습니다. 그리고 예전에 이 컨피그 그대로 사이트 열고 있었다가 내렸었는데 이번에 새로 다른거 열려니까 안되는거라 이걸로 제 설정 문제가 아니라고 단정을 짓긴 힘들겠지만 제 설정 문제라고 단정 짓기도 힘들 것 같습니다.

**Comment by Hoto-Cocoa** [comment]
필요하시다면 테섭 쉘 드릴 수 있습니다.

**Comment by Hoto-Cocoa** [comment]
![image](https://user-images.githubusercontent.com/21969938/44436258-2917ea00-a5ef-11e8-8c74-15df11b4b2ef.png)
Apache2를 이용하니까 정상 작동 합니다. Nginx에서만 문제가 발생합니다.

**Comment by bnu** [comment]
@Hoto-Cocoa nginx 설정 일부가 문제가 되었겠네요.
저희가 보유한 nginx 환경의 서버에서도 정상 동작하고 있습니다.

**Comment by Hoto-Cocoa** [comment]
기본 설정에서도 문제가 발생하는데 따로 변경해줘야 하는 값이 있나요?

**Comment by Hoto-Cocoa** [comment]
Nginx 설정값입니다. 
```
server {
	listen 443 http2;
	server_name test.tts.lol;

	root /web/test.tts.lol;
	index index.php;

	# SSL Settings
	ssl on;
	ssl_certificate /etc/letsencrypt/live/test.tts.lol/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/test.tts.lol/privkey.pem;

	# PHP
	location ~ \.php$ {
		set $php_root $document_root;
		include fastcgi_params;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/run/php/php7.1-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		try_files $uri @rewrite =404;
	}

	# XE Rewrite
	rewrite ^/(common|layouts|m.layouts)/(.+)/(.+).html$ /index.php last;
	rewrite ^/(modules|addons|widgets)/(.+)/(conf|queries|schemas)/(.+).xml$ /index.php last;
	rewrite ^/(.+)/files/(member_extra_info|attach|cache|faceOff)/(.*) /files/$2/$3 last;
	rewrite ^/(.+)/(files|modules|widgets|widgetstyles|layouts|m.layouts|addons)/(.*) /$2/$3 last;
	rewrite ^/(rss|atom)$ /index.php?module=rss&act=$1 last;
	rewrite ^/([a-zA-Z0-9_]+)/(rss|atom|api)$ /index.php?mid=$1&act=$2 last;
	rewrite ^/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/(rss|atom|api)$ /index.php?vid=$1&mid=$2&act=$3 last;
	rewrite ^/([0-9]+)/(.+)/trackback$ /index.php?document_srl=$1&key=$2&act=trackback last;
	rewrite ^/([a-zA-Z0-9_]+)/([0-9]+)/(.+)/trackback$ /index.php?vid=$1&document_srl=$2&key=$3&act=trackback last;
	rewrite ^/admin/?$ /index.php?module=admin last;
	rewrite ^/([0-9]+)$ /index.php?document_srl=$1 last;
	rewrite ^/([a-zA-Z0-9_]+)/?$ /index.php?mid=$1 last;
	rewrite ^/([a-zA-Z0-9_]+)/([0-9]+)$ /index.php?mid=$1&document_srl=$2 last;
	rewrite ^/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/?$ /index.php?vid=$1&mid=$2 last;
	rewrite ^/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/([0-9]+)$ /index.php?vid=$1&mid=$2&document_srl=$3 last;
	rewrite ^/([a-zA-Z0-9_]+)/entry/(.+)$ /index.php?mid=$1&entry=$2 last;
	rewrite ^/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/entry/(.+)$ /index.php?vid=$1&mid=$2&entry=$3 last;
}
```

**Comment by kijin** [comment]
사용하지 않는 `$php_root` 변수도 이상하고, PHP 요청이라면 이미 rewrite되어서 들어왔을 텐데 `try_files`에 `@rewrite`가 또 들어 있는 것도 이상합니다. nginx는 PHP 처리 과정에서 경로를 조금이라도 건드리면 매우 민감한 것으로 알려져 있습니다.

**Comment by Hoto-Cocoa** [comment]
2줄 삭제하였으나 아직 안됩니다.

**Comment by Hoto-Cocoa** [comment]
해결되었습니다! 감사합니다 :)
