### ISSUE TITLE
seo 모듈 모든 모듈에 같은 설명이 아닌 개별 설명이 필요합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2287]
모든 모듈(게시판 등)에 중복으로 반복된 설명이 아닌 실제 모듈이나 게시판의 설명을 출력할 수 있어야 할 것 입니다.

https://github.com/YJSoft/xe-module-seo

**Comment by wookho** [comment]
@bnu 네. 그렇다면 각 모듈에 설명을 넣을 수 있는 공간을 만들던지 하여 개선해야 할 것 같습니다. SEO는 가장 기본이고 웹사이트 운영 성패에 영향을 주는 핵심 기술입니다. CMS에서 탄탄하게 지원해야 합니다. XE도 많이 개선이 되었지만 세심한 부분은 부족합니다.

특히 중복해서 서로 다른 성격의 페이지를 모두 같은 meta tag를 출력하는 것은 하지 말아야 한다고 생각합니다.

**Comment by bnu** [comment]
@wookho 네. 말씀하신 내용에 동의합니다.
