### ISSUE TITLE
모바일 회원가입완료 후 로그인 창 상단 시스템메시지 미출력

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2289]
코어 문제인지 스킨문제인지 확인하기 어렵지만 테스트를 해보면 모바일에서 가입 시도시 가입완료 후 로그인 창으로 전환하면서 상단에 시스템메시지가 없어서 인증메일이 발송되었다는 사실을 즉시 확인하지 못합니다.

공홈에서도 테스트로 가입해보니 동일한 증상입니다.

**Comment by wookho** [comment]
정확한 해결법은 아닐수 있는데..
`	<div cond="$XE_VALIDATOR_MESSAGE && $XE_VALIDATOR_ID == 'modules/member/m.skin/default/login_form/1'" class="message {$XE_VALIDATOR_MESSAGE_TYPE}">
		<p>{$XE_VALIDATOR_MESSAGE}</p>
	</div>`


로그인파일에서 && $XE_VALIDATOR_ID == 'modules/member/m.skin/default/login_form/1' 이부분을 제거했습니다. 일단 메시지는 잘 나오네요.

**Comment by kijin** [comment]
가입후 인증메일 발송 안내에 사용되는 validator ID와 로그인 창에서 사용하는 validator ID가 달라서 생기는 문제인 것 같네요.

**Comment by wookho** [comment]
@kijin 네. 그런것 같긴한데 저 코드가 원래 오래전부터 사용하던 코드인데 그럼 정녕 아무도 이런 문제를 모르고 있었던 것인지.....

**Comment by wookho** [comment]
PC에서는 저희의 경우 레이아웃에서도 시스템메시지를 출력하고 있어 거기서 출력되어진건 아닌지 하는 생각이 드네요.

**Comment by wookho** [comment]
@kijin 가입 절차를 보면
가입폼에서 가입양식을 채우고 회원가입 등록버튼을 누르면

코어에서 회원가입에 문제가 없는지 확인 후 
db에 회원을 등록하면서 인증메일을 보내게 됩니다.

이때 회원가입폼 => 로그인폼으로 이동이됩니다.

로그인폼으로 이동된 하면에 시스템메시지가 출력이 안되는 문제이구요.
로그인폼의 시스템출력에는 위에 적어드린 코드가 적용됩니다.

라이믹스의 스킨도 내려받아 봤는데 똑같더군요.
