### ISSUE TITLE
addon_info->description을 포함하는 페이지가 escape로 인해 br 태그가 그대로 노출되는 이슈

### ISSUE THREAD

**Issue by Xvezda** [xpressengine/xe-core#2303]
`$addon_info->description` 을 포함하는 템플릿 코드가 이번 보안패치로 인해서 
기존의 nl2br이 escape 되어, 깨져보이는 이슈가 있는것으로 보입니다.

해당 변수에 noescape 필터를 적용하거나 기존 개행을 무시하는 패치가 필요 할 것으로 생각됩니다.

**Comment by bnu** [comment]
@Xvezda 감사합니다.
문제가 될 만한 페이지를 계속 찾고 있습니다.

nl2br에 대해서도 다시 확인해보도록 하겠습니다.
