### ISSUE TITLE
우편번호 5자리만 있는 경우 입력이 안됩니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2309]
검색된 주소가 신 우편번호를 가질 경우 우편번로 입력란에 들어가지 않아 주소를 입력할 수 없습니다.

**Comment by wookho** [comment]
@BNU 이문제가 dvelop 에서 아직 master로 적용안된거 모르시는거 아닌가요?

**Comment by bnu** [comment]
master 브랜치에서 확인했습니다.
우편번호 모듈의 설정을 확인해주세요.

![2018-10-29 7 50 27](https://user-images.githubusercontent.com/53764/47645292-e86ebb00-dbb3-11e8-971f-069c5f4280c8.png)

**Comment by wookho** [comment]
아.. 이건 제가 착오가 있어 배포된 시점을 놓친거 같습니다. 지금 모듈만 새로 업로드하니 설정이 생기네요. 그런데 한가지 이상한 점은 6자리를 선택해도 5자리만 부여된 신규주소도 5자리로 대체 입력되게 구현되었나요? 이게 아나라면 무조건 5자리만 유효한 사용일텐데요.

**Comment by bnu** [comment]
@wookho 도로명 주소로 넘어오는 과도기의 옵션입니다(기존 설치자는 6자리로 입력되도록 설정이 유지된 상태). 이제는 없애도 될 옵션이네요.

6자리 우편번호로 이미 입력된 데이터는 자동 변환되지 않으며,
다음 API 사용 시 지번을 선택해도 설정에 의한 5자의 우편번호로 채워집니다.

**Comment by wookho** [comment]
@bnu 전달이 잔 안되는거 같네요. 지금 6자리를 사용하겠다고 설정한 경우 새로 생긴 주소는 6자리를 가지지 않습니다. 이때 6자리 사용 설정을 해 놓은 경우라도 5자리를 입력에 성공해야 한다는 의견입니다.

**Comment by Lastorder-DC** [comment]
@wookho 6자리 우편번호를 사용하지 않는데도 6자리로 설정이 가능한것이 문제이지, 6자리일때 입력이 안되는게 문제가 아닙니다. 굳이 그렇게 할 필요 없이 옵션을 없애면 기존 설정 무관 자동으로 5자리를 쓰도록 변경되므로 문제가 발생하지 않습니다.
