### ISSUE TITLE
php 세션을 memcache에 저장하는 환경에서 캐시파일 재생성을 하면 로그인이 풀리는 문제

### ISSUE THREAD

**Issue by jdssem** [xpressengine/xe-core#2310]
### 환경
- xe_version : 1.9.8
- php : 7.1.22
- use_object_cache, use_template_cache에 memcache 사용중
- php session.save_handler = memcache

### 증상
- 관리자페이지에서 캐시파일 재생성을 하면 모든 사용자의 세션이 삭제됨

예전에는 안 그랬는데 언젠가부터 이런 현상이 있었던 것 같습니다. 아마 캐시 재생성하는 과정에서 memcache의 세션정보까지 다 삭제되는 것 같네요.

**Comment by kijin** [comment]
이건 해결하기 쉽지 않을 것 같습니다. memcache에서 XE 오브젝트 캐시 관련 데이터만 일괄 삭제하고 나머지는 그대로 두는 명령이 없으니까요. 아마 그냥 flush해버리도록 되어 있을 겁니다.

최상위 레벨에 cache group version을 사용하고 flush가 아니라 version만 바꾼다면 해결이 가능하겠지만, cache lookup이 추가로 발생하여 성능에는 악영향을 줄 수도 있으니 득실을 따져보아야 할 것입니다.

아무튼 이런 환경에서 XE를 사용하신다면 서버 구성을 자유롭게 변경할 수 있다고 가정해도 될 테니... 세션 저장에 사용하는 memcache와 오브젝트 캐시로 사용하는 memcache를 각각 따로 구동하거나, 세션 저장소는 redis로 하고 오브젝트 캐시는 memcache로 하거나, 세션은 memcache로 하고 오브젝트 캐시를 apcu로 하는 등의 방법으로 일단 문제를 피할 수 있겠습니다. (redis 사용시 세션 데이터와 오브젝트 캐시 데이터를 DB 번호로 구분하면 flush를 피할 수 있습니다.)

**Comment by jdssem** [comment]
@kijin 아, 말씀해주신 것처럼 별도의 캐시 저장소를 사용하면 되겠군요! 감사합니다.

**Comment by jdssem** [comment]
그런데 memcache는 매우 오래전(최소 7년)부터 사용을 해왔는데 제 기억이 잘못된 것인지 몰라도 예전에는 별 이상 없이 제대로 동작했던 것 같습니다.
