### ISSUE TITLE
서브 메뉴 타이틀, 제목 - 외국어 사용시, 한글로 표시 됩니다.

### ISSUE THREAD

**Issue by LIMJK** [xpressengine/xe-core#2311]
기본 레이아웃인 [xedition]이나, 김타조님이 만드신 [xe_kimtajo_layout] 모두 동일한 현상이 나오니,
다른 레이아웃에서도 동일한 현상을 보일 것 같습니다.

메인 메뉴는 해당 외국어로 표기되지만,
1차 서브 메뉴의 [메뉴 이름], [브라우저 제목] 모두 한결 같이 한글로 나옵니다.
하지만 2차 서브 메뉴는 해당 외국어로 표시됩니다.

XE에서 기본값으로 지원되는 12개언어 중에서, 몽골어 제외 11개국어로 홈페이지 제작중입니다.
따라서 이 모든 언어를 다 테스트해 봤으나, 동일한 현상으로 나옵니다. # @

**Comment by bnu** [comment]
게시판, board
샘플1, sample1

메뉴를 다국어 지정하여 테스트 해봤지만 말씀하신 증상은 보이지 않습니다.

ko
![2018-10-05 7 39 19](https://user-images.githubusercontent.com/53764/46530953-75d12f00-c8d6-11e8-9a7b-5ec643ef04b0.png)

en
![2018-10-05 7 39 34](https://user-images.githubusercontent.com/53764/46530963-808bc400-c8d6-11e8-90aa-15ccf51ee9a3.png)

**Comment by bnu** [comment]
아, 메뉴 외에 설정이 하나 더 있습니다.
게시판 및 페이지 설정에서 브라우저 제목을 변경하시면 됩니다.
이미 메뉴에서 추가한 다국어를 선택하여 재사용할 수 있습니다.
 
![2018-10-05 7 43 27](https://user-images.githubusercontent.com/53764/46531109-f8f28500-c8d6-11e8-9cbf-d22f126f8b6e.png)

**Comment by bnu** [comment]
#2313 이슈로 통합
