### ISSUE TITLE
아래 외국어 표기 오류에 대해 캡춰 이미지 첨부합니다.

### ISSUE THREAD

**Issue by LIMJK** [xpressengine/xe-core#2312]
보이는 메뉴는 문제가 없습니다.
저도 며칠째, 확인하며 만들면서 전혀 모르다가,
오늘 우연히 발견한 현상입니다.

![0](https://user-images.githubusercontent.com/24222320/46531664-ff81fc00-c8d8-11e8-83fc-5353cb88b754.png)

제가 이곳 게시판을 어떻게 사용하는지 몰라서, 추가글 형태로 올립니다.
(파일을 어떻게 첨부하는지 몰라서 글로 남겼으나, 아래 글씨를 누르니 첨부가 되는 군요. ;;)

위에 첨부한 이미지처럼,
1차 서브메뉴 타이틀이 모두 한글로 나옵니다.
하지만 2차 서브메뉴는 정상적으로 해당 외국어로 표기됩니다.

**Comment by LIMJK** [comment]
이 오류는 확인해 보니, 메뉴 하나를 새롭게 생성할 때,
[메뉴 이름]만 넣으면, 생성된 메뉴에서 [브라우저 제목]에도 동일한 명칭이 자동으로 들어갑니다.
![default](https://user-images.githubusercontent.com/24222320/46645575-714f9380-cbc0-11e8-85a6-49930ca3684d.PNG)
하지만 위 그림과 같이 최초에 메뉴 생성할 때,
[메뉴 이름]에 다국어를 넣어 생성하면,
[브라우저 제목]에는 한글명만 들어 갑니다.
이렇다보니 외국어환경에서는 자연히 한글명칭만 노출된 것입니다.

하지만 여기에 하나 더 문제점이 있었습니다.
수동으로 [브라우저 제목]을 다국어 제목으로 수정하고,
다른 메뉴도 다국어로 수정하면, 다시 위 그림과 같이 풀린다는 점입니다.

어떤 시점에 이렇게 풀리는지 확실하게 확인하지는 않았으나,
제작하며 수차례 여러 메뉴를 수정하고, 생성하다보니 어느 순간 풀려있음을 알 수 있었습니다.

유독 1차 서브메뉴에서만 이런 현상이 생기는 군요.

**Comment by bnu** [comment]
#2313 이슈로 통합
