### ISSUE TITLE
아래 문제점은 확인해 보니, 메뉴 하나를 새롭게 생성할 때~

### ISSUE THREAD

**Issue by LIMJK** [xpressengine/xe-core#2313]
이 오류는 확인해 보니, 메뉴 하나를 새롭게 생성할 때,
[메뉴 이름]만 넣으면, 생성된 메뉴에서 [브라우저 제목]에도 동일한 명칭이 자동으로 들어갑니다.
![default](https://user-images.githubusercontent.com/24222320/46645575-714f9380-cbc0-11e8-85a6-49930ca3684d.PNG)
하지만 위 그림과 같이 최초에 메뉴 생성할 때,
[메뉴 이름]에 다국어를 넣어 생성하면,
[브라우저 제목]에는 한글명만 들어 갑니다.
이렇다보니 외국어환경에서는 자연히 한글명칭만 노출된 것입니다.

하지만 여기에 하나 더 문제점이 있었습니다.
수동으로 [브라우저 제목]을 다국어 제목으로 수정하고,
다른 메뉴도 다국어로 수정하면, 다시 위 그림과 같이 풀린다는 점입니다.

어떤 시점에 이렇게 풀리는지 확실하게 확인하지는 않았으나,
제작하며 수차례 여러 메뉴를 수정하고, 생성하다보니 어느 순간 풀려있음을 알 수 있었습니다.

유독 1차 서브메뉴에서만 이런 현상이 생기는 군요.

**Comment by bnu** [comment]
메뉴관리에서 상세설정 섹션에서 수정 시 문제 확인했습니다.

(지난 이슈는 삭제하겠습니다. 이슈에 이어지는 내용의 첨언은 이슈의 댓글로 작성해주시면 됩니다.

**Comment by LIMJK** [comment]
1.11.1 나오면 그때 다른 파일과 함께 설치해야 제대로 나오나 보군요.
cc952a2로 들어가, 지적해 주신 파일의 406번째 줄을 지우고 업로드했더니, 아래와 같이 되네요. ;;;
![01](https://user-images.githubusercontent.com/24222320/46859974-395b8100-ce4a-11e8-8328-3a90fc37c47a.PNG)
![02](https://user-images.githubusercontent.com/24222320/46859976-395b8100-ce4a-11e8-8a8f-a994a00553f2.PNG)
