### ISSUE TITLE
xe 1.11.0 업데이트 후 모바일 레이아웃 적용 문제

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2322]
xe 1.11.0 적용 후 모바일 레이아웃 적용이 안됩니다.
해당 페이지를 모바일로 접속시 모바일 레이아웃 적용에 체크를 해도 적용이 안됩니다.
1.9 버전 대에서는 동일하게 해도 모바일이 적용되는데 말이죠 ;ㅁ;
이런 현상 확인 가능하신 분 계신가요?

**Comment by bnu** [comment]
설정을 확인해주실 수 있을까요?

- 관리페이지 -> 설정 -> 일반 -> 모바일 뷰 사용
- 문제가 되는 게시판/페이지 등 모듈 -> 설정 -> 모바일 뷰 사용

**Comment by bnu** [comment]
추가 내용이 확인되지 않으면 곧 이슈를 닫겠습니다.

**Comment by bnu** [comment]
같은 증상이 재현될 경우 추가 댓글 또는 별도의 이슈로 남겨주세요.
