### ISSUE TITLE
아이폰 엔터시 윗줄 마지막글자 붙는 현상

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2325]
라이믹스에서는 해결이 된 것 같다고 @kijin 께서 언급해 주셨습니다.

https://github.com/rhymix/rhymix/commit/ddb2a8afa1eb1e41f7eac9f3e6e9f699596ddd97

XE에서는 여전히 동일한 현상이 지속되고 있으니 참조해서 반영 부탁드립니다.
수년째 아이폰 유저들이 고통받고 있습니다. ㅡㅡ;

**Comment by wookho** [comment]
@bnu 혹시 아이폰 문제가 해결된것으로 파악하신 것은 아닌지요. 전혀 해결된거 없이 동일합니다. 제가 링크한 라이믹스에서 해결되지 않은 것으로 판단하고 패치한 부분이 최소한의 제가 언급한 윗줄 마지막 글자가 아래로 이어 붙는 현상은 해결되었다고 합니다.

**Comment by bnu** [comment]
@wookho 
#2207 이슈에서 해결했습니다.

현재 제가 iOS 12입니다만, 다른 버전(iOS 11 등)에서 문제가 계속 나타나는지요?

![2018-10-29 7 50 27](https://user-images.githubusercontent.com/53764/47645669-10125300-dbb5-11e8-8dd3-bccd56db5662.png)

**Comment by wookho** [comment]
@bnu 라이믹스가 추가패치를 바로 한 것도 해결이 되지 않아서 였습니다. 안타깝지만 제가 아이폰이 없어 어떤 버전에서 문제가 되는지 확인이 어렵지만 회원들에게 해당 민원이 접수가 계속 되고 있습니다.

**Comment by bnu** [comment]
@wookho 사이트에 사용 중인 에디터가 CKEditor가 맞나요?

**Comment by wookho** [comment]
@bnu 네. CK에디터 입니다.
https://pomelove.com/request/1971115

**Comment by bnu** [comment]
원인을 찾았습니다.
common/js/plugins/ckeditor/ckeditor/config.js 파일에서 커스텀 설정을 사용할 때 코어 설정을 덮어버리는 것이 원인이었습니다.
위 파일에서 아래와 같이 변경해주세요
(변경 후 댓글 달아주시면 제가 기기로 확인하겠습니다.)

```
// ,enterkey 추가
config.removePlugins = 'link,language,bidi,enterkey';
```

**Comment by bnu** [comment]
iOS에서 해당 설정의 항목에 강제로 추가하도록 변경해두겠습니다.

**Comment by wookho** [comment]
@bnu
config.js 파일에서 플러그인 제거 항목에 엔터키를 추가하라는 것인가요?
그렇게 하면 모든 디바이스에 다 적용되어버리는 거 아닌가요?

**Comment by wookho** [comment]
@bnu 저희 파일에 지금 추가를 해드려야 하나요? 제가 지금 해드리기 어려울 것 같은데요....

**Comment by bnu** [comment]
@wookho 아..그렇죠^^;
아닙니다. 해당 코드가 추가되면 될테니. 다음 버전에 패치하겠습니다.

**Comment by bnu** [comment]
@wookho 필요 시 커밋된 두 파일을 교체하시면 됩니다.

**Comment by wookho** [comment]
@bnu 파일 두개는 우선 교체해 놓았습니다. 회원님들께 확인 요청은 추후에 하겠습니다.

**Comment by bnu** [comment]
네. 해당 사이트에서 확인했습니다.
![img_0478](https://user-images.githubusercontent.com/53764/47650057-6c2fa400-dbc2-11e8-9492-9bfe858f43cc.jpg)

**Comment by wookho** [comment]
@bnu 그럼 회원들께 알릴겸 게시글로 확인요청을 해야겠네요.

**Comment by paulryu03** [comment]
@bnu 님 XETown 에서 대화가 오고 간 부분을 읽어 봐주세요.

https://xetown.com/topics/1101119

제가 공홈/포럼에서 글쓰기를 시도해 봤는데요. 에디터에 글씨를 입력할 수가 없습니다. 혹시 #2325 수정 코드를 이미 적용하셨는지 모르겠습니다. 에디터에 포커스가 되지를 않습니다. "소스"를 누르면 되구요. 테스트 기기는 iPhone XS Max 와 iPad Pro 이고, 각각 iOS 12.0.1 이 설치가 되어 있습니다.

**Comment by wookho** [comment]
@BNU css파일 3개 , js파일 2개 다시 패치해야 하는거네요. 일단 5개 파일 업데이트 했습니다.

**Comment by paulryu03** [comment]
> @paulryu03 네. 해당 증상 확인했습니다.
> 어떤 문제인지 iframe 입력 영역의 크기 문제로 CSS로 해결했습니다.

아... 그랬군요. ^^ 항상 애써 주셔서 감사합니다!!

**Comment by bnu** [comment]
@wookho 네. js 파일은 config.js 파일의 설정과 충돌하는 문제. css 파일은 iframe 영역의 크기가 제대로 표현되지 않는 문제를 수정합니다.

**Comment by bnu** [comment]
@paulryu03 관련링크 감사합니다.
저는 XS 예약했습니다!?

**Comment by paulryu03** [comment]
> @paulryu03 관련링크 감사합니다.
> 저는 XS 예약했습니다!?

앗! 그러세요. 축하드립니다. ^^ 저도 지난 주말에 도착해서 사용해 보고 있는건데 써보니깐 빠르고 좋네요. ^^

**Comment by paulryu03** [comment]
@bnu 지금 확인해 봤는데 에디터에 포커스가 잘 잡히고 글씨도 입력이 잘 됩니다. 해당 이슈가 다 해결 됐네요. 감사합니다!
