### ISSUE TITLE
(XE 1.11.1) 레이아웃  편집 후 저장을 하면, 사이트 접속시 에러가 납니다.(특정 사이트)

### ISSUE THREAD

**Issue by keysung** [xpressengine/xe-core#2326]
안녕하세요,
수고가 많으십니다.

레아아웃 편집 후 저장을 한 다음에 다시 사이트에 접속하면 에러가 나며 접속이 안됩니다.
원인을 찾아보니 레이아웃을 편집한 다음 저장을 하면 아래와 같이 코드가 변하는 현상이 생기는데...
이게 에러 원인인 듯 하니 한번 검토 부탁 드립니다.

아래는 디폴트 레이아웃을 편집한 다음 저장을 한 경우 입니다.(다른 레이아웃도 같은 현상임)

감사합니다.
ksc

```
-- 원본--
<load target="default.layout.css" />
<load target="default.layout.webfont.css" cond="$layout_info->WEB_FONT == 'YES'" />
<load target="../../common/js/respond.min.js" targetie="lt IE 9" />
<load target="default.layout.js" type="body" />
<div class="container">

-- 1차 저장--
<load target=\"default.layout.css\" />
<load target=\"default.layout.webfont.css\" cond=\"$layout_info->WEB_FONT == \'YES\'\" />
<load target=\"../../common/js/respond.min.js\" targetie=\"lt IE 9\" />
<load target=\"default.layout.js\" type=\"body\" />
<div class=\"container\">

-- 2차 저장--
<load target=\\\"default.layout.css\\\" />
<load target=\\\"default.layout.webfont.css\\\" cond=\\\"$layout_info->WEB_FONT == \\\'YES\\\'\\\" />
<load target=\\\"../../common/js/respond.min.js\\\" targetie=\\\"lt IE 9\\\" />
<load target=\\\"default.layout.js\\\" type=\\\"body\\\" />
<div class=\\\"container\\\">
```

**Comment by keysung** [comment]
흠... 묘하군요.
조금 전에 사이트에 접속을 하니, 연결이 됩니다.
(어쩌면 XE문제가 아니라 서버측 작업과 관련된 문제일 수도 있을듯 싶은데...
어제 밤 레이아웃을 편집한 시간이 밤 12시 경 이었으니... 백업 중 이었을 수 도 있고요.)

어쨌거나 지금은 정상적으로 연결이 되는군요.
다만 아래는  다시 레이아웃 편집으로 들어가서본 코드인데... 값이 변경되어 있기는 합니다..

감사합니다.
ksc

```
<load target=\\\"default.layout.css\\\" />
<load target=\\\"default.layout.webfont.css\\\" cond=\\\"$layout_info->WEB_FONT == \\\'YES\\\'\\\" />
<load target=\\\"../../common/js/respond.min.js\\\" targetie=\\\"lt IE 9\\\" />
<load target=\\\"default.layout.js\\\" type=\\\"body\\\" />
<div class=\\\"container\\\">
```

**Comment by keysung** [comment]
상태를 다시 정리 해보면,
레이아웃 편집 후 저장을 하면 사이트 접속이 안되며,
초기화 단추를 누른 후 저장 없이 사이트에 접속을 하면 연결이 됩니다
(저장을 하면 에러발생 됨)

감사합니다.
ksc

**Comment by bnu** [comment]
@keysung 디자인 설정과 설치된 레이아웃 목록에서 편집 시 해당 증상이 나타나지 않았습니다.

**Comment by keysung** [comment]
bnu 님 안녕하세요,

네, 그렇군요.
댓글을 보고 확인을 해보니, 사이트 2곳 중 한 곳에서만 위 현상이 발생하는것을 확인 했습니다.
문제가 생기는 사이트에 XE를 다시 업로드 해보고 결과를 올리도록 하겠습니다.

감사합니다.
ksc

**Comment by bnu** [comment]
네. 어떤 특이점이 있을 것 같은데, 두 환경의 다른 차이점(설치 버전, 특정 확장기능 등)을 알려주시면 좀 더 확인해보겠습니다.

**Comment by keysung** [comment]
안녕하세요,

XE 1.11.1 풀 버번을 올려 봤는데... 결과는 동일 하군요.
아래는 문제가 생기는곳의 서버 정보입니다. (총 3곳중 처음 1곳만 문제가 생겼음)
혹시... PHP버전 문제일까요?

감사합니다.
ksc

--아래는 문제가 생기는곳의 서버 정보입니다--
[XE Server Environment 2018-10-18]

realpath : /home3/planner/html/xe
location : ko
package : XE
host : http://planner123.raonnet.com/xe/
app : Apache/2.2.17 (Unix) mod_ssl/2.2.17 OpenSSL/0.9.8e-fips-rhel5 PHP/5.3.29
xe_version : 1.11.1
php : 5.3.29
db_type : mysql
use_rewrite : Y
use_db_session : Y
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, calendar, curl, fileinfo, ftp, gd, gettext, gmp, iconv, mbstring, mcrypt, mysql, mysqli, pdo_sqlite, phar, shmop, simplexml, sockets, sqlite, exif, sysvshm, xml, xmlreader, xmlwriter, zip, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.2), bodex(0.9.3), issuetracker(1.2.0), krzip(1.9.0), referer(3.11.1), resource(1.7.0), seo(1.9.0), syndication(6.0.0), wiki(1.7.0.1)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0), php_exif(1.0), referer(3.5.1), stop_spambot_xe(2.4)
layout : XE_layout123_v02(0.2), xe_official(1.7), xedition(1.9), XEgrid_Free(1.0.3), user_layout(1.7)
widget : calendar_plannerXE123(5.5.1), contentextended(2.43), counter_status(1.7)
widgetstyle : simple(1.7), simpleRound(0.1)
max_file_uploads : 20
post_max_size : 80M
memory_limit : 128M


--아래 2곳은 위 문제 없는곳의 서버 정보입니다--
[XE Server Environment 2018-10-18]

realpath : /host/home/keysung/html/xe
location : ko
package : XE
host : http://keysung.dothome.co.kr/xe/
app : Microsoft-IIS/5.0
xe_version : 1.11.1
php : 5.5.38
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, zlib, bcmath, bz2, calendar, curl, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, exif, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, phar, shmop, simplexml, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, xml, wddx, xmlreader, xmlwriter, xsl, zip, mhash, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.2), krzip(1.9.0), seo(1.9.0), syndication(6.0.0)
addon : adminlogging(1.7), captcha_member(1.7), oembed(1.0), stop_spambot_xe(2.4)
layout : sketchbook5_layout(1.6.3.6), xe_official(1.7), xedition(1.9), user_layout(1.7)
widget : calendar_plannerXE123(5.6.0), counter_status(1.7)
widgetstyle : simple(1.7)
max_file_uploads : 20
post_max_size : 100M
memory_limit : 128M


------------------
[XE Server Environment 2018-10-18]

realpath : /home/chungfamily/www/zbxe
location : ko
package : XE
host : http://chungfamily.woweb.net/zbxe/
app : Apache
xe_version : 1.11.1
php : 5.4.39
db_type : mysql
use_rewrite : Y
use_db_session : Y
use_ssl : none
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, bz2, calendar, curl, dba, fileinfo, ftp, gd, gettext, iconv, mbstring, mcrypt, mysql, mysqli, mysqlnd, pdo_sqlite, apc, pdo_mysql, shmop, simplexml, soap, sockets, exif, sysvsem, sysvshm, xml, xmlreader, xmlwriter, zip, phar, mhash, ioncube loader, zend guard loader
module : adminlogging(1.7), board(1.7.2), krzip(1.9.0), referer(3.11.1), seo(1.9.0), syndication(6.0.0)
addon : adminlogging(1.7), blockade_spambot_xe(0.1), captcha_member(1.7), layerpopup(1.10), oembed(1.0), referer(3.5.1), stop_spambot_xe(2.4)
layout : cafeXE(1.7.0), xe_official(1.7), xe_blog(0.1), xedition(1.9), 1_xe_magic2(2.0), 1_dtree_magic2(2.0), user_layout(1.7)
widget : calendar(0.2), calendar_plannerXE123(5.6.0), contentextended(2.43), counter_status(1.7), formmail_XE(2.1.0), logged_members(0.1), member_group(0.1), navigator_1(1.7.0), newest_comment(0.1), newest_document(1.0), newest_images(0.1), newest_popup(0.2.1), pcalendarXE(3.9.0), rank_count(1.5), saying(0.1), site_info(1.7.0)
widgetstyle : simple(1.7), simpleRound(0.1), simpleSquare(0.1), simpleTitle(0.1), squareWire(0.1)
max_file_uploads : 100
post_max_size : 64M
memory_limit : 128M

**Comment by keysung** [comment]
안녕하세요,

몇가지를 테스트 해보았고, 그 결과를 정리하면 아래와 같습니다.

1) 문제가 발생한 사이트에서 wiki 모듈 제거 -> 계속 문제 발생함( ' -> \'로 변경됨)

2) 문제없는 사이트에 issuetracjer 및 resource 모듈설치 후 -> 문제 발생하지 않음

3) 문제가 발생한 사이트를 XE 1.9.8 풀버전으로 업데이트  -> 문제발생하지 않음 ( ' -> \'로 변경되지 않음)

4) 아래 이미지는 문제 발생한 사이트의 DB 정보 입니다.(참고용):

감사합니다.
ksc

![mysql](https://user-images.githubusercontent.com/6400785/47132623-e49f8680-d2df-11e8-8e01-032b9eb4b1ba.png)

**Comment by keysung** [comment]
일단 특정한 사이트에 국한된 문제인 듯 하니,  다른 사람들은 별 문제가 아닐 수도 있겠군요.
더이상 문제가 안생기면 적당한 시간에 이슈 close 시켜 주시기 바랍니다.

저는 문제가 발생한 사이트는 XE 1.11.1로 올린 후에,
레이아웃 수정은 원본 layout.html을 수정해 놓고 초기화 버튼을 눌러서 업데이트 하는 방법으로 처리 하려고 합니다.

수고하세요,
ksc
