### ISSUE TITLE
getThumbnail() $thumbnail_type에 옵션이 추가되었으면 합니다.

### ISSUE THREAD

**Issue by ingcode** [xpressengine/xe-core#2327]
아래와 같이 되면 좋을꺼같습니다.

썸네일 타입 ratio으로 저장을 할경우,

세로 사이즈를 기준으로 가로사이즈를 정하더라고요,

가로 사이즈를 기준으로 세로 사이즈를 정하는 옵션이 있었으면합니다.

thumnail_type = ratio  일때의 문제점,
갤러리 게시판의 경우 이미지의 가로사이즈를 100px로 최적화했을경우,,
모든 이미지 가로가 100px로 나와야하지만
세로가 더 길경우, 세로 사이즈가 100px이 되고 가로사이즈즈 그비율에 맞춰 100px 이하가되어
이미지가 흐려져 버리게됩니다.

트랙픽이랑 생각했을경우는 해당 방법이 괜찮은거같긴 합니다,

ratio외에 가로기준으로 세로사이즈를 정하는 옵션이 하나 더있었으면 합니다.

**Comment by bnu** [comment]
`ratio` 일 때 최대 width, height 크기를 지정하게 되고, 각 최대 크기를 기준으로 비율에 맞게 리사이즈 합니다.

`getThumbnail()`는 height 값이 지정되지 않으면 width 값을 가져와 사용하게 되어 `getThumbnail(100)` 과 같이 사용 시 100x100px 이미지가 생성됩니다.

말씀하신 것처럼 '세로 기준'이 아니며, width, height 둘 다를 기준으로 잡습니다.

또 다른 것으로, 위젯에서 width, height를 고정하여 출력되는 게 문제라면 문제입니다.
![2018-10-18 11 39 10](https://user-images.githubusercontent.com/53764/47127997-77352b00-d2ca-11e8-841f-057c799dfb4c.png)
