### ISSUE TITLE
비밀번호 찾기 답변 없이 회원 가입이 됩니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2333]
이렇게 가입 후 비밀번호를 분실할 경우 임시비밀번호를 받을 수 없게 됩니다.

**Comment by wookho** [comment]
이게 의도한건지 모르겠네요.
질문/답변을 이용하지 않아도 이메일로 비밀번호를 받을 수 있는거 같네요.

**Comment by eondcom** [comment]
https://www.xpressengine.com/forum/23280446
여기 추가내용입니다.;
