### ISSUE TITLE
태블릿 모바일,PC 구분 운영자에게 선택권을 주었으면 합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2334]
사이트에 따라 또는 같은 사이트라도 상황에 따라 태블릿이 어느곳으로 편입되어야 할지 달라지게 됩니다. 지금 XE에서는 태블릿의 경우 PC보기로 보여집니다. 반대를 원할 경우 태블릿을 확인하는 코드를 제거해야 합니다.

현재 어떤 기준이 옳고 그른 것이 될 수 없는 것은 사이트마다 결정하게 해주어야 한다고 봅니다.

**Comment by bnu** [comment]
config.user.inc.php 파일에 특정 명칭의 함수를 정의해두고, 해당 함수에서 리턴한 값으로 모바일 적용 여부를 결정하도록 하면 될까요?

**Comment by bnu** [comment]
@wookho 브라우저 종류에 따라 판별하게 되는 user-agent 목록이 워낙 오래되어 잘 작동하고 있는지 모르겠네요.
그래서 아예 사용자 정의 함수를 추가하는 방법에 대해 의견을 물었던 건데.. 그 옵션만 필요하다면 추가하도록 하겠습니다.

**Comment by wookho** [comment]
@bnu 제가 알기로는 안드로이드 계열은 태블릿은 mobile을 빼고 애플은 iPad를 쓰는 것으로 압니다. 대체적으로 왠만큼 구분이 되는 듯 합니다.
