### ISSUE TITLE
1.11.0 업데이트 후 Context::addHtmlHeader("<script type='text/javascript'>$script</script>"); 로 출력이 안됩니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2336]
https://www.xpressengine.com/index.php?mid=download&package_id=22753397

위 자료를 사용하면 관리자페이지의 해당 모듈의 설정의 상단 탭과 각 게시판 설정 상단 탭에 추가로 확장기능을 사용하는 탭이 생깁니다.

그런데 최근 코어업데이트로 인해 해당 탭이 나타나지 않습니다. 이런 케이스는 어떻게 처리를 해야 하나요??

`<?php
    /**
     * @class  board_extendAdminController
     * @author xiso (xiso@xiso.co.kr)
     * @brief  board_extend module admin controller class
     **/
	require_once(_XE_PATH_.'modules/board/board.controller.php');
    class board_extendController extends boardController {
		
		function triggerDisplay(){
			//trigger display before();
			if(strpos(Context::get('act'),"ispBoardAdmin") || strpos(Context::get('act'),"ispBoard_extendAdmin")){
				$core_ver = __XE_VERSION__ ? __XE_VERSION__ : __ZBXE_VERSION__;
				$is_active = (Context::get('act') == 'dispBoard_extendAdminBoardModify') ? true : false;
				$url = getNotEncodedUrl('act','dispBoard_extendAdminBoardModify', 'selected_var_idx', '', 'type', '');
				$text = "목록수정";
				if($core_ver >= 1.7){
					$active = $is_active ? "class='x_active'" : "";
					$html = sprintf("<li %s><a href='%s'>%s</a></li>",$active,$url,$text);
					$script = "jQuery(document).ready(function(\$){\$('.x_nav').append(\"$html\");});";
				}else if($core_ver >= 1.5){
					$active = $is_active ? "class='active'" : "";
					$html = sprintf("<li %s><a href='%s'>%s</a></li>",$active,$url,$text);
					$script = "jQuery(document).ready(function(\$){\$('.x .cnb ul').append(\"$html\");});";
				}else if($core_ver >= 1.4){
					$active = $is_active ? "class='on'" : "";
					$html = sprintf("<li %s><a href='%s'>%s</a></li>",$active,$url,$text);
					$script = "jQuery(document).ready(function(\$){\$('#xeAdmin .header4 .localNavigation').append(\"$html\");});";
				}else{
					$this->stop('지원하지 않는 버전입니다. board_extend 모듈을 제거해주시기 바랍니다.');
				}
				Context::addHtmlHeader("<script type='text/javascript'>$script</script>");
			}
		}
		
	}
	
?>`

**Comment by bnu** [comment]
`addHtmlHeader()`과 관련된 문제가 아닌 것으로 확인했으며, 해당 모듈이 코어 버전을 제대로 확인하지 못하는 문제입니다.

**Comment by wookho** [comment]
이번 코어 업데이트 후 발생한 증상인데요.

**Comment by bnu** [comment]
@wookho 네. 해당 모듈이 버전 검사를 잘못하고 있어서 입니다.

```
php -r "var_dump('1.9.8' >= 1.7);"
bool(true)
php -r "var_dump('1.11.1' >= 1.7);"
bool(false)
```

**Comment by wookho** [comment]
아 그렇군요. 해당부분 검토해보고 수정하겠습니다. 감사합니다.

**Comment by bnu** [comment]
@wookho 

`if($core_ver >= 1.7){ ... }` 블럭의 코드만 남겨두시면 될 것 같습니다.
