### ISSUE TITLE
아이폰 이미지 첨부시 커서가 튕기는 문제

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2337]
이건 오래전부터 있던 문제입니다. 엔터 이슈가 해결 되었으니 이문제도 해결을 하고 싶습니다.

제가 아이폰을 사용하지 않아 현상을 자세하게 리포트해 드리지 못하는 점 죄송합니다.
글로 설명을 드리면..

글을 작성 중에 이미지를 첨부하고 또 글을 쓰고 하는 식의 글 작성을 많이 합니다. 그런데 아이폰의 경우 이미지 첨부시 커서가 실종된다고 합니다.

이때 텍스트필드 자체가 축소되어 커서를 찾을수 없다고 합니다. 필드가 축소되어 사진도 잘린 사진? 한장만 보이는 상태가 유지된다고 하는데요.

기존부터 제보가 계속 들어오고 있는 현상이며 
이 현상을 극복하는 방법 중 하나가 글을 먼저 작성하고 사이 사이에 사진을 첨부한다고 합니다.

**Comment by bnu** [comment]
네. 그렇지 않아도 이번에 다시 보면서 에디터 영역에 포커스가 갈 때 이상한 위치로 튀더라고요.
무엇이 문제인지는 살펴보는데 시간이 걸리겠지만 잡아보겠습니다.
다만, 다음 정기 배포 예정일은 12월 11일입니다...

**Comment by wookho** [comment]
@bnu 정말 이문제가 해결된다면 아이폰 유저 회원들에게 좀 덜 미안하고 할 것 같습니다. 요즘 저희 같은 생활밀착형 커뮤니티는 대부분 모바일에서 글 작성하고 피드백을 합니다. 90% 정도가 모바일이에요.

그런데 거기에 아이폰 비중도 높다보니 이분들이 어려움을 매번 접수하지만 제 개인 능력으로 해결을 해드리지 못해 죄송한 답변만 드리고 있습니다.

이게 해결된다면 정말 울것 같습니다 ㅜㅡ

**Comment by wookho** [comment]
@bnu 
https://github.com/ckeditor/ckeditor-dev/issues/498

위 이슈가 같은 내용인지 잘은 모르겠지만 혹시나 해서 링크를 남깁니다.
