### ISSUE TITLE
회원정보설정에서 자꾸 <enter> 가 추가됩니다.

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2340]
![image](https://user-images.githubusercontent.com/3683813/48037133-83682600-e1ae-11e8-93a7-4585c20925b7.png)

처음 설정할 땐 괜찮은데 추가 수정하면 띄어쓰기가 enter가 추가가됩니다;

**Comment by bnu** [comment]
예상되는 문제가 있긴하네요.
저걸 치환해주는 부분이 있는데...
정말 처음보는 코드네요.
