### ISSUE TITLE
작성글 보기에서 타이틀 옆에 댓글 개수 및 트랙백 개수 미출력

### ISSUE THREAD

**Issue by GconMaster** [xpressengine/xe-core#2347]
default 스킨에 사소한 문제가 있는 것 같습니다.
xe 회원 모듈의 default 스킨에서 document_list.html 21~27번째 줄의 코드 확인 필요해 보입니다.
댓글의 개수와 트랙백 개수를 보여주는 것 같이 보이는 데 실제로는 보여지지 않습니다.

**Comment by bnu** [comment]
트랙백 수 표시는 제거하고, 댓글 수는 정상적으로 표기되도록 문제를 고쳤습ㄴ디ㅏ.
