### ISSUE TITLE
템플릿 {@ {..} } 동작되게끔 건의 요청

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2350]
{@ .. }  이 안에 중복으로 괄호가 못 들어가는데 이거 동작되도록 구현은 안되나요?
저 안에서 foreach문 쓰려고 하면 다시 나와서  라던가 <block loop="">..</block>을 사용해야하는데요..좀 번거롭습니다;;

**Comment by bnu** [comment]
요청하신 템플릿 코드 개선은 불가합니다.
