### ISSUE TITLE
신디케이션 기본 코어에서 제거 건의

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2351]
1. 요즘 신디케이션 동작 확인해보면 
Invalid alliance site
이런 오류가 뜹니다.
2. 해당 오류는
https://webmastertool.naver.com/guide/syndi_guide.naver
제휴를 맺어야 가능합니다.
3. 신디케이션 제휴란
https://m.blog.naver.com/naver_webmaster/221280922245
신디케이션 발급 기준이 너무 까다로움.

굳이 코어에 포함될 정도로 이런 신디케이션 모듈이 더 이상 필요할까 싶습니다.

**Comment by bnu** [comment]
네. 정책이 변경되어 제거를 고려하고 있습니다.
