### ISSUE TITLE
메뉴 사이트맵에서 매번 저장이 아니라..

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2352]
사이트맵 메뉴를 다 정리한 다음에 저장하는 식으로는 어려울까요?

https://github.com/xpressengine/xe-core/issues/2157

닫은 이슈지만 역시 너무 불편합니다.

어려운게 아니라 움직일 때 디비상에 바로 저장하는게 아니라
일단 캐시 등에 저장해놓고
저장버튼을 누르면 디비에 저장하는 식으로는 하면 되지 않을까요..

구현이 쉬운 방법으로 한번 생각해봐주세요

**Comment by bnu** [comment]
변경이 쉽지 않습니다.
여전히 불편할 수 있는 부분이지만 처리하지 않습니다.
