### ISSUE TITLE
게시물 검색시 비밀글 댓글 노출됨

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2356]
통합검색에서 검색시 비밀글의 댓글 내용이 노출됩니다. 
비밀글로 같이 처리되어야 하지 않을까요?;

**Comment by bnu** [comment]
![2018-12-10 6 07 06](https://user-images.githubusercontent.com/53764/49721802-760af380-fca6-11e8-8421-7cc4f22731ac.png)

로그인 계정의 상태에 따라 다르게 보일 수 있습니다.
게시물에 권한이 없는 사용자에게는 '비밀글입니다'로 표기됩니다.
(이것도 이상하긴 하지만요)
