### ISSUE TITLE
php 확장모듈 igbinary 설치 후, 기존 글수정시 첨부파일이 에디터에서 사라집니다.

### ISSUE THREAD

**Issue by dmzvillager** [xpressengine/xe-core#2357]
https://github.com/xpressengine/xe-core/issues/2017#issue-203547136에서 이슈 등록을 했는데, 이슈가 닫혀 있네요. 
xe-1.11.1버전에서도 위의 닫힌 이슈와 같은 증상이 나타 납니다.

현재의 서버 환경입니다.
app : Apache/2.4.37 (Unix)
xe_version : 1.11.1
php : 7.3.0
db_type : mysqli_innodb
use_rewrite : Y
use_db_session : N
use_ssl : always
phpext : core, libxml, openssl, sqlite3, zlib, bcmath, bz2, calendar, curl, dba, fileinfo, ftp, gd, gettext, gmp, iconv, intl, mbstring, mysqlnd, mysqli, pdo_mysql, pdo_sqlite, phar, imap, shmop, simplexml, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, xml, xmlreader, xmlrpc, xmlwriter, zip, igbinary, ssh2, memcached, zend opcache

**Comment by YJSoft** [comment]
@dmzvillager 이슈가 닫혔다고 새로 여실 필요는 없습니다. 기존 이슈에 새로 댓글을 추가하셔도 됩니다.

환경 세팅후 살펴보겠습니다.

**Comment by YJSoft** [comment]
igbinary 설정파일에 `session.serialize_handler=igbinary` 등으로 지정되어 있는 경우 문제가 발생하는 것을 확인했습니다.

임시로 해당 설정을 찾아서(phpinfo중 Additional .ini files parsed에서 igbinary가 들어가는 파일을 찾으면 됩니다. CentOS의 경우 `/etc/php-zts.d/40-igbinary.ini`에 있습니다) 해당 문장을 지우거나 앞에 `;`를 붙여 주석처리후 웹서버를 재시작하면 됩니다.

**Comment by dmzvillager** [comment]
php.ini 파일에서 "session.serialize_handler=igbinary"로 설정 되어있으면, 방법이 없는 거네요.

**Comment by kijin** [comment]
#2358 패치 적용시 증상이 개선되는지 확인 바랍니다.

**Comment by dmzvillager** [comment]
해결되었네요!
감사합니다.

**Comment by bnu** [comment]
#2358 PR에서 해결되었습니다.
