### ISSUE TITLE
사이트 요소 중 일부가 서버내 다른 도메인으로 로딩됩니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2360]
빈도는 작지만 현상이 발생했을때 치명적인 영향을 주는 문제입니다. 이 문제는 오래전 부터 발생했는데 문의를 드려야 할 것 같아 작성합니다.

위젯에서의 목록 중 일 부 또는 해당 위젯의 전체 의 요소가 같은 서버의 다른 사이트(XE가 아닌 별개)의 도메인으로 로딩이 됩니다. 이미지 주소 등이...

이로 인해 ssl경고가 발생합니다. 인증서의 사이트이름과 실제 사이트이름이 일치하지 않는 경고인데 웹뷰 에서는 팝업으로 띄우기 때문에 사이트 운영에 큰 지장이 있습니다.

이 경우 운영자가 발견하고 캐시파일 재생성을 통해 제대로 다시 요소를 불러와야 하는 상태에 있게 됩니다.

**Comment by wookho** [comment]
같은 서버 내 문제가 되는 다른 도메인 사이트가 ssl을 사용하지 않아 봇등이 다른 사이트를 https로 안전하지 않음을 무시하고 접속 시도할 경우 ssl 사용중인 xe 사이트로 접속이 되는 것을 확인했습니다.

이 경우 해당 도메인으로 xe사이트가 열릴 수 있고 이때 캐싱이 이루어진 위젯의 경우 이미지 주소가 이 타 사이트 도메인으로 수집되는 케이스 같습니다.

이것이 어쩔 수 없는 상황이라면 혹은 서버단에서 처리되어야 할 상황이 명확하다면 close 해 주시고 혹은 XE에서 이런 접근 시 차단하는 것이 맞다면 개선 부탁드립니다.

**Comment by bnu** [comment]
@wookho 
서버 설정의 변경이 필요해 보입니다.

A(XE)도메인과 B(기타) 도메인이 모두 XE 페이지로 연결된 상황으로 보이며,
B 도메인이 XE 페이지로 연결되지 않도록 변경이 필요할 것으로 보입니다.

추측컨데, 모든 접근을 A도메인에 지정된 호스트 정보를 사용하도록 설정되어 있을 것으로 보입니다.
이와 같은 경우 악의적인 접근 시도도 빈번해서 설정 변경을 고려해보시는 것이 좋습니다.
또는, A, B 도메인 모두 XE 페이지로 연결되어 있다면 분리를 고려해보세요.

**Comment by bnu** [comment]
@wookho 443 포트에 대한 서버 설정의 문제로 보이네요.
호스트 설정에 도메인 없이 서버의 IP로만 지정되어 있거나 default로 설정 등의 이유로 443 요청 시 A 도메인 호스트 설정이 이용되고 있을 수 있습니다.

2개 이상의 도메인을 XE 페이지에 연결하여 사용하는 사례가 있으므로 이를 차단하는 것은 문제를 발생시킬 수 있으며, 서버 설정의 문제로 보이므로 조치해야 할 부분은 없어 보입니다.

**Comment by wookho** [comment]
@bnu 의견 감사합니다. ip로 지정한 부분이 문제가 될 수 있겠다는 생각은 했습니다. 해당부분을 보완하는 방법을 찾아보겠습니다. 감사합니다.

**Comment by wookho** [comment]
@bnu 그런데 검색을 해서 방법을 찾아보려고 하니 조금 이상합니다.
virtualhost 설정에 ip 말고 도메인을 직접 넣는 것이 가능한지 의문입니다.

<Virtualhost ip:443>
저는 여기에 제가 사용하는 XE 사이트 도메인만 지정한 상태이고
XE가 사용할 루트디렉토리만 지정했습니다.
</virtualhost>

여기서 서버에서 더 막아줄 수 있다는 의견이셨는데 없는 것 같습니다. 
물론 XE에서도 2개 이상 도메인을 사용하여야 하여 도메인을 특정해서 허용하기 어렵다면 해결점이 나오지 않을 수도 있는 문제일 수 있겠네요.

저는 분명히 A사이트만 443포트를 사용하여 ssl이 적용되도록 설정하였습니다.
그런데 B도메인을 누군가 강제로 443포트로 접속을 시도하면  위 설정과 무관하게 접속이 되어버립니다. 물론 XE의 버그는 아닐 겁니다. 

제가 서버 설정 이해를 못하는 부분이 있겠죠?

**Comment by bnu** [comment]
apache군요.
apache 버전에 따라 443 포트에 대한 분리가 지원되지 않을 수 있습니다.
https://xetown.com/?vid=&mid=home&act=IS&is_keyword=ssl xetown 등에서 도움을 구하실 수 있을 것 같습니다.

**Comment by wookho** [comment]
@bnu 개인적인 도움을 받고자 등록한 이슈는 아닙니다. 사실 저희는 해결을 했습니다. 해당 B 도메인에 ssl 을 적용해 주었습니다. 하지만 이부분은 문제가 될 수 있는 환경이 존재할 수 있어 이슈로 등록했던 부분입니다.

일단 저희는 도움이 필요하지는 않으니 잘 알겠습니다. 
답변 감사합니다.

**Comment by kijin** [comment]
제보된 이슈는 443 포트 분리와 관련된 특수한 상황이지만, 그렇지 않더라도 기본URL이 아닌 도메인으로 사이트가 로딩된 경우 로그인이 되지 않거나 모든 POST 요청에서 "잘못된 요청입니다"라는 에러가 나오는 등 여러 가지로 불편한 점이 있습니다.

국내 대부분의 웹호스팅 계정이 `고객아이디.호스팅업체명.com`, `고객도메인.com`, `www.고객도메인.com`, `m.고객도메인.com` 등 최소 3~4개의 도메인을 동일한 경로로 연결해 놓는다는 점을 감안하면 사용자 경험 개선을 위해 한번쯤 손봐줄 필요가 있는 문제입니다.

물론 .htaccess 파일을 수정하여 기본 도메인 외에는 모두 리다이렉트시키는 방법이 있지만, XE를 업데이트하면 종종 .htaccess 파일을 덮어씌우게 되므로 안정적인 해결책이 아닙니다. 보안 강화를 위해서라도 코어에서 URL 처리를 좀더 엄격하게 하고, 기본URL이나 xe_sites 테이블에 등록된 도메인이 아닌 경우 리다이렉트 처리해 준다면 좋겠습니다.
