### ISSUE TITLE
레벨,그룹 연동 캐시 문제인지 반영이 안되는 문제가 있습니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2361]
최근 패치 후 발생되는 문제 같습니다. 

레벨과 그룹을 연동시켜 특정 그룹의 권한자에게 실행 가능한 것을 제한해 놓았는데
회원들이 기준레벨을 인지 하고 있습니다. 그런데 해당 레벨에 도달했는데 권한이 없다고 문의가 들어오기 시작했습니다.

그래서 실제 관리자 페이지 가서 목록에서는 회원의 정보를 보면 이미 해당 그룹으로 변경되어 있습니다.
해당 회원을 관리자가 수정하려고 열어보면 수정페이지에서는 또 이전 그룹에 체크되어 있습니다.
그리고 일반 페이지에서 회원정보에는 아직도 기존 그룹으로 인식되고 있어 권한 등에서 문제가 됩니다.

실제 db에서 확인해봐도 db에는 이미 그룹이 변경되어 있습니다.

아마도 로그아웃 하고 로그인 하면 새로운 그룹으로 반영이 될 것 같지만 이것은 문제가 있어 보입니다.
레벨에 도달했을때 해당 그룹으로 이동이 즉시 되어야 합니다. 이건 기존에는 문제 없이 되었던 것으로 최근에 문의가 들어오기 시작했습니다.

**Comment by bnu** [comment]
관련 부분에 cache가 적용되었는데, 영향을 미쳤을 가능성이 예상되네요.
확인해보겠습니다.

**Comment by wookho** [comment]
@bnu 이문제 검토 부탁드립니다. 저희는 이 문제 때문에 포인트모듈 파일만 이전 파일로 사이트에서 운영중입니다.

**Comment by wookho** [comment]
지금 바뀐 서버에서 패치된거 적용해보니 이상이 없는 것 같아 이슈를 일단 종료하고 다시 현상이 확인되면 그때 다시 새로 오픈하겠습니다.
