### ISSUE TITLE
서드파티 모듈 사용시 seo 문제

### ISSUE THREAD

**Issue by eondcom** [xpressengine/xe-core#2364]
유료 컨텐츠인데, 콘텐츠판 모듈 이야기입니다.
라이믹스에서는 이 부분이 어떻게 돌아가는지 모르겠지만,
라이믹스+콘텐츠판모듈에서는 og:description이 제대로 들어가는데,
XE+콘텐츠판모듈에서는 og:description이 이상하게 먹힙니다.

https://xetown.com/questions/1144050
자세히 적어놓았는데,

https://xetown.com/point_contents/722475
이 글과
https://eond.com/shop/413817
이 글을 개발자도구로 열어서 og:description 부분을 검색해보시면...

라이믹스에서는 해당 모듈의 글설명이 제대로 들어가는데, XE에서는 해당 모듈의 글설명이 단지 첨부된 파일명으로만 읽혀지는거 같습니다.

여담인데, 제가 백단이 아직 어려워서 풀리퀘스트 요청하셔도 능력이 안됩니다. ㅠ_ㅠ/;

**Comment by bnu** [comment]
이슈 닫으신 것과 같이 오해가 있던 부분이었던 것으로 판단하고 이슈 처리하지 않겠습니다.

저도 여담으로.. 라벨이 PR 요청을 붙여 놓는 것은 이슈 작성자에게 요청한 것보다는
이슈 해결에 관심을 갖고 해결 가능하신 분에게 도움을 요청하는 목적으로 붙이는 것이니 부담가지지 않으셔도 됩니다 :)
