### ISSUE TITLE
크롬 73.0.3683.75 버전에서 페이지를 벗어나겠습니까 알림창이 발생합니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#2380]
안드로이드 웹뷰가 73.0.3683.75 버전으로 업데이트 되면서 나타나지 않아야 할 상황에서 "페이지를 벗어나겠습니까? 의 확인 알림창이 발생하는 것을 확인했습니다.

추천,비추천,신고 등 다양한 이벤트 후 발생하고 있습니다.

혹시나 해서 안드로이드 크롬의 같은 버전으로 설치해서 확인해봤더니 크롬에서도 동일한 현상이 발견되었습니다.

PC의 크롬의 같은버전에서는 확인을 해보지는 않았습니다.

크롬의 최신버전에서 XE의 js와 충돌이 발생하는 것 같습니다.

안드로이드 크롬의 경우 제 단말기의 구글플레이에는 아직 배포가 안되서 아래 링크에서 설치했습니다.
https://chrome.kr.uptodown.com/android/download

**Comment by wookho** [comment]
![Screenshot_20190317-231546](https://user-images.githubusercontent.com/6590236/54500071-3d8d4c80-495c-11e9-9f86-84118838be15.png)

XE공홈의 회원가입할때 페이지 전환될때 발생되는 알림창 입니다.




![Screenshot_20190317-231717](https://user-images.githubusercontent.com/6590236/54500081-4e3dc280-495c-11e9-9896-ab8bd10bf6d0.png)

XE공홈의 게시글 추천 후 확인창 확인을 누른다음 발생하는 알림창 입니다.

**Comment by wookho** [comment]
오늘 PC의 크롬브라우저가 같은 버전으로 업데이트되어 확인해 봤는데 이상이 없었습니다.

XE의 모바일에서 크롬 73.0.3683.75 에서 발생하는 상황입니다.

**Comment by bnu** [comment]
@wookho XE1 공홈에서만 발생하는 증상으로 확인했습니다.
facebook 이벤트 설정 때문인 것 같네요. 공홈에서 처리하도록 하겠습니다.

**Comment by wookho** [comment]
@bnu 아닙니다. 모든 XE 사이트에서 발생함을 확인했습니다. 저희도 그렇습니다.

**Comment by wookho** [comment]
@bnu 크롬 해당 버전으로 모바일에서만 현상이 발생합니다. 예를 들어 모바일 기기로 PC보기로 한다면 또 괜찮습니다. 

모바일에서 모바일로 는 당연히 위 현상이 발생을 하구요.
XE의 모바일에서  js  처리 과정에서 충돌이 납니다.

**Comment by bnu** [comment]
@wookho XE1 공홈 외 로컬에 설치한 환경에서 확인해봤으나 동일 증상이 없어서 공홈에서의 문제로 봤는데요.
확인할 수 있는 시나리오 있으면 알려주시면 다시 확인해보겠습니다.

**Comment by wookho** [comment]
@bnu 확인할 수 있는 시나리오는 이슈내용 안에 충분하다고 보는데 그렇지 않으시군요. 안드로이드 단말기에 크롬 73.0.3683.75 버전을 설치해주세요.

그리고 XE사이트에 방문하셔서 게시글 추천,댓글추천 등을 해보시면 됩니다. 공홈과 같이 가입단계에서도 애드온 사용등이 있으면 발생합니다.

**Comment by bnu** [comment]
@wookho 재현되지 않아서 그렇습니다.

http://jnvoqq.demo01.xpressengine.com:33653
로그인 계정 : admin@admin.net / NNZ7Om1@

여기서도 재현되나요?

**Comment by wookho** [comment]
@bnu 추가정보를 드리자면 PC의 크롬 같은 버전 일지라도 모바일보기로 바꿔서 테스트하면 재현됩니다. 즉, XE의 모바일쪽에서의 출동입니다.

**Comment by bnu** [comment]
@wookho 
http://jnvoqq.demo01.xpressengine.com:33653/index.php?mid=board&document_srl=99
이 게시물에 첨부된 스크린샷처럼 추천도 정상 동작했고, 다시 추천했을 때도 정상 동작했습니다.
새로고침과 관련된 alert은 XE1 공홈에서만 확인할 수 있었습니다.

**Comment by wookho** [comment]
@bnu 모바일뷰가 활성화된 사이트에서 테스트 해보셨나요? 
https://xepushapp.com/

이런곳에서 해보세요.

**Comment by wookho** [comment]
@bnu 실제 추천이 진행이 되어야 합니다.

**Comment by bnu** [comment]
@wookho 실제 추천 됐습니다. 스샷은 다시 시도했을 때 입니다. 스샷에 자세히 보시면 '추천 1'이라고 표기되어있습니다.

**Comment by wookho** [comment]
@bnu  해당 사이트가 모바일뷰로 해서 모바일이 분리되어있나요 ? 모바일에서 테스트 하셧나요?

**Comment by bnu** [comment]
@wookho 스크랩, 신고, 인쇄, 페북공유, 글쓰기, 회원가입, 비번찾기 등 제시하신 문제를 확인할 수 없었습니다.

ps. 모바일 모드(m=1)에서 확인했습니다.

**Comment by wookho** [comment]
@bnu  지금 알려주신 사이트에서 로그인해서 제가 추천할 수 있는 방법이 없어서 제가 위에 적어드린 사이트에서 캡쳐했습니다.

![스크린샷(40)](https://user-images.githubusercontent.com/6590236/54506894-24979200-4982-11e9-8ff1-4bddf285ee22.png)

**Comment by wookho** [comment]
@bnu PC에 크롬 73.0.3683.75 로 업데이트 하신다음,
PC에서 게시글 추천을 해보시고 모바일보기로 하셔서 추천을 해보세요.

**Comment by wookho** [comment]
@bnu 그리고 지금 예시로 주신 사이트는 모바일뷰를 사용하지 않고 있습니다.

**Comment by wookho** [comment]
@bnu 저는 이슈 등록에 테스트에 필요한 정보를 충분히 적었다고 생각했는데 지금 재현하시려는 상황에서 부족한가 봅니다. 

지금 XE공홈 만의 문제라고 결론을 내리시는 시점 다른 내부 사이트에서 발견하지 못했다라고 하셨고 그리고 저에게 테스트를 해보라고 알려주신 사이트의 경우,
제가 확인한 바로는 모바일뷰를 따로 쓰지 않는 설정이었습니다. 따라서 제가 제시한 모바일에서의 문제를 확인하지 못하시는게 너무 당연한 케이스였습니다.

모바일뷰 설정을 제대로 하신 후 확인 부탁드립니다. XE사이트 모바일사용을 하는 모든 사이트에서 해당 알림이 계속 뜨는 문제입니다. 물론 사용자의 크롬 브라우저 업데이트 시기에 따라 이 불편을 만나게 되는 시기는 각 방문자마다 다르게 되는 것이구요.

**Comment by bnu** [comment]
@wookho 문제 확인했습니다!!
어제는 더 이상 못 보고 좀 전에 다시해서 재현했고 원인 찾았습니다.

감사합니다!
