### ISSUE TITLE
보안패치 중 누락으로 보이는 수정사항

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xe-core#2383]
`insertModuleFileBox`(미수정)
https://github.com/xpressengine/xe-core/blob/f05b9670d5f262cbf62987c5fef5e2ceab911171/modules/module/module.controller.php#L1342

`updateModuleFileBox`(수정)
https://github.com/xpressengine/xe-core/blob/f05b9670d5f262cbf62987c5fef5e2ceab911171/modules/module/module.controller.php#L1294
1294번째 줄 `updateModuleFileBox` 함수에서는 $ext로 수정되었으나 `insertModuleFileBox` 함수에서는 그대로인데 실수로 보여 이슈 남깁니다.

**Comment by bnu** [comment]
확장자를 구하는 처리 방법이 다르나 결과는 같아 문제가 없는 부분으로 보입니다.
코드 정리가 되니 좋은 부분이긴 합니다만...

관련 부분은 보안취약점 패치와 직접 관련이 없는 부분이어서 처리하지 않도록 하겠습니다.
