### ISSUE TITLE
1.11.4 업데이트 후 사진파일 업로드시에 에러가 납니다.

### ISSUE THREAD

**Issue by OdengMul** [xpressengine/xe-core#2384]
Fatal error: Call to undefined function finfo_open() in \classes\security\UploadFileFilter.class.php on line 166

**Comment by bnu** [comment]
해당 서버의 PHP 버전이 5.3.0 버전보다 낮거나 windows 서버 환경인가요?
https://www.php.net/manual/en/fileinfo.installation.php

**Comment by OdengMul** [comment]
PHP 버전은 5.6.4 이구요.
Windows 7 환경의 APM입니다.

**Comment by bnu** [comment]
@OdengMul 
php.ini에 아래 코드를 추가 후 apache를 재시작 해보세요.

```
extension=php_fileinfo.dll
```

PHP 5.3.0부터 제공되는 함수인데 windows 환경 일부에서는 이 확장이 기본 제공되지 않을 수 있는 것 같습니다.

**Comment by OdengMul** [comment]
감사합니다. php.ini에 extension=php_fileinfo.dll 추가 후 해결 되었습니다.

**Comment by bnu** [comment]
@OdengMul 확인감사합니다 :)

**Comment by bysouh** [comment]
1.11.5에서도 파일첨부가 안되서 php.ini에 첨부함으로 해결했습니다.
감사합니다.

**Comment by ysk37ysk37** [comment]
> @OdengMul
> php.ini에 아래 코드를 추가 후 apache를 재시작 해보세요.
> 
> ```
> extension=php_fileinfo.dll
> ```
> 
> PHP 5.3.0부터 제공되는 함수인데 windows 환경 일부에서는 이 확장이 기본 제공되지 않을 수 있는 것 같습니다.

정말감사합니다. 
거의 3~4시간을 붙들고있던문제인데 
1.11.5 버전에서도 해당 이슈가 동일하게 발생하여 잘 해결되었습니다.
