### ISSUE TITLE
1.11.4 버전일때 게시판에 첨부파일 업로드가 안됩니다.

### ISSUE THREAD

**Issue by tubi55** [xpressengine/xe-core#2385]
밑에 파일첨부를 누르면 밑에 썸네일이 보이면서 본문삽입이라는 입력박스가 떠야되는데 그냥 닫히네요.

**Comment by bnu** [comment]
문제가 된 파일을 보내주실 수 있을까요?
bnu@xpressengine.com

**Comment by kijin** [comment]
#2384 와 같은 문제일 것 같습니다.

공식적으로 요구하지 않는 fileinfo 확장모듈을 아무 설명도 없이 갑자기 요구하기 시작하니 문제가 일어나는 것이 당연합니다. PHP에서 기본 제공되는 함수라는 말은 무의미합니다. 실제로 XE를 많이 사용하는 서버 환경에서 기본 제공되지 않을 가능성이 꽤 높은 확장모듈입니다.

전에는 필요하지 않았던 확장모듈이 앞으로는 필요하다고 정식으로 공지하고 마이너 버전을 변경하거나, 아니면 fileinfo 확장모듈이 없는 환경에서도 에러를 뿜지 않도록 조건문을 넣거나 대안을 마련해야 합니다.

**Comment by bnu** [comment]
fileinfo 모듈이 없을 때 문제를 수정하고, 설치 시 조건을 확인하도록 했습니다.
