### ISSUE TITLE
CAPTCHA 애드온 - img src="about:blank" 문제

### ISSUE THREAD

**Issue by DesignSORI** [xpressengine/xe-core#2387]
captcha.min.js 중간에 있는 <img src="about:blank" ~~~~ 때문에,
크롬 콘솔창에 오류가 표시됩니다.

about:blank:1 GET about:blank net::ERR_UNKNOWN_URL_SCHEME

위의 코드 중 about:blank 만 제거하면 위의 오류 문구는 표시되지 않습니다.
(about:blank 제거 후, 정상 작동 여부는 확인하지 못했습니다.)

**Comment by DesignSORI** [comment]
해당 코드를 제거해도, 실제 사용에 문제는 없습니다.
about:blank 제거 부탁드립니다.

**Comment by kjin1** [comment]
같은 문제가 있어서
`<img src="//:0">`
로 처리했습니다.

https://stackoverflow.com/questions/19126185/setting-an-image-src-to-empty/28486885

**Comment by clamo** [comment]
캡챠를 켜면 에러가 나서 어딜 수정해야 하는지 막막했는데... 좋은 정보 감사합니다.
브라우저들이 failed 에러를 내면 수정되어야 하는게 맞다고 생각합니다.

**Comment by bnu** [comment]
src 속성을 제거했습니다.
