### ISSUE TITLE
에드온 폴더 이름 정규식 개선

### ISSUE THREAD

**Issue by LIFOsitory** [xpressengine/xe-core#2393]
현재 addons 폴더 리스트를 불러오는 정규식은 `/^([a-zA-Z0-9-_]+)$/` 입니다.

해당 정규식은 하이픈(-)을 포함하고 있는데 이 하이픈(-)이 xe 상에서는 문제를 일으키는 모양입니다. 

정규식에서 하이픈(-)을 제거하는 게 나아 보입니다.

https://xetown.com/topics/1208070#comment_1208159

**Comment by bnu** [comment]
하이픈을 패턴에서 제거했습니다.
