### ISSUE TITLE
체험하기 로그인 이슈

### ISSUE THREAD

**Issue by hyunalee419** [xpressengine/xe-core#2400]
시도 1
- 메인메뉴 XE 체험하기 접속 > 체험하기 버튼 클릭 > 네이버 로그인 > 에러 페이지
에러페이지: http://demo.xpressengine.com/auth/naver/request_token/callback?code=IEiCgVHYrmZ6yPkK9H&state=e54601b655466f269bca4fd3f08e3997

시도 2
- 회원가입 후 로그인 > 메인메뉴 XE 체험하기 접속 > 체험하기 버튼 클릭 > 네이버 로그인 > 에러 페이지
에러페이지: http://demo.xpressengine.com/auth/naver/request_token/callback?code=IEiCgVHYrmZ6yPkK9H&state=e54601b655466f269bca4fd3f08e3997

로그인을 하고 체험하기 버튼을 눌러도 자꾸 에러가 발생하여 데모를 돌릴 수가 없습니다.

**Comment by Lastorder-DC** [comment]
https://www.xpressengine.com/index.php?mid=qna&document_srl=23288661#comment_23288687

로그인시 모든 정보 제공동의를 하셔야 합니다. 체험하기 서비스 네이버 연동이 해당 기능(정보 선택적 제공)이 없던 시절 만들어진거라 하나라도 빠지면 오류가 나는것으로 보입니다.

**Comment by hyunalee419** [comment]
감사합니다. 😄
