### ISSUE TITLE
글쓰기에서 '미리보기' 버튼 클릭시 html 소스가 노출되는 현상

### ISSUE THREAD

**Issue by sejin7940** [xpressengine/xe-core#2408]
XE 1.11.0 이후에서 글쓰기에서 '미리보기' 버튼 클릭시 html 소스가 노출되는 현상이 발생합니다

미리보기 기능 자체는 Core 자체에 포함이 되어있는 기능이고
게시판 스킨에 따라 '미리보기' 기능을 지원하는 경우가 있습니다.
( 예를들면 스케치북 스킨 )

단, 최신 XE 에서 보안때문에 변경된 부분에 의해 
미리보기시 html 태그가 그대로 노출되는 현상이 발생합니다.

modules/document/tpl/preview_page.html 에서

{$content}

를 아래걸로 변경

{$content|noescape}

**Comment by bnu** [comment]
감사합니다. 제안하신 것처럼 수정했습니다.
