### ISSUE TITLE
휴지통 목록에서 휴지통에 담긴 글을 볼때 html 소스가 노출되는 현상 수정방법

### ISSUE THREAD

**Issue by sejin7940** [xpressengine/xe-core#2414]
XE 1.11.0 이후에서
관리자페이지->휴지통  에서 휴지통에 담긴 글을 볼때..  html 소스가 노출되는 현상 이 생기는데
이는 최신 XE 에서 보안때문에 변경된 부분에 의해 생긴 버그네요

modules/trash/tpl/trash_view.html 에서

{$oOrigin->content}

를 아래걸로 변경하면 됩니다.

{$oOrigin->content|noescape}

**Comment by bnu** [comment]
감사합니다. 제안하신 것처럼 수정했습니다.
