### ISSUE TITLE
1.11.6 업데이트 이후 관리자 페이지에 일부 모듈 HTTP ERROR 500에러

### ISSUE THREAD

**Issue by bimileya** [xpressengine/xe-core#2426]
1.11.6 업데이트 이후 관리자 페이지에서 아래의 모듈을 클릭하면 아래의 스크린샷 처럼 HTTP ERROR 500에러가 납니다. 
사이트 접속은 잘되고 게시판에 글 등록도 잘되는데 이상하게 게시판 설정이나 아래의 모듈 등을 클릭하면 에러가 발생하네요.

- 커뮤니케이션
- 메뉴
- 통합검색
- 게시판
- 페이지

![image](https://user-images.githubusercontent.com/8811581/95005438-b5ff4100-05c6-11eb-8b8a-b4b5ccdb2ca5.png)

app : Apache
xe_version : 1.11.6
php : 7.1.33
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : always

**Comment by Lastorder-DC** [comment]
오류 로그를 올려주세요. 호스팅 사용중이신 경우 업체에 문의해 보셔야 할 수 있습니다.

**Comment by bimileya** [comment]
모듈 폴더에보니 오랜전에 인스톨한 youtube 모듈이 있었는데 이 모듈이 php 5.5에서는 정상 작동을 하지만 7.0에서 작동을 하지 않아서 위와 같은 에러 메시지가 나온것 같습니다. 모듈 삭제 이후 게시판 모듈과 사이트 메뉴 편집 등에 위와 같은 오류 없이 잘 작동이 되는 것을 확인하였습니다.
