### ISSUE TITLE
'파일첨부' 버튼이 안눌러 집니다. ㅠㅠ

### ISSUE THREAD

**Issue by iojesus80** [xpressengine/xe-core#2429]
![xxxxxxxxxxx](https://user-images.githubusercontent.com/78575921/106980347-59de4080-67a3-11eb-8632-3a7be7d17b5e.JPG)
어떻게 해야할까요?

나머지 버튼은 눌러집니다.

사이트 주소
(http://www.kceducation.or.kr/index.php?mid=media_01&listStyle=list&act=dispBoardWrite)

도와주세요. 

010-8260-6922 
한국진로개발교육원
조형익팀장입니다.

감사합니다.

**Comment by Lastorder-DC** [comment]
해당 문제의 경우 에디터 설정에서 XpressEditor 대신 CKeditor 선택하시면 됩니다.
참고로 XE는 사실상 개발 및 지원이 종료되었습니다. 이곳에 올리셔도 지원 받기 힘드실겁니다.

p.s.) 전화번호는 삭제하시는게 좋으실것 같습니다.
