### ISSUE TITLE
게시물 이동시 확장 변수가 잘못 들어가는 문제

### ISSUE THREAD

**Issue by lansi951** [xpressengine/xe-core#329]
게시물 이동시 eid 기준으로 들어가야 하는데 확장변수 인덱스 기준으로 값이 들어가는 것 같습니다.

그래서 게시판끼리 서로 다른 확장 변수가 있을 때 값이 잘못 들어갑니다.

board에서 옮김.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
