### ISSUE TITLE
load target으로 JS 파일 불러올 때 쿼리를 넣으면 불러오지 못함

### ISSUE THREAD

**Issue by lansi951** [xpressengine/xe-core#347]
``` html
<load target="js/admin.js?v=1" />
```

뒤에 쿼리가 붙으면 파일 자체를 불러오지 않습니다.

**Comment by KaironMoon** [comment]
꾸잉뀨... "하지마"라니 답변이 참 당혹스러운...
load자체는 어쩔수 없지만,
<load target="js/script.js" />
->
{@
	Context::addHtmlHeader('<script type="text/javascript" src="js/script.js?ts='.time().'"></script>');
}
요런 식으로 템플릿 내에서 변경 가능합니다.
