### ISSUE TITLE
모바일 게시판에서 파일첨부/본문수정이 가능하도록 

### ISSUE THREAD

**Issue by bigsummary** [xpressengine/xe-core#394]
모바일 게시판에서도 [파일첨부]와 [본문수정]이 가능했으면 좋겠습니다.
댓글 수정 관련 이슈는 이미 등록되어 있는 관계로 작성하지 않았습니다.

**Comment by misol** [comment]
#1086 해결시 함께 고려해주셨으면 좋겠습니다. @bnu
