### ISSUE TITLE
사이트맵에서 메뉴이름에 메뉴설명 추가 건의

### ISSUE THREAD

**Issue by treasurej** [xpressengine/xe-core#476]
메뉴 이름에 메뉴설명이 필요한데요,
현장에서는 아주 많이 사용합니다.
하지만, 메뉴 설명 기능이 없어 
임시적인 방편
1. 메뉴를 이미지로 하거나
2. 메뉴 이름에 콤마로 해서 나누는 방법 (explode(",")})

그렇지만 이런 방법들은 다국어 지원시에도 문제되고,
모든 모듈과 레이아웃에서 explode를 사용하는 게 아니라
나중에 레이아웃을 바꾸게 되면 콤마를 다 지워야 되구요..

스킨 제작자는 이것으로 다양하게 활용할 수 있어요.
메뉴 아이콘을 부트스트랩을 사용할 때 메뉴 설명에 fa-desktop 이렇게 넣으면 많은 활용이 가능해요.
메뉴 설명을 넣어서 부연설명이나 부가 기능을 활용할 수 있어요.

현장에서는 이렇게 활용이 많이 되고 있는데
꼭 반영 검토좀

 부탁드려요~~~

![menuplus](https://f.cloud.github.com/assets/4101147/2157570/f323bbf8-947e-11e3-8bd7-0dac1176aa38.png)
![ex1](https://f.cloud.github.com/assets/4101147/2157571/f33119ba-947e-11e3-8f74-3f8430772e47.png)

**Comment by YJSoft** [comment]
#1550
