### ISSUE TITLE
[1.7.4] 업데이트 후 신규회원의 경우 카페XE의 카페가입이 안 됩니다

### ISSUE THREAD

**Issue by binamu** [xpressengine/xe-core#481]
XE1.7.4 업데이트 후 나타나는 사이드 이펙트라 생각하여 이곳에 이슈 등록합니다.
(그 전 버전에선 이런  문제가 없었거든요.)

카페로 만들어진 사이트가 아닌 기본 사이트 신규 회원가입과 로그인에는 아무런 문제가 없습니다.
하지만 위 기본 사이트의 카페XE로 만들어진 사이트의 경우 기존 회원 로그인에는 아무런 문제가 없지만, 신규회원의 경우 카페 가입 버튼을 누르면 '잘못된 요청입니다.'라는 메시지만 띄우며 카페 가입을 할 수가 없습니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
