### ISSUE TITLE
oembed 애드온 동영상 인식 문제

### ISSUE THREAD

**Issue by socialskyo** [xpressengine/xe-core#501]
인식 되는 것과 안되는 것의 차이를 일단 모르겠습니다.

되는 것이 있고 안되는 것이 잇습니다.

안되는 것을 보면 `<br>` 태그등이 주소에 따라 붙는 듯 합니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
