### ISSUE TITLE
1.7.4 기본스킨(default)에서 id/pw 찾기 오류

### ISSUE THREAD

**Issue by samswnlee** [xpressengine/xe-core#518]
원인을 찾을수 없다고 계속 하셔서 
다른 스킨으로 설정후 id/pw찾기 해보니 정상작동함.

그래서 직접 뜯어볼려고 기본스킨을 보니
action="/" 부분에 . 누락되었음

action="./" 으로 변경후 정상작동 
확인요망합니다.

https://github.com/xpressengine/xe-core/blob/master/modules/member/skins/default/find_member_account.html

**Comment by gusdnv112** [comment]
바꿔도 오류가 뜨는데 어떻게 해야할까요
error return url 이라고 에러가뜨는데
