### ISSUE TITLE
일부 브라우저에서 파일 다운로드가 불가능한 버그

### ISSUE THREAD

**Issue by iodes** [xpressengine/xe-core#523]
XE 1.7.3.8 에서 Android KitKat 이상에서 첨부 파일 다운로드가 불가능합니다.
다운로드를 실패했다고 나오며, 다운로드가 되지 않습니다.

신기한건, PC 또는 젤리빈의 기본 브라우저에서는 다운로드가 잘 됩니다.
젤리빈에서도 WebView 를 활용한 서드 파티 앱에서는 잘못된 요청이라고 나옵니다.

동일한 서버의 1.5.X 버전에서는 모든 환경에서 정상 다운로드 가능합니다.

아마 저의 생각으로는, 안드로이드 OS 문제가 아니고
브라우저에 따라 지금 다운로드가 되는게 있고 안되는게 있는것 같습니다.

XE 1.7.3.8 : http://testxe.styleroot.com/index.php?mid=test&document_srl=106
XE 1.5.X : http://www.webengine.co.kr/freeboard/12434

둘다 동일한 서버입니다.
1.7.3.8 이하 버전은 테스트 해보지 못해서 어떤지 모르겠습니다만,
1.7.3.6 에서도 잘못된 요청이 나온다는 이슈가 있는걸로 보아
그 이하에서도 문제가 있을것 같습니다.

한번 확인 해주시면 감사하겠습니다. ^^

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
