### ISSUE TITLE
포인트 그룹 연동 문제

### ISSUE THREAD

**Issue by socialskyo** [xpressengine/xe-core#526]
http://www.xpressengine.com/qna/22621696
http://www.xpressengine.com/qna/22578212
http://simulz.kr/xe/board_xe_qna/525806

잘되는 것처럼 보인다 싶더라도...몇몇 회원들은 잘못된 경우가 많이 나옵니다.
예를 들어 레벨 2 이상 정회원 인경우
1. 준회원에 머물러 있는 문제

레벨 3 부터 추천회원 인경우
1. 정회원은 빠지고 추천회원만 되어 있거나, 추천회원으로 변경이 안되어 있거나..

아무튼 그룹 연동에 문제가 있습니다. strict 하게 포인트랑 연동 되었으면 합니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
