### ISSUE TITLE
board 확장변수 정렬(숫자) 관련...

### ISSUE THREAD

**Issue by narooter** [xpressengine/xe-core#535]
1.7.4 로 바뀌면서 확장변수 정렬과 검색 기능이 수정되어 잘쓰고 있습니다.
다만 텍스트값으로 모두 인식해서 숫자 정렬이 안되는데 해결책이 있을까요?
개인적으로는 value2 필드를 DB에서 bigint형으로 만들어거
값을 같이 넣어주고 sort 순서를 먼저 value2 에주고 value를 그다음으로 주고 있습니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
