### ISSUE TITLE
멀티도메인 지원과 레이아웃을 모듈별로 선택하지 않고 메뉴별로 선택하였으면 합니다.

### ISSUE THREAD

**Issue by narooter** [xpressengine/xe-core#536]
현재 바로가기로 하나의 모듈을 여러개의 메뉴에서 사용할수 있지만
하나의 모듈에서는 하나의 레이아웃밖에 선택을 못하다보니
멀티도메인으로 여러개의 사이트에서 하나의 모듈을 재사용할수가 없습니다.
제가 생각하는  것은
멀티도메인이 지원이 되어 도메일별로 레이아웃과 메뉴를 구성할수 있고
하나의 모듈을 각각의 레이아웃과 메뉴에서 호출할수 있었으면 합니다.
xe_sites 테이블이 있는걸 보면 멀티도메인은 어느정도 구상을 하고 계신것 같고
레이아웃은 xe_modules 에서 선택하기보다 xe_menu 테이블에서 선택하도록 한다면
바로가기 메뉴를 이용해서 하나의 모듈에 여러개의 레이아웃과 메뉴를 연결할수 있을것으로 기대합니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
