### ISSUE TITLE
모듈 설정 변경시 바로 반영 안되는 이슈

### ISSUE THREAD

**Issue by upgle** [xpressengine/xe-core#568]
회원설정 -> 회원가입 허가 OFF 후 저장 과 같이 모듈 설정 시 바로 반영 안되는 이슈.

확인 결과 다른 모듈 설정 한번에 반영이 안되고 두세번의 새로고침 후 반영이 됩니다.
1.7.3.8에서 발견되지 않은 이슈로 캐시 문제로 확인됩니다.

	// Insert module config
	$oModuleController = &getController('module');
	$oModuleController->insertModuleConfig('모듈명', $args);

**Comment by delphixe4** [comment]
APC 캐싱을 적용하고 있으신가요?

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
