### ISSUE TITLE
사이트맵 목록에서 사이트맵의 접힘 상태를 유지하도록 개선 필요

### ISSUE THREAD

**Issue by bnu** [xpressengine/xe-core#603]
사이트맵 관리 시 사이트맵을 접힌 상태로 두고 메뉴 변경 시 접힘 상태가 유지되지 않아 관리의 어려움이 있음.

**Comment by akasima** [comment]
기본으로 폴더를 접힌 상태로 두고 open된 폴더들의 정보를 cookie에 담아서 사용하도록 처리했습니다.

@bnu 요청으로 메뉴 찾기 기능도 추가했습니다. :)

**Comment by bnu** [comment]
=_=b
