### ISSUE TITLE
PHP 5.4 에서 content 위젯으로 rss 불러오기

### ISSUE THREAD

**Issue by myclements** [xpressengine/xe-core#624]
XE의 게시판, 또는 textyle (upgletyle) 에서 rss 피드를 공개하고,
웹 브라우저에서 그 해당 rss 주소를 입력하면 어느 버전이든 아무런 문제 없이 제대로 출력이 잘 되고 있습니다.

PHP 5.2. 버전에서 content 위젯을 통해서 rss 피드를 받아서 최근 글을 출력하는것 역시 아무런 문제가 없습니다.

그런데 똑같은 상황에서 PHP 버전을 5.4 로 변경하면, 웹 브라우저에서의 rss 출력은 아무런 문제가 없으나,
content 위젯에서는 최근글 등을 전혀 불러오지 못하고 있습니다.

**Comment by misol** [comment]
혹시 XML 파서가 대소문자를 구분하게 변경되었나요?

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
