### ISSUE TITLE
외부 링크 이미지 ratio 설정시 썸네일 생성문제

### ISSUE THREAD

**Issue by AlohafromHell** [xpressengine/xe-core#626]
외부링크 이미지일 경우 ratio로 설정시 썸네일이 생성이 않습니다.
(목록설정 요약 추가를 해도)

document.item의

// if($_w<$width || $_h<$height) continue;

를 삭제해야만 썸네일이 생성됩니다.

왜 그런걸까요;;

**Comment by bnu** [comment]
dup #1011
