### ISSUE TITLE
사이트 메뉴 편집에서 레이아웃 변경시 에러

### ISSUE THREAD

**Issue by SergioPark** [xpressengine/xe-core#639]
레이아웃을 선택하고 저장을 누르면 '서버에 요청중입니다...'가 계속 떠있고, 다른 버튼을 눌러 관리페이지 첫 화면으로 이동하면 page 모듈을 업데이트 하라고 함.
작업하던 사이트 메뉴 편집 해당 메뉴로 가면 page(모듈이 존재하지 않음)이라 나옴.
캐시파일 재생성하고 다시 들어가면 외부 페이지로 작업한 것이 위젯 페이지로 바뀌어 있음. 당연히 아무 내용도 없이.
어떤 때는 정상적으로 되고, 어떤 때는 위의 증상이 계속 반복됨.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 새로 작성해주시거나 '@bnu '를 포함하는 내용으로 댓글을 남겨주시기 바랍니다.

예시)
