### ISSUE TITLE
페이지 관리에서 모듈분류

### ISSUE THREAD

**Issue by fromhere** [xpressengine/xe-core#71]
아래에 게시판관리에서 모듈분류 이슈제출했습니다.

이번에는 페이지 관리에 들어가서 모듈분류를 선택하면

분류가 안된 모듈 -  "없음"으로 분류된 모듈들과
cafe등에서 생성된 페이지 - "가상사이트"로 분류된 모듈들이 분류항목에 나타나지 않습니다.

때문에 분류가 안된 모듈들과 Cafe등에서 만들어진 모듈들만 따로 모아 볼 수없습니다.
이것도 버그 같은데.. 수정부탁합니다

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
