### ISSUE TITLE
멀티브라우저(user-agent) 자동 로그인 지원

### ISSUE THREAD

**Issue by jdssem** [xpressengine/xe-core#711]
현재 xe의 자동로그인은 아이디, 비밀번호, user-agent 를 md5로 hash해서 xeak 쿠키에 굽는 것으로 알고 있습니다. 그러다 보니 다른 브라우저에서 자동로그인을 하면(user agent가 바뀌면) 자동로그인이 풀리게 되어있더라고요.

요즘 xe와 연동된 iOS용 앱을 개발중인데 로그인 유지를 위해 자동로그인 쿠키를 사용하려다가 이 사실을 알고 접게 되었습니다만, 다양한 브라우저에서도 자동 로그인 기능이 지원되었으면 합니다. 또 개인정보 페이지에서 자동로그인이 설정되어 있는 기록들을 보고 자동로그인을 만료시킬 수도 있으면 좋겠고요.

**Comment by misol** [comment]
https://github.com/xpressengine/xe-core/issues/987 와 유사한 이슈입니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
