### ISSUE TITLE
비밀번호 변경 유도 페이지에 [다음에 변경하기]버튼을..

### ISSUE THREAD

**Issue by Inhan1098** [xpressengine/xe-core#712]
비밀번호 변경 주기가 되면 [비번 변경 유도 페이지]가 출력되는데요.
여기서 [다음에 변경하기]버튼이 츨력되면 좋을것 같아요.

다른것에 보면 모두 있는데, 이게 없다보니가 로그인마다 출력되서 불편하네요.
클릭시 기간이 초기화된다거나 직접 변경가능하도록 하면 좋을듯 싶어서 의견 남깁니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
