### ISSUE TITLE
기본 캡챠애드온 설정시 익스플로러11에서 게시글이 이중으로 생성 됩니다

### ISSUE THREAD

**Issue by sin007x** [xpressengine/xe-core#723]
기본 캡챠애드온 설정시 익스플로러11에서 게시글이 이중으로 생성 됩니다
스팸때문에 캡챠애드온을 설정했습니다 그런데 게시판 본문에 글을 적고 등록 버튼을 누르면 캡챠문구가 뜹니다 그걸 틀리게 적고 확인 누르면 다시 다른 캡챠가 뜨고 이번에는 똑바로 적고 확인을 누르면 게시글이 중복으로 등록되어 2개씩 올라갑니다 
캡챠를 틀리지 않고 한번에 정확하게 적어서 등록을 하면 정상적으로 1개만 등록됩니다 
어떻게 해결해야하나요 
스킨이나 레이아웃은 스케치북5 쓰고 있습니다.
버전은 최신버전 1.7.5 버전입니다 부탁드립니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
