### ISSUE TITLE
서버 재부팅 후 게시판 관리에서 게시판 주소가 제대로 연결되지 않는 문제.

### ISSUE THREAD

**Issue by wbqd** [xpressengine/xe-core#734]
![2014-05-19 5 40 15](https://cloud.githubusercontent.com/assets/3282649/3011868/a00507da-df31-11e3-97c7-146a3b4a149f.png)
![2014-05-19 5 40 23](https://cloud.githubusercontent.com/assets/3282649/3011871/b398da60-df31-11e3-9446-db051d5c7521.png)
AWS EC2 사용 중에 서버를 재부팅하면 게시판 주소가 사이트 도메인이 아닌 AWS EC2 디폴트 도메인으로 바뀌는 문제가 있습니다. 현재 해결 방법으로써는 `설정 > 일반 > 고급 > 기본 URL` 을 확인 후 저장하면 제대로 돌아오긴 합니다만. 코드 상에서 현재 도메인 확인하는 로직 개선이 필요합니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
