### ISSUE TITLE
외부이미지 섬네일생성시 가로 1280px 넘어갈경우 생성되지않음

### ISSUE THREAD

**Issue by mAKEkr** [xpressengine/xe-core#790]
총 3종의 샘플로 테스트 해보았습니다.

http://24.media.tumblr.com/a6e26451c90c25b6fae222c5c0a032d9/tumblr_n76t0oir8H1r5ml59o1_r1_1280.jpg (가로 1280이상)
http://i1.ytimg.com/vi/Gn7jGyb9PIg/maxresdefault.jpg (가로 1280미만)
http://cfile30.uf.tistory.com/image/25487C34529B3750302D77 (외부링크 차단시)

총 3개의 파일로 시험해보았으나 외부링크 차단시에는 섬네일 자체가 생성되지 않는것에 비해, 외부링크가 허용된 위의 두 이미지들에 대해서는 가로 1280px이 넘어갈경우 섬네일이 제대로 생성되지 않는걸 확인했습니다.(1920x720 ratio 기준으로 생성, 240x180 crop 기준으로 생성 총 2개 시험해보았습니다)

[XE Server Environment 2014-06-15]

location : ko
package : XE
host : http://ake.kr/
app : Apache
xe_version : 1.7.5.1
php : 5.2.17
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : libxml, fileinfo, bcmath, bz2, curl, dba, simplexml, gettext, gmp, iconv, mbstring, mcrypt, mysql, mysqli, odbc, openssl, pdo_sqlite, pdo_mysql, exif, snmp, sockets, sqlite, xml, xmlreader, xmlwriter, zip, zlib, gd, pdf, soap, eaccelerator, zend optimizer
module : adminlogging(1.7), board(1.7.2), imageprocess(1.3.0.3), krzip(1.0), seo(0.1), syndication(3.1.0-beta.2)
addon : adminlogging(1.7), ajaxboard(1.5.6), captcha_member(1.7), fa_loader(1.0), jqueryuicdn(1.0), multimedia_thumbnail(1.0), oembed(1.0)
layout : makekr(), xe_official(1.7), user_layout(1.7)
widget : counter_status(1.7)
widgetstyle : simple(1.7)
max_file_uploads : 20
post_max_size : 50M
memory_limit : 128M

**Comment by qw5414** [comment]
`if($_w<$width && $_h<$height) continue;`
