### ISSUE TITLE
예전처럼 자체/외부 CDN이 이용가능한 형태로 되었으면 합니다.

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#793]
과거 XE에서 CDN을 중단하면서, 관련된 코드가 전부 삭제된 것으로 알고 있습니다. 그래서 자체적으로 CDN(cafe24 무료CDN 등)을 구축했거나 외부의 CDN(jsdelivr)을 사용하려면 현재로서는 직접 core를 수정해야 하는 것 같습니다.

관리자를 위한 UI까지는 없더라도, 예전처럼 자체 또는 외부CDN 을 간단한 설정(config.user,nic.php)에 만으로 쉽게 사용이 가능했으면 좋겠습니다.
http://www.xpressengine.com/tip/22424908

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
