### ISSUE TITLE
모듈복사시 에러

### ISSUE THREAD

**Issue by phin1000** [xpressengine/xe-core#810]
1.7.5.3에서

사이트 메뉴편집에서  모듈을 복사할 때 
복사된 모듈의 메뉴타입이  undefined(모듈이 존재하지 않음)로 됨.
삭제하려하면 "시작메뉴에 포함된 것은 삭제할 수 없습니다." 라는 메시지 출력.

고급>설치된 모듈에서 여러개 복사할 경우 복사가 안됨.

페이지, 게시판 모두 같은 현상입니다.

-------------------------

2개 이상 복사할 경우에만 에러가 발생합니다.
사이트 메뉴편집에서 1개씩은 정상작동하나
하위메뉴가 있어 결과적으로 2개이상 모듈일 경우 에러 발생

고급> 설치된 모듈에서도 1개씩은 정상작동
2개 이상은 생성 안됩니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
