### ISSUE TITLE
파일 첨부swf이실행되지않고 

### ISSUE THREAD

**Issue by HEJ5** [xpressengine/xe-core#895]
에디터로 swf파일 첨부하면 실행이않되고 
비활성화되어 버립니다 (에디터에 점선이 생겨버립니다)
버전이 1.7.5.7
버전업그레이드한후 기존의 swf파일들이 (파일첨부시킨 swf전부 비활성화되어) 점선만생김

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
