### ISSUE TITLE
load문 외부 파일 경로 http와 https 붙이지 않게 하기

### ISSUE THREAD

**Issue by treasurej** [xpressengine/xe-core#910]
load target="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
이렇게 http: 나 https: 를 붙이지 않는 이유는
현재 접속된 주소(http, https)에 따라 불러오게 하는 요즘 많이 사용되는 방법입니다.

그런데 load 문에서는 꼭 http나 https를 붙여야 되더라구요~

**Comment by bnu** [comment]
merged #1290
