### ISSUE TITLE
JS 보안 로그인 건의

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#923]
XE자체에 기본적으로 Javascript를 이용한 로그인/회원가입시 비밀번호 및 기타 중요한 정보를 암호화 하여 전송하는 기능 내장하는 것에 대해 어떻게 생각하시는가요?

ex) http://www.jcryption.org/

예전에 3rd party의 addon 형태로 처리하려고 했으나, core를 건드리지 않고서는 수정이 불가능 하더군요. 단순 http post나 get은 그래도 core에서 js 파일 하나만 건드리면 되나, 이 경우에도 act나 mid등은 암호화 자체가 불가능 하였습니다.
ajax의 형태는 xe-core를 더 많이 손봐야 하는것 같더군요...

이러한 기능이 내장되면, 클릭한번에 편리하게 보안을 증진시켜 준다는 점에서 유용할 것 같습니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 새로 작성해주시거나 (멘션)'@bnu'를 포함하는 내용으로 댓글을 남겨주시기 바랍니다.

예시) _@bnu 이 버그가 여전히 문제가 있습니다_
