### ISSUE TITLE
회원가입후 특정 URL 이동 가능하게 하기.

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#943]
현재는 회원가입을 하고 난 뒤, 특정 메뉴로 이동시킬수는 있으나, 특정 URL로 이동 시킬수 없는점에서 아쉽다고 생각하고 있습니다.

회원가입 후에 특정 메뉴 뿐만이 아니라, 특정 URL로도 이동이 가능했으면 합니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
