### ISSUE TITLE
IE11에서 게시판 url링크 기능이 비정상으로 작동하는 문제

### ISSUE THREAD

**Issue by styledd** [xpressengine/xe-core#956]
안녕하세요.^^
현재 IE11에서 xe 게시판의 문서작성 기능중 하나인 url링크걸기 버튼이 제대로 작동하지 않습니다.

글자에 드래그한 뒤 url 링크버튼을 눌러 링크를 걸 경우 태그가 제대로 먹히지 않으면서 단독링크가 걸려버립니다.

xe사이트 사용자분들에게서도 언급되던 문제인지라 말씀드립니다.

해당증상을 즉석 확인하여 보실 수 있는 테스트 사이트는
http://strut123.hosting.paran.com/xe/board1

xe버전은  1.7.5.6이며 기타 추가 애드온,모듈등을 일체 적용하지 않았습니다.
1.7.5.7에서도,서로 다른 호스팅환경에서도 동일한 증상입니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
