### ISSUE TITLE
Android Chrome에서 데이터 사용량 줄이기 옵션을 쓰면 로그인 유지가 안됨.

### ISSUE THREAD

**Issue by dorami** [xpressengine/xe-core#976]
Android Chrome에서 데이터 사용량 줄이기 옵션을 쓰면 로그인 유지가 안됩니다.
네이버나 기타 사이트에서는 되는거 같은데, xe에서는 로그인 유지가 안됩니다.

사용하고있는 안드로이드 정보는 아래와 같습니다.
Android: 4.4.4 KitKat - Nexus4
Chrome: 37.0.2062.117

**Comment by misol** [comment]
https://github.com/xpressengine/xe-core/pull/982 와 함께 이 이슈도 처리 된 것 같습니다 @bnu
