### ISSUE TITLE
swfupload security issue

### ISSUE THREAD

**Issue by ajkj** [xpressengine/xe-core#983]
swfupload에 security issue가 있습니다.

swfupload.swf의 history를 조회해보니 2011년 이후로 전혀 업데이트가 되지 않은것 같습니다.
https://github.com/xpressengine/xe-core/commits/master/modules/editor/tpl/images/SWFUpload.swf

security issue내용은 https://github.com/WordPress/secure-swfupload 에서 확인이 가능합니다.

그러나 as파일을 어떻게 swf에 적용해야 하는지는 모르겠습니다.
제가 flash가 설치되어 있지 않기도 하고, 컴파일(?)을 하는 방법도 잘 모르겠네요.

**Comment by misol** [comment]
#1086 이슈에서 해결 가능할 것 같습니다.
