### ISSUE TITLE
모바일/PC 자동로그인 다중 접속시 한쪽이 로그인 풀리는 현상

### ISSUE THREAD

**Issue by KissT0XE** [xpressengine/xe-core#987]
이 부분을 일부러 이렇게 해둔 것 일수도 있지만 혹시나 해서...^^;
해당 이슈가 있을 줄 알았는데, 찾아보니 없는 것 같아 이슈 등록해봅니다.

사이트 유저가 모바일과 PC를 사용하면, 자동로그인시 둘 중 한곳에서만 자동 로그인이 되며, 다른곳에서 로그인하면 한쪽의 자동로그인이 풀립니다.
모바일, PC의 구분뿐만이 아니라 다른 기기에서 접속시에서도 마찬가지이고요. (ex. 같은 모바일이라도 모바일 기종이 다르면 자동로그인 해제됨)

modules/member/queries/deleteAutologin.xml의 7번째 라인에서

      <condition operation="equal" column="member_srl" var="member_srl" pipe="and" />

로 바꾸면 해결되긴 합니다.

**Comment by misol** [comment]
https://github.com/xpressengine/xe-core/issues/711 와 유사한 이슈입니다.

**Comment by misol** [comment]
이 기능을 추가하게 된다면, 현재 자동로그인 설정을 제어할 수 있는 페이지가 생겼으면 좋겠습니다.

자동 로그인을 체크해서 로그인 한 다음 '실수로' 로그아웃 하지 않는 경우가 발생할 수 있으니까요.

**Comment by qw5414** [comment]
사실 하나의 브라우저 하나의 기기에서 사용함에도 불구하고 휴대용 모바일기기는 잦은 유동 아이피로 로그인이 풀리는경우가 허다합니다..

그래서 이동중에 사용하시는 일부 유저들은 사용에 불편을 느끼지요..
저도 앱을 통해서 운영하는 처지이라.. 이런 부분이 너무 불편하다고 생각해요 T^T
기존에는 로그인이 유지가 되었으나 현재는 유지가 재대로 이루어 지지 않고 잇는 현실이라서요..

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.
