### ISSUE TITLE
선택적 SSL에 질문/답변 비밀번호 찾기 act도 추가

### ISSUE THREAD

**Issue by CONORY** [xpressengine/xe-core#996]
선택적 SSL에 질문/답변 비밀번호 찾기 act도 추가하여 SSL 적용되었으면 좋을 것 같습니다.

member.class.php

$ssl_actions = array('dispMemberModifyPassword', 'dispMemberSignUpForm', 'dispMemberModifyInfo', 'dispMemberModifyEmailAddress', 'dispMemberGetTempPassword', 'dispMemberResendAuthMail', 'dispMemberLoginForm', 'dispMemberFindAccount', 'dispMemberLeave', 'procMemberLogin', 'procMemberModifyPassword', 'procMemberInsert', 'procMemberModifyInfo', 'procMemberFindAccount', 'procMemberModifyEmailAddress', 'procMemberUpdateAuthMail', 'procMemberResendAuthMail', 'procMemberLeave'/*, 'getMemberMenu'*/, 'procMemberFindAccountByQuestion');

이렇게 해야  계정찾기 페이지에서 보안경고가 안 나옵니다.

**Comment by misol** [comment]
@bnu 처리된 이슈 닫아주세요! ㅎㅎ
