### ISSUE TITLE
popup_layout.html 이 모바일을 지원하지 않음

### ISSUE THREAD

**Issue by kndol** [xpressengine/xe-core#997]
javascript:popopen()을 사용하면 /common/tpl/popup_layout.html 파일을 사용하게 되는데, 이 때 모바일을 고려하지 않은 구조로 되어 있어 반응형 페이지가 모바일 상에서도 모바일이 아닌 PC 형태로 표시되어 내용이 너무 작게 표시되는 문제가 있습니다.

**Comment by bnu** [comment]
[Github 이슈 정리 계획](https://www.xpressengine.com/devlog/23147703)을 바탕으로 이슈를 종료합니다.

이 이슈의 내용이 최신 버전에서도 여전히 발생하는 문제이거나 개선되었으면 하는 내용이라면 이슈 다시 열거나 새로 작성해주시기 바랍니다.

이슈에 내용과 댓글을 유지하기위해 이 이슈를 다시 열기위해서는 아래에서 이슈를 다시 여는 간략한 내용을 남기고 'Reopen issue' 버튼을 누르시면 됩니다.

**Comment by kndol** [comment]
수정을 해봤는데, 고쳐야 할 곳이 몇 군데 있군요.

먼저 ModuleHander.class.php:406
> if($this->module_info->use_mobile != "Y")

이 라인을

> if($this->module_info->use_mobile == "N")

으로 바꿨습니다.

ajaxboard 등 일부 별도의 모바일 뷰 사용 옵션이 없는 모듈이 있으면 무조건 모바일 모드가 해제되는 문제가 있어서 임의로 바꿨습니다. 이게 다른 문제가 있을 수도 있겠네요.

common.js와 xe.js 파일 수정
> function popopen(url, target) {
> 	if(typeof(target) == "undefined") target = "_blank";
> 	if(typeof(xeVid)!='undefined' && url.indexOf(request_uri)>-1 && !url.getQuery('vid')) url = url.setQuery('vid',xeVid);
> 	// 모바일에서는 팝업 윈도 크기 자동
> 	var w = window.innerWidth > 800 ? "width=800," : "";
> 	var h = window.innerHeight > 600 ? "height=600," : "";
> 	winopen(url, target, w+h+"scrollbars=yes,resizable=yes,toolbars=no");
> }

popup_layout.html 수정
> &lt;load target="../../modules/admin/tpl/css/admin.bootstrap.min.css" usecdn="true" /&gt;
> &lt;load target="../../modules/admin/tpl/css/admin.min.css" usecdn="true" /&gt;
> &lt;load cond="$lang_type=='ko'" target="../../modules/admin/tpl/css/admin_ko.css" usecdn="true" /&gt;
> &lt;load cond="$lang_type=='en'" target="../../modules/admin/tpl/css/admin_en.css" usecdn="true" /&gt;
> &lt;div class="x popup"&gt;
>     {$content}
> &lt;/div&gt;
> &lt;script&gt;
> // 모바일에서는 팝업 윈도 크기 변경 안 함
> &lt;!--@if(!class_exists(Mobile) || !Mobile::isFromMobilePhone())--&gt;
> 	jQuery(window).load(setFixedPopupSize);
> &lt;!--@end--&gt;
>     var _isPoped = true;
> &lt;/script&gt;

communication.mobile.php 파일에 함수 추가
> 	function dispCommunicationAddFriend()
> 	{
> 		return parent::dispCommunicationAddFriend();
> 	}
> 
> 	function dispCommunicationAddFriendGroup()
> 	{
> 		return parent::dispCommunicationAddFriendGroup();
> 	}

document.mobile.php 파일 추가

> &lt;?php
> require_once(_XE_PATH_.'modules/document/document.view.php');
> class documentMobile extends documentView
> {
> 	function init()
> 	{
> 	}
> 
> 	function dispDocumentManageDocument()
> 	{
> 		return parent::dispDocumentManageDocument();
> 	}
> }

일단 이렇게 하니 자주 쓰이는 부분에서는 팝업들이 모바일 뷰로 보입니다.

**Comment by kndol** [comment]
그런데, 'Reopen issue' 버튼은 어딨나요?

**Comment by YJSoft** [comment]
@bnu 스스로 닫은 이슈가 아니라면 Reopen이 뜨지 않습니다.

**Comment by bnu** [comment]
어이쿠...
